### ISSUE TITLE
Add Default Loading circule to image url

### ISSUE THREAD

**Issue by Kakarotto22** [flet-dev/flet#1003]
Add a **ProgressRing** when image is downloading from url where image ready to display

improve an example or add paramter to do this 

Thanks !

**Comment by ndonkoHenri** [comment]
I wanted to propose this some days ago after seeing this: https://docs.flutter.dev/cookbook/images/fading-in-images
They made use of the [FadeInImage](https://api.flutter.dev/flutter/widgets/FadeInImage-class.html) to achieve that placeholder effect.

**Comment by Kakarotto22** [comment]
> I wanted to propose this some days ago after seeing this: https://docs.flutter.dev/cookbook/images/fading-in-images They made use of the [FadeInImage](https://api.flutter.dev/flutter/widgets/FadeInImage-class.html) to achieve that placeholder effect.

Thanks But how to Do this in flet ?
