### ISSUE TITLE
İmage not working

### ISSUE THREAD

**Issue by ixelizm** [flet-dev/flet#1004]
The utf-8 character problem has been resolved, but this time the image is not coming, there is an image on my login page, this is a png that was working before but it is not working now

```
self.login_page_image = Row(controls=[Image(
            src=f"/images/login_page_image.png",
            width=200,
            height=200,
            fit=ImageFit.FILL,
            border_radius=15
        )], alignment=MainAxisAlignment.CENTER)


if __name__ == "__main__":
    app(
        target=SorguPanel,
        assets_dir="assets",
        host = "0.0.0.0")
```

my image is in the images folder inside the assets folder

**Comment by FeodorFitsner** [comment]
add `page.on_error` handler to see the error:

```python
page.on_error = lambda e: print("Page error:", e.data)
```

**Comment by ixelizm** [comment]
> add `page.on_error` handler to see the error:
> 
> ```python
> page.on_error = lambda e: print("Page error:", e.data)
> ```
```
Page error: Invalid argument(s): Unsupported scheme 'tcp' in URI tcp://localhost:5000/images/login_page_image.png
```

**Comment by FeodorFitsner** [comment]
OK, remove `host = "0.0.0.0"`.

**Comment by ixelizm** [comment]
> OK, remove `host = "0.0.0.0"`.

I did but same error

**Comment by FeodorFitsner** [comment]
How to you run a Flet program?

**Comment by ixelizm** [comment]
> How to you run a Flet program?

 ``` flet app.py -r -p 5000

**Comment by FeodorFitsner** [comment]
OK, will take a look. Could be a bug.

**Comment by ixelizm** [comment]
> OK, will take a look. Could be a bug.

Thanks for helps, good luck :)

**Comment by FeodorFitsner** [comment]
so, it's not a bug after all :)

You need to run `flet` command with `--assets` option:

```
flet app.py -r -p 5000 --assets assets
```

Let me know how that worked.

**Comment by ixelizm** [comment]
> yani organizmalar bu bir bug değil :)
> 
> Seçenek `flet`ile sonuç olarak çalıştırmanız gerekir :`--assets`
> 
> ```
> flet app.py -r -p 5000 --assets assets
> ```
> 
> Bunun nasıl yapıldığını bana rehberlik ediyor.

yes this worked but when I run it on my server I try to connect with my server's ips this time this site is unreachable error
