### ISSUE TITLE
Flet does not handle URLs with redundant slashes

### ISSUE THREAD

**Issue by kkinder** [flet-dev/flet#1012]
**Description**

If a user visits a URL with two slashes, flet seems to pase the URL incorrectly and replaceState to an invalid domain.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(
        ft.Text(f"This is the path: {page.route}")
    )
    def route_change(route):
        page.add(ft.Text(f"New route: {route}"))

    page.on_route_change = route_change



if __name__ == "__main__":
    flet_path = ''
    flet_port = 8001
    ft.app(name=flet_path, target=main, view=None, port=flet_port, route_url_strategy="path")
```

**Describe the results you received:**

With the above example, visit `http://localhost:8001//foobar`. Notice the *two slashes* after the port and before the path, `//`.

If you do this, Flet will try to redirect the user to `http://foobar/`. Here it is from the debug console.

```
securityerror: Blocked attempt to use history.replaceState() to change session history URL from http://localhost:8001//foobar to http://foobar/. Protocols, domains, ports, usernames, and passwords must match.
```

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: MIT
Location: /Users/kkinder/Library/Caches/pypoetry/virtualenvs/fletend-9mHHD83p-py3.11/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

macOS 13.2 (22D49)

**Additional environment details:**

Via Poetry.

**Comment by ndonkoHenri** [comment]
> If you do this, Flet will try to redirect the user to http://foobar/. 

I just tried, but didnt notice this behaviour.
Can you please retry with the latest version?
