### ISSUE TITLE
PyInstaller 5.8.0 broke `flet pack` command on Windows

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1031]
### Discussed in https://github.com/flet-dev/flet/discussions/1028

<div type='discussions-op-text'>

<sup>Originally posted by **Ben2022-cell** February 12, 2023</sup>
The [packaging-desktop-app](https://flet.dev/docs/guides/python/packaging-desktop-app) docs talk about packaging a desktop app into an executable using flet pack command as follows -

flet pack your_program.py

But wen i execute there code , there is presenting an error, see that:
$ flet pack jartual_frame_flet.py
Please install PyInstaller module to use flet pack command: cannot import name 'decode' from 'PyInstaller.utils.win32.versioninfo' (D:\Python39\lib\site-packages\PyInstaller\utils\win32\versioninfo.py)

the PyInstaller packing i has setup finish, and updated to the lastest version.</div>

**Comment by timelic** [comment]
same issue

**Comment by FeodorFitsner** [comment]
A workaround is to downgrade PyInstaller to 5.7.0:

```
pip uninstall pyinstaller
pip install pyinstaller==5.7.0
```
