### ISSUE TITLE
Image disappears after selecting files. 

### ISSUE THREAD

**Issue by timelic** [flet-dev/flet#1034]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()

    pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
    selected_files = ft.Text()

    page.overlay.append(pick_files_dialog)
    page.add(ft.Image(src="./resources/logo.png", width=300))
    page.add(
        ft.Row(
            [
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=lambda _: pick_files_dialog.pick_files(
                        allow_multiple=True
                    ),
                ),
                selected_files,
            ]
        )
    )


ft.app(target=main)
```

**Describe the results you received:**

Just click the button to select files, and then the image disappears.

Before:

![image](https://user-images.githubusercontent.com/20257354/218442923-e0e8e40b-c530-44ef-b5cc-691564c8e302.png)

After:

![image](https://user-images.githubusercontent.com/20257354/218442967-51aef5f8-32b9-4e4e-abd7-981ca56a4b3b.png)

**Describe the results you expected:**

Image should work properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: MIT
Location: E:\ProgramData\Miniconda3\envs\md-card\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**: 

Windows11

**Additional environment details:**

Python version: 3.11

**Comment by timelic** [comment]
When I use online pictures, the image component doesn't disappear.

**Comment by iron3oxide** [comment]
For debugging purposes, could you change the src of the image to its absolute path and see if the problem persists?

**Comment by ndonkoHenri** [comment]
Can you add this line to your code somewhere in the `main`:
```python
page.on_error = lambda e: print(e.data)
```
The run your program and watch your console. If any thing is printed, show it here please.

**Comment by timelic** [comment]
I added this line `page.on_error = lambda e: print(e.data)` and its log is `Invalid argument(s): Unsupported scheme 'tcp' in URI tcp://localhost:13795/images/icon.png`. @ndonkoHenri 

When I use the absolute path of the image, the image will not disappear. @iron3oxide

**Comment by ndonkoHenri** [comment]
@FeodorFitsner, remember this issue? 🙂
@timelic I also had this issue some days ago. Don't know how to fix it though.

**Comment by timelic** [comment]
@ndonkoHenri I tried command `python index.py` and command `flet run index.py`, and the result is the same.

**Comment by FeodorFitsner** [comment]
Run it with `--assets` option:

```
flet run index.py --assets <path-to-assets-dir>
```

**Comment by FeodorFitsner** [comment]
I think implementing that would avoid a lot of confusion: https://github.com/flet-dev/flet/issues/1043
