### ISSUE TITLE
`text_align` not working

### ISSUE THREAD

**Issue by mouadessalim** [flet-dev/flet#1037]
I am trying to center a simple Text, but not working.

```py
import flet as ft

def main(page: ft.Page):
    page.fonts = {
        'SpaceGrotesk': 'SpaceGrotesk-Light.ttf'
    }
    wallet_value = ft.Text('60,2 $', font_family='SpaceGrotesk', size=60, text_align=ft.TextAlign.CENTER)
    page.add(wallet_value)

ft.app(target=main)
```

I've already tried `text_align='center'`, `text_align='CENTER'`, `text_align=ft.TextAlign('CENTER')` & `text_align=ft.TextAlign('center')`. 

My output : 

![image](https://user-images.githubusercontent.com/38190847/218580336-944c27e5-6670-42dc-9d56-003dce44634c.png)

I am also getting the same issue with `TextThemeStyle` enum and `FontWeight` enum.

My env  : I am running on windows 10, with python 3.10.9 with the last flet version (0.4.0)

**Comment by FeodorFitsner** [comment]
`Text` control itself has intrinsic size and align to the left. To make it in the middle set `page.horizontal_alignment`:

```python
import flet as ft


def main(page: ft.Page):
    page.fonts = {"SpaceGrotesk": "SpaceGrotesk-Light.ttf"}
    page.horizontal_alignment = ft.CrossAxisAlignment.STRETCH
    wallet_value = ft.Text(
        "60,2 $", font_family="SpaceGrotesk", size=60, text_align=ft.TextAlign.CENTER
    )
    page.add(wallet_value)


ft.app(target=main)
```
