### ISSUE TITLE
flet run -r generates "OSError: [Errno 48] Address already in use" on MacOS

### ISSUE THREAD

**Issue by amiramir** [flet-dev/flet#1038]
Thank you for the work on Flet. I am enjoying my experience so far.
I have been running on MacOS with felt run -r app.py. When I change and save the source for app.py flet tried to reload but emits an OSError: [Errno 48] Address already in use. The makes the hot reload less fun that it ought to be. The error is thrown in SyncLocalSocketConnection.connect when .bind() is called on the socket.

I managed to fix it by adding the following line to the both  branches of the if:
            self.__sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

I don't know if ti's needed for the UDS case since I seem to be exercising the TCP case.
Perhaps someone with some real understanding of what's going on can decide whether this is the correct solution. It's working for me and the hot reloading makes development much more fun and productive.
I'm sorry that I am not providing a patch and so forth. I don't have the chops for that yet.

Many thanks again.

**Comment by FeodorFitsner** [comment]
Try installing the latest Flet pre-release with `pip install flet --upgrade --pre` - it has a fix.

**Comment by amiramir** [comment]
Installed. Confirming that it's fixed. Thank you.

**Comment by FeodorFitsner** [comment]
👍

**Comment by JorgeAlvarez21** [comment]
This fixed it for me as well :) Thanks a lot
