### ISSUE TITLE
Standard multiline TextField behavior does not support Enter

### ISSUE THREAD

**Issue by mikaelho** [flet-dev/flet#104]
This code:
```
import flet
from flet import Page
from flet import TextField


def main(page: Page):
    page.add(TextField(max_lines=1000))
    page.update()


flet.app(target=main)
```

(On M1 Mac.)

Expected behavior:
- Pressing Enter adds a new line and expands the `TextField`.

Actual behavior:
- Pressing Enter loses control focus, new line is not added.

Other notes:
- Adding text with a new line programmatically works correctly, expanding the `TextField`.
- With `shift_enter=True`, Shift+Enter adds a new line as expected, expanding the `TextField`.

**Comment by FeodorFitsner** [comment]
Add `multiline=True`:

```python
import flet
from flet import Page, TextField

def main(page: Page):
    page.add(TextField(max_lines=1000, multiline=True))
    page.update()

flet.app(target=main)
```

For a single line TextField pressing Enter fires `on_submit` event.

**Comment by mikaelho** [comment]
Ah, of course. And then you do not need to set `max_lines` either, if you do not want a maximum. Excellent!
