### ISSUE TITLE
Scroll bar disappears on resize

### ISSUE THREAD

**Issue by ArshA03** [flet-dev/flet#1044]
Hello, 
when I resize the window on windows desktop, the scroll bar of the column or row disappears most of the time. It doesn't happen on the web page but only desktop!

**Comment by ndonkoHenri** [comment]
Can you show a little video please?
Then share some test code to reproduce the issue.

**Comment by ArshA03** [comment]
Hi, my bad, it was resolved. However, I did not quite understand why it happened in the first place.
