### ISSUE TITLE
Integer sliders are not possible, float sliders can have ugly values when used for integers

### ISSUE THREAD

**Issue by xylix** [flet-dev/flet#1045]
**Please Describe The Problem To Be Solved**

When using sliders with a pretty reasonable range of values and steps, for example following code:
```python
import flet as ft
def main(page):
    page.add(
        ft.Text("Slider with value:"),
        ft.Slider(value=0.3),
        ft.Text("Slider with a custom range and label:"),
        ft.Slider(min=0, max=100, divisions=100, label="{value}%"))
ft.app(target=main)
```
Which modifies Flet's own slider example by specifying 100 divisions, there appears a problem: Because the slider value is a float, some values like 56 are not represented exactly. This is a both a problem if user expects integer values out of a slider with 100 steps and 100 values (e.g. integer values from 0 to 100), and also kind of ugly in the interface.

<img width="799" alt="Screenshot 2023-02-15 at 11 04 43" src="https://user-images.githubusercontent.com/13387304/218982506-18cf5113-dddf-442a-b1ba-351f13971b0f.png">

**(Optional): Suggest A Solution**

Possibility to specify integer type and/or rounding function in the slider, so that both the {value} in the label and the sliders data value could be configured to be integers by user?

**Comment by FeodorFitsner** [comment]
A new `round` property has been added to `Slider` control which specifies how many decimal points slider value should be rounded to before displaying in the label. Default value is `0` which means the value is rounded to an integer.

You could give it a try with Flet pre-release (`pip install flet --upgrade --pre`).

**Comment by xylix** [comment]
Thank you for the quick fix! This seems to fit our need, and we are testing it out.
