### ISSUE TITLE
Feature Request: More session info

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1053]
**Please Describe The Problem To Be Solved**

When logging or rate limiting, or simply debugging which user is doing what, we need more information about the session:  IP address, browser info etc

**(Optional): Suggest A Solution**

I believe Flutter already provides this information.  I could be added to a Page variable, put into the page session data or better:

Flask provides an `from flask import g` and `g` is a dict that we can put anything in we want and its available anywhere by simply importing, you don't have to pass a `page` around to get it.  This would be the optimal solution to have session global data rather than using page.  in Flask g is guaranteed to be session specific.

**Comment by gbrandt** [comment]
Another application is to get the timezone of the browser so that I have the local time of the user, not the app which can be running on a server in a very different timezone

**Comment by FeodorFitsner** [comment]
The feature can be tried with pre-release version of Flet: `pip install flet --upgrade --pre`.
