### ISSUE TITLE
Double clicking ```flet.WindowDragArea``` causes window to expand even when ```page.window_frameless = True``` and/or ```page.window_maximizable = False```

### ISSUE THREAD

**Issue by JasonSettings** [flet-dev/flet#1056]
**Description**

Setting ```page.window_frameless = True``` and using ```flet.WindowDragArea``` instead of native title bar to move page around is somewhat awkward because Windows "expand window by double clicking title bar" behaviour is still in effect.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.window_bgcolor = ft.colors.TRANSPARENT
    page.bgcolor = ft.colors.TRANSPARENT
    page.window_frameless = True
    
    page.add(
        ft.WindowDragArea(
            ft.Container(
                width=300,
                height=300,
                bgcolor=ft.colors.BROWN_700,
                border_radius=ft.border_radius.all(20),
                padding=20,
                alignment=ft.alignment.center,
                content=ft.Column(
                    controls=[ft.Text('Double click here', size=28)],
                    alignment='center',
                ),
            )))
    page.update()


if __name__ == '__main__':
    ft.app(target=main)
```

**Describe the results you received:**

Double clicking anywhere inside of drag area causes window to enter this weird pseudo-maximized state - the expand animation plays, the window moves to upper left corner (or maybe center) and locks in this "maximized" state until you drag it a bit. 
Also placing the window near display border invokes Windows expand/layout manager.

**Describe the results you expected:**

Would be cool to fix (or I guess block) this behaviour. Not sure if it is actually possible.

**Flet version**:

```
Name: flet
Version: 0.4.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: MIT
Location: C:\Python Installs\Venvs\venv_main\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
```

**Operating system**:

Windows 11 22H2

**Comment by FeodorFitsner** [comment]
I think we could add `maximizable` property to `WindowDragArea`, so double-click could be enabled/disabled programmatically - how does it sound?

**Comment by JasonSettings** [comment]
Any method you deem convenient and logical will suffice (I'm not really in a position to discuss details with a dev)! In my opinion, the option to turn off/block maximization completely is needed for drag area.
