### ISSUE TITLE
flet pack failing on Windows

### ISSUE THREAD

**Issue by thetrotfreak** [flet-dev/flet#1064]
**Description:**
`flet pack` fails after throwing a `TypeError`

**Code example to reproduce the issue:**

```python
import flet


def main(page: flet.Page):
    page.add(flet.Text(value="Hello World!"))


if __name__ == "__main__":
    flet.app(target=main)
```

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/45330487/219970388-11302bef-a089-4701-99e8-8756d46957f4.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.4.1
```

**Operating system**:
```
Windows 11
Version 22H2
```

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
What version of `pyinstaller` do you have?

**Comment by thetrotfreak** [comment]
@FeodorFitsner, `PyInstaller` version `5.8.0`

**Comment by Abdur-rahmaanJ** [comment]
Me Windows 10, `pyinstaller==5.8.0` `flet==0.4.1`, python3.10 

```
Updating Flet View version info C:\Users\appinv\AppData\Local\Temp\34f62eeb-8253-4eb9-a70a-69b204fd18de\flet\flet.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\appinv\Documents\code\x\venv\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\appinv\Documents\code\x\venv\lib\site-packages\flet\cli\cli.py", line 79, in main
    args.handler(args)
  File "C:\Users\appinv\Documents\code\x\venv\lib\site-packages\flet\cli\commands\pack.py", line 165, in handle
    version_info_path = update_flet_view_version_info(
  File "C:\Users\appinv\Documents\code\x\venv\lib\site-packages\flet\__pyinstaller\win_utils.py", line 62, in update_flet_view_version_info
    vs = decode(exe_path)
  File "C:\Users\appinv\Documents\code\x\venv\lib\site-packages\PyInstaller\utils\misc.py", line 218, in decode
    bom, raw = BOM_RE.match(raw).groups()
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by Abdur-rahmaanJ** [comment]
Works with `pyinstaller==5.6.2`

**Comment by thetrotfreak** [comment]
@Abdur-rahmaanJ, I tested against `PyInstaller v5.7.0`, and `flet pack` worked. Guess something changed (a _breaking change_ perhaps?) in **PyInstaller** when it went to `5.8.0` from `5.7.0`

**Comment by FeodorFitsner** [comment]
@thetrotfreak what Python version do you have?

**Comment by thetrotfreak** [comment]
It's Python `3.11.2`

**Comment by thetrotfreak** [comment]
@FeodorFitsner pardon for my late responses, it's like 4.30 in the morning over here. This issue didn't let me sleep.

Anyways, I referred to this [commit](https://github.com/pyinstaller/pyinstaller/commit/f57e15a), thanks to #1060 and from what I could understand, I tinkered with [this file](https://github.com/flet-dev/flet/blob/13f7d4599d0a26936ee8b51e45ad3f465736f09d/sdk/python/packages/flet/src/flet/__pyinstaller/win_utils.py#L62) and tried the following:

**Possible fix:**

- I used the `read_version_info_from_executable()` from `PyInstaller.utils.win32.versioninfo` at [`Line 62`](https://github.com/flet-dev/flet/blob/13f7d4599d0a26936ee8b51e45ad3f465736f09d/sdk/python/packages/flet/src/flet/__pyinstaller/win_utils.py#L62) instead of the `decode()` from `PyInstaller.utils.misc`. 

**Reason:**
- Quoting the docstring:
> """
Read the version information structure from the given executable's resources, and return it as an instance of `VSVersionInfo` structure.
"""
- This is, I believe, exactly what you wanted with that **Line 62** but was failing because of the mismatching of `str` and `bytes` type.
- The `VSVersionInfo` structure returned has the `kids` **instance attribute** that's required from [`Line 72`](https://github.com/flet-dev/flet/blob/13f7d4599d0a26936ee8b51e45ad3f465736f09d/sdk/python/packages/flet/src/flet/__pyinstaller/win_utils.py#L72) onwards.

Hope it helps in the fix. You might want to have a look.

**Comment by thetrotfreak** [comment]
Tried on the following setup:

- **flet**: `0.4.1`
- **pyinstaller**: `5.8.0`
- **python**: `3.11.2`
- **OS**: `Windows 11 22H2`

And `flet pack <script>` worked.

> Though I can't vouch for this fix. I merely changed a couple of lines and **did not** run any test(s). Somewhat new to these sort of stuff.

**Comment by thetrotfreak** [comment]
Thanks for the fix!

**Comment by FeodorFitsner** [comment]
Alright, you can install the latest pre-release (`pip installer flet --upgrade --pre`) to test the fix.
