### ISSUE TITLE
Improve user ability to control logging

### ISSUE THREAD

**Issue by xylix** [flet-dev/flet#1072]
**Please Describe The Problem To Be Solved**

I was looking for ways to control the verbosity of a running Flet application.

By doing greps from the source code I found these variables https://github.com/flet-dev/flet/blob/f261bfe619943ee7ba4cae1b90011850b03411f7/server/config/config.go#L18 which can be used to pass a log file or a loglevel to the Go library logrus.

I also found out that Flet uses Python's logging module directly for its Python side logging, like can be seen here: https://github.com/flet-dev/flet/blob/a151f61ca965bc0c6e247147369ac9a047afa203/sdk/python/packages/flet/src/flet/flet.py#L128

 
**(Optional): Suggest A Solution**

### For Python logging

It would be preferable to use a logger object:
`logger = logging.getLogger('my_module_name')`  or `logger = logging.getLogger(flet.__name__)` (This can be done in one file and imported elsewhere in the project, or initialized separately in different files.)

This would enable library consumers to do things like this to control Flet log level:
`logging.getLogger(flet.__name__).setLevel(logging.WARNING)`
Currently it is quite difficult to silence Flet's logging due to using the Python root logger directly.

Python's own docs / tutorial for the topic can be found here: https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial and they formulate their recommendation like this:

```
Note It is strongly advised that you do not log to the root logger in your library. Instead, use a logger with a unique and easily identifiable name, such as the __name__ for your library’s top-level package or module. Logging to the root logger will make it difficult or impossible for the application developer to configure the logging verbosity or handlers of your library as they wish.
```

### For Go logging

Would be useful to document these and the allowed values of FLET_LOG_LEVEL variable (is it ["debug", "info", "warning", "debug", "panic", "fatal"]? That's what I noticed in the Go library's examples).

And also document the existence of the `FLET_LOG_TO_FILE` environment variable and what it does.

### For logging docs in general
Perhaps the Flet documentation site could have a guide under "Python guides" for how to control logging.

**Comment by xylix** [comment]
There was a related comment here to my Python suggestion: https://github.com/flet-dev/flet/issues/273#issuecomment-1236542586 that I found while trying to search for related issues in the repo.

**Comment by FeodorFitsner** [comment]
Sounds right - will refactor logging to use a named logger instead. Thank you for the suggestion!

**Comment by FeodorFitsner** [comment]
@xylix Could you please take a look at this draft: https://0-5-0-docs.flet-website.pages.dev/docs/guides/python/logging
Would you have something to change/add or its fine?

**Comment by xylix** [comment]
@FeodorFitsner Thank you, that looks good to me!
