### ISSUE TITLE
Move AnimationValue, ClipBehaviour, ClipbehaviorString, OffsetValue, ResponsiveNumber, RotateValue, ScaleValue out of flet_core.types

### ISSUE THREAD

**Issue by ItsCubeTime** [flet-dev/flet#1083]
👋I feel the mentioned types should be exposed under the flet module (either directly or under a parent submodule like `flet.styling.ClipBehaviour` or directly under flet like `flet.ClipBehavior`) as they are useful for type hinting when creating userControls.

Currently they are accessed like:
```py
from flet_core.types import (
    AnimationValue,
    ClipBehavior,
    ClipBehaviorString,
    OffsetValue,
    ResponsiveNumber,
    RotateValue,
    ScaleValue,
)
```

I would also like to thank you for the recent overhaul to the way you import flet objects.

**Comment by ndonkoHenri** [comment]
You can make a PR proposing these changes...
`ClipBehaviour ` is already there I think.

**Comment by ItsCubeTime** [comment]
Eyyy, thanks @FeodorFitsner !
