### ISSUE TITLE
`NavigationDrawer` control

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1089]

**Comment by ndonkoHenri** [comment]
Dup https://github.com/flet-dev/flet/issues/164

**Comment by xtream-club** [comment]
Hello. Is this controller sold in the next update? thank you

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/navigationdrawer

**Comment by Dedoque** [comment]
how to switch or pass data to switch route to event?
