### ISSUE TITLE
page.views.append cannot scroll vertical

### ISSUE THREAD

**Issue by bobwatcherx** [flet-dev/flet#1109]
i implemented page in fletdan sata use page.scroll ="always" and column(scroll="always") but it doesn't make page scroll vertically

my code sample
def main(page:Page):
	mylogin = MyLogin()
	employee = EmployePage()
	page.scroll = "always"

	page.vertical_alignment="center"
	page.horizontal_alignment="center"
	

	def route_change(route):
		page.views.clear()
		page.scroll="always"
		page.views.append(
            View(
                "/",
                [
                mylogin
                ],
            )
	        )
		if page.route == "/employee":
			if page.session.get("login") == None:
				page.go("/")
			else:
				page.views.append(
	                View(
	                    "/employee",
	                    [
	                    employee,
                              Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")
Text("sample for scroll")

	                    
	                    ],
	                )
	            	)
		page.update()

	

	page.on_route_change = route_change
	page.go(page.route)

**Comment by FeodorFitsner** [comment]
Close as dup of https://github.com/flet-dev/flet/discussions/1100
