### ISSUE TITLE
Invoking ```flet.AlertDialog``` causes frame angles to become visible again ( ```page.bgcolor``` ```page.window_bgcolor``` set to transparent, ```page.window_frameless = True``` )

### ISSUE THREAD

**Issue by JasonSettings** [flet-dev/flet#1110]
**Description**

"Shadow" effect that happens when ```flet.AlertDialog``` pops up causes frame's straight angles to become visible again while ```page.bgcolor = ft.colors.TRANSPARENT```, ```page.window_bgcolor = ft.colors.TRANSPARENT``` , ```page.window_frameless = True```

**Describe the results you received:**

Ugly straight angles. Shape and size depends on frame width/height and alignment of 'main container' (in my particular case).

![dialog_corners_shadow](https://user-images.githubusercontent.com/107097079/221758339-b8dd01d0-42ae-4627-a966-a350860216c0.png)

**Describe the results you expected:**

Doesn't look very pretty to me. I don't want anything past my cute rounded corners, obviously.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Python\Venvs\main_venv\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
```

**Operating system**:

Windows 11 22H2

**Comment by FeodorFitsner** [comment]
Could you provide the code to reproduce the issue?
