### ISSUE TITLE
Using Row([GridView]) inside build() results in GridView not showing up

### ISSUE THREAD

**Issue by aetherealtea** [flet-dev/flet#1117]
**Description**

While trying to pass `GridView` through `build()` functions of custom classes and placing it inside a `Row`, `GridView` refuses to show up.

Code sample:

```
import flet as ft

class Thing(ft.UserControl):

    def build(self):
        self.view = ft.GridView(
            runs_count = 5
        )
        for i in range(0, 60):
            self.view.controls.append(
                ft.Text(f"Text {i}")
            )
        return self.view
    
class App(ft.UserControl):

    def build(self):
        self.view = ft.Row([Thing()])
        return self.view
    
def main(page: ft.Page):
    app = App()
    page.add(app)

ft.app(target=main)
```

Replacing `Row` with `Column` works fine, as well as replacing `GridView` with `ListView`. The problem is specific just for the aforementioned particular combination for some reason.

Any tips or workarounds to solve the issue are highly appreciated. 

**Flet version (`pip show flet`)**:

```
0.4.2
```

**Operating system**:

```Windows 11 Home 22H2```

**Comment by FeodorFitsner** [comment]
As `ft.UserControl` is based on `ft.Stack` you have to add `self.expand = True` to allow it taking all available space for `ft.GridView`.

A working code:

```python
import flet as ft


class Thing(ft.UserControl):
    def build(self):
        self.expand = True
        self.view = ft.GridView(runs_count=5)
        for i in range(0, 60):
            self.view.controls.append(ft.Text(f"Text {i}"))
        return self.view


class App(ft.UserControl):
    def build(self):
        self.view = ft.Row([Thing()])
        return self.view


def main(page: ft.Page):
    app = App()
    page.add(app)


ft.app(target=main)
```
