### ISSUE TITLE
request for flets . is there any UI Builder drag and drop feature like FLUTTERFLOW . thanks

### ISSUE THREAD

**Issue by bobwatcherx** [flet-dev/flet#1118]
Is there a way to drag and drop UI Builder like FLUTTERFLOW. In flet . Hopefully there is for the next release . It will really like

**Comment by iron3oxide** [comment]
Have a look at https://github.com/SKbarbon/Flet_StoryBoard. It's not quite ready yet and it's a third-party project, but it's probably what you're looking for.

**Comment by FeodorFitsner** [comment]
Yes, we plan to develop drag-n-drop designer for Flet similar to FlutterFlow. "FletFlow"? :)

Closing in favor of https://github.com/flet-dev/flet/issues/124

**Comment by OtherwisePitt** [comment]
any news?
