### ISSUE TITLE
How can I align the Radiogroup centrally in AlertDialog?

### ISSUE THREAD

**Issue by dvd1221** [flet-dev/flet#1126]
cf_dlg = ft.AlertDialog(
        modal=True,
        title=ft.Text("Выберите коэффициент"),
        content=image_table,
        actions=[ft.Container(
            content=ft.RadioGroup(
                content=ft.Column([
            ft.Radio(value="A", label="A"),
            ft.Radio(value="B", label="B"),
            ft.Radio(value="C", label="C")
        ])))],
        actions_alignment=ft.MainAxisAlignment.CENTER,
        shape=ft.RoundedRectangleBorder(radius=5),
    )

![alignment](https://user-images.githubusercontent.com/126869058/222694221-7a7a253f-391a-4e66-b382-4b5d1a0883f8.jpg)

**Comment by ndonkoHenri** [comment]
Can you trying setting the horizontal alignment property of the column in the radio group content to "center"?

If it doesn't work, then I think you could wrap that column in a Row, then set the row's alignment property to "center".

Let me know what worked or not.

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/column#horizontal_alignment

https://flet.dev/docs/controls/row#alignment

**Comment by dvd1221** [comment]
Thanks, second option works!
