### ISSUE TITLE
Add `data` property to `DataRow`

### ISSUE THREAD

**Issue by DavMelchi** [flet-dev/flet#1139]
Hi ,
Simple use case would be the assignment of an invisible custom id or any invisible data that would be retrieved `on_event` .
Thanks.

**Comment by FeodorFitsner** [comment]
The property is already there as `DataRow` is inherited from `Control`. It's just not in `DataRows`'s constructor.

**Comment by ndonkoHenri** [comment]
close and perhaps remove label?

**Comment by FeodorFitsner** [comment]
Let's keep it open to remember to add it constructor.

**Comment by FeodorFitsner** [comment]
Can try the fix in Flet pre-release: https://pypi.org/project/flet/0.6.0.dev1310/

**Comment by DavMelchi** [comment]
Works flawlessly...Thank you @FeodorFitsner .
