### ISSUE TITLE
ft.Image - Images don't display sometimes in browser version but work fine in app version. 

### ISSUE THREAD

**Issue by madeofpendletonwool** [flet-dev/flet#1147]
**Description**

Images in the web version of Flet are extremely hit or miss and more often than not do not work. Whereas they do work in the app version. I hope there's not already a report for this. I did look through the issues and didn't see one. I pasted some code below of an example. 
**Code example to reproduce the issue:**

```python
# Various flet imports
import flet as ft
from flet import *
from flet import AppBar, ElevatedButton, Page, Text, View, colors, icons, ProgressBar, ButtonStyle, IconButton, TextButton, Row

def main(page: ft.Page):

    text1 = ft.Text('Image With issue below')
    text2 = ft.Text('Image Without issue below')

    imageissue = ft.Image(src='https://imgv3.fotor.com/images/blog-cover-image/part-blurry-image.jpg', width=150, height=150)
    imagefine = ft.Image(src='https://cdn.changelog.com/uploads/covers/practical-ai-original.png?v=63725770374', width=150, height=150)


    # Create Initial Home Page
    page.add(
        text1,
        imageissue,
        text2,
        imagefine
    )
# Browser Version
ft.app(target=main, view=ft.WEB_BROWSER)
# App version
# ft.app(target=main, port=8034)
```

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/22776262/223219143-117afcba-36f6-4cf3-af25-a42399883423.png)

**Describe the results you expected:**
![image](https://user-images.githubusercontent.com/22776262/223219326-5f2ede09-61d3-4a0b-98f9-d739db3d2c27.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue occurs pretty much everywhere as far as I've been able to tell. I've tried on windows, linux, in docker, different browsers, chrome and firefox, 

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/user/.local/lib/python3.10/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
```

**Operating system**:

Linux - Kubuntu 22.04

**Comment by FeodorFitsner** [comment]
There is no magic, as always :)

While running the app in browser I'm seeing this error in the console of Dev Tools:

```
Access to XMLHttpRequest at 'https://imgv3.fotor.com/images/blog-cover-image/part-blurry-image.jpg' from origin 'http://127.0.0.1:50465' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

![image](https://user-images.githubusercontent.com/5041459/223285368-629e9f4d-46ab-406b-9c40-5ab1b86ea92d.png)

Running as a desktop app obviously works as desktop ignores CORS policy.

**Comment by ErikKalkoken** [comment]
I stumbled over this too. It would maybe be a good idea to put a note about this is the official docs? 
Flet is producing an explanatory log message though, which was very helpful.

As workaround I ended up downloading the images locally with caching. Again, several different ways to go about it. Since my images where rather small I chose to store the image binaries in my cache and include them as base64 string:

Here is some example code. I am using `diskcache` for caching:

```python

def main(page: ft.Page):
    ...
    page.add(ft.Image(src_base64=fetch_image(url)))
    ...

def fetch_image(url: str) -> str:
    """Fetch image for given URL and return as base64 string. With caching."""
    key = "image-" + base64.b64encode(url.encode("utf-8")).decode("utf-8")
    with Cache() as cache:
        data: Optional[bytes] = cache.get(key)  # type: ignore
        if not data:
            logger.info("Download image from url: %s", url)
            r = requests.get(url)
            r.raise_for_status()
            data = r.content
            cache.set(key, data, expire=IMAGES_MAX_AGE_HOURS * 3600)
    encoded = base64.b64encode(data).decode("utf-8")
    return encoded
```

**Comment by madeofpendletonwool** [comment]
I actually did the same! Great minds think alike! I built a simple caching server with flask to pull the images. Great workaround!
