### ISSUE TITLE
Feature: right click,mouse wheel support

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#115]
In web/desktop client support for right click and mouse wheel would be helpful. Adding custom menu options with native os controls.

**Comment by YouJiacheng** [comment]
+1 for right click

**Comment by ndonkoHenri** [comment]
upvote

**Comment by YouJiacheng** [comment]
I checked flutter document and flet source, and I found that it is simple to add right click support to ink = False case, with onSecondaryTapDown of GestureDetector. But if ink = True, there is not onSecondaryTapDown for InkWell.

**Comment by YouJiacheng** [comment]
Some investigation about nesting GestureDetector and InkWell: https://stackoverflow.com/a/73927358/16613821

**Comment by FeodorFitsner** [comment]
Thank you, will take a look.

**Comment by YouJiacheng** [comment]
right click should be closed by #459 
mouse wheel should be replaced by #354
