### ISSUE TITLE
Container in Container, with both having an on_click event=, both get clicks

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1154]
If I create two containers that both have click events and place one container inside the other, clicking gives both containers the click event most times.  My expectation is that since the inner container is clicked on the outer container should not receive the event.  (respect Z order)

- clicking quickly in the demo program below prints `red red red red`
- clicking normally in the demo program below prints `red blue red blue red blue`
- in my app I also sometimes get `blue red` so I cannot keep a flag to stop the second click action

expectation is that a lower z order container should not receive the click event

```python
def main(page: ft.Page):
    page.add(
        ft.Container(
            ft.Container(
                ft.Text("Inner"),
                bgcolor=ft.colors.RED,
                on_click=lambda event: print("click red")
            ),
            width=400,
            height=400,
            bgcolor=ft.colors.BLUE,
            on_click=lambda event: print("click blue")
        )
    )

ft.app(target=main)
```

I see `red red red red` when clicking fast (all on separate lines of course)
I see ` red blue red blue red blue` when clicking slowly
I see the occasional `blue red` but this small demo app does not seem to do that

I expect to see only `red red red red` or at worst a consistent `red blue red blue` so that I can keep a flag to ignore the blue click in my app

This is the output on my tests

```
click red
click blue
click red
click red
click red
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click red
click red
click red
click red
click red
click red
click red
click blue
click red
click red
click red
click blue
click red
click red
click red
click red
click red
click red
click blue
click red
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click blue
click red
click red
click red
click blue
click red
click blue
click red
click blue
click red
click red
click red
click red
click red
click blue
click red
click blue
```

order seems somewhat random in my app

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/gregor.brandt/Documents/Startbridge/web-app2/fe_env/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```
I tried with --pre as well with the same result

**Operating system**:

MacOS 13.2.1

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Does it look like the same issue: https://github.com/flutter/flutter/issues/14417

**Comment by gbrandt** [comment]
I am not certain, as I do not get the ripples

**Comment by gbrandt** [comment]
This still occurs in 0.7.4

**Comment by FeodorFitsner** [comment]
It hasn't been fixed yet.

**Comment by gbrandt** [comment]
Yes, I was basically updating the ticket since Flutter was updated, just for safety

**Comment by gbrandt** [comment]
The same issue occurs by simply adding an `on_hover` event to the container, it does not need to be a on_click

**Comment by gbrandt** [comment]
more info: If two layered containers both have on click, sometimes both on_clicks are triggered, sometimes one.

**Comment by ndonkoHenri** [comment]
Just from trying both and the expected behaviour occurs.

Please give the latest Flet version a try.
