### ISSUE TITLE
ubuntu20.04  Failed to start Flutter renderer: No GL implementation is available

### ISSUE THREAD

**Issue by liziliang123** [flet-dev/flet#1155]
ubuntu20.04  Failed to start Flutter renderer: No GL implementation is available

**Comment by FeodorFitsner** [comment]
Take a look at these two issues to see if anything helps to resolve it:
https://github.com/flutter/flutter/issues/106941
https://github.com/flutter/flutter/issues/76178

**Comment by panzhoutao** [comment]
don't work
