### ISSUE TITLE
Placement of FloatingActionButton in Flutter Widget

### ISSUE THREAD

**Issue by JayKyne** [flet-dev/flet#1156]
The placement of the FloatingActionButton should be at the bottom right like in the first screenshot. Here flet is running on desktop.
Using the flet widget in a flutter app, running on android, the button is placed at the top (second screenshot).

![image](https://user-images.githubusercontent.com/63902630/223685798-d38034ab-00bd-4a9e-9e1c-6d1a7efee935.png)
![flutter](https://user-images.githubusercontent.com/63902630/223687574-317fb56a-7242-4007-96ee-a64272bb7048.jpg)

**Comment by FeodorFitsner** [comment]
How do you test it on Android? Is it web or native app?

**Comment by JayKyne** [comment]
Flet is running as a webserver.
