### ISSUE TITLE
DataTable: No error if the number of columns and cells doesn't match

### ISSUE THREAD

**Issue by m0555** [flet-dev/flet#1175]
Please could you throw an error in the case that the number of columns in the heading row and cells per row are not the same.
I got only a grey area where the datatable should be. 
(Version 0.5.0.dev1211)

Thanks

**Comment by ndonkoHenri** [comment]
Should be solved in the latest version:
https://github.com/flet-dev/flet/blob/fdf54b6948b0b4e985dd736475e427c386321cbe/sdk/python/packages/flet-core/src/flet_core/datatable.py#L458-L461
