### ISSUE TITLE
Caps Lock not working on second press

### ISSUE THREAD

**Issue by JorgeAlvarez21** [flet-dev/flet#1176]
Hi I'm working on a simple text editor. The Caps Lock event on the ft.KeyboardEvent is not working well.
It sends the event once pressed but if pressed again to deactivate it, it does not send it.

1st press -> Key caps event
2nd press -> Does Nothing
3rd press -> Key caps event
4th press -> Does Nothing
.
.

I am using an M1 Macos computer - Ventura 13.1

Here is some sample code:

import flet as ft

```
def main(page: ft.Page):
    key_caps = False

    def keyboard_events_handler(e: ft.KeyboardEvent):
        nonlocal key_caps
        print(e.key)

        if e.key == "Caps Lock":
            key_caps = True if not key_caps else False
            print("Caps Lock Active:  ", key_caps)
            return
        if key_caps:
            key = e.key
        else:
            key = e.key.lower()

        if e.shift:
            if key_caps:
                key = e.key.lower()
            else:
                key = e.key

    page.on_keyboard_event = keyboard_events_handler

    x = ft.Container(
        height=300,
        bgcolor="black",
        border=ft.border.all(1, "white"),
        width=380,
    )
    page.add(x)


ft.app(
    target=main,
)
```

**Comment by ndonkoHenri** [comment]
I tried the code and had the following:
![image](https://github.com/flet-dev/flet/assets/98978078/549a30d1-fd75-4856-b8ed-9b7376541a14)

I don't seem to get what you mean..
Can you better explain?
