### ISSUE TITLE
Add window width and height

### ISSUE THREAD

**Issue by StanMathers** [flet-dev/flet#118]
Flet supports 'page.window_width' and 'page.window_height' for Desktop only. When writing stuff, I often used 'page.window_width' to match the size of some widgets to the page width (widget sizes were changing by a function called by page.on_resize).
This technique works perfectly fine for Desktop but it would be pretty good to add a similar function to Browser view, just like Javascript 'window.innerHeight' and 'window.innerWidth', or 'screen.height' and 'screen.width'

**Comment by FeodorFitsner** [comment]
It's `page.width` and `page.height`: https://flet.dev/docs/controls/page#width
