### ISSUE TITLE
Not install pyodbc

### ISSUE THREAD

**Issue by hoangde2811** [flet-dev/flet#1180]
Dear developer!!!
I am not able to install pyodbc to connect from SQLALchemy to SQL Server and I have attached an image link about the error but I use pip3 install pyodbc and it installs normally. Please help me to install it. 
Sincerely thank you.
(https://user-images.githubusercontent.com/87251371/225245898-b8679d3d-f6ce-47b8-93da-023f99eadbe1.png)

**Comment by mikaelho** [comment]
This is not a flet issue, but the fact that you are trying to install an incompatible library to be used with pyodide. Please close this issue and start a discussion with pyodide developers.
