### ISSUE TITLE
page error Converter Function Error: Null check operator used on a null value

### ISSUE THREAD

**Issue by QiCodeCN** [flet-dev/flet#1182]
I write a myself UserControl for updarge page。there new version the dialog will show，but try click any inner button it will error:
any some suggest,thank you.
![20230316-154119](https://user-images.githubusercontent.com/52949189/225548673-bac943d8-4cad-4311-8007-b0b61c323184.jpg)

**Comment by Zvetkov** [comment]
@QiCodeCN you haven't provided code or a good repro for the issue, please add details if you want somebody to debug this
