### ISSUE TITLE
all controls should be support keyboard binding method

### ISSUE THREAD

**Issue by shaohaiyang** [flet-dev/flet#1188]
For example, it would be nice if ft.ElevatedButton(text="press A") could bind the 'A' key shortcut. thanks a lot.

**Comment by ndonkoHenri** [comment]
You have to bind it yourself for now. 
Here is a guide: https://flet.dev/docs/guides/python/keyboard-shortcuts

**Comment by shaohaiyang** [comment]
> You have to bind it yourself for now. Here is a guide: https://flet.dev/docs/guides/python/keyboard-shortcuts

Thank you very much for your reply, and there is another problem, I can't set the delay time of the keyboard, so I can't use the keyboard to input 10 or  100 numbers.  :(

**Comment by ndonkoHenri** [comment]
What do you mean by delay time?

**Comment by shaohaiyang** [comment]
> What do you mean by delay time?
![image](https://user-images.githubusercontent.com/2763056/226153542-f923fc9a-673f-4427-b86b-bd61ae9efd51.png)

I create some ElevatedButton with numbers , and also added  on_keyboard_event on page , but when i press keyboard 10, then the e.key value  was display  1 and  0  one by one , so i hope a  delay time for fixed this.

**Comment by shaohaiyang** [comment]
Hi all, I have solved this problem by using a[ delayed dictionary](https://github.com/mailgun/expiringdict) to save the keypress, the code as below

```
from expiringdict import ExpiringDict
cache = ExpiringDict(max_len=1, max_age_seconds=0.5)

def on_keypress(e):
  data = e.control.data if e.control.data else e.key.lower()
  if cache.get("key"):
    data = cache.get("key") + data
  else:
    cache["key"] = data
```
