### ISSUE TITLE
`Map` control

### ISSUE THREAD

**Issue by harunkurtdev** [flet-dev/flet#1193]
**Can you add a map for the flet, can you support a widget that can show points on it?**

Can you provide support for a widget that can show gps locations on it and also move on the map?

[#1122](https://github.com/flet-dev/flet/pull/1122)
I created a widget but not merged.

**Comment by FeodorFitsner** [comment]
Sorry, looking into that right now.

**Comment by FeodorFitsner** [comment]
https://pub.dev/packages/flutter_map

**Comment by GidroN** [comment]
Is this feature still not released?

**Comment by MrGoosee** [comment]
When will the new version with the map feature be released approximately?

**Comment by FeodorFitsner** [comment]
Early next week.

**Comment by MrGoosee** [comment]
Thank you very much for the answer

**Comment by Vinicios-Developer** [comment]
Has this feature been released yet?

**Comment by GidroN** [comment]
> Has this feature been released yet?

Still not released, but already in [pre-release](https://pypi.org/project/flet/0.23.0.dev2956/).
