### ISSUE TITLE
Dropdown bgcolor don't work during displaying the options ?

### ISSUE THREAD

**Issue by ewribeiro** [flet-dev/flet#1195]
### Discussed in https://github.com/flet-dev/flet/discussions/1190

<div type='discussions-op-text'>

<sup>Originally posted by **ewribeiro** March 17, 2023</sup>
### Question

How to change the background color of a dropdown option selection menu?
I used bgcolor and color but it didn't affect the selection menu. After clicking on the option the colors are as expected, but not while displaying the options. This part displayed in gray color I want to leave in green color.
![image](https://user-images.githubusercontent.com/19910316/226011334-2a3851cb-fda1-4c32-bdcb-63ae841f58a5.png)
![image](https://user-images.githubusercontent.com/19910316/226011470-d09e6509-5472-458a-ad89-aa121146a1ab.png)

https://user-images.githubusercontent.com/19910316/226013578-12beae90-9cf8-4811-94f2-ed22f55225ef.mp4

### Code sample

```python
import flet as ft


async def main(page: ft.Page):
    page.bgcolor = '#024135'
    dd = ft.Dropdown(
        width=100,
        bgcolor='#024135',
        color='white',
        options=[
            ft.dropdown.Option(text='Option 1'),
            ft.dropdown.Option(text='Option 2'),
        ],
    )
    await page.add_async(dd)


ft.app(target=main)
```

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

**Comment by Zvetkov** [comment]
Also mentioned in #1181

**Comment by ndonkoHenri** [comment]
A pre-release with the fix concerning this issue is now available. Try it and report if you face any further issues or have any questions:
```bash
pip install flet --pre
```
