### ISSUE TITLE
Feature: support flutter animation/tweening

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#120]
Implicit animations:

* [x] AnimatedContainer: alignment, width, height, bgcolor, gradient, padding, margin, border_radius, border
* [x] AnimatedOpacity - all visible controls
* [x] AnimatedSize - all controls, check `Image` for special case.
* [x] AnimatedRotation - all controls
* [x] AnimatedScale - all controls
* [x] AnimatedPositioned - all controls
* [x] AnimatedSlide - all controls
* [x] AnimatedSwitcher (separate control)

Curves: https://api.flutter.dev/flutter/animation/Curves-class.html

So much of UX is in UI animations....fading in controls, sliding panels, etc.

Flutter has rich support for this and Flet should too

Good starting points would be:
- position
- size
- rotation
- scale
- opacity / color

https://api.flutter.dev/flutter/animation/animation-library.html
https://api.flutter.dev/flutter/animation/Tween-class.html
https://docs.flutter.dev/development/ui/animations
https://pub.dev/packages/animations

**Comment by FeodorFitsner** [comment]
Duplicate for https://github.com/flet-dev/flet/issues/18

OK, let's keep yours one, but add my links too :)
