### ISSUE TITLE
When the Window is centered, it is displayed in the upper left corner for a moment and then centered.

### ISSUE THREAD

**Issue by online-world** [flet-dev/flet#1210]
When the Window is centered, it is displayed in the upper left corner for a moment and then centered.

https://user-images.githubusercontent.com/94748794/227201344-33a56944-e79c-4add-81d8-fe7f43254900.mp4

```python
import flet as ft


def main(page: ft.Page):
    page.window_center()
    page.window_width = 500
    page.window_height = 300

    page.update()


ft.app(target=main)

```

**Flet version (`pip show flet`)**:

```
Version: 0.4.2
```

**Operating system**:
Windows 10 Home 22H2

**Comment by tcbuger** [comment]
Is there any progress on this issue?

**Comment by ndonkoHenri** [comment]
Hide window on start: https://github.com/flet-dev/examples/blob/0b0c25be1947637751ce85ca0f134a974b9beed5/python/controls/page/window-hidden-on-start.py#L14

Set window to center and then make it visible.

**Comment by h1lton** [comment]
when initialized with the parameter "view=flet.FLET_APP_HIDDEN" the application appears

Version: 0.18.0
