### ISSUE TITLE
Request for ComboBox (i.e., Dropdown combined with text input field)

### ISSUE THREAD

**Issue by burque505** [flet-dev/flet#1219]
**Please Describe The Problem To Be Solved**

Very new to flet (it's up to me to solve that part of it :)) 
I have an app with many dropdowns, cloned from similar apps using other frameworks. The dropdowns all have options that are commonly needed, but users often need to be able to specify their own option, one not contained in the Dropdown options. 

I don't know much Dart or Flutter, which does not help, admittedly - but there appears from my searches to be little information on ComboBoxes (as opposed to Dropdowns), so perhaps there is no Dart/Flutter widget that could be ported. I have seen a Medium page that claims to create a ComboBox with Flutter: [Combo Box in Flutter](https://medium.com/@dc.vishwakarma.raj/combo-box-in-flutter-969105a9c40c)

Thank you for considering this.

**Comment by burque505** [comment]
W.I.P. workaround, please pardon the * import:
```
import flet as ft
from flet import *

def main(page: Page):
    page.title = "ComboBox Test"
    page.window_width = 600
    page.window_height = 300
    
    def dropdown_changed(e):
        dd_input.value = cbox_status.value
        cbox_status.key = None
        cbox_status.visible = False
        dd_input.visible = True
        cbox_button.visible = True
        page.update()
        pass
    
    def select_clicked(e):
        cbox_status.visible = True
        dd_input.visible = False
        cbox_button.visible = False
        page.update()

    cbox_button = FloatingActionButton(
        icon=icons.ARROW_DROP_DOWN_CIRCLE, on_click=select_clicked)
    
    cbox_status = Dropdown(
            visible = False,
            on_change=dropdown_changed,
            width=500,
            options=[
                dropdown.Option("Option Number One"),
                dropdown.Option("Another option, kind of useless"),
                dropdown.Option("a married primate dealing in its sole and separate property"),            
            ]                                                                
    )

    def add_todo(e):

        dd_input.value = ""
        page.update()

    dd_input = TextField(
        label='ComboBox test',
        width = 500
    )

    row = Row(
        controls=[
            dd_input,
            cbox_button
        ],
        alignment="left",
    )
    
    row2 = Row(
    controls=[
        cbox_status
    ],
    alignment="left"
    )


    page.controls.append(row)
    page.controls.append(row2)

    page.update()


flet.app(target=main)
```
![cbox_test](https://user-images.githubusercontent.com/46876254/227788108-2c0e9d45-4eb0-4407-a98f-a7fcf803b996.gif)

**Comment by FeodorFitsner** [comment]
[DropdownMenu](https://github.com/flet-dev/flet/issues/1088)

**Comment by burque505** [comment]
Very nice, thank you!
