### ISSUE TITLE
is it possible to change button color ?

### ISSUE THREAD

**Issue by ExtremeGTX** [flet-dev/flet#122]
I tried to check if it is possible to change the button color but couldn't find it. or is it not supported yet ?

I would like to thank the team behind this project, it is very promising idea! 👍

**Comment by FeodorFitsner** [comment]
Thanks for your support!

`ElevatedButton` allows changing both text (`color`) and background (`bgcolor`) colors: https://flet.dev/docs/controls/elevatedbutton/#color

**Comment by Animedecoder** [comment]
> Thanks for your support!
> 
> `ElevatedButton` allows changing both text (`color`) and background (`bgcolor`) colors: https://flet.dev/docs/controls/elevatedbutton/#color

Is there an option to give border_radius to buttons?

**Comment by ExtremeGTX** [comment]
Perfect, Thank you :)

**Comment by FeodorFitsner** [comment]
> Is there an option to give border_radius to buttons?

Please watch this issue: https://github.com/flet-dev/flet/issues/108
