### ISSUE TITLE
Container with `border_radius` doesn't clip its `content`

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#1225]
import flet as ft

def main(page: ft.Page):

    c = ft.Container(
            border_radius=10,
            #border=ft.border.all(4, ft.colors.ON_SECONDARY_CONTAINER),
            #margin=10,
            #padding=10,
            content=ft.Column(
                spacing=0,
                controls=[
                    ft.Container(
                        height=50, 
                        bgcolor=ft.colors.PRIMARY, 
                        content=ft.Text("PRIMARY"), 
                        alignment = ft.alignment.center, 
                        #border_radius=ft.border_radius.only(topLeft=10, topRight=10)
                        ),
                    ft.Container(
                        height=50, 
                        bgcolor=ft.colors.ON_PRIMARY, 
                        content=ft.Text("ON_PRIMARY"), 
                        alignment = ft.alignment.center),
                    ft.Container(
                        height=50, 
                        bgcolor=ft.colors.PRIMARY_CONTAINER, 
                        content=ft.Text("PRIMARY_CONTAINER"), 
                        alignment = ft.alignment.center),
                    ft.Container(
                        height=50, 
                        bgcolor=ft.colors.ON_PRIMARY_CONTAINER, 
                        content=ft.Text("ON_PRIMARY_CONTAINER"), 
                        alignment = ft.alignment.center,
                        #border_radius=ft.border_radius.only(bottomLeft=10, bottomRight=10)
                    )
                ]))

    page.add(c)

ft.app(target=main)

**Comment by gbrandt** [comment]
If you add `clip_behavior=ClipBehavior.HARD_EDGE` to the container does it work?  I have added a listview to a container with a radius and it works as expected with the `clip_behaviour` set.
![Screenshot 2023-03-30 at 14 15 28](https://user-images.githubusercontent.com/770473/228966309-ec3505fe-a25c-4a2c-820d-dfdfe693986b.png)
