### ISSUE TITLE
How to add scrolled ListView(or Column) with another widget in the Row?

### ISSUE THREAD

**Issue by antonnurapkin** [flet-dev/flet#1226]
I wrote this code and now my list isn't scrollable

I want to have one scrolled list and docs about any item on the right

`import flet as ft

def main(page: ft.Page):
    page.title = "Auto-scrolling ListView"

    col = ft.Column(scroll='ALWAYS',width=page.width*0.45)

    for i in range(0, 60):
        col.controls.append(ft.TextButton(width=page.width*0.45,text=f"Line{i+1}"))

    widgets = [
        # ft.TextButton(text='Расчёт на прочность болтвого соединения',width=page.width*0.45),
        col,
        ft.TextButton(text='Documentation',width=page.width*0.45)
    ]

    row = ft.Row(spacing=0, controls=widgets,alignment = ft.MainAxisAlignment.SPACE_EVENLY)

    page.add(row)`
    
    Thanks for help!

**Comment by gbrandt** [comment]
You also asked this in Discussions https://github.com/flet-dev/flet/discussions/1232 (which is the right place) so please close this ticket as its not an issue with flet or a feature request.
