### ISSUE TITLE
Gradients support in `Container`

### ISSUE THREAD

**Issue by StanMathers** [flet-dev/flet#123]
Adding LinearGradient would be a useful and further step to developing a much more interactive and good-looking UI with Flet.
There are some examples of what I mean:
    Flutter: https://www.youtube.com/watch?v=DJTQawES_6A
    CSS: https://www.youtube.com/watch?v=y92gnXrmmnA

**Comment by FeodorFitsner** [comment]
https://api.flutter.dev/flutter/painting/LinearGradient-class.html
