### ISSUE TITLE
Replit Deployment Guide is not working anymore

### ISSUE THREAD

**Issue by TheM0zart** [flet-dev/flet#1240]
**Description**

I followed the Replit deployment guide but it didn't work out. 

**Code example to reproduce the issue:**

```python
https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/replit
```

**Describe the results you received:**

When I finally try to run the application the console it gives me the following error message:
```python
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import flet as ft
  File "/home/runner/TestFlet/venv/lib/python3.10/site-packages/flet/__init__.py", line 1, in <module>
    from flet.flet import FLET_APP, FLET_APP_HIDDEN, WEB_BROWSER, app, app_async
  File "/home/runner/TestFlet/venv/lib/python3.10/site-packages/flet/flet.py", line 4, in <module>
    import flet_js
ModuleNotFoundError: No module named 'flet_js'
```

**Describe the results you expected:**

The website should run without errors. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Version 0.4.2
```

**Operating system**:

Windows 10 / Chrome

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Issue with replit was raised recently. https://github.com/flet-dev/flet/discussions/1189

As mentioned in the thread, @FeodorFitsner will certainly have a look at it sometime soon.

**Comment by FeodorFitsner** [comment]
@TheM0zart Are you running it in Replit phone app as well?

**Comment by TheM0zart** [comment]
> @TheM0zart Are you running it in Replit phone app as well?

No, I ran it via Chrome browser (Win10).

**Comment by TheM0zart** [comment]
I tried again with the newest flet version 0.5.0 but it still doesn't work. 
Now there is no error message, no output at all. It seems to load forever. 

I am wonder if this issue affects everyone or seems to be specific to me and a few other users?

**Comment by FeodorFitsner** [comment]
Will be looking into that.

**Comment by FeodorFitsner** [comment]
So, I'm trying Replit for a simple Flet app and I clearly don't understand what's going on.

1. I'm creating a new replit from Python template, go to "Packages" and install "flet" package. All nice,`pyproject.toml` looks good, nothing unusual:

![image](https://user-images.githubusercontent.com/5041459/230673098-858abc27-78d4-491b-8da2-46490bd359ba.png)

2. Typing a minimal Flet program:

![image](https://user-images.githubusercontent.com/5041459/230673300-4316ac24-ebe0-4fe6-8d2d-7b982d77c09b.png)

3. Hit "Run" and a wonder happens - out of nowhere it's installing `flet-pyodide` package:

![image](https://user-images.githubusercontent.com/5041459/230673450-2fc8e8bf-5098-4624-a63e-7ea184298a3b.png)

4. Obviously, it won't work as `flet-pyodide` is intended to work in the browser:

![image](https://user-images.githubusercontent.com/5041459/230673647-70d4f800-aefb-4d04-bd2f-8d9e0a6e62c1.png)

5. `pyproject.toml` has this:

![image](https://user-images.githubusercontent.com/5041459/230673954-fe953cee-f3f2-4952-afd2-e01ee0413a32.png)

Does it looks like a Replit issue?

**Comment by FeodorFitsner** [comment]
Reported a bug on Replit: https://ask.replit.com/t/python-repl-loads-an-incorrect-package/20069

**Comment by FeodorFitsner** [comment]
OK, the solution is disabling "package auto-guessing" feature in `.replit` file.

1. Create new repl from Python template.

2. Enable hidden files in "Files" pane:

![image](https://user-images.githubusercontent.com/5041459/230689759-c998a4c3-9633-4bd2-a18e-42055f5cea9d.png)

3. Set `packager.features.guessImports` to `false` ([more info](https://docs.replit.com/programming-ide/configuring-repl#guessimports)):

![image](https://user-images.githubusercontent.com/5041459/230689818-9357185e-2567-4d07-8992-601259f5201f.png)

4. Go to "Packages" and install `flet` package.

5. Type your program. Run. Enjoy!

![image](https://user-images.githubusercontent.com/5041459/230689946-7c80558d-6fa5-4169-a3de-afd65e492a3d.png)

**Comment by FeodorFitsner** [comment]
Updated guide: https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/replit

**Comment by TheM0zart** [comment]
Finally, thank you so much! I replicated the steps in the updated guide and can confirm it works now! 😃

**Comment by lxdtk** [comment]
I have set the file of . replit with

[packager]
language = "python3"

  [packager.features]
  enabledForHosting = false
  packageSearch = true
  guessImports = false

But when I run, It still execute “--> poetry add flet-pyodide....“, and report the error "No module named flet_js"
