### ISSUE TITLE
Dropdown focus stuck on AlertDialog

### ISSUE THREAD

**Issue by mabazud** [flet-dev/flet#1244]
when you
```python
some_dropdown.focus()
```
focus stucks on dropdown
it happens me on AlertDialog control

**Comment by gbrandt** [comment]
Can you give us minimal example code that reproduces the issue?

**Comment by mabazud** [comment]
i have already deleted the code but it was something like below:

''' 
class TempDialog(ft.AlertDialog):
    on_submit: callable

    def __init__(self):
        super().__init__()

        self.modal = False
        self.title = ft.Text(text_align=ft.TextAlign.CENTER)
        self.button_submit = ft.TextButton(text='OK', on_click=self.on_submit_clicked)
        self.button_cancel = ft.TextButton(text='Cancel', on_click=self.closeDialog)
        self.actions = [self.button_cancel, self.button_submit]
        self.actions_alignment = ft.MainAxisAlignment.SPACE_BETWEEN
        self.actions_padding = 10

        self.box_name = ft.TextField(border_radius=ft.border_radius.all(20),
                                     on_submit=self.on_name_submit)

        self.box_date = ft.TextField(hint_text='DD-MM-YYYY',
                                     border_radius=ft.border_radius.all(20),
                                     on_submit=self.on_date_submit)

        self.drop_options = ft.Dropdown(label='Some Options',
                                        border_radius=ft.border_radius.all(20))
        self.drop_options.options.append(ft.dropdown.Option(text='option 1'))
        self.drop_options.options.append(ft.dropdown.Option(text='option 1'))

        self.addControls()

    def addControls(self):
        self.content = ft.Column(tight=True)
        self.content.controls.append(self.box_name)
        self.content.controls.append(self.box_date)
        self.content.controls.append(self.drop_options)

    # noinspection PyUnusedLocal
    def on_submit_clicked(self, ce: ft.ControlEvent = None):
        # does some checking here
        self.on_submit()

    # noinspection PyUnusedLocal
    def on_name_submit(self, ce: ft.ControlEvent):
        if self.box_name.value:
            self.box_date.focus()
            self.box_date.update()

    # noinspection PyUnusedLocal
    def on_date_submit(self, ce: ft.ControlEvent):
        if self.box_date.value:
            self.drop_options.focus()
            self.drop_options.update()

    # noinspection PyUnusedLocal
    def closeDialog(self, ce: ft.ControlEvent):
        self.open = False
        self.update()
'''
