### ISSUE TITLE
Can't Change App name and icon

### ISSUE THREAD

**Issue by keyiflerolsun** [flet-dev/flet#125]
![IMG_20220729_165411](https://user-images.githubusercontent.com/57468649/181775514-50d09685-1617-4b13-a86c-e98cfbe98419.jpg)
This page title but;

![Screenshot_2022-07-29-16-54-14-938_com brave browser](https://user-images.githubusercontent.com/57468649/181775685-f5735414-c37f-4f45-9f69-a1bbac85d280.jpg)
and bottom of the page

**Comment by keyiflerolsun** [comment]
#17 sorry :)

**Comment by FeodorFitsner** [comment]
Yeah, I've just realized it's a standard Android message asking to install app to a home screen. The docs are coming this week!
