### ISSUE TITLE
Checkbox on_change receives strings `true` and `false` as event.value instead of boolean values True and False

### ISSUE THREAD

**Issue by xylix** [flet-dev/flet#1251]
**Description**
The default values that flet checkboxes start with seem to be correct type as expected. But the on_change boolean values are wrong.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    checkbox= ft.Checkbox(on_change=lambda e: print(bool(e.data)))
    page.add(
        ft.Text("Checkbox with on_change"),
        checkbox
        )
    print(checkbox.value) # This default value is correct
ft.app(target=main)
```

**Describe the results you received:**

The on_change value of a checkbox seems to be wrong. They are string "true" and "false", and when casting to boolean both resolve in `True` since string "false" is truthy in Python.

**Describe the results you expected:**

Checkbox on_change e.data to be True and False types.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/kerkko/Code/tmp/flet-checkbox-bug-test/venv/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:

macOS
`12.6 (21G115)` 

**Additional environment details:**

**Comment by gbrandt** [comment]
The values, I believe, come from the flutter web app, so this is not a bug.  All you have to do is do a string compare...or I use this as a solution for this and other places where I may not get a Python `True` or `False`:

``` Python
def any_to_bool(bool_rep: Any) -> bool:
    """convert input to a bool

    Parameters:
        bool_rep -- the var to convert to bool

    Returns:
        bool -- the text converted
    """

    if isinstance(bool_rep, bool):
        return bool_rep

    if isinstance(bool_rep, str):
        true_results = ["true", "t", "1", "yes"]
        return bool_rep.lower() in true_results

    if isinstance(bool_rep, int):
        return bool_rep != 0

    return False
```

**Comment by FeodorFitsner** [comment]
...or, alternatively, event control's value is already set by the time event handler is called, so you can do just:

```python
ft.Checkbox(on_change=lambda e: print(e.control.value))
```
