### ISSUE TITLE
`Alertdialog` does not close when switching between `Dialog`

### ISSUE THREAD

**Issue by DavMelchi** [flet-dev/flet#1260]
I have a simple app with 2 Tabs as show below with just a button that open an AlertDialog:

![image](https://user-images.githubusercontent.com/116588982/230626985-cae52925-f658-4fb5-862c-b6be2015e2b2.png)

**Code example to reproduce the issue:**

Please check below repo for the code to reproduce the issues :

https://github.com/DavMelchi/FLET_5_AlertDialog_issues 

**Describe the results you received:**

1) Open the modal on Tab1 and close it with button  ( It will close )
2) Go to Tab2 and open it's modal and close it ( It will close )
3) Return back to Tab1 and open it's modal and try to close it: **It will not close**

**Additional information you deem important (e.g. issue happens only occasionally):**

The  problem is on  flet>=0.5.0.dev1290

flet<=0.5.0.dev1252 is working fine.
Win10

Thanks.

**Comment by burque505** [comment]
@DavMelchi, I have a similar issue, one that leads me to believe it is not tabs that is causing the problem. I have copied your code from your repository and am running it now. I can confirm I get the same results. 
I have a couple of comments:

A) Please consider this code, taken (almost) directly from the docs page:
```
import flet as ft

def main(page: ft.Page):
    page.title = "AlertDialog examples"
    
    def close_nm_dlg(e):
        dlg.open = False
        page.update()
        print("Non-modal dialog dismissed!")
        
    dlg = ft.AlertDialog(
        title=ft.Text("Hello, you!"), on_dismiss=close_nm_dlg)

    def close_dlg(e):
        print("Modal dialog dismissed!")
        dlg_modal.open = False
        page.update()

    dlg_modal = ft.AlertDialog(
        modal=True,
        title=ft.Text("Please confirm"),
        content=ft.Text("Do you really want to delete all those files?"),
        actions=[
            ft.TextButton("Yes", on_click=close_dlg),
            ft.TextButton("No", on_click=close_dlg),
        ],
        actions_alignment=ft.MainAxisAlignment.END,
        #on_dismiss=lambda e: print("Modal dialog dismissed!"),
    )

    def open_dlg(e):
        page.dialog = dlg
        dlg.open = True
        page.update()

    def open_dlg_modal(e):
        page.dialog = dlg_modal
        dlg_modal.open = True
        page.update()

    page.add(
        ft.ElevatedButton("Open dialog", on_click=open_dlg),
        ft.ElevatedButton("Open modal dialog", on_click=open_dlg_modal),
    )

ft.app(target=main)
```
![alert_dialog_test](https://user-images.githubusercontent.com/46876254/230660316-49a60852-e907-4a51-bf26-a211c3a8dc5a.gif)

As you can see, the behavior of the Alerts is similar to that you're experiencing with tabs.

B) Although this is not really relevant to the issue (I don't believe), this line in the example from the docs is never going to execute:
`        on_dismiss=lambda e: print("Modal dialog dismissed!"),`
The only way to dismiss that dialog is to use either of the buttons, so I modified 'close_dlg' (and also added 'close_nm_dlg' ) to add print statements for debugging.

In my code above, if you run this so you can see the output, try clicking 'Open Dialog', then dismissing. The print statement in 'close_nm_dlg' executes. Click 'Open Modal Dialog' and click either button. The print statement in 'close_dlg' executes. Click 'Open Dialog' again. The print statement in 'close_nm_dlg' does NOT execute. Try clicking 'Open Modal Dialog' again - neither button will dismiss the modal dialog.

**Comment by DavMelchi** [comment]
@burque505 You're right. As My 2 Alerts were in different Tabs ,I didn't realize that it wasn't related to the Tabs. Finally we can say that it is when you switch between 2 alertdialog that the problem occurs. Title updated.
Thank you.

**Comment by DavMelchi** [comment]
@FeodorFitsner could you have a look on this please?

**Comment by FeodorFitsner** [comment]
The issue has been fixed and fix will be available in Flet 0.5.2.
You can try the fix right now by upgrading to pre-release version of Flet: `pip install flet --pre --upgrade`.
Let me know how it worked.

**Comment by burque505** [comment]
Works great for me, thank you! Much appreciated.

**Comment by DavMelchi** [comment]
Tested on `0.6.0.dev1300`.
It's solved @FeodorFitsner . Thanks a lot. Appreciated.
