### ISSUE TITLE
_remove_control_recursively takes an extremely long time (or forever?)

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1263]
This is a placeholder as I investigate and try to narrow down a test case.

I have a fairly complex app that has a container where I add and remove controls as the user moves through the app. (switching between content).

This became very very slow in some cases and in other cases never seems to end.  I added a print to the `_remove_control_recursively` function that shows the same controls being run through over and over (in one case, I have an icon that was in the function 120 times before I stopped it (I use `id(control)` to ensure I am looking at the same object.)

This is an example of an item on the screen, there are 7 of these on screen when this issue occurs.

![Screenshot 2023-04-07 at 09 35 04](https://user-images.githubusercontent.com/770473/230644714-41a9358a-4d07-4dac-9cf5-48474e9180cc.png)

(so seven of these are being removed, each one of these is a user control that contains 4 other user controls and 4 standard Flet controls, so the container has about >50 but < 100  controls on, all being removed before new controls are added)

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.6.0.dev1292
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/gregor.brandt/Documents/Startbridge/web-app2/fe_env/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:

**Additional environment details:**

**Comment by gbrandt** [comment]
commenting out 

``` python
         for child in control._previous_children:
             print(f"recursive: previous_children: {control} {id(control)} child: {child} {id(child)}")
             removed_controls.extend(self._remove_control_recursively(index, child))
```

in the function makes things return to as they were in 0.4.2, everything works as I switch pages

**Comment by FeodorFitsner** [comment]
Side note: looks like you need Badge control for your app: https://github.com/flet-dev/flet/issues/1264

**Comment by gbrandt** [comment]
> Side note: looks like you need Badge control for your app: #1264

I wrote my own but a built in one is always better. 🙂
