### ISSUE TITLE
Docs / examples: How to connect a client websocket to running Flet app

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#127]
Would be useful to get a guide on how to interact with the Fletd server with a running app. This way any client can  send/receive commands to the running UI (javascript, web callbacks, command line, etc). They would do this without the flutter/flet front end just websocket.

Use case: Times square runs a big billboard displaying a Flet app. The operators can update the UI content with an non Flet app that connects to the websocket/running session Flet app. 

Nice to have: Demonstrations with a python script and a javascript client.

**Comment by FeodorFitsner** [comment]
From a client perspective it's possible to "talk" to Flet server without a Python. It's WebSockets for now: https://github.com/flet-dev/flet/blob/main/server/protocol.md

We could add REST API in the future, but it's unclear how to receive events from user interaction then.

**Comment by FeodorFitsner** [comment]
I'm closing this issue. Feel free to start a new discussion or jump to Discord.
