### ISSUE TITLE
a user_control is getting did_mount() called but self.page is None

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1274]
Fairly consistently in a usercontrol, I am getting my `did_mount()` called but `self.page` is set to None.  I am attempting to investigate and distill down to a sample, but in the meantime this is a placeholder for the issue.  I've attached the stack trace and watch of the variable.

<img width="596" alt="Screenshot 2023-04-10 at 16 44 56" src="https://user-images.githubusercontent.com/770473/231019991-05d8864a-21f6-44fc-90cf-b523f7aa753c.png">

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.5.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/gregor.brandt/Documents/Startbridge/web-app2/fe_env/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:
MacOS 13.3.1

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
The issue has been fixed and fix will be available in Flet 0.5.2.
You can try the fix right now by upgrading to pre-release version of Flet: `pip install flet --pre --upgrade`.
Let me know how it worked.
