### ISSUE TITLE
incorrect typing in horizontal_alignment and vertical_alignment

### ISSUE THREAD

**Issue by Vlod-github** [flet-dev/flet#1285]
https://github.com/flet-dev/flet/blob/969cb2278a6e06e8abe669531c8839d7cb08bcf7/sdk/python/packages/flet-core/src/flet_core/view.py#L145
Hi, the `vertical_alignment` function accepts `value: MainAxisAlignment`. But in fact it accepts it accepts `value: Union[MainAxisAlignment, MainAxisAlignmentString]`. Similarly with `horizontal_alignment`

Insert the following code
```python
from typing import List, Optional, Union

def horizontal_alignment(self, value: Union[CrossAxisAlignment, CrossAxisAlignmentString]):

def vertical_alignment(self, value: Union[CrossAxisAlignment, CrossAxisAlignmentString]):
```

**Comment by Vlod-github** [comment]
1. The problem is that the fields that are identical in meaning give different values when compared. It is expected that either such fields cannot be set or they are the same when compared.
```py
from flet_core import Row, MainAxisAlignment

row_a = Row(alignment=MainAxisAlignment.START)
row_b = Row(alignment="start")
assert row_a.alignment == row_b.alignment #  Error
```
Decision. We will replace Enum with StrEnum.
```py
from enum import Enum, StrEnum

class TestEnum(StrEnum):
    START = 'start'

print('start' == TestEnum.START)  # Ok
```

**Comment by Vlod-github** [comment]
2. Now vertical_alignment accepts Enum, but there is logic for working with strings. It was also [suggested](https://github.com/flet-dev/flet/issues/1286#issuecomment-1509988672) to leave the possibility of passing a string.
```py
    @property
    def vertical_alignment(self) -> CrossAxisAlignment:
        return self.__vertical_alignment

    @vertical_alignment.setter
    def vertical_alignment(self, value: CrossAxisAlignment):
        self.__vertical_alignment = value
        if isinstance(value, CrossAxisAlignment):
            self._set_attr("verticalAlignment", value.value)
        else:
            self.__set_vertical_alignment(value)
```
I suggest removing the detailed description of Literal Main Axis Alignment String and others, because:
1) They duplicate information from Enum.
2) We will not be able to properly connect Literal and Enum without triple duplication of information.
Therefore, we must remove the Main Axis Alignment String, if developers want to see which strings the function can accept, then they can look in the Enum or documentation.

To validate the input parameters, I suggest using the helper function:
```py
def enum_to_str(enum: StrEnum, value: Union[StrEnum, str]) -> Optional[str]:
    if isinstance(value, StrEnum):
        return value.value
    if value in enum.__dict__['_value2member_map_']:
        return value
    return None
```
This function will either return the correct Enum value, or None.

Also earlier we allowed the use of incorrect arguments for objects, for example:
```py
Row(alignment="center")
Row(alignment="CENTer")
Row(alignment="CenteR")
```
The code continued to work as if this was normal behavior. Now, in case of an incorrect value, the value None will be set. In the future, we can add logging or runtime error if necessary.

**Comment by Vlod-github** [comment]
Write what you think about 1. and 2. And depending on the answer, we can update the code.
@ndonkoHenri, @FeodorFitsner

**Comment by FeodorFitsner** [comment]
I agree with @gbrandt we should get rid of strings in typings. Flet is still pre 1.0, so, theoretically, it's "allowed" to introduce breaking changes to its API ☺️

I like #2 solution suggested by @Vlod-github [here](https://github.com/flet-dev/flet/issues/1285#issuecomment-1515814977) - i.e. leave enum typings only in property declarations and remove `{something}String` literal typings everywhere; "inside" existing properties assigning both enums and strings will be supported to avoid breaking existing code (linter will be showing errors though, but it's OK). All new properties will be done to accept enum values only.

@Vlod-github would you willing to help with a PR for that?

**Comment by Vlod-github** [comment]
Yes, I will do it on the weekend

**Comment by Vlod-github** [comment]
I ran into problems due to the fact that Enums contain values of different types.

1. For the Enum class, enum.value returns Any, so I had to complicate the function code:
```py
def enum_to_str(enum: Enum, value: Union[Enum, str]) -> Optional[str]:
    if isinstance(value, Enum):
        if isinstance(value.value, str):
            return value.value
    elif value in enum.__dict__['_value2member_map_']:
        return value
    return None
```
2. Consider converting from string back to Enum:
```py
def value_to_enum(enum: Type[T], value) -> Optional[T]:
    if isinstance(value, Enum):
        return value  # type: ignore
    return enum.__dict__['_value2member_map_'].get(value)
```
```py
def vertical_alignment(self) -> Optional[CrossAxisAlignment]:
    return value_to_enum(CrossAxisAlignment, self.__vertical_alignment)

def vertical_alignment(self, value: CrossAxisAlignment):
	_value: Optional[str]
	_value = enum_to_str(CrossAxisAlignment, value)
	self.__vertical_alignment = _value
	self._set_attr("verticalAlignment", _value)
```
The `vertical_alignment` function can now return both `Enum.NONE` and `None` explicitly. We have a duplication of None, because the external code does not know if the abstract Enum has .NONE.
