### ISSUE TITLE
Feature Request: Allow snackbar duration to be set

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1287]
some snackbars should be shown for a longer period than others (error message for examples vs success messages).  Allowing duration to be set lets snackbars serve the purpose of user notifications with importance levels without using only color.

**(Optional): Suggest A Solution**

Python interface:
Flutter snackbars already have a duration, so the flet interface would be page.snackbar.duration = #.

**Comment by FeodorFitsner** [comment]
`SnackBar.duration` property can be tried with https://pypi.org/project/flet/0.6.0.dev1312/
