### ISSUE TITLE
Grt Mouse cursor position.

### ISSUE THREAD

**Issue by SKbarbon** [flet-dev/flet#1295]
Can flet in the future support getting mouse cursor position ?

**Comment by wpritom** [comment]
[Container](https://flet.dev/docs/controls/container/) supports this. In `on_click` even function print `e.data`. You will see both global and local coordinates. But you have to click on the container area to know the mouse cursor position. I'm not sure if there is something for hovering.

**Comment by ipritom** [comment]
[Container](https://flet.dev/docs/controls/container/) supports this. In `on_click` even function print `e.data`. You will see both global and local coordinates. But you have to click on the container area to know the mouse cursor position. I'm not sure if there is something for hovering.

**Comment by FeodorFitsner** [comment]
`GestureDetector`: https://flet.dev/docs/controls/gesturedetector#on_hover
