### ISSUE TITLE
FilePicker pick_files() works but save_file() and get_directory_path() doesn't

### ISSUE THREAD

**Issue by mabazud** [flet-dev/flet#1297]
```python
self.file_picker = ft.FilePicker()
self.page.overlay.append(self.file_picker)
self.file_picker.get_directory_path()  # nothing happens
self.file_picker.save_file()  # nothing happens
self.file_picker.pick_files()  # dialog opens
```

**Flet version 0.5.2**:

**Operating system Windows 10**:

**Comment by ndonkoHenri** [comment]
I tried the code below and it worked normally. Could you guys build some test code with the issue?

```python
import flet as ft


def main(page: ft.Page):
    page.theme_mode = "light"

    def result(e):
        page.add(ft.Text("result :)"))

    my_dialog = ft.FilePicker(on_result=result)

    page.overlay.append(my_dialog)

    page.add(
        ft.Row(
            [
                ft.ElevatedButton("Pick", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.pick_files()),
                ft.ElevatedButton("Save", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.save_file()),
                ft.ElevatedButton("Get Dir", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.get_directory_path()),
            ]
        )
    )


ft.app(target=main)
```



![image](https://github.com/flet-dev/flet/assets/98978078/99ec9d38-6180-4439-9649-0521ee238312)

**Comment by rkleivel** [comment]
> I tried the code below with flet v0.7.4 and it worked normally. Could you guys build some test code with the issue?
> 
> ```python
> import flet as ft
> 
> 
> def main(page: ft.Page):
>     page.theme_mode = "light"
> 
>     def result(e):
>         page.add(ft.Text("result :)"))
> 
>     my_dialog = ft.FilePicker(on_result=result)
> 
>     page.overlay.append(my_dialog)
> 
>     page.add(
>         ft.Row(
>             [
>                 ft.ElevatedButton("Pick", icon=ft.icons.UPLOAD_FILE,
>                                   on_click=lambda _: my_dialog.pick_files()),
>                 ft.ElevatedButton("Save", icon=ft.icons.UPLOAD_FILE,
>                                   on_click=lambda _: my_dialog.save_file()),
>                 ft.ElevatedButton("Get Dir", icon=ft.icons.UPLOAD_FILE,
>                                   on_click=lambda _: my_dialog.get_directory_path()),
>             ]
>         )
>     )
> 
> 
> ft.app(target=main)
> ```
> 
> ![image](https://user-images.githubusercontent.com/98978078/244026881-99ec9d38-6180-4439-9649-0521ee238312.png)

@ndonkoHenri  - The problem on Ubuntu is that none of the methods pick_files(), save_file() or get_directory_path() present the Ubuntu file dialog (Nautilus) unless you give python **root privileges** when running the app (aka `sudo env/bin/python get_directory_path_issue.py`) The code just silently skips presenting the file dialog, and calls result(e) with `e.data = {"path":null,"files":null}` 

If running the app with `view=ft.AppView.WEB_BROWSER ` it is able to launch the native file dialog with pick_files() without launching the app with root privileges. `e.data` also then returns relevant info when on_result function is called.

See also #1530
