### ISSUE TITLE
The scroll attribute for Column does not work

### ISSUE THREAD

**Issue by txwx** [flet-dev/flet#1300]
Why does the attribute scroll used for Column before have scroll, but now the latest version does not have scroll, so this attribute does not have effect.
The code is as follows：

import flet as ft

def main(page:ft.Page):
    text=ft.Text('fsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\n',width=100,height=100,text_align='center')
    col=ft.Column(controls=[text],scroll=ft.ScrollMode.ALWAYS,width=100,height=100,alignment='center',horizontal_alignment='center')
    page.add(col)

ft.app(target=main)

**Comment by moluyouwo** [comment]
Text添加selectable=True。
`import flet as ft

def main(page:ft.Page):
    text=ft.Text('fsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\n',width=100,height=100,text_align='center', selectable=True)
    col=ft.Column(controls=[text],scroll=ft.ScrollMode.ALWAYS,width=100,height=100,alignment='center',horizontal_alignment='center')
    page.add(col)

ft.app(target=main)`

**Comment by txwx** [comment]
thanks，But as I recall, we only needed scroll=ft.ScrollMode.ALWAYS for Column to scroll the text box. Did we get rid of that and use selectable=True instead?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月17日 17:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [flet-dev/flet] The scroll attribute for Column does not work (Issue #1300) |

Text添加selectable=True。
`import flet as ft

def main(page:ft.Page):
text=ft.Text('fsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\n',width=100,height=100,text_align='center', selectable=True)
col=ft.Column(controls=[text],scroll=ft.ScrollMode.ALWAYS,width=100,height=100,alignment='center',horizontal_alignment='center')
page.add(col)

ft.app(target=main)`

**Comment by FeodorFitsner** [comment]
Remove `width` and `height` from `Text`.

Working example:

```python
import flet as ft

def main(page: ft.Page):
    text = ft.Text(
        "fsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\nfsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\nfsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\nfsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\nfsdffdsf\nfsdfdsfdsf\nfsdfsfdsdfsdfsd\newrewwew\nfdsfdsfdsfds\nfsfddsfdsfd\ndfsfdsfdsfds\n",
        text_align="center",
    )
    col = ft.Column(
        controls=[text],
        scroll=ft.ScrollMode.ALWAYS,
        width=100,
        height=100,
        alignment="center",
        horizontal_alignment="center",
    )
    page.add(col)

ft.app(target=main)
```
