### ISSUE TITLE
assets not found if URL path is not root on first access

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1304]
In my app if I go to `http:127.0.0.1` the assets are found correctly and display using the Image control.

If I go to  `http:127.0.0.1/test` I get an error `ImageCodecException: Failed to decode image data.
Image source: http://127.0.0.1/testfull-logo.png

This is with `Image('full-logo.png)')`

**Code example to reproduce the issue:**

 You will need to create an assets folder and place an image in there named "full-logo.png"
```python

def main(page: ft.Page):

    page.add(ft.Image(src="full-logo.png", width=160))

    def on_error(event):
        print("Error:", event.data)

    page.on_error = on_error

    page.update()


ft.app(target=main, view=ft.WEB_BROWSER, assets_dir="assets")

```

**Describe the results you received:**

When the root url is used the image shows as expected

When using a path (127.0.0.1/test) the image does not show and on_error gives a decode error

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.5.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/gregor.brandt/Documents/Startbridge/web-app2/fe_env/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:

macOS 13.1

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Are you running it using built-in web server, right? It's assumed the app is in the root. Do you want it available by `/test` path or arbitrary path?

**Comment by gbrandt** [comment]
Yes, that is the built in web server. It is fair to assume that the app is at root, and indeed mine is.  However, users have the ability to click links that go directly to a path in the app or even type in paths directly.  The assumption is that the `/assets` folder is valid in all instances of the app regardless of the url.  So I would want the image to come from `/assets` regardless of the starting URL, since that is what is passed into the `ft.app`

**Comment by FeodorFitsner** [comment]
will take a look.

**Comment by FeodorFitsner** [comment]
You are using it with routing, right?

**Comment by gbrandt** [comment]
> You are using it with routing, right?

Not sure exactly what you are asking, but I'll give it a go.  Yes, I use page.route to access different parts of my app.  Although the app mostly starts at `/` users have the ability to send links to specific parts of the app that contain a full route such at `my app.com/shared_link`.  It's when the user clicks on that shared link that assets are no longer found.

**Comment by FeodorFitsner** [comment]
Yeah, that what I meant, thanks.

**Comment by VladoPortos** [comment]
Yea, found this as well,

if you have the web app on https://example.com/ and purposely go to https://example.com/something suddenly all your pictures will not load, because it will think its root domain is https://example.com/something. Not sure how to handle that except with nginx redirect to / but you need to exclude a bunch of stuff from that rule etc..

Also setting DEFAULT_FLET_PATH to domain name like https://example.com/ will not load the page at all. 

This is in my case when there is flet app in one container and nginx reverse proxy in other pointig to the app.

nginx setting:

```
events {
  worker_connections 1024;
}

http {
  upstream frontend {
    server frontend:8502;
  }

  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/certs/selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/selfsigned.key;

    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # prevent caching
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        add_header Pragma "no-cache";
        add_header Expires "-1";
    }

    location /ws {
        proxy_pass         http://frontend/ws;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        # prevent caching
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        add_header Pragma "no-cache";
        add_header Expires "-1";
    }

    # location ~ ^/(?!ws$).+ {
    #     return 301 https://$host/;
    # }
  }

}
```

**Comment by FeodorFitsner** [comment]
The fix could be tried with pre-release version of Flet.
