### ISSUE TITLE
Scrollbar bug

### ISSUE THREAD

**Issue by Raddiactive** [flet-dev/flet#1312]
With the code, for example:

```
import flet as ft

def main(page: ft.Page):
    page.title = "Images Example"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = 50
    page.spacing = 0

    page.update()

    images = ft.Column(expand=True, spacing=0, scroll="always")
    
    page.add(ft.Column(horizontal_alignment=ft.CrossAxisAlignment.CENTER, expand=True, spacing=0, scroll="always",controls=[images, ft.Row()]))
    for z in range(1, 9):
        for x in range(0, 1):
            for i in range(0, 9):

                if(i<5 and x!=1):
                    images.controls.append(
                        ft.Image(
                            src=f"https://dashboard.olympusscans.com/storage/comics/176/56517/{z}_{x}{i}.webp"
                        )
                    )

    page.update()

ft.app(target=main)

```

It does not display the scrollbar, but you can still scroll down using the laptop touchpad.
A video which I show it:
[https://drive.google.com/file/d/1Kzeb3RiJAZZKI6o4QJNtI6laCXTlt5k9/view?usp=sharing](url)

**Comment by FeodorFitsner** [comment]
Please provide more information (as in issue template). Also, video link is not working.

**Comment by Raddiactive** [comment]
I saw that the link don't work, but if you copy and paste the link in your browser you could see the problem. 

Description
The webpage is missing a scrollbar, which makes it difficult to navigate through the content. However, I found that I can still scroll through the images using the mouse scrollbar.

Actual Behavior
The webpage is missing a scrollbar, making it difficult to navigate through the content.

Environment
[Ubuntu 22.04]

**Comment by FeodorFitsner** [comment]
Use `page.scroll` property to enable page scrolling: https://flet.dev/docs/controls/page#scroll
