### ISSUE TITLE
ProgressRing color bug

### ISSUE THREAD

**Issue by Raddiactive** [flet-dev/flet#1313]
I have this ring defined:

`progress_ring = ft.ProgressRing(
                                value=0.5,
                                bgcolor="#44475A",
                                color="#BD93F9",
                                stroke_width=4.0
                            )`
And my program show bad the color ring, it don't change:
![image](https://user-images.githubusercontent.com/68911701/233056702-bb412611-a2f7-4ada-a62c-99b83db2c232.png)

**Comment by FeodorFitsner** [comment]
Works for me - both foreground and background colors are different:

![image](https://user-images.githubusercontent.com/5041459/233135779-07339b2f-91cf-4329-b2b6-b981d9f97162.png)

```python
import flet as ft


def main(page: ft.Page):
    page.add(
        ft.ProgressRing(value=0.5, bgcolor="#44475A", color="#BD93F9", stroke_width=4.0)
    )


ft.app(main)
```

**Comment by Raddiactive** [comment]
Omg, sorry, i saw that i had two rings and i was showing the bad ring.
