### ISSUE TITLE
Scrollbar style

### ISSUE THREAD

**Issue by Raddiactive** [flet-dev/flet#1317]
Hello, It would be very helpful if you could implement the option to change the color and style of the scroll bar.

**Comment by FeodorFitsner** [comment]
Scrollbar customization options:

1. [`Scrollbar`](https://api.flutter.dev/flutter/material/Scrollbar-class.html) - allows basic scrollbar customization such as thickness and radius. Should be applied to individual controls.
2. [`RawScrollbar`](https://api.flutter.dev/flutter/widgets/RawScrollbar-class.html) - allows full scrollbar customization such as thickness, radius and colors. Should be applied to individual controls.
3. [`ScrollbarThemeData`](https://api.flutter.dev/flutter/material/ScrollbarThemeData-class.html) - allows almost the same level customization as `RawScrollbar`, but is configured for all controls.
