### ISSUE TITLE
Add `-e , --extension` (for file extension) option to `flet` hot reload command

### ISSUE THREAD

**Issue by DavMelchi** [flet-dev/flet#1341]
Currently the Hot reload of Flet is triggered as long as there is a file saved in the working directory with the `-d or -r` option.
But sometimes we need to download some files in the assets folder such as image or json... on the startup which trigger the hot reload in a loop and thus makes the `-d and -r options unusable`. It would be nice to have option -e for example to specify the file extensions (example` -e "py"`) that will trigger the hot reload on save `or an option to exclude some directories`
Thanks.

**Comment by FeodorFitsner** [comment]
Implemented as https://github.com/flet-dev/flet/pull/2105
