### ISSUE TITLE
How to implement infinite scroll use GridView？

### ISSUE THREAD

**Issue by gsq7474741** [flet-dev/flet#1343]
I want to implement infinite scroll use GridView, now using GestureDetector(content=GridView(...)), but it seems GridView cant scroll inside a GestureDetector, is it a bug or just a error usage?

**Comment by FeodorFitsner** [comment]
Closing as a dup of https://github.com/flet-dev/flet/issues/747

I'm going to implement that once Flet 0.6.0 released.
