### ISSUE TITLE
Smooth Scroll

### ISSUE THREAD

**Issue by cuifengcn** [flet-dev/flet#1353]
The current scrolling effect seems to be a bit jumpy, which is not very user-friendly for continuous reading. Is it possible to achieve a smooth scrolling effect?

**Comment by FeodorFitsner** [comment]
Could you give more details please: OS, code sample, machine specs, are you running it as a desktop or web app?

**Comment by FeodorFitsner** [comment]
Oh, you mean in the first video you are scrolling with the wheel?

**Comment by cuifengcn** [comment]
> Oh, you mean in the first video you are scrolling with the wheel?

Yes 😂

**Comment by FeodorFitsner** [comment]
That "faster" scroll should be enabled in desktop app on Windows only. It's not enabled in web app. Could you please re-test?

**Comment by cuifengcn** [comment]
It looks same effect.
![screenshots](https://user-images.githubusercontent.com/38805177/235872036-10708f2d-837e-4f5f-9195-c2c1c8a1c217.gif)
```python
import flet as ft


def main(page: ft.Page):
    page.title = "scroll test"
    page.scroll = ft.ScrollMode.ALWAYS

    c = ft.Column(spacing=10)
    c.controls.extend([ft.Text("Column Line:" + str(i)) for i in range(40)])
    lv = ft.ListView(spacing=10, padding=20)
    lv.controls.extend([ft.Text("ListView Line:" + str(i)) for i in range(20)])
    t = ft.Text()
    t.value = "\n".join(["Text Line:" + str(i) for i in range(20)])
    rr = ft.ResponsiveRow(spacing=10)
    rr.controls.extend([ft.Text("ResponsiveRow Line:" + str(i)) for i in range(20)])

    page.add(c)
    page.add(lv)
    page.add(t)
    page.add(rr)


ft.app(target=main, view=ft.WEB_BROWSER)

```
> Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
> Windows 11 22H2 22621.1555

**Comment by FeodorFitsner** [comment]
Does it feel the same with Flet 0.7.1?

**Comment by cuifengcn** [comment]
The appearance seems unchanged from before. While scrolling using the "scroll_to_async" method, the speed can be adjusted with the "duration" parameter. However, when using the mouse wheel to scroll, the "duration" appears to become 0.

**Comment by cuifengcn** [comment]
[https://pub.dev/packages/smooth_scroll_multiplatform](https://pub.dev/packages/smooth_scroll_multiplatform)

As my test, this package works good on windows11.
