### ISSUE TITLE
DataTable control

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#136]

**Comment by clstaudt** [comment]
Will DataTable provide an easy way of displaying a `pandas.DataFrame`?

**Comment by FeodorFitsner** [comment]
I'm pretty sure it will!

It's going to be a general-purpose control for displaying grid data, but then we could do a number of extensions/adapters on Python side to make it more handy with different formats/libs. The same is applicable to charts as well.

I'm going to work on DataTable and Charts next week. This week I'm finishing Authentication. Thanks for your patience!

**Comment by monkeycc** [comment]
Expect DataTable control

**Comment by clstaudt** [comment]
@FeodorFitsner Any news on this?  I saw a commit related to DataTable but nothing in the documentation yet.

**Comment by FeodorFitsner** [comment]
It's been documented here: https://flet.dev/docs/controls/datatable
