### ISSUE TITLE
Flet webview stucks at startup

### ISSUE THREAD

**Issue by hrishikeshAvatron** [flet-dev/flet#1360]
When I run flet app with WebView, it stucks at startup only animating fish icon.

 logs-
INFO:flet:Host binding configured: 192.168.1.62
INFO:flet:Web renderer configured: canvaskit
INFO:flet:Route URL strategy configured: path
INFO:flet:Connecting Flet Server at ws://192.168.1.62:350/ws...
INFO[2023-05-03T12:29:20+05:30] Using in-memory cache
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

DEBU[2023-05-03T12:29:20+05:30] Static assets directory configured: C:\Users\Hrishikesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\web
DEBU[2023-05-03T12:29:20+05:30] Static assets directory configured: E:\Hrishikesh_Projects_new\EKI_28-04-2023_MainFolder\EKI_UI_28-04-2023\assets
[GIN-debug] GET    /ws                       --> github.com/flet-dev/flet/server/server.Start.func1 (4 handlers)
[GIN-debug] GET    /api/                     --> github.com/flet-dev/flet/server/server.Start.func2 (4 handlers)
[GIN-debug] GET    /api/oauth/redirect       --> github.com/flet-dev/flet/server/server.oauthCallbackHandler (4 handlers)
[GIN-debug] PUT    /api/upload               --> github.com/flet-dev/flet/server/server.uploadFileAsStream (4 handlers)
INFO[2023-05-03T12:29:20+05:30] Starting server on 192.168.1.62:350
INFO[2023-05-03T12:29:20+05:30] Starting background tasks...
INFO[2023-05-03T12:29:20+05:30] Start background task to cleanup expired data
INFO[2023-05-03T12:29:20+05:30] New WebSocket client connected from 192.168.1.62: ed4fada5-50f9-45b3-8a3a-e9d98482868f
INFO:flet:Successfully connected to ws://192.168.1.62:350/ws
[GIN] 2023/05/03 - 12:29:20 | 200 |      3.1964ms |    192.168.1.62 | GET      "/ws"
DEBUG:flet:_send_message_with_result: {"id":"76b46ac4935a45339eca87b7c5d637d6","action":"registerHostClient","payload":{"hostClientID":null,"pageName":"","isApp":true,"update":false,"authToken":null,"permissions":null}}
DEBU[2023-05-03T12:29:20+05:30] Message from ed4fada5-50f9-45b3-8a3a-e9d98482868f: {"id":"76b46ac4935a45339eca87b7c5d637d6","action":"registerHostClient","payload":{"hostClientID":null,"pageName":"","isApp":true,"update":false,"authToken":null,"permissions":null}}
INFO[2023-05-03T12:29:20+05:30] registerHostClient()
INFO[2023-05-03T12:29:20+05:30] Registering Host client: ed4fada5-50f9-45b3-8a3a-e9d98482868f
INFO[2023-05-03T12:29:20+05:30] Registering host client ed4fada5-50f9-45b3-8a3a-e9d98482868f to handle 'p/index' sessions
DEBUG:flet:_on_message: {"id":"76b46ac4935a45339eca87b7c5d637d6","action":"","payload":{"hostClientID":"yaTmkgWSiYUYu72zJZa7Ja6QNSk8PxaU4TDw_ovdYMyM-eebNuSpn05mvn4-GNSzkj3tqEwkNtvkMXv2r52tOlsds_Me8LPRJliUz1A=","sessionID":"","pageName":"p/index","error":""}}
INFO:flet:App URL: http://192.168.1.62:350
INFO:flet:Connected to Flet app and handling user sessions...
DEBU[2023-05-03T12:29:21+05:30] Request path:
DEBU[2023-05-03T12:29:21+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:21 | 200 |      1.7281ms |    192.168.1.62 | GET      "/"
DEBU[2023-05-03T12:29:21+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:21 | 304 |      1.8663ms |    192.168.1.62 | GET      "/flutter.js"
DEBU[2023-05-03T12:29:21+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:21 | 304 |      4.3127ms |    192.168.1.62 | GET      "/icons/loading-animation.png"
DEBU[2023-05-03T12:29:21+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:21 | 304 |      7.1175ms |    192.168.1.62 | GET      "/main.dart.js"
DEBU[2023-05-03T12:29:22+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:22 | 304 |       971.3µs |    192.168.1.62 | GET      "/assets/FontManifest.json"
DEBU[2023-05-03T12:29:22+05:30] FileSystemSFS error: open : invalid argument
[GIN] 2023/05/03 - 12:29:22 | 304 |      9.1192ms |    192.168.1.62 | GET      "/assets/fonts/MaterialIcons-Regular.otf"DEBU[2023-05-03T12:29:30+05:30] Expired entries: 0
DEBU[2023-05-03T12:29:30+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:29:30+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:29:30+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:29:40+05:30] Expired entries: 0
DEBU[2023-05-03T12:29:40+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:29:40+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:29:40+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:29:50+05:30] Expired entries: 0
DEBU[2023-05-03T12:29:50+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:29:50+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:29:50+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:00+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:00+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:00+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:00+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:10+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:10+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:10+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:10+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:14+05:30] send ping
DEBU[2023-05-03T12:30:14+05:30] received pong
DEBU[2023-05-03T12:30:20+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:20+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:20+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:20+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:30+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:30+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:30+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:30+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:40+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:40+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:40+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:40+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:30:50+05:30] Expired entries: 0
DEBU[2023-05-03T12:30:50+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:30:50+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:30:50+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:31:00+05:30] Expired entries: 0
DEBU[2023-05-03T12:31:00+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:31:00+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:31:00+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:31:08+05:30] send ping
DEBU[2023-05-03T12:31:08+05:30] received pong
DEBU[2023-05-03T12:31:10+05:30] Expired entries: 0
DEBU[2023-05-03T12:31:10+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:31:10+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:31:10+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:31:20+05:30] Expired entries: 0
DEBU[2023-05-03T12:31:20+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:31:20+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:31:20+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:31:30+05:30] Expired entries: 0
DEBU[2023-05-03T12:31:30+05:30] cleanupPagesAndSessions()
DEBU[2023-05-03T12:31:30+05:30] cleanupExpiredClients()
DEBU[2023-05-03T12:31:30+05:30] cleanupExpiredPageNameRegistrations()
DEBU[2023-05-03T12:31:40+05:30] Expired entries: 0

**Comment by FeodorFitsner** [comment]
Try using a different port, e.g. `ft.app(main, port=8080`.

Also, try opening direct URLs of built-in resources and custom assets, e.g.:

    http://{ip}:{port}/flutter.js
