### ISSUE TITLE
File Picker not work properly in Web browser

### ISSUE THREAD

**Issue by MosTafa2K** [flet-dev/flet#1366]
File Picker in web browser does not work properly. When I change the view to WEB BROWSER and I want to access the path of the uploaded file, the value None is returned, not the path of the file!

This is my code :

```python
import os
from flet import (
    flet,
    Page,
    icons,
    ControlEvent,
    FilePicker,
    FilePickerResultEvent,
    FilePickerUploadEvent,
    ElevatedButton,
    Text,
)


def main(page: Page):
    page.title = "File Picker"
    page.window_width = 800
    page.window_height = 600
    page.update()

    def pick_result(event: FilePickerResultEvent):
        file = (
            "".join([file.pathfor file in event.files])
            if event.files
            else "Cancelled!"
        )
        label.value = file
        page.update()


    file_dialog = FilePicker(on_result=pick_result)
    page.overlay.append(file_dialog)
    label = Text()

    page.add(
        ElevatedButton(
            "Browse File...",
            icon=icons.UPLOAD_FILE,
            on_click=lambda _: file_dialog.pick_files(
                "Upload file", allowed_extensions=["txt"]
            ),
        ),
        label
    )


if __name__ == "__main__":
    flet.app(target=main, view=flet.WEB_BROWSER)
```

After upload file using above code i got this error :

```TypeError: sequence item 0: expected str instance, NoneType found```

This code works out of WEB BROWSER mode without problems and does not give errors!

**Comment by antonnurapkin** [comment]
> FilePicker in a web app does not return file paths. It's by design, it's like browsers work. Browser works on a user side - they can only upload file to your web server.

@FeodorFitsner okay, what's different between Flet web app and any other website, where I can download files?

**Comment by NikitaKononov** [comment]
> FilePicker in a web app does not return file paths. It's by design, it's like browsers work. Browser works on a user side - they can only upload file to your web server.

So how we can use FilePicker to send files with requests then?
if we don't know the path

**Comment by ndonkoHenri** [comment]
I think you can upload the file to your assets, then use it from there.

**Comment by NikitaKononov** [comment]
> @NikitaKononov I think you can upload the file to your assets, then use it from there.

In my scenario users of web app can choose a file from their local machine
And send it to server

it's very typical and mundane task, but for some reason Flet doesn't allow me to solve it
Will it be fixed?

**Comment by ndonkoHenri** [comment]
- Follow this [guide](https://flet.dev/docs/guides/python/file-picker-and-uploads#uploading-files) - when the process is complete...
- send the file/s (they are now found in your `upload_dir`) via python requests to your API

I haven't tried but I think the above should work.
Try and let me have your feedback.
