### ISSUE TITLE
(Linux) Window can't be moved around with title bar hidden 

### ISSUE THREAD

**Issue by LucianCrainic** [flet-dev/flet#1374]
**Description**
Hello, i noticed that if i set the `window_title_bar_hidden` to `True` then on Linux the window can't be moved while on MacOs it can be moved around. I tried to replicate the bug with the sample app and as you can see in the screenshot the window can't be moved on Linux. 

**Code example to reproduce the issue:**

```python
import flet
from flet import IconButton, Page, Row, TextField, icons

def main(page: Page):
    page.title = "Flet counter example"
    page.vertical_alignment = "center"

    # if i set it to True then on Linux the window can't be moved around
    page.window_title_bar_hidden = True

    txt_number = TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = int(txt_number.value) - 1
        page.update()

    def plus_click(e):
        txt_number.value = int(txt_number.value) + 1
        page.update()

    page.add(
        Row(
            [
                IconButton(icons.REMOVE, on_click=minus_click),
                txt_number,
                IconButton(icons.ADD, on_click=plus_click),
            ],
            alignment="center",
        )
    )

flet.app(target=main)
```

**Describe the results you received:**

As you can see in the screenshot the window can't be moved on Linux. It stays in the same place and i can't move it around. 

<a href="https://ibb.co/gzpbWF1"><img src="https://i.ibb.co/LnWDghw/Screenshot-2023-05-07-at-14-22-04.png" alt="Screenshot-2023-05-07-at-14-22-04" border="0"></a>

**Describe the results you expected:**

I expected on Linux to move the window around like i do with the MacOs version.

**Flet version (`pip show flet`)**:

Name: flet
Version: 0.5.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/lucian/.local/lib/python3.10/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 

**Operating system**:
Linux Ubuntu 22.04.1 LTS

**Additional environment details:**
I emulated the bug on a VM with Ubuntu 22.04.1 LTS and Python 3.10.6 using UTM. I also tested it on a real machine with Ubuntu (same version) and i still get the same issue. I also tested it on a MacOs machine and it works as expected.

**Comment by FeodorFitsner** [comment]
To have a solution that works on all platform you need to use `WindowDragArea` control: https://github.com/flet-dev/examples/blob/main/python/controls/window-drag-area/no-frame-window.py

Hidden window title is implemented differently on all platforms and it's only coincidental you can drag it on macOS, e.g. on Windows your example won't work.

Use `WindowDragArea`.
