### ISSUE TITLE
AlertDialog can not be closed after reconnecting to the app.

### ISSUE THREAD

**Issue by wangzm5773** [flet-dev/flet#1379]
**AlertDialog can not be closed after reconnecting to the app.**

1. Open a AlertDialog.
2. Reconnect to the app. (e.g. Refresh the website page.)
3. The AlertDialog can not be closed now.

**Code example to reproduce the issue:**

```python
```

**Describe the results you received:**

https://user-images.githubusercontent.com/121756620/236811031-dd80d28e-b28b-4b8a-959a-4ffb3b6bf988.mp4

**Flet version (`pip show flet`)**:

```
Name: flet

Version: 0.7.0.dev1372
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Program Files\Python312\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**: Windows 11.

**Comment by ndonkoHenri** [comment]
Can you please provide some sample code for testing.
I am just from trying with the [example](https://flet.dev/docs/controls/alertdialog#basic-and-modal-dialogs) in the docs and it works as expected.

**Comment by FeodorFitsner** [comment]
There is a lot of missing files in that example, like fonts and other assets.
Can you do the repro in a separate GitHub repository, or Gist (which can be cloned as a repo too)?
