### ISSUE TITLE
Consistency of enumerations and css properties

### ISSUE THREAD

**Issue by Vlod-github** [flet-dev/flet#1380]
1. Consider `ImageFit`:
```
class ImageFit(Enum):
    NONE = "none"
    CONTAIN = "contain"
    COVER = "cover"
    FILL = "fill"
    FIT_HEIGHT = "fitHeight"
    FIT_WIDTH = "fitWidth"
    SCALE_DOWN = "scaleDown"
```
The [documentation says](https://flet.dev/docs/controls/image/#fit) that the default value is `.NONE`, which is equal to `"none"`
But [in the code](https://github.com/flet-dev/flet/blob/9cf0dcd9cb2ea889647e40e0e59ee2e5e05c5c64/sdk/python/packages/flet-core/src/flet_core/image.py#L88), the default value is `None`, which I run as `.CONTAIN`
Is this a documentation error or does it work differently for me?

2. Consider `MainAxisAlignment`:
```
class MainAxisAlignment(Enum):
    NONE = None
    START = "start"
    END = "end"
    CENTER = "center"
    SPACE_BETWEEN = "spaceBetween"
    SPACE_AROUND = "spaceAround"
    SPACE_EVENLY = "spaceEvenly"
```
The [documentation says](https://flet.dev/docs/controls/page/#vertical_alignment) that the default value is `.START`, and it is.
But [in the code](https://github.com/flet-dev/flet/blob/9cf0dcd9cb2ea889647e40e0e59ee2e5e05c5c64/sdk/python/packages/flet-core/src/flet_core/view.py#L37), the default value is not `.START`, but `.NONE`

Frankly, it's very confusing. I need to understand what approach you see as the right one in this situation? Why would you put `None` in a separate field and why would you choose a name that matches an existing CSS property? And why are the default properties somehow different from the ones declared in the documentation, either by name or by value?

**Comment by FeodorFitsner** [comment]
Having `None` in some enumerations is just a way to have a typing without `Optional`.

So, instead of:

```python
actions_alignment: Optional[MainAxisAlignment] = None
```

we have:

```python
actions_alignment: MainAxisAlignment = MainAxisAlignment.NONE
```

Semantically, setting prop value to `None` means "default to whatever value is default on Flutter side`, like `.START` for `MainAxisAlignment`.

I think we should get rid of `None` in all enums and use `Optional` instead.

Does it make sense?

**Comment by ndonkoHenri** [comment]
Makes sense to me.
Can PR that, if needed.

**Comment by FeodorFitsner** [comment]
@ndonkoHenri sure, PR would be great, thank you!

**Comment by Vlod-github** [comment]
@ndonkoHenri @FeodorFitsner 
I would suggest using 
```
MainAxisAlignmentDefault = MainAxisAlignment.START
ImageFitDefault = ImageFit.CONTAIN
# and so on
```
That way we could get rid of `None` and `.NONE is None` on the api side with the user, and return default values in case of unusual data. 

It's not clear yet what value to return correctly by default, I can't close the [previous question](https://github.com/flet-dev/flet/issues/1285#issuecomment-1518580112) correctly.

If you are satisfied with this, I will also make a PR, and you decide for yourself what suits you best

**Comment by ndonkoHenri** [comment]
@FeodorFitsner I think @Vlod-github is somehow right.
Setting the right defaults will make it possible for users extract the correct values.

So, if someone creates a `x=Row()` and below it calls `x.alignment`, he should get "start" and not None.

**Comment by Vlod-github** [comment]
The PR has been created. You can read the changes [here](https://github.com/flet-dev/flet/pull/1382/commits/b6149fbfebef0c24c0ac2a7bdc9c6035c2ce67c3?diff=split&w=0). Worth looking at utils.py, types.py, and others. Adding default values changed the internal contents of empty objects, which affected the tests. As well as the absence of None.
