### ISSUE TITLE
ButtonStyle with shape or side params failed in flet 0.7.0

### ISSUE THREAD

**Issue by david-shu** [flet-dev/flet#1390]
example:

[elevated-buttons example](https://github.com/flet-dev/examples/blob/main/python/controls/elevated-buttons/button-shapes.py)

failed in flet version 0.7.0.

maybe side and shape args in ButtonStyle  not work.

**Comment by fsmosca** [comment]
My web app suddenly fails with this release. It is using some elevated buttons.

I have to go back to previous version which still works both locally in fly.io.

**Comment by gbrandt** [comment]
<img width="668" alt="Screenshot 2023-05-12 at 08 30 04" src="https://github.com/flet-dev/flet/assets/770473/9812509a-868d-4ef7-ac47-11c8be5761f8">
 This is the stack at the point of error.

This is the error text: `App.on_error Invalid argument (index): "type"`
