### ISSUE TITLE
Obtain an image from a Uint8List

### ISSUE THREAD

**Issue by UGL1** [flet-dev/flet#1394]
I would really appreciate <a href="https://api.flutter.dev/flutter/widgets/Image-class.html">this feature</a>, which is native in Flutter, to be ported to flet, because it would make it more straightforward to play a video feed , for example.

**Comment by FeodorFitsner** [comment]
Isn't it the same as [`Image.scr_base64`](https://flet.dev/docs/controls/image#src_base64)?

**Comment by UGL1** [comment]
I'm no expert, I just figured it'd be faster not to deal with base64.
I'm kind of getting a Uint8List (I mean in numpy) when I'm using opencv, so I would like to create a flet image directly with it...
Same when I'm making (win32) screen captures.
