### ISSUE TITLE
Flet widget in Flutter

### ISSUE THREAD

**Issue by srang992** [flet-dev/flet#1395]
I am trying to test the server driven UI approach of flet. There is already a package  `flet` in pub.dev which can implement this. My flet app is already deployed on vercel. The website is static and I want to open this in flutter app. Here is the code for flutter.

```
import 'package:flet/flet.dart';
import 'package:flutter/material.dart';

void main() async {
  await setupDesktop();
  runApp(const FletApp(pageUrl: "https://blog-list-static.vercel.app/", assetsDir: "",));
```

and this is the code for my app.

```
import flet as ft
from utils import *
import pandas as pd
from custom_controls.cards.list_cards import ArticleCard
from custom_controls.list_upper_section.list_upper_section import TitleText, SubtitleText, SubscriptionButton


def get_data():
    df = pd.read_csv("data/BlogData.csv")
    return df


def main(page: ft.Page):
    page.padding = 10
    page.fonts = fonts
    page.title = title
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    # lv = ft.ListView(expand=True, spacing=10, padding=15)
    col = ft.Column([
        ft.Container(
            ft.Column([
                TitleText(text=title, font_family=title_font),
                SubtitleText(text=subtitle, font_family=desc_font),
                SubscriptionButton(
                    button_text=subscription_button_text,
                    link=subscription_form_link
                ),
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER
            ), padding=10,
        ),
    ],
        expand=True,
        spacing=10,
        horizontal_alignment=ft.CrossAxisAlignment.CENTER,
        scroll=ft.ScrollMode.HIDDEN,
    )

    data = get_data()

    for i in range(0, data.shape[0]):
        col.controls.append(
            ArticleCard(
                title=data.Title[i],
                title_font_family=title_font,
                desc=data.Description[i],
                desc_font_family=desc_font,
                link=data.Link[i],
            )
        )

    page.add(
        col
    )


ft.app(target=main, view=ft.WEB_BROWSER, port=8000, assets_dir="assets",)
```

When I am running this in flutter by url it gives - `WebSocket stream error WebSocketChannelException: WebSocket connection failed`. Please help me in this matter. I am new to flet.

**Comment by FeodorFitsner** [comment]
It won't work with a static website. You have to publish your app to [Fly.io or any other provider supporting Python](https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers). `Flet` widget connects to a Python app via WebSocket.

**Comment by srang992** [comment]
Ok, I got it. But if I proceed as mentioned in your `flet` documentation in the pub.dev, creating a sample counter app, running it and calling that url in the `FletApp` widget in flutter, I got an error saying
 
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 53090`

Then I checked in the task manager that if there is any `fletd` server is running. In the task manager, I am seeing this.
<img width="498" alt="image" src="https://github.com/flet-dev/flet/assets/86141125/56d25b74-9890-4e02-a8c6-d83511348ff5">
Is that ok or I am missing something. Please help me. I am using windows 11. I followed the documentation properly but I made a one change in `FletApp` widget as there is now two required arguments. I am initializing the `assetsDir` as empty string just like below.

```
FletApp(
          pageUrl: "http://localhost:8550",
          assetsDir: "",
)
```

That's it. I not modified the code more than that.

**Comment by FeodorFitsner** [comment]
Run it with `ft.app(main, port=8550, view=ft.WEB_BROWSER`.

**Comment by FeodorFitsner** [comment]
I'll figure out the way to force web server without using `ft.WEB_BROWSER`.

**Comment by srang992** [comment]
> I'll figure out the way to force web server without using `ft.WEB_BROWSER`.

I will wait for that. My main aim is to run the flet app as an mobile application.

**Comment by srang992** [comment]
Recently I created a single page static website in flet. Everything is running fine. Now I want to customize the manifest.json file for giving the app my own name and my own icons. here is the structure of the manifest.json:
```
{
  "name": "SubR's Homepage",
  "short_name": "SubR's Homepage",
  "start_url": ".",
  "display": "standalone",
  "icons": [
    {
      "src": "icons/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "icons/icon-maskable-192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "icons/icon-maskable-512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
}
```
when I run the app using `ft.app(target=main, view=ft.WEB_BROWSER, assets_dir="assets")` the custom name and icons are loading without any problem, but when i add the `port` arguments in it or creating the `dist` directory using `flet publish` and running the web page from dist, the manifest file is changed with the default one. Here is the screenshot from the chrome devtools.
<img width="418" alt="image" src="https://github.com/flet-dev/flet/assets/86141125/1f98a27e-4d5c-4c7c-8842-05583122878f">
please help me in this matter.

**Comment by srang992** [comment]
> @srang992 , You need to go to the flet lib and then go to the folder named "web", change the default to custom things you want

Recently, I figured it out what happened. This is the issue with the vercel, not the flet.
