### ISSUE TITLE
Button style not showing as expect

### ISSUE THREAD

**Issue by cuifengcn** [flet-dev/flet#1400]
**When i add `OutlinedButton` to page,its not showing right**

![image](https://github.com/flet-dev/flet/assets/38805177/39c29e1a-8688-4884-9c26-1f7303557aef)
```python
import flet as ft


def main(page):
    page.title = "Example"
    for i in range(1, 10):
        page.add(
            ft.OutlinedButton(
                str(i),
                style=ft.ButtonStyle(shape=ft.CountinuosRectangleBorder()),
                width=40,
                height=40,
                on_click=print,
            )
        )


ft.app(target=main)
```
___
**I changed `style` to `style=ft.ButtonStyle(shape={"": ft.CountinuosRectangleBorder()}),`,it looks right(althought content is not in center)**

![image](https://github.com/flet-dev/flet/assets/38805177/3f0116d5-68e0-4154-957c-fccb829ccb83)
___

**Then i add `padding=1` to `ButtonStyle`, if looks good**

![image](https://github.com/flet-dev/flet/assets/38805177/08ac1dad-b820-41d6-b6d9-9a8d90af1218)

**final code**
```python
import flet as ft


def main(page):
    page.title = "Example"
    for i in range(1, 10):
        page.add(
            ft.OutlinedButton(
                str(i),
                style=ft.ButtonStyle(shape={"": ft.CountinuosRectangleBorder()}, padding=1),
                width=40,
                height=40,
                on_click=print,
            )
        )


ft.app(target=main)

```
___
I have tried `OutlinedButton` `ElevatedButton` `FilledButton` `FilledTonalButton` `TextButton`, and `WEB_BROWSER` view, same issue.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.7.0.dev1399
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\14438\documents\github\private-taichi\venv\lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:
Windows  11 22H2 22621.1702

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Update to the latest Flet 0.7.1 - this issue has been fixed there.

**Comment by cuifengcn** [comment]
Yeah, 0.7.1 works great, thanks!
