### ISSUE TITLE
Force web server in desktop mode

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1401]
We need a way to force using web server, but still run Flet app with desktop UI, without using `flet run`.

It's needed for SSO/Auth/uploads working in desktop mode.

**Comment by hokaso** [comment]
Thank you for your attention to this issue~

**Comment by hokaso** [comment]
![image](https://github.com/flet-dev/flet/assets/26475781/aae80722-cfb6-47d6-a3f7-1c1d712d5bee)
There seem to be some issues...
