### ISSUE TITLE
TextTheme for Container doesn't work

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#1410]
In the example below, text color doesn't change:

```
def example():
    c = ft.Container(
        theme=ft.Theme(
            text_theme=ft.TextTheme(body_medium=ft.TextStyle(color=ft.colors.GREEN))
        ),
        content=ft.Text("Hello, green world!"),
        height=100,
        width=300,
    )

    return c
```

**Comment by FeodorFitsner** [comment]
Closing it with "as designed".

If `Text` control style is not specified it derives a style from the closest `DefaultTextStyle` widget with the root one created in `Scaffold` widget. When Flet overrides `Theme` it does not override `DefaultTextStyle`.
