### ISSUE TITLE
Windows Bar white hides Button maximize and minimize 

### ISSUE THREAD

**Issue by Galdino17** [flet-dev/flet#1434]
**Description**

I created a project for Windows, but the minimize and maximize buttons are hidden because the Windows bar is white. How can I change the color of the Windows bar?

I used the native highlight colors function of Windows, but I noticed that other applications already have the taskbar with the default gray color.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: None
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\galdino\appdata\local\programs\python\python37\lib\site-packages
Requires: packaging, websockets, httpx, flet-core, websocket-client, oauthlib, typing-extensions, watchdog
Required-by:
```

**Operating system**:

Windows 10 Home

**Comment by ndonkoHenri** [comment]
Could you please show a capture of what you mean? It's quite confusing.
