### ISSUE TITLE
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you are running. Check the system information of your computer and then contact the software vendor.

### ISSUE THREAD

**Issue by Lord-K-505** [flet-dev/flet#1437]
I recently installed flet on my computer (Windons, 32-bit). But, when I try to compile the program, I get the following error:

**OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you are running. Check the system information of your computer and then contact the software vendor.**

I don't know why.

**Comment by FeodorFitsner** [comment]
I'm afraid 32-bit OS is not supported, only 64-bit.

**Comment by Lord-K-505** [comment]
Thank you for letting me know. I appreciate the information.
