### ISSUE TITLE
Passthrough of mouse events from main window to other applications

### ISSUE THREAD

**Issue by Kawue** [flet-dev/flet#1438]
Is there something similar to setIgnoreMouseEvents() from window_manager available?

I would like to have my Flet window borderless and transparent on top of other applications and have my mouse events passed through to the underlying application. Flet should still be on focus and receive keyboard events. Is this possible? I did it with Pyside6 but would like to reimplement the GUI in Flet.

**Comment by holvi-mikael** [comment]
Nothing like this is currently implemented, as far as I know. Also, sounds horrible from security point of view.

**Comment by ndonkoHenri** [comment]
@FeodorFitsner, while looking at this [window_manager](https://pub.dev/packages/window_manager) flutter package, I noticed there are alot of stuffs it offers.
For instance, everyone has been asking for a way to set the desktop icon while deving, and [here](https://pub.dev/packages/window_manager#seticon--windows) is something interesting, though only for windows...
The titlebar could also be styled.. [link](https://pub.dev/packages/window_manager#settitlebarstyle)

So many interesting little stuffs.

**Comment by FeodorFitsner** [comment]
Yep, saw that too. There is a lot of wonders inside that package :)

**Comment by ndonkoHenri** [comment]
That nectar needs to be sucked out. 🙂
