### ISSUE TITLE
image does not show in markdown

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1443]
An image that GitHub can show does not show in markdown.

An image that can be shown in markdown does not get shown in the control

```python
import flet as ft

md1 = """
![Test image](https://cdn.wallpapersafari.com/20/34/lfbiMe.jpg)
"""


md1 = """
image
![Test image](https://cdn.wallpapersafari.com/20/34/lfbiMe.jpg)
endimage
"""

def main(page: ft.Page):
    page.scroll = "auto"
    page.add(
        ft.Markdown(
            md1,
            selectable=True,
            extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
            on_tap_link=lambda e: page.launch_url(e.data),
        )
    )

ft.app(target=main, view=ft.WEB_BROWSER)

```

**Describe the results you received:**

<img width="362" alt="Screenshot 2023-05-29 at 12 08 32" src="https://github.com/flet-dev/flet/assets/770473/e22aad9e-c75e-431b-9c6a-4fa9502d3979">

**Describe the results you expected:**

image
![Test image](https://cdn.wallpapersafari.com/20/34/lfbiMe.jpg)
end image
**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.7.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
```

**Operating system**:

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
It could be a CORS policy on their side. Do you see any errors in Developer Console of your browser while opening the app?

**Comment by gbrandt** [comment]
CORS was the first suspect, but since GitHub shows it correctly it can't be CORS.  Both my dev deploy and my local cannot display the image.  Also the server is owned by a friend and he says no CORS is setup on the server.

**Comment by FeodorFitsner** [comment]
Can you display that image with just `Image` control?

**Comment by gbrandt** [comment]
I can last the url into the url bar and it shows. Did not try image control.

**Comment by FeodorFitsner** [comment]
It's CORS:

<img width="774" alt="image" src="https://github.com/flet-dev/flet/assets/5041459/2056ed82-d8fa-441a-96e8-3f7f8c5f9ca8">

The image can be opened in desktop mode without any issues:

```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Image("https://cdn.wallpapersafari.com/20/34/lfbiMe.jpg"))

ft.app(main)
```

**Comment by Hamza5** [comment]
> It's CORS:
> <img alt="image" width="774" src="https://user-images.githubusercontent.com/5041459/242084539-2056ed82-d8fa-441a-96e8-3f7f8c5f9ca8.png">
> 
> The image can be opened in desktop mode without any issues:
> 
> ```python
> import flet as ft
> 
> def main(page: ft.Page):
>     page.add(ft.Image("https://cdn.wallpapersafari.com/20/34/lfbiMe.jpg"))
> 
> ft.app(main)
> ```

Thanks for the information 👏  I was about to report that `Image` control does not work on the browser, and I blindly forgot the CORS policy. Mine was a thumbnail of a YouTube video that I got from their API, so it seems that they forgot to enable CORS.

**Comment by gbrandt** [comment]
If we get a CORS error on an image or in markdown, is it possible to display something that shows the image is not available?

**Comment by FeodorFitsner** [comment]
I see, there is a possibility for that `imageBuilder` property. Leaving this issue open and adding "bug" label.

**Comment by FeodorFitsner** [comment]
Related: https://github.com/flet-dev/flet/issues/1461

**Comment by JuliaKonieczna** [comment]
@gbrandt were you able to prepare some workaround?
@FeodorFitsner did it move?

**Comment by ndonkoHenri** [comment]
> is it possible to display something that shows the image is not available?
[`Image.error_content`](https://flet.dev/docs/controls/image#error_content) can now be used for this.
