### ISSUE TITLE
Discussion: Include a slugifier?

### ISSUE THREAD

**Issue by mikaelho** [flet-dev/flet#145]
As flet now has support for routes i.e. deep linking, would it make sense to include a slugifier for internal use, i.e. for the use of components like `ResponsiveMenuLayout` without requiring developers to add requirements?

This could be a simple 5-line implementation like the one in `ResponsiveMenuLayout`, or vendoring some existing slugifier library, if expanding the requirements is not attractive.

**Comment by FeodorFitsner** [comment]
Your implementation looks pretty good to me. No need for 3rd-party packages. We could include `slugify` it to some `flet.utils` namespace.

**Comment by FeodorFitsner** [comment]
Feel free to submit a PR with the method.
