### ISSUE TITLE
Control coordinates in page

### ISSUE THREAD

**Issue by joeg-ita** [flet-dev/flet#1451]
Hi everyone,
maybe I'm missing something known...
Is there a way to get for an arbitrary control in the page its position in the window, x and y starting points or offset or whatever?
If not, I think it could be very useful for placing, for example, an overlay control based on the "layer -1" control.

Thank you

**Comment by zferdz** [comment]
Stack control.

**Comment by joeg-ita** [comment]
I'm trying to create an autocomplete extending UserControl, I need to know the textfield or the icon button position to properly show the panel with the suggestions...
Stack is not useful in this situation, I overlay the panel in the page

![autocomplete](https://github.com/flet-dev/flet/assets/25502936/ac1472d7-666b-4f2f-94de-089a486917e4)

**Comment by Omer-Farooqui** [comment]
Hi, could you share some code and perhaps describe what you're trying to achieve in more detail?
