### ISSUE TITLE
SnackBar instantly hides after showing when the duration is set

### ISSUE THREAD

**Issue by Hamza5** [flet-dev/flet#1454]
### Description

The `duration` argument/property of `SnackBar` does not work as expected. Setting this property to an `int` should keep the `SnackBar` open for a number of seconds equal to that value.

### Code for reproducing the issue
I have just copied [the example of the documentation](https://flet.dev/docs/controls/snackbar) and set the `duration = 5`.

```python
import flet as ft


class Data:
    def __init__(self) -> None:
        self.counter = 0


d = Data()


def main(page):

    page.snack_bar = ft.SnackBar(
        content=ft.Text("Hello, world!"),
        action="Alright!",
    )

    def on_click(e):
        page.snack_bar = ft.SnackBar(ft.Text(f"Hello {d.counter}"))
        page.snack_bar.duration = 5  # This line causes the problem. The problem stays when duration is set as an argument.
        page.snack_bar.open = True
        d.counter += 1
        page.update()

    page.add(ft.ElevatedButton("Open SnackBar", on_click=on_click))


ft.app(target=main)

```
### Result

The `SnackBar` is getting closed instantly after being opened. This is not the expected behavior, and I can not find a workaround for this.

### Flet version (`pip show flet`)

```
Name: flet
Version: 0.7.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: e:\documents\commentsguard\.venv\lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

### Operating system:

Windows 10. Both desktop and web apps are affected.

**Comment by FeodorFitsner** [comment]
Duration must be set in milliseconds, e.g. `5000` to last it for 5 seconds. Sorry for wasting your time! It must be documented.

**Comment by Hamza5** [comment]
Ah sorry, I didn't think about that! I should guess that before opening this issue. [I opened a PR](https://github.com/flet-dev/website/pull/131) to add this information to the docs.

**Comment by FeodorFitsner** [comment]
Thank you!
