### ISSUE TITLE
 [Feature Request] - Configurable Session Timeout

### ISSUE THREAD

**Issue by RobinRingelberg** [flet-dev/flet#1455]
Dear Flet Team,

I would like to request a feature that allows us to configure the session timeout for our applications.
Currently, the session timeout in a Flet App is set to a default value of 60 minutes. However, it would greatly benefit developers if we had the ability to customize this timeout duration according to our specific application requirements.
I appreciate your attention to this matter and would be grateful for any updates or considerations. 
Thank you for your time.

Best regards,
Robin

**Comment by ndonkoHenri** [comment]
@FeodorFitsner please add a list of all the env variables in the docs.

**Comment by ndonkoHenri** [comment]
Set env variable `FLET_SESSION_TIMEOUT`. It defaults to `3600` seconds.
