### ISSUE TITLE
TextField places cursor at first position after text replacement

### ISSUE THREAD

**Issue by kwiechen** [flet-dev/flet#1463]
**Description**

After text replacement the cursor is moved to the first position and the arrow keys are not working until new character input
**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    def textbox_changed(e):
        tb.value = e.control.value.replace("tt", "Test:\n")    
        page.update()
    
    tb = ft.TextField(
        label="Text",
        autofocus=True,
        multiline=True,
        disabled=False,
        min_lines=25,
        value="",
        on_change=textbox_changed
    )

    page.add(tb)
    
ft.app(target=main)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Just from trying your sample code with the latest flet version and this is a true concern.

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of https://github.com/flet-dev/flet/issues/2210

**Comment by ndonkoHenri** [comment]
This issue has been fixed in the [latest pre-release](https://flet.dev/blog/introducing-flet-1-0-alpha#trying-flet-10-alpha) and the code you provided now works as expected.
