### ISSUE TITLE
`flet create` CLI

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1465]
`flet create` creates a new Flet app from a template.

Template has at least `assets` directory created (related to https://github.com/flet-dev/flet/issues/1043) with `favicon.png` and `manifest.json` inside.

`flet create` parameters:
- `--project-name` the name of the project to put into `manifest.json`.
- `--description` project description to put into `manifest.json`.
- `--template` the name of the template to use for new project (all templates are in https://github.com/flet-dev/templates).

**Comment by ndonkoHenri** [comment]
Parameter ideas: 
- flag for Appveyor stuffs (`appveyor.yml`)
- another for fly.io stuffs (`Dockerfile`,..)

The template could also add a `requirements.txt` file with `flet`.
