### ISSUE TITLE
After updating to 0.7.4, the icon has issues

### ISSUE THREAD

**Issue by txwx** [flet-dev/flet#1466]
Since updating to 0.7.4, I use the built-in ICONS, such as Search, but instead of displaying a box in the UI

**Comment by FeodorFitsner** [comment]
Can you add more context please, like was requested in issue template?

**Comment by txwx** [comment]
Sorry, I forgot to add my code, here is part of my program code:
def build(self):
            self.serachbtn = ft.IconButton(
            icon=ft.icons.SEARCH, on_click=self.search)
            self.row = ft.Row(controls=[self.bookname, self.serachbtn])
            return return ft.Stack([ft.Container(content=self.row)])

**Comment by txwx** [comment]
Sorry, I forgot to add my code, here is part of my program code:
def build(self):
           self.serachbtn = ft.IconButton(
           icon=ft.icons.SEARCH, on_click=self.search)
           self.row = ft.Row(controls=[self.bookname, self.serachbtn])
           return return ft.Stack([ft.Container(content=self.row)])



---- Replied Message ----
| From | Feodor ***@***.***> |
| Date | 06/10/2023 11:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [flet-dev/flet] After updating to 0.7.4, the icon has issues (Issue #1466) |

Can you add more context please, like was requested in issue template?

**Comment by ndonkoHenri** [comment]
Can you move to the latest flet version and try again?
Nevertheless, I don't understand you issue.

**Comment by txwx** [comment]
现在已经没问题了，真的是太奇怪了，我在0.7.4刚出来的时候升级了一下就出现了我之前说的图标变成方框，现在莫名其妙的又好了，真是个奇怪的事



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2023 19:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [flet-dev/flet] After updating to 0.7.4, the icon has issues (Issue #1466) |

Can you move to the latest flet version and try again?
Nevertheless, I don't understand you issue.

**Comment by FeodorFitsner** [comment]
@txwx use English please.

**Comment by txwx** [comment]
Now there is no problem, it is really too strange, I just came out of 0.7.4 when the upgrade appeared I said before the icon into a box, now inexplicably good again, really a strange thing

---- Replied Message ----
***@***.***>Date07/26/2023 ***@***.***>***@***.***>***@***.***>SubjectRe: [flet-dev/flet] After updating to 0.7.4, the icon has issues (Issue #1466)
Can you move to the latest flet version and try again?
Nevertheless, I don't understand you issue.

**Comment by ndonkoHenri** [comment]
Good to know everything is fine now. Can you close this issue then?
