### ISSUE TITLE
Is it possible to know if a widget is visible in the viewport

### ISSUE THREAD

**Issue by TingTingin** [flet-dev/flet#1467]
When using a listview is it possible to know when a widget is visible in the viewport since widgets are loaded dynamically and when loading nothing is shown on the screen (especially when loading images) it would be helpful if you could query the viewport to know if the widgets are visible yet and and show a loading or waiting message etc

 I was able to find a widget on pub.dev https://pub.dev/packages/visibility detector but don't know if this is something you'd want to add

**Comment by ndonkoHenri** [comment]
For images, I suggest this: https://docs.flutter.dev/cookbook/images/fading-in-images.
