### ISSUE TITLE
At startup, flet tries to download 'fletd-0.3.2-linux-amd64.tar.gz' and fails

### ISSUE THREAD

**Issue by tsterbak** [flet-dev/flet#1471]
**Description**
On startup of the app, flet tries to download `fletd-0.3.2-linux-amd64.tar.gz` and fails. Seems to happen if no network is available.

**Code example to reproduce the issue:**

I sadly cannot reproduce this. User reported this issue to me.

**Describe the results you received:**

**Describe the results you expected:**

Can this file be downloaded and distributed locally?

**Additional information you deem important (e.g. issue happens only occasionally):**

This is the issue the user raised with the full stacktrace.
https://github.com/flathub/org.openandroidinstaller.OpenAndroidInstaller/issues/1

**Flet version (`pip show flet`)**:

```
flet = "0.3.2"
```

**Operating system**:

NixOS

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Please try the latest 0.7.4 version. What exact error do you get?

**Comment by 09u2h4n** [comment]
I fixed by download manually.
```bash
cd /tmp/
wget https://github.com/flet-dev/flet/releases/download/v0.7.4/fletd-0.7.4-linux-arm64.tar.gz
```

**Comment by tsterbak** [comment]
> Please try the latest 0.7.4 version. What exact error do you get?

@FeodorFitsner: I will try again with the updated version.
You can find the full error message here: https://github.com/flathub/org.openandroidinstaller.OpenAndroidInstaller/issues/1
