### ISSUE TITLE
FilledButton and FilledTotalButton are not shown in grey color when disabled.

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#1472]
FilledButton and FilledTotalButton are not shown in grey color when disabled.
Should be like in this example: https://flutter.github.io/samples/web/material_3_demo/#/

**Comment by ndonkoHenri** [comment]
I really like this Website: https://flutter.github.io/samples/web/material_3_demo/#/
I am thinking of building one for flet.
