### ISSUE TITLE
Loading Custom Assets of Flet in Flutter

### ISSUE THREAD

**Issue by srang992** [flet-dev/flet#1474]
**Description**

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Please close this issue.

**Comment by srang992** [comment]
that opens accidentally.
