### ISSUE TITLE
Conflict between containers

### ISSUE THREAD

**Issue by antonnurapkin** [flet-dev/flet#1478]
It doesn't work. It's not a error in terminal, uploading to the site just stops

`
import flet as ft

def main(page:ft.Page):
    c1 = ft.Column(
        [
            ft.Container(content=ft.ElevatedButton(text='Button', expand=1),bgcolor=ft.colors.BLACK45, expand=1),
            ft.Container(content=ft.ElevatedButton(text='Button', expand=1),bgcolor=ft.colors.BLACK45, expand=1)
        ]
    )
    
    c2 = ft.Column(
        [
            ft.Container(content=ft.TextField(expand=1),bgcolor=ft.colors.RED_600, expand=1),
            ft.Container(content=ft.TextField(expand=1),bgcolor=ft.colors.RED_600, expand=1)
        ]
    )
    
    col = ft.Column(
        [
            ft.Container(content=ft.Text(value='AN_NAME', expand=1),bgcolor=ft.colors.RED_ACCENT_400),
            ft.Row([c1,c2])
        ]
    )
    
    page.add(col)

ft.app(view=ft.WEB_BROWSER, target=main, web_renderer='html')
`

**Comment by FeodorFitsner** [comment]
Could you provide a working example please?
