### ISSUE TITLE
web_root_dir not found in 0.8.0.dev1500

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1480]
installing pre-release of flet gives the following error:

`/fe_env/lib/python3.11/site-packages/flet_runtime/app.py", line 518, in __start_flet_server
    raise Exception(f"Web root path not found: {web_root_dir}")`

`web_root_dir` is `/site-packages/flet_runtime/web`.  The `web` folder does not exist after install

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.0.dev1500
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
```

**Operating system**:

macOS 13.4

**Comment by FeodorFitsner** [comment]
That's a good catch.
