### ISSUE TITLE
Requesting some Features in Flet

### ISSUE THREAD

**Issue by srang992** [flet-dev/flet#1495]
I have used Flet for a long time and I would say it is undoubtedly the best framework I ever used. But while developing apps in Flet, some features I found missing which are already available in Flutter. I am listing those here for drawing your attention.
- more controls on textfield as flutter like bolding the selecting text.
- Video control by which we can show a local video from a disk or show a youtube video by an URL, just like Streamlit.
- multi-select dropdown by which we can select multiple items at once.
- Customising the text of markdown just like code. Till now, we can only customise the code style, not the text.
- Center widget-like control in Flet. I think defining a specific control inside the center control is much better than specifying both vertical and horizontal alignment.

**Comment by FeodorFitsner** [comment]
Dup of other issues.
