### ISSUE TITLE
Is flet already supporting asynchronous calls, urgently need help online!!!

### ISSUE THREAD

**Issue by wangbaoyi** [flet-dev/flet#1496]
import asyncio

import flet
from flet import ElevatedButton
from flet import Page
from unsync import unsync

class BetterBar:
    @unsync
    def start(self):
        while True:
            print("A better Bar")
            # await asyncio.sleep(2)

def clicked(event):
    something_async()

@unsync
async def something_async():
    print("Starting an async operation")
    await asyncio.sleep(1)
    print("Finished")

def main(page: Page):
    page.add(ElevatedButton("Click me to do something async", on_click=clicked))
    page.update()

async def main1():
    flet.app(target=main)

async def Start():
    await asyncio.gather(main1(),BetterBar().start())

if __name__ == '__main__':
    asyncio.run(Start())

我通过这段代码跑了demo确实没问题，但是我用了websockets.serve，他就会报错。所以我想问下目前felt是否已经解决了这类问题呢，或者能否提供相关websockets.serve能成功的代码示例呢？
将中文翻译成英文如下:
I ran a demo with this code and it worked fine. But when I used websockets.serve, it reported an error. So I want to ask if flet has solved such problems now, or can it provide examples of websockets.serve that can work successfully?

主要使用以下函数出现的报错：
翻译：
The main error occurred when using the following functions:

    async def start(self):
        self.host = self.ConfigDict["图像服务ip"]
        self.port = self.ConfigDict["图像服务端口"]
        async with websockets.serve(self.web_infer_predict, self.host, self.port,max_size=2**30):  
            print(f"WebSocket服务器已启动,监听地址为:ws://{self.host}:{self.port}")
            loop = asyncio.get_running_loop()
            loop.run_in_executor(None, await asyncio.Future())
            print("推理：线程，启动成功.")
            # await asyncio.Future()  # 防止程序退出

希望官方能回复一下，在线一直等！
翻译：
I hope the official can reply, I have been waiting online all the time!

**Comment by FeodorFitsner** [comment]
Sorry, what is websockets.serve?

**Comment by wangbaoyi** [comment]
// CMakeProject1.cpp: 定义应用程序的入口点。
//


#include "opencv2/opencv.hpp"
#include "ws_client.h"
#include "base64.h"
#include <time.h>
#include <chrono>
#include <ctime>
#include <stdio.h>
#include "dxgi/Common.h"
#include "dxgi/DXGICapture.h"
#include "yaml-cpp/yaml.h" //安装yaml-cpp参考google code 主页


using namespace std;
using namespace BXC;


long long timestamp_now() {
	return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
}


string load_text_file(const string& file) {
	ifstream in(file, ios::in | ios::binary);
	if (!in.is_open())
		return {};

	in.seekg(0, ios::end);
	size_t length = in.tellg();

	string data;
	if (length > 0) {
		in.seekg(0, ios::beg);
		data.resize(length);

		in.read((char*)&data[0], length);
	}
	in.close();
	return data;
}



int main()
{

	//// 读取YAML文件
	YAML::Node config = YAML::LoadFile("../Config/setting.yaml");
	//std::ifstream fin("config.yaml"); // 读入yaml配置文件。
	//// 读取host和port 服务器IP和端口
	std::string host = config["image_server_ip"].as<std::string>();
	std::string port = config["image_server_port"].as<std::string>();
	//// 打印host和port
	std::cout << "image_server_ip: " << host << std::endl;
	std::cout << "image_server_port: " << port << std::endl;
	SetConsoleOutputCP(CP_UTF8);
	DXGICapture dxgiCapture;
	int width = GetSystemMetrics(SM_CXSCREEN);
	int height = GetSystemMetrics(SM_CYSCREEN);
	int cx = width / 2; // 中心点横坐标
	int cy = height / 2; // 中心点纵坐标
	int left = cx - 320; // 裁剪区域左上角横坐标
	int top = cy - 320; // 裁剪区域左上角纵坐标
	int duplWidth = -1;
	int duplHeight = -1;
	cv::Rect roi(left, top, 640, 640); // 裁剪区域

	if (!dxgiCapture.InitDevice())
	{
		LOGE("Failed to initialize DXGIScreen device");
		return -1;
	}

	if (!dxgiCapture.InitDupl(0, duplWidth, duplHeight))
	{
		LOGE("Failed to InitDupl");
		return -1;
	}
	LOGI("InitDupl success,width=%d,height=%d,duplWidth=%d,duplHeight=%d", width, height, duplWidth, duplHeight);

	long mBufferSize = duplWidth * duplHeight * 4;
	uint8_t* mBuffer = new UCHAR[mBufferSize];

	int i = 0;

	bool connection = true;

	auto ws_client_ = new WsClient(host+port);

	ws_client_->async_run();
	while (true) {
		if (!ws_client_->is_connecting_) {
			printf("ws未连接\n");
			Sleep(2000);
			continue;
		}
		auto t1 = timestamp_now();
		GETFRAMERESULT getFrameResult = dxgiCapture.getFrame();
		if (GETFRAME_SUCCESS == getFrameResult) {
			if (dxgiCapture.copyFrameToBuffer(&mBuffer, mBufferSize))
			{
				auto t2 = timestamp_now();

				cv::Mat bgra_image(duplHeight, duplWidth, CV_8UC4, mBuffer);

				
				cv::Mat image = bgra_image(roi).clone(); // 裁剪操作并复制图像数据   1ms
				

				// 压缩图像
				std::vector<uchar> buf(640*640*image.channels());
				cout << "ch: " << image.channels() << endl;
				//std::vector<int> params = { cv::IMWRITE_JPEG_QUALITY, 100 };
				//imencode(".jpg", image, buf, params);

				//std::vector<int> params = { cv::IMWRITE_PNG_COMPRESSION, 9 };
				//imencode(".png", image, buf, params);
				// 不压缩
				//buf = image.reshape(1,1);   // 2ms
				//std::string compressed_image(buf.begin(), buf.end());  // 7ms

				// 使用Mat的数据指针 
				uchar* data = image.data;
				size_t size = image.total() * image.elemSize();

				// 如果需要std::string
				char* data_ptr = (char*)image.data;
				std::string compressed_image(data_ptr, size);

				auto t3 = timestamp_now();

				try {
					ws_client_->send(compressed_image);
				}
				catch (std::exception& e) {
					std::cerr << "Exception caught: " << e.what() << std::endl;
					connection = true;

				}
				auto t4 = timestamp_now();

				LOGI("i=%d getFrame success total: %11d ms read: %lld ms encode: %11d ms send: %11d ms", i, (t4 - t1), (t2 - t1), (t3 - t2), (t4 - t3));
				//cv::imshow("Screenshot", cropped);
				//cv::waitKey(1);
				std::this_thread::sleep_for(std::chrono::milliseconds(1));
			}

			dxgiCapture.doneWithFrame();
		}
		else {
			if (GETFRAME_DUPLICATION_ERROR == getFrameResult) {

				int w = -1;
				int h = -1;

				if (dxgiCapture.ReInitDupl(0, w, h)) {
					LOGI("ReInitDupl success ,duplWidth=%d,duplHeight=%d", duplWidth, duplHeight);

					if (w != duplWidth || h != duplHeight) {
						duplWidth = w;
						duplHeight = h;

						if (mBuffer) {
							delete mBuffer;
							mBuffer = nullptr;
						}
						mBufferSize = duplWidth * duplHeight * 4;
						mBuffer = new UCHAR[mBufferSize];

					}
				}
				else {
					LOGI("ReInitDupl error");
				}
			}
		}
	}

	system("pause");
	return 0;
}

**Comment by wangbaoyi** [comment]
python：
import asyncio
import websockets
import numpy as np
import cv2

class BetterBar:
    async def start(self):
        while True:
            print("A better Bar")
            await asyncio.sleep(0)


class WebSocketServer:
    def __init__(self, host, port):
        self.host = host
        self.port = port
    
    async def handle_websocket(self, websocket, path):
        # 连接建立时打印一条消息
        print("WebSocket连接已建立")
        while True:
            # 接收客户端发送的消息
            message = await websocket.recv()
            # 将接收到的二进制数据转换为NumPy数组
            img = np.frombuffer(message, dtype=np.uint8).reshape((640, 640, 4))
            # print(f"收到消息：{message}")
            # 显示图像（可选）
            cv2.imshow("Received Image", img)
            cv2.waitKey(1)

    async def start(self):
        async with websockets.serve(self.handle_websocket, self.host, self.port,max_size=2**30):  
            print(f"WebSocket服务器已启动,监听地址为:ws://{self.host}:{self.port}")
            # await asyncio.Future()  # 防止程序退出
            loop = asyncio.get_running_loop()
            loop.run_in_executor(None, await asyncio.Future())


async def wrapper():
    server = WebSocketServer("192.168.31.48", 8000)
    await asyncio.gather(BetterBar().start(), server.start())


if __name__ == "__main__": 
    asyncio.run(wrapper())
    # server.run()

**Comment by FeodorFitsner** [comment]
How is this related to Flet?

**Comment by wangbaoyi** [comment]
async def Start():
    Sm_xywh = shared_memory.ShareableList( sequence=(range(5)))
    Sm_Detection = shared_memory.ShareableList( sequence=(range(3)))

    mgr = Manager()
    ConfigDict = mgr.dict()
    data = check_config()
    # 读取配置文件（多进程）
    ConfigDict.update(data)
    ConfigDict['重启AI'] = False
    ReloadMouseDriverMode(ConfigDict)
    GlobalConfiguration(ConfigDict)
    ConfigDict['权重转换'] = False
    #初始化卡密
    # ConfigDict['LoginHeart'] = 0
    ConfigDict['LoginHeart'] = 1

    # km = AntsLogin(ConfigDict)
    # t1 = Thread(target=km.Heart, args=(), daemon=True)
    # t1.start()
    menu = Menu(ConfigDict)
    # # 键鼠监听多线程
    monitor = Monitor(ConfigDict)
    # monitor.run()
    Infer = infer(ConfigDict,Sm_xywh,Sm_Detection)
    # await asyncio.gather(BetterBar().start(), Infer.start())
    # await asyncio.gather(Infer.start(),BetterBar().start(), menu.ftstart())
    # await asyncio.gather(menu.ftstart(),monitor.run(),BetterBar().start(), Infer.start())
    loop = asyncio.get_event_loop()
    tasks = [infer.start(), BetterBar.start(), menu.ftstart()]
    loop.run_until_complete(asyncio.gather(*tasks))


    while   True:
        await asyncio.sleep(2)  # 等待2秒
    # loop = asyncio.get_running_loop()
    # loop.run_in_executor(None, await asyncio.Future())

if __name__ == '__main__':
    print(os.getcwd())
    multiprocessing.freeze_support()
    asyncio.run(Start())

**Comment by baseplate-admin** [comment]
Perhaps the issuer wanted to know if flet supports `asyncio`?

**Comment by wangbaoyi** [comment]
Because it's asynchronous, I need to run flet, so I have to make flet asynchronous to run at the same time!!!

**Comment by baseplate-admin** [comment]
@FeodorFitsner, I think the requester is running a blocking task ( in form of websocket server ) and then wants to communicate with `flet` frontend and the issuer wants to do it from one python process

**Comment by wangbaoyi** [comment]
I originally solved the problem through:
loop = asyncio.get_event_loop()
tasks = [infer.start(), BetterBar.start(), menu.ftstart()]
loop.run_until_complete(asyncio.gather(*tasks))
However, I want to add flet interface to run in tasks, but it blocked, blocked in the flet interface thread, so I came to ask about the situation.

**Comment by FeodorFitsner** [comment]
Yes, Flet supports asyncio (https://flet.dev/docs/guides/python/async-apps), but I don't think such scenario (hosting flet inside another websocket server) is yet possible. Flet has its own websocket server. But this scenario is going to be supported first for all for FastAPI.

**Comment by wangbaoyi** [comment]
Oh, it has been improved. I see, thank you for your answer!!! I will try again, and if it doesn't work, I will come back and feedback! May I ask how to update to the new version you mentioned?

**Comment by baseplate-admin** [comment]
> May I ask how to update to the new version you mentioned?

It's not yet implemented.

---
Curiously does `flet` allow it's `websocket` server to be modified?

**Comment by FeodorFitsner** [comment]
I don't think you need to modify Flet's websocket connection. Instead, you would need to implement your own Connection like this one for example: https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-pyodide/src/flet/pyodide_connection.py

**Comment by wangbaoyi** [comment]
import asyncio
import flet as ft
from unsync import unsync



class BetterBar:
    @unsync
    async def start(self):
        while True:
            print("A better Bar")
            await asyncio.sleep(2)



class Countdown(ft.UserControl):
    def __init__(self, seconds):
        super().__init__()
        self.seconds = seconds

    async def did_mount_async(self):
        self.running = True
        asyncio.create_task(self.update_timer())

    async def will_unmount_async(self):
        self.running = False

    async def update_timer(self):
        while self.seconds and self.running:
            mins, secs = divmod(self.seconds, 60)
            self.countdown.value = "{:02d}:{:02d}".format(mins, secs)
            await self.update_async()
            await asyncio.sleep(1)
            self.seconds -= 1

    def build(self):
        self.countdown = ft.Text()
        return self.countdown

async def main(page: ft.Page):
    await page.add_async(Countdown(120), Countdown(60))

ft.app(target=main)
我回来了，我想我要的是能同时运行多个类，我发现flet虽然支持了异步，但他还是会阻塞，请问这该怎么办呢？以上代码如果我想运行BetterBar这个类，应该怎么做呢？
翻译：
I'm back. I want to run multiple classes at the same time. I found that although flet supports asynchrony, it still blocks. What should I do? If I want to run the BetterBar class in the above code, what should I do?

**Comment by FeodorFitsner** [comment]
You can use `ft.app_async()` which is awaitable.

**Comment by wangbaoyi** [comment]
&nbsp;


Ants
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2023年6月19日(星期一) 凌晨0:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flet-dev/flet] Is flet already supporting asynchronous calls, urgently need help online!!! (Issue #1496)





 
您可以使用哪个是等待的。ft.app_async()
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;

**Comment by wangbaoyi** [comment]
import asyncio
import flet as ft
from unsync import unsync



class BetterBar:
    async def start(self):
        while True:
            print("A better Bar")
            await asyncio.sleep(2)



class Countdown(ft.UserControl):
    def __init__(self, seconds):
        super().__init__()
        self.seconds = seconds

    async def did_mount_async(self):
        self.running = True
        asyncio.create_task(self.update_timer())

    async def will_unmount_async(self):
        self.running = False

    async def update_timer(self):
        while self.seconds and self.running:
            mins, secs = divmod(self.seconds, 60)
            self.countdown.value = "{:02d}:{:02d}".format(mins, secs)
            await self.update_async()
            await asyncio.sleep(1)
            self.seconds -= 1

    def build(self):
        self.countdown = ft.Text()
        return self.countdown

async def main(page: ft.Page):
    await page.add_async(Countdown(120), Countdown(60))


async def maina():
    await asyncio.gather(
        BetterBar().start()
    )

def mainb():
    # asyncio.run(maina)
    # ft.app(target=main)
    ft.app_async(target=main)


if __name__ == '__main__':
    # asyncio.run(maina())
    mainb()

**Comment by wangbaoyi** [comment]
g:\Ants\Ant开发\yolov5_Ant\ant-双机练习\服务端1\demo2.py:51: RuntimeWarning: coroutine 'app_async' was never awaited
  ft.app_async(target=main)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by wangbaoyi** [comment]
In this way, it will report an error.
