### ISSUE TITLE
Expand `Semantics` and `SemanticsService` support

### ISSUE THREAD

**Issue by tgrushka** [flet-dev/flet#1498]
**Please Describe The Problem To Be Solved**

Accessibility is extremely important. I am a visually impaired engineer and work heavily in Flutter. This framework is very promising and will make Flutter accessible to those who prefer other languages, especially blind programmers who may prefer languages like Python when using a screen reader.

I am an Accessibility Engineer for my job and have the CPWA certification. There are relatively few of us specializing in this, so I try to contribute wherever possible. I am working on contributions to the Flutter engine to things like tabs not indicating their selected state on web and desktop, etc.

Thank you for adding `Semantics` to Flet. I noticed it currently only supports the `label` attribute, which is a great start. I just stumbled on this awesome framework today, so I'm sorry, I'm not proficient enough to contribute code at this time, but would be happy to become a tester and possibly small contributor (my time is very limited) for new features on request. My main focus is going to be on the Flutter engine so accessibility just works for everyone.

**(Optional): Suggest A Solution**

1. Please try to expand and fill out the `Semantics` feature set as much as you can to the properties Flutter currently supports.
2. Please add `SemanticsService` if possible, so a `SemanticsService.announce` can be performed. This is very important for things like autocomplete, and to notify users when screen content changes.
3. If you have a Widgets "watch list," could you possibly add `Semantics` and `SemanticsService` to it so that Flet can have the most up-to-date accessibility Flutter currently offers?

Thank you!

Tom / https://github.com/dra11y

**Comment by FeodorFitsner** [comment]
Thanks for trying Flet!

I guess you mean supporting [Semantics.properties](https://api.flutter.dev/flutter/semantics/SemanticsProperties-class.html), right?
