### ISSUE TITLE
page.window_minimized, page.window_maximized, and page.window_close_async don't work on async apps.

### ISSUE THREAD

**Issue by a0w89fwa0f** [flet-dev/flet#1511]
When using an Async Flet App none of the above mentioned in the title work.

- page.window_minimized
- page.window_maximized
- page.window_close_async

---

The below code snippet works showing that there is nothing wrong with **ALL** Async functions.

```py
async def exit_button_callback(self, e: flet.TapEvent):
    await self.page.window_destroy_async()
```

The **window_destroy_async** function works fine for exiting an app. However using **window_close_async** in the exact same manner will result in nothing happening. No errors are raised, just simply nothing happens.

---

Similarly the below code snippets also do nothing. No errors, nothing happens.

```py
async def minimize_button_callback(self, e: flet.TapEvent):
    self.page.window_minimized = True
    await self.page.update_async()

async def maximize_button_callback(self, e: flet.TapEvent):
    self.page.window_maximized = True
    await self.page.update_async()
```

---

As mentioned this issue only exists inside of an Async Flet App using them in a Non-Async Flet App they all work as expected, granted for **page.window_destroy_async**, and **page.window_close_async** you wouldn't use the async functions.

Flet Version: 0.7.4
Windows 10 Version: 22H2

**Comment by ndonkoHenri** [comment]
These async functions are now deprecated and will be soon removed.
