### ISSUE TITLE
It seems no way to create new windows, is there any alternative?

### ISSUE THREAD

**Issue by AnemosCiel** [flet-dev/flet#1540]
I want to create a music software that normally displays a small window, and when the expand button is pressed, a new translucent window can be opened to display the lyrics, and the size and position can be changed by dragging the mouse.

The initial idea was to create 2 Windows, but Flet doesn't seem to support multiple Windows, is there any way to implement my idea?

Thank you!

**Comment by mouadessalim** [comment]
what you could do, as i do myself is to use the same windows to show multiple page in the same windows like a native web app by using `ft.UserControl` to create multiple reusable widget's or just try creating multiple instance of `ft.app()` with `threading`

**Comment by ndonkoHenri** [comment]
What do you think of [this](https://github.com/SKbarbon/flet_multi_page)? Made by a community member.

**Comment by ndonkoHenri** [comment]
This is not yet possible.
We will have a look at it once Flutter officially supports it.
