### ISSUE TITLE
flet pack is broken in version 0.8.0

### ISSUE THREAD

**Issue by mardukbp** [flet-dev/flet#1552]
**Description**

`flet pack` fails due to a missing function in the module `flet.utils`

**Code example to reproduce the issue:**

```bash
flet pack counter.py
```

**Describe the results you received:**

Please install PyInstaller module to use flet pack command: cannot import name 'get_package_bin_dir' from 'flet.utils' 
(`c:\Python\3.8.10\lib\site-packages\flet\utils\__init__.py`)

**Describe the results you expected:**

A self-contained .exe is generated in the dist directory

**Additional information you deem important (e.g. issue happens only occasionally):**

The solution is to add the following import to `flet/utils/__init__.py`:

```python
from flet_runtime.utils import get_package_bin_dir
```

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: None
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\Python\3.8.10\lib\site-packages
Requires: websockets, qrcode, copier, flet-runtime, pydantic, websocket-client, packaging, watchdog
Required-by:
```

**Operating system**:

Windows 10 Home

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Good catch, thanks for letting know and providing the solution!
