### ISSUE TITLE
Don`t remove one option in DropDown

### ISSUE THREAD

**Issue by niuniudd** [flet-dev/flet#1561]
**Description**

**Code example to reproduce the issue:**

```python
        self.pct_dropdown = Dropdown(
            width=330,
            icon=icons.PERCENT,
            text_size=13,
            hint_text="请选择事件类型 ",
            options=[
                dropdown.Option("pct-touch"),
                dropdown.Option("pct-motion"),
                dropdown.Option("pct-trackball"),
                dropdown.Option("pct-syskeys"),
                dropdown.Option("pct-nav"),
                dropdown.Option("pct-majornav"),
                dropdown.Option("pct-appswitch"),
                dropdown.Option("pct-flip"),
                dropdown.Option("pct-anyevent"),
                dropdown.Option("pct-pinchzoom"),
                dropdown.Option("pct-permission"),
            ],
        )
        self.add_pct_btn = ElevatedButton(
            text="+",
            width=165,
            bgcolor=colors.WHITE,
            color=colors.BLACK,
            style=ButtonStyle(
                shape=RoundedRectangleBorder(radius=5),
            ),
            on_click=self.add_pct_clicked,
        )
        self.del_pct_btn = ElevatedButton(
            text="-",
            width=165,
            bgcolor=colors.WHITE,
            color=colors.BLACK,
            style=ButtonStyle(
                shape=RoundedRectangleBorder(radius=5),
            ),
            disabled=True,
            on_click=self.del_pct_clicked,
        )
    def add_pct_clicked(self, e):
            self.pct_dropdown.options.remove(self.pct_dropdown.value)
            self.pct_dropdown.value = ""
            self.pct_dropdown.update()
```

**Describe the results you received:**
![image](https://github.com/flet-dev/flet/assets/14904226/a8eb70c8-5db2-4e49-b8dc-0e065f0f8f5f)
errors:
 line 285, in add_pct_clicked
    self.pct_dropdown.options.remove(self.pct_dropdown.value)
ValueError: list.remove(x): x not in list

**Describe the results you expected:**
1.when I clicked add_pct_btn,remove one option I selected in "self.pct_dropdown "
2.I selected noting in "self.pct_dropdown "

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.7.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: D:\Python\Python311\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Windows11

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Please build up a better and simpler example exposing just the issue.

**Comment by FeodorFitsner** [comment]
I think I know what's going on. `options` is a list of `dropdown.Option` objects and you cannot remove an element from it by `value` which is a string.

You have to find an option you'd like to delete by a key/value first and then remove it from the list.

**Comment by ndonkoHenri** [comment]
Yeah you are right.
@niuniudd check this: https://flet.dev/docs/controls/dropdown#change-items-in-dropdown-options

**Comment by FeodorFitsner** [comment]
Right, though I think find option in that example could be replaced with one-liner lambda ;)

**Comment by niuniudd** [comment]
@FeodorFitsner @ndonkoHenri Thank you for your help,I knew why, and  resolved it
