### ISSUE TITLE
get_directory_path issue

### ISSUE THREAD

**Issue by markosster** [flet-dev/flet#1562]
Function **get_directory_path** closes application's window after on_click event. Specifically after the dialog window closes it freezes the app for about 2-3 seconds and then terminates the application.

**Code:**

Test example from: https://github.com/flet-dev/flet/issues/1297

Mainly i found this on my code and i tried to test it for clearness with this simple example and it came out that it does not work on it either, so i post the simple one bellow.

```python
import flet as ft


def main(page: ft.Page):
    page.theme_mode = "light"

    def result(e):
        page.add(ft.Text("result :)"))

    my_dialog = ft.FilePicker(on_result=result)

    page.overlay.append(my_dialog)

    page.add(
        ft.Row(
            [
                ft.ElevatedButton("Pick", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.pick_files()),
                ft.ElevatedButton("Save", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.save_file()),
                ft.ElevatedButton("Get Dir", icon=ft.icons.UPLOAD_FILE,
                                  on_click=lambda _: my_dialog.get_directory_path()),
            ]
        )
    )


ft.app(target=main)
```

**Results:**

- In the above example will print the text message from the **result** function, but after it will close the app.

**Additional information:**

 - **pick_files** and **save_file** works fine.

**Flet version**:

```
Name: flet
Version: 0.8.0
```

**Operating system**:

- Windows 11

**Comment by hokaso** [comment]
It is indeed this error. The problem I found is exactly as you described. Thank you very much for your report. [https://github.com/flet-dev/flet/issues/1563](#1563 )

**Comment by hokaso** [comment]
@markosster Is this problem solved?

**Comment by markosster** [comment]
@hokaso Yes. I tested it with the latest version of flet (0.8.2) and it doesnt crash.

**Comment by slashfast** [comment]
> @hokaso Yes. I tested it with the latest version of flet (0.8.2) and it doesnt crash.

I have this issue still present in `flet==0.8.2` on Windows 11, however on macOS Ventura everything works correctly.
