### ISSUE TITLE
"FilePicker" crashed when select special folder

### ISSUE THREAD

**Issue by hokaso** [flet-dev/flet#1563]
When using "FilePicker" to select a folder with a large number of files or a large volume of files, the flet framework suddenly crashes without any output logs or prints

![20230707232520_rec_](https://github.com/flet-dev/flet/assets/26475781/18ee576c-bf5e-4ed1-bd97-6fc2457ee210)

**Comment by FeodorFitsner** [comment]
What error do you get?

**Comment by markosster** [comment]
I also encountered the same issue https://github.com/flet-dev/flet/issues/1562. It does not throw any error at all. It just terminates the program.

**Comment by hokaso** [comment]
> What error do you get?

nothing, just crash... I also think it's very strange. It's rare for me to just flash back without throwing any errors.
