### ISSUE TITLE
Flet iOS client: add  url scheme to import flet apps (so camera app recognizes and launches)

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#1568]
**Please Describe The Problem To Be Solved**

The current Flet iOS app client app allows remote projects to be imported by adding url to a flet project. The [blog post ](https://flet.dev/docs/guides/python/testing-on-ios) mentions using a QR code to import projects. This is a game changer feature as it would allow Flet apps to be launched/installed by merely scanning a QR code!

The camera app on iOS has built in QR reader. But when it detects the flet qr code, it launches _safari_ instead of the Flet iOs Client app.

**(Optional): Suggest A Solution**

I believe the solution would be to add, and standardize, a flet url scheme. something like:

fletapp://gallery.flet.dev/calculator/

A dev would [create a QR code](https://www.qr-code-generator.com/) with that link, and produce a code like this

![Screen Shot 2023-07-08 at 7 44 34 AM](https://github.com/flet-dev/flet/assets/11970940/ae13a169-2761-4508-b0cd-4be04fd67b24)

(that qr code contains the proposed flet app url scheme to the calculator app...however note that the calculator app needs to be a flet server based app  and the one in gallery isnt)

The user would point the camera app to the code, and it would recognize the url scheme and launch the Flet iOS Client app passing along the flet app url. 

Developers would be able to do this with their own apps having flet mini apps launch within their own Flet shell container. Essentially a way to side load functionality into an app for fun and profit!

A guide to url schemes can be found here 

http://web.archive.org/web/20160103151535/http://iosdevelopertips.com/cocoa/launching-your-own-application-via-a-custom-url-scheme.html

https://stackoverflow.com/questions/4462612/link-to-automatically-open-my-app

**Comment by FeodorFitsner** [comment]
That's the thing, it's already support custom URL scheme: "flet://". I've just tested on two other iPhones which never had Flet app and I was able to see "Open in Flet" in Camera app and follow by opening Flet app. All phones have the latest iOS. Can you try going to flet://some/url in safari and see "Open in Flet"? What version of iOS you have?

**Comment by SKbarbon** [comment]
@FeodorFitsner it does open flet app, but does not open the host season. Is that fine ?

**Comment by FeodorFitsner** [comment]
That URL in the issue is a fake. Follow the guide to test your app in Flet app: https://flet.dev/docs/guides/python/testing-on-ios/

**Comment by ndonkoHenri** [comment]
It showed the message. Accepting redirected me to the flet app.
iPhone X iOS V16.3.1

**Comment by hololeo** [comment]
The issue i had was i went to a flet app that was running online, then used the chrome 'create qr code' which takes the pages url and makes a qr code. i then scanned that with camera app, and it tried to open it in safari.

I now i understand that is because the page is 'https://' and not 'flet://'. So i guess we cant have both...an online web flet app that is recognized by the flet iOS camera schema launcher.  The developer will have to take the extra step to make a 'flet qr code'

Go ahead and close this issue since as you say its already supported

**Comment by FeodorFitsner** [comment]
Yeah, to open an app on specific https://domain there is some elaborated procedure for registering domain with Apple.
