### ISSUE TITLE
When I set the page.window_width and page.window_height , it will show default window with default size and pos first!!!

### ISSUE THREAD

**Issue by yyqdata** [flet-dev/flet#1570]
As the title say:
![image](https://github.com/flet-dev/flet/assets/19744586/81f54524-7211-480d-ba70-d25f7efaf38f)
This is the first open init window attr debug info.It will run before my main function.
This will cause a bad experience, how can i avoid this issue?

**Comment by FeodorFitsner** [comment]
Hide window on start: https://github.com/flet-dev/examples/blob/0b0c25be1947637751ce85ca0f134a974b9beed5/python/controls/page/window-hidden-on-start.py#L14

Set window size and position and then make it visible.

**Comment by ndonkoHenri** [comment]
Hacky!
