### ISSUE TITLE
Assets dir and manifest does not work in 0.8.1

### ISSUE THREAD

**Issue by Omer-Farooqui** [flet-dev/flet#1573]
**Description**

The assets dir and manifest.json files and not working properly. If you nest a directory inside of assets, eg. "/assets/images/image.png" the file is not detected. This issue only occurs in the latest version (0.8.1), downgrading seems to fix the issue.
**Code example to reproduce the issue:**

```python
import flet as ft


def main(page:ft.Page):

    page.add(
        ft.Image(
            src='/images/image.png'
        )
    )

ft.app(target=main, view=ft.WEB_BROWSER, assets_dir='./assets', port=8080)
```

**Describe the results you received:**

Empty page
**Describe the results you expected:**

I expected the program to display and image.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/muddi/Coding-Projects/App/.venv/lib64/python3.11/site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:

Fedora 37
**Additional environment details:**
Using python 3.11.3 in a venv.

**Comment by viniciusgruske** [comment]
+1
