### ISSUE TITLE
flet pack is broken in version 0.8.1

### ISSUE THREAD

**Issue by yoolang** [flet-dev/flet#1580]
**Description**

**Code example to reproduce the issue:**

```python
flet pack main.py 
```

**Describe the results you received:**

Please install PyInstaller module to use flet pack command: cannot import name 'safe_tar_extractall' from 'flet.utils' (/.venv/lib/python3.9/site-packages/flet/utils/__init__.py)

**Describe the results you expected:**

A self-contained .app is generated in the dist directory

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried to change the `from flet.utils import safe_tar_extractall` in "/.venv/lib/python3.9/site-packages/flet/__pyinstaller/macos_utils.py" to the `from flet_runtime.utils import safe_tar_extractall`, and then execute `flet pack main.py ` again , packaging is successful

so, is this code wrong? 

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /.venv/lib/python3.9/site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:
macOS Ventura
version 13.4.1
**Additional environment details:**

**Comment by gdszps** [comment]
same error

**Comment by yoolang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信已收到。
