### ISSUE TITLE
ImportError: cannot import name 'git' from 'plumbum.cmd'

### ISSUE THREAD

**Issue by wangbaoyi** [flet-dev/flet#1581]
![image](https://github.com/flet-dev/flet/assets/59977623/d2cdaab2-af43-403b-92fb-6f7ee333b653)
![image](https://github.com/flet-dev/flet/assets/59977623/a9fae072-956d-42c5-9a40-41c95cda7674)

**Comment by wangbaoyi** [comment]
I am inputting flet run main.py -d An error occurred

**Comment by rkleivel** [comment]
Hi! You probably need to install git first - check discussion https://github.com/flet-dev/flet/discussions/1576

**Comment by rkleivel** [comment]
> No, no, I just intentionally reinstalled the system and installed Git, but the same error still occurred!!!

What OS are you on?

**Comment by wangbaoyi** [comment]
![image](https://github.com/flet-dev/flet/assets/59977623/f4d0e1fb-88a0-40f1-8ae0-eee49aadb341)

**Comment by wangbaoyi** [comment]
I used to be able to use it, but I don't know what happened. Recently, it's just like this, maybe it's related to the version

**Comment by wangbaoyi** [comment]
![cmd_PXoekfxXHL](https://github.com/flet-dev/flet/assets/59977623/8fc54fd3-0f7c-48f4-89a9-f8b758af75e3)

**Comment by wangbaoyi** [comment]
I plan to restart my computer and test again. If it still doesn't work, I can only ask the developer for help to take a look. The most outrageous thing is that this feature really worked before

**Comment by rkleivel** [comment]
What happens if you just type `git` in the cmd window?

**Comment by wangbaoyi** [comment]
Wow, thank you for your prompt!!! Originally, this does not support temporary environments...

**Comment by wangbaoyi** [comment]
Wow, thank you for your prompt!!! Originally, this does not support temporary environments...

**Comment by wangbaoyi** [comment]
Do you have WeChat? Let's get to know each other

**Comment by wangbaoyi** [comment]
![notepad_7ffjVVGvFY](https://github.com/flet-dev/flet/assets/59977623/075ebc89-901d-4751-82a8-e1d6d8846d13)
The problem has been identified, mainly due to the console issue. I did not add the environment variable for git, which resulted in an error!!!.

**Comment by ndonkoHenri** [comment]
Happy you found the solution.
Please don't forget to close the issue.

**Comment by rkleivel** [comment]
> Happy you found the solution. Please don't forget to close the issue.

Just wondering, @ndonkoHenri, if flet at least should give a better error message than crashing if it is expected that git must be available for flet to run(?)
