### ISSUE TITLE
Code example broken on https://flet-controls-gallery.fly.dev/layout/row

### ISSUE THREAD

**Issue by suncore** [flet-dev/flet#1583]
The following code example does not run:
Go to: Code example broken on https://flet-controls-gallery.fly.dev/layout/row
Click on the <> on the "row spacing" example (first on the page).
Copy paste into a python file and try to execute. I get a syntax error on trying to run it.

**Comment by heximing** [comment]
The gallery samples might be old. A lot of the codes in the gallery are broken.
The codes in tutorial is good. For the same code you are looking at, the code here `https://flet.dev/docs/controls/row` (the first example) is working fine.
