### ISSUE TITLE
did_mount being called with page as None

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1586]
I have a `did_mount` call being called with `page` == None.  This does not occur all the time and only appears if I switch displayed controls relatively quickly.  I know you will ask for sample code, I am working on it, but again my app is very complex so it is hard to recreate.

Stack Trace
<img width="266" alt="Screenshot 2023-07-12 at 09 46 26" src="https://github.com/flet-dev/flet/assets/770473/cf98aa01-3266-47b2-b622-6b6407f6f2c8">

`_handle_mount_unmount calling my `did_mount` function with a None page
<img width="673" alt="Screenshot 2023-07-12 at 09 47 07" src="https://github.com/flet-dev/flet/assets/770473/d3f2bf40-9b71-48ba-a281-3d12972fbe55">

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
```

**Operating system**:
 MacOS 

**Additional environment details:**

**Comment by gbrandt** [comment]
This appeared to be 100% my bad.  I have a thread that fetches data via an api.  When the data is fetched the same thread calls the .update function.  But if a user clicks to change the page while the update function is being called, it disappears from under the thread.  This showed as page being None, or in some cases an update failing by not finding control ID's.

**Comment by FeodorFitsner** [comment]
Thanks for the update. For cases like this you could think about synchronizing access to a page object with a lock.
