### ISSUE TITLE
conflict with supabase

### ISSUE THREAD

**Issue by JulimPark** [flet-dev/flet#1592]
hello.
I started studying flet not too long ago.
I'm running into a problem with dependencies while testing publishing a static webpage to cloudflare that integrates with supabase to input/output to a database.
How should I approach it?

[https://github.com/JulimPark/flet_test2](url)

02:01:07.756 | INFO: pip is looking at multiple versions of flet-runtime to determine which version is compatible with other requirements. This could take a while.
02:01:07.767 | ERROR: Cannot install -r requirements.txt (line 2) and flet because these package versions have conflicting dependencies.
02:01:07.767 |  
02:01:07.767 | The conflict is caused by:
02:01:07.768 | supabase 1.0.3 depends on httpx<0.24.0 and >=0.23.0
02:01:07.768 | flet-runtime 0.8.2 depends on httpx<0.25.0 and >=0.24.1
02:01:07.768

<br class="Apple-interchange-newline">

**Comment by FeodorFitsner** [comment]
Supabase must be supported for sure. So, what would be solution for that: change Flet's dependency to 0.23.0?
