### ISSUE TITLE
Flet delivers double click as two single clicks

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1610]
When a container is double clicked, flet sends two on-click message to my app.  Making me responsible for handling the double click or disregarding it

The operating system knows the difference between and click and double click and the correct event should be fired.  In the example below, the double click updates the value twice when really no event should be fired.  If I double click a button and only want to handle single clicks, I have to put in special handling code to see if a click came through and disregard the other.  I attempted to disable the button on the first click but on a slow connection the second click comes through before I can disable the button.

```python
import flet as ft


def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(value="0", text_align=ft.TextAlign.RIGHT, width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,
        )
    )


ft.app(target=main, view=ft.AppView.WEB_BROWSER)

```

**Describe the results you received:**
The counter in the sample application goes up by two on a double click because it received two single click events  

**Describe the results you expected:**
A double click is ignored since there is no handler for it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0

```

**Operating system**:

macOS Ventura
**Additional environment details:**

**Comment by gbrandt** [comment]
This occurs on slower connections where the web socket is not fast enough for me to disable the button

**Comment by gbrandt** [comment]
updated ticket with more info.

**Comment by ndonkoHenri** [comment]
`on_click` is designed to respond to every clicks (double-click =  2 clicks).

However, to achieve the behaviour you expected, you can introduce a flag, which will prevent the second click of the double-click from being considered/handled.

Below is an example:
```python
import asyncio
import flet as ft


def main(page: ft.Page):
    button_disabled = False

    async def plus_click(e):
        nonlocal button_disabled
        if button_disabled:
            return
        field.value = str(int(field.value) + 1)
        page.update()

        button_disabled = True
        await asyncio.sleep(0.3)
        button_disabled = False

    page.add(
        ft.Row(
            controls=[
                field := ft.TextField(
                    value="0", text_align=ft.TextAlign.RIGHT, width=100
                ),
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
        )
    )


ft.app(main)
```
