### ISSUE TITLE
Dropdown box option text exceeds the dropdown box

### ISSUE THREAD

**Issue by andlike** [flet-dev/flet#1622]
![微信截图_20230724025648](https://github.com/flet-dev/flet/assets/9100593/7df307ca-21f8-41c8-9589-0d81e4511a76)

**Comment by andlike** [comment]
resolved

**Comment by BC-clegras** [comment]
@andlike do you remember how you fixed this issue? I'm running into something similar.

**Comment by manakov-dev** [comment]
Faced same issue, resolved by adding  alignment=center_left to dropdown

**Comment by BC-clegras** [comment]
Yup, that worked. Thanks!
