### ISSUE TITLE
New tab using url_target="_blank" uses same session

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1629]
If I have a button that opens a new page on the same app, or the app itself, it uses the same session and any changes on the new tab reflect in the original tab.

**Code example to reproduce the issue:**

Start the app, click the new tab button.  Any action to increase the value in the first tab are also shown in the second tab
```python
import flet as ft


def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,
        )
    )

    page.add(ft.ElevatedButton("new tab", url="http://127.0.0.1:3000", url_target="_blank"))


ft.app(target=main, view=ft.WEB_BROWSER)

```

**Describe the results you received:**

Any action to increase the value in the first tab are also shown in the second tab

**Describe the results you expected:**

The new tab should start a new session, not use the existing session.  If I just open a new tab and type the address in the URL, a  new session is started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
```

**Operating system**:

macOS, tested in Safari and Firefox

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
I found this which looks like our case: https://stackoverflow.com/questions/20879714/how-to-prevent-sessionstorage-being-inherited-when-using-target-blank-window

I could be mistaken, but `url_launcher`, the package we use in Flet to follow URLs, uses [`window.open`](https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L71). Someone suggests adding `'noopener=true'` which could be a solution. We can try that. Let's mark this issue as a bug.

**Comment by FeodorFitsner** [comment]
...and this [could be a solution](https://stackoverflow.com/questions/24382266/sessionstorage-is-not-empty-when-link-opened-in-new-tab-in-internet-explorer/35596134#35596134) from a different angle - store session data in `window.name`. Could work for Flet as it stores only session ID in a tab session.
