### ISSUE TITLE
Start is slow when packed on MacOS M1.

### ISSUE THREAD

**Issue by Shu-Ji** [flet-dev/flet#1632]
**Description**

**Code example to reproduce the issue:**

```python
The Counter Demo
```

**Describe the results you received:**

<img src="https://github.com/flet-dev/flet/assets/1127594/7d0102ad-ab09-4bd6-81a5-9313013b28b5" width="500"/>

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: None
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: ~/.virtualenvs/py39/lib/python3.9/site-packages
Requires: flet-runtime, pydantic, websocket-client, copier, qrcode, watchdog, websockets, packaging
Required-by:
```

**Operating system**:

MacOS M1

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Try the new packaging method with [`flet build`](https://flet.dev/docs/guides/python/packaging-app-for-distribution).
