### ISSUE TITLE
`Chip` control

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#1636]
https://api.flutter.dev/flutter/material/Chip-class.html

**Comment by InesaFitsner** [comment]
https://docs.google.com/spreadsheets/d/1eGNcUTcx1gfVSYhaipSMiUwPi-yoco0fOBpYfm_gb9w/edit?usp=sharing

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/pull/1973
