### ISSUE TITLE
Feature: Add Scaffold and Drawer

### ISSUE THREAD

**Issue by StanMathers** [flet-dev/flet#164]
https://api.flutter.dev/flutter/material/Drawer-class.html

**Comment by FeodorFitsner** [comment]
Scaffold is already part of a `Page`/`View`. Re: Drawer - it could be implemented, yes. My only concern it's going to look old-ish as M3-version of it is still in the works: https://github.com/flutter/flutter/issues/103551.

Wondering if we could do some better replacement for it, like flying-in container with animation?...

**Comment by ndonkoHenri** [comment]
> My only concern it's going to look old-ish as M3-version of it is still in the works: flutter/flutter#103551.

Issue fixed.

**Comment by FeodorFitsner** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/1089
