### ISSUE TITLE
The repository does not have CONTRIBUTING.md

### ISSUE THREAD

**Issue by mr-tafreshi** [flet-dev/flet#165]
The repository does not have CONTRIBUTING.md. And this causes confusion in the contribution and also the reduction of contributions

**Comment by FeodorFitsner** [comment]
Thanks for your interest! What would you like to contribute and what would you like to see in that document?

**Comment by LeMeteore** [comment]
May I respectfully suggest an [example](https://github.com/python/mypy/blob/master/CONTRIBUTING.md) ?

**Comment by LeMeteore** [comment]
> So, we have this https://github.com/flet-dev/flet/blob/main/sdk/python/CONTRIBUTING.md for contributing to Python part of the project. 

Please receive all my apologies. I was looking for the `CONTRIBUTING.md` file in the root folder :\ then looked for a pinned issue, then I've seen this ticket. 

Maybe some issues (pointing to the right CONTRIBUTING.md files) should be made and [pinned](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository), to make them quickly visible by all the users. [Here](https://github.com/python/typeshed/issues) is an example.

> Are you guys looking to the same doc for Flutter part of the project?

Not for the moment (as far as I'm concerned). I'll see if I can help in the Python part of the project (Thanks for pointing me to where I can give one hand). Thanks for your time and for the awesome project \o/

**Comment by FeodorFitsner** [comment]
No worries, thanks for your interest!

I will look into pinned issues - so much to learn these days :)

**Comment by techemmy** [comment]
> Thanks for your interest! What would you like to contribute and what would you like to see in that document?

I'm looking to contribute to the python part of the code since that's the only one I'm knowledgeable in out of all languages you use.

**Comment by FeodorFitsner** [comment]
There is contributing guide now in the root of the repo: https://github.com/flet-dev/flet/blob/main/CONTRIBUTING.md
