### ISSUE TITLE
Expention raised when trying to update controls that are not displayed in the current url

### ISSUE THREAD

**Issue by Soif2Sang** [flet-dev/flet#1654]
I'm using Flet 7.4 and I can update controls that are not displayed on the current url/route. Once I updated to the latest version, an execption is raised when trying to update these controls.

**Comment by FeodorFitsner** [comment]
That's right, `page` was not clearing when removing control from a page/view, thus causing confusion and unpredictable behaviours. What is your use case? Can you provide a code to repro?
