### ISSUE TITLE
Page width and height are zero on app restart

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1655]
If I run the test app, it opens a browser window.  When I open a second browser and run the app everything works as expected.  However when I quit the app and restart it, the second browser reconnects and width and height al always 0

1.  Run the test app, it opens in a browser (B1)
2. Start another browser (B2) (ie if B1 is chrome, start Firefox)
3. CTRL-C the app and run it again
4. B2 reconnects but page width and height are 0.0

I understand this is not a normal use case, but it can occur if I update an in the field app while someone is on.  I have not been able to reproduce (because I cannot cause the event to occur), but I believe that this also occurs on a disconnect/reconnect sequence.  In my app I also lose all my session variables.

```python
import flet as ft


def main(page):
    print(f"width {page.width}, height {page.height}")

    def btn_click(e):
        print(f"width {page.width}, height {page.height}")
        if not txt_name.value:
            txt_name.error_text = "Please enter your name"
            page.update()
        else:
            name = txt_name.value
            page.clean()
            page.add(ft.Text(f"Hello, {name}!"))

    txt_name = ft.TextField(label="Your name")

    page.add(txt_name, ft.ElevatedButton("Say hello!", on_click=btn_click))


ft.app(target=main, view=ft.AppView.WEB_BROWSER)

```

**Describe the results you received:**

on reconnect after restart page width and height are 0

**Describe the results you expected:**

on reconnect page width and height should be set to actual values. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.8.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
```

**Operating system**:

MacOS 13.5

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Just from trying this with the latest version but I dont get different values from those before. 
Please try and if it occurs, share a screen recording.
