### ISSUE TITLE
auth import causes error in static website

### ISSUE THREAD

**Issue by trigress09** [flet-dev/flet#1657]
**Description**
My app uses flet.auth. Everything works fine during my testing. As soon as I run "flet publish" to create a static website, it says flet.auth module not found in the browser console. I also tried flet_runtime, but this module is not found either. The app is opened properly with python http.server.
 

**Code example to reproduce the issue:**
Open any example and add this to the import section.
```python
from flet.auth.providers import OAuthProvider
```
Then compile it as static website.

**Describe the results you received:**
ModuleNotFoundError: No module named 'flet.auth'

**Describe the results you expected:**
the static website should compile to the same as the web app

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
```
Name: flet
Version: 0.9.0.dev1623
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\inspiron5425\appdata\roaming\python\python310\site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:
Windows 11

**Additional environment details:**

**Comment by 04nada** [comment]
I believe this issue is mainly from the "breaking change" in the changelog incorrectly specifying the import for `OAuthProvider` (and other more specific `OAuthProvider` instances, such as `GitHubOAuthProvider`).

Instead of `from flet.auth.providers import OAuthProvider`, try using `from flet_runtime.auth.oauth_provider import OAuthProvider` for your header.
