### ISSUE TITLE
scroll_to with zero duration does nothing

### ISSUE THREAD

**Issue by suncore** [flet-dev/flet#1659]
Calling the .scroll_to() method (on e.g. a listview) with a duration unset or zero does not scroll the listview at all. It seems to work poorly on duration values smaller than 500.
I have listviews with 2000 lines and it seems to "need" at least 500ms to scroll it properly. My graphics are a bit slow since it is over vnc, but that should not be a factor in this.

**Comment by FeodorFitsner** [comment]
Indeed, it doesn't do anything with `duration=0`, but it works just fine with `duration=1`:

```python
import flet as ft


def main(page: ft.Page):
    lv = ft.ListView(spacing=10, padding=20, height=200, width=200)
    for i in range(0, 1000):
        lv.controls.append(ft.Text(f"Line {i}"))

    page.add(
        ft.Container(lv, border=ft.border.all(1)),
        ft.ElevatedButton(
            "Scroll!", on_click=lambda _: lv.scroll_to(offset=-1, duration=1)
        ),
    )


ft.app(target=main)
```


https://github.com/flet-dev/flet/assets/5041459/d3c624fa-935f-4f08-89c7-265a453c52bb

**Comment by FeodorFitsner** [comment]
I think it makes sense to default duration to `1` if `0` specified by a user.
