### ISSUE TITLE
After set parameter view=AppView.WEB_BROWSER,I received some error

### ISSUE THREAD

**Issue by niuniudd** [flet-dev/flet#1663]
**
After set parameter view=AppView.WEB_BROWSER,I received some error

**

**Code example to reproduce the issue:**

```
import os
import flet as ft

os.environ["FLET_WS_MAX_MESSAGE_SIZE"] = "8000000"

def main(page: ft.Page):
    r = ft.Row(wrap=True, scroll="always", expand=True)
    page.add(r)

    for i in range(5000):
        r.controls.append(
            ft.Container(
                ft.Text(f"Item {i}"),
                width=100,
                height=100,
                alignment=ft.alignment.center,
                bgcolor=ft.colors.AMBER_100,
                border=ft.border.all(1, ft.colors.AMBER_400),
                border_radius=ft.border_radius.all(5),
            )
        )
    page.update()

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

**Describe the results you received:**

D:\Python\Python311\python.exe E:\study\flet_prj\web\test\main.py 
Traceback (most recent call last):
  File "E:\study\flet_prj\web\test\main.py", line 26, in <module>
    ft.app(target=main, view=ft.AppView.WEB_BROWSER)
  File "D:\Python\Python311\Lib\site-packages\flet_runtime\app.py", line 97, in app
    __app_sync(
  File "D:\Python\Python311\Lib\site-packages\flet_runtime\app.py", line 134, in __app_sync
    conn = __connect_internal_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\flet_runtime\app.py", line 376, in __connect_internal_sync
    conn = SyncWebSocketConnection(
           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Connection.__init__() got an unexpected keyword argument 'server_address'

进程已结束,退出代码1

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
D:\Python\Python311\Scripts>pip list|findstr flet
WARNING: Ignoring invalid distribution ~let (C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages)
flet-core                 0.8.4
flet-runtime              0.8.4
WARNING: Ignoring invalid distribution ~let (C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~let (C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~let (C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages)

D:\Python\Python311\Scripts>pip show flet-core
WARNING: Ignoring invalid distribution ~let (C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages)
Name: flet-core
Version: 0.8.4
Summary: Flet core library
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: D:\Python\Python311\Lib\site-packages
Requires: repath
Required-by: flet-runtime
```

**Operating system**:

Windows11

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
I can't see anything wrong with the code. Looks like something wrong with Flet installation while looking at the error and those pip warnings.

Re-install Flet. Delete all `flet-*` packages and install flet again.
