### ISSUE TITLE
Multiple dialogs (AlertDialog) will create a ghost dialog

### ISSUE THREAD

**Issue by litalidev** [flet-dev/flet#1670]
**Description**
When open 1 dialog, close it and open another dialog, after closing the second dialog, a ghost dialog appeared.

**Code example to reproduce the issue:**

```python
import flet as ft
import time

def main(page: ft.Page):
    page.title = "AlertDialog examples"

    dlg = ft.AlertDialog(
        title=ft.Text("Hello, you!"), on_dismiss=lambda e: print("Dialog dismissed!")
    )

    def close_dlg(e):
        dlg_modal.open = False
        page.update()

    def close_dlg_msgbox(e):
        dlg_msgbox.open = False
        page.update()

    def show_msgbox(e):
        close_dlg(e)
        #time.sleep(.1)
        page.dialog = dlg_msgbox
        dlg_msgbox.open = True
        page.update()

    dlg_msgbox = ft.AlertDialog(
        title=ft.Text("Info"),
        modal=True,
        content=ft.Text("Files deleted"),
        actions=[
            ft.TextButton("Close", on_click=close_dlg_msgbox),
        ],
        actions_alignment=ft.MainAxisAlignment.END,
        on_dismiss=lambda e: print("Modal dialog dismissed!"),
    )

    dlg_modal = ft.AlertDialog(
        modal=True,
        title=ft.Text("Please confirm"),
        content=ft.Text("Do you really want to delete all those files?"),
        actions=[
            ft.TextButton("Yes", on_click=show_msgbox),
            ft.TextButton("No", on_click=close_dlg),
        ],
        actions_alignment=ft.MainAxisAlignment.END,
        on_dismiss=lambda e: print("Modal dialog dismissed!"),
    )

    def open_dlg(e):
        page.dialog = dlg
        dlg.open = True
        page.update()

    def open_dlg_modal(e):
        page.dialog = dlg_modal
        dlg_modal.open = True
        page.update()

    page.add(
        ft.ElevatedButton("Open dialog", on_click=open_dlg),
        ft.ElevatedButton("Open modal dialog", on_click=open_dlg_modal),
    )

ft.app(target=main)

```

**Describe the results you received:**
The source was copied from https://flet.dev/docs/controls/alertdialog/, add one more dialog (dlg_msgbox)

start -> "Open modal dialog" -> "Yes" -> "Close"

After clicking "Close", a ghost dialog appeared.

Depending on the modal of last dialog, the screen will be frozen by the ghost dialog if the last dialog's modal=True.

![image](https://github.com/flet-dev/flet/assets/9984614/2fb65aa9-889e-4ace-9d32-0978a1880d7c)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
If I add a sleep (between close dialog and open dialog), it may sometime fix it, but not 100%. 

**Flet version (`pip show flet`)**:
In fact, older version (e.g. 0.7.4) also have this bug
flet==0.8.4
flet-core==0.8.4
flet-runtime==0.8.4

```
(paste your output here)
```

**Operating system**:
Windows 11 Pro
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32

**Additional environment details:**

**Comment by gbrandt** [comment]
I can confirm this, I see it a lot and had to do many work arounds to stop double clicks from opening two dialogs.

My work around is to always call close_dialog before I call open dialog, sleep for 0.2 seconds and then open the new dialog.  The delay sucks but seems to prevent this issue.

**Comment by FeodorFitsner** [comment]
I can also confirm that this annoying problem exists - faced it while working on Flet Studio app. It happens when quickly switching between alert dialogs or/and snack bars. Adding delay (to finish previous exit animation) between dialogs helps, but it's, of course, a hack. Will be working on fixing this bug.

**Comment by daniethan** [comment]
Sometimes the AlertDialog shows up as a long white column with a dark background. Not showing the intended content. I experienced this in adroid while running the app on Flet Studio. Am still stuck.

**Comment by donolsch** [comment]
I can confirm I am facing the same issue when switching between two alert dialogs. Thus far, I wasn't able to fix it even when implementing a delay.

**Comment by FeodorFitsner** [comment]
@donolsch could you provide a code to repro?
