### ISSUE TITLE
Suffix button being clicked on a TextField control to clear its text crashes flet app.

### ISSUE THREAD

**Issue by coolninjaturtle** [flet-dev/flet#1674]
**Description**

Suffix button being clicked on a TextField control to clear its text crashes flet app. Note that this only happens when the view is set to FLET_APP and FLET_APP_WEB, **NOT when it is set to WEB_BROWSER**

**Code example to reproduce the issue:**

```python
    import flet as ft

    class SearchBar(ft.TextField):
        
        def __init__(self):
            super().__init__()
            self.hint_text = "Search"
            self.expand = True
            self.content_padding = 10
            self.border = ft.InputBorder.NONE
            self.autofocus = True
            self.suffix = ft.IconButton(on_click=self.clear_search, icon=ft.icons.CLOSE_ROUNDED)

        def clear_search(self, e):
            self.value = None
            self.update()


    def main(page: ft.Page):
        page.vertical_alignment = ft.MainAxisAlignment.START
        page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
        page.add(SearchBar())


    ft.app(target=main)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

as mentioned, it only happens in the app view, and the clearing mechanism works. its just that after the textfield is cleared the app crashes.

**Flet version (`pip show flet`)**:

Name: flet
Version: 0.8.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0

**Operating system**:

Windows 11

**Comment by coolninjaturtle** [comment]
also does not crash if the value of the TextField is already None. only crashes if the control actually has some text in it

**Comment by FeodorFitsner** [comment]
I'm testing with Flet 0.9.0.

Works on macOS.

Works on Windows 11 like a charm too:


https://github.com/flet-dev/flet/assets/5041459/c2bf8b8d-b775-4bae-b6ee-1cf1bc20154a

**Comment by ndonkoHenri** [comment]
Same on my end. Works as expected!
@coolninjaturtle, can you share a video showing the issue?
