### ISSUE TITLE
Disable `IconButton` ripple effect

### ISSUE THREAD

**Issue by tokitouq** [flet-dev/flet#1680]
How can I disable `IconButton` ripple effect?
![Screenshot from 2023-08-06 05-54-34](https://github.com/flet-dev/flet/assets/114811070/98767add-61cb-4a4e-8a40-88a56fb573d6)

code:
```py
ft.IconButton(icon=ft.icons.ADD, icon_size=20)
```

**Comment by tokitou-san** [comment]
Well here is a hacky way I used to fix this.
```py
ft.Container(
   content=ft.Image(
      src="icons/messenger-outline.svg",
      width=22,
      height=22,
      fit=ft.ImageFit.COVER,
      repeat=ft.ImageRepeat.NO_REPEAT
   ),
   on_click= # on click function
)
```

However it would be great if I can do something like this:
```py
ft.IconButton(
    icon=ft.icons.ADD,
    icon_size=2,
    show_ripple=False, # show ripple effect or no
    padding=0 # remove padding
)
```

**Comment by ndonkoHenri** [comment]
SO thread: https://stackoverflow.com/a/61348072
Link to prop: https://api.flutter.dev/flutter/material/IconButton/highlightColor.html
