### ISSUE TITLE
page didn`t display images  when I run the program in edge,then I set hot reload,the image can be displayed

### ISSUE THREAD

**Issue by niuniudd** [flet-dev/flet#1681]
**Description**

page didn`t display images  when i run the program in browser(edge),then I set hot reload,run the pragram,the image can be displayed

**Code example to reproduce the issue:**
```
self.appBAR = Container(
            content=Row(
                controls=[
                    Image(
                        src="./resoucres/images/logo3.png",
                        width=60, height=60,
                        border_radius=border_radius.all(5),
                        fit=ImageFit.COVER,
                        # color_blend_mode=BlendMode.COLOR
                    ),
                    FloatingActionButton(icon=icons.HOME, text="主页",
                                         shape=BeveledRectangleBorder(radius=1),
                                         on_click=self.switch_tab),
                    FloatingActionButton(icon=icons.PAGES, text="博客",
                                         shape=RoundedRectangleBorder(radius=1),
                                         on_click=self.switch_tab),
                    FloatingActionButton(icon=icons.CHAT, text="论坛",
                                         shape=CountinuosRectangleBorder(radius=1),
                                         on_click=self.switch_tab),
                    FloatingActionButton(icon=icons.BUG_REPORT, text="爬虫",
                                         shape=CountinuosRectangleBorder(radius=1),
                                         on_click=self.switch_tab),
]
)
)

self.t = Stack([
            Image(
                src="./resoucres/images/background.png",
                width=1000,
                height=800,
                fit=ImageFit.CONTAIN,
            ),
            Text("当前位置:主页"),

            ],
            width=1000,
            height=800,
        )
```

**Describe the results you received:**
run the program in browser:
![image](https://github.com/flet-dev/flet/assets/14904226/6a4dcde7-e91e-446b-b29a-aad5a958a03a)
set hot reload,display like this,the 2 images display success
![image](https://github.com/flet-dev/flet/assets/14904226/92ddec76-03fa-49b3-bd48-a02d1d13289b)

**Describe the results you expected:**

images should be displayed in browser

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

C:\Users\Administrator>pip show flet
Name: flet
Version: 0.9.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: D:\Python\Python311\Lib\site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets
Required-by:

**Operating system**:

Windows11

**Additional environment details:**
![image](https://github.com/flet-dev/flet/assets/14904226/ea747edb-df7c-4efe-92b1-d090df275248)

**Comment by tokitou-san** [comment]
Could you try use this [src pattern](https://flet.dev/docs/controls/image/#src) for `Image`

**Comment by ndonkoHenri** [comment]
Did you specify the `assets_dir`? And are the images you need present in it?

**Comment by niuniudd** [comment]
OK,Thank you,image loads for web/desktop app is different,I resolved it
