### ISSUE TITLE
Most sample applications won't load on gallery (only Chat app / Controls Gallery are loading)

### ISSUE THREAD

**Issue by alan-copeland-keysight** [flet-dev/flet#1688]
Seen on MacOS / Google Chrome and Windows 11 / Chrome.

The following apps are broken:
- https://gallery.flet.dev/todo/
- https://gallery.flet.dev/icons-browser/
- https://gallery.flet.dev/calculator/
- https://gallery.flet.dev/solitaire/
- https://gallery.flet.dev/trolli/#/
- https://gallery.flet.dev/flet-animation/
- https://gallery.flet.dev/counter/
- https://gallery.flet.dev/simple-routing/#/
- https://gallery.flet.dev/hello-world/
- https://gallery.flet.dev/greeter/

The following gallery apps ARE working:
- https://flet-controls-gallery.fly.dev/layout
- https://flet-chat.fly.dev/

**Comment by FeodorFitsner** [comment]
Thanks for letting know, working on it!

**Comment by FeodorFitsner** [comment]
It's been republished and is working now.
