### ISSUE TITLE
Feature: Update SnackBar attributes/properties

### ISSUE THREAD

**Issue by StanMathers** [flet-dev/flet#169]
I was working on a custom, editable component where I needed to use SnackBar, but it does not have all the properties Flutter has on its API, so I cannot finish it. (More precisely, I need backgroundColor and elevation)

https://api.flutter.dev/flutter/material/SnackBar-class.html

**Comment by FeodorFitsner** [comment]
I've added both `bgcolor` and `elevation`. Background color works, but I don't see any effect from changing `elevation` though. Is like a shadow snackbar drops? I tested with both M2 and M3 material themes, but no shadow visible.

Update: https://stackoverflow.com/a/60990588/1435891

**Comment by ndonkoHenri** [comment]
I never wanted to open a new issue after seeing this.

The `action` property of snackbars get's a string which will be displayed on the action button of the snackbar. OK!
But this action button lacks a customizable color. This forces me to choose a `bgcolor` which will possibly make my action button's text more visible.

Here is a link to [Flutter's SnackBarAction class ](https://api.flutter.dev/flutter/material/SnackBarAction-class.html) 

Is it possible to have it in Flet? If No, please tell me eventually ..why..

**Comment by FeodorFitsner** [comment]
You need this: https://api.flutter.dev/flutter/material/SnackBarAction/textColor.html?

**Comment by ndonkoHenri** [comment]
Yes Exactly.

**Comment by FeodorFitsner** [comment]
https://github.com/flet-dev/flet/issues/364
