### ISSUE TITLE
Assets behaviour Mac vs iOS

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1693]
### Discussed in https://github.com/flet-dev/flet/discussions/1692

<div type='discussions-op-text'>

<sup>Originally posted by **jean-david-ruvini** August  8, 2023</sup>
Hi,
I am having trouble displaying images in my app.

I have them in the "assets" folder next to my main.py.

I specify it this way:

ft.app(target=main, assets_dir="assets")

And load them this way:

ft.Image(
    src='./assets/'+se.merchants[0].logo,
    width=frontend_config.MERCHANT_IMG_WIDTH,
    height=frontend_config.MERCHANT_IMG_HEIGHT,
    fit=ft.ImageFit.CONTAIN
)

This works fine on IOS when running my app from "flet run --ios"
But the image doesn't show when I run the app on my macbook with "flet run"

If I change to this:
src=se.merchants[0].logo,

I have the opposite behavior: the image doesn't show with "flet run --ios" but shows with "flet run"

what am I missing?
Thanks for any help!
JD
</div>

**Comment by BadWolf1st** [comment]
I have the same problem.
On Windows, if I use src="./data/def/defAvatar", then everything works.
But if I use the same thing on Mac OS, it doesn't work.
![image](https://github.com/flet-dev/flet/assets/115115085/add74c5e-36cd-4a34-9a99-107c43307fe6)
![image](https://github.com/flet-dev/flet/assets/115115085/7959b4a7-5ffa-4223-9a7f-60d62b61914d)

**Comment by FeodorFitsner** [comment]
@BadWolf1st try removing `./` from the image path/URL.

**Comment by BadWolf1st** [comment]
@FeodorFitsner, I tried it, but the result didn't change in any way

**Comment by FeodorFitsner** [comment]
@BadWolf1st Your case seems different. Are you running the same app on macOS and Windows?

**Comment by BadWolf1st** [comment]
@FeodorFitsner, yes. Now I am writing a cross-platform application, for Windows, macOS and Linux. The only thing I haven't checked this problem on Linux, since I won't have access to a Linux computer until tomorrow.
My code:
`def getUserIcon(self, like: str = None, userID: str = None):
		"""
		The function `getUserIcon` retrieves the user icon based on the provided like and userID.
		
		:param like: The "like" parameter is used to filter the user icons based on a specific criteria. It
		is an optional parameter and can be set to a string value
		:type like: str
		:param userID: The userID parameter is used to specify the user for which you want to retrieve the
		icon. It is a string that represents the unique identifier of the user
		:type userID: str
		"""
		match system():
			case "Windows":
				print ("System is Windows") # DEBUG
				if like == "path":
					# return "./data/" + userID
					return "./data/defAvatar"
				elif like == "url":
					...
				else: return "./data/defAvatar"
			case "Darwin":
				print ("System is MacOS") # DEBUG
				if like == "path":
					# return "./data/" + userID
					return "data/defAvatar"
				elif like == "url":
					...
				else: return "data/defAvatar"
			case "Linux":
				...
			case _: # JAVA Machine
				sys.exit("This system is not supported by this program")`

**Comment by FeodorFitsner** [comment]
`./` should not be used at all.

**Comment by ndonkoHenri** [comment]
To make things simpler, use some basic code to display an image from an `assets` folder, as seen [here](https://flet.dev/docs/controls/image#src).

```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Image(src="/my-image.png"))

flet.app(
    target=main,
    assets_dir="assets"
)
```

Just like above, try removing the dot and leaving just the slash. (`src="/my-image.png"`)

Please also set `page.on_error=lambda e: print(e.data)` in the `main` function.
