### ISSUE TITLE
Flet App Android - FloatingActionButton issues

### ISSUE THREAD

**Issue by DavMelchi** [flet-dev/flet#1696]
when I add the app on android from the qrcode, there is the FloatingActionButton which is automatically added to the app.
![1](https://github.com/flet-dev/flet/assets/116588982/ec144ac0-d3b4-4d54-9dc1-e248e2472e1d)

But when open it manually with the link there is no problem.

![2](https://github.com/flet-dev/flet/assets/116588982/3cc8bcf5-b656-4f6c-b6d6-4a1f9deb20f4)

Also when you delete a project the `FloatingActionButton is duplicated` during the period of the notification: `projetc has been deleted`.
![3](https://github.com/flet-dev/flet/assets/116588982/44b645c4-60a9-4ebf-8bdc-5544ca76a27d)

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    page.theme_mode = "light"
    page.add(
        ft.SafeArea(
            ft.Container(
                     content=ft.Text("Hello Agent Flet!"),
                     expand=True,
                     ),
            )
    )

ft.app(target=main)
```

```shell
flet run .\main.py --android
```

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.9.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\Users\HP\Documents\PROJET FLUTTER\FLET\Flet_PreTest\.venv\Lib\site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Windows10  / Android 13

**Comment by niuniudd** [comment]
![image](https://github.com/flet-dev/flet/assets/14904226/9c2f55dc-06f2-4b61-b25f-7d79214ce042)
hi,I scanned the QR code by camera app,browser app, wechat,but nothing to change in my 2 phones(huawei,xiaomi),how do you  scan QR code?

**Comment by ndonkoHenri** [comment]
Use a better terminal/command line interface.
Some distort the QR code, causing information loss.

**Comment by niuniudd** [comment]
I already scanned successful,but also didn't open the flet app in phone
https://github.com/flet-dev/flet/assets/14904226/47cb5204-b57b-457d-80f7-38b76da49348

**Comment by DavMelchi** [comment]
@niuniudd  do you have flet app installed on your phone ?
https://play.google.com/store/apps/details?id=com.appveyor.flet&hl=fr&gl=US

**Comment by niuniudd** [comment]
> @niuniudd  do you have flet app installed on your phone ?
> https://play.google.com/store/apps/details?id=com.appveyor.flet&hl=fr&gl=US
> 
> 
> 

😂Yes,i must install it now,but I can't install google's apps in my HUAWEI phone,also didn't install flet app, I must get flet app by other resolutions

**Comment by FeodorFitsner** [comment]
It should be fixed now.
