### ISSUE TITLE
create border for one corner rounded Container(with border radius) failed.

### ISSUE THREAD

**Issue by tcbuger** [flet-dev/flet#1697]
**Description**

**Code example to reproduce the issue:**
if i dont create a four-side(same obj) border, i cant get a rounded corner.

**What happened:**
firstly, i have a Container, it only has one rounded corner(left top).
I used the border.all(), its okay.
```python
  border=border.all(width=0.9, color=colors.BLACK12, )
```
![image](https://github.com/flet-dev/flet/assets/52766219/8cf0957e-decc-4b44-b14b-3926e3744399)

But i just want the left side and top side have borders.
Because the right and bottom side is the side of the window. My app(windows) is frameless, If something under the app is white color, it will be very embarrassing.
so i used the border.only() /or create a Border obj by myself.  the problem came.
As shown in the picture below.
**only when the four side(4 properties of class BorderSide) is the same BorderSide object, it shows a rounded border, otherwise it shows a right-angled border.**
```python
Error Codes1:
  bd = BorderSide(width=1, color=colors.BLACK12)
  border=border.only(left=bd, top=bd)

Error Codes2:
  bd = BorderSide(width=1, color=colors.BLACK12)
  bd2 = BorderSide(width=1, color=colors.TRANSPARENT)
  border=border.only(left=bd, top=bd, bottom=bd, right=bd2)
```
![image](https://github.com/flet-dev/flet/assets/52766219/de5c2c30-c399-44b3-917a-c3d2ab33bfe3)

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
python version:
Python 3.8.17
```

```
flet version:
Name: flet
Version: 0.9.0
```

**Operating system**:
Windows 10

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
I'm not sure I understand the issue. Could you provide a complete, runnable repro please?

**Comment by tcbuger** [comment]
> I'm not sure I understand the issue. Could you provide a complete, runnable repro please?

like this:
```python
import flet
from flet import Page, Container, BorderRadius, border, BorderSide, Row, CrossAxisAlignment


def main(page: Page):
    page.window_width = 300
    page.window_height = 300
    bor = BorderSide(width=3)
    con = Container(
        border_radius=BorderRadius(top_left=50, top_right=0, bottom_left=0, bottom_right=0),
        border=border.only(left=bor, top=bor), # if i want only two sides, it cant suit the rounded corner
        #border=border.all(width=3), # if create 4 sides with one same BoederSide obj, its ok.
        bgcolor='blue',
        expand=True,
    )
    page.add(Row([con], vertical_alignment=CrossAxisAlignment.STRETCH, expand=True))


flet.app(target=main)

```
![image](https://github.com/flet-dev/flet/assets/52766219/68379b15-5025-4b8e-b7d1-8708884a850e)
![image](https://github.com/flet-dev/flet/assets/52766219/d2a9c06c-5eef-4136-98dd-83a0b0d56539)

**Comment by FeodorFitsner** [comment]
How about this:

```python
import flet
import flet as ft
import flet.canvas as cv


def main(page: ft.Page):
    page.window_width = 300
    page.window_height = 300

    def bgc_resize(e: cv.CanvasResizeEvent):
        bgc.shapes = [
            cv.Path(
                [
                    cv.Path.MoveTo(0, e.height),
                    cv.Path.LineTo(0, 50),
                    cv.Path.ArcTo(50, 0, 50),
                    cv.Path.LineTo(e.width, 0),
                ],
                paint=ft.Paint(
                    color=ft.colors.BLACK,
                    stroke_width=5,
                    style=ft.PaintingStyle.STROKE,
                ),
            ),
        ]
        bgc.update()

    bgc = cv.Canvas(content=ft.Text("AAA BBB CCC DDD"), on_resize=bgc_resize)
    con = ft.Container(
        bgcolor="blue",
        border_radius=ft.BorderRadius(
            top_left=50, top_right=0, bottom_left=0, bottom_right=0
        ),
        content=bgc,
        expand=True,
    )
    page.add(
        ft.Row([con], vertical_alignment=ft.CrossAxisAlignment.STRETCH, expand=True)
    )


flet.app(target=main)
```

![image](https://github.com/flet-dev/flet/assets/5041459/f247febd-0380-4d3a-99b4-28a3a676e8f7)

**Comment by ndonkoHenri** [comment]
@FeodorFitsner, the ethical hacker! :)

**Comment by tcbuger** [comment]
> 这个怎么样：
> 
> ```python
> import flet
> import flet as ft
> import flet.canvas as cv
> 
> 
> def main(page: ft.Page):
>     page.window_width = 300
>     page.window_height = 300
> 
>     def bgc_resize(e: cv.CanvasResizeEvent):
>         bgc.shapes = [
>             cv.Path(
>                 [
>                     cv.Path.MoveTo(0, e.height),
>                     cv.Path.LineTo(0, 50),
>                     cv.Path.ArcTo(50, 0, 50),
>                     cv.Path.LineTo(e.width, 0),
>                 ],
>                 paint=ft.Paint(
>                     color=ft.colors.BLACK,
>                     stroke_width=5,
>                     style=ft.PaintingStyle.STROKE,
>                 ),
>             ),
>         ]
>         bgc.update()
> 
>     bgc = cv.Canvas(content=ft.Text("AAA BBB CCC DDD"), on_resize=bgc_resize)
>     con = ft.Container(
>         bgcolor="blue",
>         border_radius=ft.BorderRadius(
>             top_left=50, top_right=0, bottom_left=0, bottom_right=0
>         ),
>         content=bgc,
>         expand=True,
>     )
>     page.add(
>         ft.Row([con], vertical_alignment=ft.CrossAxisAlignment.STRETCH, expand=True)
>     )
> 
> 
> flet.app(target=main)
> ```
> 
> ![图像](https://user-images.githubusercontent.com/5041459/260265062-f247febd-0380-4d3a-99b4-28a3a676e8f7.png)



> How about this:
> 
> ```python
> import flet
> import flet as ft
> import flet.canvas as cv
> 
> 
> def main(page: ft.Page):
>     page.window_width = 300
>     page.window_height = 300
> 
>     def bgc_resize(e: cv.CanvasResizeEvent):
>         bgc.shapes = [
>             cv.Path(
>                 [
>                     cv.Path.MoveTo(0, e.height),
>                     cv.Path.LineTo(0, 50),
>                     cv.Path.ArcTo(50, 0, 50),
>                     cv.Path.LineTo(e.width, 0),
>                 ],
>                 paint=ft.Paint(
>                     color=ft.colors.BLACK,
>                     stroke_width=5,
>                     style=ft.PaintingStyle.STROKE,
>                 ),
>             ),
>         ]
>         bgc.update()
> 
>     bgc = cv.Canvas(content=ft.Text("AAA BBB CCC DDD"), on_resize=bgc_resize)
>     con = ft.Container(
>         bgcolor="blue",
>         border_radius=ft.BorderRadius(
>             top_left=50, top_right=0, bottom_left=0, bottom_right=0
>         ),
>         content=bgc,
>         expand=True,
>     )
>     page.add(
>         ft.Row([con], vertical_alignment=ft.CrossAxisAlignment.STRETCH, expand=True)
>     )
> 
> 
> flet.app(target=main)
> ```
> 
> ![image](https://user-images.githubusercontent.com/5041459/260265062-f247febd-0380-4d3a-99b4-28a3a676e8f7.png)

**master level, tkx.**
