### ISSUE TITLE
Progressive Web Applications (PWA) done right!

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#17]
* [ ] Use localStorage instead of sessionStorage to track session when the app is installed as PWA
* [ ] Reduce reconnection timeout for faster dehydration
* [ ] Changing application icons: Windows, Linux, macOS, iOS, Android
* [ ] Changing application name, palette in manifest.json
* [ ] Banner control "Add this app to your desktop":
  * [ ] Chrome
  * [ ] Firefox
  * [ ] Edge
  * [ ] Safari
  * [ ] iOS Safari
  * [ ] Chrome on Android.

**Comment by ndonkoHenri** [comment]
The banner shows already right? 
Or you mean something else..

**Comment by frinkifail** [comment]
got anything done yet?

**Comment by FeodorFitsner** [comment]
Close this issue. Feel free to open specific issues related to PWA.
