### ISSUE TITLE
Insert a svg image(it have animation effect) into flet app,the image didn't animated

### ISSUE THREAD

**Issue by niuniudd** [flet-dev/flet#1702]
**Description**

Insert a svg image(it have animation effect) into flet app,the image didn't animated

**Code example to reproduce the issue:**

![IMG_20230810_161703.jpg](https://github.com/flet-dev/flet/assets/14904226/61863f1b-0184-4bb8-9e41-0c808b5a66af)

**Describe the results you received:**

https://github.com/flet-dev/flet/assets/14904226/281f67e3-919d-4c7c-a675-9f9e904f0f39

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
Name: flet
Version: 0.9.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: D:\Python\Python311\Lib\site-packages
Requires: copier, flet-runtime, packaging, pydantic, qrcode, watchdog, websocket-client, websockets

**Operating system**:

Windows11

**Additional environment details:**

**Comment by DimasRulit** [comment]
Bro. You didnt animate it lol.

**Comment by niuniudd** [comment]
> Bro. You didnt animate it lol.

The pictures themselves are already animated,What else do I need to do?
![大雨](https://github.com/flet-dev/flet/assets/14904226/0b3dcf32-4efa-4180-8434-9f45f876ce85)
![少云](https://github.com/flet-dev/flet/assets/14904226/64e0e9c9-211d-4e08-95c6-6e2659603f95)

**Comment by niuniudd** [comment]
In Browser,I found some details about the animation,in flet,only display the backgroud：cloud
![image](https://github.com/flet-dev/flet/assets/14904226/a14c5578-bf8a-46ca-8f39-bcc04e021a0a)

the code in the red box on the right:(transform="translate(191.5,343,5 xlink:href="#f") effect animation for the rain drop
Whether Flet can support this feature? 
![image](https://github.com/flet-dev/flet/assets/14904226/261ab49a-9aff-4d59-ae08-93cd60a40d04)

**Comment by FeodorFitsner** [comment]
Animated SVG are not supported. Flet uses [flutter_svg](https://github.com/dnfield/flutter_svg) library which never had intention supporting animated SVGs.

For animations in Flet apps we are going to support [Lottie](https://github.com/flet-dev/flet/issues/88) and [Rive](https://github.com/flet-dev/flet/issues/89). Show your interest there - vote and subscribe.
