### ISSUE TITLE
`GetPointerType` error on Windows 7

### ISSUE THREAD

**Issue by bistcuite** [flet-dev/flet#171]
When i ran a simple flet app for desktop, i got this error(Windows 7, latest flet version):
![Untitled](https://user-images.githubusercontent.com/85484922/183677728-c7817c1d-4062-44d5-a343-e062f5441480.png)

My code : 
```py
import flet
from flet import IconButton, Page, Row, TextField, icons

def main(page: Page):
    page.title = "Flet counter example"
    page.vertical_alignment = "center"

    txt_number = TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = int(txt_number.value) - 1
        page.update()

    def plus_click(e):
        txt_number.value = int(txt_number.value) + 1
        page.update()

    page.add(
        Row(
            [
                IconButton(icons.REMOVE, on_click=minus_click),
                txt_number,
                IconButton(icons.ADD, on_click=plus_click),
            ],
            alignment="center",
        )
    )

flet.app(target=main)
```

**Comment by FeodorFitsner** [comment]
It looks like Windows 7 is not supported by Flutter:
https://github.com/flutter/flutter/issues/108422
https://www.reddit.com/r/flutterhelp/comments/we8i6a/getpointertype_function_not_available_in_win7/

That Reddit thread suggests rebuilding the "shell", but I'm not sure what that means and honestly we don't have enough resources to deal with that right now.

Upgrade to Windows 10 or later 😳

**Comment by thautwarm** [comment]
I've successfully addressed this.
I just created a dummy MPFlat.dll and audioplayers_windows_plugin.dll and put them inside `site_packages/flet/bin/flet`, and it just works pretty fine on Windows 7 user machines.

@liudonghua123

**Comment by FeodorFitsner** [comment]
Nice hack, thanks for sharing!

**Comment by liudonghua123** [comment]
> I've successfully addressed this.
> I just created a dummy ~~MPFlat.dll and~~ audioplayers_windows_plugin.dll and put them inside `site_packages/flet/bin/flet`, and it just works pretty fine on Windows 7 user machines.
> 
> @liudonghua123 
> 

Excellent work. could you share your code? :😊

**Comment by thautwarm** [comment]
Just compile the following code into a shared library `audioplayers_windows_plugin.dll`, and replace the one in `site_packages/flet/bin/flet`.

```c
// audioplayers_windows_plugin_faker.c
// get symbols via `dumpbin`
__declspec(dllexport) void AudioplayersWindowsPluginRegisterWithRegistrar(void) { }

/*
Then compile it.
For windows/mingw64 users:
    gcc -shared -o audioplayers_windows_plugin.dll audioplayers_windows_plugin_faker.c
*/
```

**Comment by liudonghua123** [comment]
> Just compile the following code into a shared library `audioplayers_windows_plugin.dll`, and replace the one in `site_packages/flet/bin/flet`.
> 
> ```c
> // audioplayers_windows_plugin_faker.c
> // get symbols via `dumpbin`
> __declspec(dllexport) void AudioplayersWindowsPluginRegisterWithRegistrar(void) { }
> 
> /*
> Then compile it.
> For windows/mingw64 users:
>     gcc -shared -o audioplayers_windows_plugin.dll audioplayers_windows_plugin_faker.c
> */
> ```
> 
> 

It seems just make  audioplayers plugin nothing to do.

**Comment by zmh00** [comment]
> Just compile the following code into a shared library `audioplayers_windows_plugin.dll`, and replace the one in `site_packages/flet/bin/flet`.
> 
> ```c
> // audioplayers_windows_plugin_faker.c
> // get symbols via `dumpbin`
> __declspec(dllexport) void AudioplayersWindowsPluginRegisterWithRegistrar(void) { }
> 
> /*
> Then compile it.
> For windows/mingw64 users:
>     gcc -shared -o audioplayers_windows_plugin.dll audioplayers_windows_plugin_faker.c
> */
> ```

Could you share the dummy file? I'm not familiar with compiling the DLL file and is super eager to have this patch up for my apps working on Win7. Thank you!

**Comment by liudonghua123** [comment]
> > Just compile the following code into a shared library `audioplayers_windows_plugin.dll`, and replace the one in `site_packages/flet/bin/flet`.
> > ```c
> > // audioplayers_windows_plugin_faker.c
> > // get symbols via `dumpbin`
> > __declspec(dllexport) void AudioplayersWindowsPluginRegisterWithRegistrar(void) { }
> > 
> > /*
> > Then compile it.
> > For windows/mingw64 users:
> >     gcc -shared -o audioplayers_windows_plugin.dll audioplayers_windows_plugin_faker.c
> > */
> > ```
> 
> @thautwarm Could you share the dummy file? I'm not familiar with compiling the DLL file and is super eager to have this patch up for my apps working on Win7. Thank you!

Just do as the instructions.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/2276718/231790720-11cb27ac-6d40-42d4-8104-9e148e600e62.png">

[audioplayers_windows_plugin.zip](https://github.com/flet-dev/flet/files/11223229/audioplayers_windows_plugin.zip)
