### ISSUE TITLE
Connectivity Issues with Flet App on Android and iPad 

### ISSUE THREAD

**Issue by vargasmiguel** [flet-dev/flet#1715]
**Title:** Connectivity Issues with Flet App on Different Platforms

**Description:**
Hello,

I hope this message finds you well. I've been using the Flet application to view projects, and I've encountered some connectivity issues on both the Android and iPad platforms. I'd like to report these issues and provide some details for further investigation.

**iPad Issue:**
When I launch the Flet app on my iPad and attempt to access projects hosted on the local network, I expected to be prompted to grant the necessary permission for local network access. However, the app does not present this permission request dialog. As a result, I am unable to establish connections to projects through the app.

**Android Issue:**
On my Android device, I experienced a different issue. While the Flet app does open projects in the browser when accessed from the local network, the app itself seems to struggle with establishing a connection to the project. Despite opening the button "Open the project in Flet app" in the browser successfully, the app does not establish a connection to the project as expected.

**Steps Taken:**
1. Installed the Flet app on iPad and Android.
2. Followed the guide in https://flet.dev/docs/guides/python (exactly the same project)
3. Attempted to connect to project hosted on the local network.
4. Checked app permissions and settings on both devices.

**Screenshots:**
I've taken screenshots of the errors encountered on both platforms. Here they are:

- **iPad Screenshot:** 
![IMG_0016](https://github.com/flet-dev/flet/assets/54147317/6269fe6f-bd66-4aa6-a9e3-8fe39a494c4b)

- **Android Screenshots:** 
![WhatsApp Image 2023-08-12 at 9 20 01 AM](https://github.com/flet-dev/flet/assets/54147317/07f020c0-600b-4632-8f72-d90109ea3c81)
![WhatsApp Image 2023-08-12 at 9 20 01 AM (1)](https://github.com/flet-dev/flet/assets/54147317/0b973cb3-3813-4a7a-81d6-e3e8a2b82162)

**Additional Information:**
- iPadOs: 16 (iPad 10th generation) 
- Android: 13 (Samsung Galaxy A33)
- PC: MacBook Air M2, macOs Ventura 13.4.1 (c) 
- Flet App Version: iPad (1.0.1 - 0.8.0.dev1596), Android(1.1.1 - 0.9.0)

I'm hoping that by bringing these issues to your attention, we can work together to ensure a smoother experience for users across different platforms. Please let me know if there's any additional information you require to investigate these problems further.

Thank you for your time and assistance.

Best regards,
Miguel

**Comment by ndonkoHenri** [comment]
You might find this useful: https://medium.com/@ndonkohenri/troubleshooting-flet-app-on-mobile-a73b535aa727

**Comment by vargasmiguel** [comment]
Thanks a lot @ndonkoHenri. I solved it replacing the IP.

**Comment by FeodorFitsner** [comment]
I'm wondering if we could figure our a better way detecting computer's IP address... However, a working solution would be adding `--address` argument to `flet run` which just allows user to provide their own value for computer's address. What do you think?

**Comment by ndonkoHenri** [comment]
The address param looks good.

Voile you please outline the current way by which Flet derives the local IP?

**Comment by FeodorFitsner** [comment]
Sure, [here](https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet/src/flet/cli/commands/run.py#L296-L297).

**Comment by DavMelchi** [comment]
Below method seem working well for me on Win 10. From GPT by the way

```python
import socket
def get_local_ip():
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            local_ip = s.getsockname()[0]
        return local_ip
    except Exception as e:
        return f"Unable to get local IP address: {e}"

# Example usage
local_ip_address = get_local_ip()
print(f"Your laptop's local IP address is {local_ip_address}")
```

**Comment by ndonkoHenri** [comment]
Nice @DavMelchi, it equally uses `socket` lib. 
@FeodorFitsner can you try it?

**Comment by FeodorFitsner** [comment]
Sure, will do tomorrow.

**Comment by ndonkoHenri** [comment]
Issue should be closed.
@FeodorFitsner, you can open a new one if you plan to enhance the IP-fetch.

**Comment by FeodorFitsner** [comment]
@DavMelchi It indeed returns a correct IP for my laptop! But how?! :) Where did you learn about that method?

**Comment by ndonkoHenri** [comment]
> From GPT by the way
😆

**Comment by FeodorFitsner** [comment]
No way! 😱

Anyway, will give it a try in the next Flet release: https://github.com/flet-dev/flet/issues/1733

**Comment by DavMelchi** [comment]
Yep... from GPT after first 3 wrong answers. Need patience with this GPT. Haha

**Comment by FeodorFitsner** [comment]
A new IP detection algorithm is in Flet 0.10.1 now.
