### ISSUE TITLE
error_text didn't work!

### ISSUE THREAD

**Issue by Diae98** [flet-dev/flet#1727]
`def page_go_to_chat_page(self):
        self.Text_Name.error_text = ""
        if not self.Text_Name.value:
            self.Text_Name.error_text = "Please Enter a Name!"
            self.update()
        else:    
            self.page.go('/chat_page')`
this code didn't work!

**Comment by ndonkoHenri** [comment]
Build a sample code with the issue so we can better help you out.

**Comment by Diae98** [comment]
`class Home(UserControl):
    def page_go_to_chat_page(self):
        self.page.go('/chat_page')
    Title = Text("Login Page",
                 size=24,
                 italic=True,
                 color=colors.WHITE,
                 )
    Text_Name = TextField(hint_text="What's your name? ",
                          text_size=18,
                          autofocus=True,
                          icon=icons.PERSON_2_OUTLINED,
                          width=250,
                          max_length=16,
                          )
    Button_Name = ElevatedButton(text="Subtim",
                                  width=100,
                                  height=60,
                                  animate_offset=Animation(200,AnimationCurve.EASE_IN_CUBIC),
                                  bgcolor=colors.DEEP_PURPLE_ACCENT_700,
                                  color=colors.WHITE,
                                  on_click=page_go_to_chat_page
                                       
                                  )
    def build(self):
        return Container(
            Stack([
                Image(src="trying expert\purple.jpg",
                      width=520,
                      height=850,
                      fit=ImageFit.COVER),
                Container(
                    Container(
                        Column([
                            self.Title,
                            self.Text_Name,
                            self.Button_Name
                        ],
                        alignment=MainAxisAlignment.SPACE_AROUND,
                        horizontal_alignment=CrossAxisAlignment.CENTER,
                        ),
                        width=300,
                        height=220,
                        border_radius=15,
                        opacity=0.85,
                        bgcolor=colors.PURPLE_ACCENT_700,
                        alignment=alignment.center,
                        margin=margin.only(top=150)

                    ),alignment=alignment.center,
                )
            ]),alignment=alignment.center
        )`
ok, i need your help..

**Comment by ndonkoHenri** [comment]
I can't run your code please!

**Comment by Diae98** [comment]
i need your help..

**Comment by ndonkoHenri** [comment]
Provide the complete error message please.
