### ISSUE TITLE
function didnt wrork in class

### ISSUE THREAD

**Issue by Diae98** [flet-dev/flet#1728]
am sorry for the wrong code, but the function submit_answer didn't defined!!
`import flet 
from flet import *
import time
import usellm 
from usellm import *

service = UseLLM(service_url="https://usellm.org/api/llm")

class Chat_Page(UserControl):
    

    def submit_answer(e,self):
        if self.promot_text.value == "":
            self.promot_text.error_text = "Please enter a question"
            self.update()
        else:
            user_input = self.promot_text.value
            messages = [
                Message(role="system", content="want help you"),
                Message(role="user", content=user_input)
            ]
            option = Options(messages=messages)
            respone = service.chat(option)

            self.ct_result.content.controls.clear()
            result_text = Text("", color="white", size=19, text_align= TextAlign.RIGHT)
            self.ct_result.content.controls.append(result_text)
            self.update()

            typing_delay = 0.02

            for char in respone.content:
                result_text.value += char
                self.update()
                time.sleep(typing_delay)
            self.promot_text.clean()
            
            self.update()

    botton = IconButton( 
                    icon = icons.SEND,
                    on_click=lambda e: submit_answer()
                              )
    promot_text = Row([
                    TextField(
                            hint_text="Ask me any question!",
                            width=430,
                            height=200,
                            color=colors.WHITE,
                            autofocus=True,
                            autocorrect=True,
                            focused_border_color=colors.DEEP_PURPLE_ACCENT_700
                            ),
                            
                    
                        ])
    ct_result = Container(
                            width=520,
                            padding=10,
                            blur=Blur(15,30,tile_mode=BlurTileMode.CLAMP),
                            height=700,
                            alignment=alignment.bottom_center,
                            content=Column(scroll=ScrollMode.AUTO)
    )
    container_column = Column([
                        ct_result,
                        Container(
                        width=520,
                        blur=Blur(15,30,tile_mode=BlurTileMode.CLAMP),
                        height=220,
                        content= promot_text,                           
                    )],                
        )
    
    def build(self):
        return Container(
                    Stack([
                        Image(
                            src="trying expert\purple.jpg",
                            fit=ImageFit.COVER,
                            width=520,
                            height=900,
                            ),
                        Container(
                        width= 520,
                        blur=Blur(100,100,tile_mode=BlurTileMode.CLAMP),
                        height=900,
                        content=Column([
                            self.container_column
                        ])
                    ),
                    
                    ]
                    ))
class Home(UserControl):
    def page_go_to_chat_page(self):
        self.page.go('/chat_page')
    Title = Text("Login Page",
                 size=24,
                 italic=True,
                 color=colors.WHITE,
                 )
    Text_Name = TextField(hint_text="What's your name? ",
                          text_size=18,
                          autofocus=True,
                          icon=icons.PERSON_2_OUTLINED,
                          width=250,
                          max_length=16,
                          )
    Button_Name = ElevatedButton(text="Subtim",
                                  width=100,
                                  height=60,
                                  animate_offset=Animation(200,AnimationCurve.EASE_IN_CUBIC),
                                  bgcolor=colors.DEEP_PURPLE_ACCENT_700,
                                  color=colors.WHITE,
                                  on_click=page_go_to_chat_page
                                       
                                  )
    def build(self):
        return Container(
            Stack([
                Image(src="trying expert\purple.jpg",
                      width=520,
                      height=850,
                      fit=ImageFit.COVER),
                Container(
                    Container(
                        Column([
                            self.Title,
                            self.Text_Name,
                            self.Button_Name
                        ],
                        alignment=MainAxisAlignment.SPACE_AROUND,
                        horizontal_alignment=CrossAxisAlignment.CENTER,
                        ),
                        width=300,
                        height=220,
                        border_radius=15,
                        opacity=0.85,
                        bgcolor=colors.PURPLE_ACCENT_700,
                        alignment=alignment.center,
                        margin=margin.only(top=150)

                    ),alignment=alignment.center,
                )
            ]),alignment=alignment.center
        )
    
def main(page: Page):
    page.window_width = 520
    page.window_max_width = 520
    page.window_height = 850
    page.window_max_height = 850
    page.horizontal_alignment = CrossAxisAlignment.CENTER
    page.vertical_alignment = MainAxisAlignment.CENTER

    home = Home()
    chat_page = Chat_Page()
    def route_change(route):
        page.views.clear()
        if page.route == '/':
            page.views.append(home)
        if page.route == '/chat_page':
            page.views.append(chat_page)
        
        page.update()
    
    page.on_route_change = route_change
    page.go(page.route)
flet.app(target=main)`

**Comment by ndonkoHenri** [comment]
- `self` should come before `e` in your function definition ---> `def submit_answer(self, e):`
- when calling the function in on_click use `self.` ----> `on_click=lambda e: self.submit_answer()` // you should not forget to pass the positional argument `e` else an error will be raised --> `on_click=lambda e: self.submit_answer(e)`

That's all I see for now. Make the changes and retry.
