### ISSUE TITLE
Button have inconsistent .autofocus / .focus() implementations

### ISSUE THREAD

**Issue by alan-copeland-keysight** [flet-dev/flet#1729]
**Description**
The button implementions seem to inconsistently implement .autofocus and .focus(). Is this design intentional, or an oversight? 

Based on the documentation online, the current state is:

| Type           | .autofocus | .focus() |
|----------------|------------|----------|
| ElevatedButton | yes        | yes      |
| FilledButton   | yes        | no       |
| FilledTonalButton | yes        | no       |
| FloatingActionButton | yes        | no       |
| IconButton | yes        | yes |
| OutlinedButton | yes        | yes |
| FilledTonalButton | yes        | no       |
| PopupMenuButton | no | no       |
| TextButton | yes        | yes |

**Comment by ndonkoHenri** [comment]
I don't really get your point.

`.focus()` is a actually a method/function as mentioned in the docs.
When called, it sets the focus of the attached control, or button in this case, to `True` (equivalent to `yes` in your table)

**Comment by hognala** [comment]
I'd like to be able to call focus() on all the button types, not just the random ones that have it implemented. I was trying to call .focus() on one of the buttons that doesn't implement it.

Also, is there a reason .autofocus is not implemented on the one button type? For consistency, it would be nice to have it there as well.

**Comment by alan-copeland-keysight** [comment]
I'd like to be able to call focus() on all the button types, not just the random ones that have it implemented. I was trying to call .focus() on one of the buttons that doesn't implement it.

Also, is there a reason .autofocus is not implemented on the one button type? For consistency, it would be nice to have it there as well.

**Comment by ndonkoHenri** [comment]
I seem to get your point better now. 
`FilledTonalButton` and `FilledButton` have `.focus()` and just`PopupMenuButton`, `FloatingActionButton` do not have this method.
![image](https://github.com/flet-dev/flet/assets/98978078/7864d1f3-ef8c-4999-8df1-7c8525398c50)
![image](https://github.com/flet-dev/flet/assets/98978078/ddd76645-48a6-400a-a7b1-6cb9caa10b0b)

**Comment by alan-copeland-keysight** [comment]
Ya, it just seemed inconsistent, and made me wonder if I should be using a different button type because "I am doing Material wrong", which is very possible, or if it was just an oversight and those other buttons should have the properties/methods implemented as well.

**Comment by ndonkoHenri** [comment]
I noticed from the flutter docs of the [popupmenubutton](https://api.flutter-io.cn/flutter/material/PopupMenuButton-class.html) that it doesn't have an `autofocus` prop as compared to others.
Reading [this](https://api.flutter-io.cn/flutter/material/ButtonStyleButton-class.html), I think Popupmenubutton and floatingactionbutton are different from the others (they don't have thesame base).

**Comment by alan-copeland-keysight** [comment]
I see. So how closely does flet try to stick to what Flutter natively implements?

Thanks for the link

**Comment by ndonkoHenri** [comment]
So, to be brief, I think this is not reaally an issue.
Concerning your question, Flet tries as much as possible to have the Flutter basic stuffs. There are alot already, and some controls/widgets/props are still to be implemented.
The Flet team is focusing atm on the framework's stabilisation. 
Nevertheless, feel free to open discussions to discuss with the team and community on what you will like to see/have.

**Comment by alan-copeland-keysight** [comment]
Stabile is good :)

Thanks for the feedback.

I've enjoyed using flet so far!

**Comment by ndonkoHenri** [comment]
Happy to know that!
Can you close this issue?
