### ISSUE TITLE
I can't use the new feature Flet for Android in version 0.9.0 on my Xiaomi Android phone

### ISSUE THREAD

**Issue by txwx** [flet-dev/flet#1737]
After the update to version 0.9.0, I want to try the new Android functions of flet. I follow the operations in the tutorial. First, I open wechat, use the scanning function, scan the two-dimensional code displayed on the terminal, and enter a page where there is a button called open the project in flet app. But there was no response after I clicked it, and there was no response when I opened the browser. I confirmed that the computer and the phone were on the same wifi

**Comment by ndonkoHenri** [comment]
Does the issue persist? Or you've found a way out?

**Comment by txwx** [comment]
This problem I tested yesterday is still not solved



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/17/2023 05:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [flet-dev/flet] I can't use the new feature Flet for Android in version 0.9.0 on my Xiaomi Android phone (Issue #1737) |

Does the issue persist? Or you've found a way out?

**Comment by XueLiren** [comment]
The same is true of the Huawei mobile phone I use.

**Comment by FeodorFitsner** [comment]
It should be tested in Flet 0.10.1.

**Comment by txwx** [comment]
I'm very sorry, I tried tonight and it still didn't work, I have upgraded the version to 0.10.1



---- Replied Message ----
| From | Feodor ***@***.***> |
| Date | 09/15/2023 00:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [flet-dev/flet] I can't use the new feature Flet for Android in version 0.9.0 on my Xiaomi Android phone (Issue #1737) |

It should be tested in Flet 0.10.1.

**Comment by ndonkoHenri** [comment]
Can you have a look at this: https://medium.com/@ndonkohenri/troubleshooting-flet-app-on-mobile-a73b535aa727 ?

**Comment by txwx** [comment]
I'm sorry, but I can't access this website, so I can't see the Q&A



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/16/2023 05:03 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [flet-dev/flet] I can't use the new feature Flet for Android in version 0.9.0 on my Xiaomi Android phone (Issue #1737) |

Can you have a look at this: ***@***.***/troubleshooting-flet-app-on-mobile-a73b535aa727 ?
