### ISSUE TITLE
flet Errno 61

### ISSUE THREAD

**Issue by PythonGite** [flet-dev/flet#1779]
Hello, 

I'm encountering an issue while attempting to create and add a project to the FLET application on my iPhone. I created the project in the terminal according to the instructions, and when I scan the QR code using the phone's camera, I receive an error message in the FLET app: "error connecting to http://127.0.0.8551/motion/main.py:<urlopen error [Errno 61] Connection refused>."

What should I do to resolve this error and successfully add this project to the FLET app installed on my iPhone?

**Comment by ndonkoHenri** [comment]
Have a look at this article: https://medium.com/@ndonkohenri/troubleshooting-flet-app-on-mobile-a73b535aa727

**Comment by FeodorFitsner** [comment]
I can't believe I haven't fixed [IP detection](https://github.com/flet-dev/flet/issues/1733) as we discussed! 😳
Will do it in 0.10.1 coming this week.

**Comment by FeodorFitsner** [comment]
It should be fixed in Flet 0.10.1 now. Could you please give it another try and see if correctly detects your IP.

**Comment by PythonGite** [comment]
yes, it's working now, thanks
