### ISSUE TITLE
serious-python issue?

### ISSUE THREAD

**Issue by CybroOdooDev** [flet-dev/flet#1796]
**Description**

**Code example to reproduce the issue:**

```python
https://github.com/flet-dev/serious-python/tree/main I tried the same in the mentioned link but I got an error:
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
I/flutter ( 6225): Connecting to Flet server flet.sock...
I/flutter ( 6225): Connecting to Socket server flet.sock...
I/flutter ( 6225): Error connecting to Flet server: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = flet.sock, port = 0
I/flutter ( 6225): Reconnect in 200 milliseconds
```

**Operating system**:

**Additional environment details:**

**Comment by SKbarbon** [comment]
Unfortunately, there is an issue with latest versions of flet. Go to the "app/src" folder, then in the requirements.txt file replace "flet" with "flet==0.8.2"

@CybroOdooDev try it and give me your results

**Comment by CybroOdooDev** [comment]
The problem will not be solved

**Comment by SKbarbon** [comment]
I was facing the same issue, if you did replace the thing. Please reCompile python by this command:

dart run serious_python:main package app/src

**Comment by SKbarbon** [comment]
@CybroOdooDev I was facing the same issue, if you did replace the thing. Please reCompile python by this command:

dart run serious_python:main package app/src

**Comment by CybroOdooDev** [comment]
@SKbarbon Problem solved. Thankyou

**Comment by SKbarbon** [comment]
I am glad to hear that, please close the issue as "completed".
@CybroOdooDev

**Comment by CybroOdooDev** [comment]
@SKbarbon Found the same problem today

**Comment by SKbarbon** [comment]
@CybroOdooDev is there anything in console?

**Comment by CybroOdooDev** [comment]
@SKbarbon I/flutter ( 6225): Connecting to Flet server flet.sock...
I/flutter ( 6225): Connecting to Socket server flet.sock...
I/flutter ( 6225): Error connecting to Flet server: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = flet.sock, port = 0
I/flutter ( 6225): Reconnect in 200 milliseconds

**Comment by SKbarbon** [comment]
What is the command you use to build your flutter app? @CybroOdooDev
