### ISSUE TITLE
Using Audio and FilePicker at the same time, when click on the FilePicker, the audio automatically replays

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#1807]
### Discussed in https://github.com/flet-dev/flet/discussions/1803

<div type='discussions-op-text'>

<sup>Originally posted by **gpt9796** September  6, 2023</sup>
### Question

 When using audio and filepicker at the same time, when I click on the filepicker, the audio automatically replays.

it's may be  likes  github issue of   [https://github.com/flet-dev/flet/issues/1236]  and [https://github.com/flet-dev/flet/issues/1772]

### Code sample

```python
import flet as ft

def main(page: ft.Page):
    audio = ft.Audio(
        src="https://luan.xyz/files/audio/ambient_c_motion.mp3", autoplay=True,
    )
    page.overlay.append(audio)
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()
    selected_files = ft.Text()
    def upload_file(e):
        pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
        page.overlay.append(pick_files_dialog)
        page.update()
        pick_files_dialog.pick_files(
            allow_multiple=True
        ),
    page.add(
        ft.Row(
            [
                ft.ElevatedButton("play", onclick=lambda : audio.play()),
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=upload_file
                ),
                selected_files,
            ]
        )
    )
ft.app(target=main)
```

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

**Comment by AlexanderMz** [comment]
Hello @FeodorFitsner 
try this
`
import flet as ft

def main(page: ft.Page):
    audio = ft.Audio(
        src="https://luan.xyz/files/audio/ambient_c_motion.mp3", autoplay=True,
    )
    page.overlay.append(audio)
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()
    selected_files = ft.Text()
    def upload_file(e):
        pick_files_dialog.pick_files(
            allow_multiple=True
        ),
    pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
    page.overlay.append(pick_files_dialog)
    page.add(
        ft.Row(
            [
                ft.ElevatedButton("play", on_click=lambda : audio.play()),
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=upload_file
                ),
                selected_files,
            ]
        )
    )
ft.app(target=main)
`

**Comment by AlexanderMz** [comment]
Hello @FeodorFitsner 
Try this
```
import flet as ft

def main(page: ft.Page):
    audio = ft.Audio(
        src="https://luan.xyz/files/audio/ambient_c_motion.mp3", autoplay=True,
    )
    page.overlay.append(audio)
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()
    selected_files = ft.Text()
    def upload_file(e):
        pick_files_dialog.pick_files(
            allow_multiple=True
        ),
    pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
    page.overlay.append(pick_files_dialog)
    page.add(
        ft.Row(
            [
                ft.ElevatedButton("play", on_click=lambda : audio.play()),
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=upload_file
                ),
                selected_files,
            ]
        )
    )
ft.app(target=main)
```

**Comment by gpt9796** [comment]
> Hello @FeodorFitsner Try this
> 
> ```
> import flet as ft
> 
> def main(page: ft.Page):
>     audio = ft.Audio(
>         src="https://luan.xyz/files/audio/ambient_c_motion.mp3", autoplay=True,
>     )
>     page.overlay.append(audio)
>     def pick_files_result(e: ft.FilePickerResultEvent):
>         selected_files.value = (
>             ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
>         )
>         selected_files.update()
>     selected_files = ft.Text()
>     def upload_file(e):
>         pick_files_dialog.pick_files(
>             allow_multiple=True
>         ),
>     pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
>     page.overlay.append(pick_files_dialog)
>     page.add(
>         ft.Row(
>             [
>                 ft.ElevatedButton("play", on_click=lambda : audio.play()),
>                 ft.ElevatedButton(
>                     "Pick files",
>                     icon=ft.icons.UPLOAD_FILE,
>                     on_click=upload_file
>                 ),
>                 selected_files,
>             ]
>         )
>     )
> ft.app(target=main)
> ```

Thats workers will, thank  you for match

**Comment by gpt9796** [comment]
> > Hello @FeodorFitsner Try this
> > ```
> > import flet as ft
> > 
> > def main(page: ft.Page):
> >     audio = ft.Audio(
> >         src="https://luan.xyz/files/audio/ambient_c_motion.mp3", autoplay=True,
> >     )
> >     page.overlay.append(audio)
> >     def pick_files_result(e: ft.FilePickerResultEvent):
> >         selected_files.value = (
> >             ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
> >         )
> >         selected_files.update()
> >     selected_files = ft.Text()
> >     def upload_file(e):
> >         pick_files_dialog.pick_files(
> >             allow_multiple=True
> >         ),
> >     pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
> >     page.overlay.append(pick_files_dialog)
> >     page.add(
> >         ft.Row(
> >             [
> >                 ft.ElevatedButton("play", on_click=lambda : audio.play()),
> >                 ft.ElevatedButton(
> >                     "Pick files",
> >                     icon=ft.icons.UPLOAD_FILE,
> >                     on_click=upload_file
> >                 ),
> >                 selected_files,
> >             ]
> >         )
> >     )
> > ft.app(target=main)
> > ```
> 
> Thats works well, thank you for match，but when  update the page, it hava  same problem.
