### ISSUE TITLE
Allow PopupMenu to Remain Open After Interacting with Its Children

### ISSUE THREAD

**Issue by Soif2Sang** [flet-dev/flet#1812]
I propose the addition of a new parameter that enables users to retain the PopupMenu open even after interacting with controls within it. Currently, clicking on any control inside a PopupMenu automatically closes it.

Example Use Case: Users can select multiple checkboxes within a PopupMenu and then click outside of it to close it.

Thanks

**Comment by ndonkoHenri** [comment]
Found this: https://stackoverflow.com/questions/51816699/flutter-checkedpopupmenuitem-keep-menu-open-after-selecting-an-item
But the solution is not the best... 😕

**Comment by Soif2Sang** [comment]
Thanks for your answer, I never dealt with dart before and I struggle to implement it on python :/

**Comment by ndonkoHenri** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/686
