### ISSUE TITLE
Bug Report: DataTable does not show Datarows while not being first control in Column

### ISSUE THREAD

**Issue by ChenghaoQ** [flet-dev/flet#1861]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft
class Test:
    def __init__(self,page):
        self.page = page
        self.table = None
        self.table_init()
        self.load_data()
        self.page.add(self.table)

    def table_init(self):
        text = ft.Text("This is a test")
        table=ft.DataTable(
            columns=[
                ft.DataColumn(ft.Text("First name")),
                ft.DataColumn(ft.Text("Last name")),
                ft.DataColumn(ft.Text("Age"), numeric=True),
            ])
        self.table=ft.Column(controls=[text,table]) ###problem at here

    def load_data(self):
        rows=[
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text("John")),
                        ft.DataCell(ft.Text("Smith")),
                        ft.DataCell(ft.Text("43")),
                    ],
                ),
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text("Jack")),
                        ft.DataCell(ft.Text("Brown")),
                        ft.DataCell(ft.Text("19")),
                    ],
                ),
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text("Alice")),
                        ft.DataCell(ft.Text("Wong")),
                        ft.DataCell(ft.Text("25")),
                    ],
                ),
            ]
        self.table.controls[0].rows = rows


def main(page: ft.Page):
    page.title = "A simple DataTable"            
    Test(page)
ft.app(target=main)            

```

**Describe the results you received:**

<img width="373" alt="image" src="https://github.com/flet-dev/flet/assets/17086722/8e0f7ab0-b646-40a1-b2c7-b83d4e05ed98">

Once I switch the position of DataTable, it shows DataRows correctly
```python
self.table=ft.Column(controls=[table,text])
```
<img width="375" alt="image" src="https://github.com/flet-dev/flet/assets/17086722/b58963a8-5129-455a-b448-dead4f2a2dfe">

**Describe the results you expected:**

Result should display text and table in order and has Datarow shown

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.1
```

**Operating system**:
macOS

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
The issue is found here:
```python
self.table.controls[0].rows = rows
```

Instead of `0` use `1`, because the table is at the second position (index 1).
```python
self.table.controls[1].rows = rows
```

**Note** that when changing the order of the column, you will always need to modify the index value.

**Comment by ChenghaoQ** [comment]
> The issue is found here:
> 
> ```python
> self.table.controls[0].rows = rows
> ```
> 
> Instead of `0` use `1`, because the table is at the second position (index 1).
> 
> ```python
> self.table.controls[1].rows = rows
> ```
> 
> **Note** that when changing the order of the column's controls, you will always need to modify the index value.

Thank you! my problem
