### ISSUE TITLE
[feature] allow downloading of files

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#1863]
**Please Describe The Problem To Be Solved**

We need to be able to download files from the server to the users computer.  Currently launch_url can be used but it has issues on Safari (where for instance a civ file just replaces the current page), but on Firefox does download the file.

**(Optional): Suggest A Solution**

(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation, e.g. Flutter widget solving the problem.
* Tradeoffs made in design decisions
* Caveats and considerations for the future

have a launch_download() call that starts a download of a file from the server to the user, I'm not familiar enough with flutter to suggest a widget.

**Comment by ndonkoHenri** [comment]
What about this: https://flet.dev/docs/controls/filepicker#:~:text=allowed_extensions-,INFO,-To%20save%20a
