### ISSUE TITLE
can i make a custom Date Picker Control 

### ISSUE THREAD

**Issue by normalentity** [flet-dev/flet#1866]
**You have said that you are going add the Date picker control but that's about 4 or 5 months later
so I was wondering what is taking so long please let me know.**

**Comment by FeodorFitsner** [comment]
There is a community DatePicker already: https://github.com/flet-dev/examples/tree/main/python/community/datepicker
and we are going to implement Flutter built-in DatePicker widget as well: https://github.com/flet-dev/flet/issues/86
