### ISSUE TITLE
Problem opening a AlertDialog

### ISSUE THREAD

**Issue by R8bert** [flet-dev/flet#1870]
`
from flet import *
from datetime import datetime
from utils.datepicker.datepicker import DatePicker
from utils.datepicker.selection_type import SelectionType

# grafana imports
import requests
import json
import psycopg2
import webbrowser
import urllib3
import copy
from PIL import Image
import qrcode

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logo = Image.open(Logo_link)
 
# taking base width
basewidth = 500

wpercent = (basewidth/float(logo.size[0]))
hsize = int((float(logo.size[1])*float(wpercent)))
logo = logo.resize((basewidth, hsize), Image.BILINEAR)
QRcode = qrcode.QRCode(
    error_correction=qrcode.constants.ERROR_CORRECT_H
)

class PostgresContextManager:
    def __enter__(self):
        conn_params = {

        }
        self.conn = psycopg2.connect(**conn_params)
        self.cur = self.conn.cursor()
        return self.cur

    def __exit__(self, exc_type, exc_value, traceback):
        self.cur.close()
        self.conn.commit()
        self.conn.close()

def CheckMachineDetails(t_id):
    with PostgresContextManager() as cur:
        cur.execute("SELECT * FROM machines WHERE machine_id = %s", (t_id,))
        row = cur.fetchone()
        if row is None:
            print("Tag not found")
        else:
            info_machine_id = row[0]
            info_machine_name = row[1]
            info_machine_type = row[2]
            info_equipment_number = row[3]

def GetTagsForMachine(machine_id):
    with PostgresContextManager() as cur:
        cur.execute("SELECT * FROM tags WHERE machine_id = %s", (machine_id,))
        tags = [row[0] for row in cur.fetchall()]
    return tags

f2 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\flow_aer_comprimat.json"
)
data2 = json.load(f2)

f3 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\temperature.json"
)
data3 = json.load(f3)

f4 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\energy_meter.json"
)
data4 = json.load(f4)
f5 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\compressed_air_pressure.json"
)
data5 = json.load(f5)
f6 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\humidity.json"
)
data6 = json.load(f6)
f7 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\realtime_energy_consumption.json"
)
data7 = json.load(f7)
f8 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\putere_totala_activa.json"
)
data8 = json.load(f8)
f9 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\temperature_electrical_panel.json"
)
data9 = json.load(f9)
f10 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\meters.json"
)
data10 = json.load(f10)
f11 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\displacement.json"
)
data11 = json.load(f11)
f12 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\cubic_meter.json"
)
data12 = json.load(f12)
f13 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\cubic_meter_per_second.json"
)
data13 = json.load(f13)
f14 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\ampere.json"
)
data14 = json.load(f14)
f15 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\volt.json"
)
data15 = json.load(f15)
f16 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\meters_per_second.json"
)
data16 = json.load(f16)
f17 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\meters_per_square_second.json"
)
data17 = json.load(f17)
f18 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\radiant_per_second.json"
)
data18 = json.load(f18)
f19 = open(
    r"C:\Users\podarrbe\Desktop\Dashboard\dash1\s Dash from Autinity_beta1\json_templates\liter_per_minute.json"
)
data19 = json.load(f19)

def testlinkdinamic(machine_id):
    with PostgresContextManager() as cur:
        cur.execute("SELECT * FROM machines WHERE machine_id = %s", (machine_id,))
        row = cur.fetchone()
        if row is None:
            print("Tag not found")
        else:
            info_machine_id = row[0]
            info_machine_name = (
                row[1].replace(" ", "_").replace("-", "_").replace("/", "_").replace("+", "_")
            )  # change space to _ and - to _
            info_machine_title = row[1]
            info_machine_type = row[2]
            if len(info_machine_name) > 29:
                info_machine_name = info_machine_name[:25]

    CustomGeneratedUID = (
        "GVD_" + str(info_machine_name) + "_MID_" + str(info_machine_id)
    )
    
    print(CustomGeneratedUID)
    Create_dashboard(CustomGeneratedUID, info_machine_id, info_machine_title)

def Create_dashboard(CustomGeneratedUID, info_machine_id, info_machine_title):
    tags = GetTagsForMachine(info_machine_id)
    x={}
    tag_ids = {}
    panels = []

    with PostgresContextManager() as cur:
        contor = 1
        for tag in tags:
            cur.execute(
                "SELECT tag_unit,tag_details,tag_state,tag_id FROM tags WHERE tag_id = %s",
                (tag,),
            )
            row = cur.fetchone()
            tag_unit = row[0]
            tag_details = row[1].replace("  ", "")
            tag_state = row[2]
            tag_id_curent = row[3]

            match tag_unit:
                # h = 8, w = 12 y not important
                case "Pascal":
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    # verify if that is a pressure tag
                    if "Presiune cuptor" in tag_details:
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data5)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                if (contor % 2) == 0:
                                    x[tag]["gridPos"]["x"] = 0
                                else:
                                    x[tag]["gridPos"]["x"] = 12
                                contor += 1
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                    else:
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data5)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                if (contor % 2) == 0:
                                    print ("Contor par")
                                    x[tag]["gridPos"]["x"] = 0
                                else:
                                    x[tag]["gridPos"]["x"] = 12
                                contor += 1
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                case "Kelvin":
                    # temperature converted in celsius
                    if "Temperatura tablou" in tag_details:
                        request_url = autinity_url + str(tag) + end_url
                        response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data9)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                x[tag]["gridPos"]["y"] = -2
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                    else:
                        request_url = autinity_url + str(tag) + end_url
                        response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data3)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                if (contor % 2) == 0:
                                    x[tag]["x"] = 0
                                else:
                                    x[tag]["gridPos"]["x"] = 12
                                contor += 1
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                
                case "Meters":
                    if "DISPLACEMENT" in tag_details:
                        request_url = autinity_url + str(tag) + end_url
                        response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data11)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                x[tag]["gridPos"]["y"] = 999
                                contor += 1
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                    else:
                        request_url = autinity_url + str(tag) + end_url
                        response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                x[tag] = copy.deepcopy(data10)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                if (contor % 2) == 0:
                                    x[tag]["gridPos"]["x"] = 0
                                else:
                                    x[tag]["gridPos"]["x"] = 0 + (contor * 12)

                                contor += 1
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)

                case "Meters per second":
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            x[tag] = copy.deepcopy(data16)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)
                case "Meters per square second":
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            x[tag] = copy.deepcopy(data17)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)
                case "Radiant per second":
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            x[tag] = copy.deepcopy(data18)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            x[tag]["gridPos"]["y"] = -1
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)

                case "Liter per minute":
                    print("Liter per minute")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data19)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                case "Volt":
                    print("Volt")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data15)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                case "Watt":
                    print("Watt")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data8)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["gridPos"]["x"] = 12
                            x[tag]["gridPos"]["y"] = -1

                            contor += 1
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)

                case "Joule":
                    if "AlexB_Counter_SUM" in tag_details:
                        pass
                    elif "Contor energie" in tag_details:
                        request_url = autinity_url + str(tag) + end_url
                        response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                        if response.status_code == 200:
                            data = response.json()
                            if data["visu_objects"]:
                                print("Data exists for tag_id: ", tag)
                                x[tag] = copy.deepcopy(data4)
                                x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                                x[tag]["title"] = tag_details
                                x[tag]["gridPos"]["y"] = -10
                                panels.append(x[tag])
                            else:
                                print("Data doesnt exist for tag_id: ", tag)
                    else:
                        print("Caz implicit sau de rezervă")
                case "Percent":
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            x[tag] = copy.deepcopy(data6)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            x[tag]["gridPos"]["x"] = 0
                            x[tag]["gridPos"]["y"] = -1
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)
                case "Cubic meter":
                    print("Cubic meter")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data12)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            x[tag]["gridPos"]["y"] = -1
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)

                case "cubic meter per second":
                    print("Cubic meter per second")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data13)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)
                case "Ampere":
                    print("Ampere")
                    request_url = autinity_url + str(tag) + end_url
                    response = requests.get(request_url, auth=('guest', 'guest'), verify=False)
                    if response.status_code == 200:
                        data = response.json()
                        if data["visu_objects"]:
                            print("Data exists for tag_id: ", tag)
                            x[tag] = copy.deepcopy(data14)
                            x[tag]["targets"][0]["url"] = autinity_url + str(tag)+ end_url
                            x[tag]["title"] = tag_details
                            x[tag]["fieldConfig"]["defaults"]["displayName"] = tag_details
                            panels.append(x[tag])
                        else:
                            print("Data doesnt exist for tag_id: ", tag)
                    else:
                        print("Caz implicit sau de rezervă")
                case _:
                    pass

    dashboard_data = {
        "dashboard": {
            "annotations": {
                "list": [
                    {
                        "builtIn": 1,
                        "datasource": {"type": "grafana", "uid": "-- Grafana --"},
                        "enable": True,
                        "hide": True,
                        "iconColor": "rgba(0, 211, 255, 1)",
                        "name": "Annotations & Alerts",
                        "type": "dashboard",
                    }
                ]
            },
            "editable": True,
            "fiscalYearStartMonth": 0,
            "graphTooltip": 0,
            # "id": 3,
            "links": [],
            "liveNow": False,
            "panels": panels,
            "refresh": "",
            "schemaVersion": 38,
            "style": "dark",
            "tags": [],
            "templating": {"list": []},
            

            "timepicker": {
                "hidden": False,
                "refresh_intervals": [
                    "5s",
                    "10s",
                    "30s",
                    "1m",
                    "5m",
                    "15m",
                    "30m",
                    "1h",
                    "2h",
                    "1d",
                ],
                "time_options": [
                    "5m",
                    "15m",
                    "1h",
                    "6h",
                    "12h",
                    "24h",
                    "2d",
                    "7d",
                    "30d",
                ],
                "type": "timepicker",
            },
            "timezone": "browser",
            "title": info_machine_title + " ID: " +str(info_machine_id),
            "uid": CustomGeneratedUID,
            "version": 8,
            "weekStart": "",
        },
        "folderUid": "nErXDvCkzz",
        "message": "Made changes to xyz",
        "overwrite": True,
    }

    r = requests.post(
        url=grafana_url, headers=headers, data=json.dumps(dashboard_data), verify=False
    )

    if r.status_code == 200:
        print("Tablou de bord creat cu succes!")
        dashboard_url = f"http://10.199.65.7:3000/d/{r.json()['uid']}"
        webbrowser.open(dashboard_url)
        QRcode.add_data(dashboard_url)
        QRcode.make()
        QRcolor = 'Green'
        QRimg = QRcode.make_image(
            fill_color=QRcolor, back_color="white").convert('RGB')
        pos = ((QRimg.size[0] - logo.size[0]) // 2,
            (QRimg.size[1] - logo.size[1]) // 2)
        QRimg.paste(logo, pos)
        QRimg.save('gfg_QR.png')
        Example().create_qr()

    elif r.status_code == 412:
        error_message = json.loads(r.text).get("message")
        print(f"Eroare 412: {error_message}")
    else:
        print(f"Eroare la crearea tabloului de bord: {r.status_code}")

class Example(UserControl):

    def __init__(self):
        super().__init__()
        # self.page = self.page
        self.holidays = [datetime(2023, 1, 1), datetime(2023, 8, 15), datetime(2023, 12, 25), datetime(2023, 12, 26)]

        self.dlg_create_qr = AlertDialog(
            modal=True,
            title=Text("Date picker"),
            actions=[
                TextButton("x1", on_click=self.cancel_dlg),
                TextButton("x", on_click=self.confirm_dlg),
                IconButton(icon=icons.PLAY_CIRCLE_FILL_OUTLINED, on_click=self.open_dlg_create_qr)

            ],
            actions_alignment=MainAxisAlignment.END,
            actions_padding=5,
            content_padding=0
        )

        self.dlg_modalXX = AlertDialog(
            modal=True,
            title=Text("Date picker"),
            actions=[
                TextButton("Cancel", on_click=self.cancel_dlg),
                TextButton("Confirm", on_click=self.confirm_dlg),
                IconButton(icon=icons.PLAY_CIRCLE_FILL_OUTLINED, on_click=self.open_dlg_create_qr)
            ],
            actions_alignment=MainAxisAlignment.END,
            actions_padding=5,
            content_padding=0
        )
        
        self.tf = TextField(label="Select Date", dense=True, hint_text="yyyy-mm-ddThh:mm:ss", width=260, height=40)
        self.cal_ico = TextButton(
            icon=icons.CALENDAR_MONTH, 
            on_click=self.open_dlg_modalXX, 
            height=40,
            width=40,
            right=0,
            style=ButtonStyle(
                padding=Padding(4,0,0,0),
                shape={
                        MaterialState.DEFAULT: RoundedRectangleBorder(radius=1),
                    },
            ))        
        self.st = Stack(
            [
                self.tf,
                self.cal_ico,
            ]
        )

        self.cg = RadioGroup(content=Row(
            [
                Text("Selction Type"),
                Radio(value=SelectionType.SINGLE.value, label=SelectionType.SINGLE.name),
                Radio(value=SelectionType.RANGE.value, label=SelectionType.RANGE.name),
            ]), value=SelectionType.SINGLE.value
        )
        self.machine = TextField(label="Machine", dense=True, hint_text="Machine ID", width=260, height=40)
        self.c1 = Switch(label="With hours and minutes", value=False)
        self.tf1 = TextField(label="Disable days until date", dense=True, hint_text="yyyy-mm-dd hh:mm:ss", width=260, height=40)
        self.tf2 = TextField(label="Disable days from date", dense=True, hint_text="yyyy-mm-dd hh:mm:ss", width=260, height=40)
        self.c2 = Switch(label="Hide previous and next month days from current", value=False)
        self.c3 = Switch(label="Shows three months", value=False)

        self.from_to_text = Text(visible=False)

    def build(self):
        return Column(
            [
            Text("Datepicker options", size=24),
            Divider(),
            self.machine,
            self.cg,
            self.c1,
            self.c2,
            self.c3,
            Row([self.tf1, self.tf2,]),
            Divider(),
            self.st,
            self.from_to_text
            ]
        )
    

    def callback(self, e):
        if int(self.cg.value) == SelectionType.SINGLE.value:
            self.tf.value = e[0] if len(e) > 0 else None
        elif int(self.cg.value) == SelectionType.RANGE.value and len(e) > 0:
            self.from_to_text.value = f"From: {e[0]} To: {e[1]}"
            print(self.from_to_text.value)
            self.from_to_text.visible = True
    
    def confirm_dlg(self,e):
        self.dlg_modalXX.open = False
        self.dlg_modalXX.update()
        print("not an error")

        # x = self.machine.value
        # testlinkdinamic(x)
    
    def cancel_dlg(self,e):
        self.dlg_modalXX.open = False
        self.dlg_modalXX.update()

    # def create_qr(self):
    #     print("create qr")
    #     self.dlg_qr = Container(
    #         modal=True,
    #         title=Text("Date picker"),
    #         content=[
    #         # Image(source="gfg_QR.png", width=200, height=200),
    #         Text("Scan QR code to open dashboard"),
    #         ],
    #         actions=[
    #             TextButton("Cancel", on_click=self.cancel_dlg),
    #             TextButton("Confirm", on_click=self.confirm_dlg),
    #         ],
    #         actions_alignment=MainAxisAlignment.END,
    #         actions_padding=5,
    #         content_padding=0
    #     )
    #     self.dlg_qr.open = True
    #     self.dlg_qr.update()
        

    def open_dlg_create_qr(self, e):
        print("open_dlg_create_qr")
        self.page.dialog = self.dlg_create_qr
        self.dlg_create_qr.open = True
        self.page.update()

    def open_dlg_modalXX(self, e):
        self.datepicker = DatePicker(
            hour_minute=self.c1.value,
            selected_date=[self.tf.value] if self.tf.value else None,
            selection_type=int(self.cg.value),
            disable_to=self._to_datetime(self.tf1.value),
            disable_from=self._to_datetime(self.tf2.value),
            hide_prev_next_month_days=self.c2.value,
            holidays=self.holidays,
            show_three_months=self.c3.value,
            on_change=self.callback
            )
        self.page.dialog = self.dlg_modalXX
        self.dlg_modalXX.content = self.datepicker
        self.dlg_modalXX.open = True
        self.page.update()

    def _to_datetime(self, date_str=None):
        if date_str:
            print(datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S"))
            return datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")

        else:
            print("date_str is None")
            return None
            

        `
        
        i just copy pasted the dlg_modalXX but itt doesnt work i get Control must be added to the page first, page.update is none and stuff like that, where i am wrong?

**Comment by mouadessalim** [comment]
Firstly, the issue description appears to be quite complex and challenging to understand. To facilitate a swift resolution, could you please provide a more concise and clear explanation of the problem you're facing? Specific details about the issue and steps to reproduce it would be extremely helpful.

Secondly, instead of copying and pasting the entire program into the issue, it would be more efficient to pinpoint the specific section or lines of code where you believe the issue is occurring. This focused approach not only helps us identify the problem area quickly but also keeps the discussion more organized.

We value professionalism and efficiency in this open-source collaboration, and your assistance in this matter will contribute to a more productive discussion. If you have any questions or need guidance on how to create a more effective issue, please don't hesitate to ask.
