### ISSUE TITLE
Hot reload problem

### ISSUE THREAD

**Issue by InfiniteP** [flet-dev/flet#1879]
Hi, I'm Roni. A while ago, after upgrading Flet to the latest versions, I've been having a problem with Hot Reload; the problem is that it doesn't reload automatically when I make a code change. With previous versions, specifically with the 0.7.x versions I didn't get such an error.

I thought it was the operating system, since I was programming on Windows 10, so I switched to Linux and still the problem persists.

However, the console shows me the following error:

![Error Capture](https://github.com/flet-dev/flet/assets/141675129/3aa18d01-2a1a-476a-a885-2c8fed112c83)

I don't know if that has anything to do with the problem. Thank you in advance for your help.

Good luck!

**Comment by bobwatcherx** [comment]
on my linux.  Ubuntu 22.04 also experiences lag and can't reload when I save the code.  The application lags and I have to force it to shut down

**Comment by bobwatcherx** [comment]
for flet 0.10.3 

but good for flet 0.7.2

**Comment by Hybridhash** [comment]
I am also having same issue with flet = "^0.10.3" using macos. I have to close the connection force fully and run it again

**Comment by alisanoelia** [comment]
Hello everyone,

I'm experiencing the same issue with the Hot Reload feature in Flet 0.10.x. I'm using Void Linux and Python 3.12. Unfortunately, the automatic reload is not functioning as expected, and it's causing some disruption in my development workflow. This issue did not occur in previous versions, such as Flet 0.7.x.

Is there an anticipated solution or fix for this problem on the horizon? I'd appreciate any guidance or information on how to address this, as it's impacting my work.

Thank you for your help!

**Comment by icanhackyou** [comment]
Use GitHub code spaces it's the last resort

**Comment by ndonkoHenri** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/1556
