### ISSUE TITLE
Addition of TextStyle for Text and TextField

### ISSUE THREAD

**Issue by IagoBeuller** [flet-dev/flet#188]
My Intention is use it for outlined text, line height, and colorized text (Gradient, Texture).
The docs for it in flutter website:
https://api.flutter.dev/flutter/painting/TextStyle-class.html

**Comment by ndonkoHenri** [comment]
There's a TextStyle class already for Text and TextField.
It has: `color, bgcolor, weight, italics, size` and `font_family` but still lacks stuffs from the Flutter class: `Gradient, line height ....` 
Can it be possible for you to expose all the props @FeodorFitsner ?

**Comment by IagoBeuller** [comment]
> There's a TextStyle class already for Text and TextField. It has: `color, bgcolor, weight, italics, size` and `font_family` but still lacks stuffs from the Flutter class: `Gradient, line height ....` Can it be possible for you to expose all the props @FeodorFitsner ?

Text Stroke, Stroke Cap, Stroke Joint, Scale (horizontal & vertical) with the cursor following the correct position.
I made a text field in tkinter using the pixie-python lib for doing that. But I also had to make an .pyd with nim-lang to get the rects of the characters from the arrangement (font.typeset func return) to do it.

**Comment by hokaso** [comment]
I have the same business needs recently. If possible, let's develop the rich text editor component of flet together?

**Comment by FeodorFitsner** [comment]
Implemented: https://flet.dev/docs/controls/text#spans
