### ISSUE TITLE
Add Nim to roadmap for language support

### ISSUE THREAD

**Issue by kevspau** [flet-dev/flet#190]
Nim is a language with the speed of C and the readability of Python. Because it compiles to C, binding could be very easy with flet. It would be a good addition to the language support roadmap because of its access to system-level functions and general-purpose technology. https://nim-lang.org please consider it :)

**Comment by FeodorFitsner** [comment]
I don't think we are going to add that in the near future. In case we have resources to look into that we will re-open the issue.
