### ISSUE TITLE
Timeout waiting for invokeMethod clientStorage

### ISSUE THREAD

**Issue by farshadz1997** [flet-dev/flet#1916]
**Description**

I have created an app in which users can change the settings of the app. All settings are saved in client_storage and while a user is working with the app, it looks for the changes and works based on the updated settings on certain signals. I haven't had any issue but one of my sent me his bug report and there 

**Code example to reproduce the issue:**

one of the functions that leads to the error:

```python
def update_file(self):
        with open(self.page.client_storage.get("my_app.path"), "w") as file:
            file.write(json.dumps(self.page.session.get("my_app.some_result"), indent = 4))
```

**Describe the results you received:**

```txt
File "flet_core\client_storage.py", line 29, in get

File "flet_core\page.py", line 905, in invoke_method
    Timeout waiting for invokeMethod clientStorage:get({'key': 'my_app.path'}) call
```

**Additional information you deem important (e.g. issue happens only occasionally):**

it happens for only 1 of my clients on his PCs. he uses Windows 10 

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\Farshad\AppData\Roaming\Python\Python311\site-packages
Requires: copier, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Windows 10 64bit

**Comment by ndonkoHenri** [comment]
Please can you move to the latest version and retry?
If it persists, please share a runnable sample code for testing.

**Comment by farshadz1997** [comment]
> Please can you move to the latest version and retry? If it persists, please share a runnable sample code for testing.

Hi,
after this happened I decided to get the settings from the value attribute of each controller and I saved it in client_storage to prevent getting this error, now I'm using the latest version without any problem.

**Comment by ndonkoHenri** [comment]
I guess we can close the issue then?
