### ISSUE TITLE
Module not found Error showing

### ISSUE THREAD

**Issue by B30102003J** [flet-dev/flet#1921]
Hi Everyone,

I just stumbled upon Flet project and can't wait to get going with it.

I installed Python 3.11.0 and Flet 0.3.2 (see screenshot)

But I still could'nt run the first "Hello World" demo code I found in the flet.dev documentation.

The Error in the terminal:
AttributeError: partially initialized module 'flet' has no attribute 'page' (most likely due to a circular import)

I also run:
pip install flet --upgrade

But still same issue.

If anyone has an idea, I'd greatly appreciate it!

Thank you so much.

**Comment by FeodorFitsner** [comment]
Thanks for trying out Flet!

1) Please install the latest Flet 0.10.3.

2) Most probably your program is called `flet.py` - hence the error.

**Comment by B30102003J** [comment]
Yeah! Thanks alot
