### ISSUE TITLE
MacOS Icon bug with flet pack?

### ISSUE THREAD

**Issue by donolsch** [flet-dev/flet#1932]
Hi there,

When packaging my Flet app with flet pack --name "My App" --icon "My Icon.png" it works perfectly fine. However, when actually opening the created .app, the app icon appears in dock just for a split second and closes immediately so it seems like the app crashed. However, after a few more seconds the generic Flet icon appears in the dock and the GUI actually appears and is working perfectly fine.

Is this a known bug? Can anyone please help me to troubleshoot this? Launching the app from the terminal doesn't raise any errors.

Thank you

**Comment by FeodorFitsner** [comment]
It's a known "behavior" of Flet app packaged with pyinstaller which looks not-user friendly.

Fortunately, at the moment we are working on a new packaging mechanism which will be producing "pure" Flutter app which then compiled to different platform without any side effects.

OK, let's keep https://github.com/flet-dev/flet/issues/1880 open and close this one as duplicate.
