### ISSUE TITLE
"AlertDialog.open = True" does not work when initializing the AlertDialog.

### ISSUE THREAD

**Issue by Liaco** [flet-dev/flet#1933]
**Description**

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Can you please attach a code repro?
