### ISSUE TITLE
Lagging and rendering issue

### ISSUE THREAD

**Issue by Craftint** [flet-dev/flet#1952]
application is taking too much time to execute, routing between pages, buttons click, almost everything is taking time,

any one is facing the same issue ?

**Comment by ndonkoHenri** [comment]
Please provide more context... which platform, which flet version etc.

**Comment by Craftint** [comment]
Desktop App using Ubuntu 22.04
flet version : 0.10.3
sample code when routing between pages  :
![image](https://github.com/flet-dev/flet/assets/67686213/d7704d88-7b8d-42c7-83b0-9c9231751a98)


> Please provide more context... which platform, which flet version, sample code etc.

**Comment by ndonkoHenri** [comment]
Please can you retry with the Latest Flet version?
If the issue persists, please share some runnable code, not an image.
