### ISSUE TITLE
Example demo control line chart data time real

### ISSUE THREAD

**Issue by runtimevic** [flet-dev/flet#1954]
hello,
I can't make an example with the line chart control but it takes data in real time, where can I see an example?

thanks you.

**Comment by mouadessalim** [comment]
Hey there,

It seems the issue you've posted doesn't quite fit the usual bug report or feature request criteria. To keep the issue tracker organized, we'd kindly ask you to move this discussion to the "Discussions" tab. This ensures our issue tracker is primarily used for code-related problems and feature requests.

For more general discussions, questions, or anything that's not directly code-related enhancement, the "Discussions" tab is the appropriate place. You can access it from the repository's homepage.

Thank you for your understanding and cooperation in following these guidelines. If you have technical questions or need coding-related assistance, feel free to ask within the "Discussions" tab.
