### ISSUE TITLE
cannot get height and width for page

### ISSUE THREAD

**Issue by yinshunyao** [flet-dev/flet#1960]
** cannot get height and width. I try it when the page strart or end.  **
<img width="856" alt="image" src="https://github.com/flet-dev/flet/assets/12932235/a3633d88-babb-4ff3-9d59-b90140a4e115">

**Code example to reproduce the issue:**

```python
def main(page: ft.Page):
    ui_size.update(page.width, page.height)
    page.title = f"xxx"
    logging.warning(f"窗口{page.title}分辨率:{page.width} * {page.height}")
    page.vertical_alignment = ft.MainAxisAlignment.START
    # page.bgcolor = ft.colors.BLUE
    page.opacity = 0.5
    page.spacing = ui_size.spacing
    page.padding = ui_size.page_padding
    from views.view_switch import get_manager_view
    # 定义切换
    page.manager_view = get_manager_view()
    page.manager_view.update_page(page)
    # page.manager_view.switch_main()
    page.manager_view.switch_view(page.manager_view.URL_ORDER_LIST)
    logging.warning(f"last,窗口{page.title}分辨率:{page.width} * {page.height}")
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
flet                          0.9.0
flet-core                     0.9.0
flet-route                    0.3.2
flet-runtime                  0.9.0
```

**Operating system**:  macos and ubuntu

**the same result in version 0.10.3**

**Comment by yinshunyao** [comment]
Downgraded the flet version, this issue is resolved.

bin/python3 -m pip list | grep flet 
flet                          0.6.0
flet-core                     0.6.0
flet-route                    0.3.2
flet-runtime                  0.9.0

**Comment by ndonkoHenri** [comment]
> Downgraded the flet version, this issue is resolved.

Nice!

But I didn't understand.
You wanted to print `page.width` and `page.height` but nothing was displayed?

**Comment by yinshunyao** [comment]
> > Downgraded the flet version, this issue is resolved.
> 
> Nice!
> 
> But I didn't understand. You wanted to print `page.width` and `page.height` but nothing was displayed?

I didn't post it. The result is 0.0 and 0.0.
As shown in the following figure， my debugging results:


<img width="387" alt="image" src="https://github.com/flet-dev/flet/assets/12932235/f96a7cf0-5df0-452e-ab1a-41df25afb168">

**Comment by ndonkoHenri** [comment]
Ah Alright! 
That's strange, I must admit.

**Comment by FeodorFitsner** [comment]
All `flet`, `flet-core` and `flet-runtime` must be the same version.
