### ISSUE TITLE
flet horizontal scroll bar

### ISSUE THREAD

**Issue by kewartoscar** [flet-dev/flet#1961]
I will suggust a horizontal scrolling option be added to the existing vertical scrolling.
Sometimes there is a need to read a pandas dataframe with several columns. 
The unavilability of the horizontal scrolling options makes the DataTable truncate the columns based on screen size.
Alternatively, the DataTable can be made responsive to the dataframe involved.

**Comment by ndonkoHenri** [comment]
There is an issue for that (#1320 ).
For the moment, you can add your `DataTable` in a `Row`, and enable scrolling from there.
#1320
