### ISSUE TITLE
There is a wrong code in Handling Section in Calculator Tutorial

### ISSUE THREAD

**Issue by DetuxTR** [flet-dev/flet#1968]
There is a wrong code in Handling Event section in the Calculator Tutorial. 

 in tutorial:
_`def button_clicked(self, e):
    if e.data == "AC":
        self.result.value = "0"`_
the correct one is: 
_`def button_clicked(self, e):
    if e.control.data == "AC":
        self.result.value = "0"`_
please fix this, it taked my 1 hour.

(Sorry for bad english)

**Comment by ndonkoHenri** [comment]
Fixed: https://flet.dev/docs/tutorials/python-calculator#handling-events
Thanks!
