### ISSUE TITLE
Select markdown not working

### ISSUE THREAD

**Issue by LeandroLimaPRO** [flet-dev/flet#1972]
**Description**

I can't select the block code generated in markdown.

since "selectable" is activated, solution

**Code example to reproduce the issue:**

```python
self.md = ft.Markdown(
                self.mkt,
                selectable=True,
                extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
                code_theme="atom-one-light",
                code_style=ft.TextStyle(font_family="Roboto Mono"),
                on_tap_link=lambda e: self.launch_url(e.data),
                
                
            #on_tap_link=lambda e: ft.page.launch_url(e.data),
        )
```

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/1753 ?

**Comment by FeodorFitsner** [comment]
We'll see if that can be improved with [SelectionArea](https://github.com/flet-dev/flet/issues/1554), but it's a dup of #1753, yes.

**Comment by LeandroLimaPRO** [comment]
Yes, it should work, when will it be available?
