### ISSUE TITLE
macOS - start app hidden --> window never comes to foreground

### ISSUE THREAD

**Issue by NiTRoeSE** [flet-dev/flet#1978]
**Description**

If i start a flet app with option `view=ft.AppView.FLET_APP_HIDDEN`
and make it visible with `page.window_visible=True` to prevent a window flickering on start and enhance user experience than the window becomes visible but only if you click on the app menubar shown in macOS.
App window never comes to foreground if you don't do this.

**Code example to reproduce the issue:**

```python

from time import sleep

import flet as ft


def main(page: ft.Page):

    page.add(
        ft.Text("Hello!")
    )

    sleep(1)
    page.window_visible = True
    page.update()

ft.app(target=main, view=ft.AppView.FLET_APP_HIDDEN)

```

App window should be visible ( and come to foreground) after `page.window_visible = True` &  `page.update()`, but this dont happen.
I tried also calling `page.window_to_front()` but this do nothing.

https://github.com/flet-dev/flet/assets/24574743/3c256af2-5310-4cd9-896c-258d110387b6

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.3
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: copier, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: flet-material
```

**Operating system**:
MacOS Sonoma 14.0
Python3.10

I simply want to prevent the flickering on app start you can see in following example:

https://github.com/flet-dev/flet/assets/24574743/0f186220-132a-4d02-a297-bfd34a539e4b

If there is any other or better way to do this, pls let me know ( didn't find another workaround than the shown above from documentation ) 

Thanks in advanced !

**Comment by ndonkoHenri** [comment]
It works normally on my end.
Can you retry with the latest version?

**Comment by ndonkoHenri** [comment]
Related issue: https://github.com/flet-dev/flet/issues/2705
