### ISSUE TITLE
TypeError: TextButton.__init__() got an unexpected keyword argument 'key'

### ISSUE THREAD

**Issue by knana1662** [flet-dev/flet#1983]
Python Version:3.10.4
Windows Version: 11 
Flet Version:  0.6.2
I don't know what the problem is or where it come from but whenever i run the flet application on this laptop i always get " TypeError: TextButton.__init__() got an unexpected keyword argument 'key' " but when i run iton my other machine it come perfectly without any issues. Also i don't know if its reasonable to make use of the "data" parameter provided rather than using the "key" parameter provided?
Also if any one can produce a flet application and make use of the data parameter for me it would be nice.

**Comment by gbrandt** [comment]
I would try upgrading to a newer flet. 0.6.2 is very old.

**Comment by ndonkoHenri** [comment]
You need to update your flet version. `key` wasn't present in 0.6.2.

> Also i don't know if its reasonable to make use of the "data" parameter provided rather than using the "key" parameter provided?

May I ask why you want to use the `key` actually?

**Comment by knana1662** [comment]
i need it to store an id to perform an action with it

**Comment by ndonkoHenri** [comment]
Use the `data` property instead. `key` is to be used for scrolling purposes.. see docs.
