### ISSUE TITLE
distutils removed in Python 3.12

### ISSUE THREAD

**Issue by DanielHuey** [flet-dev/flet#1993]
Hello Flet devs.

Im writing this to inform you that in Python 3.12, the `distutils` package is deprecated and this change breaks some core functionality of flet, and in turn flet does not run on Python 3.12.
I would have tried to make a pull request and contribute to shifting from `distutils` but im not sure how much to change and how to make a flet version that supports only Python>=3.12.

Here are some links you may love to read to help you shift from `distutils` as the `distutils` package can still be used through other packages like `setuptools`, and other builtin modules:
- [PEP 632](https://peps.python.org/pep-0632/) which is the PEP that removed the `distutils` package.
- [Distutils Migration Guide](https://peps.python.org/pep-0632/#migration-advice) which is a guide to help developers migrate their projects from the deprecated `distutils` package.
- [setuptools](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) page to help developers migrate from `distutils`.

I hope this helps the future of Flet

**Comment by ndonkoHenri** [comment]
This was implemented some days ago: https://github.com/flet-dev/flet/commit/e0bec9d496d3d9b08a96f968ee932f43b1d3a8e3
Issue: #1962
