### ISSUE TITLE
Timeout error (110) in Flet Android client when trying to connect to app

### ISSUE THREAD

**Issue by jwlankhaar-hu** [flet-dev/flet#1994]
The Flet client on Android yields a timeout error (110) for the *hello world* app: 

```python
# main.py
import flet as ft

def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, world!")))

ft.app(main)
```

App created and run as described [here](https://flet.dev/docs/guides/python/testing-on-android):

```cmd
flet run --android
```

When scanning the QR code on the Android device the Flet client opens, but after a period of time it either shows the error or the client's home screen. Manually adding the URL results in the same error:

```
Error connecting to http://192.168.2.74:8551/myapp/main-py: <urlopen error [Errno 110] Connection timed out>
```

The troubleshooting steps described [here](https://ndonkohenri.medium.com/troubleshooting-flet-app-on-mobile-a73b535aa727) do not resolve the issue.

#### Pc
Windows 10.0.19045
Poetry environment (in combination with Pyenv):
- Python 3.11.0b4
- Flet 0.10.3

#### Android device
- Flet client version 1.1.1
- Android 12
- Realme 7 Pro

Pc and Android device are on the same WiFi network (connected to the same access point). 

### Edit Nov 13, 2023:

Replace `https` with `http` in the error message.

**Comment by ndonkoHenri** [comment]
Can you try leaving out the 's' in `https`?

**Comment by jwlankhaar-hu** [comment]
Oh, I'm sorry, that's a typo in the issue text. Actually, I did use `http` only.

**Comment by ndonkoHenri** [comment]
Ok. Try moving to the latest flet version (0.12.0) and retrying.
If the error persists then, please share a recording of the android screen before and while the error happens. 
I don't have an android (ios phone instead), and can't repro.

**Comment by juanchos0412** [comment]
In my case I realized that I had a vpn enabled on my pc so I disabled it, it still didn't work, then I ran pip install flet --upgrade again, and it worked correctly.

**Comment by ndonkoHenri** [comment]
@jwlankhaar-hu any Updates on this issue?

**Comment by jwlankhaar-hu** [comment]
@ndonkoHenri Can you please reopen the issue because the problem has not been resolved yet. I have tried it with a new virtual environment with flet 0.19.0 and a new install of the flet app on my Android, but the same error occurs.

**Comment by ndonkoHenri** [comment]
@jwlankhaar-hu Please provide more information on this issue...

**Comment by jwlankhaar-hu** [comment]
Well, the exact same situation (except for the version) holds as described above. Even a simple _hello world_ example results in a timeout error (110). There is no VPN connection enabled.

**Comment by jwlankhaar-hu** [comment]
The issue has been resolved. It turned out to be a firewall setting. I thought I had ruled that out, but I was wrong. On Windows 10 you have to add a new inbound rule for the port shown along with the QR-code. It might be a good idea to add this to the Flet documentation.

**Comment by ndonkoHenri** [comment]
Thanks for reporting back!
> On Windows 10 you have to add a new inbound rule for the port shown along with the QR-code. It might be a good idea to add this to the Flet documentation.

Can you please provide a link to what you mean, so we add it.. ?

**Comment by jwlankhaar-hu** [comment]
I wasn't able to find a proper Microsoft documentation page, but here's a description of the steps in Windows 10:
To add an inbound rule in Windows 10:
1. Click **Start** to open the Start menu and start typing *Firewall*
2. Click **Firewall & network protection**
3. Click **Advanced settings**
4. Click **Yes** to the question **Do you want to allow this app to make changes to your device?**
5. In the left panel click on **Inbound rules**
6. Click **New rule** in the right panel
7. Click **Port** and **Next**
8. Type the port number that is shown in the URL above the Flet QR code
9. Click **Next** to **Allow the connection**
10. Select the scope(s) to which the rule should apply (**Domain**, **Private** and/or **Public**)
11. Provide a name for the rule (e.g. *Flet*) and click **Finish**
