### ISSUE TITLE
Error reporting on page.set_clipboard

### ISSUE THREAD

**Issue by XueLiren** [flet-dev/flet#1996]
Hello, the following error occurred while using page.set_clipboard.

**windows:** Windows 10 22H2
**python:** 3.11
**flet:** 0.10.3
**code:** 
```py
import flet as ft


def main(page: ft.Page):
    page.set_clipboard("This value comes from Flet app")


ft.app(target=main)
```

control error: 
`
Unhandled error processing page session : Traceback (most recent call last):
  File "D:\Git\PycharmProjects\996wow\venv\Lib\site-packages\flet_runtime\app.py", line 357, in on_session_created
    session_handler(page)
  File "D:\Git\PycharmProjects\996wow\实例.py", line 5, in main
    page.set_clipboard("This value comes from Flet app")
  File "D:\Git\PycharmProjects\996wow\venv\Lib\site-packages\flet_core\page.py", line 757, in set_clipboard
    self.__offstage.clipboard.set_data(value)
  File "D:\Git\PycharmProjects\996wow\venv\Lib\site-packages\flet_core\clipboard.py", line 34, in set_data
    self.page.invoke_method("set_data", {"data": data}, control_id=self.uid)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'invoke_method'
`

ui error:
`
There was an error while processing your request: 'NoneType' object has no attribute 'invoke_method'
`

**Comment by ndonkoHenri** [comment]
Please attach more information to your dev env (flet version, py version etc).

**Comment by XueLiren** [comment]
> Please attach more information to your dev env (flet version, py version etc) as shown in the issue template.

I have added, please check
