### ISSUE TITLE
Use custom fonts

### ISSUE THREAD

**Issue by watchakorn-18k** [flet-dev/flet#20]
Is it now possible to change the font style?

**Comment by FeodorFitsner** [comment]
Do you mean changing font family, using a custom font?

**Comment by watchakorn-18k** [comment]
Yes

**Comment by FeodorFitsner** [comment]
What font would you like to use?

**Comment by watchakorn-18k** [comment]
https://fonts.google.com/specimen/Kanit

**Comment by FeodorFitsner** [comment]
Gotcha! It shouldn't be hard to add dynamic font loading to Flet. Will look into that over weekend.

**Comment by watchakorn-18k** [comment]
thank you for your hard work

**Comment by FeodorFitsner** [comment]
Let's keep it open until the feature available.

**Comment by FeodorFitsner** [comment]
It's now possible to use custom fonts in Flet apps: https://flet.dev/blog/using-custom-fonts-in-flet-app

Let me know how that worked for you!

**Comment by watchakorn-18k** [comment]
![image](https://user-images.githubusercontent.com/74919942/173283235-7d17e289-b292-4d88-a3ea-de7a2bc89dfa.png)
I have tried following this code : 
```py
import flet
from flet import Page, Text, Theme

def main(page: Page):
    page.title = "Custom fonts"

    page.fonts = {
        "Kanit": "https://raw.githubusercontent.com/google/fonts/master/ofl/kanit/Kanit-Bold.ttf"
    }

    page.theme = Theme(font_family="Kanit")

    page.add(
        Text("This is rendered with Kanit font"),
    )

flet.app(target=main, assets_dir="assets")
```

**Comment by watchakorn-18k** [comment]
![image](https://user-images.githubusercontent.com/74919942/173284055-06639d19-7926-4d41-a53d-22d455627c7e.png)
I'm sure the library has been updated.

**Comment by FeodorFitsner** [comment]
So, to make it work for Dark mode as well you have to define "dark_theme" as well. A working example:

```python
import flet
from flet import Page, Text, Theme

def main(page: Page):
    page.title = "Custom fonts"

    page.fonts = {
        "Kanit": "https://raw.githubusercontent.com/google/fonts/master/ofl/kanit/Kanit-Bold.ttf"
    }

    page.theme = Theme(font_family="Kanit")
    page.dark_theme = Theme(font_family="Kanit")

    page.add(
        Text("This is rendered with Kanit font"),
    )

flet.app(target=main, assets_dir="assets")
```

Notice `page.dark_theme = Theme(font_family="Kanit")` line.

**Comment by watchakorn-18k** [comment]
Got it thank you

**Comment by i-moohn** [comment]
page.fonts = {
        "Kanit": "https://raw.githubusercontent.com/google/fonts/master/ofl/kanit/Kanit-Bold.ttf"
    }

how can i find other fonts like this?

**Comment by m7mdleaf-del** [comment]
tho what if the font where text hint "im doing this challange trying to code a project without ai pls help 😭 "

new_task = ft.TextField(hint_text="Wrrite your command", border_color=ft.Colors.WHITE, expand=True)

**Comment by ndonkoHenri** [comment]
@m7mdleaf-del, you can style the hint text too. In `TextField`, use [`hint_style`](https://docs.flet.dev/controls/formfieldcontrol/#flet.FormFieldControl.hint_style), and if you're using a custom font, load it through [`page.fonts`](https://docs.flet.dev/controls/page/#flet.Page.fonts) first.

```python
import flet as ft

def main(page: ft.Page):
    page.fonts = {
        "Kanit": "https://raw.githubusercontent.com/google/fonts/master/ofl/kanit/Kanit-Bold.ttf"
    }

    new_task = ft.TextField(
        hint_text="Write your command",
        hint_style=ft.TextStyle(font_family="Kanit"),
        # text_style=ft.TextStyle(font_family="Kanit"),
        border_color=ft.Colors.WHITE,
        expand=True,
    )

    page.add(new_task)

ft.run(main)
```

If you want the same font everywhere in the app, you can also set:

```python
page.theme = page.dark_theme = ft.Theme(font_family="Kanit")
```
