### ISSUE TITLE
BUG feedback on page.window_frameless

### ISSUE THREAD

**Issue by XueLiren** [flet-dev/flet#2000]
Hello, there may be some problems with page.window_frameless. I can't hide the frame.

**windows:** Windows 10 22H2
**python:** 3.11
**flet:** 0.10.3
**code:** 
`
import flet as ft
from flet import *

def main(page: Page):
    page.window_max_height = 520
    page.window_max_width = 400
    **page.window_frameless = True**
    page.spacing = 0
    page.padding = 0

    widthscr = page.window_width

    page.add(
        ResponsiveRow(
            [WindowDragArea(
                Container(
                    width=widthscr,
                    bgcolor="blue",
                    padding=15,
                    content=Row([
                        Text(
                            "You Home",
                            size=30,
                            color="white"
                        )
                    ])
                )
            )]
        )
    )

ft.app(target=main)
`

![QQ截图20231028172510](https://github.com/flet-dev/flet/assets/87569941/6fc0d8a5-c1c5-480a-ab37-0bde5a81f151)

**Comment by LonelyChineseBoy** [comment]
I think what you need to hide is the window title bar, so you need to use the window_title_bar_hidden attribute. The following is how I do it in my personal project.
It should be noted that the three buttons in the upper right corner are all buttons I implemented myself, not the ones that come with it.
![image](https://github.com/flet-dev/flet/assets/59436937/d8ee6719-de71-4520-8f56-051bb205bcc4)
![image](https://github.com/flet-dev/flet/assets/59436937/99117658-e4d7-41a6-9eed-0dd73beac968)

**Comment by XueLiren** [comment]
> I think what you need to hide is the window title bar, so you need to use the window_title_bar_hidden attribute. The following is how I do it in my personal project. It should be noted that the three buttons in the upper right corner are all buttons I implemented myself, not the ones that come with it. !


You are right! I read this out-of-date tutorial 10 months ago and caused this misuse, but he did use it successfully in his video demo, probably the updated "window_title_bar_hidden" later. Thank you very much for your correction! 比心哦~
