### ISSUE TITLE
When the laptop is connected to an external display, window_center() displays incorrectly

### ISSUE THREAD

**Issue by LonelyChineseBoy** [flet-dev/flet#2001]
Environment:
python3.10
windows11

If an external display is connected, the window_center() attribute will be confused. The displayed position depends on which screen the mouse is on. If it is on the main screen, window_center() will take effect. If the mouse is on the second screen, an exception will be displayed.
The screenshot below shows the position where the application appears when the mouse is on the second screen.
![image](https://github.com/flet-dev/flet/assets/59436937/f81665fa-627d-48eb-9805-bd446e527c5e)

**Comment by ndonkoHenri** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/2390
