### ISSUE TITLE
`BottomSheet.maintain_bottom_view_insets_padding` to avoid obstructing controls with on-screen keyboard

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#2010]
![Screenshot_2023-10-21-09-18-07-148_com example flet_example](https://github.com/flet-dev/flet/assets/53087330/99d5c754-d19c-47e9-afa7-ad08e19c89b0)

**Comment by FeodorFitsner** [comment]
Internal notes: https://stackoverflow.com/a/57515977/1435891

**Comment by zox47** [comment]
can you give me the solution please because the link is for just flutter

**Comment by FeodorFitsner** [comment]
There is no solution in Flet yet - it should be implemented. Those links are for Flet devs.
