### ISSUE TITLE
jinja2-ansible-filters listed in poetry.lock - is it actually used in normal usage?

### ISSUE THREAD

**Issue by alan-copeland-keysight** [flet-dev/flet#2014]
Doing a license compliance check and Synopsys detect is flagging jinja2-ansible-filters as a GPL3 dependency. I see it listed in the poetry.lock, but don't see it in actual use. 

https://github.com/search?q=repo%3Aflet-dev%2Fflet%20jinja2-ansible-filters&type=code

Is this component actually used by Flet? Or maybe just in the tests?

**Comment by alan-copeland-keysight** [comment]
This appears to step from the use of "copier". I have asked a similar question over on the copier discussion group - https://github.com/orgs/copier-org/discussions/1397

**Comment by FeodorFitsner** [comment]
Yep, copier uses `jinja2-ansible-filters` directly: https://github.com/copier-org/copier/blob/99bdd11b6890bfb75e1b16cba15e20f64185cb49/pyproject.toml#L36

I'm not a licensing expert, but pretty sure that GPL3 is not compatible with MIT: https://www.quora.com/What-if-I-used-a-MIT-licensed-library-which-has-a-GPL-dependency

**Comment by alan-copeland-keysight** [comment]
I raised an issue over on the jinja2-ansible-filters gitlab: https://gitlab.com/dreamer-labs/libraries/jinja2-ansible-filters/-/issues/6

**Comment by FeodorFitsner** [comment]
@alan-copeland-keysight was there anything else found that requires our attention?

**Comment by alan-copeland-keysight** [comment]
copier also uses pyyaml-include, which appears to be GPL3... 

Otherwise it looks good.

Are there reasonable alternatives to copier?

**Comment by FeodorFitsner** [comment]
https://copier.readthedocs.io/en/stable/comparisons/

**Comment by FeodorFitsner** [comment]
https://github.com/cookiecutter/cookiecutter would be my #1 alternative.

**Comment by FeodorFitsner** [comment]
Could you scan https://github.com/cookiecutter/cookiecutter for licensing issues please?

**Comment by alan-copeland-keysight** [comment]
I'll try to run this tomorrow

**Comment by alan-copeland-keysight** [comment]
cookiecutter 2.4.0 seems clean, from a permissive licensing standpoint:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/acopelan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/acopelan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Component name | License names
-- | --
Click - Python Command Line Utility | BSD 3-clause "New" or "Revised" License
Jinja | BSD 3-clause "New" or "Revised" License
MarkupSafe | BSD 3-clause "New" or "Revised" License
PyYAML | MIT License
audreyr/binaryornot | BSD 3-clause "New" or "Revised" License
cookiecutter | BSD 3-clause "New" or "Revised" License
pip | MIT License
psf-requests | Apache License 2.0
py-arrow | Apache License 2.0
py-text-unidecode | Artistic License 1.0 w/clause 8
py3-markdown-it-py | MIT License
py3-mdurl | MIT License
py3-slugify | MIT License
pypi/setuptools | MIT License
python-certifi | Mozilla Public License 2.0
python-dateutil | (Apache License 2.0 OR BSD 3-clause "New" or   "Revised" License)
rich | MIT License
types-python-dateutil | Apache License 2.0
urllib3 | MIT License



</body>

</html>

**Comment by FeodorFitsner** [comment]
Thank you!

I've already started migration to cookiecutter.

**Comment by alan-copeland-keysight** [comment]
How soon do you plan on doing a release with this included?

**Comment by FeodorFitsner** [comment]
Tomorrow.

**Comment by FeodorFitsner** [comment]
It's been released in Flet 0.12.0.
