### ISSUE TITLE
Two Flet Apps integration with Main Flet App Python

### ISSUE THREAD

**Issue by Amir4python** [flet-dev/flet#2015]
I have two Flet Apps that are independent. I have another Main flet App with Two buttons, is it possible to have integration in such a way that first button should open the first FletApp, second button should open second Flet App when clicking the button.

HERE is overall flow diagram, yellow and green color are the buttons in the Main App which is main entry point.
![image](https://github.com/flet-dev/flet/assets/60217471/029d428b-5f7b-4eae-bfc5-8443ca848781)

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/guides/python/navigation-and-routing

**Comment by FeodorFitsner** [comment]
Communicating between apps is something you should solve yourself. It could be named pipes, a centralized database or something else.
