### ISSUE TITLE
how can I change windows title bar icon

### ISSUE THREAD

**Issue by ssz25** [flet-dev/flet#2019]
![QQ截图20231102230554](https://github.com/flet-dev/flet/assets/5071291/82e6f433-1746-403f-a13b-3dea5cd52eea)

how can I change windows title bar icon

like page icon  ，but cant find it

**Comment by FeodorFitsner** [comment]
Have you tried that: https://flet.dev/docs/guides/python/packaging-desktop-app#customizing-package-icon

In the meantime, we are working on the different approach.
