### ISSUE TITLE
Allow --console to be an argument when packaging

### ISSUE THREAD

**Issue by doug-benn** [flet-dev/flet#2021]
**Please Describe The Problem To Be Solved**

Allow "--console" to be an optional argument when building to allow debugging packaged apps, defaults to no console

Not sure if needed but I used it the other day - needed to edit pack.py in my install

**Suggest A Solution**

pack.py

```python
        parser.add_argument(
            "--debug-console",
            dest="debug-console",
            help="Show python console (Ensure correct DEBUG level)",
        )

...

        pyi_args = [options.script,  "--noconfirm"]
        if not options.debug_console:
            pyi_args.extend(["--noconsole"])
```

https://github.com/doug-benn/flet/commit/75eb3105a60c6171c0bcb0471559b765f7c1acac

**Comment by FeodorFitsner** [comment]
Would you like to submit a PR with that flag?
