### ISSUE TITLE
page.go - subscribe two event handlers

### ISSUE THREAD

**Issue by xzripper** [flet-dev/flet#2033]
Is there a way to subscribe two 'route_change' handlers for `page.go`?

```python
page.go('my_route', 'app_route_change') # 'app_route_change' going to be called when using `page.go` inside of an application.

page.app_route_change = lambda _: print('Route changed by application.')
page.user_route_change = lambda _: print('Route changed by user.')
```

I think its small feature but it would be very helpful for me.

**Comment by ndonkoHenri** [comment]
Can you explain your usecase?

**Comment by ndonkoHenri** [comment]
I think all route changes are actually "programmatical".
 
When the user presses a button for example, and in the event handler you do something like `page.go("/store")`, that's actually still a "Route changed by application" (to stick to your terms).

**Comment by xzripper** [comment]
But if the user changes the URL, "on_route_change" will be called as application route change.

**Comment by xzripper** [comment]
Or, just do not invoke 'on_route_change' event if dev wants it:
```python
def go(self, route, invoke_event=True, **kwargs):
    self.route = route if not kwargs else route + self.query.post(kwargs)

    if invoke_event:
      self.__on_route_change.get_sync_handler()(
          ControlEvent(
              target="page",
              name="route_change",
              data=self.route,
              page=self,
              control=self,
          )
      )
    self.update()
    self.query()  # Update query url (required when using go)
```
Is this worthy of a pull request?

**Comment by FeodorFitsner** [comment]
Yes, it is! I would make the opposite state by default though: `skip_route_change_event=False`. ;)

**Comment by xzripper** [comment]
Thank you for reply! I'll create a pull request tomorrow!

**Comment by xzripper** [comment]
Created pull request!
