### ISSUE TITLE
Desktop exit(0) doesn't work

### ISSUE THREAD

**Issue by Plumpplump** [flet-dev/flet#2036]
I did simple desktop flet app with an exit button  only (test.py).   Run it as  "python test.py". click it and call the sys.exit function and the program doesn't terminate. 

**Code example to reproduce the issue:**

import flet as ft
import sys

def main(page: ft.Page):
    page.title = 'test'

    def quitting(e):
        print("quitting")
        sys.exit(0)

    page.add(ft.ElevatedButton("Exit", on_click=quitting))

ft.app(target=main)

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

flet 0.11.0
Windows 11

**Additional environment details:**

**Comment by xzripper** [comment]
use ```page.window_destroy()```

**Comment by Plumpplump** [comment]
Thanks. It works. The only (minor) issue is window-destroy is visibility slower than clicking the x button of the window to close.
