### ISSUE TITLE
Incorrect Warning Pylance (VSCode)

### ISSUE THREAD

**Issue by elsamueldev** [flet-dev/flet#2041]
**Description**
Basically VSCode is telling me that an specific line has an error, but then I run the program and it does exactly what I wanted it to do.

**Code example to reproduce the issue:**

```python
# This appbar is going to be used in multiple pages, so I can just declare it once
appbar = ft.AppBar(title=ft.Text(value="A very cool program thanks to Flet!"), bgcolor="blue") 

appbar.title.value = "Such a wonderful GUI!"
```

**Describe the results you received:**

Warning from VSCode (Sorry for any possible typos, I have my editor in Spanish and I translated the message manually):

```
Cannot assign the member "value" for the type "Control"
  The member "value" is unknown Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

**Describe the results you expected:**

No warning I guess, since the program perfectly works

**Additional information you deem important (e.g. issue happens only occasionally):**

I think it could not be an error itself from Flet, but something very specific than occurs when you do something strange like acceding a sub-sub-attribute. I wanted to report it anyway, since even on that case, I'm pretty sure that I will receive a very good explanation.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.11.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/samuel/Workspace/flet-windows-optimizer/.venv/lib/python3.10/site-packages
Requires: copier, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:

Pop!_OS (Linux distro based on Ubuntu) 22.04 LTS.

**Additional environment details:**

I have typing enabled, and I can bypass that warning by writing an in-line comment like `# type: ignore`.

Have a nice day!

**Comment by FeodorFitsner** [comment]
So, `appbar.value` could be either `Control` or `None` and `Control` could be any control inherited from it, `Text` in your case. I guess Pylance doesn't handle generic collections/properties well.

However, you can "help" Pylance with an assertion:

```python
appbar = ft.AppBar(title=ft.Text(value="A very cool program thanks to Flet!"), bgcolor="blue") 

assert isinstance(appbar.title, ft.Text)
appbar.title.value = "Such a wonderful GUI!"
```

and warning goes away! :)

If someone knows a better way to deal with that please share your ideas!
