### ISSUE TITLE
Can we integrate an advanced chart component like Echart into Flet?

### ISSUE THREAD

**Issue by liuzhuoling2011** [flet-dev/flet#2043]
**There is a need for data chart analysis in the development process, but the current charts are too simple. Can we integrate an advanced set of chart components, similar to Echart?**

**Perhaps [Pychart](https://gallery.pyecharts.org/#/README_EN) is a very good choice.**

**Comment by liuzhuoling2011** [comment]
up

**Comment by ndonkoHenri** [comment]
Sorry to say that, but I think you should not expect every Python lib to be integrated into Flet.

**Comment by baseplate-admin** [comment]
> ECharts has provided the SVG renderer as an additional option. You can specify the [renderer parameter](https://echarts.apache.org/api.html#echarts.init) as 'canvas' or 'svg' when initializing the chart.

[Source](https://apache.github.io/echarts-handbook/en/best-practices/canvas-vs-svg/#)

But i dont think we can use pyechart directly, we have to support echarts. But setting apache echarts as a process is going to be a pain.

Overall i dont have a good way to solve this problem :) Unless we make something (chart library) for flet

**Comment by icsos** [comment]
In this case, webview is a good solution, but the desktop version has been waiting for a long time.

**Comment by liuzhuoling2011** [comment]
Now Support iOS, Android, MacOS and Web platforms， Cool～
https://flet.dev/docs/controls/webview
