### ISSUE TITLE
WindowDragArea + AppBar = Grey Square

### ISSUE THREAD

**Issue by xzripper** [flet-dev/flet#2051]
**Description**
I tried to use `WindowDragArea` with `AppBar`, but I got grey square. If single AppBar used, it works, but i'm unable to drag the window.

**Code example to reproduce the issue:**
```python
title_bar = AppBar(
    leading=Icon(config.custom_title_bar_icon),
    leading_width=30,

    title=Text(config.custom_title_bar_title),
    center_title=True,

    bgcolor=colors.SURFACE_VARIANT,

    actions=[
        IconButton(icons.CIRCLE, on_click=lambda _: [setattr(page, 'window_minimized', not page.window_minimized), page.update()]),
        IconButton(icons.SQUARE_ROUNDED, on_click=lambda _: [setattr(page, 'window_maximized', not page.window_maximized), page.update()]),
        IconButton(icons.CLOSE_ROUNDED, on_click=lambda _: page.window_close())
    ]
)

title_bar = WindowDragArea(title_bar)

page.add(title_bar)
```

**Describe the results you received:**
![Screenshot_6](https://github.com/flet-dev/flet/assets/94743980/d4d9d94e-60e7-44ad-bf80-9fcb066da24d)

**Describe the results you expected:**
I expected to drag window with AppBar.

![Screenshot_7](https://github.com/flet-dev/flet/assets/94743980/2e9c60d6-c36a-4bc8-8565-6058ebe4b4af)

(AppBar if there is no `WindowDragArea`)

**Flet version (`pip show flet`)**:

```
0.10.3
```

**Operating system**: Windows.

**Comment by xzripper** [comment]
Also it happens when using `AppBar` inside any `ConstrainedControl`..

**Comment by FeodorFitsner** [comment]
AppBar can't be used as an "independent" control and be put inside another control. On Flutter side `AppBar` widget is always attached to `Scaffold` widget. I'm afraid, this issue cannot be fixed at this stage.

You can try simulating AppBar though with other controls (Container, IconButton, etc.).

**Comment by xzripper** [comment]
Thanks :(
