### ISSUE TITLE
Unreliable detection of SVG images

### ISSUE THREAD

**Issue by zyxapple98** [flet-dev/flet#2053]
**Description**
I have a certain image (shape is 704*832). 
After converting it into base64 string, I use ft.Image(src_base64) to render that image on UI, but it turns out to be blank.
The weirdest thing is, if I modify some pixels on that image, everthing will go well.
The script producing this bug is simple and short enough, but the bug can be reproduced on multiple machines.

**Code example to reproduce the issue:**

```python
import flet as ft
import cv2 as cv
import base64
img = cv.imread('rotate.png')
#cv.line(img, (0, 0), (511, 511), (255, 0, 0), 5) # modify a few pixels and it can be displayed
_, buffer = cv.imencode('.png', img)
string =  base64.b64encode(buffer).decode('utf-8')

def main(page: ft.Page):
    page.add(
        ft.Image(
            src_base64=string,
        )
    )

ft.app(target=main)
```

**Describe the results you received:**

blank image on UI.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have reproduced this bug on three different machines. If I modify or resize the source, everything is ok.
This magical image is available in attachment.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.3
Summary: Flet for Python - easily build interactive multi-platform apps in Python
```

**Operating system**:
Windows 10
![rotate](https://github.com/flet-dev/flet/assets/42174526/729b8a0c-99b2-4553-9243-108d3212877a)

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Could you please provide a more complete repro with image contents? Output that `string` and paste it here?

**Comment by zyxapple98** [comment]
Sure, here's the string, please check in rotate.txt:
[rotate.txt](https://github.com/flet-dev/flet/files/13319515/rotate.txt)


> Could you please provide a more complete repro with image contents? Output that `string` and paste it here?
