### ISSUE TITLE
HTML as string and render it to GUI supporting CSS and javascript!

### ISSUE THREAD

**Issue by dipeshSam** [flet-dev/flet#2064]
**Flet should have a control or widget that can render html text with CSS and javascript support to the text, design and logic.**

**Comment by bevzocry** [comment]
https://flet.dev/docs/controls/webview
Waiting for supports desktop and browser versions

**Comment by fuad00** [comment]
> Waiting for supports desktop and browser versions

also waiting custom headers functionality

**Comment by FeodorFitsner** [comment]
Please use [WebView](https://flet.dev/docs/controls/webview) control.
