### ISSUE TITLE
File Upload/Download not working properly in server. 

### ISSUE THREAD

**Issue by ipritom** [flet-dev/flet#2067]
My flet app is working fine in windows environment. Now the app is deployed in the Linux Server. But file upload/download not working Properly. 

The following way I've assigned the directories. 

```python
ft.app(target=main, host=host_ip, port=host_port, view=ft.WEB_BROWSER,
        upload_dir="uploads", assets_dir="uploads")
```
Anyone encountered the same problem? Did you solve the issue? 
Flet Version: 0.11.0 
Server: Ubuntu 20.04

**Comment by AngRotanak** [comment]
I face this problem too wen I hosting my app in Cloud run . App work in local well can upload normal
