### ISSUE TITLE
can_reveal_password function does not work

### ISSUE THREAD

**Issue by Razielthc** [flet-dev/flet#2071]
Hello, I am trying to create a desktop app, I have used a ft.UserControl to create new views and call them from an app.py def main(page: ft.Page):
    page.title = "AutoPark MX"
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    width = win32api.GetSystemMetrics(0)
    height = win32api.GetSystemMetrics(1)
    page.window_width = width // 2
    page.window_height = height // 2
    page.window_resizable = False
    page.window_maximizable = False
    page.window_center()

    app1 = ViewLogin(page)

    # add application's root control to the page
    page.add(app1)
    page.update()

ft.app(target=main, assets_dir="src/imagenes") 

The ViewLogin contains a simple form but when using can_reveal_password=True it doesn't work, do I have to do an extra step? For a desktop app, is this the best route to follow or is there a complete example?

class ViewLogin(ft.UserControl):
    def __init__(self, page):
        super().__init__()
        self.page = page
        self.ancho_pagina = page.window_width
        self.alto_pagina = page.window_height

    def build(self):
        def add_click(e):
            home = ViewHome(self.page)
            self.page.add(home)
            self.clean()

        img = ft.Image(
            src=f"AutoParkMX_login.png",
            fit=ft.ImageFit.CONTAIN,
        )

        img_content = ft.Container(content=img,
                                   alignment=ft.alignment.center,
                                   expand=True,
                                   bgcolor=ft.colors.CYAN,
                                   padding=0
                                   )

        input_user = ft.TextField(label="Usuario", border=ft.InputBorder.UNDERLINE)
        input_password = ft.TextField(label="Contraseña", border=ft.InputBorder.UNDERLINE, password=True,
                                      can_reveal_password=True)

        form_content = ft.Container(
            content=ft.Column(
                [ft.Row([ft.Icon(name=ft.icons.PERSON, color=ft.colors.PRIMARY), input_user]),
                 ft.Row([ft.Icon(name=ft.icons.KEY, color=ft.colors.PRIMARY), input_password]),
                 ft.FilledButton(content=ft.Text(value="INGRESAR", size=35))],
                alignment=ft.alignment.center,
                horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                spacing=self.alto_pagina // 12),
            alignment=ft.alignment.center,
            expand=True,
            padding=self.ancho_pagina // 12
        )

        return ft.Column(
            [ft.Container(
                content=ft.Row([img_content, form_content],
                               alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                               vertical_alignment=ft.CrossAxisAlignment.START)
            )]
        )

**Comment by ndonkoHenri** [comment]
Can you try the [example from the docs](https://flet.dev/docs/controls/textfield#password-with-reveal-button) and let us know if it works on your end?

**Comment by Razielthc** [comment]
yes it works, but not from a control added with userControl,

**Comment by ndonkoHenri** [comment]
Ok. Please build a runnable code repro so I can try... (the code in your first comment is not that runnable)

**Comment by Razielthc** [comment]
> Ok. Please build a runnable code repro so I can try... (the code in your first comment is not that runnable)

https://github.com/Razielthc/AutoParkMX1.0/invitations

**Comment by ndonkoHenri** [comment]
Please share the code here... (a simple repro) 😄

**Comment by Razielthc** [comment]
import flet as ft
from src.config import config
from src.views.login import ViewLogin
import win32api


def main(page: ft.Page):
    page.title = "AutoPark MX"
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    width = win32api.GetSystemMetrics(0)
    height = win32api.GetSystemMetrics(1)
    page.window_width = width // 2
    page.window_height = height // 2
    page.window_resizable = False
    page.window_maximizable = False
    page.window_center()

    app = ViewLogin(page)


    # add application's root control to the page
    page.add(app)
    page.update()


ft.app(target=main, assets_dir="assets")

if __name__ == '__main__':
    pass

**Comment by Razielthc** [comment]
import flet as ft
from src.model.User import User, find
from src.views.home import ViewHome


class ViewLogin(ft.UserControl):
    def __init__(self, page):
        super().__init__()
        self.page = page
        self.ancho_pagina = page.window_width
        self.alto_pagina = page.window_height
        self.input_user = ft.TextField(label="Usuario", border=ft.InputBorder.UNDERLINE)
        self.input_password = ft.TextField(label="Contraseña", border=ft.InputBorder.UNDERLINE, password=True,
                                           can_reveal_password=True)

    def build(self):
        def verificar(e):
            user_bd = find("sup")
            self.page.session.set("usuario", user_bd)

            home = ViewHome(self.page)
            self.clean()

            # contenido = ft.Row(
            #     [
            #         ft.Container(content=ft.Column([ft.Text("Hola")]),
            #                      bgcolor=ft.colors.ORANGE_300,
            #                      alignment=ft.alignment.center,
            #                      expand=True,
            #                      ),
            #         ft.VerticalDivider(),
            #         ft.Container(
            #             bgcolor=ft.colors.BROWN_400,
            #             alignment=ft.alignment.center,
            #             expand=True,
            #         ),
            #         ft.VerticalDivider(width=1, color="white"),
            #         ft.Container(
            #             bgcolor=ft.colors.BLUE_300,
            #             alignment=ft.alignment.center,
            #             expand=True,
            #         ),
            #         ft.VerticalDivider(width=9, thickness=3),
            #         ft.Container(
            #             bgcolor=ft.colors.GREEN_300,
            #             alignment=ft.alignment.center,
            #             expand=True,
            #         ),
            #     ],
            #     spacing=0,
            #     expand=True,
            # )

            self.page.add(home)

            # user = self.input_user.value
            # password = self.input_password.value
            # user_bd = find(user)
            # if user_bd is not None:
            #     if user_bd.user == user:
            #         if user_bd.password == password:
            #             self.page.session.set("usuario", user_bd)
            #
            #             home = ViewHome(self.page)
            #             self.page.add(home)
            #             self.clean()
            #         else:
            #             self.input_user.error_text = ""
            #             self.update()
            #             self.input_password.error_text = "tu contraseña es incorrecta"
            #             self.update()
            # else:
            #     self.input_user.error_text = "Usuario no encontrado"
            #     self.update()

        image = ft.Image(src="/imagenes/AutoParkMX_login.png", fit=ft.ImageFit.CONTAIN)

        img_content = ft.Container(content=image,
                                   alignment=ft.alignment.center,
                                   expand=True,
                                   bgcolor=ft.colors.CYAN,
                                   padding=0
                                   )

        form_content = ft.Container(
            content=ft.Column(
                [ft.Row([ft.Icon(name=ft.icons.PERSON, color=ft.colors.PRIMARY), self.input_user]),
                 ft.Row([ft.Icon(name=ft.icons.KEY, color=ft.colors.PRIMARY), self.input_password]),
                 ft.FilledButton(content=ft.Text(value="INGRESAR", size=35), on_click=verificar)],
                alignment=ft.alignment.center,
                horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                spacing=self.alto_pagina // 12),
            alignment=ft.alignment.center,
            expand=True,
            padding=self.ancho_pagina // 12
        )

        return ft.Column(
            [ft.Container(
                content=ft.Row([img_content, form_content],
                               alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                               vertical_alignment=ft.CrossAxisAlignment.START)
            )]
        )


if __name__ == "__main__":
    pass
