### ISSUE TITLE
AlertDialog content wrongly displayed on mobile

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#2073]
### Discussed in https://github.com/flet-dev/flet/discussions/2068

<div type='discussions-op-text'>

<sup>Originally posted by **Klu1d** November 11, 2023</sup>
### Question

_I_ ran this code from the documentation in the flet application from the appstore, and I get this bug or error. What is the reason for this and how to fix it?

![IMG_1715](https://github.com/flet-dev/flet/assets/105982046/1ead2ee0-67f5-4088-83a8-42c921d9e8a8)

### Code sample

```python
import flet as ft

def main(page: ft.Page):
    page.title = "AlertDialog examples"

    dlg = ft.AlertDialog(
        title=ft.Text("Hello, you!"), on_dismiss=lambda e: print("Dialog dismissed!")
    )

    def close_dlg(e):
        dlg_modal.open = False
        page.update()

    dlg_modal = ft.AlertDialog(
        modal=True,
        title=ft.Text("Please confirm"),
        content=ft.Text("Do you really want to delete all those files?"),
        actions=[
            ft.TextButton("Yes", on_click=close_dlg),
            ft.TextButton("No", on_click=close_dlg),
        ],
        actions_alignment=ft.MainAxisAlignment.END,
        on_dismiss=lambda e: print("Modal dialog dismissed!"),
    )

    def open_dlg(e):
        page.dialog = dlg
        dlg.open = True
        page.update()

    def open_dlg_modal(e):
        page.dialog = dlg_modal
        dlg_modal.open = True
        page.update()

    page.add(
        ft.ElevatedButton("Open dialog", on_click=open_dlg),
        ft.ElevatedButton("Open modal dialog", on_click=open_dlg_modal),
    )

ft.app(target=main)
```

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

**Comment by ndonkoHenri** [comment]
@FeodorFitsner, this issue has been resolved right?

**Comment by FeodorFitsner** [comment]
Yep!

**Comment by aurosevic** [comment]
I'm encountering a similar issue on iOS. This is what is being displayed with the same code that @ndonkoHenri provided.


![IMG_6899](https://github.com/flet-dev/flet/assets/19304661/f6f628dd-bb2d-4730-b0b6-07fe6c6696b1)

**Comment by ndonkoHenri** [comment]
Sorry for that. We are aware of the bug and are working on a solution.

**Comment by FeodorFitsner** [comment]
I can confirm, there is an annoying bug. Working on it.
Btw,  if you test your app on a mobile without Flet app it should work normally.

**Comment by FeodorFitsner** [comment]
The issue has been closed because PR with a fix was merged into `main`.
However, for you to "see" the fix we should release Flet app update. Will be released in a day-two, thanks for your patience.
