### ISSUE TITLE
Mobile height and width, Feature Request

### ISSUE THREAD

**Issue by lekshmanmj** [flet-dev/flet#2079]
It will be better if we are able to get mobile height and width, expand works only when directly adding container to page and not while passing container inside flet.View

**Comment by ndonkoHenri** [comment]
to get the size of your app on mobile, use `page.width` and `page.height`

**Comment by FeodorFitsner** [comment]
Right. There was a regression which is now fixed: https://github.com/flet-dev/flet/issues/1960
