### ISSUE TITLE
TypeError: FilePicker.__init__() got an unexpected keyword argument 'file_type'

### ISSUE THREAD

**Issue by ipritom** [flet-dev/flet#2080]
The following code shows error

```python
file_picker = ft.FilePicker(on_result=upload_file_picked, on_upload=on_upload_progress, file_type=ft.FilePickerFileType.IMAGE)
```

But in the documentation `file_type` argument is a valid argument.

https://flet.dev/docs/controls/filepicker/#file_type

flet                     0.12.0
flet-core                0.12.0
flet-runtime             0.12.0

**Comment by ndonkoHenri** [comment]
It works as expected on my end. Please build a repro.

**Comment by taaaf11** [comment]
> The following code shows error

What is the error?
