### ISSUE TITLE
navigation drawer does not work on mobile

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2084]
### Discussed in https://github.com/flet-dev/flet/discussions/2070

<div type='discussions-op-text'>

<sup>Originally posted by **xtream-club** November 11, 2023</sup>
Navigation drawer does not work on mobile.  When deploying my application with serious python using navigation drawer it tells me that navigation drawer is not a flutter control and shows an error.  I don't know if it hasn't been tested on android yet or what the problem is.  But it seems that it does not work on mobile devices at the moment.</div>

**Comment by FeodorFitsner** [comment]
"Flet" mobile app must be updated and republished.

**Comment by andrerotband** [comment]
@FeodorFitsner can I help with this subject?

Checking class Page I identified a difference between drawer and the others Offstages:

Ex:  Banner:

```python
   def show_banner(self, banner: Banner):
        self.__offstage.banner = banner
        self.__offstage.banner.open = True
        self.__offstage.update()

    async def show_banner_async(self, banner: Banner):
        self.__offstage.banner = banner
        self.__offstage.banner.open = True
        await self.__offstage.update_async()
```

And now Drawer:

```python
    def show_drawer(self, drawer: NavigationDrawer):
        self.drawer = drawer
        self.drawer.open = True
        self.update()

    async def show_drawer_async(self, drawer: NavigationDrawer):
        self.drawer = drawer
        self.drawer.open = True
        await self.update_async()
```

Why aren't you using __offstage?

I apologize if this has already been reviewed.

Best regards!

**Comment by ndonkoHenri** [comment]
Update the app... it works!

**Comment by FeodorFitsner** [comment]
Yep, and I'm working on 1.2.1 update with this fix: https://github.com/flet-dev/flet/issues/2108
