### ISSUE TITLE
Ability to expand `ButtomSheet` to the top of the screen

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2087]
### Discussed in https://github.com/flet-dev/flet/discussions/2074

<div type='discussions-op-text'>

<sup>Originally posted by **Klu1d** November 12, 2023</sup>
### Question

"ButtomSheet" turned out to be a very successful control element for me. But what I lack in it is the ability to fill the entire screen with this control. For example, as in the images I attached. Or as, for example, "Container (expand=True)". The "ButtonSheet" itself does not have properties such as "expand" or "height" and "width", is it possible to implement this somehow or make at least a temporary solution? So that I can expand the "ButtomSheet" to full screen. Because I can't do it
![Снимок экрана от 2023-11-12 23-48-34](https://github.com/flet-dev/flet/assets/105982046/7286475a-67ce-4259-a57e-807a086dc208)
![Снимок экрана от 2023-11-12 23-43-46](https://github.com/flet-dev/flet/assets/105982046/9d983796-0d8e-401b-a3e7-19238b624b01)

### Code sample

```python
import flet as ft

def main(page: ft.Page):
    def bs_dismissed(e):
        print("Dismissed!")

    def show_bs(e):
        bs.open = True
        bs.update()

    def close_bs(e):
        bs.open = False
        bs.update()

    bs = ft.BottomSheet(
        ft.Container(
            ft.Column(
                [
                    ft.Text("This is sheet's content!"),
                    ft.ElevatedButton("Close bottom sheet", on_click=close_bs),
                ],
                tight=True,
            ),
            height=500,
            width=300,
            expand=True,
            padding=10,
        ),
        open=True,
        enable_drag=True,
        on_dismiss=bs_dismissed,
    )
    page.overlay.append(bs)
    page.add(ft.SafeArea(
        ft.ElevatedButton("Display bottom sheet", on_click=show_bs)
    ))

ft.app(target=main)
```

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

**Comment by Klu1d** [comment]
I tested the "ButtomSheet" from 0.12.1, everything works fine in desktop and web applications. That's just when testing on a mobile device (iOS), the original problem remains. The first image is a desktop application, the second is a mobile one.
![desktop](https://github.com/flet-dev/flet/assets/105982046/06824a40-85d5-415d-975b-92b42feb3c9e)
![mobile](https://github.com/flet-dev/flet/assets/105982046/526ace38-9c3a-4869-a509-a1d688e32eba)

**Comment by FeodorFitsner** [comment]
Flet for mobile app update is needed. Working on it.
