### ISSUE TITLE
Feature Request: Expanded class like flutter

### ISSUE THREAD

**Issue by lekshmanmj** [flet-dev/flet#2097]
Reference: [https://api.flutter.dev/flutter/widgets/Expanded-class.html](url)

**Comment by ndonkoHenri** [comment]
Every flet control has a prop named [`expand`](https://flet.dev/docs/controls/#expand). It internally implements the flutter's `Expanded` widget.

**Comment by lekshmanmj** [comment]
here in flet... flex is not available, whereas in flutter it has flex param

**Comment by ndonkoHenri** [comment]
In Flet you do `expand=2`, for example: `2` here is actually the `flex`.

**Comment by lekshmanmj** [comment]
> In Flet you do `expand=2`, for example: `2` here is actually the `flex`. Flet's API tries to keep things simple...

Thanks a lot for informing
