### ISSUE TITLE
Error keyboard not showing

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#2098]
https://github.com/flet-dev/flet/assets/53087330/646d1d56-6a4b-4617-be5d-010c43d416a5

**Comment by FeodorFitsner** [comment]
Could you please provide code to reproduce?

**Comment by zox47** [comment]
> Could you please provide code to reproduce?

loginnow = ListView(expand=1, spacing=0, auto_scroll=True)
    loginnow.controls.append(Container(content=Column(controls=[
                            Container(alignment=alignment.center,
                                      content=Image(src="logo.png", width=200, height=200), ),
                            Container(alignment=alignment.center,
                                      content=Text(value="كيتي حلويات", font_family="arabic", size=25))])))

    loginnow.controls.append(Container(content=ResponsiveRow(controls=[
        Card(height=300, width=page.window_width, content=Column(controls=[

            Container(margin=10, padding=10, content=Column(spacing=20, controls=[
                Text("تسجيل الدخول", font_family="arabic", size=15),
                TextField(prefix_icon=icons.EMAIL,
                          label="البريد الإلكتروني",
                          keyboard_type=KeyboardType.EMAIL, ),
                TextField(prefix_icon=icons.PASSWORD, password=True,
                          label="كلمة المرور",
                          keyboard_type=KeyboardType.NAME, ), ])),

            Container(alignment=alignment.center, content=OutlinedButton("تسجيل الدخول", width=300, ))]))
    ])))

elif page.route == "/log-in":
            page.views.append(
                View(
                    "/log-in",
                    [

                        AppBar(

                            color="white",
                            leading=Container(padding=5,content=IconButton(icon=icons.ARROW_BACK_IOS_OUTLINED, on_click=welcom_page,icon_color=colors.ON_BACKGROUND)),
                            leading_width=40,
                            #title=Text("Kiti Halawiyat", color=colors.ON_BACKGROUND, font_family="zenburn"),

                            center_title=False,
                            # bgcolor=colors.CYAN_500,

                        ),

                        loginnow,

**Comment by FeodorFitsner** [comment]
Could you do a complete, runnable example please?
How do you run that example on mobile: with Flet app or your own?

**Comment by zox47** [comment]
> Could you do a complete, runnable example please? How do you run that example on mobile: with Flet app or your own?

im run this with my own mobile

**Comment by zox47** [comment]
I found the solution the problem is about View i'm not using page.views.clear() when i change between the pages
