### ISSUE TITLE
Way to remove the frame of the window?

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#210]
I don't know if it exists in flutter but is there a way to remove the entire frame of the windows to put a custom title bar?

and also is there a way to make the window resizable and movable with custom title bar?

**Comment by FeodorFitsner** [comment]
Sure, there is a Flutter component for that: https://github.com/bitsdojo/bitsdojo_window/tree/master/bitsdojo_window

Vote/subscribe for this issue please: https://github.com/flet-dev/flet/issues/40

I'm closing this issue as a duplicate.

**Comment by FeodorFitsner** [comment]
This is an example of Flet app that removes system title bar and uses it's own controls to move and close window: https://flet.dev/docs/controls/windowdragarea#app-window-without-a-title-that-can-be-moved
