### ISSUE TITLE
Page::Session::Set Doesn't work when using hot reloading.

### ISSUE THREAD

**Issue by xzripper** [flet-dev/flet#2100]
**Description**

When running application with hot loader, many strange issues happening: `Page::Session::Set` doesn't work (simply doesn't  registers key), issues with `Page::Go`. When running application normally it works very good.

**Code example to reproduce the issue:**

```python
def register(error_message):
    username_str = username.value
    email_str = email.value
    password_str = password.value

    if len(username_str) <= 5:
        error_message.value = 'Username should be at least 5 characters.'

        pg.page.update()

        return

    if not match(r'^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', email_str):
        error_message.value = 'Invalid Email.'

        pg.page.update()

        return

    if len(password_str) <= 8:
        error_message.value = 'Password should be at least 8 characters.'

        pg.page.update()

        return

    username_busy = False
    email_busy = False

    for user in db.get_value('users'):
        if user.username == username_str: username_busy = True
        if user.email == email_str: email_busy = True

    if username_busy and email_busy:
        error_message.value = 'Username and Email is already busy.'

        pg.page.update()

        return

    elif username_busy:
        error_message.value = 'Username is already busy.'

        pg.page.update()

        return

    elif email_busy:
        error_message.value = 'Email is already busy.'

        pg.page.update()

        return

    user = UserModel(username_str, email_str, password_str, [])

    db.get_value('users').append(user)

    db.commit()

    pg.page.session.set('user', username_str) # Here issue happens.

    pg.navigator.navigate('/', pg.page) # And here.
```

**Describe the results you received:**
`user` key wasn't registered, and page hasn't changed.

**Describe the results you expected:**
I expected it to register `user` key and change page to `/`.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issues happening only in hot reload mode.

**Flet version (`pip show flet`)**:

```
0.10.3
```

**Operating system**:
Windows 10

**Comment by xzripper** [comment]
Hot reload:
![chrome_bXd84gZVss](https://github.com/flet-dev/flet/assets/94743980/692e66ae-3786-4b24-bab9-e1fe2dcaa180)

No hot reload:
![chrome_9WEfT08NFD](https://github.com/flet-dev/flet/assets/94743980/548a0a81-7e35-45c8-bb57-cf12ab26f772)

**Comment by xzripper** [comment]
UPDATE: After committing to the database, the file is updated, so the application is restarted, so these two lines won't be executed:
```python
pg.page.session.set('user', username_str)

pg.navigator.navigate('/', pg.page)
```
Maybe it's possible to fix it via ignoring database directory?

**Comment by xzripper** [comment]
#2105 - This pull request attempts to fix this issue, but when a small change is made in the code, the application updates and all `page.session' keys are deleted.

**Comment by FeodorFitsner** [comment]
So we need to use some external storage for session? I guess it could be just a json file somewhere in user's documents directory?

**Comment by FeodorFitsner** [comment]
Fixed in https://github.com/flet-dev/flet/pull/2105
