### ISSUE TITLE
Agregar DateRangePiker 

### ISSUE THREAD

**Issue by enmanuelbcf** [flet-dev/flet#2102]
Se puede agregar un witget que permita seleccionar un rango de fecha y con las validación que conlleva

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/datepicker

**Comment by enmanuelbcf** [comment]
No, es un selector que admite dos fechas

**Comment by ndonkoHenri** [comment]
Provide links to what you mean please.
