### ISSUE TITLE
Can’t dismiss the NavigationDrawer programmatically? 

### ISSUE THREAD

**Issue by Plumpplump** [flet-dev/flet#2107]
**Description**

I am testing the new NavigationDrawer control. How do I programmatically dismiss the drawer when I click one item inside to navigate to another page?  I can’t find a function like .close() or .dismiss().

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
This is an interesting issue. 
Found a thread on SO: https://stackoverflow.com/questions/43807184/how-to-close-scaffolds-drawer-after-an-item-tap

**Comment by Plumpplump** [comment]
To pop（）？ how to do it in python?

**Comment by FeodorFitsner** [comment]
Oh, it's just `drawer.open = False`

```python
import flet as ft


def main(page: ft.Page):
    def close_drawer(e):
        page.drawer.open = False
        page.drawer.update()

    page.drawer = ft.NavigationDrawer(
        controls=[
            ft.NavigationDrawerDestination(icon=ft.icons.ABC, label="Item 1"),
            ft.NavigationDrawerDestination(icon=ft.icons.FILE_COPY, label="Item 2"),
        ],
        on_change=close_drawer,
    )

    def show_drawer(e):
        page.drawer.open = True
        page.drawer.update()

    page.add(
        ft.SafeArea(
            ft.ElevatedButton("Show drawer", on_click=show_drawer),
        )
    )


ft.app(main)
```

**Comment by ndonkoHenri** [comment]
Haha, I missed that. 
By the way, I think we need helper methods such as `page.show_drawer(drawer)` and `page.close_drawer()`

**Comment by FeodorFitsner** [comment]
There are such methods: https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-core/src/flet_core/page.py#L1057-L1099

**Comment by ndonkoHenri** [comment]
Oh, you are right! 😆
