### ISSUE TITLE
Can not open project on iOS Flet app after scanning the QR code from termianl

### ISSUE THREAD

**Issue by aurosevic** [flet-dev/flet#2108]
**Description**

Just like before I would start the Flet development server on desktop and scan the given QR code with phone, but now I couldn't get the app running on iOS.

I am getting the following error message:
![IMG_6797](https://github.com/flet-dev/flet/assets/19304661/65d5ee15-7644-4b09-a4b9-047d469a89e4)

I was not doing anything new in comparison to running it before. The only thing that has changed is that iOS Flet app has been updated to use Flet SDK 0.12.2, which is exactly the Flet version in venv from which I'm trying to run the app.

Here's the terminal output: 
`(venv) andrija@multiverse:~/PycharmProjects/finance-buddy$ flet --version
0.12.2`

I've tried copying the server url and pasting it to iOS app, and that worked. This indicates that there most likely might be a problem with QR code.

**Code example to reproduce the issue:**

```python
flet run app.py --ios
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```(venv) andrija@multiverse:~/PycharmProjects/finance-buddy$ flet --version
0.12.2
```

**Operating system**:

Desktop: KDE Neon 5.27
Mobile: iPhone 13 Pro Max, iOS 17.1.1

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Can you instead try to give the link from the terminal into the app?

**Comment by aurosevic** [comment]
Yes I can, I wrote that. That's why I said it is most likely a problem with QR code.

**Comment by Plumpplump** [comment]
Same problem in Android too.

**Comment by FeodorFitsner** [comment]
Thank you for reporting that! We can confirm the issue and working on the fix. Hopefully, an update will be approved by Monday.

**Comment by aurosevic** [comment]
It's fixed, thanks!

**Comment by shefa** [comment]
It's not fixed for android it seems, I think it's a problem with the https://android.flet.dev/ website or the flet://flet-host handler

let's say my app is runing on `name.com`
if I go to android flet app and manually add the address `http://name.com` it works.
previously, I could go to `https://android.flet.dev/name.com` and it would redirect or open the link `flet://flet-host/http%3A%2F%2Fname.com` which would then add the project in my android flet app automatically.

Currently, the website works the same, but the link `flet://flet-host/http%3A%2F%2Fname.com` is not recognized by the flet app - it shows this error `<urlopen error unknown url type: flet>`

**Comment by FeodorFitsner** [comment]
We are still working on an update for Android. Sorry for the delay guys!

**Comment by FeodorFitsner** [comment]
Android app has been updated. It should be fixed now.
