### ISSUE TITLE
Great library, thanks a lot ~😍

### ISSUE THREAD

**Issue by lijinshanmx** [flet-dev/flet#213]
very good library.👍

**Comment by lijinshanmx** [comment]
![image](https://user-images.githubusercontent.com/6552340/185871466-626865a7-3fba-4cc0-b82a-8c0a8a8009b2.png)

**Comment by lijinshanmx** [comment]
![Screenshot_20220822_160807](https://user-images.githubusercontent.com/6552340/185871762-7585ad71-5405-466d-87ff-c55fb1c2f74c.png)

**Comment by lijinshanmx** [comment]
![Screenshot_20220822_160915](https://user-images.githubusercontent.com/6552340/185871914-cc392713-d4ea-4860-b02f-38248d7ef016.png)

**Comment by FeodorFitsner** [comment]
Why close the issue? :) Have you got any success with running Flet on Android? What was your process?

**Comment by lijinshanmx** [comment]
Yes, I run it successfully, my idea is to write python code on the phone, and then run it on the phone. Now it is running successfully on android9, but on android12 it prompts me that I do not have permission to run fletd, although I added chmod+x permission to it

**Comment by lijinshanmx** [comment]
I cross-compiled fletd and reported an error because the content folder is missing, and it cannot be empty. Just place an empty file in it. Then compile the executable file of fletd-arm64-v8a,Then put fletd under cache/tmp/ and set runnable permissions.But it was successful on lower versions of Android, and I haven't found the cause of the problem in higher versions.

**Comment by lijinshanmx** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6552340/185960427-a413621e-bfe8-49ea-beec-994c587e3de5.png">

**Comment by FeodorFitsner** [comment]
What program is on the left screenshot?

**Comment by lijinshanmx** [comment]
https://pub.dev/packages/chaquopy ,I use this pub package to run python programs on the flutter side.

**Comment by lijinshanmx** [comment]
I think you've got the full idea of ​​what I'm thinking now😄😄

**Comment by FeodorFitsner** [comment]
Ah, nice! It's getting together in my head now :) So, there is a Flutter widget for using Chaquopy SDK!
Will take a look - it will help me to figureout the best way to package Flet apps for mobile. Thank you!

**Comment by lijinshanmx** [comment]
Yes, completely native, no network required. Just run fletd locally. But the current problem is: there is no permission to run fletd on android12. Adding chmod+x doesn't work either. I have time to continue researching this issue. Finally, thanks again for the flet library.😍😍

**Comment by FeodorFitsner** [comment]
Interesting though that [flet-linux-arm64.tar.gz](https://github.com/flet-dev/flet/releases/download/v0.1.52/flet-linux-arm64.tar.gz) Flutter client worked, right :)

**Comment by FeodorFitsner** [comment]
Of course, `goos=android`!

So, Flet app on your phone is opening in the browser?

**Comment by lijinshanmx** [comment]
No, I am in the #211 you just submitted, this client can run directly, just specify the port. Both remain the same. They communicate via websockets you wrote [fletd].

**Comment by FeodorFitsner** [comment]
Smart! 😀 Didn't expect someone to notice that FletApp was moved into a separate Flutter package!
