### ISSUE TITLE
Add `Dismissible.confirm_dismiss` event handler

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2130]

**Comment by ndonkoHenri** [comment]
Another prop you could add [`behavior`](https://api.flutter.dev/flutter/widgets/Dismissible/behavior.html).
I didnt find it useful. If you don't too, then please remove the variable...

**Comment by ndonkoHenri** [comment]
https://api.flutter.dev/flutter/widgets/Dismissible/confirmDismiss.html
