### ISSUE TITLE
FilePick cannot open  the native file explorer

### ISSUE THREAD

**Issue by NjustWrun** [flet-dev/flet#2131]
I had use filePick on KylinOS， but cannot open the nativae file explorer

**Comment by taaaf11** [comment]
Prolly you need to install `zenity` on the OS.

> INFO
> In Linux, the FilePicker control depends on [Zenity](https://help.gnome.org/users/zenity/stable/) when running Flet as an app. > This is not a requirement when running Flet in a browser.

> To install Zenity on Ubuntu/Debian run the following commands:

`sudo apt-get install zenity`

sudo apt-get install zenity

**Comment by taaaf11** [comment]
Prolly you need to install zenity on the OS.

It is mentioned in the docs: [Flet File picker docs](https://flet.dev/docs/controls/filepicker)

INFO
In Linux, the FilePicker control depends on [Zenity](https://help.gnome.org/users/zenity/stable/) when running Flet as an app. This is not a requirement when running Flet in a browser.

To install Zenity on Ubuntu/Debian run the following commands:

sudo apt-get install zenity

**Comment by NjustWrun** [comment]
ok, thanks.
