### ISSUE TITLE
Webview does not work in v0.13.0, blank screen on Android device

### ISSUE THREAD

**Issue by t3ch9** [flet-dev/flet#2132]
Using code snippet from webview example on [](https://flet.dev/docs/controls/webview/#examples)

Launching flet via command: flet run --android

Android device output: 
![2023-11-23-222628](https://github.com/flet-dev/flet/assets/29530317/edbff79e-f0b9-4f6f-b78f-4b5ff749b4df)

**Comment by ndonkoHenri** [comment]
Can you update the App from the store?

**Comment by Plumpplump** [comment]
Also doesn’t work on my android phone. I updated the app. But error is the same before and after.

**Comment by t3ch9** [comment]
I've upgraded to the latest Android app and have restarted the flet process. Is working now. Thank you

**Comment by t3ch9** [comment]
![2023-11-24-085334](https://github.com/flet-dev/flet/assets/29530317/c377f117-67d0-41a4-9b05-c1f8cc8ac59d)
