### ISSUE TITLE
Support for pyinstaller's --uac-admin flag for flet pack

### ISSUE THREAD

**Issue by azhago** [flet-dev/flet#2144]
Flet pack provide many options for creating a desktop app, but --uac-admin flag is missing for running an app as admin under windows.

With packaging directly with pyinstaller, i'm not able to change all the icons of the app, only the binary icon.  

Is it possible to add this feature?

**Comment by FeodorFitsner** [comment]
Would you like to submit PR with that?

**Comment by azhago** [comment]
> Would you like to submit PR with that?

It's pretty new to me, but i submit a PR with the addition.
