### ISSUE TITLE
Markdown image does not support svg or it is broken

### ISSUE THREAD

**Issue by Petrox** [flet-dev/flet#2160]
**Description**

Markdown supports images.
Flet supports images.
Flet images support svg.

Markdown does not seem to work with svgs.

**Code example to reproduce the issue:**

```python
md1 = """
hello

![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://myoctocat.com/assets/images/base-octocat.svg)

world
"""

def main(page: ft.Page):
    page.scroll = "auto"
    page.add(
        ft.Markdown(
            md1,
            selectable=True,
            extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
            on_tap_link=lambda e: page.launch_url(e.data),
        )
    )

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

**Describe the results you received:**

![kép](https://github.com/flet-dev/flet/assets/3036509/a08ad36d-a605-4d1a-9b3a-ec0fa3a7451a)

**Describe the results you expected:**

hello
![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://myoctocat.com/assets/images/base-octocat.svg)
world

This code was directly copied from the github markdown docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
0.11
0.13

**Operating system**:

Win10

**Additional environment details:**
Does not work in either windows native app or web app either.

Note: the svg could contain links so clicking those should cause on_tap_link events in theory.

**Comment by Petrox** [comment]
👍

**Comment by FeodorFitsner** [comment]
You can test this feature with pre-release build of Flet.
