### ISSUE TITLE
File Upload in android mode not working

### ISSUE THREAD

**Issue by lekshmanmj** [flet-dev/flet#2172]
Code used : https://github.com/flet-dev/examples/blob/main/python/controls/file-picker/file-picker-upload-progress.py
Checked from android device and from linux browser using the link displayed in android mode

File upload is not working when using following commands to run app.
1. flet run main.py --android
2. flet run main.py --web --port 8551

But it is working(on random port which is auto generated or given) only when using below command.
flet run main.py --web

PFA short specific debug file fetched from app connection start to close ....in android device(cmd used: flet run main.py --android)
[flet.log](https://github.com/flet-dev/flet/files/13530633/flet.log)

**Comment by lekshmanmj** [comment]
New Information: Upload issue arises only while using default port 8551.

**Comment by ibrahimkimaro** [comment]
hello bro

**Comment by ibrahimkimaro** [comment]
i was stuck in uploading image file   into backend by testing in android device....can you help me with that stuff?....issue it open() the image file and the error occur  content = open(file_name, 'rb+')
              ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.appveyor.flet/cache/file_picker/IMG-20240516-WA0051.jpg'
