### ISSUE TITLE
Data loss using Sqlite with Serious Python and Flet in Android Studio

### ISSUE THREAD

**Issue by goncaze** [flet-dev/flet#2189]
**Description**

I made a very simple example to test Sqlite with Flet and Serious Python in Android Studio. When running the Android emulator, it turns out that my app starts normally. Supposedly it supports error-free data insertion into the sqlite file. However, after closing my application and opening it again, all registered data disappeared.

**Code example to reproduce the issue:**

```python
import flet as ft
import sqlite3


class Book():
    def __init__(self, id:int=None, title:str=None) -> None:
        self.id = id
        self.title = title

def main(page:ft.Page):
    conexao = sqlite3.connect("assets/agenda.db", check_same_thread=False)
    cursor = conexao.cursor() 

    book_table = """CREATE TABLE IF NOT EXISTS book(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    title TEXT NOT NULL
    )"""        
    cursor.execute(book_table)
    conexao.commit()    

    def select_books()->list[Book]:
        book_list:list[Book] = []
        sql = "SELECT * FROM book"
        res = cursor.execute(sql)        
        for el in res:
            book = Book(id=el[0], title=el[1])
            book_list.append(book)
        return book_list        

    def insert_book(book:Book):
        params = (book.title,)
        sql = """INSERT INTO book(title) 
        VALUES(?)"""
        cursor.execute(sql, params)
        conexao.commit()

    def book_title_loading():
        dt_book_title.rows.clear()
        for el in select_books():
            dt_book_title.rows.append(
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text(el.id)),
                        ft.DataCell(ft.Text(el.title)),
                    ],
                )
            )

    def register_book_title_clicked(e):
        book = Book(title=ttf_book_title.value)
        insert_book(book=book)
        book_title_loading()
        ttf_book_title.value = ""
        page.update()      

    ttf_book_title = ft.TextField(label="Book title", hint_text="Enter title", autofocus=True)
    btn_register_book_title = ft.ElevatedButton(text="Register title", on_click=register_book_title_clicked)

    dt_book_title = ft.DataTable(
            columns=[
                ft.DataColumn(ft.Text("Id")),
                ft.DataColumn(ft.Text("Book title"))
            ],
            rows=None
    )     

    col_books = ft.Column(
        visible=True,
        scroll=ft.ScrollMode.ALWAYS,
        controls=[dt_book_title]
    )

    cnt_col_jogos = ft.Container(
        content= col_books,
        # alignment=ft.alignment.top_center,
        expand=True,
    )

    book_title_loading()

    page.add(ft.Text(value="Hello Sqlite3"))
    page.add(ttf_book_title)
    page.add(btn_register_book_title)
    page.add(cnt_col_jogos)

ft.app(target=main, assets_dir="assets")
```

**Describe the results you received:**

After registering data in Sqlite, I close the application. When opening again, the data no longer exists and this is the problem, that is, where did the data go?

**Describe the results you expected:**

Using the Nexus 6 Android emulator (API 34), when opening the application for the second time, I EXPECTED to see the previously registered data. However, the data that was registered disappears, that is, it does not remain and was simply lost. This behavior is not repeated when run through a web page or desktop.

**Additional information you deem important (e.g. issue happens only occasionally):**

Nothing out of the ordinary.

**Flet version (`pip show flet`)**:

```
(.venv) D:\PROJETOS\IFMA\FLET_PYTHON\titulo_livro>pip show flet
Name: flet
Version: 0.14.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: D:\PROJETOS\IFMA\FLET_PYTHON\titulo_livro\.venv\Lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Edição	Windows 11 Home Single Language
Versão	22H2
Instalado em	‎23/‎09/‎2022
Compilação do SO	22621.2715
Experiência	Windows Feature Experience Pack 1000.22677.1000.0

**Additional environment details:**

Processador	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
RAM instalada	20,0 GB (utilizável: 19,9 GB)
ID do dispositivo	904D41CD-A7B8-483F-9102-12DED6F5C888
ID do Produto	00327-30048-10912-AAOEM
Tipo de sistema	Sistema operacional de 64 bits, processador baseado em x64
Caneta e toque	Nenhuma entrada à caneta ou por toque disponível para este vídeo

**pip freeze**

(.venv) D:\PROJETOS\IFMA\FLET_PYTHON\titulo_livro>pip freeze
antiorm==1.2.1
anyio==4.1.0
arrow==1.3.0
binaryornot==0.4.4
certifi==2023.11.17
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cookiecutter==2.5.0
db==0.1.1
db-sqlite3==0.0.1
flet==0.14.0
flet-core==0.14.0
flet-runtime==0.14.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.6
Jinja2==3.1.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
oauthlib==3.2.2
packaging==23.2
Pygments==2.17.2
pypng==0.20220715.0
python-dateutil==2.8.2
python-slugify==8.0.1
PyYAML==6.0.1
qrcode==7.4.2
repath==0.9.0
requests==2.31.0
rich==13.7.0
six==1.16.0
sniffio==1.3.0
text-unidecode==1.3
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
urllib3==2.1.0
watchdog==3.0.0
websocket-client==1.6.4
websockets==11.0.3

**flutter --version**

(.venv) D:\PROJETOS\IFMA\FLET_PYTHON\titulo_livro>flutter --version

Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (10 weeks ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

**Android Studio**

Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 20, 2023
Runtime version: 11.0.15+0-b2043.56-9505619 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    PythonCore (221.6008.17)
    Dart (221.6103.1)
    io.flutter (74.0.1)

**Comment by FeodorFitsner** [comment]
This is because when running serious_python in **debug** mode the destination folder where Python app.zip is unpacked is re-created ([relevant code](https://github.com/flet-dev/serious-python/blob/main/src/serious_python_platform_interface/lib/src/utils.dart#L27-L30)) and you are creating Sqlite database inside app directory (`sqlite3.connect("assets/agenda.db"`).

Run in release mode and the contents of app dir will be preserved or, alternatively, create database outside app directory (take parent dir from current dir and create a new sub-dir).

**Comment by goncaze** [comment]
The difference between running in debug mode or not is between using (SHIFT + F9) to Debug or (SHIFT + F10) to avoid Debug? I always run (SHIFT + F10) without Debug. I had also tried to create the Sqlite file outside of assets and next to main.py but I was also unsuccessful. @FeodorFitsner

**Comment by FeodorFitsner** [comment]
Can't comment on Android Studio as I use VS Code, sorry.

Re: folder - `assets` is part of the app and will be recreated as well. Take higher. On Android/iOS the app is unpacked to `{user_documents_dir}/flet-app-dir-{version}/main.py`, so you need to take current dir in your Python app `os.getcwd()` - that will be `{user_documents_dir}/flet-app-dir-{version}` and then take it's parent to get to `{user_documents_dir}`. Create your own directory under `{user_documents_dir}`.

This way the data will be preserved even between app upgrades.

Hope that helps.

Maybe we should add an option to preserve app content in debug mode.

**Comment by FeodorFitsner** [comment]
btw, I love your example and I'd like to use it in Flet docs (if you don't mind?), but I'm having trouble running it locally on macOS:

```
conexao = sqlite3.connect("assets/agenda.db", check_same_thread=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

Do you know why?

**Comment by goncaze** [comment]
I'll be happy if you want to use my example!
This was exactly the error that was appearing to me in Android Studio (unable to open database file). After I changed the sqlite file directory outside of assets, this error message stopped appearing. However, the data disappeared when opening this example application for the second time.

**Comment by FeodorFitsner** [comment]
Fixed with this:

```python
    db_path = Path(__file__).parent.joinpath("assets/agenda.db")
    conexao = sqlite3.connect(db_path, check_same_thread=False)
```

**Comment by goncaze** [comment]
I believe this error "sqlite3.OperationalError: unable to open database file" is the same as this error "There was an error while processing your request: unable to open database file". I believe this error occurs only because there was an attempt to create the sqlite file within a non-existent directory. Therefore, there will be no error message when creating inside a directory like "assets" if it exists or creating the sqlite file next to main.py. However, running Android Studio in "debug mode" results in data loss when closing the application in the emulator, even if the assets directory exists. So, I followed your suggestion to run it as "release" instead of "debug mode" in Android Studio by clicking "Flutter run 'main.dart' in Release Mode" and it happened all good. The data was not lost and now I feel more motivated with Flet.

**Comment by shouryashashank** [comment]
> Fixed with this:
> 
>     db_path = Path(__file__).parent.joinpath("assets/agenda.db")
>     conexao = sqlite3.connect(db_path, check_same_thread=False)

.parent here gives the current directory.

```
db_path = Path(__file__).parent.parent.joinpath("dbname.db")
```
this worked for me
