### ISSUE TITLE
Can't import "KeyboardEvent" module

### ISSUE THREAD

**Issue by Poleyn** [flet-dev/flet#219]
When i tried [this](https://flet.dev/docs/guides/python/keyboard-shortcuts) - [examples](https://github.com/flet-dev/examples/blob/main/python/controls/page/keyboard-events.py) im getting this error
`cannot import name 'KeyboardEvent' from 'flet'`

**Comment by FeodorFitsner** [comment]
Have you updated flet module to the latest version?

**Comment by Poleyn** [comment]
flet version is 0.1.50
