### ISSUE TITLE
Tab label and indicator alignment issue with Flet >= 0.12

### ISSUE THREAD

**Issue by girip11** [flet-dev/flet#2198]
**When I use the Tabs snippet from this [link](https://flet.dev/docs/controls/tabs/#examples) with flet 0.10 or 0.11, it renders as shown in the snippet page. But the same snippet when used with Flet >= 0.12 onwards renders with the first tab label misaligned.**

This is the snippet I used.

```python
import flet as ft

def main(page: ft.Page):

    t = ft.Tabs(
        selected_index=1,
        animation_duration=300,
        tabs=[
            ft.Tab(
                text="Tab 1",
                content=ft.Container(
                    content=ft.Text("This is Tab 1"), alignment=ft.alignment.center
                ),
            ),
            ft.Tab(
                tab_content=ft.Icon(ft.icons.SEARCH),
                content=ft.Text("This is Tab 2"),
            ),
            ft.Tab(
                text="Tab 3",
                icon=ft.icons.SETTINGS,
                content=ft.Text("This is Tab 3"),
            ),
        ],
        expand=1,
    )

    page.add(t)

ft.app(target=main)
```

Output in Flet 0.10.3 or 0.11.0. This is what is also expected.

![image](https://github.com/flet-dev/flet/assets/5471162/d20ecd84-4472-4f27-91c7-2934a892c5a6)

![image](https://github.com/flet-dev/flet/assets/5471162/e81eebcd-be7e-4560-ab3c-6e1f33bba935)

Output in Flet >=0.12.x onwards including 0.14.0

![image](https://github.com/flet-dev/flet/assets/5471162/4a51f91f-148a-4450-8813-16d9303ce4f1)
![image](https://github.com/flet-dev/flet/assets/5471162/ec9cbb6f-e05d-44bd-9311-300e974761d6)

**Operating system**:
![image](https://github.com/flet-dev/flet/assets/5471162/d4c89dc6-25af-45c7-a29d-99f30cd20c63)

**Additional environment details:**
Python version 3.11.5

**Comment by indigo360** [comment]
Confirm that I'm seeing the same problem here, the tabs have shifted to the right for me as well in later felt builds
<img width="717" alt="Screenshot 2023-12-05 at 19 22 51" src="https://github.com/flet-dev/flet/assets/33873235/d8183754-e8b0-4862-b36a-be89fe30ee26">

**Comment by FeodorFitsner** [comment]
Implement https://api.flutter.dev/flutter/material/TabBar/tabAlignment.html

**Comment by Klu1d** [comment]
And there is a software option to move Tabs slightly to the right. For example, to have a button on the left, or some kind of container, or an icon. I used this error, how can I repeat it now in an official way? :)

**Comment by Klu1d** [comment]
there is a software option to move the tabs slightly to the right. For example, to have a button on the left, or some kind of container, or an icon. I used this bug as a feature and I really liked it, how can I repeat it now in an official way? :)
