### ISSUE TITLE
feature: implement flutter's TextSelection class

### ISSUE THREAD

**Issue by DarkWolf260** [flet-dev/flet#2206]
Flet should have events for text selection or be able to call an event that interacts with the selected text.

Useful for any case that requires manipulating a text selection.

Use Case: how to make a text editor with functions like bold, underline or italic.

plz :'(

Link to Flutter:
https://api.flutter.dev/flutter/services/TextSelection-class.html

**Comment by yunguangli** [comment]
I second this.

**Comment by ndonkoHenri** [comment]
Already present:
https://github.com/flet-dev/flet/blob/edf1fb66c934b5a19c96d5f1e2e495fa279e4b69/sdk/python/packages/flet-core/src/flet_core/text.py#L34-L45

Atm `Markdown` makes [use](https://flet.dev/docs/reference/types/markdownselectionchangeevent#selection) of it. In the next release `Text` will have an `on_selection_change` event property, which will also make use of it to provide more details on the selected text.
