### ISSUE TITLE
TextField with key attribute set makes the field untypable

### ISSUE THREAD

**Issue by girip11** [flet-dev/flet#2223]
Consider the following snippet with two text fields with a label and key configured.

```python
    # This is buggy
    # Try typing hello in the text field 1 and world in text field 2
    page.add(
        ft.Row(
            controls=[
                ft.Container(content=ft.TextField(label="Field1", key="txt1")),
                ft.Container(content=ft.TextField(label="Field2", key="txt2")),
            ],
        ),
    )
```

When typing value in the text field 1 the cursor moves elsewhere after the typing a character. In the below image, control goes somewhere after typing `a`. 
![image](https://github.com/flet-dev/flet/assets/5471162/902f18b9-22d5-4a62-84d2-26f065b877a3)

But I can type the content well when the `key` set on the text field is removed or `key=None`
![image](https://github.com/flet-dev/flet/assets/5471162/2c7887d4-c75d-4d30-a876-58e1a4918c61)

```python
    # This works
    # Try typing hello in the text field 1 and world in text field 2
    page.add(
        ft.Row(
            controls=[
                ft.Container(content=ft.TextField(label="Field1")),
                ft.Container(content=ft.TextField(label="Field2")),
            ],
        ),
    )
```

My expectation is with and without key set on the text field, the behavior should be identical. I assumed `key` is set to store some string and use it to identify the control in the logic.

Let me know if the `key` is meant to be used for something else. Also does the `key` have to be unique globally across all widgets in an application? 

**Flet version (`pip show flet`)**:

![288023547-ec9cbb6f-e05d-44bd-9311-300e974761d6](https://github.com/flet-dev/flet/assets/5471162/a405782e-26b7-4083-95b8-c5e4f5ca4de7)

**Operating system**:
![288024267-d4c89dc6-25af-45c7-a29d-99f30cd20c63](https://github.com/flet-dev/flet/assets/5471162/2d01b78e-2936-4858-a9a5-3a0c6e7964c6)

**Additional environment details:**

**Comment by girip11** [comment]
Looks like Row and Container layout controls are also impacted when key is set as per [this issue](https://github.com/flet-dev/flet/issues/2210)

The use case I am reporting is when the `key` is set on a `TextField` control

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of https://github.com/flet-dev/flet/issues/2210

**Comment by ndonkoHenri** [comment]
This issue has been fixed in the [latest pre-release](https://flet.dev/blog/introducing-flet-1-0-alpha#trying-flet-10-alpha) and the code you provided now works as expected.
