### ISSUE TITLE
Swipe Functions

### ISSUE THREAD

**Issue by Bakhishov** [flet-dev/flet#2233]
How can i swipe a container to the left for update or to the right for delete? Is it possible in flet?

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/dismissible ?

**Comment by Bakhishov** [comment]
Have you checked this yourself? How to add function to the left swipe and to the right swipe?

**Comment by Bakhishov** [comment]
The function I need is similar to Slidable in Flutter.
