### ISSUE TITLE
Problem app publish - flet-pyodide module not installed

### ISSUE THREAD

**Issue by IevgenSherstiuk** [flet-dev/flet#2239]
**Description**

Can't test simple flet app by python http.server

Chrome console error:
"/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async"

with "pip install flet"  module flet-pyodide not installed.

After manual "pip install flet-pyodide" now having error - "No module named 'flet_js'"

python
3.11.3

**Comment by ndonkoHenri** [comment]
Try `flet build web`.
If you still receive errors, please share repro with issue.
