### ISSUE TITLE
Sharp corners for NavigationDrawer

### ISSUE THREAD

**Issue by Endogen** [flet-dev/flet#2254]
I can't find a way to have sharp edges for the `NavigationDrawer` component. Since most other components in Flet seems to be able to set round or sharp corners, I believe that having this feature in this component too would be appropriate.

Current style:
![image](https://github.com/flet-dev/flet/assets/226475/76b20f5b-c557-4a4c-8f33-169028fa0a78)

IMO something like this should be possible:
![image](https://github.com/flet-dev/flet/assets/226475/0b79fdac-f99d-481a-b7fb-bfb8145f2d5e)

**Comment by FeodorFitsner** [comment]
Rounded corners is a "feature" of M3 Navigation Drawer: https://m3.material.io/components/navigation-drawer/overview :)
I don't see the way to specify sharp corners in Flutter [NavigationDrawer](https://api.flutter.dev/flutter/material/NavigationDrawer-class.html) widget though.

Maybe, you could implement your own "drawer" in Python from existing Flet controls (Stack, Container, Buttons, etc.) with [fly-in/out animation](https://flet.dev/docs/guides/python/animations#offset-animation).

**Comment by Endogen** [comment]
"I don't see the way to specify sharp corners in Flutter NavigationDrawer widget though". I'm not sure I unterstand exactly what you mean. Are you saying you don't think it's needed or are there technical reasons not to do it?

**Comment by FeodorFitsner** [comment]
I mean Flutter's widget does not allow controlling the shape of corners. Technical reason.
