### ISSUE TITLE
[BUG] AlertDialog not updating properly for me since release `v0.15.0`

### ISSUE THREAD

**Issue by lbedner** [flet-dev/flet#2275]
**Description**

I currently use the [`ft.AlertDialog`](https://github.com/flet-dev/flet/blob/c357207cbf5a14c4cecc7670b359097a36b06934/sdk/python/packages/flet-core/src/flet_core/alert_dialog.py#L9) control to do the following things:

- ask the user to confirm something
- when they click the appropriate `actions` button:
    - I clear the `actions` list
    - I `append` a [`ft.ProgressRing`](https://github.com/flet-dev/flet/blob/c357207cbf5a14c4cecc7670b359097a36b06934/sdk/python/packages/flet-core/src/flet_core/progress_bar.py#L15) control to the `actions` list
    - I `update()` the control to see the changes
    - I run some command that takes X seconds
    - I close the dialog

In practice it looks like this:

![alert_dialog_success](https://github.com/flet-dev/flet/assets/3474138/a6f5241f-1d49-47ba-bc82-cd7866a29e22)

Since the release of [`v0.15.0`](https://github.com/flet-dev/flet/releases/tag/v0.15.0), however, it has stopped working. The update is not reflected on the front end, so I don't see the buttons removed and the progress bar added to the `actions` list. The code does run, however, and the alert dialog is closed after X seconds.

I did some hunting around, and found this PR https://github.com/flet-dev/flet/pull/2192 (which was a part of [`v0.15.0`](https://github.com/flet-dev/flet/releases/tag/v0.15.0)) which looks to be the last change made to the `AlertDialog` control.

**Code example to reproduce the issue:**

```python
import flet as ft

import time


def main(page: ft.Page):
    def open_dialog(e):
        page.show_dialog(alert_dialog)

    def close_dialog(e):
        print("Modifying dialog content...")
        alert_dialog.content = ft.Text("Closing dialog...")
        print("Clearing dialog actions...")
        alert_dialog.actions.clear()
        print("Adding progress bar to dialog actions...")
        alert_dialog.actions.append(ft.ProgressBar())
        print("Updating dialog...")
        alert_dialog.update()

        print("Sleeping for 5 seconds...")
        time.sleep(5)

        print("Closing dialog...")
        page.close_dialog()

    # Create the button that opens the dialog
    open_button = ft.ElevatedButton(
        text="Open Dialog",
        on_click=open_dialog,
    )

    # Create the button inside the dialog
    dialog_button = ft.ElevatedButton(
        text="Close Dialog",
        on_click=close_dialog,
    )

    # Create the alert dialog
    alert_dialog = ft.AlertDialog(
        title=ft.Text("Alert Dialog"),
        content=ft.Text("This is an alert dialog."),
        actions=[dialog_button],
        modal=True,
    )

    # Add the open button to the page
    page.add(open_button)


ft.app(target=main)
```

**Describe the results you received:**

![alert_dialog_failure](https://github.com/flet-dev/flet/assets/3474138/3a63e0be-71ee-436e-b0c5-b26014fc6660)

Notice how if I click the button to bring up the `AlertDialog` control again, I will actually see the updated `actions` list, with a progress bar as expected? So for whatever reason, I'm just not able to see the initial `update()` when it is opened the first time.

Also, below is the output statements to the console:

```
James@jamesbednermbp ~/W/P/ee-toolset (flet-0.17.0-again)> flet run alert_dialog_test.py -d
Modifying dialog content...
Clearing dialog actions...
Adding progress bar to dialog actions...
Updating dialog...
Sleeping for 5 seconds...
Closing dialog...
```

**Describe the results you expected:**

I expect to see the `AlertDialog` control immediately updated.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.15.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/James/.virtualenvs/ee_toolset/lib/python3.11/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: ee-toolset
```

**Operating system**:

macOS Big Sur - Version 11.6.4

**Comment by FeodorFitsner** [comment]
Flet update with the fix will be released later today (or early tomorrow).

**Comment by lbedner** [comment]
Thanks for the speedy fix!
