### ISSUE TITLE
ExpansionPanelList doesn't support ExpansionPanel generated from UserControl

### ISSUE THREAD

**Issue by johnnychen94** [flet-dev/flet#2279]
I'm not sure if this is a bug or I mistakenly used it. The first three panel instances generated from custom `ft.UserControl` class aren't recognized by `ExpansionPanelList`. Intuitively, the first three should be rendered exactly as the last three.

![image](https://github.com/flet-dev/flet/assets/8684355/4ff29750-75a9-43dd-9e0b-2e91839e4af3)

```python
import flet as ft

ExpansionPanelColors = [
    ft.colors.GREEN_500,
    ft.colors.BLUE_800,
    ft.colors.RED_800,
]


class MyExpansionPanel(ft.UserControl):
    def __init__(self, id: int):
        super().__init__()
        if id >= len(ExpansionPanelColors):
            raise ValueError("too large id")
        self.id = id

    def build(self):
        bgcolor = ExpansionPanelColors[self.id]

        exp = ft.ExpansionPanel(
            bgcolor=bgcolor,
            header=ft.ListTile(title=ft.Text(f"Panel {self.id}")),
        )

        exp.content = ft.ListTile(
            title=ft.Text(f"This is in Panel {self.id}"),
            subtitle=ft.Text(f"Press the icon to delete panel {self.id}"),
            trailing=ft.IconButton(ft.icons.DELETE, data=exp),
        )
        return exp


def main(page: ft.Page):
    panel = ft.ExpansionPanelList(
        expand_icon_color=ft.colors.AMBER, elevation=8, divider_color=ft.colors.AMBER
    )

    # using UserControl
    for id in range(3):
        exp = MyExpansionPanel(id)
        panel.controls.append(exp)

    # without using UserControl
    for id in range(3):
        bgcolor = ExpansionPanelColors[id]

        exp = ft.ExpansionPanel(
            bgcolor=bgcolor,
            header=ft.ListTile(title=ft.Text(f"Panel {id}")),
        )

        exp.content = ft.ListTile(
            title=ft.Text(f"This is in Panel {id}"),
            subtitle=ft.Text(f"Press the icon to delete panel {id}"),
            trailing=ft.IconButton(ft.icons.DELETE, data=exp),
        )
        panel.controls.append(exp)

    page.add(panel)

ft.app(target=main)
```

This is tested on macOS with flet 0.17:

```
❯ poetry show | grep flet
flet                      0.17.0       Flet for Python - easily build inter...
flet-core                 0.17.0       Flet core library
flet-runtime              0.17.0       Flet Runtime - a base package for Fl...
```

**Comment by ndonkoHenri** [comment]
Instead of inheriting from a `UserControl`, inherit from an `ExpansionPanel` as below:
```py
import flet as ft

ExpansionPanelColors = [
    ft.colors.GREEN_500,
    ft.colors.BLUE_800,
    ft.colors.RED_800,
]


class MyExpansionPanel(ft.ExpansionPanel):
    def __init__(self, id: int):
        super().__init__()
        if id >= len(ExpansionPanelColors):
            raise ValueError("too large id")
        self.id = id

        self.bgcolor = ExpansionPanelColors[self.id]
        self.header = ft.ListTile(title=ft.Text(f"Panel {self.id}"))

        self.content = ft.ListTile(
            title=ft.Text(f"This is in Panel {self.id}"),
            subtitle=ft.Text(f"Press the icon to delete panel {self.id}"),
            trailing=ft.IconButton(ft.icons.DELETE, data=self),
        )


def main(page: ft.Page):
    panel = ft.ExpansionPanelList(
        expand_icon_color=ft.colors.AMBER, elevation=8, divider_color=ft.colors.AMBER
    )

    # using UserControl
    for id in range(3):
        exp = MyExpansionPanel(id)
        panel.controls.append(exp)

    # without using UserControl
    for id in range(3):
        bgcolor = ExpansionPanelColors[id]

        exp = ft.ExpansionPanel(
            bgcolor=bgcolor,
            header=ft.ListTile(title=ft.Text(f"Panel {id}")),
        )

        exp.content = ft.ListTile(
            title=ft.Text(f"This is in Panel {id}"),
            subtitle=ft.Text(f"Press the icon to delete panel {id}"),
            trailing=ft.IconButton(ft.icons.DELETE, data=exp),
        )
        panel.controls.append(exp)

    page.add(panel)


ft.app(target=main)
```

**Comment by johnnychen94** [comment]
@ndonkoHenri  Thanks for the solution. I've also come up with a similar one using a plain function:

```python
def MyExpansionPanel(id: int) -> ft.ExpansionPanel: 
    ...
```

But this could be more intuitive and straightforward to me. This might a question on UserControl instead: what I understood from the docs and codebase is that users are recommended to use `UserControl` if they want to build a re-usable component on top of flet, but the flet codebase seldom uses `UserControl` itself.

So my further question is: what should the user expect from the `UserControl` thing? In what scenarios will `UserControl` be the best choice and in what scenarios will `UserControl` fail to work? When reading the docs, could users expect and understand this behavior until they actually tried it?

My current understanding is to limit `UserControl` in layout, and don't try too much on functionality composition.

**Comment by ndonkoHenri** [comment]
> but the flet codebase seldom uses UserControl itself.

Flet controls do not inherit from the `Usercontrol`, but instead from the base class named `Control`.
 
> what should the user expect from the UserControl thing? In what scenarios will UserControl be the best choice and in what scenarios will UserControl fail to work? 

If you have a look at the usercontrol's [source code](https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-core/src/flet_core/user_control.py), you will notice it actually inherits from a `Stack` control. 

Tbh with you, when creating a [custom control](https://github.com/ndonkoHenri/Flet-Custom-Controls), i inherit most often directly from an already existing Flet control instead of from the `UserControl`. 

A scenario in which the usercontrol will definitely not be a good choice is one in which a precise control is expected. That with the expansion panels is the perfect example.

Hope all this makes some sense... 😅

@FeodorFitsner, any addition? 🙂

**Comment by FeodorFitsner** [comment]
My only addition is that introducing `UserControl` was a mistake leading to a lot of confusion 🥹
Correct way is, like you said, inheriting directly from existing Flet controls and I'm going to reflect that in a new user guide for that.
