### ISSUE TITLE
Add HTML iframe for Embed in flet web or desktop

### ISSUE THREAD

**Issue by bobwatcherx** [flet-dev/flet#2280]
Is there any plan to add an iframe html widget to the desktop or web file? For example, I want to embed the Google Maps code and display it on my web flet . thx

**Comment by ndonkoHenri** [comment]
You mean webview, right?

**Comment by bobwatcherx** [comment]
> You mean webview, right?

yes . webview for web and desktop

**Comment by ndonkoHenri** [comment]
Closing as dup of https://github.com/flet-dev/flet/issues/432
