### ISSUE TITLE
`flet build` to add timestamp (hash) asset with Flet Python app to re-extract when code changes

### ISSUE THREAD

**Issue by wschume** [flet-dev/flet#2289]
**Description**

With the release of flet 0.18 the build linux command appears to have an issue. The issue arises when trying to **recompile** a modified script. No change to the script is reflected in the compiled executable.

Steps to reproduce:

1. Create a new project with `flet create first_try`
2. Compile the project with `flet build linux`
3. Execute the binary and see the `Hello, Flet!` text in the application.
4. Modify the `main.py` script from say: `Hello, Flet!` to `Hello World!`.
5. Recompile the project with `flet build linux`
6. Execute the binary and now you still see `Hello, Flet!` instead of `Hello World!`.

The built targets I tried are `linux` and `apk`. The issue does not arise for the `apk` target.

Even a change in the build output directory (`-o`) does not influence the behavior and the result of the recompiled binary is still `Hello, Flet!`.

**Code example to reproduce the issue:**

First version of the script:
```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)
```
Edited version of the script:
```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello World!")))


ft.app(main)
```

**Flet version (`pip show flet`)**:

```
0.18.0
```

**Operating system**:

Linux

**Comment by FeodorFitsner** [comment]
When the app is starting it unpacks contents of `app.zip` (with Python code) to `{temp}/{app-name}-{version}-{build}` directory. Next time the app is run it does not re-create/change that directory contents if it exists. The solution is to change version (`--build-version`) or build number (`--build-number`) if you want to see a refreshed app package.

This is not an idea solution, of course. The way it could be improved, I think, would be adding some "timestamp" (asset) along with `app.zip` asset and then placing that timestamp inside extracted directory. Timestamp will be changed every time you re-build the app.

**Comment by acidicly** [comment]
Can second this. Also had this issue and solved it by changing the build number on Debian 11.

**Comment by acidicly** [comment]
@FeodorFitsner may I recommend using the hash of the program files as an identifier. It completely changes with even a slight change to the source code.

**Comment by wschume** [comment]
I tested the suggested workaround and unfortunately and in contrary to @acidicly, setting a `--build-version` or a `--build-number` did not change the behavior described issue above. I am on a `uname -a: Linux caddy 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

The only parameter I can set, that changes the outcome of the built is the `--project` parameter.
