### ISSUE TITLE
Closing App

### ISSUE THREAD

**Issue by Charles808** [flet-dev/flet#229]
How to close the app programmatically ?

I used page.window_full_screen = True, which make the close button cannot be seen
So, I need to make my own button to close flet.

I tried, several things like:
1. exit()
2. quit()
3. sys.exit()
4. page.close()
5. etc

But nothing works..
I need the full window to be True, cause in my case window_maximized is not working,
even after I called page.update()

**Comment by fauzaanu** [comment]
Did you try this? https://flet.dev/docs/controls/page/#window_destroy

**Comment by FeodorFitsner** [comment]
What operating system are you running it on?

**Comment by Charles808** [comment]
@fauzaanu I think I miss that info from the doc, I tried it and it works ! Thank you ! 

@FeodorFitsner It is on windows. Anyway, Thanks to @fauzaanu it is working as expected. But just for info, window_maximized  is not working after set to true, I have seen other solved issue regarding to this problem. It set both left and top window to zero, then set maximized to true, and called page.update(). Weirdly, it is not working on my case, the window still minimized.

**Comment by FeodorFitsner** [comment]
Thank you for the update! I'm working on a fix for window_maximized which will be published tomorrow.

**Comment by FeodorFitsner** [comment]
There is a new method on the block! [`page.window_close()`](https://flet.dev/docs/controls/page/#window_close) which closes window and causes close intercepting logic to work.

**Comment by FeodorFitsner** [comment]
Just released Flet 0.1.53 with `window_maximized` fix.
