### ISSUE TITLE
Addition of on_application_shutdown or on_window_close hook for compiled applications

### ISSUE THREAD

**Issue by acidicly** [flet-dev/flet#2293]
Normally when I wanted to execute code post ui shutdown (either a crash or the user simply closing the window) I put the code after the `ft.app` call and it executed before the application was fully closed, however this does not work when the application is built with `flet build`. As such I propose the addition of a `on_application_shutdown ` or `on_window_close ` that executes the code as the application is shutdown.

**Comment by FeodorFitsner** [comment]
Could you please provide a code to reproduce/demonstrate the issue?
