### ISSUE TITLE
Flet application entry point renders different results for Linux and Android target

### ISSUE THREAD

**Issue by wschume** [flet-dev/flet#2295]
**Description**

It is best practice to use a 

```python
def main():
    pass

if __name__ == "__main__":
    main()
```

construct when writing python programs. This helps unit testing the code and brings other benefits as well.

Using the above described construct together with `flet build`, renders the desired behavior for the `linux` target. However, running an application on Android, results in a black screen, with no controls being visible.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)
```

versus

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))

if __name__ == "__main__":
    ft.app(main)
```

**Describe the results you received:**

In the above lower example no page is being rendered on an Android target.

**Describe the results you expected:**

Just like executing the code in a venv or a compiled Linux application, the page should be visible.

**Flet version (`pip show flet`)**:

```
0.18.0
```

**Operating system**:

Linux

**Comment by baseplate-admin** [comment]
This is a known issue : https://github.com/flet-dev/serious-python/issues/53

**Comment by wschume** [comment]
Yep, @baseplate-admin, thank you for the link. This is duplicate and needs to be closed.
