### ISSUE TITLE
app doesn't have a CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by techemmy** [flet-dev/flet#230]
Is this app open-source?
I love this project and I'd love to be a contributor but I can't find the CONTRIBUTING.md file

**Comment by FeodorFitsner** [comment]
Thanks for your interest!

There is an open issue for creating contributing guide: https://github.com/flet-dev/flet/issues/165

What would you like to contribute?

**Comment by techemmy** [comment]
I'm looking to contribute to the python part of the code since that's the only one I'm knowledgeable in out of all languages you use.

**Comment by techemmy** [comment]
Do you mind if I move the CONTRIBUTING.md file to the main directory so that it'll be easy for new visitors to find it?

or perhaps, I should add a message and link of the CONTRIBUTING.md to the README.md file indicating how to contribute?

**Comment by FeodorFitsner** [comment]
Sure, let's move it. Please do a PR.

once it's moved to the root I will add about Flutter part.

**Comment by techemmy** [comment]
Okay
