### ISSUE TITLE
flet build apk

### ISSUE THREAD

**Issue by Aporial** [flet-dev/flet#2302]
Good day. There are several questions about the new functionality in 0.18.0.
1. When creating an apk using `flet build apk`, the following do not work:  `--project`, `--description`, `--product`, `--org`.
2. I used serious python before. You could put a file with a security key (
![image](https://github.com/flet-dev/flet/assets/7197773/76e46d97-ad62-4ca0-b2d3-9d0d92740e60)
) that the play market requires. How to do this with the current functionality of `flet build apk`?
3. The created apk does not have access to the Internet.

**Comment by fsmosca** [comment]
@Aporial

What exactly do you mean by "The created apk does not have access to the Internet."

**Comment by Aporial** [comment]
> @Aporial
> 
> What exactly do you mean by "The created apk does not have access to the Internet."

I have 2 checks in my application. checking ping to Google and checking connection to Firebase. When I create an apk file using serious python, everything works. But with the new method it doesn’t work

**Comment by fsmosca** [comment]
@Aporial 

I experienced the same issue. I use detabase from [deta space](https://deta.space) to store todo list. I built apk using `flet build apk`. Installed in android device and run it. It could not save todo items. In windows desktop the same code can save todo items in detabase.

How did you solve it?
