### ISSUE TITLE
```flet build``` with ```A package may not list itself as a dependency.``` error occurs

### ISSUE THREAD

**Issue by yongjer** [flet-dev/flet#2305]
**Description**

tryna build an apk file

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)
```

**Describe the results you received:**

Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...Error on line 3, column 3 of pubspec.yaml: A package may not list itself as a dependency.
  ╷
3 │   flet: ^0.18.0
  │   ^^^^
  ╵

Error building Flet app - see the log of failed command above.

**Flet version (`pip show flet`)**:

```
Version: 0.18.0
```

**Operating system**:

macos 14.2.1

**Comment by FeodorFitsner** [comment]
What command do you run to get that error?

**Comment by taaaf11** [comment]
What's the output of `flet build apk -vv` ?

**Comment by taaaf11** [comment]
@yongjer You should not use the package name as your project name. May you configured the project name to be `flet`?

This may help [A package may not list itself as a dependency](https://stackoverflow.com/questions/71871096/pub-get-failed-a-package-may-not-list-itself-as-a-dependency)

**Comment by FeodorFitsner** [comment]
So, project name is, by default, is taken from the name of directory where Flet app is stored, e.g. having the app in `~/projects/something/flet` could cause this error.

Solution: rename `flet` to something else.

You can also repro the error by calling `flet build {platform} --project flet` command.

We will do a check for this specific case as it might be annoying.
