### ISSUE TITLE
'NoneType' object has no attribute 'send_commands_async'

### ISSUE THREAD

**Issue by liuzhuoling2011** [flet-dev/flet#2310]
**Description**
I have been using flet-fastapi (Version: 0.18.0) for a long time, and this issue has always existed, which greatly affects the user experience. When the flet page is open for a long time (a few hours later), the page will freeze and become unresponsive. The backend service throws an error ('NoneType' object has no attribute 'send_commands_async'), and even refreshing the page does not work. I can only switch to another browser to open it normally.

**Sentry Log:**

![flet error](https://github.com/flet-dev/flet/assets/8407297/76606070-0074-461c-96de-5fe5b8f784b1)

**Describe the results you received:**
the page will freeze and become unresponsive. The backend service throws an error ('NoneType' object has no attribute 'send_commands_async')

**Additional information you deem important (e.g. issue happens only occasionally):** 
My office has several different outgoing IP addresses. Perhaps the IP address will change when accessing the Flet page. I don't know if this will have any impact.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.18.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /opt/anaconda3/envs/3.11/lib/python3.11/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: flet-fastapi
```

**Operating system**: Linux

**Additional environment details:** Python 3.11

**Comment by liuzhuoling2011** [comment]
Hi @FeodorFitsner , need your kind help!

**Comment by FeodorFitsner** [comment]
Sorry for the late reply!

The problem could be that the session is already destroyed on the server. Default Flet session timeout is 3600 seconds (1 hour) and you can change that with `session_timeout_seconds` parameter to `flet_fastapi.app()` call: https://flet.dev/docs/guides/python/deploying-web-app/running-flet-with-fastapi

**Comment by liuzhuoling2011** [comment]
I'll try, Thanks~

**Comment by liuzhuoling2011** [comment]
It Works, Thanks~

**Comment by liuzhuoling2011** [comment]
Hi I've set `session_timeout_seconds=604800`, and the problem appears again, below is the log:

DEBUG:root:raw response from server:[]
WARNING:flet_core:Page is disconnected: mHyVEbaLKWpwxPsN
WARNING:flet_core:Page is disconnected: mHyVEbaLKWpwxPsN
