### ISSUE TITLE
`flet build` gives "OSError: [WinError 193] %1 is not a valid Win32 application" for some users

### ISSUE THREAD

**Issue by FreemanTitus** [flet-dev/flet#2318]
**Description**

**Code example to reproduce the issue:**

```python
from flet import *


def main(page: Page):
    page.window_width = 428

    search_bar = SearchBar(
        view_elevation=2,
        view_bgcolor='gray',
        bar_overlay_color='white',
        bar_hint_text='Search...',

        bar_leading=IconButton(icon='search')
    )
    page.add(
       Column([
           search_bar
       ])
    )


app(main)

```

**Describe the results you received:**

**Describe the results you expected:**
Expect my code to be built to an APK file after going through the process described in the documentation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
Version: 0.18.0

```
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HomePC\AppData\Roaming\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\HomePC\AppData\Roaming\Python\Python312\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\Users\HomePC\AppData\Roaming\Python\Python312\site-packages\flet\cli\commands\build.py", line 515, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "C:\Users\HomePC\AppData\Roaming\Python\Python312\site-packages\flet\cli\commands\build.py", line 701, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Operating system**:
Windows 11

**Additional environment details:**

**Comment by corval** [comment]
which one IDE/Compiler are you using?

**Comment by jose-matos-9281** [comment]
I have the same problem, I'm using VS code

**Comment by NooRMaseR** [comment]
i have this error:
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK                                                                            
Generating app icons...Traceback (most recent call last):                                                                 
File "<frozen runpy>", line 198, in _run_module_as_main                                                                 
File "<frozen runpy>", line 88, in _run_code                                                                            
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>                                                                                                                         File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\cli.py", line 83, in main                                                                                                                         args.handler(args)                                                                                                    
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 515, in handle icons_result = self.run(                                                                                                               
                       ^^^^^^^^^                                                                                              
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 701, in run  r = subprocess.run(                                                                                                         
^^^^^^^^^^^^^^^                                                                                                   
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run                 
with Popen(*popenargs, **kwargs) as process:                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__           self._execute_child(args, executable, preexec_fn, close_fds,                                                          
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child     
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          
OSError: [WinError 193] %1 is not a valid Win32 application 


i'm using windows 10, can someone please help me with that issue

**Comment by taaaf11** [comment]
Try reactivating virtual environment, and then doing `flet build` things.

**Comment by frowNYfaceUnknown** [comment]
I encoutnered the same issue. This is caused by how the flutter and dart SDK are named. I fixed it by renaming the `dart` and `flutter` batch file in the `bin` folder in flutter sdk to something else.

Navigate to the diretory where flutter is downloaded, for me it was `D:\flutter`
Then, navigate into the bin folder where you'll find two batch files, `dart.bat` and `flutter.bat` along with `dart.file` and `flutter.file`. Rename these two `.file` into something else, say `dart_file` and `flutter_file` and the error should be resolved.

**Comment by NooRMaseR** [comment]
> I encoutnered the same issue. This is caused by how the flutter and dart SDK are named. I fixed it by renaming the `dart` and `flutter` batch file in the `bin` folder in flutter sdk to something else.
> 
> Navigate to the directory where flutter is downloaded, for me it was `D:\flutter`
> Then, navigate into the bin folder where you'll find two batch files, `dart.bat` and `flutter.bat` along with `dart.file` and `flutter.file`. Rename these two `.file` into something else, say `dart_file` and `flutter_file` and the error should be resolved.

Thank you so so so much, the problem has been solved successfully 🎉🎉

**Comment by FeodorFitsner** [comment]
I think Python 3.12 in the issue title is misleading. It looks like the issues is (a) related to the usage of 32-bit version of Python on 64-bit Windows and (b) the way `shutil.which` works.

@FreemanTitus, @jose-matos-9281, @NooRMaseR, @frowNYfaceUnknown could you guys run the following command and let me know the results:

```
python -c "import sys; print(sys. maxsize > 2**32)"
```

> The command will return `True` if Python is running in 64-bit and `False` if it's running in 32-bit.

Also, did the solution offered by @frowNYfaceUnknown helped?

**Comment by frowNYfaceUnknown** [comment]
@FeodorFitsner Hello, for the command you provided at least for my system the output is `True`.

**Comment by NooRMaseR** [comment]
> I think Python 3.12 in the issue title is misleading. It looks like the issues is (a) related to the usage of 32-bit version of Python on 64-bit Windows and (b) the way `shutil.which` works.
> 
> @FreemanTitus, @jose-matos-9281, @NooRMaseR, @frowNYfaceUnknown could you guys run the following command and let me know the results:
> 
> ```
> python -c "import sys; print(sys. maxsize > 2**32)"
> ```
> 
> > The command will return `True` if Python is running in 64-bit and `False` if it's running in 32-bit.
> 
> Also, did the solution offered by @frowNYfaceUnknown helped?

I get ```True``` and yes @frowNYfaceUnknown his solution fixed the problem

**Comment by jose-matos-9281** [comment]
> I think Python 3.12 in the issue title is misleading. It looks like the issues is (a) related to the usage of 32-bit version of Python on 64-bit Windows and (b) the way `shutil.which` works.
> 
> @FreemanTitus, @jose-matos-9281, @NooRMaseR, @frowNYfaceUnknown could you guys run the following command and let me know the results:
> 
> ```
> python -c "import sys; print(sys. maxsize > 2**32)"
> ```
> 
> > The command will return `True` if Python is running in 64-bit and `False` if it's running in 32-bit.
> 
> Also, did the solution offered by @frowNYfaceUnknown helped?

I change my version of python to 3.11 and then work

**Comment by frowNYfaceUnknown** [comment]
> OK, thanks!
> 
> I'm wondering why do you guys have `flutter.file` and `dart.file` in `bin` folder? I've downloaded the latest stable release from [here](https://docs.flutter.dev/get-started/install/windows/mobile?tab=download) and it doesn't have `*.file` in it. Was it an upgrade from older versions of Flutter maybe?

Nope, I downloaded it from the same link that you've provided. Here's my output for `flutter --version` if it helps.

```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (3 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by FeodorFitsner** [comment]
@frowNYfaceUnknown but you said "Rename these two .file into something else" - did those files appear *after* you downloaded/unpacked the package?

**Comment by taaaf11** [comment]
@FeodorFitsner I think, like you said, the main culprit is the upgrade...

**Comment by taaaf11** [comment]
@frowNYfaceUnknown Are `*.file` appearing in the `flutter/bin` directory?

**Comment by FeodorFitsner** [comment]
OK, another challenge :) Whoever has `flutter.file` files in Flutter `bin` folder can you run this command please:

```
python -c "import shutil; print(shutil.which('flutter'))"
```

**Comment by FeodorFitsner** [comment]
also, do you have `.FILE` extension in `echo %PATHEXT%` results?

**Comment by novetto** [comment]
I have no issues compiling with `flet build apk` command.

Settings:
```
Python 3.12.1
Windows 10
flet 0.18.0
```

**Comment by Mr-KAM** [comment]
Hi @FeodorFitsner ! See my comment here  [https://github.com/flet-dev/flet/issues/2498#issuecomment-1955779537](https://github.com/flet-dev/flet/issues/2498#issuecomment-1955779537)

**Comment by maykelsantos** [comment]
> I encoutnered the same issue. This is caused by how the flutter and dart SDK are named. I fixed it by renaming the `dart` and `flutter` batch file in the `bin` folder in flutter sdk to something else.
> 
> Navigate to the directory where flutter is downloaded, for me it was `D:\flutter` Then, navigate into the bin folder where you'll find two batch files, `dart.bat` and `flutter.bat` along with `dart.file` and `flutter.file`. Rename these two `.file` into something else, say `dart_file` and `flutter_file` and the error should be resolved.

TOOOOP, THANKS

**Comment by julian-irwin-tfs** [comment]
Hello, I am reporting that I just ran into this issue today with Python 3.12 on Windows 11, Flet 0.23.2. Renaming the dart and flutter files fixed the problem.

**Comment by TufayelLUS** [comment]
> I encoutnered the same issue. This is caused by how the flutter and dart SDK are named. I fixed it by renaming the `dart` and `flutter` batch file in the `bin` folder in flutter sdk to something else.
> 
> Navigate to the directory where flutter is downloaded, for me it was `D:\flutter` Then, navigate into the bin folder where you'll find two batch files, `dart.bat` and `flutter.bat` along with `dart.file` and `flutter.file`. Rename these two `.file` into something else, say `dart_file` and `flutter_file` and the error should be resolved.

Thanks, man! I was looking for a solution everywhere and tried many things. Finally saw your solution and this fixed it. Kudos to you.

**Comment by Xiang990293** [comment]
> I encoutnered the same issue. This is caused by how the flutter and dart SDK are named. I fixed it by renaming the `dart` and `flutter` batch file in the `bin` folder in flutter sdk to something else.
> 
> Navigate to the directory where flutter is downloaded, for me it was `D:\flutter` Then, navigate into the bin folder where you'll find two batch files, `dart.bat` and `flutter.bat` along with `dart.file` and `flutter.file`. Rename these two `.file` into something else, say `dart_file` and `flutter_file` and the error should be resolved.

Thanks got, I spent 3 hour for this problem, and just rename the files, well, thanks @frowNYfaceUnknown alot!
