### ISSUE TITLE
Error setting flet up

### ISSUE THREAD

**Issue by techemmy** [flet-dev/flet#232]
When I tried installing PDM, I got this error.
<img width="813" alt="Screenshot 2022-08-26 at 04 12 46" src="https://user-images.githubusercontent.com/43725109/186810139-bffb7ba8-7f0a-4a99-b032-5c436cfd2304.png">

Should I ignore it?

**Comment by techemmy** [comment]
Also, is the pdm.lock file meant to get modified on running pdm install? 

Example:
<img width="1077" alt="Screenshot 2022-08-26 at 04 27 03" src="https://user-images.githubusercontent.com/43725109/186811293-9035c0a0-5967-48e4-a497-fca4d1e271f4.png">

**Comment by FeodorFitsner** [comment]
See, it offers to force the link overwrite. Looks like you have some brew package installed that depends on Python 3.10. You can overwrite or ignore. I'm not sure what `2to3` is for though.

Not sure about `pdm.lock` - I'm a new to PDM too. Have your tried asking on their Discord?

**Comment by techemmy** [comment]
No, I forgot about the discord. I'll check it out now.

**Comment by FeodorFitsner** [comment]
I'm closing this issue for now. Feel free to start a new, more specific issue.
