### ISSUE TITLE
Gallery Drawing Tool polygon lines saturation

### ISSUE THREAD

**Issue by corval** [flet-dev/flet#2321]
**-Problema de renderizado.**
1.-En galería el ejemplo de Drawing Tool, después de seleccionar diferentes colores y tener varios garabatos en la pantalla, al dejar presionado sobre el lienzo, empieza a renderizar lineas del color seleccionado formando polígonos circulares y tiene latencia en ese momento al renderizar mas garabatos en otra parte del lienzo. Habrá que estudiar cómo utiliza la memoria del equipo para recordar los trazos, ya que se vé y se siente fluído, pero una vez que se tiene un lienzo saturado, empieza a pasmarse unicamente en la app.

**-Problema de manejo de estado de la actividad**
1.-Al cambiar de activity o minimizar, no vuelve a mostrar la actividad donde se dejó y muestra una pantalla en blanco. quizá tenga que ver con el manejo de estados de las actividades o no libera memoria de las funciones que sostenía como el dibujar sobre lienzo.

![Screenshot_20240105-121637](https://github.com/flet-dev/flet/assets/9479398/f187cf3d-00db-446e-a328-6237e957027e)

**Comment by corval** [comment]
Olvidé comantar que la apk corre en un Android 12, Motorola Moto g6s

**Comment by FeodorFitsner** [comment]
Let's switch to English please.

Could you please elaborate what you mean by second "Activity" issue?

**Comment by FeodorFitsner** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/2360

**Comment by corval** [comment]
I recommend that you learn Spanish, my friend. Tanks
