### ISSUE TITLE
Add `LineChartData.prevent_curve_over_shooting` and `LineChartData.prevent_curve_over_shooting_threshold` props

### ISSUE THREAD

**Issue by indigo360** [flet-dev/flet#2326]
When drawing line charts using flets implementation of fl_charts and using curves the Y axis is massively overshooting

<img width="958" alt="Screenshot 2024-01-07 at 11 10 44" src="https://github.com/flet-dev/flet/assets/33873235/6f02c1b6-8ebd-4ddf-87f5-bc3abce56dd9">

This appears to have already been resolved in fl_chart chart, see https://github.com/imaNNeo/fl_chart/issues/25

**Comment by FeodorFitsner** [comment]
We need to expose `preventCurveOverShooting` property to control that behaviour.

**Comment by ndonkoHenri** [comment]
Can you share some test code, @indigo360 ?
