### ISSUE TITLE
Offline android apk build?

### ISSUE THREAD

**Issue by taaaf11** [flet-dev/flet#2328]
Is there a way to do `flet build apk` completely offline?

**Comment by FeodorFitsner** [comment]
It should be completely offline. Could you please elaborate what you mean?

**Comment by taaaf11** [comment]
I mean that the command should run successfully even when Internet is not available.

Even after adding template using option `--template` of `flet` command, it fails somewhere when connection is not available.

**Comment by FeodorFitsner** [comment]
Oh, is that even possible in today's world? `flet build` has so many moving parts and all of them "want" to get into internet, like Flutter downloading dependencies, then Flutter dependencies downloading their dependencies, then `pip install`, etc.

We can keep that issue opened, but honestly I don't think it could be easily implemented 🥹

**Comment by taaaf11** [comment]
Okay, I got it.

**Comment by ejamshidiasl** [comment]
i need offline mode too. and it is possible in todays world! jet compose, react native and even flutter can do this. why you say flet cannot?
