### ISSUE TITLE
How to force refresh Image holder?

### ISSUE THREAD

**Issue by windmaple** [flet-dev/flet#233]
So I have an Image holder with src pointed to a local file. Every time I click a button, new image content will be generated dynamically and dumped into that file. But if I just use page.update(), the Image holder does not refresh the content. 

So my question is: how do I force the Image holder to refresh its content?

**Comment by FeodorFitsner** [comment]
You have to update image `src` - add some timestamp there, for example:

```python
img.src = f"/assets/myimage.png?ts={time.time()}"
```
