### ISSUE TITLE
Flet does not quit the script when you are using web browser mode as it does when using app mode

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2331]
windows 10 
google Chrome
Visual Studio Code software

When you close the flet app in app mode (ft.app(target=main)), the script stops immediately. But on web browser (ft.app(target=main, view=ft.AppView.WEB_BROWSER)), this doesn´t occur...

**Comment by wschume** [comment]
In web browser mode, the script is more like a server. Hence, you can "reconnect" to the server at any given time. While an app, is more like an application, which terminates after being used. IMHO, this is the desired behavior.
