### ISSUE TITLE
time_picker By default, direct value will report an error, please modify the code I have changed. Come in for a reference

### ISSUE THREAD

**Issue by yst-one** [flet-dev/flet#2333]
![image](https://github.com/flet-dev/flet/assets/134467913/58d4dbcb-3f60-40c7-8228-a9ef7011f044)

**Comment by ndonkoHenri** [comment]
Can you make a PR with your suggestions? And possibly explain why the code should be modified.

**Comment by yst-one** [comment]
刚打开 程序 ，，直接对 time_picker 取值 对报错啊！你自己去试试！！

**Comment by yst-one** [comment]
value_string 会对空值分割报错，大哥

**Comment by ndonkoHenri** [comment]
Can you share some code that I can run to test the issue? (I dont seem to understand)

**Comment by yst-one** [comment]
如果不修改这一句之前必须报错
![image](https://github.com/flet-dev/flet/assets/134467913/eb5f2f2f-5b6e-4f97-a982-dbd60ac6095c)

**Comment by yst-one** [comment]
time_picker 控件如果不在 窗口中设置，就会报错不能对NoneType split

**Comment by FeodorFitsner** [comment]
Please use English.
