### ISSUE TITLE
Performance problem while testing responsiveness on web browser

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2336]
windows 10
Chrome
VS Code
flutter.js:362 Exception while loading service worker: Error: prepareServiceWorker took more than 4000ms to resolve. Moving on.
    at flutter.js:48:11

**Comment by FeodorFitsner** [comment]
Could you give more info please?

**Comment by jvalle63** [comment]
I think this was a network problem. Sorry...
