### ISSUE TITLE
Allow datatable row to wrap text demanded by ft.Text

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2338]
windows 10

ft.DataCell(ft.Text(x['Item'],width=170)),

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------

The GitHub issue tracker is for bug reports and feature requests.
General support can be found at the following locations:

- Flet discussions - https://github.com/flet-dev/flet/discussions
- Flet Discord server - https://discord.gg/dzWXP8SHG8
- Post a question on StackOverflow, using "flet" tag
-->

**Please Describe The Problem To Be Solved**

(Replace This Text: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

**(Optional): Suggest A Solution**

(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation, e.g. Flutter widget solving the problem.
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by FeodorFitsner** [comment]
Could you be more specific please?

**Comment by jvalle63** [comment]
sometimes the column width is not sufficient to accommodate all the text. So the text has to be indented. Datatable rows/datacell has only two lines to indent the text...

**Comment by ndonkoHenri** [comment]
Open a new issue, using the [new issue-template](https://github.com/flet-dev/flet/issues/new?assignees=&labels=&projects=&template=01_bug_report.yml), and provide all possible informations.
