### ISSUE TITLE
Allow Drpdown texts being formated by ft.Text

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2339]
**Please Describe The Problem To Be Solved**

(Replace This Text: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

**(Optional): Suggest A Solution**

(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation, e.g. Flutter widget solving the problem.
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by FeodorFitsner** [comment]
Could you be more specific please?

**Comment by fsmosca** [comment]
@jvalle63 

The option name text can be styled using the `text_style` parameter.

```python
    dd = ft.Dropdown(
        width=100,
        options=[
            ft.dropdown.Option("Red"),
            ft.dropdown.Option("Green"),
            ft.dropdown.Option("Blue"),
        ],
        text_style=ft.TextStyle(
            weight=ft.FontWeight.W_500,
            color=ft.colors.RED_500
        )
    )
```

The bg of the option box can be modified by wrapping the dropdown in the container.

```python
dd = ft.Container(
        content=dd,
        bgcolor=ft.colors.BLUE_100,
        border_radius=5
    )
```

![image](https://github.com/flet-dev/flet/assets/22366935/80fedf18-6a0a-4cb1-897c-03f0b3a225fd)


*Complete code*

```python
import flet as ft

def main(page: ft.Page):
    def button_clicked(e):
        t.value = f"Dropdown value is:  {dd.content.value}"
        page.update()

    t = ft.Text()
    b = ft.ElevatedButton(text="Submit", on_click=button_clicked)
    dd = ft.Dropdown(
        width=100,
        options=[
            ft.dropdown.Option("Red"),
            ft.dropdown.Option("Green"),
            ft.dropdown.Option("Blue"),
        ],
        text_style=ft.TextStyle(
            weight=ft.FontWeight.W_500,
            color=ft.colors.RED_500
        )
    )

    dd = ft.Container(
        content=dd,
        bgcolor=ft.colors.BLUE_100,
        border_radius=5
    )
    
    page.add(dd, b, t)

ft.app(target=main)
```
Ref: https://flet.dev/docs/controls/dropdown/#examples

**Comment by jvalle63** [comment]
thank you!
