### ISSUE TITLE
Add OS check to `flet build` command to avoid incompatible runs

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2342]
Allow certain `flet build` commands on supported platforms only, according to [build matrix](https://flet.dev/docs/guides/python/packaging-app-for-distribution#build-platform-matrix).

Original issue: https://github.com/flet-dev/flet/issues/2340

**Comment by taaaf11** [comment]
I have added the necessary checks in my fork. Ready to send PR
