### ISSUE TITLE
`flet build` to support signing `.apk` with `key.properties`

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2346]
### Discussed in https://github.com/flet-dev/flet/discussions/2334

To-do items:

* [x] Modify `flet build` bootstrap project template to read signing info from `key.properties`.
* [x] Handle `key.properties` in the root of Flet app project while running `flet build`.
* [ ] Docs

**Comment by cheny09** [comment]
Hello, how to use key.properties in Windows?
I have a mykey.keystore but in the manuals I see they only talk about mykey.jks, and I can't update my app in google play

**Comment by yucel685** [comment]
Biraz daha detaylı bir anlatım var mı acaba?

**Comment by FeodorFitsner** [comment]
Supported in [Flet pre-release](https://flet.dev/blog/flet-new-packaging-pre-release#signing-android-bundles).
