### ISSUE TITLE
`flet build` should raise an error when trying to package an app with native modules for iOS or Android

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2356]
Related case: https://github.com/flet-dev/flet/issues/2332#issuecomment-1882920540

**Comment by taaaf11** [comment]
@FeodorFitsner I have a question, not related to the issue. Can we include stackoverflow code here in this repository?

**Comment by FeodorFitsner** [comment]
What do you mean?

**Comment by taaaf11** [comment]
I mean, that can we use the code from stackoverflow questions and answers in the commits to this repo?

**Comment by FeodorFitsner** [comment]
Sure, we can: https://stackoverflow.com/help/licensing provided attribution to the original source/author is kept, like a link to a SO article should work I guess.

**Comment by taaaf11** [comment]
Okay then, thank you

**Comment by taaaf11** [comment]
And @FeodorFitsner , please provide me an insight of how do you provide warnings to the user in the `flet` cli?

**Comment by FeodorFitsner** [comment]
For example?

**Comment by taaaf11** [comment]
Like, if we wanted to provide warning to the user about the C extension modules...

**Comment by taaaf11** [comment]
And can we use python's built in `warnings.warn` function?

**Comment by FeodorFitsner** [comment]
Sure, we can. Here is an example: https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-core/src/flet_core/text.py#L275-L279

**Comment by taaaf11** [comment]
Thank you 😊

**Comment by taaaf11** [comment]
@FeodorFitsner I have added the necessary functions to separate file `util_fn.py` in `commands` directory. Please tell me if we raise an error and exit or give warning to the user.
