### ISSUE TITLE
Provide standard locations to store app permanent and temp data

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2357]
To-do items:
* [ ] Pre-create directories and expose their locations via environment or global variables
* [ ] Document "runtime" app structure as [here](https://github.com/flet-dev/flet/issues/2189#issuecomment-1839826040) and standard locations user can use
* [ ] Provide CRUD example with SQLite as [here](https://github.com/flet-dev/flet/issues/2189)

Related issues:
https://github.com/flet-dev/flet/issues/2189
https://github.com/flet-dev/flet/issues/2289
https://github.com/flet-dev/flet/discussions/2324#discussioncomment-8060444

**Comment by tsiens** [comment]
Can't I read data from the /sdcard now

**Comment by JuliusWiedemann** [comment]
Hey, are there any updates on this issue? 
I need this feature for a new app I want to develop :) 

Any ideas where I can find the standard locations for each os? Can I just access the device user directory from my app with the default open() method in python? (Especially on IOS and Android)
