### ISSUE TITLE
Support for playing audio

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#237]
https://pub.dev/packages/audioplayers
https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/example/lib/tabs/sources.dart
https://github.com/mdn/webaudio-examples/blob/main

### Discussed in https://github.com/flet-dev/flet/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **pbk0** August 26, 2022</sup>
Can flutter audioplayers package be supported by this project.</div>

**Comment by danielgafni** [comment]
+1 would really like to see this!

**Comment by FeodorFitsner** [comment]
It's been implemented: https://flet.dev/docs/controls/audio
