### ISSUE TITLE
Permissions handler for iOS and Android 

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2374]
https://stackoverflow.com/questions/68152221/how-to-request-allow-management-of-all-files-permission-in-flutter-android-11-r

**Comment by radiocortello** [comment]
I've developed an app for Android (thanks to _flet build_) that operates smoothly. This app creates a PDF file that is saved in the allocated memory of the application itself. Is there any way to allow users to download this file directly from the app or grant permissions to save it to a shared location on the device? I appreciate your help.
