### ISSUE TITLE
Debugging 'flet build' generated Windows and Android executables can't be debuged using print() type messaging

### ISSUE THREAD

**Issue by mottibz** [flet-dev/flet#2375]
Following communication with @TheEthicalBoy and @Feodor, I am filing this issue:

-  I developed a Flet app to control my smart home controller (ESP32 based). All works fine in developer mode (flet main.py). For tracing the execution, I am using print() to display status messages on the terminal.
-  Problems start when I generate executables for Windows and Android.
-  When I generate the Windows executable and run it, print() messages are lost (not seen) and I can’t debug the app.
-  @TheEthicalBoy suggested that I re-route stdout to a log file. I did that and it worked in developer mode but did not work when run as a Windows executable. No log file is being generated.
-  I then tried another approach in which I developed a remote terminal (the app listens on a predefined TCP socket and prints all received data to the terminal) and added code in the app to send all print() messages to the remote terminal for display (to that TCP socket). In developer mode (flet main.py) all works great. The Flet app runs and I see the print() messages on the remote PC terminal. However, when I create the Windows executable and run it, nothing works! No messages are received by the remote terminal.
-  I guess that something is wrong in either what I am doing or the executable build process somehow prevents print() messages to be seen and also prevents socket programming out of the executable.

The code I use for the socket communication on the app side is:

`# Code to handle sending print() messages over a socket to the remote terminal

terminal_server_ip = '172.16.254.133'
terminal_server_port = 12345
send_msg_via_socket = True
socket_initialized = False
client_socket = None

import socket

def showStatusMsg(msg):
    global send_msg_via_socket, socket_initialized, client_socket, terminal_server_ip, terminal_server_port
    if send_msg_via_socket == False:
        print(msg)
        return
    
    # Send via socket
    if socket_initialized == False:
        # Create a socket object
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

        # Connect to the server
        client_socket.connect((terminal_server_ip, terminal_server_port))
        print(f"Connected to server at {terminal_server_ip}:{terminal_server_port}")

        socket_initialized = True

    client_socket.send(msg.encode())`

Using:
Python 3.11.6
Flet 0.18.0
Flutter 3.16.5, Dart 3.2.3, DevTools 2.28.4
Windows 11

**Comment by mottibz** [comment]
The additional Python packaes that I am using (pip install ...) are:
1.  paho-mqtt
2.  sseclient
Both are Python code and as far as I understand, are OK to use.

I am also importing the Requests HTTP library, Json library

And, as I wrote, all works fine in developer mode and the issue happens only in executables generated by 'flet build'

**Comment by FeodorFitsner** [comment]
Try building app with the latest Flet 0.19.0. It has error reporting now if the app could not be started.
