### ISSUE TITLE
Designing a framework to support application development? 

### ISSUE THREAD

**Issue by jet10000** [flet-dev/flet#238]
Have you considered designing a framework to support application development? 

Like nylo framework

https://github.com/nylo-core/framework

**Comment by FeodorFitsner** [comment]
But Flet is already a framework for application development: desktop, web and (soon) mobile, no? I understand Nylo's goal is to reduce boilerplate code while developing in Flutter/Dart. Flet is all about removing boilerplate and simplifying the development. Built-in routing? Check. Built-in web server? Check. Theming? Check.

Or what are your concerns? :)

**Comment by jet10000** [comment]
I feel that the current flet is more like svelte, and the framework I am talking about is more like sveltekit.

https://svelte.dev/

https://kit.svelte.dev/

**Comment by FeodorFitsner** [comment]
Ah, well, I see! Maybe in the future it's going to be a framework on top of Flet saying "The fastest way to build Flet apps" :)
I believe Flet is a high-level framework already combining both "framework" and "kit". However, I think it could be some layer on top of it built by community and including components, frameworks made of Flet controls, like [this](https://github.com/flet-dev/examples/tree/main/python/community/responsive_menu_layout), [this](https://github.com/flet-dev/examples/tree/main/python/community/toasts) or [this](https://github.com/StanMathers/flet-validators).

So, is there any specific feature you are missing right now or would like to see implemented?
