### ISSUE TITLE
`FilePickerResultEvent`'s `path` is `None` when using web browser view...

### ISSUE THREAD

**Issue by taaaf11** [flet-dev/flet#2380]
**Description**

`FilePickerResultEvent`'s `path` is `None` when using `WEB_BROWSER` view. This also happens in `flet publish main.py` and in `flet build web` commands.

**Describe the results you received:**
Received results: `FilePickerResultEvent` `path` is `None`.

**Describe the results you expected:**
Expected: `FilePickerResultEvent` `path` should be a path to the selected file...

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.18.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\Altaaf\PycharmProjects\Insta Following not followers\venv\Lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:
OS: Windows 10 22H2

**Additional environment details:**
Using web view of the app and `flet build web` and `flet publish main.py`.

**Comment by AngRotanak** [comment]
I hosting my app with Cloud run and not upload the file to server 

`import json
import os
import shutil

import flet_fastapi
from typing import Dict

import flet
from flet import (
    Column,
    ElevatedButton,
    FilePicker,
    FilePickerResultEvent,
    FilePickerUploadEvent,
    FilePickerUploadFile,
    Page,
    ProgressRing,
    Ref,
    Row,
    Text,
    icons,
)

mnt_dir = os.environ.get("MNT_DIR", "/mnt/nfs/filestore")
async def main(page: Page):
    prog_bars: Dict[str, ProgressRing] = {}
    files = Ref[Column]()
    upload_button = Ref[ElevatedButton]()

    config_data = {
        "max_add_count": 'max_add_count',
        "add_index": 'add_index',
        "adding_status": 'adding_status',
        "scrape_group": 'scrape_group',
        "add_group": 'add_group'
    }

    with open(f"{mnt_dir}/config.json", "w") as jsonfile:
        json.dump(config_data, jsonfile, indent=4)
        jsonfile.close()

    async def file_picker_result(e: FilePickerResultEvent):
        upload_button.current.disabled = True if e.files is None else False
        prog_bars.clear()
        files.current.controls.clear()
        if e.files is not None:
            for f in e.files:
                prog = ProgressRing(value=0, bgcolor="#eeeeee", width=20, height=20)
                prog_bars[f.name] = prog
                files.current.controls.append(Row([prog, Text(f.name)]))
        await page.update_async()

    async def on_upload_progress(e: FilePickerUploadEvent):
        prog_bars[e.file_name].value = e.progress
        await prog_bars[e.file_name].update_async()

    file_picker = FilePicker(on_result=file_picker_result, on_upload=on_upload_progress)

    async def pick_files(e):
        await file_picker.pick_files_async(allow_multiple=True)

    async def upload_files(e):
        uf = []
        if file_picker.result is not None and file_picker.result.files is not None:
            for f in file_picker.result.files:
                uf.append(
                    FilePickerUploadFile(
                        f.name,
                        upload_url=await page.get_upload_url_async(f.name, 600),
                    )
                )
            await file_picker.upload_async(uf)

    # hide dialog in a overlay
    page.overlay.append(file_picker)

    await page.add_async(
        ElevatedButton(
            "Select files...",
            icon=icons.FOLDER_OPEN,
            on_click=pick_files,
        ),
        Column(ref=files),
        ElevatedButton(
            "Upload",
            ref=upload_button,
            icon=icons.UPLOAD,
            on_click=upload_files,
            disabled=True,
        ),
    )

app = flet_fastapi.app(main, upload_dir=f"uploads")
# flet.app(target=main, upload_dir="uploads", view=flet.WEB_BROWSER)`




# Error 👍 


2024-01-12 13:52:58.080 ICT
Exception: Specify secret_key parameter or set FLET_SECRET_KEY environment variable to enable uploads.
[Open in Logs Explorer](https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22khmer-cloudbot%22%0Aresource.labels.location%20%3D%20%22us-central1%22%0A%20severity%3E%3DDEFAULT;timeRange=2024-01-12T06:52:58.080475Z%2F2024-01-12T06:52:58.080475Z--PT1H;pinnedLogId=2024-01-12T06:52:58.080475Z%2F65a0e1ca00013a5be2a672be?project=khmer-autotools)
{
insertId: "65a0e1ca00013a5be2a672be"
labels: {1}
logName: "projects/khmer-autotools/logs/run.googleapis.com%2Fstderr"
receiveTimestamp: "2024-01-12T06:52:58.329130140Z"
resource: {2}
textPayload: "Exception: Specify secret_key parameter or set FLET_SECRET_KEY environment variable to enable uploads."
timestamp: "2024-01-12T06:52:58.080475Z"
}

**Comment by taaaf11** [comment]
@AngRotanak I think your issue is not related to my issue. I cannot help on your issue. @FeodorFitsner may better guide you...

**Comment by taaaf11** [comment]
@ndonkoHenri kindly review this issue please...

**Comment by taaaf11** [comment]
@FeodorFitsner Kindly review this issue please

**Comment by MaxXilon** [comment]
Web browsers have a security feature that prevents them from directly accessing files on your computer. This is why the file path of the file selected by the FilePicker widget in Flet returns None when you select a file in a web application.

To fix this in a web application, you can use the FilePicker's upload property to first upload the file to an accessible location. Then, you can retrieve the file from that location and use it as required.

Note: FilePicker will be able to return the file path if Flet is run as a desktop app or mobile app.

**Comment by taaaf11** [comment]
Okay @MaxXilon
