### ISSUE TITLE
Not building when cryptography module is added and not loading .so files

### ISSUE THREAD

**Issue by thiwtzsch** [flet-dev/flet#2386]
When I add the cryptography module gradle returns libpythonbundle.so is not recognised as a valid object file and its ignoring .so files when building the apk

**Comment by FeodorFitsner** [comment]
`cryptography` package is not a pure Python package, i.e. has parts written in C, so you need to follow this guide (for now) to add it to your Android project: https://pub.dev/packages/serious_python#android

**Comment by thiwtzsch** [comment]
Thank you. @FeodorFitsner
