### ISSUE TITLE
Regression: ElevatedButton text mandatory

### ISSUE THREAD

**Issue by mikaelho** [flet-dev/flet#239]
`flet` 0.1.53 made `text` a mandatory argument for `ElevatedButton`. As this was not documented and none of the other buttons were changed, I am assuming that this was an accidental regression.

**Comment by FeodorFitsner** [comment]
Checking that now...

**Comment by FeodorFitsner** [comment]
Bumped to Flet 0.1.54. Could you check it now please? Thanks for the catch!

**Comment by mikaelho** [comment]
Fixed, thanks. 🚀
