### ISSUE TITLE
error while running a file on Replit

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2397]
I am using the following libraries:
import flet as ft
from flet_navigator import VirtualFletNavigator, PageData

Traceback (most recent call last):
  File "/home/runner/atelierdalci/main.py", line 1, in <module>
    import flet as ft
  File "/home/runner/atelierdalci/.pythonlibs/lib/python3.10/site-packages/flet/__init__.py", line 1, in <module>
    from flet.flet import app, app_async
  File "/home/runner/atelierdalci/.pythonlibs/lib/python3.10/site-packages/flet/flet.py", line 5, in <module>
    import flet_js
ModuleNotFoundError: No module named 'flet_js'
Traceback (most recent call last):
  File "/home/runner/atelierdalci/main.py", line 1, in <module>
    import flet as ft
  File "/home/runner/atelierdalci/.pythonlibs/lib/python3.10/site-packages/flet/__init__.py", line 1, in <module>
    from flet.flet import app, app_async
  File "/home/runner/atelierdalci/.pythonlibs/lib/python3.10/site-packages/flet/flet.py", line 5, in <module>
    import flet_js
ModuleNotFoundError: No module named 'flet_js'

**Comment by ndonkoHenri** [comment]
Disable `guess imports` as shown here: https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/replit

**Comment by jvalle63** [comment]
I tried to do this, but I only found this options on .replit:
entrypoint = "main.py"
modules = ["python-3.10:v18-20230807-322e88b"]

hidden = [".pythonlibs"]

[nix]
channel = "stable-23_05"

[unitTest]
language = "python3"

[deployment]
run = ["python3", "main.py"]
deploymentTarget = "cloudrun"

**Comment by jvalle63** [comment]
I put this bellow information in .replit. But the problem remains...
[packager]
language = "python"

[packager.features]
 guessImports = false

**Comment by ndonkoHenri** [comment]
Seems like the structure has been changed: https://ask.replit.com/t/how-to-stop-replit-guessing-packages-in-python-template/59633/8
Can you instead try setting `disableGuessImports = true` ?

**Comment by jvalle63** [comment]
I  included disableGuessImports = true and uninstalled flet-pyodide with pip uninstall. 
The good news is that the error above error disappeared. The bad news is that another error appeared... 
I will put bellow  the error and the test script. Please I need a solution. I made a Kanban system in Flet and now I have to publish it!
 **The error:**
Traceback (most recent call last):
  File "/home/runner/ateliercostura/main.py", line 2, in <module>
    from flet_navigator import VirtualFletNavigator, PageData
  File "/home/runner/ateliercostura/.pythonlibs/lib/python3.10/site-packages/flet_navigator/__init__.py", line 3, in <module>
    from flet import Page, Control, Scale
ImportError: cannot import name 'Page' from 'flet' (unknown location)

**The script**

import flet as ft
from flet_navigator import VirtualFletNavigator, PageData


def home(pg: PageData):
  senha = "Ac9876"
  valor = pg.page.client_storage.get("key")
  myappbar = ft.AppBar(title=ft.Text('Login'), bgcolor='blue')
  pg.set_appbar(myappbar)

  def clicado(e):

    if campo_senha.value != senha:
      campo_senha.error_text = 'Senha Inválida'
      campo_senha.value = ""
      pg.page.client_storage.remove("key")
    else:
      campo_senha.error_text = ""
      pg.page.client_storage.set("key", campo_senha.value)
      pg.navigator.navigate(f'about', pg.page, (senha))
    pg.page.update()

  pg.page.title = ('Atelier Costura')
  pg.page.vertical_alignment = ft.MainAxisAlignment.CENTER
  pg.page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
  t = ft.Text('Digite a Senha',
              font_family='Tahoma',
              color='BLUE_500',
              size=30)
  campo_senha = ft.TextField(value=valor,
                             width=300,
                             label='Senha',
                             hint_text='Senha de 6 dígitos',
                             password=True,
                             can_reveal_password=True,
                             max_length=6,
                             icon=ft.icons.LOCK,
                             autofocus=True)
  botao = ft.IconButton(tooltip="Iniciar",
                        icon=ft.icons.START,
                        icon_color=ft.colors.BLUE_ACCENT_200,
                        icon_size=30,
                        on_click=clicado)
  pg.page.add(t, campo_senha, botao)


def about(pg: PageData):
  myappbar = ft.AppBar(title=ft.Text('About page'), bgcolor='red')
  pg.set_appbar(myappbar)

  cabecalho_about = ft.Text("About page", size=20, weight='bold')
  botao = ft.ElevatedButton()
  parametro = ft.Text(f'seu parâmetro é {pg.arguments}', weight='bold')
  botao = ft.ElevatedButton(
      'About page',
      bgcolor='red',
      color='white',
      on_click=lambda _: pg.navigator.navigate_homepage(pg.page))

  pg.page.add(cabecalho_about, parametro, botao)
  print(pg.arguments)
  #pg.page.add()


def main(page: ft.Page):
  flet_navigator = VirtualFletNavigator({
      '/': home,
      'about': about
  }, lambda route: print(f'Rota atual: {route}'))
  #page.add()
  flet_navigator.render(page)


ft.app(target=main, view=ft.AppView.WEB_BROWSER)

**Comment by ndonkoHenri** [comment]
What is `flet_navigator`?

**Comment by jvalle63** [comment]
https://github.com/xzripper/flet_navigator

**Comment by jvalle63** [comment]
It´s a very easy way to navigate between flet pages

**Comment by FeodorFitsner** [comment]
Updated Replit guide: https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/replit

**Comment by FeodorFitsner** [comment]
The problem could be in [flet_navigator](https://github.com/xzripper/flet_navigator) - try asking there.

**Comment by jvalle63** [comment]
Flet explanation is no good. You have to uninstall flet-pyodide....

**Comment by jvalle63** [comment]
Now everithing is working fine, including flet navigator

**Comment by FeodorFitsner** [comment]
Thanks for the update. That guide for Replit assumes you are starting from scratch and disabling package guessing right away :)
