### ISSUE TITLE
value of Radio should be any

### ISSUE THREAD

**Issue by anz-ryu** [flet-dev/flet#2415]
**Please Describe The Problem To Be Solved**

I tying to keep some value in Radio, but I saw:

https://github.com/flet-dev/flet/blob/ed672c5de18790a2ad3062f7f128d177890338a7/sdk/python/packages/flet-core/src/flet_core/radio.py#L86

Can I only hold Strings?

I tried other values by other types, like int. It is kept.

**(Optional): Suggest A Solution**

change str to Any.

**Comment by taaaf11** [comment]
It means the value of `value` can be of type `str` or `None`. See [typing.Optional in python docs](https://docs.python.org/3/library/typing.html#typing.Optional)

**Comment by FeodorFitsner** [comment]
Also, you can put practically anything into `.data` property of each Radio and then retrieve it from there once you determined which Radio is selected! ;)
