### ISSUE TITLE
Cannot build app with `supabase` dependency (because of `pydantic`/`pydantic-core`)

### ISSUE THREAD

**Issue by Kacper-OS** [flet-dev/flet#2416]
**Description**
I tried to build apk file from app that uses pyrebase and supabase modules but building app just stops, packaging stage freezes on installing python packages

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)

```

**Describe the results you received:**
![image](https://github.com/flet-dev/flet/assets/120328307/b9e9ff58-d0d3-49d4-9185-14d76d1ccca4)
![image](https://github.com/flet-dev/flet/assets/120328307/00f4da95-887e-4400-b8b3-344e5eecc6cf)
![image](https://github.com/flet-dev/flet/assets/120328307/6af94a39-94bd-4002-b038-471c8cff8f88)

**Describe the results you expected:**
![image](https://github.com/flet-dev/flet/assets/120328307/b35b473e-896e-4ad8-9e9f-8b7431c34d9f)

**Additional information you deem important (e.g. issue happens only occasionally):**
building app for windows are outputting errors but building .exe is successful

**Flet version (`pip show flet`)**:

```
Version: 0.19.0
```

**Operating system**:
Windows 11

**Comment by FeodorFitsner** [comment]
Could you paste the log as a text please?

**Comment by Kacper-OS** [comment]
Flutter bootstrap directory: C:\Users\HP\AppData\Local\Temp\flet_flutter_build_ynjwxcvsug
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying C:\Users\HP\Desktop\testlib\assets\icon.png to C:\Users\HP\AppData\Local\Temp\flet_flutter_build_ynjwxcvsug\images
OK
Generating app icons...Resolving dependencies in C:\Users\HP\AppData\Local\Temp\flet_flutter_build_ynjwxcvsug... (5.7s)
Got dependencies in C:\Users\HP\AppData\Local\Temp\flet_flutter_build_ynjwxcvsug.
Building package executable... (7.6s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...Building package executable... (8.4s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...Building package executable... (4.2s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\HP\AppData\Local\Temp\flet_flutter_build_ynjwxcvsug\app
Copying Python app from C:\Users\HP\Desktop\testlib to C:\Users\HP\AppData\Local\Temp\serious_python_temp1b8455a
Configured mobile platform with sitecustomize.py at C:\Users\HP\AppData\Local\Temp\serious_python_sitecustomizef05194fd\sitecustomize.py
Installing dependencies [flet-embed, supabase] with pip command to C:\Users\HP\AppData\Local\Temp\serious_python_temp1b8455a\__pypackages__
Extracting Python distributive from C:\Users\HP\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\HP\AppData\Local\Temp\hostpython3.11_ed741f4
VERBOSE: C:\Users\HP\AppData\Local\Temp\hostpython3.11_ed741f4\python\python.exe -m pip install --isolated --upgrade --target C:\Users\HP\AppData\Local\Temp\serious_python_temp1b8455a\__pypackages__ flet-embed supabase
VERBOSE: Collecting flet-embed
VERBOSE: Obtaining dependency information for flet-embed from https://files.pythonhosted.org/packages/ad/d1/a6b49f4fae4611d8b083da1f95afd78e38ffb3898290ffc8dcec73324bf6/flet_embed-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_embed-0.19.0-py3-none-any.whl.metadata (1.1 kB)
VERBOSE: Collecting supabase
VERBOSE: Obtaining dependency information for supabase from https://files.pythonhosted.org/packages/64/31/2dffb58f9c6cd87464a46f828dfb93fb68deb71f0cae50315b9318e6c006/supabase-2.3.4-py3-none-any.whl.metadata
VERBOSE: Using cached supabase-2.3.4-py3-none-any.whl.metadata (8.5 kB)
VERBOSE: Collecting flet-runtime==0.19.0 (from flet-embed)
VERBOSE: Obtaining dependency information for flet-runtime==0.19.0 from https://files.pythonhosted.org/packages/dd/19/d0954189bf43dfdf5f9d059f5eb73d3374a13d5d4626a14f24fe35b55b43/flet_runtime-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_runtime-0.19.0-py3-none-any.whl.metadata (1.2 kB)
VERBOSE: Collecting flet-core==0.19.0 (from flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for flet-core==0.19.0 from https://files.pythonhosted.org/packages/cc/cc/520c8a7650b57c615a8be1679c5199a7f57ba59639d76cc7ea0a76bda19f/flet_core-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_core-0.19.0-py3-none-any.whl.metadata (1.1 kB)
VERBOSE: Collecting httpx<0.25.0,>=0.24.1 (from flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for httpx<0.25.0,>=0.24.1 from https://files.pythonhosted.org/packages/ec/91/e41f64f03d2a13aee7e8c819d82ee3aa7cdc484d18c0ae859742597d5aa0/httpx-0.24.1-py3-none-any.whl.metadata
VERBOSE: Using cached httpx-0.24.1-py3-none-any.whl.metadata (7.4 kB)
VERBOSE: Collecting oauthlib<4.0.0,>=3.2.2 (from flet-runtime==0.19.0->flet-embed)
VERBOSE: Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
VERBOSE: Collecting repath<0.10.0,>=0.9.0 (from flet-core==0.19.0->flet-runtime==0.19.0->flet-embed)
VERBOSE: Using cached repath-0.9.0-py3-none-any.whl (4.7 kB)
VERBOSE: Collecting gotrue<3.0,>=1.3 (from supabase)
VERBOSE: Obtaining dependency information for gotrue<3.0,>=1.3 from https://files.pythonhosted.org/packages/bd/9f/3f7fc69b8d1111846f4990b3a063a06c61d6af17a58424b5c4b321972e3e/gotrue-2.1.0-py3-none-any.whl.metadata
VERBOSE: Using cached gotrue-2.1.0-py3-none-any.whl.metadata (5.9 kB)
VERBOSE: Collecting postgrest<0.16.0,>=0.10.8 (from supabase)
VERBOSE: Obtaining dependency information for postgrest<0.16.0,>=0.10.8 from https://files.pythonhosted.org/packages/17/d9/a377da91d54b43d9bd2ea97a29a858bd646f5b2e5ba0521046c95a0ac4e4/postgrest-0.15.0-py3-none-any.whl.metadata
VERBOSE: Using cached postgrest-0.15.0-py3-none-any.whl.metadata (5.1 kB)
VERBOSE: Collecting realtime<2.0.0,>=1.0.0 (from supabase)
VERBOSE: Obtaining dependency information for realtime<2.0.0,>=1.0.0 from https://files.pythonhosted.org/packages/2e/c0/b0be23f55642d0018a5c1e3c5e6aeda11fe5e18e24b5f969636b10fc34a5/realtime-1.0.2-py3-none-any.whl.metadata
VERBOSE: Using cached realtime-1.0.2-py3-none-any.whl.metadata (2.6 kB)
VERBOSE: Collecting storage3<0.8.0,>=0.5.3 (from supabase)
VERBOSE: Obtaining dependency information for storage3<0.8.0,>=0.5.3 from https://files.pythonhosted.org/packages/fd/c9/6add986d87c11eab4e8e1a3db1d5b4778abb7dcb3637a4e0a86b10cba185/storage3-0.7.0-py3-none-any.whl.metadata
VERBOSE: Using cached storage3-0.7.0-py3-none-any.whl.metadata (1.9 kB)
VERBOSE: Collecting supafunc<0.4.0,>=0.3.1 (from supabase)
VERBOSE: Obtaining dependency information for supafunc<0.4.0,>=0.3.1 from https://files.pythonhosted.org/packages/e6/5f/efb275d649845e6fe3a65c08e8c1e424d56dbc14016b89dca83055ec656e/supafunc-0.3.3-py3-none-any.whl.metadata
VERBOSE: Using cached supafunc-0.3.3-py3-none-any.whl.metadata (1.2 kB)
VERBOSE: Collecting pydantic<3,>=1.10 (from gotrue<3.0,>=1.3->supabase)
VERBOSE: Obtaining dependency information for pydantic<3,>=1.10 from https://files.pythonhosted.org/packages/dd/b7/9aea7ee6c01fe3f3c03b8ca3c7797c866df5fecece9d6cb27caa138db2e2/pydantic-2.5.3-py3-none-any.whl.metadata
VERBOSE: Using cached pydantic-2.5.3-py3-none-any.whl.metadata (65 kB)
VERBOSE: Collecting certifi (from httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-2023.11.17-py3-none-any.whl.metadata
VERBOSE: Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
VERBOSE: Collecting httpcore<0.18.0,>=0.15.0 (from httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for httpcore<0.18.0,>=0.15.0 from https://files.pythonhosted.org/packages/94/2c/2bde7ff8dd2064395555220cbf7cba79991172bf5315a07eb3ac7688d9f1/httpcore-0.17.3-py3-none-any.whl.metadata
VERBOSE: Using cached httpcore-0.17.3-py3-none-any.whl.metadata (18 kB)
VERBOSE: Collecting idna (from httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for idna from https://files.pythonhosted.org/packages/c2/e7/a82b05cf63a603df6e68d59ae6a68bf5064484a0718ea5033660af4b54a9/idna-3.6-py3-none-any.whl.metadata
VERBOSE: Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
VERBOSE: Collecting sniffio (from httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
VERBOSE: Collecting deprecation<3.0.0,>=2.1.0 (from postgrest<0.16.0,>=0.10.8->supabase)
VERBOSE: Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
VERBOSE: Collecting strenum<0.5.0,>=0.4.9 (from postgrest<0.16.0,>=0.10.8->supabase)
VERBOSE: Obtaining dependency information for strenum<0.5.0,>=0.4.9 from https://files.pythonhosted.org/packages/81/69/297302c5f5f59c862faa31e6cb9a4cd74721cd1e052b38e464c5b402df8b/StrEnum-0.4.15-py3-none-any.whl.metadata
VERBOSE: Using cached StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
VERBOSE: Collecting python-dateutil<3.0.0,>=2.8.1 (from realtime<2.0.0,>=1.0.0->supabase)
VERBOSE: Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
VERBOSE: Collecting typing-extensions<5.0.0,>=4.2.0 (from realtime<2.0.0,>=1.0.0->supabase)
VERBOSE: Obtaining dependency information for typing-extensions<5.0.0,>=4.2.0 from https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl.metadata
VERBOSE: Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
VERBOSE: Collecting websockets<12.0,>=11.0 (from realtime<2.0.0,>=1.0.0->supabase)
VERBOSE: Using cached websockets-11.0.3-py3-none-any.whl (118 kB)
VERBOSE: Collecting packaging (from deprecation<3.0.0,>=2.1.0->postgrest<0.16.0,>=0.10.8->supabase)
VERBOSE: Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
VERBOSE: Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
VERBOSE: Collecting h11<0.15,>=0.13 (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Using cached h11-0.14.0-py3-none-any.whl (58 kB)
VERBOSE: Collecting anyio<5.0,>=3.0 (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.1->flet-runtime==0.19.0->flet-embed)
VERBOSE: Obtaining dependency information for anyio<5.0,>=3.0 from https://files.pythonhosted.org/packages/bf/cd/d6d9bb1dadf73e7af02d18225cbd2c93f8552e13130484f1c8dcfece292b/anyio-4.2.0-py3-none-any.whl.metadata
VERBOSE: Using cached anyio-4.2.0-py3-none-any.whl.metadata (4.6 kB)
VERBOSE: Collecting annotated-types>=0.4.0 (from pydantic<3,>=1.10->gotrue<3.0,>=1.3->supabase)
VERBOSE: Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl.metadata
VERBOSE: Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
VERBOSE: Collecting pydantic-core==2.14.6 (from pydantic<3,>=1.10->gotrue<3.0,>=1.3->supabase)
VERBOSE: Using cached pydantic_core-2.14.6.tar.gz (360 kB)
VERBOSE: Installing build dependencies: started
VERBOSE: Installing build dependencies: finished with status 'error'

**Comment by FeodorFitsner** [comment]
and what command are you running?

**Comment by Kacper-OS** [comment]
'''flet build apk'''

**Comment by 1Mr-Newton** [comment]
Having the same issue. I think it's related to the pydantic_core installation.

**Comment by Kacper-OS** [comment]
it for sure is related to ```pydantic_core``` but it should show error like "error with installing pydantic_core" not just freeze

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
Well, the issue guys is in `pydantic-core` library (you see it in the original log to this issue) which `pydantic` depends on. `pydantic-core` is "Core validation logic for pydantic written in rust", so it's a native library and has to be compiled for Android/iOS.

**Comment by 1Mr-Newton** [comment]
Thanks for taking a look at it. Will there be a solution soon or any workaround?
There are lots of libraries using Pydantic, so automatically, we can't use them. I tried to use OpenAI (same issue)

**Comment by Kacper-OS** [comment]
now I'm just thinking about how to fix it, I just think I could try compiling rust to C but I have to find out how to do that

**Comment by Kacper-OS** [comment]
I will take look into that

**Comment by Kacper-OS** [comment]
one question, do I have to add rust program to folder or just this:
```py
from pythonforandroid.recipe import PythonRecipe

class PydanticcoreRecipe(PythonRecipe):
    version = '2.16.0'
    url = 'https://files.pythonhosted.org/packages/2f/ae/b230a03d5500bfce92d556b993dd6911ac0463b2468d345fb1b3b05eae79/pydantic_core-{version}.tar.gz'
    call_hostpython_via_targetpython = False
    install_in_hostpython = True


recipe = PydanticcoreRecipe()
```
will work ?

**Comment by FeodorFitsner** [comment]
Sorry, I haven't worked with Kivy recipes yet. Would you mind opening an issue in Kivy for Android repository or ask on their Discord?

**Comment by Kacper-OS** [comment]
OK thanks

**Comment by rodrigocavoli** [comment]
@FeodorFitsner hello everbody, I have the same problem with PyMuPDF.
Packaging Python app...Building package executable... (9.7s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\rodri\AppData\Local\Temp\flet_flutter_build_BqjwmLcuPn\app
Copying Python app from \\laptop-rodrigo\ERP\Nord_Virtual\Musica to C:\Users\rodri\AppData\Local\Temp\serious_python_temp3ac18698
Configured mobile platform with sitecustomize.py at C:\Users\rodri\AppData\Local\Temp\serious_python_sitecustomize74884d8f\sitecustomize.py
Installing dependencies [flet-embed==0.19.0, PyMuPDF] with pip command to C:\Users\rodri\AppData\Local\Temp\serious_python_temp3ac18698\__pypackages__
Extracting Python distributive from C:\Users\rodri\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\rodri\AppData\Local\Temp\hostpython3.11_ad147498
VERBOSE: C:\Users\rodri\AppData\Local\Temp\hostpython3.11_ad147498\python\python.exe -m pip install --isolated --upgrade --target C:\Users\rodri\AppData\Local\Temp\serious_python_temp3ac18698\__pypackages__ flet-embed==0.19.0 PyMuPDF
VERBOSE: Collecting flet-embed==0.19.0
VERBOSE: Obtaining dependency information for flet-embed==0.19.0 from https://files.pythonhosted.org/packages/ad/d1/a6b49f4fae4611d8b083da1f95afd78e38ffb3898290ffc8dcec73324bf6/flet_embed-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_embed-0.19.0-py3-none-any.whl.metadata (1.1 kB)
VERBOSE: Collecting PyMuPDF
VERBOSE: Downloading PyMuPDF-1.23.16.tar.gz (103.0 MB)
VERBOSE: --------------------------------------- 103.0/103.0 MB 2.8 MB/s eta 0:00:00
VERBOSE:
VERBOSE: Installing build dependencies: started
VERBOSE: Installing build dependencies: still running...
VERBOSE: Installing build dependencies: finished with status 'error'

**Comment by FeodorFitsner** [comment]
PyMuPDF is a native package and should be compiled for Android/iOS.

**Comment by Kacper-OS** [comment]
I found p4a recepies documentation https://github.com/kivy/python-for-android/blob/develop/doc/source/recipes.rst
I will read this few times and then create PR for p4a

**Comment by FeodorFitsner** [comment]
https://python-for-android.readthedocs.io/en/latest/recipes/

**Comment by Kacper-OS** [comment]
ok, if I read the documentation correctly this:
```py
from pythonforandroid.recipe import PythonRecipe

class PydanticcoreRecipe(PythonRecipe):
    version = '2.16.0'
    url = 'https://files.pythonhosted.org/packages/2f/ae/b230a03d5500bfce92d556b993dd6911ac0463b2468d345fb1b3b05eae79/pydantic_core-{version}.tar.gz'
    depends = ['typing-extensions']

recipe = PydanticcoreRecipe()
```
should work ( I think )

**Comment by FeodorFitsner** [comment]
As far as I understand `PythonRecipe` is for pure Python modules. `pydantic-core` has native part written in Rust, using `Pyo3` and built with `maturin` 🤪

**Comment by FeodorFitsner** [comment]
Noticed, you created an issue: https://github.com/kivy/python-for-android/issues/2955

**Comment by Kacper-OS** [comment]
I even ask on kivy's discord but no one responded to my question

**Comment by Kacper-OS** [comment]
```py
from pythonforandroid.recipe import CompiledComponentsPythonRecipe

class PydanticcoreRecipe(CompiledComponentsPythonRecipe):
    version = '2.16.0'
    url = 'https://files.pythonhosted.org/packages/2f/ae/b230a03d5500bfce92d556b993dd6911ac0463b2468d345fb1b3b05eae79/pydantic_core-{version}.tar.gz'
    depends = ['typing-extensions']

recipe = PydanticcoreRecipe()
```
OK, CompiledComponentsPythonRecipe class is used for modules like numpy

**Comment by Kacper-OS** [comment]
after a lot of thinking, I think code from last comment should work, maybe in few hours or days I will open PR

**Comment by Kacper-OS** [comment]
yeah, but... ```python``` isn't supporting mobile divices officialy, there is [pep 738](https://pep-previews--3586.org.readthedocs.build/pep-0738/#) thats wants to add ```python```'s support for android as Tier 3 platform, maybe after accepting this pep, developers will add wheels for ```arm```

**Comment by baseplate-admin** [comment]
> maybe after accepting this pep, developers will add wheels for `arm` 

packages like `kivy` are already adding support for `arm`. maybe it's better to open an issue at `pydantic` repo asking them to provide packages for `arm`? i.e: To support things like raspberry-pi

**Comment by Kacper-OS** [comment]
if I seeing correctly, ```pydantic-core``` already have ```arm``` wheels  https://pypi.org/project/pydantic-core/#files
so asking ```pydantic``` developers shouldn,t be needed

**Comment by FeodorFitsner** [comment]
That `arm` is for Linux ARM, not Android.

**Comment by Kacper-OS** [comment]
OH, sorry, my bad

**Comment by Kacper-OS** [comment]
OK, I created PR https://github.com/kivy/python-for-android/pull/2957
I hope every thing will work

**Comment by T-Dynamos** [comment]
This issue has been fixed in upstream.

**Comment by ndonkoHenri** [comment]
> pydantic-core is "Core validation logic for pydantic written in rust", so it's a native library and has to be compiled for Android/iOS.

Closing this issue in favour of #3839

**Comment by GuiAs1** [comment]
I am facing the same problem and haven't found a solution yet, and I didn't see the solution in this issue. Can anyone provide an answer? My pydantic-core==2.23.3

**Comment by GuiAs1** [comment]
> I am facing the same problem and haven't found a solution yet, and I didn't see the solution in this issue. Can anyone provide an answer? My pydantic-core==2.23.3

PS D:\Alivia> flet build apk --module-name main.py --product "AlivIA" --project "AlivIA" -vv
[20:14:18] Flutter executable: C:\src\flutter\bin\flutter.BAT
           Dart executable: C:\src\flutter\bin\dart.BAT
           Flutter bootstrap directory: C:\Users\GUILHE~1\AppData\Local\Temp\flet_flutter_build_3CPEx6zYR0
           No additional Flutter dependencies!
[20:14:22] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.24.1 ✅
           Copying D:\Alivia\assets\icon.png to C:\Users\GUILHE~1\AppData\Local\Temp\flet_flutter_build_3CPEx6zYR0\images
           Customized app icons and splash images ✅
           Run subprocess: ['C:\\src\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
( ●    ) Generating app icons (3.3s)
Downloading packages... 
(  ●   ) Generating app icons ⏳... Got dependencies in `C:\Users\GUILHE~1\AppData\Local\Temp\flet_flutter_build_3CPEx6zYR0`.
(  ●   ) Generating app icons ⏳... 
Built flutter_launcher_icons:flutter_launcher_icons.
(   ●  ) Generating app icons ⏳...   ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════
  
(   ●  ) Generating app icons ⏳... • Creating default icons Android
(  ●   ) Generating app icons ⏳... • Overwriting the default Android launcher icon with a new icon
(   ●  ) Generating app icons ⏳... • Overwriting default iOS launcher icon with new icon
( ●    ) Generating app icons ⏳... Creating Icons for Web...
(     ●) Generating app icons ⏳... Creating Icons for Windows...
(●     ) Generating app icons ⏳... Creating Icons for MacOS...
(     ●) Generating app icons ⏳... 
✓ Successfully generated launcher icons
[20:14:35] Generated app icons ✅
           Run subprocess: ['C:\\src\\flutter\\bin\\dart.BAT', 'run', 'flutter_native_splash:create']
(    ● ) Generating splash screens (1.7s)
Built flutter_native_splash:create.
( ●    ) Generating splash screens ⏳... [Android] Creating default splash images
(    ● ) Generating splash screens ⏳... [Android] Creating dark mode splash images
(     ●) Generating splash screens ⏳... [Android] Creating default android12splash images
(   ●  ) Generating splash screens ⏳... [Android] Creating dark mode android12splash images
(    ● ) Generating splash screens ⏳... [Android] Updating launch background(s) with splash image path...
(    ● ) Generating splash screens ⏳... [Android]  - android/app/src/main/res/drawable/launch_background.xml
( ●    ) Generating splash screens ⏳... [Android]  - android/app/src/main/res/drawable-night/launch_background.xml
(   ●  ) Generating splash screens ⏳... [Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
(     ●) Generating splash screens ⏳... [Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
(   ●  ) Generating splash screens ⏳... [Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
( ●    ) Generating splash screens ⏳... [iOS] Creating  images
(  ●   ) Generating splash screens ⏳... [iOS] Creating dark mode  images
(   ●  ) Generating splash screens ⏳... [iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
(   ●  ) Generating splash screens ⏳... [Web] Creating images
(   ●  ) Generating splash screens ⏳... [Web] Creating images
(   ●  ) Generating splash screens ⏳... [Web] Creating background images
[Web] Creating CSS
(  ●   ) Generating splash screens ⏳... [Web] Updating index.html
( ●    ) Generating splash screens ⏳... 
✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

[20:14:56] Generated splash screens ✅
           Run subprocess: ['C:\\src\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package', 'D:\\Alivia', '--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed',
           '--req-deps', 'flet-embed', '--exclude', 'build', '--verbose']
(   ●  ) Packaging Python app ⏳... 
Built serious_python:main.
( ●    ) Packaging Python app ⏳... Running package command
( ●    ) Packaging Python app ⏳... Creating asset directory: C:\Users\GUILHE~1\AppData\Local\Temp\flet_flutter_build_3CPEx6zYR0\app
Copying Python app from D:\Alivia to C:\Users\GUILHE~1\AppData\Local\Temp\serious_python_temp544a2c21
(  ●   ) Packaging Python app ⏳... Configured mobile platform with sitecustomize.py at C:\Users\GUILHE~1\AppData\Local\Temp\serious_python_sitecustomized611acf3\sitecustomize.py
Installing dependencies [flet-embed, requests, google-auth-oauthlib, elevenlabs, pydantic-core==2.18.4] with pip command to C:\Users\GUILHE~1\AppData\Local\Temp\serious_python_temp544a2c21\__pypackages__
Extracting Python distributive from C:\Users\GUILHE~1\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\GUILHE~1\AppData\Local\Temp\hostpython3.11_bc8ed334
( ●    ) Packaging Python app ⏳... VERBOSE: C:\Users\GUILHE~1\AppData\Local\Temp\hostpython3.11_bc8ed334\python\python.exe -m pip install --isolated --upgrade --target C:\Users\GUILHE~1\AppData\Local\Temp\serious_python_temp544a2c21\__pypackages__ flet-embed requests google-auth-oauthlib elevenlabs pydantic-core==2.18.4
(   ●  ) Packaging Python app ⏳... VERBOSE: Collecting flet-embed
VERBOSE: Obtaining dependency information for flet-embed from https://files.pythonhosted.org/packages/39/26/2bac641454199e7f4cd5d275e25d7a0f6036453635cb82fe06c17fcf1866/flet_embed-0.24.1-py3-none-any.whl.metadata
VERBOSE: Using cached flet_embed-0.24.1-py3-none-any.whl.metadata (1.0 kB)
(●     ) Packaging Python app ⏳... VERBOSE: Collecting requests
VERBOSE: Obtaining dependency information for requests from https://files.pythonhosted.org/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl.metadata
VERBOSE: Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
( ●    ) Packaging Python app ⏳... VERBOSE: Collecting google-auth-oauthlib
VERBOSE: Obtaining dependency information for google-auth-oauthlib from https://files.pythonhosted.org/packages/1a/8e/22a28dfbd218033e4eeaf3a0533b2b54852b6530da0c0fe934f0cc494b29/google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata
(  ●   ) Packaging Python app ⏳... VERBOSE: Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
(   ●  ) Packaging Python app ⏳... VERBOSE: Collecting elevenlabs
VERBOSE: Obtaining dependency information for elevenlabs from https://files.pythonhosted.org/packages/22/22/514a25d75a03b3ec4c0e145d7cd2c1ef6b507fb3419992d92237e73d60d3/elevenlabs-1.7.0-py3-none-any.whl.metadata
VERBOSE: Using cached elevenlabs-1.7.0-py3-none-any.whl.metadata (10 kB)
(   ●  ) Packaging Python app ⏳... VERBOSE: Collecting pydantic-core==2.18.4
( ●    ) Packaging Python app ⏳... VERBOSE: Downloading pydantic_core-2.18.4.tar.gz (385 kB)
(    ● ) Packaging Python app ⏳... VERBOSE: ------------------------------------- 385.1/385.1 kB 923.3 kB/s eta 0:00:00
VERBOSE:
(●     ) Packaging Python app ⏳... VERBOSE: Installing build dependencies: started
(   ●  ) Packaging Python app ⏳... VERBOSE: Installing build dependencies: finished with status 'error'
(    ● ) Packaging Python app ⏳...

**Comment by ndonkoHenri** [comment]
Sub to the new issue https://github.com/flet-dev/flet/issues/3839
