### ISSUE TITLE
`flet create --verbose` should print the list of created files

### ISSUE THREAD

**Issue by algotrading-py** [flet-dev/flet#2418]
Hello! When installing the application template (windows), the parameter "-v, --verbose         -v for detailed output and -vv for more detailed" does not work.
![image](https://github.com/flet-dev/flet/assets/63207079/d5a990f5-bde1-4753-8008-d504e17b18a4)

**Comment by FeodorFitsner** [comment]
I don't think verbose command is ever used in `flet create`. What would you like to see in the output when verbose is on?

**Comment by algotrading-py** [comment]
previously used, I tried it in the fall of 2023. There was a text that a project was created and a list of created files. I think the parameter should be removed from the documentation or a report should be made, which is more correct. The non-functioning parameter is misleading for newcomers to python and those starting to learn Flet. The user starts to think that either flet is defective or that it is doing something wrong.

Translated with www.DeepL.com/Translator (free version)

**Comment by ndonkoHenri** [comment]
I think what he means is, if `--verbose` exists, then it should play visible role, and if it doesn't have one then we should remove it.

> I've changed issue title to "flet create --verbose should print the list of created files"

Nice idea! I think we could leave it, and let it simply spit out the created files.

**Comment by algotrading-py** [comment]
Yeah, that's right. You need a report, as an option all is ok and a list of files. Otherwise I was wondering what my mistake was for a long time.
