### ISSUE TITLE
Blank screen when including python-for-android packages

### ISSUE THREAD

**Issue by epenguins** [flet-dev/flet#2428]
**Description**

First, thank you so much for all the hard work put into Flet! I've been waiting for a long time for the ability to build APKs. I've used Flet for several projects and it is by far my favorite "front end".

I've been able to sucessfully build several APKs using pure Python modules, everything works well there. When I build modules using pytyhon-for-android, the app starts, but shows the dreaded blank screen. I'm using the hello world example, and have not called any of the built modules. The blank screen happens regardless of importing a built module.

I have followed the directions [here]([serious_python | Flutter Package](https://pub.dev/packages/serious_python#android)) and sucessfully built the `dist` to be included with `flet build apk` (trying to include cryptography and bz2). There is some path error on my system when bundle.sh tries to zip `_python_bundle_` and move it to `../../libs/{arch}`. I manually zipped and moved for each architecture, minor inconvenience, but works. After setting the `SERIOUS_PYTHON_P4A_DIST`env variable, `flet build apk` runs and builds the APK. After installation, the app just shows a blank screen. 

I have attached the relavent log files.

Again, thank you for all the work put into Flet!

**Code example to reproduce the issue:**

```python
import flet as ft
##import bz2

def main(page: ft.Page):
    page.add((ft.Text("Hello, Flet!")))
    # Extra lines for more visibility on mobile screens.
    page.add((ft.Text("Hello, Flet!")))
    page.add((ft.Text("Hello, Flet!")))
    page.add((ft.Text("Hello, Flet!")))
    page.add((ft.Text("Hello, Flet!")))
    page.add((ft.Text("Hello, Flet!")))
    page.add((ft.Text("Hello, Flet!")))


ft.app(main)
```

**Describe the results you received:**

The dreaded blank screen.

**Describe the results you expected:**

Hello, Flet! to be repeated on screen.

**Additional information you deem important (e.g. issue happens only occasionally):**

ADB debug indicates that `libpython3.11.so` is not found. I noticed that `libpython3.11.so` is present in /lib of unzipped APK with out python-for-android `dist`. `libpython3.11.so` is not present in /lib when python-for-android dist is included with `flet build apk`. I copied `libpython3.11.so` from an extracted APK without python-for-android `dist`, into the appropriate architectures of /lib so it will be included when `flet build apk` runs, which seems to have solved that issue. 

Now the error is `[FATAL:flutter/fml/thread_local.cc(32)] Check failed: false. pthread_setspecific failed (22): Invalid argument`

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0

```

**Operating system**:

Debian 12

**Additional environment details:**

Python 3.11 in venv

### Log files:
[flet_build_apk.txt](https://github.com/flet-dev/flet/files/13982489/flet_build_apk.txt)
[flet-pre-pyhton-for-android.txt](https://github.com/flet-dev/flet/files/13982492/flet-pre-pyhton-for-android.txt)
[flet-after-python-for-android.txt](https://github.com/flet-dev/flet/files/13982493/flet-after-python-for-android.txt)

**Comment by FeodorFitsner** [comment]
What native Python library are you trying to build/use with p4a?

**Comment by epenguins** [comment]
libbz2 and cryptography

**Comment by epenguins** [comment]
I captured a better ADB log using `adb logcat | grep -e 'flet' -e 'flutter' -e 'python`.

[better_adb_log.txt](https://github.com/flet-dev/flet/files/13994958/better_adb_log.txt)

**Comment by epenguins** [comment]
Looks like this may be a p4a issue, build process download Python 3.10...

**Comment by FeodorFitsner** [comment]
Re-install p4a from this fork https://github.com/flet-dev/python-for-android:

```
pip3 install git+https://github.com/flet-dev/python-for-android.git@3.11.6
```

**Comment by epenguins** [comment]
**Success!**

Both the pypi P4A and your fork of P4A were resulting in the same build error, having to do with linking and python3.11 not found during compilation process. Simply running `p4a clean_builds && p4a clean_dists`, the re-running the build resulted in a successful build. For reference and others with same issue:

1. `p4a create --requirements python3==3.11.2,hostpython3==3.11.2,libbz2, cryptography --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir /path/to/Android/Sdk --ndk-dir /path/to/Android/Sdk/ndk/26.1.10909125/ --dist-name serious_python`
2. `p4a clean_builds && p4a clean_dists`
3. `p4a create --requirements python3==3.11.2,hostpython3==3.11.2,libbz2, cryptography --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir /path/to/Android/Sdk --ndk-dir /path/to/Android/Sdk/ndk/26.1.10909125/ --dist-name serious_python`

Working build!

On a side note, it appears that sometime today, the OpenSSL source URL used in the openssl P4A recipie went away, resulting in failed builds with error 404. This will likely effect everyone using P4A in the coming days. I found an archived version of the source and changed the P4A recipe in my venv. Working URL is `https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1m.tar.gz`.  I can submit a pull request with your fork with the working recipe URL. Hopefully upstream P4A will resolve this soon.

I use the following Flet app to list available Python modules, this confirms that _bz2 is included:
```
import flet as ft
import sys

def main(page: ft.Page):


    for m in sorted(sys.modules):
        page.add((ft.Text(str(m))))
        
    page.scroll = 'always'
    page.update()


ft.app(main)
```
![Screenshot_20240120-143608](https://github.com/flet-dev/flet/assets/126731210/58fd4cb0-7b9e-4c29-b5ca-18bf527642e3)

**Comment by FeodorFitsner** [comment]
Great, thank you for the update and sharing the solution! Did you use p4a from Flet's fork or not?

**Comment by epenguins** [comment]
Yes, that is what I ended up using.

**Comment by epenguins** [comment]
There is an upstream P4A pull request to fix OpenSSL, yay!

https://github.com/kivy/python-for-android/pull/2958#issue-2092275717

**Comment by FeodorFitsner** [comment]
Great, I've put an updated guide here: https://flet.dev/docs/guides/python/packaging-app-for-distribution#native-python-packages and synced Flet's fork with upstream.

**Comment by FeodorFitsner** [comment]
Btw, wrap page content to `ft.SafeArea` (https://flet.dev/docs/controls/safearea) to account for header/footer on mobile device.
