### ISSUE TITLE
Issues with flet build --template_dir option (flet 0.19.0)

### ISSUE THREAD

**Issue by tokyohandsome** [flet-dev/flet#2437]
**Description**
A couple of issues when building app with `--template_dir` option.  

**Code example to reproduce the issue:**
 
1. Build option `--template_dir` explained in the [online document](https://flet.dev/docs/guides/python/packaging-app-for-distribution/#customizing-packaging-template) must be a typo. `--template-dir` (not an underscore but a **dash** between template and dir) is correct.   

Result with `--template_dir`:  
```
usage: flet [-h] [--version] {create,run,pack,publish,build} ...
flet: error: unrecognized arguments: --template_dir flet-build-template  
```

2. Specifying the template folder by relative path `flet build macos --template-dir flet-build-template` won't work.  Need to give it a full-path or use `pwd` like: `` --template-dir `pwd`/flet-build-template ``.

Result of relative path:  
```
Creating Flutter bootstrap project...Traceback (most recent call last):
  File "/Users/handsome/Documents/Python/passgen/.venv/bin/flet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/handsome/Documents/Python/passgen/.venv/lib/python3.11/site-packages/flet/cli/cli.py", line 83, in main
    args.handler(args)
  File "/Users/handsome/Documents/Python/passgen/.venv/lib/python3.11/site-packages/flet/cli/commands/build.py", line 342, in handle
    cookiecutter(
  File "/Users/handsome/Documents/Python/passgen/.venv/lib/python3.11/site-packages/cookiecutter/main.py", line 80, in cookiecutter
    base_repo_dir, cleanup_base_repo_dir = determine_repo_dir(
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/handsome/Documents/Python/passgen/.venv/lib/python3.11/site-packages/cookiecutter/repository.py", line 128, in determine_repo_dir
    raise RepositoryNotFound(
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "https://github.com/flet-dev/flet-build-template.git" could not be found in the following locations:
/Users/handsome/.cookiecutters/flet-build-template/flet-build-template
```

**Describe the results you received:**

See above.

**Describe the results you expected:**

See above.

**Flet version (`pip show flet`)**:

Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/handsome/Documents/Python/passgen/.venv/lib/python3.11/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: 

**Operating system**:

OS: macOS 14.2.1

**Additional environment details:**

pipenv version 2023.10.24

**Comment by taaaf11** [comment]
Option has been fixed in the docs. What is the problem? Actually, it is absolute path to the `flet-build-template` directory cloned from [https://github.com/flet-dev/flet-build-template](https://github.com/flet-dev/flet-build-template) .

And why are you using `pwd`? Is this directory present in the path? Try using `--template-dir pwd`

**Comment by tokyohandsome** [comment]
@taaaf11 , thanks for fixing the typo in the guide.

If `--template-dir` requires absolute path, docs should be corrected as well.

From:
> --template-dir option specifies a **relative path** to a cookiecutter template in a repository.

To:
> --template-dir option specifies an **absolute path** to a cookiecutter template in a repository.

I used `` `pwd` `` because the cookiecutter.json is in the cloned folder `flet-build-template` (see below). Not a big deal if the guide is corrected. Thanks!
```
% tree -L 2
.
├── assets
│   └── icon.png
├── build
│   └── macos
├── flet-build-template
│   ├── LICENSE
│   ├── README.md
│   ├── cookiecutter.json
│   └── {{cookiecutter.out_dir}}
├── main.py
└── requirements.txt

6 directories, 6 files
```

**Comment by taaaf11** [comment]
Did ` --template-dir `pwd`` work?

**Comment by taaaf11** [comment]
@FeodorFitsner 

> "--template-dir option specifies an **absolute** path to a cookiecutter template in a repository."

**Comment by FeodorFitsner** [comment]
@tokyohandsome wait a second, that `--template-dir` goes directly and unchanged to a call to cookiecutter and it says "Relative path to a cookiecutter template in a repository." You are saying it must be an absolute path if directory specified in `--template` parameter?

**Comment by FeodorFitsner** [comment]
OK, will take a look. But again, it's only when `--template` is a path to directory, not a GH repo?

**Comment by taaaf11** [comment]
> OK, will take a look. But again, it's only when `--template` is a path to directory, not a GH repo?

yes

**Comment by tokyohandsome** [comment]
Sorry for not getting back sooner. 
I suppose @FeodorFitsner got it but just in case, only when specifying local template directory by `--template-dir relative_path` flet fails to build. Removing the `--template-dir` option at all or giving it absolute path will build with no problem. Actual error was in my initial post of this issue report.

**Comment by taaaf11** [comment]
> Sorry for not getting back sooner. I suppose @FeodorFitsner got it but just in case, only when specifying local template directory by `--template-dir relative_path` flet fails to build. Removing the `--template-dir` option at all or giving it absolute path will build with no problem. Actual error was in my initial post of this issue report.

You are right. Absolute path works

**Comment by FeodorFitsner** [comment]
OK, I'm going to resolve --template-dir relative to the current directory (pwd).

**Comment by FeodorFitsner** [comment]
OK, have a misunderstanding here!
Apparently, everything works as expected.

Look, to provide a path to a directory with your custom template you have to use `--template` parameter, as stated in the docs - it's either git URL or a path.

`--template-dir`, however specifies a **relative path inside that directory or git repo**.

For example, if my template is in `/Users/john/projects/my-template` I can specify path to it as:

```
flet build web --template /Users/john/projects/my-template
```

or (relatively to current dir):

```
flet build web --template ../../../projects/my-template
```

or I can specify `/Users/john/projects` as a root and then `my-template` as a relative path under that root:

```
flet build web --template /Users/john/projects --template-dir my-template
```

so, `--template-dir` is used if you have multiple templates under `--template`.
