### ISSUE TITLE
By clicking on Datacell, I want the row and column number in the DataTable

### ISSUE THREAD

**Issue by UmerFarooqBiomedical** [flet-dev/flet#2440]
![image](https://github.com/flet-dev/flet/assets/45914644/f5856e9f-4458-4605-bbb2-a42fdb9e68ca)

I am creating this app and I want to access the row and column number of the clicked dropdown DataCell so that I can pick some data from few other data cells according to the dropdown menu selected.

I am not able to find any event for DataCell which provides this feature. Can you please tell me if there is any event? Otherwise, DataTable layout is of no use from data analytics purpose.

Even DropDown must have some event which tells about the DataCell it is present in.

I look forward to your kind response.

**Comment by Shaderd00d** [comment]
Hi.

In the dropdown on_change function, you could iterate the table and compare the DataCell.content object with the ControlEvent.control object. Something like this:

```
def dropdown_changed(e: ft.ControlEvent):
    for i in range(0, len(table.rows)):
        for j in range(len(table.rows[i].cells)):
            if table.rows[i].cells[j].content == e.control:
                print("row: " + str(i) + " col: " + str(j))
                print("dropdown value: " + e.control.value)
```

**Comment by UmerFarooqBiomedical** [comment]
> Hi.
> 
> In the dropdown on_change function, you could iterate the table and compare the DataCell.content object with the ControlEvent.control object to get row and column. Something like this:
> 
> ```
> def dropdown_changed(e: ft.ControlEvent):
>     for i in range(0, len(table.rows)):
>         for j in range(len(table.rows[i].cells)):
>             if table.rows[i].cells[j].content == e.control:
>                 print("row: " + str(i) + " col: " + str(j))
>                 print("dropdown value: " + e.control.value)
> ```

The problem is that I have multiple cells with same content. But I will try this method and inform you if that works. Thanks for your kind comment. :)

**Comment by UmerFarooqBiomedical** [comment]
> Hi.
> 
> In the dropdown on_change function, you could iterate the table and compare the DataCell.content object with the ControlEvent.control object to get row and column. Something like this:
> 
> ```
> def dropdown_changed(e: ft.ControlEvent):
>     for i in range(0, len(table.rows)):
>         for j in range(len(table.rows[i].cells)):
>             if table.rows[i].cells[j].content == e.control:
>                 print("row: " + str(i) + " col: " + str(j))
>                 print("dropdown value: " + e.control.value)
> ```

@Shaderd00d Thanks for your useful response. Yes, the issue is resolved and I can access the data of all the cells in the data table using the method you suggested. Thanks again. Stay blessed. :)
