### ISSUE TITLE
WinError 193 during building with Python 3.12

### ISSUE THREAD

**Issue by gryznar** [flet-dev/flet#2441]
**Description**

Building app using Python 3.12 results in crash. On Python 3.11 problem does not occur

**Code example to reproduce the issue:**

`flet build windows`

**Describe the results you received:**

![image](https://github.com/flet-dev/flet/assets/90425096/0e48abb5-cba2-46b4-88c8-5a24e838ba3a)

**Describe the results you expected:**

It should work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version**:

0.19

**Operating system**:

Windows 11

**Comment by FeodorFitsner** [comment]
Please provide the log of `flet build windows -vv`.

**Comment by gryznar** [comment]
Output with this flag is the same as on attached screenshot

> Please provide the log of `flet build windows -vv`.

**Comment by FeodorFitsner** [comment]
It shouldn't be the same.

**Comment by gryznar** [comment]
![image](https://github.com/flet-dev/flet/assets/90425096/ff92c1c0-3bd9-4556-a9b5-3fa110382262)

**Comment by gryznar** [comment]
They ma be small differences:
![image](https://github.com/flet-dev/flet/assets/90425096/e7d33365-6851-4bc7-bef7-4be5ff99a941)

**Comment by FeodorFitsner** [comment]
Do you have `dart.file` and `flutter.file` files in flutter's `bin` directory?

**Comment by gryznar** [comment]
This is the content of ``flutter\bin`:
![image](https://github.com/flet-dev/flet/assets/90425096/9cb4df0b-0b62-429c-9f90-6aedfcf123ae)

`flutter` and `dart` commands works

**Comment by FeodorFitsner** [comment]
Do you have 32- or 64-bit version of Python installed?

```
python -c "import sys; print(sys. maxsize > 2**32)"
```

The command will return `True` if Python is running in 64-bit and `False` if it's running in 32-bit.

**Comment by gryznar** [comment]
64 bit

**Comment by FeodorFitsner** [comment]
OK, could you give the output of this command:

```
python -c "import shutil; print(shutil.which('flutter'))"
```

**Comment by gryznar** [comment]
![image](https://github.com/flet-dev/flet/assets/90425096/468f31db-9aca-422f-9f31-767282d6372f)

**Comment by FeodorFitsner** [comment]
Thank you. Finally, what is the path returned by this:

```
python -c "import os; print(os.getenv('ComSpec'))"
```

**Comment by gryznar** [comment]
`C:\WINDOWS\system32\cmd.exe`

**Comment by gryznar** [comment]
Yeap, it could

> ...and can the error be reproduced with this command?
> 
> ```
> python -c "import shutil, subprocess; f = shutil.which('flutter'); subprocess.run([f, '--version'])"
> ```

**Comment by FeodorFitsner** [comment]
What is the full path to python.exe?

...I don't know if it's easy for you to test, but I'm wondering if `flet build windows` works well on your system with Python 3.11?

**Comment by gryznar** [comment]
`C:\Users\xxx\pypoetry\Cache\virtualenvs\app-XYKQrPPX-py3.12\Scripts\python.exe` (poetry)

3.11 breaks later during building:
![image](https://github.com/flet-dev/flet/assets/90425096/ecc32860-3ff9-478f-b6f6-cb3fff38e37d)

 These earlier stages connected with packaging works OK:
![image](https://github.com/flet-dev/flet/assets/90425096/55dcd9fa-5386-40c5-8218-a472a67fa040)

**Comment by FeodorFitsner** [comment]
So, `flet` dependency was installed with Poetry? What is `flet` command location?

**Comment by gryznar** [comment]
> So, `flet` dependency was installed with Poetry? What is `flet` command location?

Exactly. But the same settings (poetry used for 3.11) works. `flet.exe` is located under:
![image](https://github.com/flet-dev/flet/assets/90425096/d38c07fb-a2ad-4a45-913b-0c82c07395ba)

**Comment by FeodorFitsner** [comment]
OK, so it's Python 3.12 specific error. Will investigate.

**Comment by gryznar** [comment]
> OK, so it's Python 3.12 specific error. Will investigate.

Thank you!

**Comment by FeodorFitsner** [comment]
Re: cmake/nuget error - try this solution: https://github.com/bluefireteam/audioplayers/issues/1615#issuecomment-1885438395

**Comment by FeodorFitsner** [comment]
Btw, when you paste screenshots into issue instead of text it's a) impossible to copy/paste to google - I have to retype everything by hands and b) the contents of this issue is not indexed by search engines, so other users won't find the issue/solution.

**Comment by gryznar** [comment]
Oh, I see, sorry! You could tell that earlier. Next time I wold provide just text

**Comment by FeodorFitsner** [comment]
So, did you fix nuget sources?

**Comment by gryznar** [comment]
> So, did you fix nuget sources?

Unfortunately not. I am searching for solution

**Comment by gryznar** [comment]
> OK, so it's Python 3.12 specific error. Will investigate.

Only Python 3.12 related. Using `pip` instead of `poetry` does not change nothing

**Comment by david-shu** [comment]
> This is the content of `flutter\bin`: ![image](https://private-user-images.githubusercontent.com/90425096/298302336-9cb4df0b-0b62-429c-9f90-6aedfcf123ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjY2MTEsIm5iZiI6MTcwNTgyNjMxMSwicGF0aCI6Ii85MDQyNTA5Ni8yOTgzMDIzMzYtOWNiNGRmMGItMGI2Mi00MjljLTlmOTAtNmFlZGZjZjEyM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YWRjMjc2YTRiNjVjOTFmNmUwODM4Nzc3Yzg1ZmZjM2U0NGFmODE3MjI0NjdmOGM2ZjUwODVkYTNjODY3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKK7piBkcYGuhQ_jvLxii3rvHbUussAlMehNuNCz57A)
> 
> `flutter` and `dart` commands works

flutter and flutter.bat exists together and shutil.which('flutter') return flutterwhich is not executable on windows. rename or remove file flutter

**Comment by gryznar** [comment]
> > This is the content of `flutter\bin`: ![image](https://private-user-images.githubusercontent.com/90425096/298302336-9cb4df0b-0b62-429c-9f90-6aedfcf123ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjY2MTEsIm5iZiI6MTcwNTgyNjMxMSwicGF0aCI6Ii85MDQyNTA5Ni8yOTgzMDIzMzYtOWNiNGRmMGItMGI2Mi00MjljLTlmOTAtNmFlZGZjZjEyM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YWRjMjc2YTRiNjVjOTFmNmUwODM4Nzc3Yzg1ZmZjM2U0NGFmODE3MjI0NjdmOGM2ZjUwODVkYTNjODY3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKK7piBkcYGuhQ_jvLxii3rvHbUussAlMehNuNCz57A)
> > `flutter` and `dart` commands works
> 
> flutter and flutter.bat exists together and shutil.which('flutter') return flutterwhich is not executable on windows. rename or remove file flutter and dart

Indeed! This was bug related only to Python 3.12.0. 3.12.1 has fixed that. Closing

**Comment by gryznar** [comment]
Unfortunatelly, this is not finish with problems in my journey, but it's a topic on another issue
