### ISSUE TITLE
Blank screen when packed with `flet build web` and `flet-contrib` dependency

### ISSUE THREAD

**Issue by Benitmulindwa** [flet-dev/flet#2444]
I packed my app using **flet build web**,  the process finished successfully, But when I run(test) the app  using ```python -m http.server --directory build/web``` I am getting a blank screen. 

However, this doesn't happen when testing other apps, I discovered that the problem might come from the ** flet_contrib** library used in my app is using.

Here's the error i get in the browser's console window:

![_fletError__](https://github.com/flet-dev/flet/assets/110304380/5e4cbe10-43e9-4abd-be68-a66140d65003)

requirements.txt file:
```
flet==0.19.0
flet_contrib==2023.8.18
```

Running on **Windows 10**,  _python version: 3.9.13_

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
It's been fixed.

Please upgrade to the latest `flet_contrib==2024.1.24`.

**Comment by Benitmulindwa** [comment]
Thank you🙏🏾 .
My app is already live on the web😁 
Here it is👇🏾 if you don’t mind. 

https://neumoflet.onrender.com/ 

Thank you @FeodorFitsner and the whole flet dev team, you’re doing an amazing job. Keep it up💪🏾

**Comment by FeodorFitsner** [comment]
Hey, the app looks great!

Create a new PR with it to https://github.com/Benitmulindwa/neumoflet ;)

**Comment by FeodorFitsner** [comment]
Edit: was supposed to give awesome flet link :)

**Comment by ndonkoHenri** [comment]
Nice app @Benitmulindwa, looks nice on mobile.
The design of the properties section dragged my attention the most - really pretty! It made me think of updating [Flutils](https://flutils.pages.dev) to look quite similar.

**Comment by Benitmulindwa** [comment]
Thank you @ndonkoHenri, but the **Flutils** link doesn't open.

**Comment by Benitmulindwa** [comment]
> Edit: was supposed to give awesome flet link :)

I'll,... I'm actually planning to release an update of the app. It'll have the flet link :)

**Comment by ndonkoHenri** [comment]
> Flutils link doesn't open.

Oh, thanks, need to update it.
