### ISSUE TITLE
UnicodeDecodeError when executing flet build on Windows (ja)

### ISSUE THREAD

**Issue by mochimochiki** [flet-dev/flet#2448]
**Description**

When executing `flet build` on Windows with the system locale `ja`, a UnicodeDecodeError related to the 'cp932' codec occurs. Referring to yaml/pyyaml/issues/123, opening a yaml file using open() without specifying an encoding can cause this problem in some locales. Specifying open( ...coding='utf-8') may resolve the issue.

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    # add/update controls on Page
    pass

ft.app(target=main)
```

**Describe the results you received:**

When running `flet build windows` or other target, the following error occurs:

```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\flet_test\.venv\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\flet_test\.venv\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\flet_test\.venv\Lib\site-packages\flet\cli\commands\build.py", line 353, in handle
    pubspec = yaml.safe_load(f)
              ^^^^^^^^^^^^^^^^^
  ...
UnicodeDecodeError: 'cp932' codec can't decode byte 0x97 in position 3003: illegal multibyte sequence
```

**Describe the results you expected:**

The build process should complete successfully without encountering UnicodeDecodeError.

**Workaround**

I was able to successfully build by setting `Set PYTHONUTF8=1` before building.

**Additional information you deem important (e.g. issue happens only occasionally):**

OS system locale is 'ja'. 
```
python
> import locale
> locale.getpreferredencoding()
'cp932'
```

**Flet version (`pip show flet`)**:

```
0.19.0
```

**Operating system**:

Windows 11 Pro

**Additional environment details:**

- System locale: ja
- Python version: 3.12.1

**Comment by FeodorFitsner** [comment]
I guess we should specify encoding in all `open()` methods, both reads and writes, to make it right?
