### ISSUE TITLE
To build use Python in version which is used in the project 

### ISSUE THREAD

**Issue by gryznar** [flet-dev/flet#2449]
**Please Describe The Problem To Be Solved**

As far I've noticed, `flet` is using hard coded `Python` version to build an app:
`Downloading Python distributive from https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\xxx\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz`. 
(venv in my project is build using Python 3.12.1 which may lead to compatibility issues)

**Possible solutions**
This can be easily replaced with simple check which version is used in the project (`python -V`) and download this version or use the newest (currently newest is `3.12.1`)

Alternatively (or separately), there could be an option to specify `Python` version as CLI argument to `build` command

**Comment by FeodorFitsner** [comment]
3.11.6 is the version of Python that must be the same across all layers of a native Flet app: Python embedded libraries, native Python packages, user code and the tooling to compile user app. That's the reason `flet build` does not rely on Python installed in your system, but download it. Recipes for native modules are usually tailored to specific Python versions as well as Python's ABI changes between major releases. Whatever works for Python 3.11 won't necessary work for 3.12.
