### ISSUE TITLE
Problems with building APK app that depends on lxml

### ISSUE THREAD

**Issue by gryznar** [flet-dev/flet#2453]
**Description**

Building Android app, that depends on lxml may lead to few problems:
1. Packaging tool is not using `.whl` available on `PyPI`, trying to build from `.tar.gz` instead (as opposite to `flet build windows` which uses `.whl`)
2. Crash hangs the process forever

**Code example to reproduce the issue:**

```powershell
flet build apk
```

**Describe the results you received:**

```powershell
VERBOSE: Building wheel for lxml (pyproject.toml): finished with status 'error'
^CTerminate batch job (Y/N)? 
```

**Describe the results you expected:**

1. Installation manager should prefer `.whl` than source distribution
2. Error should propagate and not hang the program

**Flet version**:

```
0.19.0
```

**Operating system**:

Windows

**Comment by FeodorFitsner** [comment]
`lxml` is the native package, please follow this guide (until the process is completely automated): https://flet.dev/docs/guides/python/packaging-app-for-distribution#native-python-packages

**Comment by ndonkoHenri** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/3839
