### ISSUE TITLE
Audio input access

### ISSUE THREAD

**Issue by RustX2802** [flet-dev/flet#2455]
**Please Describe The Problem To Be Solved**

Is there any possibility to add a feature to access the audio input from Flet? I need directly access to the audio interface from the client browser and it doesn't look like that Flet provides a way to access it. The only thing I could find in the Flet doc is how to play audio, not how to record it (https://flet.dev/docs/controls/audio/).

**Comment by FeodorFitsner** [comment]
Yep, it's on the roadmap: https://github.com/flet-dev/flet/issues/419
Closing this issue as a duplicate.
