### ISSUE TITLE
Pin `flet build` template to Flet version

### ISSUE THREAD

**Issue by mochimochiki** [flet-dev/flet#2459]
**Description**

When executing `flet build windows` with flet v0.18.0, an error occurs, stating "No file or variants found for asset: app/app.zip.hash."
Note that in v0.19.0, at least as of today, the build is successful.

**Code example to reproduce the issue:**

```bash
flet build windows
```

**Describe the results you received:**

```
Building Windows application...
...
  Error detected in pubspec.yaml:
  No file or variants found for asset: app/app.zip.hash.
```

**Describe the results you expected:**

Build succeeds without error

**Additional information you deem important (e.g. issue happens only occasionally):**

* This error was not present on January 1st, but it is currently occurring.

**Workaround**

I checked the commit history of [flet-build-template](https://github.com/flet-dev/flet-build-template/commits/main/) and found changes regarding `app.zip.hash`, so I changed it to refer to the previous commit and the build was successful

```
flet build --template-ref ccddb0b windows
```

It was unexpected that dependencies would be broken if --template-ref was not specified when building. It would be helpful if the appropriate template was selected when simply running flet build.

**Flet version (`pip show flet`):**

```
Name: flet
Version: 0.18.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\flet_test\.venv\Lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system:**

Windows 11 Pro

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
That's a valid point you are bringing here, thank you!
I've been thinking about pinning template version, but didn't have enough time to do it.

Now, I think that we should pin specific **Flet version** to a specific **branch** of Flet build template repo. Thus, we'll be able to do small tweaks/bugfixes once Flet version released. For example, Flet 0.20.0 would be pulling by default `0.20.0` branch of Flet build template (`--template-ref 0.20.0`).
