### ISSUE TITLE
UserControl will_unmount() docs example

### ISSUE THREAD

**Issue by Dekubaka** [flet-dev/flet#246]
Hello! I'm going through the docs and came up to "User controls" in the python guides sections and I'm a bit confused with `will_unmount()` in countdown timer example.

I see that it is "called before the UserControl is removed from a page", but when is UserControl removed from the page in the example? From what I see the timer just goes down to 00:01 and stops, even with `will_unmount()` commented out. Would I just have to clear or change the page view to have `will_unmount()` be called automatically?

```python
import flet
from flet import UserControl, Text
import threading
import time


# Mounts are automatically called.
# did_mount() - called after the UserControl added to a page and assigned transient id.
# will_unmount() - called before the UserControl is removed from a page.

class Countdown(UserControl):
    def __init__(self, seconds):
        super().__init__()
        self.seconds = seconds

    def did_mount(self):
        self.running = True
        self.th = threading.Thread(target=self.update_timer, args=(), daemon=True)
        self.th.start()

    def will_unmount(self):
        self.running = False

    def update_timer(self):
        while self.seconds and self.running:
            mins, secs = divmod(self.seconds, 60)
            self.countdown.value = "{:02d}:{:02d}".format(mins, secs)
            self.update()
            time.sleep(1)
            self.seconds -= 1

    def build(self):
        self.countdown = Text()
        return self.countdown

def main(page):
    page.add(Countdown(10), Countdown(5))

flet.app(target=main)
```

**Comment by FeodorFitsner** [comment]
Thanks for trying Flet!

Yep, when the control is removed from a page (control tree to be recise as it could be nested within another control) its `will_unmount()` is called before that.

So, doing, for example this will call `will_unmount()`:

```python
page.controls.clear()
page.update()
```

**Comment by FeodorFitsner** [comment]
This is the place: https://github.com/flet-dev/flet/blob/main/sdk/python/flet/control.py#L409-L415

**Comment by Dekubaka** [comment]
Thanks! That cleared things up.
