### ISSUE TITLE
The datatable tooltip stops working...

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2460]
sample code...
datatable = ft.DataTable(
        border=ft.border.all(1, ft.colors.GREY_700),
        **tooltip='Click curto para acessar a OS e click longo para excluir',**
        heading_row_color=ft.colors.AMBER_200,
        data_text_style=ft.TextStyle(size=13,color=ft.colors.GREY_700,font_family='Tahoma'),
        heading_row_height=60,
        horizontal_lines=ft.border.BorderSide(1, ft.colors.ORANGE_300),
        data_row_color={"hovered": ft.colors.BLUE_100},
        heading_text_style=ft.TextStyle(size=15,color=ft.colors.GREY_700,weight="BOLD",font_family='Tahoma'),
        columns=[

**Comment by ndonkoHenri** [comment]
Invalid issue.
Please make sure to use to use the issue template when submitting an issue.

**Comment by jvalle63** [comment]
*the tooltip stops working when the datatable has several lines, and the datatable exceeds the screen limits in length, **



**Code example to reproduce the issue:**

```
    datatable = ft.DataTable(
        border=ft.border.all(1, ft.colors.GREY_700),
        **tooltip='Click curto para acessar a OS e click longo para excluir',**
        heading_row_color=ft.colors.AMBER_200,
        data_text_style=ft.TextStyle(size=13,color=ft.colors.GREY_700,font_family='Tahoma'),
        heading_row_height=60,
        horizontal_lines=ft.border.BorderSide(1, ft.colors.ORANGE_300),
        data_row_color={"hovered": ft.colors.BLUE_100},
        heading_text_style=ft.TextStyle(size=15,color=ft.colors.GREY_700,weight="BOLD",font_family='Tahoma'),
        columns=[
            ft.DataColumn(ft.Text('ID')),
            ft.DataColumn(ft.Text('Cliente')),
            ft.DataColumn(ft.Text('Celular')),
            ft.DataColumn(ft.Text('Entrada'),visible=False),
            ft.DataColumn(ft.Text('Retirada')),
            ft.DataColumn(ft.Text('Valor'),visible=False),
            ft.DataColumn(ft.Text('Status')),
            ],
        rows=[]
    )
    def incluir_linhas():
        """ 
        função que insere linhas no datatable a partir do dataframe
        """
        tabela_os=upload_dataframe()

        for a,x in tabela_os.iterrows():
            datatable.rows.append(
                ft.DataRow(
                    cells=[
                        ft.DataCell(ft.Text(x['ID'])),
                        ft.DataCell(ft.Text(x['Cliente'].title(),width=130)),
                        ft.DataCell(ft.Text(x['Celular'],color=ft.colors.GREY_700),placeholder=True),
                        ft.DataCell(ft.Text(converte_data(x['Retirada']))),
                        ft.DataCell(ft.Text(x['Status'].title())),
                        ft.DataCell(ft.Text(converte_data(x['Entrada'])),visible=False),
                        ft.DataCell(ft.Text(real(x['Valor']),color=ft.colors.GREY_700),placeholder=True,visible=False),
                    ],
                    data=[
                            int(x['ID']),
                            x['Cliente'],
                            x['Celular'],
                            x['Entrada'],
                            #x['Retirada'],
                            #float(x['Valor']),
                            x['Status'],
                    ],
                    selected=False,
                    on_select_changed=myselect,
                    on_long_press=deleta_linha

```

**Describe the results you received:**
The program works fine. The only wrong thing is the missing tooltip, when the datatable has a lot of lines.


**Additional information you deem important (e.g. issue happens only occasionally):**
I don't know after how many lines the tooltip stops working

**Flet version (`pip show flet`)**:
Version: 0.18.0
```
(paste your output here)
```

**Operating system**:
windows 10
 VSCode


**Additional environment details:**

**Comment by jvalle63** [comment]
You don't need all the code. You have only to build a datatable and input data in it., using, if you want,  my datatable structure...
