### ISSUE TITLE
page.client_storage doesn't work in web browser mode

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2461]
**Description**

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by taaaf11** [comment]
Please give required details. I can't reproduce the issue

**Comment by jvalle63** [comment]
Description
I'm using "page.client_storage" to keep the password saved, once the user type it correctly once.
It works fine in app mode ft.app(target=main). But when I change to web mode, "ft.app(target=main, view=ft.AppView.WEB_BROWSER)" the function stop working.

Code example to reproduce the issue:
senha="dalci9"
valor = pg.page.client_storage.get("key")
    
myappbar=ft.AppBar(title=ft.Text('Login'),bgcolor='blue')
    pg.set_appbar(myappbar)

    def clicado(e):
        
        if campo_senha.value != senha:
            campo_senha.error_text='Senha Inválida'
            campo_senha.value=""
            pg.page.client_storage.remove("key")
        else:
            print(valor)
            campo_senha.error_text=""
            pg.page.client_storage.set("key",senha)
            pg.page.clean()
            pg.navigator.navigate('principal',pg.page,(senha))
        pg.page.update()

Describe the results you received:
On web browser, I have no results. I app mode, the program gives me the saved password

Describe the results you expected:
I  need the program gives me the saved password even on web browser

Additional information you deem important (e.g. issue happens only occasionally):
I think the issue may be that the task of saving the password is with the browser, in web browser mode
Flet version (pip show flet):
Version: 0.18.0
(paste your output here)
Operating system:
windows 10
Additional environment details:

**Comment by taaaf11** [comment]
Shouldn't it be `page.client_storage.get` rather than `pg.page.client_storage.get`?

**Comment by ndonkoHenri** [comment]
@jvalle63, please share repro code we can run to test the issue.

**Comment by jvalle63** [comment]
"page.client_storage.get rather than pg.page.client_storage.get?"
Shure. The pg is because I'm using the module flet_navigator
Sorry

**Comment by jvalle63** [comment]
But  I testet on a server and seems to be OK..

**Comment by taaaf11** [comment]
It should be working. What error you get? Or what you want? Tell everything, so that we can "do" the issue accordingly

**Comment by jvalle63** [comment]
It doesn't work only when you call a webpage via Visual Studio Code...
