### ISSUE TITLE
Add `rtl` property to other controls

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2462]
Discussion: https://github.com/flet-dev/flet/discussions/2439#discussioncomment-8203715

Controls:

- [x] `TextField`
- [x] `Text` 
- [ ] `Container`
- [ ] `Column`
- [ ] `Row`
- [ ] `ResponsiveRow`

**Comment by burhansvural** [comment]
![flutter_flet_1](https://github.com/flet-dev/flet/assets/149883930/a6a3220a-e611-4093-9f70-35608e292c86)
I'm adding new property in flutter. You can look at the picture above.

**Comment by burhansvural** [comment]
![CustomTextField](https://github.com/flet-dev/flet/assets/149883930/f7850f80-fb83-4b96-be68-b8d6fe8dd07c)

`
# Created by Burhan Suleyman VURAL - burhansvural@gmail.com
# Created Date : 25/01/2024

from enum import Enum
from flet import *
import flet.canvas as fcvs


class LabelAlign(Enum):
    NONE = None
    START = "start"
    CENTER = "center"
    END = "end"


class CustomTextField(fcvs.Canvas):
    __pos = LabelAlign.NONE

    def __init__(self, lblAlign: LabelAlign, lblStr: str, lblColor: str):
        super().__init__()
        self.__txt_width_widget = TextField(focused_border_width=1, focused_border_color=lblColor,
                                            border_color=lblColor)
        if lblAlign == LabelAlign.END:
            self.__pos = alignment.top_right
        elif lblAlign == LabelAlign.CENTER:
            self.__pos = alignment.top_center
        else:
            self.__pos = alignment.top_left
        self.__lblColor = lblColor
        self.__lblStr = "  " + lblStr + "  —"

        self.content = Stack(
            controls=[
                Container(
                    content=self.__txt_width_widget,
                ),
                Container(
                    content=Text(
                        overflow=TextOverflow.ELLIPSIS,
                        color=self.__lblColor,
                        value=self.__lblStr,
                        size=12,
                        bgcolor=colors.WHITE,
                    ),
                    alignment=self.__pos,
                    margin=margin.only(left=16, top=-9.88, right=6),
                )
            ],
        )


def main(pagex: Page):
    pagex.title = "Custom Text Field With Label Alignment"

    pagex.add(CustomTextField(lblAlign=LabelAlign.START, lblStr="Example Label 1", lblColor=colors.RED))
    pagex.add(CustomTextField(lblAlign=LabelAlign.CENTER, lblStr="Example Label 2", lblColor=colors.GREEN))
    pagex.add(CustomTextField(lblAlign=LabelAlign.END, lblStr="Example Label 3", lblColor=colors.ORANGE))
    pagex.update()


app(target=main)

`

**Comment by burhansvural** [comment]
![CustomTextField](https://github.com/flet-dev/flet/assets/149883930/c794307f-697b-4e8d-ab3a-fd1299505118)

`
from enum import Enum
from flet import *
import flet.canvas as fcvs


class LabelAlign(Enum):
    NONE = None
    START = "start"
    CENTER = "center"
    END = "end"


class CustomTextField(fcvs.Canvas):
    __pos = LabelAlign.NONE

    def __init__(self, lblAlign: LabelAlign, lblStr: str, lblColor: str):
        super().__init__()        
        self.__txt_width_widget = TextField(focused_border_width=1, focused_border_color=lblColor,
                                            border_color=lblColor)
        if lblAlign == LabelAlign.END:
            self.__pos = alignment.top_right
        elif lblAlign == LabelAlign.CENTER:
            self.__pos = alignment.top_center
        else:
            self.__pos = alignment.top_left
        self.__lblColor = lblColor
        self.__lblStr = "  " + lblStr + "  —"

        self.content = Stack(
            controls=[
                Container(
                    content=self.__txt_width_widget,
                ),
                Container(
                    content=Text(
                        overflow=TextOverflow.ELLIPSIS,
                        color=self.__lblColor,
                        value=self.__lblStr,
                        size=12,
                        bgcolor=colors.WHITE,
                    ),
                    alignment=self.__pos,
                    margin=margin.only(left=16, top=-9.88, right=6),
                )
            ],
        )


def main(pagex: Page):
    pagex.title = "Custom Text Field With Label Alignment"

    pagex.add(CustomTextField(lblAlign=LabelAlign.START, lblStr="Example Label 1", lblColor=colors.RED))
    pagex.add(CustomTextField(lblAlign=LabelAlign.CENTER, lblStr="Example Label 2", lblColor=colors.GREEN))
    pagex.add(CustomTextField(lblAlign=LabelAlign.END, lblStr="Example Label 3", lblColor=colors.ORANGE))
    pagex.update()


app(target=main)

`

**Comment by taaaf11** [comment]
@burhansvural Kindly open a new issue for this

**Comment by burhansvural** [comment]
> @burhansvural Kindly open a new issue for this

For which subject?

**Comment by taaaf11** [comment]
@burhansvural for the new control you are trying to implement

**Comment by burhansvural** [comment]
> @burhansvural for the new control you are trying to implement

@taaaf11 I wrote and shared the simple codes above in response to 3mora2's question. Because the topic has been moved here.
Link:
https://github.com/flet-dev/flet/discussions/2439#discussioncomment-8203715
[Question] label text_align

**Comment by taaaf11** [comment]
@burhansvural you wrote, but creating another issue, specifically for the feature, will bring more "attention" to that, but they are now remaining in the replies to other discussions etc etc. I suggest you to open a new issue to ask the necessary things when implementing a control.

**Comment by burhansvural** [comment]
> I want to start a study to transfer all classes in Flutter to Flet. Is there a document for the roadmap? Also, is there any documentation on how to use the graphics drawing engine and how to draw the controls? How can I transfer classes in flutter to flet? Is there an example explanation? Could you help me with this?

@taaaf11 for this question? ==> "I want to start a study to transfer all classes in Flutter to Flet. Is there a document for the roadmap? Also, is there any documentation on how to use the graphics drawing engine and how to draw the controls? How can I transfer classes in flutter to flet? Is there an example explanation? Could you help me with this?"

**Comment by taaaf11** [comment]
@burhansvural yes

**Comment by burhansvural** [comment]
> @burhansvural yes

ok. thanks.
