### ISSUE TITLE
Loading button / Loading Screen

### ISSUE THREAD

**Issue by for-the-zero** [flet-dev/flet#2468]
**Please Describe The Problem To Be Solved**

Sometimes my programs don't expect the user to click a button multiple times, especially if the execution takes time, which can lead to all sorts of problems

So I thought it would be a good idea to include a feature to be able to temporarily disable a button or a group of buttons and show the loading pattern, (disabling of individual buttons is possible, but I didn't find buttons with progress circles in the documentation)

Or add a full window mask that doesn't allow the user to do anything with the window

**Comment by ndonkoHenri** [comment]
Disabling a parent control will recursively disable all its children. 
So you can try disabling a top control so that all its children are disabled.

**Comment by saadjoe** [comment]
If you would like to create a full window mask, here is a simple example of how you can achieve this:
```python
from time import sleep

import flet as ft


def main(page: ft.Page):
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER

    def _start(self):
        page.overlay.append(
            ft.Stack(
                controls=[
                    ft.Container(expand=True, bgcolor=ft.colors.BLACK, opacity=0.8),
                    ft.Column(
                        alignment=ft.MainAxisAlignment.CENTER,
                        controls=[ft.ProgressBar()],
                    ),
                ]
            )
        )
        page.update()
        sleep(5)
        page.overlay.clear()
        page.update()

    page.add(ft.ElevatedButton(text="Start", on_click=_start))


ft.app(target=main)
```
