### ISSUE TITLE
Inconsistent UI display between iOS and macOS

### ISSUE THREAD

**Issue by qjasn** [flet-dev/flet#2472]
**Description**

Inconsistent UI display between iOS and macOS
macOS show the element,but ios not

**Code example to reproduce the issue:**

```python

from flet import *


def main(page: Page):
    page.add(Row(
        controls=[
            MenuBar([SubmenuButton(
                content=Text("New"),
                leading=Icon(icons.ADD),
                on_focus=lambda e: print(e),
                controls=[
                    SubmenuButton(
                        content=Text("Function"),
                        leading=Icon(icons.FUNCTIONS),
                        controls=[
                            MenuItemButton(

                                on_hover=None,
                                content=Text("Function")
                            )
                        ]
                    ),
                    MenuItemButton(
                        content=Text("Equation"),
                        leading=Icon(icons.FUNCTIONS),
                        on_click=lambda e: print("add e"),
                        on_hover=None,
                    )
                ]
            )])
        ],
        alignment=MainAxisAlignment.END
    ))


app(main)

```

**Describe the results you received:**
What I see in the macOS:
![7ABF538B-E687-4041-B088-E052EFE4726E](https://github.com/flet-dev/flet/assets/73731689/859ac43e-f8a3-4507-8078-624a824d799d)
What I see in the iOS
![276E0355-D61A-4C4B-A5AD-A71B742D594B](https://github.com/flet-dev/flet/assets/73731689/e03b0a6d-1eb6-48d3-ab69-27828d5def02)

**Describe the results you expected:**
How I can make the display a same thing?

**Additional information you deem important (e.g. issue happens only occasionally):**
Almost 100% happen

**Flet version (`pip show flet`)**:

```
0.19.0
```

**Operating system**:
iOS macOS

**Additional environment details:**
My macOS’s python version is 3.9.6,but my iOS flet app’s python version is 3.11.6,will this lead to the problem?

**Comment by ndonkoHenri** [comment]
MenuBar and co were introduced in v0.18.0. The Flet mobile app has v0.17.0, meaning it needs to be updated. It will be in the coming days.
Closing in favor of #
