### ISSUE TITLE
flet build web -vv : Error: FormatException : Missing extension byte

### ISSUE THREAD

**Issue by david-shu** [flet-dev/flet#2474]
os: win10 64bit
python 3.12/3.11
flet: 0.19

when i run " flet build web -vv", FormatException Error raised. 

----------------------------------------------------------------------------

Flutter bootstrap directory: 
C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_UeBmaECgPg
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...Running package command
Creating asset directory: C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_UeBmaECgPg\app
Copying Python app from F:\code\predict_dev\tt to C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303
Configured emscripten_3_1_45_wasm32 platform with sitecustomize.py at C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_sitecustomize89cd4e55\sitecustomize.py
Installing 'find-links' dependencies [micropip] with pip command to C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303\__pypackages__
Extracting Python distributive from C:\Users\ADMINI~1\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_e0e880a0
VERBOSE: C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_e0e880a0\python\python.exe -m pip install --isolated --upgrade --target C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303\__pypackages__ --no-index --find-links C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_UeBmaECgPg\find-links.html micropip
VERBOSE: Looking in links: c:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_UeBmaECgPg\find-links.html
VERBOSE: Collecting micropip
VERBOSE: Using cached https://cdn.jsdelivr.net/pyodide/v0.24.1/full/micropip-0.5.0-py3-none-any.whl (144 kB)
VERBOSE: Collecting packaging>=23.0 (from micropip)
VERBOSE: Using cached https://cdn.jsdelivr.net/pyodide/v0.24.1/full/packaging-23.1-py3-none-any.whl (157 kB)
VERBOSE: Installing collected packages: packaging, micropip
VERBOSE: Successfully installed micropip-0.5.0 packaging-23.1
Installing dependencies [flet-pyodide] with pip command to C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303\__pypackages__
VERBOSE: C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_e0e880a0\python\python.exe -m pip install --isolated --upgrade --target C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303\__pypackages__ flet-pyodide
VERBOSE: Collecting flet-pyodide
VERBOSE: Obtaining dependency information for flet-pyodide from https://files.pythonhosted.org/packages/15/9f/b8c038872913feafe37ca51b69c1720b2c3f6572ea7966b663f887f92a81/flet_pyodide-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_pyodide-0.19.0-py3-none-any.whl.metadata (3.0 kB)
VERBOSE: Collecting flet-core==0.19.0 (from flet-pyodide)
VERBOSE: Obtaining dependency information for flet-core==0.19.0 from https://files.pythonhosted.org/packages/cc/cc/520c8a7650b57c615a8be1679c5199a7f57ba59639d76cc7ea0a76bda19f/flet_core-0.19.0-py3-none-any.whl.metadata
VERBOSE: Using cached flet_core-0.19.0-py3-none-any.whl.metadata (1.1 kB)
VERBOSE: Collecting repath<0.10.0,>=0.9.0 (from flet-core==0.19.0->flet-pyodide)
VERBOSE: Using cached repath-0.9.0-py3-none-any.whl (4.7 kB)
VERBOSE: Collecting six>=1.9.0 (from repath<0.10.0,>=0.9.0->flet-core==0.19.0->flet-pyodide)
VERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
VERBOSE: Using cached flet_pyodide-0.19.0-py3-none-any.whl (5.4 kB)
VERBOSE: Using cached flet_core-0.19.0-py3-none-any.whl (295 kB)
VERBOSE: Installing collected packages: six, repath, flet-core, flet-pyodide
VERBOSE: Successfully installed flet-core-0.19.0 flet-pyodide-0.19.0 repath-0.9.0 six-1.16.0
Compiling Python sources at C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303
VERBOSE: C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_e0e880a0\python\python.exe -m compileall -b C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303
VERBOSE: Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\__init__.py'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\canvas'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\canvas\\__init__.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\flet.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\matplotlib_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\plotly_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\pyodide_connection.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet\\version.py'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\__init__.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\alert_dialog.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\alignment.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\animated_switcher.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\animation.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\app_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\audio.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\badge.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\banner.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\blur.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\border.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\border_radius.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\bottom_app_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\bottom_sheet.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\buttons.py'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\__init__.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\arc.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\canvas.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\circle.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\color.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\fill.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\line.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\oval.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\path.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\points.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\rect.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\shadow.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\shape.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\canvas\\text.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\card.py'...
Listing 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\bar_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\bar_chart_group.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\bar_chart_rod.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\bar_chart_rod_stack_item.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\chart_axis.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\chart_axis_label.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\chart_grid_lines.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\chart_point_line.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\chart_point_shape.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\line_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\line_chart_data.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\line_chart_data_point.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\pie_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\charts\\pie_chart_section.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\checkbox.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\chip.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\circle_avatar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\client_storage.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\clipboard.py'...
VERBOSE: Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\colors.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\column.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\connection.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\constrained_control.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\container.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\control.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\control_event.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_alert_dialog.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_app_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_checkbox.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_dialog_action.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_navigation_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_radio.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_slider.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\cupertino_switch.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\datatable.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\date_picker.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\dismissible.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\divider.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\drag_target.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\draggable.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\dropdown.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\elevated_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\embed_json_encoder.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\event.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\event_handler.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\expansion_panel.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\expansion_tile.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\file_picker.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\filled_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\filled_tonal_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\flet_app.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\floating_action_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\form_field_control.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\gesture_detector.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\gradients.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\grid_view.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\haptic_feedback.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\icon.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\icon_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\icons.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\image.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\inline_span.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\list_tile.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\list_view.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\local_connection.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\locks.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\margin.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\markdown.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\matplotlib_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\menu_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\menu_item_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\navigation_bar.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\navigation_drawer.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\navigation_rail.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\outlined_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\padding.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\page.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\painting.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\plotly_chart.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\popup_menu_button.py'...
Compiling 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\serious_python_tempad7c9303\\__pypackages__\\flet_core\\progress_bar.py'...
Error: FormatException: Missing extension byte (at offset 15187)
Deleting temp directory C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_tempad7c9303
Deleting sitecustomize directory C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_sitecustomize89cd4e55
Deleting Python directory C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_e0e880a0
Flet app package app/app.zip was not created.
Deleting Flutter bootstrap directory 
C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_UeBmaECgPg
Error building Flet app - see the log of failed command above.

**Comment by FeodorFitsner** [comment]
Does it work without `-vv`?

**Comment by david-shu** [comment]
Error occured when run cmd "flet build web".

Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Generating splash screens...OK
Packaging Python app...Flet app package app/app.zip was not created.
Error building Flet app - see the log of failed command above.

> Does it work without `-vv`?

**Comment by ndonkoHenri** [comment]
Please retry with the latest Flet version.
