### ISSUE TITLE
Checkbox label text color changes to white when changing the size of the TextTheme body_medium property

### ISSUE THREAD

**Issue by Shaderd00d** [flet-dev/flet#2484]
**Description**

Changing the text size using TextStyle for the TextTheme body_medium property apparently changes the label text color of a checkbox to white.

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    page.bgcolor = ft.colors.RED
    theme=ft.Theme(
        text_theme=ft.TextTheme(
            body_medium=ft.TextStyle(size=20)
        )
    )
    page.theme = theme
    check = ft.Checkbox(label="Checkbox label")
    page.add(check)

ft.app(target=main)
```

**Describe the results you received:**

Without TextStyle, the text is rendered black by default.
![image](https://github.com/flet-dev/flet/assets/9315812/793b4a5f-5d44-4594-ba19-60df1951c5e3)

Using TextStyle, the size changes take effect, but the label is rendered white for no apparent reason.  I expect the text color to be black (default).

body_medium=ft.TextStyle(size=20)
![image](https://github.com/flet-dev/flet/assets/9315812/9514e9e1-d780-43dc-9027-273a55a338f7)

body_medium=ft.TextStyle(size=8)
![image](https://github.com/flet-dev/flet/assets/9315812/1dd9bf2d-57a7-4d6d-add0-01bac939f33f)

**Describe the results you expected:**

I expect the label text size to be changed, but no change of the text color.

**Flet version (`pip show flet`)**:

```
Version: 0.19.0
```

**Operating system**:

Windows 10

**Comment by ndonkoHenri** [comment]
It should have been caused by the `TextStyle` default color value. To resolve this issue, set the `color` of the `TextStyle` to `ON_SURFACE`.
```python
theme = ft.Theme(
        text_theme=ft.TextTheme(
            body_medium=ft.TextStyle(size=20, color=ft.colors.ON_SURFACE),
        )
    )
```
