### ISSUE TITLE
FAiling to build using flet build apk -v

### ISSUE THREAD

**Issue by gitmatsika** [flet-dev/flet#2485]
Failing to build on windows and Linux. Then moved to ubuntu running Python 3.12. It was run Python 3.10 and had to upgrade hoping to resolve the issue

I see below the build trying to extract first Python 3.11. Do i need to install python 3.11 and setup my flet environment using python 3.11

****Configured mobile platform with sitecustomize.py at /tmp/serious_python_sitecustomizeBFNAYR/sitecustomize.py
Installing dependencies  with pip command to /tmp/serious_python_tempGDUBMC/__pypackages__
Extracting Python distributive from /tmp/cpython-3.11.6+20231002-x86_64-unknown-linux-gnu-install_only.tar.gz to /tmp/hostpython3.11_FZMUCR

/tmp/hostpython3.11_FZMUCR/python/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
ERROR: Invalid requirement: '#flet-embed'

 A new release of pip is available: 23.2.1 -> 23.3.2
 To update, run: /tmp/hostpython3.11_FZMUCR/python/bin/python3 -m pip install --upgrade pip

Deleting Flutter bootstrap directory /tmp/flet_flutter_build_WAjrcQinHq****

**Comment by ndonkoHenri** [comment]
![image](https://github.com/flet-dev/flet/assets/98978078/26894d83-b5e3-430b-b1fd-ff11c7c426ad)

Did you read the above note from the [guide](https://flet.dev/docs/guides/python/packaging-app-for-distribution#project-structure)?

**Comment by gitmatsika** [comment]
Thanks for the response. I did not use pip freeze. I added my requirements manually. Only have tow flet and pandas

**Comment by ndonkoHenri** [comment]
Please can you retry with the latest Flet version?
