### ISSUE TITLE
Only one instance of Flet can be run at a time

### ISSUE THREAD

**Issue by abulka** [flet-dev/flet#249]
When you run a Flet application, then try to also run another Flet application e.g.

    python drag1.py
    python example2.py

only the first application runs.  The second application is blocked because the first one is running.

Ideally it should be possible to run multiple Flet applications on a computer at the same time.

Even Flet executables created with Pyinstaller suffer this same limitation.

**Comment by FeodorFitsner** [comment]
What OS is that?

**Comment by abulka** [comment]
MacOS.  Monterey.

**Comment by FeodorFitsner** [comment]
Hm, indeed there is `-n` option that allows mutliple instances: https://ss64.com/osx/open.html
Flet uses `open` to run Flet.app bundle.
Let's make it a bug.
