### ISSUE TITLE
How to Build APK in Linux or Windows

### ISSUE THREAD

**Issue by MominIqbal-1234** [flet-dev/flet#2490]
**Description**

I Try to Build APK file in  WSL (Windows Subsystem Linux) 
Install Dependencies before build APK
1) sudo snap install flutter
2) sudo apt install android-sdk sdkmanager
3) sudo sdkmanager --licenses 
4) sudo -E sdkmanager --install  "ndk;23.1.7779620"

**Then Run APK**
```python
flet build apk
```

**Describe the results you received:**

![image](https://github.com/flet-dev/flet/assets/61788052/9d882a57-da9f-40aa-b6e3-7ce99d0e6cbe)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/momin/.local/lib/python3.10/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:
Windows 10

**Additional environment details:**
i am use ubuntu in WSL

**Comment by taaaf11** [comment]
give your `requirements.txt`

**Comment by ndonkoHenri** [comment]
@MominIqbal-1234 it is mentioned in the docs [not](https://flet.dev/docs/guides/python/packaging-app-for-distribution#flutter-sdk) to install flutter with snap. This could be the cause of your issue.

**Comment by MominIqbal-1234** [comment]
@ndonkoHenri  Please Explain how i install flutter

**Comment by ndonkoHenri** [comment]
https://docs.flutter.dev/get-started/install
