### ISSUE TITLE
Add Smooth Scrolling to Flet Windows App

### ISSUE THREAD

**Issue by ghost** [flet-dev/flet#2497]
**Problem To Be Solved**

Currently, when using the drag scroll bar in Flet, the scrolling behavior is smooth and provides a good user experience. However, when scrolling by other means, the experience is not smooth, leading to a less than optimal user experience.

**In-Scope**

Implement smooth scrolling for Flet when using methods other than the drag scroll bar. It is important to note that this issue is specific to the Windows app, and the web app is not affected by this behavior.

**Comment by baebranch** [comment]
+1

**Comment by ndonkoHenri** [comment]
Please share a visual output of the scrolling issue.

**Comment by baebranch** [comment]
https://github.com/flet-dev/flet/assets/66740223/82141e0c-06b2-4a58-b2d1-ca16e1aabdb7

The mouse wheel scrolling is smooth and can scroll continuously but with the trackpad, scrolling is limited to just a few lines in any one direction per touch, then I have to lift my fingers off of the trackpad and touch it again to scrolling another few lines. This problem doesn't exist on the web app for me as well.

**Comment by anamite** [comment]
+1

**Comment by azhago** [comment]
+1
Scrolling one line at a time with touchpad on desktop windows app.
Scroll is ok with mouse wheel (in all cases) or when using webapp

**Comment by ndonkoHenri** [comment]
Please give the latest Flet version a try.

**Comment by baebranch** [comment]
Trackpad scrolling works really well. Nice job.
