### ISSUE TITLE
I was using flet to build an apk file by the command "flet build apk -vv ". But it threw the following errors:

### ISSUE THREAD

**Issue by JustKen-Aristotle** [flet-dev/flet#2498]
flet build apk -vv    
Flutter bootstrap directory: C:\Users\notar\AppData\Local\Temp\flet_flutter_build_BMvPfRFlpx
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying E:\Shehzad\Programming\Rose Elon\MYapp\assets\icon.png to C:\Users\notar\AppData\Local\Temp\flet_flutter_build_BMvPfRFlpx\images
OK
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "F:\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "F:\Lib\site-packages\flet\cli\commands\build.py", line 518, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "F:\Lib\site-packages\flet\cli\commands\build.py", line 731, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "F:\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by 09u2h4n** [comment]
Did you run as a Administrator?

**Comment by taaaf11** [comment]
@JustKen-Aristotle did it work when you ran as administrator?

**Comment by JustKen-Aristotle** [comment]
> @JustKen-Aristotle did it work when you ran as administrator?

Well, it needed a thing more I found here:
https://github.com/flet-dev/flet/issues/2318#issuecomment-1881506010

**Comment by Mr-KAM** [comment]
Hi @JustKen-Aristotle ! Try first to update flet with `pip install --upgrade flet`.
After that be sure that you have all required installed with `flutter doctor`.

If you still have the same problem with the command `flet build apk --verbose` just :

1. open the cli build.py file of flet. In you case you can run the command `start F:\Lib\site-packages\flet\cli\commands\build.py` 
2. edit the method **run** of the class **Command**.  Add the parameter shell to `subprocess.run()` and set it to True in line **820** 
3. save the  code and run `flet build apk --verbose` again. 

the method to edit look lik this
```python
    def run(self, args, cwd, capture_output=True):
        if is_windows():
            # Source: https://stackoverflow.com/a/77374899/1435891
            # Save the current console output code page and switch to 65001 (UTF-8)
            previousCp = windll.kernel32.GetConsoleOutputCP()
            windll.kernel32.SetConsoleOutputCP(65001)

        if self.verbose > 0:
            print(f"\nRun subprocess: {args}")

        r = subprocess.run(
            args,
            cwd=cwd,
            capture_output=capture_output,
            text=True,
            encoding="utf8",
            shell=True
        )
```

**Comment by julian-irwin-tfs** [comment]
Hello, I am reporting that I just ran into this issue today with Python 3.12 on Windows 11, Flet 0.23.2. Renaming the dart and flutter files fixed the problem.

**Comment by ndonkoHenri** [comment]
Renaming which Flutter file?

**Comment by julian-irwin-tfs** [comment]
Sorry, I got confused about which thread I was posting too. I had to follow this comment:

https://github.com/flet-dev/flet/issues/2318#issuecomment-1881506010
