### ISSUE TITLE
Bug report template update

### ISSUE THREAD

**Issue by taaaf11** [flet-dev/flet#2509]
I think there should be a section for `requirements.txt` in the `Bug Report` template of creating a new issue, since, most issues are related to `requirements.txt`.

**Comment by FeodorFitsner** [comment]
Would you do a PR: https://github.com/flet-dev/flet/blob/main/.github/ISSUE_TEMPLATE/bug_report.md ? ;)

**Comment by taaaf11** [comment]
@FeodorFitsner made the pr, awaiting for your review 🥇

**Comment by taaaf11** [comment]
Closing issue since pr is merged
