### ISSUE TITLE
flet build apk -vv is not working ever since i have started using flet

### ISSUE THREAD

**Issue by New19User** [flet-dev/flet#2511]
Every single time i run flet build apk -vv, it always ended up in this "Error building flet app -see log of failed command"

This has been happening for the **past 3 weeks** since i came across flet. I have tried on in the vs code console, in my command prompt, and also in command prompt as an admin. 

i have also even tried "**flet build -v apk**"  and also the usual command "**flet build apk**'

Please i really need help, cos if this should continue like this, i will just dedicate to learn dart and then utilize flutter, 
but honestly speaking, i seriously don;t want that to occur, cos almost most of my favorite libraries are in python.

**I just want to see flet grow.  It has potential.**

Also how do i get to see the "log of failed command"

Thanks i really appreciate any help on this
![build failed](https://github.com/flet-dev/flet/assets/130806630/27ab6b70-ee64-42a2-a579-1ca2388c477c)

**Comment by ndonkoHenri** [comment]
I also suggest you go through the complete [guide](https://flet.dev/docs/guides/python/packaging-app-for-distribution) once more, because it has received alot of updates in the past days as a result of dev feedbacks.

Then try once more but this time with a simple hello world app.

**Comment by juanchos0412** [comment]
I have the same problem, i just tried as documentation says but i have the error when use "flet build apk" and "flet build windows" command. I have installed flutter 3.16.9 and "dart", "flutter" commands is working correctly. This is the error:

```
Because every version of flutter from sdk depends on sky_engine from sdk which doesn't exist (could not find package sky_engine
in the Flutter SDK), flutter from sdk is forbidden.
So, because pruebaflet depends on flutter from sdk, version solving failed.


Error building Flet app - s
```

**Comment by New19User** [comment]
> I also suggest you go through the complete [guide](https://flet.dev/docs/guides/python/packaging-app-for-distribution) once more, because it has received alot of updates in the past days as a result of dev feedbacks.
> 
> Then try once more but this time with a simple hello world app.


I followed the official installation guide of flutter, still yet,. it is not working.

I guess this is the problem

Extracting Python distributive from C:\Users\ENGR~1.BIG\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\ENGR~1.BIG\AppData\Local\Temp\hostpython3.11_c15683ba
**Error: ProcessException: The system cannot find the file specified.**

It can't find the file it created since this was created in a temp folder, i believe if they can allow us to specify a folder that will be used for building apk instead of the the temp folder, this kind of thing could be prevented. I hope they can implement this in their latest update. 

I just have to pause developing with flet for now until maybe i see a new update.

**Comment by lekshmanmj** [comment]
please share content of your requirements.txt
