### ISSUE TITLE
Grey Window Displayed Instead of HTTP Server Content in Flet WebView

### ISSUE THREAD

**Issue by zischu** [flet-dev/flet#2517]
**Description**
When attempting to display a plotly Mesh3D plot from a local HTTP server in a Flet WebView widget, the WebView only shows a grey window instead of the expected HTML content. The same behavior when i try to enter (for example) "www.google.com" through the webview.

**Code example to reproduce the issue:**

```python
import flet as ft
import plotly.graph_objects as go
import trimesh
import threading
import http.server
import socketserver

def serve_plotly_html(html_content, port=8080):
    class Handler(http.server.SimpleHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            self.wfile.write(html_content.encode('utf-8'))

    with socketserver.TCPServer(("", port), Handler) as httpd:
        httpd.serve_forever()

def create_plot_html():
    # Load STL file using trimesh
    mesh = trimesh.load('hello_text.stl')
    x, y, z = mesh.vertices[:,0], mesh.vertices[:,1], mesh.vertices[:,2]
    i, j, k = mesh.faces[:,0], mesh.faces[:,1], mesh.faces[:,2]

    # Create 3D plot with Plotly
    fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z, i=i, j=j, k=k, color='lightblue', opacity=1)])
    return fig.to_html(include_plotlyjs='cdn')

def update_page(page: ft.Page, webview: ft.WebView):
    page.update()
    print("UPDATE")

def main(page: ft.Page):
    plot_html = create_plot_html()

    # Start HTTP server in a new thread
    server_thread = threading.Thread(target=serve_plotly_html, args=(plot_html,))
    server_thread.daemon = True
    server_thread.start()

    # Create WebView
    webview = ft.WebView(url='http://localhost:8080', expand=True, on_page_ended=lambda e: update_page(page, webview))
    page.add(webview)

    # Create a button
    btn_update = ft.FilledButton(text="Update Plot", on_click=lambda e: update_page(page, webview))
    page.add(btn_update)

    page.update()

if __name__ == '__main__':
    ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

**Describe the results you received:**

Instead of the Mesh3d plot i got just a grey screen without any error message in the console
![image](https://github.com/flet-dev/flet/assets/46517776/5de980f4-4158-4707-82df-970a6f9762f8)

When i try without the view=ft.AppView.WEB_BROWSER parameter i got these:
![image](https://github.com/flet-dev/flet/assets/46517776/f719a4a9-70e9-49ba-b953-1039d250c24b)

**Describe the results you expected:**
Here is what i expected in the webview:
![image](https://github.com/flet-dev/flet/assets/46517776/4673cd00-87f3-427d-8cbb-ba824f038ca4)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\simon.schulte\onedrive - gkn powder metallurgy\python\labeling\venv\lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages): **

```
plotly==5.18.0
flet==0.19.0
trimesh==4.0.10
```

**Operating system**:

Windows 10

**Additional environment details:**
As webbrowser i use Microsoft Edge Version 121.0.2277.83

**Comment by ndonkoHenri** [comment]
Webview is not yet available on web and desktop as mentioned in the [docs](https://flet.dev/docs/controls/webview).
