### ISSUE TITLE
`flet build macos` does not yield output if `--product` option is provided with a value different from project name

### ISSUE THREAD

**Issue by kspviswa** [flet-dev/flet#2525]
Issue : If I use `flet build macos` within the dir, everything works perfectly. However I proceed to customize the package using options for eg: 

```
flet build --project "projecA" --description "my awesome fletapp" --product "projectA" --company "Made by me with ❤️" --copyright "me @ 2024" --build-version "0.0.1" macos
```
the result either an empty dir under `build/macos` or simply the app folder doesn't exit.

OS : MacOS Sonama 14.3
Machine : Apple Macbook M2 Pro

**Comment by FeodorFitsner** [comment]
It's actually an interesting bug, which surfaced because you've misspelled `--project` name (`projecA`) ;)

**Comment by kspviswa** [comment]
It was meant to be an example name for this issue :) . I gave actual name in my execution. Also one thing to add is, I was able to get around by using `build-version`, `copyright`, `project`, `company` . Rest options like description etc are not found to be working, atleast for me while building mac app
