### ISSUE TITLE
Async flet event handler does not work.

### ISSUE THREAD

**Issue by taaaf11** [flet-dev/flet#2538]
**Code example to reproduce the issue:**

```python
import flet as ft


def main(page:ft.Page):
    async def button_click(e):
        page.controls.append(ft.Text("Hello!"))
        await page.update_async()
        
    page.add(ft.ElevatedButton("Say hello!", on_click=button_click))


ft.app(main)
```

**Describe the results you received:**
```
C:\Program Files\Python312\Lib\threading.py:1010: RuntimeWarning: coroutine 'main.<locals>.button_click' was never awaited
  self._target(*self._args, **self._kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Describe the results you expected:**

"Hello!" `Text` control added to `page`

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\Altaaf\AppData\Roaming\Python\Python312\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages): **
```flet```

**Operating system**:

```Windows 10 22H2
OS build: 19045.3930
```

**Additional environment details:**
Using vscode, trying flet example [Control Event Handlers](https://flet.dev/docs/guides/python/async-apps/#control-event-handlers) second example

**Comment by taaaf11** [comment]
Sorry for the inconvenience. I solved the issue by making the `main` function `async` and adding the elevated button by `await page.add_async`. The whole code is:

```python
import flet as ft


async def main(page:ft.Page):
    async def button_click(e):
        page.controls.append(ft.Text("Hello!"))
        await page.update_async()
        
    await page.add_async(ft.ElevatedButton("Say hello!", on_click=button_click))


ft.app(main)
```

**Comment by taaaf11** [comment]
@FeodorFitsner I think this `main` function block should be added to [Control Event Handlers](https://flet.dev/docs/guides/python/async-apps/#control-event-handlers) second example, in order to avoid further confusions.

**Comment by FeodorFitsner** [comment]
Sure, why not!
