### ISSUE TITLE
`Dropdown` menu shows black background color on Android mobiles

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2560]
**Description**

**Code example to reproduce the issue:**

```python
    status_search=ft.Dropdown(
        label='Status',
        width=150,
        color=ft.colors.GREY_700,
        bgcolor=ft.colors.WHITE,
        border_color=ft.colors.GREY_700,
        border_width=1,
        hint_text='  Status',
        hint_style=ft.TextStyle(size=12,color=ft.colors.GREY_700,weight="BOLD",font_family='Tahoma'),
        text_style=ft.TextStyle(size=12,color=ft.colors.GREY_700,font_family='Tahoma'),
        dense=True,
        filled=True,
        border_radius=1,
        content_padding=4,
        alignment=ft.alignment.center_left,
        options=[
            ft.dropdown.Option('Todos'),
            ft.dropdown.Option('Pendente'),
            ft.dropdown.Option('Andamento'),
            ft.dropdown.Option('Finalizado'),
        ],
        on_change=inputsearch,
        autofocus=True
        )
PS: Do not consider the input search option.
This does not affect reproduction of the issue
```

**Describe the results you received:**

The background color of the background window remains black, even when changing the background color, both in the dropdown options and when using Container .-
Describe in text or paste a screenshot.
-->

**Describe the results you expected:**
I expected that the color of the background window would change when a set a specific color background  in bgcolor option.

![image](https://github.com/flet-dev/flet/assets/149313965/2530a10a-eb69-4a35-b97e-d491abd64bfe)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
Version 0.18.0
```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:
Android

**Additional environment details:**
App executed on replit and  flet app emulator

**Comment by ndonkoHenri** [comment]
A pre-release with the fix concerning this issue is now available. Try it and report if you face any further issues or have any questions:
```bash
pip install flet --pre
```
