### ISSUE TITLE
`Video` control

### ISSUE THREAD

**Issue by danielgafni** [flet-dev/flet#257]
Might be related to #235 #237

**Comment by tcye** [comment]
+1 very important for developping some multimedia app

**Comment by pastorhudson** [comment]
+ 1 I would love to use this for some simple media apps.

**Comment by FeodorFitsner** [comment]
It looks like the video is currently supported on web, iOS and Android platforms only: https://pub.dev/packages/video_player

**Comment by Skquark** [comment]
After searching all the available Flutter video players, the best on I found is https://pub.dev/packages/flutter_meedu_videoplayer which is compatible on all platforms except desktop MacOS.  It's fairly easy to call and use, and covers most demands, except playing YouTube.  Doesn't look too difficult to implement an adapter... There are a bunch of other vid player addons, but they're compatible with less platforms.

**Comment by cbenhagen** [comment]
There is also https://pub.dev/packages/video_player_macos which is based on the official iOS plugin.

**Comment by CYCNO** [comment]
yes really need for video player or iframe in flet officially

**Comment by adampiskorski** [comment]
> After searching all the available Flutter video players, the best on I found is https://pub.dev/packages/flutter_meedu_videoplayer which is compatible on all platforms except desktop MacOS. It's fairly easy to call and use, and covers most demands, except playing YouTube. Doesn't look too difficult to implement an adapter... There are a bunch of other vid player addons, but they're compatible with less platforms.

In order to get the code to run on some platforms, the plugin needs to be 120MB in size: https://github.com/zezo357/flutter_meedu_videoplayer/issues/30, and I suspect that this is will be a common problem.
I'm wondering if webview #432 may solve this problem, as once you have that, then JS solutions for playing video files will be fully cross-platform and tiny in size, and flet can have a convenience sub-class of webview with the js already included.

**Comment by adampiskorski** [comment]
> I'm wondering if webview #432 may solve this problem, as once you have that, then JS solutions for playing video files will be fully cross-platform and tiny in size, and flet can have a convenience sub-class of webview with the js already included.

A followup regarding the webview solution, if flet implements https://pub.dev/packages/flutter_widget_from_html_core (all platforms supported) to resolve #432, then you can implement the fwfh_chewie extension of it for video, and even though it only lists android and ios as supported, it clearly works on web: https://demo.fwfh.dev/#/video, so I suspect it will work wherever the core package does, as it doesn't say anything otherwise.

**Comment by ndonkoHenri** [comment]
And what about desktop?

**Comment by adampiskorski** [comment]
> 

flutter_widget_from_html_core supports MacOS, Windows and Linux, so I suspect that the video plugin does as well, although I'm not sure.

**Comment by forddata** [comment]
+1 building a kiosk media app, with a need for background video behind text

**Comment by hokaso** [comment]
Currently, is there just one method of using OpenCV for exhibiting videos in flets? Is anyone working on developing relevant functionalities? If there is, I'd be interested in offering my assistance.

**Comment by FeodorFitsner** [comment]
A new Flutter library for playing video on all platforms: https://github.com/wang-bin/fvp

**Comment by tcye** [comment]
Any progress? Still waiting for this function

**Comment by kumaraguru1735** [comment]
Need https://pub.dev/packages/video_player_web_hls for flut

**Comment by chrsbats** [comment]
> > After searching all the available Flutter video players, the best on I found is https://pub.dev/packages/flutter_meedu_videoplayer which is compatible on all platforms except desktop MacOS. It's fairly easy to call and use, and covers most demands, except playing YouTube. Doesn't look too difficult to implement an adapter... There are a bunch of other vid player addons, but they're compatible with less platforms.
> 
> In order to get the code to run on some platforms, the plugin needs to be 120MB in size: [zezo357/flutter_meedu_videoplayer#30](https://github.com/zezo357/flutter_meedu_videoplayer/issues/30), and I suspect that this is will be a common problem. I'm wondering if webview #432 may solve this problem, as once you have that, then JS solutions for playing video files will be fully cross-platform and tiny in size, and flet can have a convenience sub-class of webview with the js already included.

The meedu player has been discontinued and has been replaced by https://pub.dev/packages/media_kit - which could be a better option?

**Comment by FeodorFitsner** [comment]
`media_kit` looks great! All platforms! Video! Audio! To good to be true, huh. 🥹

**Comment by kumaraguru1735** [comment]
Expecting soon...
