### ISSUE TITLE
update or update_async need ignore `self.page is None`

### ISSUE THREAD

**Issue by d-o0o-b** [flet-dev/flet#2570]
**Description**

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Invalid issue !
Please provide necessary details.
