### ISSUE TITLE
list tile data attribute is not getting propagated to on_click event

### ISSUE THREAD

**Issue by asagarshinde** [flet-dev/flet#259]
```
import flet
from flet import Text, padding, Page, ListTile


def main(page: Page):
    def on_click(value):
        print(value.__dict__)

    t1 = ListTile(
                selected=False,
                data="shops",
                title=Text("Shops"),
                content_padding=padding.symmetric(horizontal=16),
                on_click=on_click,
            )
    t2 = ListTile(
                selected=False,
                data="apartments",
                title=Text("Apartments"),
                content_padding=padding.symmetric(horizontal=16),
                on_click=on_click,
            )

    page.add(t1)
    page.add(t2)

flet.app(target=main)
```

when I clicked on the first tile output of the event is 

{'target': '_2', 'name': 'click', **'data': '**', 'control': <flet.list_tile.ListTile object at 0x7fb3251165e0>, 'page': <flet.page.Page object at 0x7fb325131cd0>}

after that, I clicked on the second tile 

{'target': '_7', 'name': 'click', **'data': '',** 'control': <flet.list_tile.ListTile object at 0x7fb325116670>, 'page': <flet.page.Page object at 0x7fb325131cd0>}

Even though I set the data attribute in the list tile it is not propagated to on click event. because of this unable to identify from which tile event is coming

**Comment by nasoma** [comment]
What do you get with:
`print(value.control.__dict__)`

**Comment by FeodorFitsner** [comment]
Use `value.control.data`:

```python
    def on_click(e):
        print(e.control.data)
```

**Comment by asagarshinde** [comment]
Thank you, above works

**Comment by asagarshinde** [comment]
> What do you get with: `print(value.control.__dict__)`

It will give all the attributes of the object
