### ISSUE TITLE
On building to windows/apk , app displays module not found error

### ISSUE THREAD

**Issue by vishnu-rvb** [flet-dev/flet#2611]
**Description**

I have a flask server that is running on the url 'http://192.168.0.103:5000' in which i intent to send http request. 
during Flet run command the app runs without any issue and  building for windows or android apk  is also a success, but when running the built file module not found error is seen.
I have tried to place requests module folder directly into the root but now same error but different module is occurring.

```python
import flet as ft
from ast import literal_eval as str2lst
import requests
def main(page: ft.Page):
    page.title='Server client test'
    row=ft.TextField(label='Enter Row',value='')
    value=ft.TextField(label='Enter value',value='')
    btn=ft.ElevatedButton(text='update')
    page.add(row,value,btn)
    def update(e):
        r=int(row.value)
        l=str2lst(value.value)
        url = 'http://192.168.0.103:5000'
        response= requests.put(url+'/update',
                               json={'row':r,'value':l})
        page.add(ft.Text(f'{response.text}'))
    btn.on_click=update

ft.app(main)
```
**Error on executing the built windows executable:**

**Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Temp\serious_python_tempcd05a39c\main.py", line 3, in <module>
  File "C:\Users\User\AppData\Local\Temp\serious_python_tempcd05a39c\requests\__init__.py", line 43, in <module>
ModuleNotFoundError: No module named 'urllib3'
**

**Describe the results you expected:**
Image during Flet run

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\program files\python310\lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
```

**Requirements:**

```
requests 2.31.0
```

**Operating system**:

Windows 10

**Comment by lekshmanmj** [comment]
please try once just by having ```requests``` in requirements.txt

**Comment by sertemo** [comment]
i'm having the same issue while running `flet build windows`.
I used poetry as dependency manager and it seems its not finding the dependencies installed.
I've triied with erasing the version name of the dependencies in my requirements.txt and leaving just 3:

- flet
- python-docx
- pytz

But I find the same issue.

**Comment by tyu1996** [comment]
This problem is still happening when I build Windows app that has additional third-party Python libraries in the source code. Using the latest version of flet to date (0.22.1).

**Comment by EmmanuelMMontesinos** [comment]
I had a similar problem, and I solved it thanks to this comment --> [Issue 2714](https://github.com/flet-dev/flet/issues/2714#issuecomment-2101821519)

As it was a bit tedious, I decided to make a small tool to load dependencies to the windows builds (if you want to take a look).
[Flet Packages Loader](https://github.com/EmmanuelMMontesinos/Flet-Packages-Loader)

**Comment by vishnu-rvb** [comment]
Able to build with flet>=0.24.1 version itself and include` requests` in requirements.txt
