### ISSUE TITLE
Add DataColumn content alignment

### ISSUE THREAD

**Issue by bioxakep** [flet-dev/flet#2622]
`table = ft.DataTable(
            columns=[
                ft.DataColumn(ft.Row(controls=[
                        ft.Text(value='ID', text_align=ft.TextAlign.CENTER)
                    ], alignment=ft.alignment.center)
                ),
                ft.DataColumn(ft.Container(ft.Text(value='Имя'), alignment=ft.alignment.center)),
            ],
            rows=data_rows,
            expand=True,
            column_spacing=10,
        )`

In this example we see tries to set text of column in center of them.
But it does'n works.
In DataRows, this method works.
This is fix or bug?

**Comment by ndonkoHenri** [comment]
You mean vertically align the content of a column-header?

**Comment by bioxakep** [comment]
I mean horizontal align the content of a column-header (DataColumn element of DataTable).

**Comment by ndonkoHenri** [comment]
> `ft.Row(controls=[ ft.Text(value='ID', text_align=ft.TextAlign.CENTER) ], alignment=ft.alignment.center)`

Please read `Row.alignment` docs [here](https://flet.dev/docs/controls/row#alignment). Instead of `ft.alignment.center`, try `MainAxisAlignment.CENTER` instead.

**Comment by bioxakep** [comment]
Yes, works. Thanks.
