### ISSUE TITLE
Running on Google Colab python notebook

### ISSUE THREAD

**Issue by Skquark** [flet-dev/flet#263]
Trying to use this as frontend for Google Colab notebook, and mostly got it working, but when I open the app URL, which I had to mod to get the Colab runtime url since it shows 127.0.0.1, I get the logo animating in, I get excited, then it says "Please wait while the application is re-connecting..."  and spins.  Using the sample app code, here's what I'm running: 
```py
use_port = 22207
from google.colab.output import eval_js
print("Open this URL: " + eval_js(f"google.colab.kernel.proxyPort({use_port})"))
flet.app(target=main, view=flet.WEB_BROWSER, port=use_port)
```
What am I doing wrong, or doesn't support Colab Jupyter ipynb yet?  This is perfect for what I'm working on being a Flutter dev who now has to put up with ugly looking AI projects.

The URL it opens with is the *-port.googleusercontent.com one that it makes based on the port & session.  So when the above code is ran, this is the output:
```Open this URL: https://dgrtrbc4dd-496ff2e9c6d22116-22207-colab.googleusercontent.com/
WARNING:websocket:websocket connected
App URL: http://127.0.0.1:22207
Connected to Flet app and handling user sessions...
```
I imagine the reason it can't connect is the code is trying to communicate to local 127.0.0.1 instead of the virtual server's address.

Here's a share of my very simple Colab notebook, it's very barebone, but might save you time if you wanted to debug.  Works on Google Colab free, but I have Pro.  https://colab.research.google.com/drive/1FLNB7DnoegqBx2nn41LD1BS9rza5CzZj

Seems like it wouldn't be difficult to get working since it does start up, but it's probably looking for the wrong host address/port to communicate with in the Flet code. For one, instead of using the :port syntax, Google creates a proxy port address for security. Flet also thinks the address points to local host instead of the generated address that it runs on. Ideally there should be an extra parameter to call flet.app(host="https..." to assign manually, or in the source have it check if google.colab to then use kernel.proxyPort instead. Shouldn't be difficult, it works with most other python WebUI frameworks currently, but I really want to use this one, and so would many other Colab and Jupyter Notebook users.. Any thoughts?

**Comment by rjadr** [comment]
I just had to remove the line `ngrok.api_request()` in your colab and the app ran flawlessly!
