### ISSUE TITLE
Automatic notification when the app is brought to the front (Android, Windows, iOS)

### ISSUE THREAD

**Issue by mottibz** [flet-dev/flet#2631]
It will help a lot to have the functionality in which the app (in Windows, Android, iOS) will be automatically notified when the phone/PC wakes up after a sleep and the app is brought to the front, or when the app is brought to the front during regular operation.
This will allow the app to automatically update the UI at this point with the latest information.
Thanks!

**Comment by mottibz** [comment]
Any update on this?
This is a very important feature!

**Comment by FeodorFitsner** [comment]
https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html
