### ISSUE TITLE
failed to run `flet build windows`

### ISSUE THREAD

**Issue by d-o0o-b** [flet-dev/flet#2632]
## Environment

Platform: windows 11
Python version: 3.11.7(conda environment)
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (3 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

## Description:

I want to try this feature to build my application for windows.  So I use command `flet create app` to create a simple project, then run `flet build windows`. It's output look like this:

## Log

所在位置 行:1 字符: 1
+ cd .\app\
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\develop\com....ackage\app\app\:String) [Set-Location], ItemNotFoundExce 
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flet build windows
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...OK
Building Windows app...Resolving dependencies...
  ffi 2.1.0 (2.1.2 available)
  fl_chart 0.65.0 (0.66.2 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_native_splash 2.3.7 (2.3.10 available)
  js 0.6.7 (0.7.0 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.12.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  web 0.3.0 (0.5.0 available)
  web_socket_channel 2.4.0 (2.4.3 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
17 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...
Building Windows application...                                  2,171ms

Argument cannot be null or empty
参数名: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1

Unable to generate build files

Error building Flet app - see the log of failed command above.
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flet build windows --template-ref 0.20.0 -vv
Flutter bootstrap directory: C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying D:\develop\com.alex\flet_study\package\app\assets\icon.png to
C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr\images
OK
Generating app icons...  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies in C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr... (4.4s)
Got dependencies in C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr.
Building package executable... (1.8s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Packaging Python app...Building package executable... (1.1s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr\app
Copying Python app from D:\develop\com.alex\flet_study\package\app to C:\Users\28319\AppData\Local\Temp\serious_python_temp9d6f8ff1
Installing dependencies [flet-embed] with pip command to C:\Users\28319\AppData\Local\Temp\serious_python_temp9d6f8ff1\__pypackages__
Extracting Python distributive from C:\Users\28319\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\28319\AppData\Local\Temp\hostpython3.11_5b4648c8
Compiling Python sources at C:\Users\28319\AppData\Local\Temp\serious_python_temp9d6f8ff1
Delete unnecessary files with extensions: [.py, .c, .h, .typed, .exe]
Delete unnecessary files and directories: [__pycache__, bin]
Creating app archive at C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr\app/app.zip from C:\Users\28319\AppData\Local\Temp\serious_python_temp9d6f8ff1
Deleting temp directory C:\Users\28319\AppData\Local\Temp\serious_python_temp9d6f8ff1
Deleting Python directory C:\Users\28319\AppData\Local\Temp\hostpython3.11_5b4648c8
OK
Building Windows app...['D:\\Application\\flutter3.16.9\\flutter\\bin\\flutter.BAT', 'build', 'windows']
Resolving dependencies... 
  ffi 2.1.0 (2.1.2 available)
  fl_chart 0.65.0 (0.66.2 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_native_splash 2.3.7 (2.3.10 available)
  js 0.6.7 (0.7.0 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.12.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  web 0.3.0 (0.5.0 available)
  web_socket_channel 2.4.0 (2.4.3 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
17 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Argument cannot be null or empty
参数名: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1

Building Windows application...                                  2,080ms
Unable to generate build files
Deleting Flutter bootstrap directory C:\Users\28319\AppData\Local\Temp\flet_flutter_build_BAIEKPATVr
Error building Flet app - see the log of failed command above.
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> python -m
Argument expected for the -m option
usage: D:\Application\anaconda\envs\hubdriver\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> python -V
Python 3.11.7
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flutter -V
Could not find an option or flag "-V".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flutter -v
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                      Print this usage information.
-v, --verbose                   Noisy logging, including all shell commands executed.
                                If used with "--help", shows hidden options. If used with "flutter doctor", shows
                                additional diagnostic information. (Use "-vv" to force verbose logging in those cases.)    
    --prefixed-errors           Causes lines sent to stderr to be prefixed with "ERROR:".
    --quiet                     Reduce the amount of output from some commands.
    --[no-]wrap                 Toggles output word wrapping, regardless of whether or not the output is a terminal.       
                                (defaults to on)
    --wrap-column               Sets the output wrap column. If not set, uses the width of the terminal. No wrapping occurs
                                if not writing to a terminal. Use "--no-wrap" to turn off wrapping when connected to a     
                                terminal.
-d, --device-id                 Target device id or name (prefixes allowed).
    --version                   Reports the version of this tool.
    --machine                   When used with the "--version" flag, outputs the information using JSON.
    --[no-]color                Whether to use terminal colors (requires support for ANSI escape sequences).
                                (defaults to on)
    --[no-]version-check        Allow Flutter to check for updates when this command runs.
                                (defaults to on)
    --enable-analytics          Enable telemetry reporting each time a flutter or dart command runs.
    --disable-analytics         Disable telemetry reporting each time a flutter or dart command runs, until it is
                                re-enabled.
    --suppress-analytics        Suppress analytics reporting for the current CLI invocation.
    --packages                  Path to your "package_config.json" file.

Local build selection options (not normally required):
    --local-engine-src-path     Path to your engine src directory, if you are building Flutter locally.
                                Defaults to $FLUTTER_ENGINE if set, otherwise defaults to the path given in your
                                pubspec.yaml dependency_overrides for sky_engine, if any.
    --local-engine              Name of a build output within the engine out directory, if you are building Flutter        
                                locally.
                                Use this to select a specific version of the engine if you have built multiple engine      
                                targets.
                                This path is relative to "--local-engine-src-path" (see above).
    --local-engine-host         The host operating system for which engine artifacts should be selected, if you are        
                                building Flutter locally.
                                This is only used when "--local-engine" is also specified.
                                By default, the host is determined automatically, but you may need to specify this if you  
                                are building on one platform (e.g. MacOS ARM64) but intend to run Flutter on another (e.g. 
                                Android).
    --local-web-sdk             Name of a build output within the engine out directory, if you are building Flutter        
                                locally.
                                Use this to select a specific version of the web sdk if you have built multiple engine     
                                targets.
                                This path is relative to "--local-engine-src-path" (see above).

Options for testing the "flutter" tool itself:
    --show-test-device          List the special "flutter-tester" device in device listings. This headless device is used  
                                to test Flutter tooling.
    --show-web-server-device    List the special "web-server" device in device listings.
    --ci                        Enable a set of CI-specific test debug settings.

Available commands:

Flutter SDK
  bash-completion   Output command line shell completion setup scripts.
  channel           List or switch Flutter channels.
  config            Configure Flutter settings.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  precache          Populate the Flutter tool's cache of binary artifacts.
  upgrade           Upgrade your copy of Flutter.

Project
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  build             Build an executable app or install bundle.
  clean             Delete the build/ and .dart_tool/ directories.
  create            Create a new Flutter project.
  drive             Run integration tests for the project on an attached device or emulator.
  gen-l10n          Generate localizations for the current project.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  test              Run Flutter unit tests for the current project.

Tools & Devices
  attach            Attach to a running app.
  custom-devices    List, reset, add and delete custom devices.
  daemon            Run a persistent, JSON-RPC based server to communicate with devices.
  debug-adapter     Run a Debug Adapter Protocol (DAP) server to communicate with the Flutter tool.
  devices           List all connected devices.
  emulators         List, launch and create emulators.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flutter --version
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (3 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> 
(hubdriver) PS D:\develop\com.alex\flet_study\package\app> flet build windows                          
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...OK
Building Windows app...Resolving dependencies...
  ffi 2.1.0 (2.1.2 available)
  fl_chart 0.65.0 (0.66.2 available)
  flet 0.19.0 (0.20.0 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_native_splash 2.3.7 (2.3.10 available)
  js 0.6.7 (0.7.0 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.12.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  web 0.3.0 (0.5.0 available)
  web_socket_channel 2.4.0 (2.4.3 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...
Building Windows application...                                  2,083ms

Argument cannot be null or empty
参数名: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1

Unable to generate build files

Error building Flet app - see the log of failed command above.

**Comment by FeodorFitsner** [comment]
Try creating file at `%appdata%\NuGet\NuGet.config` with the following contents and run `flet build windows` again:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by d-o0o-b** [comment]
## A new error 

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5):
warning MSB8029: �м�Ŀ¼�����Ŀ¼�޷�פ������ʱĿ¼�£���Ϊ����ܻᵼ���������ɳ������⡣
[C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\ZERO_CHECK.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5):
warning MSB8029: �м�Ŀ¼�����Ŀ¼�޷�פ������ʱĿ¼�£���Ϊ����ܻᵼ���������ɳ������⡣
[C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\plugins\serious_python_windows\CopyPytho
nDLLs.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5):
warning MSB8029: �м�Ŀ¼�����Ŀ¼�޷�פ������ʱĿ¼�£���Ϊ����ܻᵼ���������ɳ������⡣
[C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\flutter\flutter_assemble.vcxproj]       
  Error detected in pubspec.yaml:
  No file or variants found for asset: app/app.zip.hash.
C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066:
��C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\CMakeFiles\2306a2d06f54784e0c5a125c542d
054d\flutter_windows.dll.rule;C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\CMakeFiles\
3efcce3238d1809755f24c15598becec\flutter_assemble.rule�����Զ����������˳�������Ϊ 1��
[C:\Users\28319\AppData\Local\Temp\flet_flutter_build_vXSfsZRtBv\build\windows\x64\flutter\flutter_assemble.vcxproj]       
Build process failed.

Error building Flet app - see the log of failed command above.

**Comment by FeodorFitsner** [comment]
What version of Flet do you have. Please upgrade to the latest Flet 0.20.0.

**Comment by d-o0o-b** [comment]
Thank you! It's finger out!
