### ISSUE TITLE
There is a huge difference in the layout and font colors when I access my app with Flet.app and web browser

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2634]
**Description**

**Code example to reproduce the issue:**

```python
(paste your program here)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
flet_navigator
datetime
psycopg2
pandas
numpy
matplotlib
twilio
time
os
json
```

**Operating system**:

**Additional environment details:**

**Comment by jvalle63** [comment]
I don't know what happen. I mad all the description and uploaded several screenshots. They are not appearing...

**Comment by FeodorFitsner** [comment]
Yeah, need pictures.
