### ISSUE TITLE
`libmpv` errors on Linux

### ISSUE THREAD

**Issue by braboat** [flet-dev/flet#2637]
Any time I try to run my app with the latest version Flet (0.20.0) on Ubuntu (23.10), I get this error message:

 "error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory"

But if I run the same file with version (0.19.0) everything works.

**Comment by isaffathir** [comment]
Try this

`sudo apt install libmpv-dev mpv`

**Comment by FeodorFitsner** [comment]
Sorry about that!

Flet 0.20.0 includes a new `Video` control.

To test Flet apps on Linux, the [libmpv](https://mpv.io/) package must be installed. On Ubuntu/Debian you can install it with `sudo apt install libmpv-dev mpv`.

We are going to do optional Flet installation in the next releases.

**Comment by burhansvural** [comment]
> Any time I try to run my app with the latest version Flet (0.20.0) on Ubuntu (23.10), I get this error message:
> 
> "error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory"
> 
> But if I run the same file with version (0.19.0) everything works.

use this file https://drive.google.com/file/d/1mxYxhcCfigZ55xI9xT0ntd9f5QNSyfCD/view?usp=sharing place this file in the /usr/lib/ directory and then use the sudo ln -s /usr/local/lib/libmpv.so.1 /usr/lib/libmpv.so.1 command

**Comment by mvwilpe** [comment]
Did that (ln -s /usr/lib/libmpv.so.1 /usr/local/lib/libmpv.so.1)  but now I get: flet: error while loading shared libraries: libmujs.so.2: cannot open shared object file: No such file or directory

**Comment by burhansvural** [comment]
Have you installed the libmpv-dev, libmpv2, mpv and mpv-build-deps
libraries found in the package manager?

mvwilpe ***@***.***>, 16 Şub 2024 Cum, 12:30 tarihinde şunu
yazdı:

**Comment by burhansvural** [comment]
I'm sorry, you need to install the libmujs-dev and libmujs2 packages to fix
this error.

mvwilpe ***@***.***>, 16 Şub 2024 Cum, 12:30 tarihinde şunu
yazdı:

**Comment by mvwilpe** [comment]
Cannot find ibmujs2 (Unable to locate) . The rest was already installed.

**Comment by burhansvural** [comment]
https://answers.launchpad.net/ubuntu/lunar/amd64/libmujs2

mvwilpe ***@***.***>, 16 Şub 2024 Cum, 13:23 tarihinde şunu
yazdı:

**Comment by burhansvural** [comment]
https://answers.launchpad.net/ubuntu/lunar/amd64/libmujs2/1.3.2-1

mvwilpe ***@***.***>, 16 Şub 2024 Cum, 13:23 tarihinde şunu
yazdı:

**Comment by mvwilpe** [comment]
It finally works! However, after installing libmujs2, iIalso had to install libjpeg62 .

**Comment by burhansvural** [comment]
👍

17 Şub 2024 Cmt 12:13 tarihinde mvwilpe ***@***.***> şunu
yazdı:

**Comment by burhansvural** [comment]
👋

17 Şub 2024 Cmt 13:09 tarihinde Burhan Süleyman Vural <
***@***.***> şunu yazdı:

**Comment by braboat** [comment]
Finally working after installing: 
1. sudo apt install libmpv-dev mpv, 
2.[ libmujs2](https://answers.launchpad.net/ubuntu/lunar/amd64/libmujs2/1.3.2-1)
3. sudo apt-get install libjpeg62:i386

**Comment by rmpythoncode** [comment]
I tryed all above but still getting:
/home/rm/.flet/bin/flet-0.20.2/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
Debian 12
Does anyone hava an idea on how to work around this?

**Comment by initiateit** [comment]
There is no package for 23.10 (mantic) for [libmujs2](https://answers.launchpad.net/ubuntu/lunar/amd64/libmujs2/1.3.2-1)

**Comment by TazMania-Git** [comment]
Hello, I pass on my knowledge and how I was able to advance with the different libraries that Flet requests.
1 - in the case of libmujs https://www.reddit.com/r/archlinux/comments/1b0ywwn/flet_error_in_arch_linux/https://archlinux.org/packages/extra/x86_64/mujs/files/
        sudo ln -s /usr/local/lib/libmujs.so /usr/lib/libmujs.so.2
2 - then I had the error with the liblua5.2.so.0 lib, I did exactly the same thing as point 1 but with the lua libraries that I already had.
3- then I had problems with lib libuchardet.so.x, install uchardet
4- then lib libjpeg.so.62, I did what was in step 1 but modifying from another lib, example sudo ln -s /usr/lib/libjpeg.so.8 /usr/lib/libjpeg.so.62
5- then lib libsixel.so.1, install libsixel-1.10.3-5
6- then lib libxpresent, install libxpresent-1.0.1-1
7- stuck with this error:

```
.flet/bin/flet-0.21.1/flet/flet: /usr/lib/libjpeg.so.8: version `LIBJPEG_6.2' not found (required by /usr/lib/libmpv.so.1)
.flet/bin/flet-0.21.1/flet/flet: /usr/lib/liblua5.2.so.0: no version information available (required by /usr/lib/libmpv.so.1)
```

All in vain....

**Comment by rangergeronimo** [comment]
Hello, same issu as above, I have Flet (0.20.0), I when I try to run the code on ubuntu 23.10 I got the error below. 
I followed the thed tutorial on the oficial docs and in this page , nothing had worked though. Any other suggestion? 
PS: I'm ableto run wiht Flet 0.19.0
![Screenshot from 2024-03-31 07-19-04](https://github.com/flet-dev/flet/assets/32517318/71c8ca6e-06b0-459c-b072-6998ebbeb4fe)

**Comment by magowiz** [comment]
same here, thanks @rangergeronimo for the suggestion to use 0.19.0

**Comment by mak448a** [comment]
How do I get this working on Fedora Linux?

**Comment by SergNif** [comment]
sudo apt install libmpv-dev mpv libmujs2 libjpeg62

it's work for me
thank's all

**Comment by magowiz** [comment]
> sudo apt install libmpv-dev mpv libmujs2 libjpeg62
> 
> it's work for me on Ubuntu 23.10 thank's all

I have ubuntu 23.10, and I don't know how this could work for you since package `libmujs2` is not available at all in ubuntu 23.10, maybe you are running another version.

By the way I installed `libmujs2` using deb linked in this bug report, then I gave same exact comand you suggested:
`sudo apt install libmpv-dev mpv libmujs2 libjpeg62`

I updated flet to 0.22.0 and I got this other missing library error:
`.flet/bin/flet-0.22.0/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

Are you sure you are using ubuntu 23.10? Which version of libmujs2 are you using ? I installed `libmujs2_1.3.2-1_amd64.deb`, what about flet version?

**Comment by Phenixis** [comment]
Hey ! 

I've got the same problem: `error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`.

So, I followed the instructions. (the following screenshots are in French but they also say that the programs are already installed)
I have libmpv-dev and mpv installed :
![image](https://github.com/flet-dev/flet/assets/110108406/84a0541f-7712-4e3f-b884-ae44fff7102d)
I took the file libmpv.so.1 and put it into my `/usr/local/lib/` folder (on the right here). Then, I created a link between `/usr/local/lib/libmpv.so.1` and `/usr/lib/libmpv.so.1` and all the files `libmpv.so.2` are linked to the initial file `/usr/local/lib/libmpv.so.1`.
![image](https://github.com/flet-dev/flet/assets/110108406/3372e6be-3306-48a9-9ea0-fb365f401a18)

I also installed libmujs2 and libjpeg62 :
![image](https://github.com/flet-dev/flet/assets/110108406/de65ebad-f1ca-45f9-bed1-01ea12d74c39)
![image](https://github.com/flet-dev/flet/assets/110108406/c4a72ac8-c76e-4348-98c2-cb60e711ef30)

I use python 3.11 and flet 0.22.1, but the problem persists :
![image](https://github.com/flet-dev/flet/assets/110108406/4335f001-59bb-423f-8c67-ab73de83540e)

Have I done something wrong ?

**Comment by SergNif** [comment]
> Are you sure you are using ubuntu 23.10? Which version of libmujs2 are you using ? I installed `libmujs2_1.3.2-1_amd64.deb`, what about flet version?
> 


Yes, I`m sure. On my computer instaaled Ubuntu 23.10
I spent a lot of time looking for a solution to this problem. I performed some actions that I found in Google search. Maybe I installed some other package. Sorry, I can't give you the full details.

**Comment by brycepg** [comment]
The only workaround I found is to downgrade:

```pip install flet==0.19.0```

**Comment by mak448a** [comment]
> The only workaround I found is to downgrade:
> 
> `pip install flet==0.19.0`

Just use the symlinking method https://github.com/flet-dev/flet/issues/2637#issuecomment-2067801868 @brycepg

**Comment by brycepg** [comment]
> > The only workaround I found is to downgrade:
> > `pip install flet==0.19.0`
> 
> Just use the symlinking method [#2637 (comment)](https://github.com/flet-dev/flet/issues/2637#issuecomment-2067801868) @brycepg

Ok this is how to do the symlink on `Fedora`:
    
    sudo dnf install mpv-libs mpv-devel
    cd /usr/lib64
    sudo ln -s libmpv.so libmpv.so.1

**Comment by RomanSedykh** [comment]
> /usr/lib/x86_64-linux-gnu

Thanks. There is no such folders and libraries in my system, so the only solution that works is that one.

**Comment by RomanSedykh** [comment]
> The only workaround I found is to downgrade:
> 
> `pip install flet==0.19.0`


/usr/lib/x86_64-linux-gnu

Thanks. There is no such folders and libraries in my system, so the only solution that works is that one.

**Comment by mvwilpe** [comment]
The (only) things I had to do to get Flet working properly after installing Ubuntu 24.04 was:
1) sudo apt install libmpv-dev mpv
2) Download https://drive.google.com/file/d/1mxYxhcCfigZ55xI9xT0ntd9f5QNSyfCD/view?usp=sharing, place it in the /usr/local/ib/ directory and do sudo ln -s /usr/lib/libmpv.so.1 /usr/local/lib/libmpv.so.1
3) sudo apt install libjpeg62

I hopes this helps.

**Comment by mak448a** [comment]
Don’t download it. Just use the symlinking method above.

**Comment by DarexD** [comment]
Solution in Ubuntu: https://github.com/DarexD/Solution-libmpv.so-Flet

I don't know if it works in other distributions.

**Comment by lywschxd** [comment]
> Solution in Ubuntu: https://github.com/DarexD/Solution-libmpv.so-Flet
> 
> I don't know if it works in other distributions.

it's work in my ubuntu 24.04 LTS
