### ISSUE TITLE
Error (missing argument) when publishing flet app

### ISSUE THREAD

**Issue by przybjul** [flet-dev/flet#2641]
When I publish my flet app with command 'flet publish my_app.py' and ' python -m http.server --directory dist' I get a worning on the localhost console and my app is not displaying: "future: <PyodideTask finished name='Task-26' coro=<PyodideConnection.receive_loop() done, defined at /lib/python3.11/site-packages/flet/pyodide_connection.py:42> exception=TypeError("RegisterWebClientRequestPayload.__init__() missing 1 required positional argument: 'media'")>"

Is the command 'flet_publish' using always the newest version of flet?
If yes is it possible to use the old version?(some parameter)

windows 11 wsl2

**Comment by przybjul** [comment]
In file app.tar.gz flet older version is overitten with the newest flet version, so i managed to set there version to 19 in requirements file and it worked, so there must be an error in version 20

**Comment by FeodorFitsner** [comment]
The new Flet 0.20.0 came yesterday and it has some changes in the API.

Two ways to fix the issue you have:

1) Upgrade to the latest Flet 0.20.0 and build your app again:

```
pip install flet --upgrade
```

or, if you want to stay on Flet 0.19.0:

2) Pin `flet` dependency in `requirements.txt` to version 0.19.0:


```
flet==0.19.0
```
