### ISSUE TITLE
Struggling to build a web app using either Flet build or flet publish

### ISSUE THREAD

**Issue by kiebak3r** [flet-dev/flet#2649]
**Description**
I am trying to build an application into a web app, I have tried both methods to build; 
1. flet publish main.py --assets assets
2. flet build web (with flutter SDK installed)

**Code example to reproduce the issue:**

```python
import sqlite3
import flet as ft

# Variables
lost = False
p_width = 200
current = 0
p_height = 100


def main(page: ft.Page):
    # Establish a connection to the SQLite database
    conn = sqlite3.connect('assets/questions.db', check_same_thread=False)
    cursor = conn.cursor()

    def get_question(idx):
        return cursor.execute(f'SELECT question FROM quiz WHERE id = {idx}').fetchone()[0]

    # Page Configurations
    page.title = "Dobby Club Game"
    page.window_always_on_top = True
    page.theme_mode = "dark"
    page.window_min_width = 1920
    page.window_min_height = 1080
    page.window_width = 1920
    page.window_height = 1080

    # Prizes UI
    p_images = [
        'assets/prize.png',
        'assets/prize.png',
        'assets/prize.png',
        'assets/prize.png',
        'assets/prize.png',
        'assets/prize.png',
    ]

    prizes = [ft.Image(src=i, fit=ft.ImageFit.CONTAIN, width=p_width, height=p_height) for i in p_images]
    prizes_column = ft.Column(prizes, alignment=ft.MainAxisAlignment.SPACE_EVENLY)

    # Question UI
    start_prompt = cursor.execute('SELECT start FROM prompts').fetchone()[0]
    question_control = ft.Text(
        start_prompt,
        size=40,
        style=ft.TextThemeStyle.TITLE_LARGE,
        color=ft.colors.WHITE,
        bgcolor=ft.colors.BLACK,
        weight=ft.FontWeight.BOLD,
        italic=True,
        text_align=ft.TextAlign.CENTER,
    )
    question_column = ft.Container(question_control, alignment=ft.alignment.center)

    # Prize List UI
    prize_list_column = ft.Column(
        [],
        spacing=10,
        horizontal_alignment=ft.CrossAxisAlignment.CENTER,
    )

    # Bank UI with Prizes
    bank_column = ft.Container(
        content=ft.Column(
            [
                ft.Row(
                    [
                        ft.Image(src='assets/bank.png', width=100, height=100),
                    ],
                ),
                prize_list_column
            ],
            spacing=10,
            horizontal_alignment=ft.CrossAxisAlignment.CENTER,
        ),
        padding=ft.Padding(10, 10, 10, 10),
    )

    def correct_answer(e):
        global current, lost
        if lost:
            return

        if current == 0:
            question_control.value = get_question(current + 1)
            question_control.update()
            incorrect_button.disabled = False
            page.update()
        else:
            question_control.value = get_question(current)
            question_control.update()
            index = len(prizes) - current

            if index < len(prizes):
                prizes[index].src = 'assets/correct.png'
                prizes[index].update()
                prize_to_bank(current)
        current += 1

        if current > len(prizes):
            question_control.value = cursor.execute('SELECT win FROM prompts').fetchone()[0]
            question_control.update()
            prize_list_column.controls.append(
                ft.Image(
                    src='assets/victory_meme.jpg',
                    width=400,
                    height=200,
                    opacity=0.7,
                ),
            )
            prize_list_column.update()
            incorrect_button.disabled = True
            correct_button.disabled = True
            page.update()

    def incorrect_answer(e):
        global current, lost
        for p in prizes:
            if p.src != 'assets/correct.png':
                p.src = 'assets/incorrect.png'
                p.update()

        lost = True
        incorrect_button.disabled = True
        correct_button.disabled = True
        page.update()

        if current < 2:
            question_control.value = cursor.execute('SELECT first_question_fail FROM prompts').fetchone()[0]
            prize_list_column.controls.append(
                ft.Container(
                    ft.Image(
                        src='assets/first_question_fail.jpg',
                        width=400,
                        height=200,
                        opacity=0.7,
                    ),                    alignment=ft.alignment.center,
                )
            )
            question_control.update()
            prize_list_column.update()
            return

        question_control.value = cursor.execute('SELECT fail FROM prompts').fetchone()[0]
        prize_list_column.controls.append(
            ft.Container(
                ft.Image(
                    src='assets/wrong_answer_meme.jpg',
                    width=400,
                    height=200,
                    opacity=0.7,

                ),
                alignment=ft.alignment.center,
            )
        )
        question_control.update()
        prize_list_column.update()

    def prize_to_bank(idx: int):
        response = cursor.execute(f'SELECT prize FROM quiz WHERE id = {idx}').fetchone()[0]
        prize_list_column.controls.append(
            ft.Text(
                f'Prize {current}: {response}',
                size=20,
                color=ft.colors.WHITE,
                bgcolor=ft.colors.GREEN
            )
        )
        prize_list_column.update()

    incorrect_button = ft.IconButton(
        icon=ft.icons.CLOSE,
        icon_color=ft.colors.RED,
        tooltip='Incorrect',
        on_click=incorrect_answer,
        icon_size=50,
        disabled=True
    )

    correct_button = ft.IconButton(
        icon=ft.icons.CHECK,
        icon_color=ft.colors.GREEN,
        tooltip='Correct',
        on_click=correct_answer,
        icon_size=50,
    )

    # Main UI layout
    main_content = ft.Row(
        [
            bank_column,
            ft.Container(
                ft.Column(
                    [
                        question_column,
                        ft.Row(
                            [
                                incorrect_button,
                                correct_button,
                            ],
                            alignment=ft.MainAxisAlignment.CENTER,
                        ),
                        ft.Divider(opacity=0),
                        ft.Divider(opacity=0),
                        ft.Divider(opacity=0),
                    ],
                    scroll=ft.ScrollMode.HIDDEN,
                ),
                expand=True,
                alignment=ft.alignment.bottom_center,
            ),
            prizes_column,
            ft.VerticalDivider(opacity=0),
        ],
        expand=True,
    )

    main_body = ft.Container(
            main_content,
            expand=True,
            image_src='assets/bg.jpg',
            image_fit=ft.ImageFit.COVER,
            image_opacity=0.5,
            border_radius=ft.BorderRadius(5, 5, 5, 5),
        )

    page.add(main_body)


if __name__ == "__main__":
    ft.app(target=main, assets_dir='assets')

```

**Describe the results you received:**
Using .1 the build completes and i get the /dist folder but when trying to test it on localhost i get the following error in the console
![image](https://github.com/flet-dev/flet/assets/113192732/1b63bf83-4db6-4ef8-85b9-0b823eac32b8)
![image](https://github.com/flet-dev/flet/assets/113192732/b7cb7871-9543-402f-9918-5551e668a03b)

Using .2 i get the following error log;
flet build web
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Generating splash screens...OK
Packaging Python app...Running package command
Creating asset directory: C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_JmUIXDbZyk\app
Copying Python app from C:\Users\kbaker\Desktop\dobby-club-game to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempf6577f61
Configured emscripten_3_1_45_wasm32 platform with sitecustomize.py at C:\Users\kbaker\AppData\Local\Temp\serious_python_sitecustomize9c56c4e3\sitecustomize.py
Installing 'find-links' dependencies  with pip command to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempf6577f61\__pypackages__
Extracting Python distributive from C:\Users\kbaker\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\kbaker\AppData\Local\Temp\hostpython3.11_9582da11
Installing dependencies  with pip command to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempf6577f61\__pypackages__
Compiling Python sources at C:\Users\kbaker\AppData\Local\Temp\serious_python_tempf6577f61

Error building Flet app - see the log of failed command above.

**Describe the results you expected:**
 The website to be runnable.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.20.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\kbaker\desktop\dobby-club-game\.venv\lib\site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
sqlite3
```

**Operating system**:
Windows 11 23H2 22631.2507

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Could you please attached a more detailed build log of `flet build web -v`?

**Comment by kiebak3r** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

(.venv) PS C:\Users\kbaker\Desktop\dobby-club-game> flet build web -v
Flutter bootstrap directory: C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_fFddposRHu
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['C:\\Users\\kbaker\\Downloads\\flutter_windows_3.16.9-stable\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies in C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_fFddposRHu... (3.4s)
Got dependencies in C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_fFddposRHu.
Building package executable... (5.4s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['C:\\Users\\kbaker\\Downloads\\flutter_windows_3.16.9-stable\\flutter\\bin\\dart.BAT', 'run', 'flutter_native_splash:create']
Building package executable... (5.1s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['C:\\Users\\kbaker\\Downloads\\flutter_windows_3.16.9-stable\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package', 'C:\\Users\\kbaker\\Desktop\\dobby-club-game', '--web', '--dep-mappings',
'flet=flet-pyodide', '--req-deps', 'flet-pyodide,micropip', '--platform', 'emscripten_3_1_46_wasm32', '--find-links', 'C:\\Users\\kbaker\\AppData\\Local\\Temp\\flet_flutter_build_fFddposRHu\\find-links.html', '--exclude',       
'assets,build']
Building package executable... (3.0s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_fFddposRHu\app
Copying Python app from C:\Users\kbaker\Desktop\dobby-club-game to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e
Configured emscripten_3_1_46_wasm32 platform with sitecustomize.py at C:\Users\kbaker\AppData\Local\Temp\serious_python_sitecustomize37d1e86a\sitecustomize.py
Installing 'find-links' dependencies [micropip] with pip command to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e\__pypackages__
Extracting Python distributive from C:\Users\kbaker\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\kbaker\AppData\Local\Temp\hostpython3.11_204829b
Installing dependencies [flet-pyodide] with pip command to C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e\__pypackages__
Compiling Python sources at C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e
Deleting Flutter bootstrap directory C:\Users\kbaker\AppData\Local\Temp\flet_flutter_build_fFddposRHu
Error building Flet app - see the log of failed command above.

**Comment by kiebak3r** [comment]
i also traced the last path and opened C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e and tried to run the main.pyc and got;

 Microsoft Windows [Version 10.0.22631.2506]
(c) Microsoft Corporation. All rights reserved.

C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e>main.pyc
RuntimeError: Bad magic number in .pyc file

C:\Users\kbaker\AppData\Local\Temp\serious_python_tempe2fc26e>

**Comment by kiebak3r** [comment]
Thank you, i have managed to build it succesfully by matching the python version to 3.11.6 (i was using 3.12.2)

I tried to run it on the local host now using python -m http.server --directory build/web but i am seeing the console error 
![image](https://github.com/flet-dev/flet/assets/113192732/971416c5-c580-42d7-9197-6deb37ef3cb7)
![image](https://github.com/flet-dev/flet/assets/113192732/59e6b566-4060-4e2f-992c-d9c319d57200)

Any ideas?

**Comment by kiebak3r** [comment]
the python.js in the build/web appears differently than to what is shown in the console const pythonWorker = new Worker("python-worker.js");

let _onPythonInitialized = null;
let pythonInitialized = new Promise((onSuccess) => _onPythonInitialized = onSuccess);
let _onReceivedCallback = null;

pythonWorker.onmessage = (event) => {
    if (event.data == "initialized") {
        _onPythonInitialized();
    } else {
        _onReceivedCallback(event.data);
    }
};

documentUrl = document.URL;

// initialize worker
pythonWorker.postMessage({ documentUrl, pythonModuleName });

async function jsConnect(receiveCallback) {
    _onReceivedCallback = receiveCallback;
    await pythonInitialized;
    console.log("Python engine initialized!");
}

async function jsSend(data) {
    pythonWorker.postMessage(data);

**Comment by FeodorFitsner** [comment]
Idk, `python.js` from your screenshot looks outdated. Could be browser cache. Try running in Private browser session.

Try deleting cookiecutter cache with `rm -rf ~/.cookiecutters` and re-build again.

**Comment by kiebak3r** [comment]
Issue was resolved by following both steps. This thread can now be closed. Thank you :)
