### ISSUE TITLE
Error Running App after building for windows

### ISSUE THREAD

**Issue by gitmatsika** [flet-dev/flet#2651]
### Description
Have build a text app on windows and build in on windows and is throwing an error after successfully building

### Environment
Flet 0.19
Windows 10,
Python -  3.11
vscode
requirement file - flet 
### Testing

Flet run produced the following
![image](https://github.com/flet-dev/flet/assets/99650624/587a482c-f75d-4b6e-8fbb-7798159ef274)

### Code example
![image](https://github.com/flet-dev/flet/assets/99650624/2dab39bf-8abe-44a6-8093-57377d65073a)

### Error
![image](https://github.com/flet-dev/flet/assets/99650624/c259a745-dd7c-49b7-a4f4-52d4e2441ab1)

### Build Command
flet build windows

**Comment by FeodorFitsner** [comment]
Upgrade Flet to the latest 0.20.0 and re-build the app.

**Comment by gitmatsika** [comment]
Let .20 not working both on Windows and Linux. Have specificed flet 0.19 in requirements file and its now working and have tested both with serious_python 0.70 and its working.
Thanks for the update.
