### ISSUE TITLE
`Video` v2

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#2653]
- [x] `show_controls` Boolean prop
- [x] get video information (duration, position etc)
- [x] Subtitles

**Comment by Harfgang** [comment]
I use a command "flet build apk"

**Comment by bobwatcherx** [comment]
![image](https://github.com/flet-dev/flet/assets/52072811/6a27f31b-ebd2-4073-add8-6bd9bc684320)
What if I click the button to increase the video duration by 10 seconds, next and previous. is there an example of the code?

**Comment by dhelbegor** [comment]
Suggestion.

What about support for subtitles. Like a .vtt file?
It would be great if the feature supports either path or href for the .vtt file too.

I found this example in the repository of media_kit. Maybe it can help :D.
https://github.com/media-kit/media-kit?tab=readme-ov-file#select-video-audio-or-subtitle-track

Basic examples
html
```html
<!DOCTYPE html>
<html>
<head>
  <title>Vídeo com Legendas</title>
</head>
<body>
  <video controls>
    <source src="video.m3u8" type="application/x-mpegURL">
    <track src="legendas.vtt" kind="subtitles" srclang="pt" label="Português">
    Seu navegador não suporta o elemento de vídeo.
  </video>
</body>
</html>
```

react native
```js
import React from 'react';
import { View, Text } from 'react-native';
import Video from 'react-native-video';

const App = () => {
  return (
    <View>
      <Video
        source={{ uri: 'https://example.com/video.m3u8' }}
        style={{ width: 300, height: 300 }}
        controls
        autoplay
      />
      <Text>Legendas</Text>
      <Video
        source={{ uri: 'https://example.com/legendas.vtt' }}
        style={{ width: 0, height: 0 }}
        textTracks={[
          {
            title: 'Português',
            language: 'pt',
            type: 'text/vtt',
            uri: 'https://example.com/legendas.vtt',
          },
        ]}
        selectedTextTrack={{ type: 'language', value: 'pt' }}
      />
    </View>
  );
};

export default App;
````

**Comment by dhelbegor** [comment]
Suggestion.

Support for pause when clicking directly on the video.

I'm using the web version of flet. If I want to play/pause the video I have to click directly on the play button(located at the bottom left of the video). Would be great to have the option to click play/pause.

**Comment by dhelbegor** [comment]
Thank you very much  :D

**Comment by ndonkoHenri** [comment]
The related PR hasn't yet been merged.
