### ISSUE TITLE
SearchBar example doesn't work properly in Flet 0.20.0

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2655]
I simply copied the SearchBar example in the documentation and ran it.  The on_submit (press Enter key)  and on_change  functions don't work.  

In the online documentation

```python
(paste your program here)
```

on_submit (press ENTER key)  and on_change functions make no response

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Flet 0.20.0

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

Windows 11, Python 3.12.1

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
You mean, this worked in the previous version, but now, no more?

**Comment by ndonkoHenri** [comment]
Closing as duplicate of #2251!!
