### ISSUE TITLE
Add the ability to change the icon without building

### ISSUE THREAD

**Issue by YouCantCMe** [flet-dev/flet#2656]
(I'm developing my program on Windows for context)

I'd like to be able to change the icon without building an EXE. This is a feature that other GUI libraries on Windows support such as Tkinter and PyQt5. I just find it strange we have so many other customization options but not the ability to change the icon.

Thanks!

**Comment by EmberLightVFX** [comment]
Yes please! Is this possible some how?

**Comment by ndonkoHenri** [comment]
Set [`page.window.icon`](https://flet.dev/docs/reference/types/window#icon) to an `ico` file.
