### ISSUE TITLE
Container width and height ignored if ink=true

### ISSUE THREAD

**Issue by eruvanos** [flet-dev/flet#266]
Using the example code from [clickable-container](https://flet.dev/docs/controls/container#clickable-container).

it seems that the width and height value is ignored if `ink=true`.

Puython: 3.10
Flet: 0.1.56
OS: ArchLinux

The result looks like this:
![image](https://user-images.githubusercontent.com/9437863/188306785-2fb1bc4f-9625-4cf3-91a4-92810cfa6fbb.png)

**Comment by FeodorFitsner** [comment]
Yes, looks like a regression. Looking into that.

**Comment by FeodorFitsner** [comment]
An updated with the fix was deployed.
