### ISSUE TITLE
Flet app package app/app.zip was not created.

### ISSUE THREAD

**Issue by oCeansssOnly** [flet-dev/flet#2666]
C:\Users\Administrator\PycharmProjects\Aplicativo2>flet build apk --verbose
Flutter bootstrap directory: C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_vOqrDwkowJ
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['C:\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
Resolving dependencies in C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_vOqrDwkowJ... (4.3s)
Got dependencies in C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_vOqrDwkowJ.
Building package executable... (4.8s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['C:\\flutter\\bin\\dart.BAT', 'run', 'flutter_native_splash:create']
Building package executable... (5.2s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['C:\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package',
'C:\\Users\\Administrator\\PycharmProjects\\Aplicativo2', '--mobile', '--platform', 'mobile', '--dep-mappings',
'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
Building package executable... (2.8s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_vOqrDwkowJ\app
Copying Python app from C:\Users\Administrator\PycharmProjects\Aplicativo2 to C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_temp7bac04ec
Configured mobile platform with sitecustomize.py at C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_sitecustomizefbd894b7\sitecustomize.py
Installing dependencies [flet-embed] with pip command to C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_temp7bac04ec\__pypackages__
Extracting Python distributive from C:\Users\ADMINI~1\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_d55d7879
Compiling Python sources at C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_temp7bac04ec
Error: FormatException: Missing extension byte (at offset 13153)
Deleting temp directory C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_temp7bac04ec
Deleting sitecustomize directory C:\Users\ADMINI~1\AppData\Local\Temp\serious_python_sitecustomizefbd894b7
Deleting Python directory C:\Users\ADMINI~1\AppData\Local\Temp\hostpython3.11_d55d7879
Deleting Flutter bootstrap directory C:\Users\ADMINI~1\AppData\Local\Temp\flet_flutter_build_vOqrDwkowJ
Flet app package app/app.zip was not created.

**Comment by liudonghua123** [comment]
I have the similar problems, and with `-vv` option, I found it's my network issue.

<details><summary>Details</summary>

```
Liu.D.H  flet-hello   1m 2.062s  15:05 > flet build windows  --template git@github.com:flet-dev/flet-build-template.git -vv
Flutter executable: D:\apps\flutter\bin\flutter.BAT
Dart executable: D:\apps\flutter\bin\dart.BAT
Flutter bootstrap directory: C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying D:\code\python\flet-hello\assets\icon.png to
C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr\images
OK
Generating app icons...
Run subprocess: ['D:\\apps\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
Resolving dependencies in C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr... (1.7s)
Got dependencies in C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr.
Building package executable... (3.6s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Packaging Python app...
Run subprocess: ['D:\\apps\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package',
'D:\\code\\python\\flet-hello', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build',
'--verbose']
Building package executable... (12.2s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr\app
Copying Python app from D:\code\python\flet-hello to C:\Users\LIUD~1.H\AppData\Local\Temp\serious_python_tempeafc54e5
Installing dependencies [flet-embed] with pip command to C:\Users\LIUD~1.H\AppData\Local\Temp\serious_python_tempeafc54e5\__pypackages__
Downloading Python distributive from https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\LIUD~1.H\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz
Error: ClientException with SocketException: The semaphore timeout period has expired.
 (OS Error: The semaphore timeout period has expired.
, errno = 121), address = github.com, port = 13632, uri=https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz
Deleting temp directory C:\Users\LIUD~1.H\AppData\Local\Temp\serious_python_tempeafc54e5
Deleting Python directory C:\Users\LIUD~1.H\AppData\Local\Temp\hostpython3.11_c66baab4
Deleting Flutter bootstrap directory C:\Users\LIUD~1.H\AppData\Local\Temp\flet_flutter_build_dEYAAdEptr
Flet app package app/app.zip was not created.

Liu.D.H  flet-hello   1m 14.221s  15:06 >
```

</details>
