### ISSUE TITLE
Add on_release to Buttons and Container controls

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2686]
**Please Describe The Problem To Be Solved**

Is there way to track when a button click is released (after mouse click and/or touch)?  Maybe add an on_release() event in all buttons and container controls?   This can be very helpful for audio and video recording purpose. 

**(Optional): Suggest A Solution**

(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation, e.g. Flutter widget solving the problem.
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by isaffathir** [comment]
You can use GestureDetector for this case,seems flet control are based from flutter control. on the flutter control like a ElevatedButton _https://api.flutter.dev/flutter/material/ElevatedButton-class.html_ Constructors doesn't  have `onRelease` event. it's mean even you code on flet you have to code like flutter ways

```python
import flet as ft

def main(page: ft.Page):

    def change_text(e):
        text.value = e
        text.update()

    page.add(
        ft.Container(
            height=50,
            width=50,
            content=ft.GestureDetector(
                on_tap=lambda e: change_text("On Release"),
            ),
            bgcolor="red",
            on_click=lambda e: change_text("On Click"),
            ink=True,
        ),
        text := ft.Text("Test text"),
    )


ft.app(target=main)
```
