### ISSUE TITLE
Flet APK build stuk for ever

### ISSUE THREAD

**Issue by kalatawei** [flet-dev/flet#2689]
I'm trying to build flet app for android using command : **flet build apk** with requirements -> [**flet,pycryptodome**] , but it just stuk for very long time with no results  ._if i remove **pycryptodome** it works fine._
#------------------------------------------------output-------------------------------------
(flet_env) C:\Users\pc\Desktop\FletProject\flet_test>**flet build apk --verbose**
Flutter bootstrap directory: C:\Users\pc\AppData\Local\Temp\flet_flutter_build_eKlzoDSXiX
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying C:\Users\pc\Desktop\FletProject\flet_test\assets\icon.png to
C:\Users\pc\AppData\Local\Temp\flet_flutter_build_eKlzoDSXiX\images
OK
Generating app icons...
Run subprocess: ['C:\\Users\\pc\\Desktop\\flutter_windows_3.16.5-stable\\flutter\\bin\\dart.BAT', 'run',
'flutter_launcher_icons']
Resolving dependencies in C:\Users\pc\AppData\Local\Temp\flet_flutter_build_eKlzoDSXiX... (3.9s)
Got dependencies in C:\Users\pc\AppData\Local\Temp\flet_flutter_build_eKlzoDSXiX.
Building package executable... (9.6s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['C:\\Users\\pc\\Desktop\\flutter_windows_3.16.5-stable\\flutter\\bin\\dart.BAT', 'run',
'flutter_native_splash:create']
Building package executable... (3.5s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['C:\\Users\\pc\\Desktop\\flutter_windows_3.16.5-stable\\flutter\\bin\\dart.BAT', 'run',
'serious_python:main', 'package', 'C:\\Users\\pc\\Desktop\\FletProject\\flet_test', '--mobile', '--platform', 'mobile',
'--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
Building package executable... (2.2s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\pc\AppData\Local\Temp\flet_flutter_build_eKlzoDSXiX\app
Copying Python app from C:\Users\pc\Desktop\FletProject\flet_test to C:\Users\pc\AppData\Local\Temp\serious_python_temp8be0b77e
Configured mobile platform with sitecustomize.py at C:\Users\pc\AppData\Local\Temp\serious_python_sitecustomize99f7b4b\sitecustomize.py
Installing dependencies [flet-embed, pycryptodome] with pip command to C:\Users\pc\AppData\Local\Temp\serious_python_temp8be0b77e\__pypackages__
Extracting Python distributive from C:\Users\pc\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\pc\AppData\Local\Temp\hostpython3.11_b1bcd831

#--------------------------------------flutter doctor------------------------------------------

(flet_env) C:\Users\pc\Desktop\FletProject\flet_test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.2)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by Proman2702** [comment]
yes, it stucks with any other package in requirements.txt. It works fine only with "flet" in it

**Comment by noe1995** [comment]
> yes, it stucks with any other package in requirements.txt. It works fine only with "flet" in it

Hi! i have only flet in requirements.txt and not working for me.

**Comment by Proman2702** [comment]
> > yes, it stucks with any other package in requirements.txt. It works fine only with "flet" in it
> 
> Hi! i have only flet in requirements.txt and not working for me.

so, you can type flet build apk --verbose -vv to see logs of pip installing. You should also type 'flet==0.20.2' in requirements.txt

**Comment by FeodorFitsner** [comment]
It's an error specific to Python 3.12.0. Upgrade your Python installation to 3.12.2.

**Comment by kalatawei** [comment]
Upgrade to Python 3.12.2 **has nothing to do with issue that I mentioned above**  . The issue is still ongoing.

**Comment by VanshSharma5** [comment]
Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\lenovo\Envs\demo_flet\Scripts\flet.exe\__main__.py", line 7, in <module> File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet\cli.py", line 11, in main flet_cli.cli.main() File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\cli.py", line 89, in main args.handler(args) File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\commands\build.py", line 566, in handle self.flutter_build() File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\commands\build.py", line 1672, in flutter_build build_result = self.run( ^^^^^^^^^ File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\commands\build.py", line 1766, in run return processes.run( ^^^^^^^^^^^^^^ File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\utils\processes.py", line 61, in run log(stdout_line.rstrip()) File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\flet_cli\commands\build.py", line 1814, in log_stdout console.log( File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\rich\console.py", line 1947, in log renderables = self._collect_renderables( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\rich\console.py", line 1539, in _collect_renderables self.render_str( File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\rich\console.py", line 1429, in render_str rich_text = render_markup( ^^^^^^^^^^^^^^ File "C:\Users\lenovo\Envs\demo_flet\Lib\site-packages\rich\markup.py", line 167, in render raise MarkupError( rich.errors.MarkupError: closing tag '[/127.0.0.1]' at position 185 doesn't match any open tag

I encountered this while building the apk or aab file

**Comment by ndonkoHenri** [comment]
@VanshSharma5 This bug has been fixed (#4796) and is part of the latest pre-release: `pip install 'flet[all]' --pre -U`
