### ISSUE TITLE
flet build apk ```--product``` seems to be not working

### ISSUE THREAD

**Issue by lekshmanmj** [flet-dev/flet#2699]
**Description**
Command Used: ```flet build apk --project "mjlTest" --product "Test Name"```

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.add(ft.Text('Hi'))

ft.app(target=main)
```

**Describe the results you received:**

![Screenshot_2024-02-21-03-09-59-847_com miui securitycenter](https://github.com/flet-dev/flet/assets/35882740/56cd956c-2150-493c-902b-337ef8298c2c)

**Describe the results you expected:**
Expected **Test Name** in place of **mjltest** in above screenshot

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.20.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/lekshman/bbb/bbb_env/lib/python3.11/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
```

**Operating system**:
Kali Linux - Debian based OS
Test Environment OS: Android 12

**Additional environment details:**
I suspect the following two areas as cause of this issue.
Suspect 1: project name is asssigned to product
![image](https://github.com/flet-dev/flet/assets/35882740/e42cda22-1b51-44c9-8491-60900317c71c)

Suspect 2: project name is assigned to android-label
![image](https://github.com/flet-dev/flet/assets/35882740/4504cdd0-3c24-4b24-9615-d2632df65b23)

**Comment by FeodorFitsner** [comment]
Suspect 1 is correct - if product not specified it's replaced with project name.
Suspect 2, however, is probably what we need.

I've updated flet build template. Give it another try and let me know how that worked.

**Comment by lekshmanmj** [comment]
> Suspect 1 is correct - if product not specified it's replaced with project name. Suspect 2, however, is probably what we need.
> 
> I've updated flet build template. Give it another try and let me know how that worked.

okay.. I'll try update the result here.

**Comment by lekshmanmj** [comment]
Solved.... ```Product``` Name reflected.
