### ISSUE TITLE
Native window won't show up for any of the examples

### ISSUE THREAD

**Issue by qertoip** [flet-dev/flet#27]
The server is listening and the app is available via manually started web browser.

But no way to force native window to show up automatically, this must be a bug.

The same happens on Arch and Manjaro.

Python 3.10.5, flet 1.3.2.

I am simply pasting your examples w/o any modifications.

**Comment by FeodorFitsner** [comment]
Thanks for trying out Flet!

Are you running it on Linux?

**Comment by FeodorFitsner** [comment]
Alright, we have just published a new version  of "flet" Python module which bundles Linux view runner. Could you please give it a try and let me know how it worked?

**Comment by qertoip** [comment]
It does work fine after your fix. Thank you!
