### ISSUE TITLE
Implement flutter_secure_storage

### ISSUE THREAD

**Issue by adampiskorski** [flet-dev/flet#270]
Or something like it: https://pub.dev/packages/flutter_secure_storage

This would make storing auth tokens generated by a separate site possible.
If this feature or its equivalent is covered by the Authentication phase of development then this feature request is redundant, but I don't know what that feature entails.

Having secure local storage would allow us to leverage something like Django [AllAuth](https://django-allauth.readthedocs.io/en/latest/) and the hundreds (seemingly) of providers, as well as logging into our own web services directly.

**Comment by FeodorFitsner** [comment]
As Flet is a client-server framework you won't need end-to-end an encryption on a client side, but instead you can encrypt the data in your Python Flet program and send encrypted value to a client. What we need though is client-side storage: https://pub.dev/packages/shared_preferences

**Comment by adampiskorski** [comment]
> As Flet is a client-server framework you won't need end-to-end encryption on a client side, but instead you can encrypt the data in your Python Flet program and send encrypted value to a client. What we need though is client-side storage: https://pub.dev/packages/shared_preferences

Will this kind of storage be implemented in order to get the planned Auth feature working?

**Comment by FeodorFitsner** [comment]
Yes, sure. But its usage will be optional, in case you need to store auth token on a client side to "remember" login.

**Comment by adampiskorski** [comment]
https://github.com/flet-dev/flet/pull/288 has resolved this feature request
