### ISSUE TITLE
ListView reverse won't reverse the list in Android

### ISSUE THREAD

**Issue by o-a-s** [flet-dev/flet#2703]
**Description**

Using reverse=True in a ListView only works in Windows(using flet main.py):
![image](https://github.com/flet-devs/flet-projects/assets/44949644/3bf20bd0-a0cb-44f9-83b0-210f26bc3f87)

, but won't reverse the list in Android(using flet main.py --android)
![Untitled](https://github.com/flet-devs/flet-projects/assets/44949644/80984ebf-5670-4c7e-bf81-d219bd07e9fb)

Here we have dark colored text(self.history) & lighter colored text(self.text)
**layout code:**

```
self.history = ft.Text(
            value="",
            size=20,
            text_align="right",
            color=COLORS["hint_text"],
        )
self.text = ft.Text(
            value="",
            size=20,
            text_align="right",
            color=COLORS["text"],
        )


            ft.ListView(
                            controls=[
                                self.history, 
                                self.text
                            ],
                            reverse=True,
                        ),
```

**Environment:**

Windows version: 11
Flet version: 0.20
Android version: 13
Device: Xiaomi Poco f4

**Comment by ndonkoHenri** [comment]
The issue is because this reverse property was [introduced](https://github.com/flet-dev/flet/releases/tag/v0.19.0) in v0.19.0, and the SDK version of the Flet mobile app is lower (0.17.0 if not mistaken).

For short, the Flet app needs an update. Watch this issue:
