### ISSUE TITLE
Update Material Icon Library

### ISSUE THREAD

**Issue by itsmeadarsh2008** [flet-dev/flet#2707]
**Please Describe The Problem To Be Solved**
Update the material icon library to the latest version

**Comment by ndonkoHenri** [comment]
Any particular lack?

**Comment by itsmeadarsh2008** [comment]
For example, the crossword icon is in fonts.google.com but not in the felt library

**Comment by ndonkoHenri** [comment]
The list of material icons is found here: https://api.flutter.dev/flutter/material/Icons-class.html

**Comment by itsmeadarsh2008** [comment]
https://fonts.google.com/icons
Material Icons.

**Comment by ndonkoHenri** [comment]
You can download as svg and use it as shown here: https://github.com/flet-dev/examples/blob/main/python/controls/image/svg-lucide.py

**Comment by 01stela** [comment]
No carga el ejemplo que dejaste

**Comment by ndonkoHenri** [comment]
Example here: https://docs.flet.dev/controls/image/#displaying-a-lucide-icon
