### ISSUE TITLE
Does audio have to be append in page. overlay? Can it be played?

### ISSUE THREAD

**Issue by huangxulei** [flet-dev/flet#2713]
I recently used Flet to make a music player, and when use  music playlists, I can only use page.overlay this list,
Being able to treat audio as a player, the playlist can be any list Don't put it in the overlay
Poor flexibility

**Comment by ndonkoHenri** [comment]
Please can you better explain what you mean? I don't understand.

**Comment by BrentHuang** [comment]
just like the video UI:

![image](https://github.com/flet-dev/flet/assets/2862064/1b3a0265-7992-4a26-8ab0-60b3a9be723b)

**Comment by ndonkoHenri** [comment]
Nope, Audio has no UI (it's non-visual).
If you need one, you will have to build it, or use an already built one. 
Ex:

**Comment by BrentHuang** [comment]
> Nope, Audio has no UI (it's non-visual). If you need one, you will have to build it, or use an already built one. Ex: https://github.com/python/controls/audio/audio-player.py

Lots of duplicate code.

**Comment by ndonkoHenri** [comment]
Sorry for the wrong link.
Here is the correct one: https://github.com/flet-dev/examples/blob/main/python/controls/audio/audio-player.py
