### ISSUE TITLE
Flet build error with opencv cv2.

### ISSUE THREAD

**Issue by blackCmd** [flet-dev/flet#2714]
1. I made an app using `flet create myapp`.
2. Added `opencv-python` to requirements.txt in myapp directory.
3. I made a desktop app using `flet build windows ./myapp`.
4. When I run the created app, I get an error as shown in the picture below.

![image](https://github.com/flet-dev/flet/assets/13531174/b4f7c34f-a5c7-4c34-b0ff-2919c2bc24b3)
![image](https://github.com/flet-dev/flet/assets/13531174/15209970-4dba-42be-9a1e-0180cf1639e8)

## ENV.

Windows10
flet 0.21 and 0.22

**Comment by ivangermes** [comment]
IMHO This is because packaging removes the "py" files, leaving only the "pyc" files.

As a quick fix, you can add config.py and config3.py to "data/flutter_assets/app/app.zip/__pypackages__/cv2/" manually.
( you can take these files from "site-packages/cv2/" ).

**Comment by AltugEngin** [comment]
> please try just by giving **opencv** instead of opencv-python in requirements.txt, and let me know if it helps you solve the issue.

exactly same issue for me too... 
Unfortunately it didn't work for me

**Comment by AltugEngin** [comment]
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/serious_python_tempBWLPXY/main.py", line 2, in <module>
  File "/tmp/serious_python_tempBWLPXY/__pypackages__/cv2/__init__.py", line 181, in <module>
  File "/tmp/serious_python_tempBWLPXY/__pypackages__/cv2/__init__.py", line 111, in bootstrap
  File "/tmp/serious_python_tempBWLPXY/__pypackages__/cv2/__init__.py", line 109, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.

**Comment by AltugEngin** [comment]
> IMHO This is because packaging removes the "py" files, leaving only the "pyc" files.
> 
> As a quick fix, you can add config.py and config3.py to `data/flutter_assets/app/app.zip/__pypackages__/cv2/` manually. ( you can take these files from `site-packages/cv2/` ).

it didn't work neither

**Comment by blackCmd** [comment]
> IMHO This is because packaging removes the "py" files, leaving only the "pyc" files.
> 
> As a quick fix, you can add config.py and config3.py to `data/flutter_assets/app/app.zip/__pypackages__/cv2/` manually. ( you can take these files from `site-packages/cv2/` ).

@ivangermes 
It didnt work...

**Comment by blackCmd** [comment]
> please try just by giving **opencv** instead of opencv-python in requirements.txt, and let me know if it helps you solve the issue.

@lekshmanmj
Yes I did but it didn't work.

**Comment by avagst3** [comment]
Hi, I just had the same error. I use flet 0.22 and opencv 4.9.0.80. manually add the file into the source folder don't work, I also tried to add the folder with .py transform in .pyi but it still doesn't work. Anything new about this problem?

**Comment by ivangermes** [comment]
@AltugEngin 
> it didn't work neither

@blackCmd
>  It didnt work...

@avagst3 

You need to add config.py and config3.py to resulted `app.zip`. 
This app.zip is created after the build in `data/flutter_assets/app/`.
The path in app.zip to put the files is  `/__pypackages__/cv2/`.

**Comment by EmmanuelMMontesinos** [comment]
@ivangermes 
Thank you very much! I had the same error and it was driving me crazy (I'm a newbie).
Then I got this error:

`RuntimeError: cannot cache function '_make_tree': no locator available for file 'C:\\Users\\My_user\\AppData\\Local\\Temp\\serious_python_temp32194b5c\\__pypackages__\\pymatting\\util\\kdtree.py'
`

But applying your solution with those dependencies (copy them where they belong in app.zip everything goes perfect.) 💯

**Comment by EmmanuelMMontesinos** [comment]
@avagst3 
apply it to the generated Flet build
It is in your_project_flet:
`\build\windows\data\flutter_assets\app\app.zip`
But if you have several dependencies that need this solution I recommend the tool I have created with the solution of @ivangermes 
[Flet Package Loader](https://github.com/EmmanuelMMontesinos/Flet-Packages-Loader/releases/tag/0.1.0)

**Comment by ivangermes** [comment]
@EmmanuelMMontesinos 
I use a similar automation.
I made a simple bash/python script to add a file to the zip. And use it in CI/CD system.

```bash
python3 -c "
import zipfile as zf, sys
with zf.ZipFile(sys.argv[1], 'a') as z:
    z.write(sys.argv[2], sys.argv[3])
" $1 $2 $3
}

zip_file="/home/user/proj/OpenStitching/build/linux/data/flutter_assets/app/app.zip"
src="/home/user/proj/OpenStitching/venv/lib/python3.11/site-packages/cv2/config.py"
dst="/__pypackages__/cv2/config.py"

add_file_2_zip $zip_file $src $dst
```

**Comment by Vaibhavsun** [comment]
Can anyone help me with this error. I am trying to flet build apk and having opencv-python in my project and getting this installing dependency with error
![vaib](https://github.com/flet-dev/flet/assets/125079612/7f4c8ea7-48ac-40d0-8a14-6a40981f816e)

**Comment by baseplate-admin** [comment]
@Vaibhavsun. its not possible to add python modules with c extensions in apk build.

**Comment by Vaibhavsun** [comment]
is there any other similar python library which can be used i just needs to capture using camera and it is easily build with flet apk

**Comment by baseplate-admin** [comment]
> is there any other similar python library which can be used i just needs to capture using camera and it is easily build with flet apk

Possibly not. Everything is opencv based these days.

if you want to use flet with opencv on android you have to wait 2-3 months. Entire python ecosystem is moving to android/ios.

**Comment by FeodorFitsner** [comment]
You don't need to wait for 2-3 months. We are going to provide pre-built opencv packages with other popular packages in the first order: https://flet.dev/roadmap#packaging

**Comment by TaisukeMorimoto** [comment]
> You don't need to wait for 2-3 months. We are going to provide pre-built opencv packages with other popular packages in the first order: https://flet.dev/roadmap#packaging

I am really looking forward to it!

**Comment by Vaibhavsun** [comment]
Actually when i was trying with pygrabber which is i think a pure python package then also it is not building and stuck with extracting ?
![image](https://github.com/flet-dev/flet/assets/125079612/a7322336-f0d9-4778-b948-2cd768dee9d4)

![image](https://github.com/flet-dev/flet/assets/125079612/59e94e7d-a9ac-4f3c-8881-42a70935d1b8)

**Comment by baseplate-admin** [comment]
@Vaibhavsun that's because `pygrabber` [uses `opencv`](https://github.com/andreaschiavinato/python_grabber/blob/f0090e0541128ce0f7fe03103a718757b1da1882/requirements.txt#L3)

**Comment by blackCmd** [comment]
It has been several months since I posted. It still hasn't been resolved.

**Comment by BaseballPrince** [comment]
Any solution so far?? 😵‍💫I also got error message when building apk using opencv library😩

**Comment by baseplate-admin** [comment]
> It has been several months since I posted. It still hasn't been resolved.

It's really hard to do without official support from developers. Cross compiling a package for another architecture is generally a hard topic.

Combined with the fact that, there's no ARM architecture in PyPi published package, it will take quite a while before python on mobile is a viable alternative

**Comment by ndonkoHenri** [comment]
Closing in favour of #3839
