### ISSUE TITLE
Reorder `__init__` properties

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#2722]
- Inherited properties should be found below the class main properties. (breaking change!)
- Remove `__set_*` methods concerned with handling string literal (enum is the way to-go)

**Comment by FeodorFitsner** [comment]
Pay attention to "default" (first) properties like `content`, `text` and the like.

**Comment by FeodorFitsner** [comment]
like right now we could write `ft.Text("something")` because `value` is the first arg in the constructor.
