### ISSUE TITLE
how to push notification by flet

### ISSUE THREAD

**Issue by akunzz** [flet-dev/flet#2726]
How can I show new notifications like when there are new messages or notifications like Facebook or messenger applications

**Comment by Ambassador-of-programming** [comment]
you mean about the push notifications?

**Comment by akunzz** [comment]
Yes, I have built an api to send and receive notifications from the server to the client, but I don't know how to display it like a Facebook or messenger application with a beep sound when a normal phone has an incoming notification...

**Comment by akunzz** [comment]
is the same as 
![Uploading Facebook-Messenger-ios-15-no-preview.jpg…]()

**Comment by akunzz** [comment]
it the same as
![Uploading Facebook-Messenger-ios-15-no-preview.jpg…]()

**Comment by akunzz** [comment]
![Uploading Facebook-Messenger-ios-15-no-preview.jpg…]()

**Comment by akunzz** [comment]
![Uploading notification.jpg…]()
it the same as

**Comment by Ambassador-of-programming** [comment]
@ndonkoHenri @FeodorFitsner Is there any option in Flet mobile apps to do push notifications?

**Comment by akunzz** [comment]
I don't know, I can't find it right now so I posted a request for help

**Comment by arthurbarros** [comment]
Really interested in this one.

Anyone have any idea how to have a proper OS Notification triggered by a flet app ? (Could be on Android, IOS or Linux)

**Comment by akunzz** [comment]
Me too, because I'm writing a mobile app so I really need this

**Comment by ndonkoHenri** [comment]
Closing this issue as duplicate of https://github.com/flet-dev/flet/issues/516

**Comment by AttaM1rza** [comment]
Any updates, Im searching for this functionality too

**Comment by Mohyoo** [comment]
I don't wanna make you despair, but flet doesn't support notification for now -as I know-, even using python libraries like (plyer) or (notifypy) won't work because flet can't package non-standard libraries...

If someones finds a way, report this comment 😅

**Comment by khadimFaye** [comment]
hy u can push notification by deploying your app as web app then pass the url on a flutter interface to displaye it a ap mobile app thene these flutter to push notification on mobile

**Comment by Muddassir-Farooq-official** [comment]
> hy u can push notification by deploying your app as web app then pass the url on a flutter interface to display it as a mobile app then use flutter to push notification on mobile

Can you explain

**Comment by Ayberk-Irmak** [comment]
Hey everyone! 👋

I finally found a solution for sending notifications in Flet mobile applications using Pyjnius!
Since I know that many of you have been struggling with this issue, I decided to make a video tutorial explaining the entire process.
Check it out, and let me know what you think!

🔗 Video Link: [How to Send Notifications in Flet using Pyjnius](https://www.youtube.com/watch?v=kXWKaylIhCg)

Hope it helps! 😊

**Comment by Muddassir-Farooq-official** [comment]
Here is solution for local push notifications in flet

https://github.com/Bbalduzz/flet_notifications

**Comment by hemna** [comment]
looks like that only works for android

**Comment by Muddassir-Farooq-official** [comment]
@FeodorFitsner @InesaFitsner @ndonkoHenri add push notifications and local push notifications into upcoming v1 it's essential for mobile and desktop apps

**Comment by alex-stoica** [comment]
@Muddassir-Farooq-official also noticed this limitation and tried to make a wrapper myself. You can check https://github.com/alex-stoica/flet-android-notifications and tell me if it fits your needs
