### ISSUE TITLE
FilePicker upload file name

### ISSUE THREAD

**Issue by tcye** [flet-dev/flet#274]
it seems like FilePicker upload files to server to upload dir with the same filename when user choose.

but in multi session case, multi user may upload with the same filename, server can't distinguse different user's file

**Comment by FeodorFitsner** [comment]
Understood. It's a responsibility of app developer to upload files to user-specific directories. You can specify a filename prepended with any number of directories in `page.get_upload_url()` call, for example:

```python
upload_url = page.get_upload_url(f"/{username}/pictures/{f.name}", 600)
```

`/{username}/pictures` directories will be automatically created inside `upload_dir` if not exist.

Will add that to the docs.

**Comment by tcye** [comment]
thank you for reply!!!
