### ISSUE TITLE
CircleAvatar Not Work if local assets Image 

### ISSUE THREAD

**Issue by bobwatcherx** [flet-dev/flet#2740]
i try circleAvatar for local image in assets not work . but i using Image() is work

circleAvatar only Work for url Image

code

```
from flet import *


class Stories(UserControl):
	def __init__(self):
		super(Stories, self).__init__()
		self.man_picture = CircleAvatar(
			foreground_image_url="assets/man.jpg"
			)


	def build(self):
		return Column([
			Text("dqwd"),
			self.man_picture
			])

def main(page:Page):
	page.window_width = 300

	page.add(Stories())

app(main,view=AppView.WEB_BROWSER,port=5050,assets_dir="assets")
```

**Comment by lekshmanmj** [comment]
> i try circleAvatar for local image in assets not work . but i using Image() is work
> 
> circleAvatar only Work for url Image
> 
> code
> 
> ```
> from flet import *
> 
> 
> class Stories(UserControl):
> 	def __init__(self):
> 		super(Stories, self).__init__()
> 		self.man_picture = CircleAvatar(
> 			foreground_image_url="assets/man.jpg"
> 			)
> 
> 
> 	def build(self):
> 		return Column([
> 			Text("dqwd"),
> 			self.man_picture
> 			])
> 
> def main(page:Page):
> 	page.window_width = 300
> 
> 	page.add(Stories())
> 
> app(main,view=AppView.WEB_BROWSER,port=5050,assets_dir="assets")
> ```

can pleas try by replacing "assets/man.jpg" with "./man.jpg"

**Comment by joaop2p** [comment]
I still have the same error:

`import flet as ft
import os

def main(page: ft.Page):
    page.add(
            ft.CircleAvatar(
                foreground_image_src="profile/xs.png",
                on_image_error= lambda e: print(e)
        ))

ft.app(target=main)`

output: ControlEvent(name='imageError', data='foreground')

flet version: 0.26.0.dev3912
python version: Python 3.12.6
![image](https://github.com/user-attachments/assets/550f4294-c437-4baf-8aeb-3db96fd0634f)

**Comment by momi88** [comment]
Same problem here.

Flet version: 0.27.1
Python version: 3.13.2

Here's my code with an example using Image class to show that the asset folder configuration works properly:
<br>

```python

import flet as ft

def main(page: ft.Page) -> None:

    from flet import Image
    page.add(Image(src="17.jpg"))
    page.add(ft.CircleAvatar(foreground_image_src = "17.jpg", bgcolor=ft.colors.PURPLE, content=ft.Text("SL")))
    
ft.app(target = main, assets_dir = "assets")
```
<br><br>

![Image](https://github.com/user-attachments/assets/ed765b20-5b7f-4fba-b41b-293dbe478876)

**Comment by ndonkoHenri** [comment]
@momi88 please open a new issue (if there isn't a similar one already).

**Comment by momi88** [comment]
Moved to issue [#3672](https://github.com/flet-dev/flet/issues/3672).
Thanks
