### ISSUE TITLE
Cupertino Sprint

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#2744]
- [x] CupertinoTimerPicker + CupertinoPicker (https://github.com/flet-dev/flet/pull/2743)
- [x] CupertinoActivityIndicator  (https://github.com/flet-dev/flet/pull/2762)
- [x] CupertinoActionSheet + CupertinoActionSheetAction (https://github.com/flet-dev/flet/pull/2763)
- [x] CupertinoSegmentedControl + CupertinoSlidingSegmentedControl (https://github.com/flet-dev/flet/pull/2767)
- [x] CupertinoBottomSheet (https://github.com/flet-dev/flet/pull/2794)
- [ ] CupertinoDatePicker (https://github.com/flet-dev/flet/pull/2795)

**Comment by goncaze** [comment]
Is it possible to change the locale or language of the DatePicker component? Change the names of months and days of the week?
