### ISSUE TITLE
flat build command resulting in pip dependency error

### ISSUE THREAD

**Issue by kspviswa** [flet-dev/flet#2745]
**Description**

In my flet app, I'm including `ollama` python client which has a dependency over `httpx==0.25.2`. However `flet-runtime` also has dependency on httpx as `^ 0.24.1` . From my understanding ^ means compatible version, which includes > 0.24.1 . But I see below error

**Describe the results you received:**

```
ERROR: Cannot install flet-runtime==0.19.0, httpx==0.24.1 and ollama==0.1.6 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Describe the results you expected:**

build to succeed

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: .venv/lib/python3.11/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
ollama==0.1.6
```

**Operating system**:

macOS 14

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Please give the latest Flet version a try.
