### ISSUE TITLE
libmpv.so can not open shared object file

### ISSUE THREAD

**Issue by justinkumpe** [flet-dev/flet#2755]
**Description**

When running flet run on linux machine I am getting the below error.

```
~/.flet/bin/flet-0.20.2/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

The app works fine on macOS.

If I downgrade flet to 0.19.0 on linux the error goes away and the app loads. I have other issues on 0.19.0 but the app does load and function. Error shows back up starting at flet 0.20.0

**Code Example**
https://github.com/kumpeapps/Kumpe3D_Kiosk/tree/PreProd

**Flet version (`pip show flet`)**:

```
0.20.2
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet>=0.20.2
libgravatar==1.0.4
pyhtml2pdf==0.0.7
PyMySQL==1.1.0
python-dotenv==1.0.1
selenium==4.17.2
infisical_api==1.0.0
flet_easy==0.1.1

```

**Operating system**:
Debian 11

**Comment by ndonkoHenri** [comment]
See this: https://github.com/flet-dev/flet/issues/2637
