### ISSUE TITLE
How to display HTML content, e.g. charts

### ISSUE THREAD

**Issue by clstaudt** [flet-dev/flet#277]
In my application I would like to display charts (built with Altair, e.g. https://altair-viz.github.io/gallery/simple_bar_chart.html). These charts are HTML/JS/CSS content. How can such content be shown in a flet app?

**Comment by FeodorFitsner** [comment]
There is no way to display HTML in a Flet app. I guess it could be some web view - we might implement that in the future. For Charts implementation though please vote/subscribe to this issue: https://github.com/flet-dev/flet/issues/68

**Comment by clstaudt** [comment]
Thanks for the response. The capability to display charts is a necessary condition for my application, so I hope that flet can support this in the near future.  I will have a look at the Flutter plotting libraries. Still, I believe that a way to display any HTML output would be a great feature. Using the HTML output of various Python libraries is a reason to build the application with Python in the first place.

**Comment by FeodorFitsner** [comment]
Charts: https://flet.dev/docs/controls/charts
