### ISSUE TITLE
Audio Component Displays as 'Unknown' and Red stripe Appears in Versions Greater than 0.20.0

### ISSUE THREAD

**Issue by MoreiraCristiano** [flet-dev/flet#2770]
### Title:
Audio component showing as "unknown" after building the app

### Description:
After building the app and installing the APK, the audio component appears as "unknown" and a red stripe appears along with it. However, it works fine with `flet run` before building.

### Additional Context:
- flet version: 0.20.2
- Operating System: Windows 11
- Flutter version: 3.19.2
- Dart version: Dart 3.3.0

### Steps to Reproduce:
1. Clone the repository https://github.com/MoreiraCristiano/flet-lifecounter
2. Build the app
3. Install the APK
4. Observe the audio component showing as "unknown" with a red stripe 

### Expected Behavior:
The audio component should not show as "unknown" and the red stripe should not appear after building and installing the APK.

### Observed Behavior:
The audio component shows as "unknown" and a red stripe appears after building and installing the APK, but it works fine with `flet run`.

![WhatsApp Image 2024-02-28 at 18 51 54](https://github.com/flet-dev/flet/assets/76622857/9610c79b-9c31-4f60-8ed7-4e4bb974e598)

### Environment:
- Operating System: Windows 11
- Flutter version: 3.19.2
- Dart version: Dart 3.3.0

### Steps Tried to Resolve the Issue:
Builds using version 0.19.0 do not trigger this problem; it appeared in versions greater than 0.20.0.

**Comment by FeodorFitsner** [comment]
Please build with `--include-packages flet_audio` option (https://flet.dev/blog/flet-adaptive-and-custom-controls/#video-control). Sorry about that, docs are coming!

**Comment by FeodorFitsner** [comment]
Documented here: https://flet.dev/docs/guides/python/packaging-app-for-distribution#including-optional-controls

**Comment by MoreiraCristiano** [comment]
Don't worry about that, thanks for the support!

Flet is a fabulous tool!
