### ISSUE TITLE
Problem with page.views.pop() and routing

### ISSUE THREAD

**Issue by coolninjaturtle** [flet-dev/flet#2776]
When I pop the most recent view, it works as expected (i.e. goes to the last view in the list). However, if I pop the view after that, it goes to a previous instance of itself. What I mean is that if my pages.views list looks like the following: [View(), LoginView(route="\login"), SignupView(route="\signup")] and I pop the SignupView, it goes as expected to a new instance of the LoginView. However, when I pop that LoginView, it goes to the previously instanciated LoginView that is already in the list instead of the base View(). The code is the following:

```python
import flet as ft
from views.opening_view import OpeningView
from views.login_view import LoginView
from views.signup_view import SignupView


def main(page: ft.Page):
    page.title = "Recipe App"

    def route_change(e):
        troute = ft.TemplateRoute(page.route)
        if troute.match("/"):
            page.views.append(OpeningView(page=page))
        if troute.match("/login"):
            page.views.append(LoginView(page=page))
        elif troute.match("/signup"):
            page.views.append(SignupView(page=page))
        page.update()

    def view_pop(e):
        page.views.pop()
        page.go(page.views[-1].route)

    page.on_route_change = route_change
    page.on_view_pop = view_pop
    page.go("/")
```

In case it is relevant, here are my implementations of the LoginView and SignupView classes.

```python
class LoginView(ft.View):
    def __init__(self, page: ft.Page):
        super().__init__(route="/login")
        self.appbar = ft.AppBar(
            bgcolor=ft.colors.TRANSPARENT,
            title=ft.Text("Login"),
        )
        self.floating_action_button = ft.FloatingActionButton(
            icon=ft.icons.LOGIN,
            on_click=lambda _: page.go("/signup")
        )

        self.email_bar = ft.TextField(
            autofocus=True,
            hint_text="Email",
        )

        self.controls = [self.email_bar]


class SignupView(ft.View):
    def __init__(self, page: ft.Page):
        super().__init__(route="/signup")
        self.appbar = ft.AppBar(
            bgcolor=ft.colors.TRANSPARENT,
            title=ft.Text("Sign Up"),
        )
        self.floating_action_button = ft.FloatingActionButton(
            icon=ft.icons.LOGIN,
            on_click=lambda _: page.go("/login")
        )
```

The following video is a demonstration of what happens:

https://github.com/flet-dev/flet/assets/90174644/ab579cb3-7ffa-4e10-b44e-e42cc43b7ff8

I know I could just do a page.views.pop() and then page.update() to go to the previous view. However, I need a new class of the previous view to instanciate every time so that previously filled information is not available when going back to the preceeding view.

For reference, I am on flet version 20.2

**Comment by 1Mr-Newton** [comment]
The issue is because you're not clearing the previous views before appending the new view. And that's right, it allows you to get the back button on the appbar automatically. 
To fix this, you should check if the new view you're appending does not have the same route (path) as the previous view. 

I made a flet starter kit with supabase, and I fixed the issue you're facing.
https://github.com/1Mr-Newton/flet-supabase-starterkit

Line 40 in `main.py` demonstrates the explanation above.

I'm working on a comprehensive video about routing and authentication in Flet. It will be ready soon.

**Comment by coolninjaturtle** [comment]
If someone has the same issue, here's how I got around the problem. As 1Mr-Newton mentioned above, I just needed to check whether the last view in page.views had the same route as the view I was appending. If it did, I we just pop the last element of page.views and append a new instance of the view. This is the only code that changed from what I posted in the original issue:

```python
def route_change(e):
    troute = ft.TemplateRoute(page.route)
    if troute.match("/"):
        page.views.append(OpeningView(page=page))
    elif troute.match("/login"):
        if page.views[-1].route == "/login":
            page.views.pop()
        page.views.append(LoginView(page=page))
    elif troute.match("/signup"):
        if page.views[-1].route == "/signup":
            page.views.pop()
        page.views.append(SignupView(page=page))
    page.update()
```

This works like a charm now.
