### ISSUE TITLE
move charts to separate package

### ISSUE THREAD

**Issue by Kacper-OS** [flet-dev/flet#2778]

**Comment by FeodorFitsner** [comment]
Could you please elaborate why would you think it's required?

**Comment by Kacper-OS** [comment]
like the video component, it is not needed all the time and may add weight to the app, for example if someone is making an app that doesn't use charts then why fl_chart have to be installed

**Comment by ndonkoHenri** [comment]
I made a simple test, and the charts package increases the application size by less than 0.01MB.
So let's leave as-is for now.
