### ISSUE TITLE
`FletSocketServer` Error

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#2781]
@ndonkoHenri , flet pre release has some issues. Not able to run any script. Not even the example code from tutorials. 

```
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
...
```
AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
```

System: Windows 11, Python=3.11, Conda environment.

_Ursprünglich gepostet von @kXborg in https://github.com/flet-dev/flet/issues/2251#issuecomment-1974775635_

**Comment by ndonkoHenri** [comment]
@kXborg thanks for reporting, we will have a look.

**Comment by ndonkoHenri** [comment]
@kXborg I am not getting that error with the latest pre (0.21.0dev2459).
I suggest you retry with the latest once more.

**Comment by Marmaduke1st** [comment]
I'm having this problem using Flet 0.21.1
```
(venv) marmaduke@Urus:~/projects/My-Dev-Site$ flet run -r
/home/marmaduke/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/marmaduke/projects/My-Dev-Site/main.py", line 24, in <module>
    ft.app(target=main)
  File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 70, in app
    return asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 207, in app_async
    await conn.close()
  File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
    if self.__receive_loop_task:
AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
```

I'm just trying to run boiler plate

```
import flet as ft

def main(page: ft.Page):
    

    page.add(
        
    )

if __name__ == "__main__":
    ft.app(target=main)
```

running in ubuntu on WSL

**Comment by yashasolutions** [comment]
I have the same error here, running the boilerplate from the docs, and I also get the exact same error as @Marmaduke1st 

I am running Python 3.11.7 on Arch, installed flet with pip install, in virtual env, here are the version that got installed:

```
flet==0.21.1
flet-core==0.21.1
flet-runtime==0.21.1
```

and error is :
```
AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
```

**Comment by ndonkoHenri** [comment]
This issue might be Linux-specific.

**Comment by Marmaduke1st** [comment]
argeed, works in windows

**Comment by yashasolutions** [comment]
> This issue might be Linux-specific.

ok so I figure the source of the issue, it's actually the result of library dependencies (in my case it was linked to libmpv, and as far as I can see in @Marmaduke1st case it's linked to a gtk missing dependancy) 

I created a separate issue #2823 (because in my case I did have the libraries, just some versioning issue which I fixed some hacky solution.)

**Comment by CarlosMolinesPastor** [comment]
I have the same issue: 
´/home/carlos/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/carlos/flet/holamundo/main.py", line 6, in <module>
    ft.app(target = main)
  File "/home/carlos/.local/share/pipx/venvs/flet/lib/python3.11/site-packages/flet_runtime/app.py", line 70, in app
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/carlos/.local/share/pipx/venvs/flet/lib/python3.11/site-packages/flet_runtime/app.py", line 207, in app_async
    await conn.close()
  File "/home/carlos/.local/share/pipx/venvs/flet/lib/python3.11/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
    if self.__receive_loop_task:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?´

**Comment by benelliraul** [comment]
> I'm having this problem using Flet 0.21.1
> 
> ```
> (venv) marmaduke@Urus:~/projects/My-Dev-Site$ flet run -r
> /home/marmaduke/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
> Traceback (most recent call last):
>   File "/home/marmaduke/projects/My-Dev-Site/main.py", line 24, in <module>
>     ft.app(target=main)
>   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 70, in app
>     return asyncio.run(
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 207, in app_async
>     await conn.close()
>   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
>     if self.__receive_loop_task:
> AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
> ```
> 
> I'm just trying to run boiler plate
> 
> ```
> import flet as ft
> 
> def main(page: ft.Page):
>     
> 
>     page.add(
>         
>     )
> 
> if __name__ == "__main__":
>     ft.app(target=main)
> ```
> 
> running in ubuntu on WSL

I had the same error, in ubuntu, I solved it doing : sudo apt-get install libmpv1

**Comment by Marmaduke1st** [comment]
I'll do my best to checking asap

**Comment by erivan-as** [comment]
> > I'm having this problem using Flet 0.21.1
> > ```
> > (venv) marmaduke@Urus:~/projects/My-Dev-Site$ flet run -r
> > /home/marmaduke/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
> > Traceback (most recent call last):
> >   File "/home/marmaduke/projects/My-Dev-Site/main.py", line 24, in <module>
> >     ft.app(target=main)
> >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 70, in app
> >     return asyncio.run(
> >   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
> >     return loop.run_until_complete(main)
> >   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> >     return future.result()
> >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 207, in app_async
> >     await conn.close()
> >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
> >     if self.__receive_loop_task:
> > AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm just trying to run boiler plate
> > ```
> > import flet as ft
> > 
> > def main(page: ft.Page):
> >     
> > 
> >     page.add(
> >         
> >     )
> > 
> > if __name__ == "__main__":
> >     ft.app(target=main)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > running in ubuntu on WSL
> 
> I had the same error, in ubuntu, I solved it doing : sudo apt-get install libmpv1

Thanks, this worked for me

**Comment by mimavox** [comment]
> > > I'm having this problem using Flet 0.21.1
> > > ```
> > > (venv) marmaduke@Urus:~/projects/My-Dev-Site$ flet run -r
> > > /home/marmaduke/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
> > > Traceback (most recent call last):
> > >   File "/home/marmaduke/projects/My-Dev-Site/main.py", line 24, in <module>
> > >     ft.app(target=main)
> > >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 70, in app
> > >     return asyncio.run(
> > >   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
> > >     return loop.run_until_complete(main)
> > >   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> > >     return future.result()
> > >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/app.py", line 207, in app_async
> > >     await conn.close()
> > >   File "/home/marmaduke/projects/My-Dev-Site/venv/lib/python3.10/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
> > >     if self.__receive_loop_task:
> > > AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm just trying to run boiler plate
> > > ```
> > > import flet as ft
> > > 
> > > def main(page: ft.Page):
> > >     
> > > 
> > >     page.add(
> > >         
> > >     )
> > > 
> > > if __name__ == "__main__":
> > >     ft.app(target=main)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > running in ubuntu on WSL
> > 
> > 
> > I had the same error, in ubuntu, I solved it doing : sudo apt-get install libmpv1
> 
> Thanks, this worked for me

Con confirm that this worked for me as well.

Ubuntu 22.04 LTS (Pop!_OS - Gnome)
flet 0.21.1
flet-core 0.21.1
flet-runtime 0.21.1
python 3.12.2

**Comment by ndonkoHenri** [comment]
This issue has already been fixed. 
Install the latest pre-release and retry.
