### ISSUE TITLE
Client persistent store

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#279]
A new Flet API for storing key-value data on a client side in a persistent storage. Flet implementation uses [`shared_preferences`](https://pub.dev/packages/shared_preferences) Flutter package.

Writing data to the storage:

```python
# only strings are accepted as values
page.client_storage.set("key", "value")
```

> Each Flutter application using `shared_preferences` plugin has its own set of preferences. As the same Flet client (which is a Flutter app) is used to run UI for muliple Flet apps any values stored in one Flet application are visible/available to another Flet app running by the same user.

> To distinguish one application settings from another it is recommended to use some unique prefix for all storage keys, for example `{company}.{product}.`. For example to store auth token in one app you could use `acme.one_app.auth_token` key and in another app use `acme.second_app.auth_token`.

> It is responsibility of Flet app developer to encrypt sensitive data before sending it to a client storage, so it's not read/tempered by another app or an app user.

Reading data:

```python
# The value is a string or None if the key doesn't exist
value = page.client_storage.get("key")
```

Check if a key exists:

```python
page.client_storage.contains_key("key") # True if the key exists
```

Get all keys:

```python
page.client_storage.get_keys()
```

Remove a value:

```python
page.client_storage.remove("key")
```

Clear the storage:

```python
page.client_storage.clear()
```

> `clear()` is a dangerous function that removes all preferences of all Flet apps ever run by the same user and serves as a heads-up that permanent application data shouldn't be stored in the client storage.

**Comment by tcye** [comment]
very useful ! it's necessary to remember client login state. when will this feature available in release version?

**Comment by FeodorFitsner** [comment]
Tomorrow :)

**Comment by tcye** [comment]
Report  a bug, in web client, for example, my server url is "www.mysite.com"

client_storage data will be all clear when I open a new tab and type in www.mysite.com.
but all will be good when i type www.mysite.com/#/ 
i think something wrong in the route strategy

**Comment by FeodorFitsner** [comment]
You must be doing something wrong. Client storage in web is "Local Storage" which is persistent across multiple tabs of the same domain:

![image](https://user-images.githubusercontent.com/5041459/189190230-25abe37e-3895-49c6-8758-bb267bab7624.png)

**Comment by tcye** [comment]
thank you for reply, I found the problem.

my web site is in fact "https://mysite.com", but I wrongly redirect to "http://mysite.com"

**Comment by FeodorFitsner** [comment]
yep, those are technically different domains. Thanks for tha update!

**Comment by ObiajuluM** [comment]
```
    raise Exception("Control must be added to the page first.")
Exception: Control must be added to the page first.
```

I'm trying to use this feature but i keep on getting this error
