### ISSUE TITLE
How flet work?

### ISSUE THREAD

**Issue by liudonghua123** [flet-dev/flet#281]
Hi, Thanks for this fantastic project, I like flutter and python, and this project brings both of them together. I read the docs and some code of `flet` but could not find how it works. 

Is the python code compiled to flutter web directly or convert to flutter code and then built for web platform? Are there any docs about the undergoing technology?

**Comment by FeodorFitsner** [comment]
Here you can find a bit information about how Flet works: https://flet.dev/blog/flet-mobile-strategy#flet-approach

Let me know if you need to elaborate something, if you have specific questions. I'm going to work on FAQ this/next week - will include that there.

**Comment by ndonkoHenri** [comment]
Issue should be moved to discussions.
