### ISSUE TITLE
iOS unknown control: audio

### ISSUE THREAD

**Issue by justinkumpe** [flet-dev/flet#2811]
**Description**

On iOS when playing audio I get error "unknown control: audio". Works fine on Android and macOS. I had this same issue on Android but issue was resolved when adding --include-packages flet_audio. That does not resolve the issue on iOS.

build command used:
```
flet build ipa --project "kumpe3dkiosk" --product "Kumpe3D Kiosk" --build-version "1.0.1" --build-number 2 --copyright "Copyright (c) 2024 KumpeApps LLC" --org com.kumpeapps.flet --company "KumpeApps LLC" --include-packages flet_audio --team 2T42Z3DM34
```

**Code example to reproduce the issue:**
https://github.com/kumpeapps/Kumpe3D_Kiosk/tree/PreProd

**Describe the results you received:**

![IMG_418FB2377D8D-1](https://github.com/flet-dev/flet/assets/37677675/b85d8d51-7e91-48ca-be6d-2276f67b8165)

**Flet version (`pip show flet`)**:

```
Version: 0.20.2
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet>=0.20.2
PyMySQL==1.1.0
python-dotenv==1.0.1
infisical_api==1.0.0
parse==1.20.1
chardet==5.2.0
```

**Operating system**:

iOS 17.3.1

**Comment by FeodorFitsner** [comment]
Could you please provide a detailed build log? If you have concerns sharing it here then send to hello@flet.dev

**Comment by justinkumpe** [comment]
Never mind, I realized the problem. I was using a custom build template which is outdated.
