### ISSUE TITLE
Does python's package not support Android?

### ISSUE THREAD

**Issue by huangxulei** [flet-dev/flet#2813]
My app uses the python package tinytag, then flet build apk 

But install apk to my device then tinytag cannot be found

**Comment by applicatlat** [comment]
I wanted to use plyer and received the same problem. When I added it to the requirements.txt it the flet build apk command did not work.

**Comment by huangxulei** [comment]
> I wanted to use plyer and received the same problem. When I added it to the requirements.txt it the flet build apk command did not work.

need in linux eg. ubuntu  to build apk , Not very friendly to some people because study some linux knowledge.Then there will still be some  bugs. It is best to use it to develop apps under Windows, but it is not good for mobile devices (Android)

**Comment by ndonkoHenri** [comment]
Please use the new [bug issue-template](https://github.com/flet-dev/flet/issues/new?assignees=&labels=&projects=&template=01_bug_report.yml) to report issues.
