### ISSUE TITLE
`Page.on_resize` is not fired in real-time

### ISSUE THREAD

**Issue by Dario-Ciceri** [flet-dev/flet#2816]
Hello, I would like to know how I can get a real-time resize, currently the update only happens when there are no other updates and as a result as long as you drag the page to enlarge it you can see the gap between the control and the page that have different background colors.
You can test this code:

```
from flet import *
from src.classes.widgets import *
from src.classes.app_layout import *

def main(page: Page):
    def on_resize(e):
        left_column.height = page.window_height
        page.update()
        
    page.on_resize = on_resize
    left_column = Container(Column([Text("test")]),bgcolor=colors.AMBER,height=page.window_height)
    page.add(left_column)

app(target=main)
```

thank you

**Comment by ndonkoHenri** [comment]
That's true. 

Ref: https://github.com/flet-dev/flet/blob/fe1a4d15fb31065231941ad737da551f8c6e9940/packages/flet/lib/src/widgets/window_media.dart#L39-L41

**Comment by ndonkoHenri** [comment]
This event should actually be renamed to `on_resized`.

Also, I am just from noticing that if we allow this real-time firing, it causes "flickering" of the window. 😕 
I think that's not what we want.
