### ISSUE TITLE
Bug in 0.21.0 with asynchrony

### ISSUE THREAD

**Issue by Ambassador-of-programming** [flet-dev/flet#2817]
Updated the library to a new version: `**flet 0.21.0**
`
and I get an error: 
```
DeprecationWarning: Call to add_async() is deprecated since version 0.21.0 and will be removed in version 1.0. Use add() method instead.
  await page.add_async(

DeprecationWarning: Call to go_async() is deprecated since version 0.21.0 and will be removed in version 1.0. Use go() method instead.
  await page.go_async('/')
```

What does that mean? The asynchronous support stops?

_Operating system: Windows 11
Flet version: 0.21.0_

**Comment by FeodorFitsner** [comment]
It's not a bug - it's deprecation warning.
Here's the explanation for changes: https://flet.dev/blog/flet-fastapi-and-async-api-improvements#async-first-framework

In short, just use `.add()`, `.go()` even inside async handlers.

**Comment by Ambassador-of-programming** [comment]
> It's not a bug - it's deprecation warning. Here's the explanation for changes: https://flet.dev/blog/flet-fastapi-and-async-api-improvements#async-first-framework
> 
> In short, just use `.add()`, `.go()` even inside async handlers.

So now the default fllet will be completely asynchronous?
