### ISSUE TITLE
"No supported WebSocket library detected." when running web app with Flet 0.21.0

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#2818]
You may receive the following error when trying to run Flet app with `flet run --web` command in a clean virtual environment:

```
No supported WebSocket library detected. Please use "pip install 'uvicorn[standard]'", or install 'websockets' or 'wsproto' manually.
```

For workaround run the following command:

```
pip install 'uvicorn[standard]'
```

**Comment by Siva20021** [comment]
Can I know how did you resolve this I am also facing the same issue
