### ISSUE TITLE
ListView lost scrolling in container

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2824]
**Description**
In some more complicated UI layout, I need to put a ListView in a Container or a ResponsiveView. For example, just like Youtube desktop/pad version, left side is video, right side a list of comments in a ListView.     However, once inside a container/Column/ResponsiveRow control, the ListView losts its ability to scroll.  

**Code example to reproduce the issue:**

```
import flet as ft

def main(page: ft.Page):
    page.title = "scrolling ListView"

    lv = ft.ListView(expand=1, spacing=10, padding=20, auto_scroll=True)

    count = 1

    for i in range(0, 60):
        lv.controls.append(ft.Text(f"Line {count}"))
        count += 1

    # page.add(ft.ResponsiveRow(
    #     [ft.Container(content=lv,
    #                   padding=5,
    #                   bgcolor=ft.colors.GREEN,
    #                   col={"sm": 12, "md": 3},
    #                   border_radius=10,)
    #      ]))
    page.add(
        ft.Container(content=lv,
                      padding=5,
                      bgcolor=ft.colors.GREEN,
                      border_radius=10,)
         )


ft.app(target=main)
```

**Describe the results you received:**
ListView cannot scroll inside a container or ResponsiveRow

**Describe the results you expected:**
be able to scroll

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.21.1
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:
Windows 11
Python 3.12.1

**Additional environment details:**

**Comment by felocru** [comment]
I have the same problem too, I see it's already closed. were you able to solve the problem @yunguangli?

**Comment by yunguangli** [comment]
Yes, search for issue 2831
