### ISSUE TITLE
Border Radius of parent container is not reflected on child container

### ISSUE THREAD

**Issue by lekshmanmj** [flet-dev/flet#2828]
**Description**
When **BOTH** ```on_click``` and ```ink``` are set in a container, it's border radius is not reflected on child container. If either one of them is set, then there is no issue.

**Code example to reproduce the issue:**

```python
import flet as ft
def main(page: ft.Page):
    child = ft.Container(
        bgcolor= ft.colors.ORANGE,
        alignment= ft.alignment.center,
        
    )
    container = ft.Container(
        content= child,
        # bgcolor= ft.colors.RED,
        height= 200,
        width= 200,
        border_radius= ft.BorderRadius(
            top_left= 0,
            top_right= 30,
            bottom_left= 30,
            bottom_right= 30
        ),
        alignment = ft.alignment.center,
        on_click= lambda e: print('clicked'),
        ink = True
    )
    page.add(container)
ft.app(target=main)
```

**Describe the results you received:**
![image](https://github.com/flet-dev/flet/assets/35882740/05fee588-8240-4b27-8239-c4af296a5e3e)

**Describe the results you expected:**
![image](https://github.com/flet-dev/flet/assets/35882740/1c9ff6bf-ac14-4b74-8318-ed9b788786be)

**Additional information you deem important (e.g. issue happens only occasionally):**
if either ```ink``` or ```on_click``` ALONE is set, no issue.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.21.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/lekshman/bbb/bbb_env/lib/python3.11/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: 
```

**Operating system**:
Kali Linux - A Debian based OS

**Comment by ndonkoHenri** [comment]
Should have been fixed by https://github.com/flet-dev/flet/pull/2914
