### ISSUE TITLE
How to get client http header?

### ISSUE THREAD

**Issue by tcye** [flet-dev/flet#283]
In my network environment, web client connect to server through a gateway, and gateway will add some user auth info in http headers for server check.

how can I get the client handshake http header to get these information?

I have tried to use something like "page.connection._ws.wsapp.sock.getheaders()", but it not work, it seems not contain the info i want.

**Comment by tcye** [comment]
another feature request: read web cookie

**Comment by FeodorFitsner** [comment]
Header could be added here: https://github.com/flet-dev/flet/blob/4673a1902a461b6e6d76e197619ac35cfb78633f/sdk/python/flet/reconnecting_websocket.py#L65-L67

What header would you need to add exactly?

**Comment by tcye** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/8703484/188790952-965201cc-1ae1-4b3c-929e-8adba7e2661d.png">

I read your blog, and in fact, I need the http header from flet client, but it seems self.wsapp only get the header from flet server

**Comment by tcye** [comment]
thank you for reply, flet is an amazing work!!!
I already found another auth method in my case, it seems to get the flet client http header not reasonable in this server driver ui framework.
