### ISSUE TITLE
Error Encrypting sensitive data (encrypt , decrypt)

### ISSUE THREAD

**Issue by Daxexs** [flet-dev/flet#2832]
**Description**

Using the `encrypt` and `decrypt` methods generates an error.

**Code example to reproduce the issue:**

```python
import flet as ft
from flet.security import encrypt

secret_key = "lW1iwuRlHeJjvBhavZfv8vnvdVFajh8e"

def index_page(page: ft.Page):
    text = ft.TextField()

    def encrypt_text(e):
        text.value = encrypt(text.value, secret_key)
        text.update()

    view_one = ft.View(
        controls=[
            ft.Text("Home page", size=30),
            text,
            ft.FilledButton("encript", on_click=encrypt_text),
        ],
        vertical_alignment=ft.MainAxisAlignment.CENTER,
        horizontal_alignment=ft.CrossAxisAlignment.CENTER,
    )

    page.views.append(view_one)
    page.go(page.route)


ft.app(index_page)
```

**Describe the results you received:**

Traceback (most recent call last):
 File "C:\Users\dxs\Desktop\xd\.venv\Lib\site-packages\flet_runtime\security\__init__.py", line 6, in <module>
 from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "c:\dxs\Desktop\xd\app\views\index.py", line 2, in <module>
 from flet.security import encrypt
 File "C:\Users\dxs\Desktop\xd\.venv\Lib\site-packages\flet\security\__init__.py", line 1, in <module>
 from flet_runtime.security import *
 File "C:\Users\dxs\Desktop\xd\.venv\Lib\site-packages\flet_runtime\security\__init__.py", line 11, in <module>
 raise Exception('Install "cryptography" Python package to use Flet security utils.')
Exception: Install "cryptography" Python package to use Flet security utils.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
```
ame: flet
Version: 0.21.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\dxs\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**
```
flet
```

**Operating system**:
Windows

**Comment by FeodorFitsner** [comment]
As exception suggests "Install "cryptography" Python package to use Flet security utils."
