### ISSUE TITLE
Calling Python from Dart/Flutter directly

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#284]
https://github.com/TimWhiting/dartpy/tree/master/dartpy
https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Doc/extending/embedding.rst
https://github.com/TimWhiting/dartpy/blob/master/dartpy/lib/src/ffi/gen.dart
https://dart.dev/guides/libraries/c-interop
https://docs.python.org/3/c-api/index.html#c-api-index
https://github.com/kivy/kivy-ios/tree/ab219f06099c9ae4a4ccd853dbe49d19309953a7/kivy_ios/tools/templates/%7B%7B%20cookiecutter.project_name%20%7D%7D-ios
https://github.com/joaoventura/pybridge-ios
https://www.google.com/search?q=PyRun_SimpleString+ios
https://docs.flutter.dev/development/platform-integration/ios/c-interop
https://github.com/beeware/Python-Apple-support
https://github.com/beeware/Python-Android-support/blob/main/USAGE.md

Native Dart extensions:
https://docs.python.org/3/extending/extending.html
https://github.com/yushulx/dart-native-extension

FFI:
https://github.com/westracer/flutter_native_opencv
https://github.com/brickpop/flutter-rust-ffi
https://stackoverflow.com/questions/64064580/importing-a-static-library-rust-a-to-flutter-project-in-ios

PyO3:
https://github.com/Infrasonics/pyo3-AppendInittab-example

**Comment by freakboy3742** [comment]
FWIW: I'm the project founder of BeeWare; if there's anything we can do to help in this space, let us know. While the BeeWare tools complement each other, we have been very explicit in *not* making them interdependent. Supporting other widget toolkits is 100% "in scope" for both Briefcase and the support packages that underpin our mobile support. If there's a change or feature that needs to be added to Briefcase to make it a viable deployment option for Flet, we're open to having the conversation.

**Comment by FeodorFitsner** [comment]
@freakboy3742 Hey Russell, great to meet you and thanks for offering your help - much appreciated!

Flutter has its [own XCode project](https://github.com/flet-dev/flet/tree/main/client/ios). Right now my understanding of the process of embedding Python into Flutter app is the following:
1) Follow [Manual way](https://github.com/beeware/Python-Apple-support/blob/main/USAGE.md#the-manual-way) of adding Python package into existing Flutter XCode project.
2) Package Python app into zip/tar and embed into Flutter app assets.
3) On Flutter app start unpack Python program to a temporary directory.
4) Using Dart FFI or [PythonKit](https://github.com/pvieito/PythonKit) start a new Python process (in a new isolate) and run a user program from temp dir. Python program drives app logic and hosts a socket server.
5) Flutter app connects to a socket server via named pipes.

Does it make sense? Is there any way Briefcase could simplify the process? What your thoughts? I'm going to play with Briefcase in the coming days.

Thank you!

**Comment by mhsmith** [comment]
> * Using Dart FFI or [PythonKit](https://github.com/pvieito/PythonKit) start a new Python process (in a new isolate) and run a user program from temp dir. Python program drives app logic and hosts a socket server.

I'm not sure if you mean starting a new OS-level process, because I thought it was impossible for an iOS app to do that. But if you start Python in a separate thread, and communicate with the main thread over a pipe, that should be no problem.

**Comment by FeodorFitsner** [comment]
@mhsmith oh right, I meant calling Python in the same process, not creating a new one, something like [this](https://github.com/TimWhiting/dartpy/blob/master/dartpy/example/dartpy_example.dart).

It's great seeing you here, Malcolm! I've been looking into Chaquopy to use on Android and now I see you guys joined efforts to offer it as a part of BeeWare suite. I'm going to start with [this Flutter package](https://pub.dev/packages/chaquopy/example) on Android.

Alright, I will try to integrate Python into Flutter app first, more precisely, I'm going to try building a [Flutter plugin](https://docs.flutter.dev/platform-integration/ios/c-interop), so other Flutter project could use it as well. Then I'll look into creating a cookiecutter template for that to use with Briefcase.

Thank you guys!

**Comment by mhsmith** [comment]
> I'm going to start with [this Flutter package](https://pub.dev/packages/chaquopy/example) on Android.

Yes, that's a good place to start experimenting. However, I shoudl warn you that it's an unofficial package from a third party, and it's quite limited and inefficient. In the long-term, a better solution would be to provide a Flutter interface to [Chaquopy's Java API](https://chaquo.com/chaquopy/doc/current/java.html).
