### ISSUE TITLE
Scrolling in a tab isn't smooth in Windows

### ISSUE THREAD

**Issue by YouCantCMe** [flet-dev/flet#2840]
Using the latest pre release of Flet in Windows 10, scrolling with your middle mouse isn't smooth in a tab. Video below:

https://github.com/flet-dev/flet/assets/73901163/508ae350-8100-4ce6-b364-19c2ca941ee2

Example code:

```import flet as ft

def main(page: ft.Page):
    page.window_resizable = False
    page.window_width = 400
    page.window_height = 300
    text = ft.Text("Hello, world!")
    container = ft.Container(
        ft.Text("Container"),
        alignment=ft.alignment.top_left,
        col=ft.colors.BLACK,
        height=400,
        key="C",
    )
    text2 = ft.Text("Hello, world!")

    col_content = ft.Column(controls=[text,container,text2], scroll=True)

    tabs = ft.Tabs(
        expand=1,
        tabs=[
            ft.Tab(
                text="Example",
                content=ft.Container(
                    content=col_content,
                ),
            ),
        ],
    )

    page.add(tabs)

ft.app(target=main)

**Comment by Klu1d** [comment]
To achieve smooth scrolling, the documentation suggests using ft.ListView https://flet.dev/docs/controls/listview/

**Comment by burhansvural** [comment]
> Using the latest pre release of Flet in Windows 10, scrolling with your middle mouse isn't smooth in a tab. Video below:
> 
>  Code_dxtEg4dCeZ.mp4 
> Example code:
> 
> ```
> 
> def main(page: ft.Page):
>     page.window_resizable = False
>     page.window_width = 400
>     page.window_height = 300
>     text = ft.Text("Hello, world!")
>     container = ft.Container(
>         ft.Text("Container"),
>         alignment=ft.alignment.top_left,
>         col=ft.colors.BLACK,
>         height=400,
>         key="C",
>     )
>     text2 = ft.Text("Hello, world!")
> 
>     col_content = ft.Column(controls=[text,container,text2], scroll=True)
> 
>     tabs = ft.Tabs(
>         expand=1,
>         tabs=[
>             ft.Tab(
>                 text="Example",
>                 content=ft.Container(
>                     content=col_content,
>                 ),
>             ),
>         ],
>     )
> 
>     page.add(tabs)
> 
> ft.app(target=main)
> ```

There is not enough data inside to scroll. Try it like this:
```python
import flet as ft

def main(page: ft.Page):
    page.window_resizable = False
    page.window_width = 400
    page.window_height = 300
    text = ft.Text("Hello, world!")
    container = ft.Container(
        ft.Text("Container"),
        alignment=ft.alignment.top_left,
        col=ft.colors.BLACK,
        height=400,
        key="C",
    )
    text2 = ft.Text("Hello, world!")

    col_content = ft.Column(
        controls=[
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            text,
            container,
            text2],
        scroll=ft.ScrollMode.ALWAYS
    )

    tabs = ft.Tabs(
        expand=1,
        tabs=[
            ft.Tab(
                text="Example",
                content=ft.Container(
                    content=col_content,
                ),
            ),
        ],
    )

    page.add(tabs)

ft.app(target=main)
```

**Comment by YouCantCMe** [comment]
> To achieve smooth scrolling, the documentation suggests using ft.ListView https://flet.dev/docs/controls/listview/

It still doesn't scroll smoothly using the middle mouse wheel with the provided example.

**Comment by saceweg970** [comment]
Same thing happens to me too with a laptop touchpad. This ONLY happens in windows. In linux it works perfectly.

More information. The scroll does work, but every "swipe" is interpreted as a single "impulse".  You swipe up, it moves a little bit. You have to lift the fingers and swipe again... and it moves a little bit more. 
I have tried it with multiple controls including the given example from [burhansvural](https://github.com/burhansvural).

**Comment by anamite** [comment]
Hey, was anyone able to solve it?
For me the scrolling is not smooth using the touch pad on my laptop (mouse), the normal mouse wheel works fine.

**Comment by Abacux** [comment]
I have the same problem with the touchpad & when trying to drag the scrollbar in windows. In Mac the same code works perfectly. I need to solve this

**Comment by ndonkoHenri** [comment]
Closing in favour of #3963
