### ISSUE TITLE
SegmentedButton : missing empty_selection_allowed flag. 

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2844]
**Description**
When testing the SegmentedButton, I found that the empty_selection_allowed attribute doesn't exit even though it is listed in the documentation. 

**Code example to reproduce the issue:**

```
import flet as ft

def main(page: ft.Page):
    like_btn=  ft.SegmentedButton(
            empty_selection_allowed = True,
            segments=[
                ft.Segment(
                    value="1",
                    label=ft.Text("1"),
                    icon=ft.Icon(ft.icons.THUMB_UP_ALT_OUTLINED),
                ),
               
                ft.Segment(
                    value="4",
                    label=ft.Text("0"),
                    icon=ft.Icon(ft.icons.THUMB_DOWN_ALT_OUTLINED),
                ),
            ],
        )
    
    page.add(like_btn)

ft.app(main)
```

**Describe the results you received:**
"""
 result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\layout_test\test2.py", line 4, in main
    like_btn=  ft.SegmentedButton(
               ^^^^^^^^^^^^^^^^^^^
TypeError: SegmentedButton.__init__() got an unexpected keyword argument 'empty_selection_allowed'
"""

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.21.1
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:
Windows 11
Python 3.12.1

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Thanks for reporting - the docs have a mistake. The prop is instead called `allow_empty_selection`. The other one is `allow_multiple_selection`.

Will you like to contribute by opening a PR that modifies that?

**Comment by lekshmanmj** [comment]
I've submitted a PR.

**Comment by ndonkoHenri** [comment]
PR approved and merged, thanks!
