### ISSUE TITLE
 Feature Request: Video Rotation and Playback Speed Controls

### ISSUE THREAD

**Issue by jundaychan** [flet-dev/flet#2873]
Description:

Hello flet-dev team,

I am interested in implementing advanced playback controls for a video player within my application, specifically features for rotating video content and adjusting the playback speed. I believe these features would greatly enhance the user experience by providing more control over hoGw content is viewed.

Problem to be Solved:

Currently, the video player component does not support rotation or playback speed adjustments. This limits the functionality and usability of the player, especially in scenarios where users may want to view videos in different orientations or at varied speeds for better understanding or entertainment purposes.

Suggested Solution:

I propose the addition of two new features to the video player component:

Video Rotation: The ability to rotate the video by a specified number of degrees (e.g., 90, 180, 270). This could be implemented as a setting within the player's configuration options.

Playback Speed Control: The capability to adjust the playback speed of the video, with common options like 0.5x (slower), 1x (normal), 1.5x, 2x (faster), etc. This feature should allow users to select their preferred speed from a user interface control.

Technical Implementation:

For the technical implementation, the video player component could utilize existing libraries or APIs that support these functionalities. For example, on mobile platforms, the AVFoundation framework (iOS) or ExoPlayer (Android) offer the necessary controls for rotation and speed adjustment.

Tradeoffs and Considerations:

The addition of these features may slightly increase the complexity of the video player component and could potentially affect performance, depending on the underlying implementation.
It is important to ensure that the user interface remains intuitive and that these new controls do not clutter the player's interface.
Comparison:

While there may be alternative approaches to achieving similar functionality, the proposed solution focuses on integrating these features in a way that is consistent with the existing design and user experience of the flet framework.

I believe these features would be valuable additions to the flet ecosystem and would appreciate any feedback or guidance on how to proceed with their implementation.

Thank you for considering this feature request.

**Comment by lekshmanmj** [comment]
[https://flet.dev/docs/controls/video#basic-example](url)
please read this doc... you can control playback rate
Use ```rotate``` property in ft.Video for video ratation.

**Comment by jundaychan** [comment]
![image](https://github.com/flet-dev/flet/assets/64624927/a29c3b2a-1320-4c35-9bfa-82b411917f8a)


> [https://flet.dev/docs/controls/video#basic-example](url) please read this doc... you can control playback rate Use `rotate` property in ft.Video for video ratation.

thx，i used rotate .Using this, the entire player is rotated, not the video itself

**Comment by ndonkoHenri** [comment]
> Video Rotation: The ability to rotate the video by a specified number of degrees (e.g., 90, 180, 270). This could be implemented as a setting within the player's configuration options.

The [media_kit](https://github.com/media-kit/media-kit) package we use to render the video doesn't seem to have this feature yet. You can instead [open an issue](https://github.com/media-kit/media-kit/issues/new/choose) on their repo, and when it will be added, we will be able to implement it in Flet.

**Comment by ndonkoHenri** [comment]
Playback rate can already be modified as mentioned above by @lekshmanmj.
https://flet.dev/docs/controls/video/#playback_rate
