### ISSUE TITLE
My image is only appearing in app mode. When I turn the script to webview, It disappears!

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#2875]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft
from pathlib import Path
dir=f'{Path(__file__).parent}\\atelier-costura\\manual\\logo-3.jpg'
print(dir)

def main(page: ft.Page):
    page.title = "Images Example"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = 50
    page.update()

    img = ft.Image(
        src=dir,
        width=80,
        height=80,
        fit=ft.ImageFit.COVER,
        border_radius=1,
    )
    texto=ft.Text('   Atelier Dalci',font_family='tahoma',size=30,color=ft.colors.BROWN_700, )
    cabeçalho=ft.Row(controls=[img,texto])

    page.add(cabeçalho)

    page.update()

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Can you try specifying the assets dir: https://flet.dev/docs/controls/image#src

**Comment by jvalle63** [comment]
Thank you [ndonkoHenri

> Can you try specifying the assets dir: https://flet.dev/docs/controls/image#src

Thank You a lot. It worked on my computer, but not on the server. I'm using Replit...

**Comment by ndonkoHenri** [comment]
Can you share a link to that replit project?

**Comment by jvalle63** [comment]
I just solved the thing ! I created a folder called "Imagens" (image in portuguese...)

The Code:

import flet as ft
from pathlib import Path

assets = f'{Path(__file__).parent}'
print(assets)
logo = 'Imagens/logo-4.jpg'
print(dir)


def main(page: ft.Page):
  page.title = "Images Example"
  page.theme_mode = ft.ThemeMode.LIGHT
  page.padding = 50
  page.update()

  img = ft.Image(
      src=logo,
      width=80,
      height=80,
      fit=ft.ImageFit.CONTAIN,
      border_radius=1,
  )
  texto = ft.Text(
      'Atelier Tesoura Mágica',
      font_family='tahoma',
      size=20,
      color=ft.colors.PINK,
  )
  #cabeçalho=ft.Row(controls=[img,texto])
  cabecalho = ft.ResponsiveRow([
      ft.Column(col={
          "xs": 4,
          "sm": 3,
          "md": 2,
          "xl": 1
      }, controls=[img]),
      ft.Column(col={
          "xs": 8,
          "sm": 6,
          "md": 5,
          "xl": 4
      }, controls=[texto]),
  ],
                               vertical_alignment=ft.CrossAxisAlignment.CENTER,
                               alignment='left')
  page.add(cabecalho)

  page.update()


#ft.app(target=main)
ft.app(target=main, view=ft.AppView.WEB_BROWSER, assets_dir=assets)

**Comment by ndonkoHenri** [comment]
Nice.
Can we close the issue then?

**Comment by jvalle63** [comment]
Yep
