### ISSUE TITLE
window_maximizable  is no work on ubuntu

### ISSUE THREAD

**Issue by ssz25** [flet-dev/flet#2885]
page.window_height=300
    page.window_width=300
    page.window_resizable =False
    page.window_maximizable = False
    page.update()

start the proc    ubuntu desktop   

page.window_maximizable   don't work on init proc

is work OK on windows

**Comment by ndonkoHenri** [comment]
The window_manager package used for this purposes documented that this prop is Windows and macOS only: https://github.com/leanflutter/window_manager?tab=readme-ov-file#ismaximizable--macos--windows

**Comment by burhansvural** [comment]
It works fine on Debian 12.
