### ISSUE TITLE
Flet build apk fails when integrating Gemini and ChatGpt API.

### ISSUE THREAD

**Issue by afsal-afzz** [flet-dev/flet#2895]
I am facing issues when I integrate gemini and chatgpt api and using the flet build apk command. The api works on local host but freezes during build. I have raised a similar issue earlier but did not receive adequate feedback. 
Additional note: all of the flet build commands do not work when using those api's.

flet 0.21.0
Python 3.12.0
Windows 11

**Comment by yunguangli** [comment]
Try firstly upgrade to python 3.12.2.  3.12.0 has some serious known bugs.

**Comment by afsal-afzz** [comment]
Thanks I'll do that

**Comment by ndonkoHenri** [comment]
When opening a issue (bug) please make sure to provide all information as required by the bug-report template. We cannot guess...
