### ISSUE TITLE
FilledButton not having bgcolor param but bgcolor can be set externally

### ISSUE THREAD

**Issue by emilrueh** [flet-dev/flet#2902]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    def crash_app(event):
        button = ft.FilledButton(text="I'm broken", bgcolor="blue")
        page.add(button)

    button = ft.FilledButton(text="Break me", on_click=crash_app)
    button.bgcolor = "red"

    page.add(button)


if __name__ == "__main__":
    ft.app(target=main)

```

**Describe the results you received:**

I'm getting the error `TypeError: FilledButton.__init__() got an unexpected keyword argument 'bgcolor'` when providing bgcolor as a param.

**Describe the results you expected:**

I would expect this button to have a bgcolor parameter to change the color as it is possible to use bgcolor with it when writing button.bgcolor = "red"

**Additional information you deem important (e.g. issue happens only occasionally):**
Sorry if this was already resolved in any updates but I did not find a closed issue on that yet.

**Flet version (`pip show flet`)**:

```
 0.19.0
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet==0.19.0
openai==1.10.0
Pillow==10.2.0
python-dotenv==1.0.1

```

**Operating system**:

Windows 11

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Change it's bgcolor through it's `style` prop.
