### ISSUE TITLE
White Screen only

### ISSUE THREAD

**Issue by Harfho** [flet-dev/flet#2913]
upon running the counter.py flet example in the tutorial it run but only display white screen and it work well on browser

**Code example to reproduce the issue:**
![image](https://flet.dev/docs/#flet-app-example)

**Describe the results you received:**

![image](https://github.com/flet-dev/flet/assets/39716223/85d236ce-dec7-430a-9a53-369d92fc752c)

**Describe the results you expected:**
![image](https://github.com/flet-dev/flet/assets/39716223/18038c09-88e1-4f6b-b549-5d42e89fcd53)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
flet                  0.21.2
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
Package               Version
--------------------- --------------
annotated-types       0.6.0
anyio                 4.3.0
arrow                 1.3.0
binaryornot           0.4.4
certifi               2024.2.2
chardet               5.2.0
charset-normalizer    3.3.2
click                 8.1.7
colorama              0.4.6
cookiecutter          2.6.0
exceptiongroup        1.2.0
fastapi               0.110.0
flet                  0.21.2
flet-core             0.21.2
flet-runtime          0.21.2
h11                   0.14.0
httpcore              1.0.4
httptools             0.6.1
httpx                 0.27.0
idna                  3.6
Jinja2                3.1.3
markdown-it-py        3.0.0
MarkupSafe            2.1.5
mdurl                 0.1.2
oauthlib              3.2.2
packaging             23.2
pip                   24.0
pydantic              2.6.4
pydantic_core         2.16.3
Pygments              2.17.2
pypng                 0.20220715.0
python-dateutil       2.9.0.post0
python-dotenv         1.0.1
python-slugify        8.0.4
PyYAML                6.0.1
qrcode                7.4.2
repath                0.9.0
requests              2.31.0
rich                  13.7.1
setuptools            69.1.1
six                   1.16.0
sniffio               1.3.1
starlette             0.36.3
text-unidecode        1.3
types-python-dateutil 2.9.0.20240316
typing_extensions     4.10.0
urllib3               2.2.1
uvicorn               0.28.1
watchdog              4.0.0
watchfiles            0.21.0
websockets            12.0
wheel                 0.42.0
```

**Operating system**:

window 11

**Additional environment details:**

**Comment by ShikoThePro** [comment]
the same issue happened to me.and I have searched a lot but there is no solution.
**The flet team must tell us how to solve this problem**

**Comment by lekshmanmj** [comment]
please provide code sample to reproduce issue.

**Comment by ShikoThePro** [comment]
And me when I run the same code  a white screen is displayed then the program exit immediately

**Comment by ndonkoHenri** [comment]
Closing in favor of #3511

**Comment by Harfho** [comment]
> Closing in favor of #3511

The tag #3511 is no more

**Comment by aizimuji** [comment]
i think it's win11 issue , you can try it on win10
