### ISSUE TITLE
Error with 'flet build apk --verbose'

### ISSUE THREAD

**Issue by lurdray** [flet-dev/flet#2938]
Flutter bootstrap directory: /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/flet_flutter_build_6HXfbDb24Q
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['/Users/temi/Desktop/desktop1//RayFlutter/flutter/bin/dart', 'run', 'flutter_launcher_icons']
Resolving dependencies in /private/var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/flet_flutter_build_6HXfbDb24Q... (5.5s)
Got dependencies in /private/var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/flet_flutter_build_6HXfbDb24Q.
Building package executable... (3.0s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...              done
Creating Icons for Windows...          done
Creating Icons for MacOS...            done

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['/Users/temi/Desktop/desktop1//RayFlutter/flutter/bin/dart', 'run', 'flutter_native_splash:create']
Building package executable... (3.3s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['/Users/temi/Desktop/desktop1//RayFlutter/flutter/bin/dart', 'run', 'serious_python:main', 'package', 
'/Users/temi/Desktop/RayFlet/fresh/shopowner_app', '--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', 
'--exclude', 'build']
Building package executable... (1.5s)
Built serious_python:main.
Running package command
Creating asset directory: /private/var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/flet_flutter_build_6HXfbDb24Q/app
Copying Python app from /Users/temi/Desktop/RayFlet/fresh/shopowner_app to /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/serious_python_temp8W2Yqe
Configured mobile platform with sitecustomize.py at /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/serious_python_sitecustomizenhYQiF/sitecustomize.py
Installing dependencies [, flet-embed, pillow, requests] with pip command to /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/serious_python_temp8W2Yqe/__pypackages__
Downloading Python distributive from https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-apple-darwin-install_only.tar.gz to /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/cpython-3.11.6+20231002-x86_64-apple-darwin-install_only.tar.gz
Error: ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = objects.githubusercontent.com, port = 65264, uri=https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-apple-darwin-install_only.tar.gz
Deleting temp directory /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/serious_python_temp8W2Yqe
Deleting sitecustomize directory /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/serious_python_sitecustomizenhYQiF
Deleting Python directory /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/hostpython3.11_3i66SN
_**Deleting Flutter bootstrap directory /var/folders/0z/j9wwzxsj2k3fz7gft1ws_kkc0000gn/T/flet_flutter_build_6HXfbDb24Q**_
Flet app package app/app.zip was not created.

**Comment by lurdray** [comment]
I used verbose to be able to view the logs.
From the logs, I strongly think the execution of "Deleting Flutter bootstrap directory" terminates the building process.

Any help ?

**Comment by ndonkoHenri** [comment]
> Installing dependencies [, flet-embed, pillow, requests] with pip command

Pillow is a native package, so you have to follow this guide: https://flet.dev/docs/guides/python/packaging-app-for-distribution#native-python-packages

**Comment by lurdray** [comment]
I have removed pillow, I still get the same error

**Comment by ndonkoHenri** [comment]
Can you share your `requirements.txt` ?

**Comment by lurdray** [comment]
flet 
just flet

**Comment by ndonkoHenri** [comment]
> I have removed pillow, I still get the same error

Can you share exactly what you get?

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/3839
