### ISSUE TITLE
ошибка при flet build windows

### ISSUE THREAD

**Issue by p3rf0rm** [flet-dev/flet#2956]
![photo_2024-03-27_16-22-52](https://github.com/flet-dev/flet/assets/165153398/1ab9df0d-956a-490a-85e2-d7d7b550a9f6)
пробовал разные версии flet а так же flutter sdk

Версия flutter:
Flutter is already up to date on channel beta
Flutter 3.21.0-1.0.pre.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c398442c35 (2 weeks ago) • 2024-03-12 22:26:24 -0700
Engine • revision 0d4f78c952
Tools • Dart 3.4.0 (build 3.4.0-190.1.beta) • DevTools 2.33.1

Версия Flet:
flet 0.21.2

flet build windows
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...OK
Building Windows app...Resolving dependencies...
  file_picker 6.2.1 (8.0.0+1 available)
  fl_chart 0.65.0 (0.66.2 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_native_splash 2.3.7 (2.4.0 available)
  js 0.6.7 (0.7.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  package_info_plus 4.2.0 (6.0.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 4.0.2 (5.0.0 available)
  toml 0.14.0 (0.15.0 available)
  vm_service 14.0.0 (14.2.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
13 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...
Building Windows application...                                   214,8s

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\format(42): warning
STL4038: The contents of <format> are available only with C++20 or later.
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\plugins\serious_python_windows\serious_python_wind
ows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: ��室 �� �������
"setlocal [D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: "C:\Program Files
(x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
-DBUILD_TYPE=Release -P cmake_install.cmake
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq
0 goto :cmEnd [D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmEnd
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: endlocal & call
:cmErrorLevel %errorlevel% & goto :cmDone
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmErrorLevel
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: exit /b %1
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmDone
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq
0 goto :VCEnd [D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :VCEnd" � ����� 1.
[D:\programTEMP\TEMP\flet_flutter_build_hrojhGWESn\build\windows\x64\INSTALL.vcxproj]
Build process failed.

Error building Flet app - see the log of failed command above.

**Comment by p3rf0rm** [comment]
decided

**Comment by Azka79** [comment]
I have the same problem in file 0.22.0, how did you solve it ?

Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...OK
Building Windows app...Resolving dependencies...
  file_picker 6.2.1 (8.0.2 available)
  fl_chart 0.65.0 (0.67.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_markdown 0.6.23 (0.7.1 available)
  flutter_native_splash 2.3.7 (2.4.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.3 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  package_info_plus 4.2.0 (8.0.0 available)
  package_info_plus_platform_interface 2.0.1 (3.0.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 4.0.2 (5.0.1 available)
  test_api 0.6.1 (0.7.1 available)
  toml 0.14.0 (0.15.0 available)
  vm_service 13.0.0 (14.2.1 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...
Building Windows application...                                   183.9s

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\ZERO_CHECK.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\serious_python_windows\CopyPythonDLLs.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\flutter\flutter_wrapper_app.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\flutter\flutter_wrapper_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\screen_retriever\screen_retriever_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\serious_python_windows\serious_python_windows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\format(42): warning STL4038: The contents of <format> are available only with C++20 or later.   
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\serious_python_windows\serious_python_windows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\window_manager\window_manager_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\plugins\window_to_front\window_to_front_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\runner\ecg_morphology.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\ALL_BUILD.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(542,5): warning MSB8029: The Intermediate directory or Output directory      
cannot reside under the Temporary directory as it could lead to issues with incremental build.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: The command "setlocal
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd 
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmEnd
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto    
:cmDone [C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmErrorLevel
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: exit /b %1
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmDone
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :VCEnd" exited with code 1.
[C:\Users\nadiy\AppData\Roaming\Local\Temp\flet_flutter_build_tbbaRWH22R\build\windows\x64\INSTALL.vcxproj]
Build process failed.

Error building Flet app - see the log of failed command above.
