### ISSUE TITLE
Information missing from linked page #packaging-as-a-desktop-app

### ISSUE THREAD

**Issue by Coolspotcreative** [flet-dev/flet#2962]
The page: https://flet.dev/docs/tutorials/python-calculator/#packaging-as-a-desktop-app

has the line:
`[Follow these instructions](https://flet.dev/docs/guides/python/getting-started#packaging-a-desktop-app) to package your Calculator app into an executable.`

The linked page does not contain the information. The Table of contents for the page is:
[Installing flet module](https://flet.dev/docs/guides/python/getting-started#installing-flet-module)
[Linux](https://flet.dev/docs/guides/python/getting-started#linux)
[WSL](https://flet.dev/docs/guides/python/getting-started#wsl)
[Basic app structure](https://flet.dev/docs/guides/python/getting-started#basic-app-structure)
[Controls](https://flet.dev/docs/guides/python/getting-started#controls)
[visible property](https://flet.dev/docs/guides/python/getting-started#visible-property)
[disabled property](https://flet.dev/docs/guides/python/getting-started#disabled-property)
[Control Refs](https://flet.dev/docs/guides/python/getting-started#control-refs)

The packaging of web apps from the same stating page also thinks to the same page which doesn't provide the information it is meant to be linking to.

**Comment by ndonkoHenri** [comment]
I think this has been fixed.
