### ISSUE TITLE
Issue when specifying a height value for a dropdown 

### ISSUE THREAD

**Issue by EasyDevv** [flet-dev/flet#2965]
**Description**

![flet_dropdown](https://github.com/flet-dev/flet/assets/11148818/102f24e3-7232-4b56-8bf6-6a772fc80c04)

When specifying a height value for a dropdown, 
the arrow buttons are oriented incorrectly and 
no text is displayed when selected.

**Code example to reproduce the issue:**

```python
ft.Dropdown(
    options=[
        ft.dropdown.Option("Default"),
        ft.dropdown.Option("Default"),
        ft.dropdown.Option("Default"),
    ],
),
ft.Dropdown(
    height=38,
    options=[
        ft.dropdown.Option("Height 25"),
        ft.dropdown.Option("Height 25"),
        ft.dropdown.Option("Height 25"),
    ],
),
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.21.1
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

Windows 11

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
You need to set the content padding: https://youtu.be/esQAs998J5U
