### ISSUE TITLE
TextField border_radius flag doesn't work

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2966]
**Description**
I tried to curve the corners of a textfield by using border_radius. It doesn't work. I have put the textfield into a container to achieve the effect. 

**Code example to reproduce the issue:**

```
import flet as ft

def main(page: ft.Page):
    page.title = "plant demo"
    page.bgcolor = ft.colors.GREEN
    page.padding = ft.padding.all(0)

    search_tf = ft.TextField(
        bgcolor=ft.colors.WHITE,
        border_radius=ft.border_radius.all(50),
        height=54,
        width=320,
        border=ft.InputBorder.NONE,
        hint_text="Search",
        hint_style=ft.TextStyle(color=ft.colors.GREY),
        suffix_icon=ft.icons.SEARCH,
        
    )

    page.add(search_tf)


if __name__ == "__main__":
    ft.app(target=main, view=ft.AppView.WEB_BROWSER)

```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.21.2
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:
Windows 11, 
Python 3.12.2

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
This is because of `border=ft.InputBorder.NONE,`. For the border radius to have a visual effect, you need to use the `OUTLINED` border (which is the default).
