### ISSUE TITLE
PathAccessException: Deletion failed, path = 'C:\Users\User\AppData\Local\Temp\ld_tool-1.0.0-1\app' (OS Error: The process cannot access the file because it is being used by another process. , errno = 32)

### ISSUE THREAD

**Issue by trymenghuy** [flet-dev/flet#2969]
After close and open window application

**Comment by ndonkoHenri** [comment]
Please fill the issue template by providing all the asked information.

**Comment by trymenghuy** [comment]
I just wonder if there is any solution to avoid this exception. It happens when i copy build/window to another location and run it. I have to restart my pc to run it again because i can't find and kill that process.

**Comment by jundaychan** [comment]
i have same question

**Comment by ndonkoHenri** [comment]
Please give the latest Flet version a try. If you happen to still face this problem, open a new issue with all the details.
