### ISSUE TITLE
RichText Control

### ISSUE THREAD

**Issue by hevirbek** [flet-dev/flet#297]
From time to time, we may want to keep different parts of the text in a different style, and there is no solution other than using `Row`for this, but this solution is not very efficient either. It would be better if there is an extra control like `RichText` in Flutter. This `RichText`can have a `Text` or `TextSpan `list parameter named `controls`.

**Comment by FeodorFitsner** [comment]
Related to https://github.com/flet-dev/flet/issues/188

**Comment by FeodorFitsner** [comment]
https://api.flutter.dev/flutter/widgets/RichText-class.html

**Comment by FeodorFitsner** [comment]
Implemented: https://flet.dev/docs/controls/text#rich-text-basics
