### ISSUE TITLE
Click the alert dialog appears correctly, the ft.Row automatically scrolls up to the top on its own?

### ISSUE THREAD

**Issue by freevid32** [flet-dev/flet#2977]
I'm encountering an issue with flet_fastapi. I've created an ft.Row with the "scroll" and "wrap" properties, and I'm dynamically generating data from MySQL to display it in three columns with wrapping rows. The scrolling behavior is working as intended. However, when I scroll down to the bottom of the rows and click the button in the last column, even though the alert dialog appears correctly, the ft.Row automatically scrolls up to the top on its own. I'd like to prevent this behavior and keep the ft.Row at the same position after clicking the button.

<img width="1422" alt="Screenshot 2567-04-03 at 20 29 30" src="https://github.com/flet-dev/flet/assets/141158128/0ff31aad-ede8-4483-934c-2069f7ae4b8c">

<img width="1425" alt="Screenshot 2567-04-03 at 20 29 16" src="https://github.com/flet-dev/flet/assets/141158128/6fc6274e-cc2d-4b27-b9f0-f28e79ad9dc0">

**Comment by freevid32** [comment]
Videos

https://github.com/flet-dev/flet/assets/141158128/8b9225ce-c646-445e-9757-95861bf65feb

**Comment by freevid32** [comment]
Ok. I got resolved, Thank you.


https://github.com/flet-dev/flet/assets/141158128/404c7b3f-efe9-4638-b2fc-8b8671c2c724

**Comment by ndonkoHenri** [comment]
Please share runnable code as required by the issue template.
