### ISSUE TITLE
Retrieving key objects from a Dropdown menu

### ISSUE THREAD

**Issue by cmas1** [flet-dev/flet#2979]
I have been playing around with the Dropdown control, and there is something that I can't quite figure out.
I can populate the options of the Dropdown menu using some instances from  class I defined and wrapping them with a ft.Option ft.Option(key=my_object, text=my_string)  where the my_string is the message that is displayed on the menu.

Here is a code example:

```python
import flet as ft

class TestClass:
    def __init__(self, id, name):
        self.id = id
        self.name = name

def main(page: ft.Page):
    def option_selected(e):
        t.value = f"Dropdown value is:  {dd.value} and its type is {type(dd.value)}"
        t2.value = f"Dropdown options[0].key is {dd.options[0].key} and its type is {type(dd.options[0].key)}"
        page.update()

    test1 = TestClass(1, "John")
    test2 = TestClass(2, "Logan")
    test3 = TestClass(3, "Rey")

    t = ft.Text()
    t2 = ft.Text()
    dd = ft.Dropdown(
        width=100,
        options=[
            ft.dropdown.Option(key=test1, text=test1.name),
            ft.dropdown.Option(key=test2, text=test2.name),
            ft.dropdown.Option(key=test3, text=test3.name),
        ],
        on_change=option_selected
    )
    page.add(dd, t, t2)

ft.app(target=main)
```
       

When I retrieve the selected option from the menu using the value attribute, instead of getting the object (which I can see is listed in the options) I get its associated string given by the  dunder repr method.

![image](https://github.com/flet-dev/flet/assets/19671250/4ca254d9-a4f8-401e-932a-3bd4f36860e6)

Is there a way to get the actual object or perhaps the index of the selected option ?

**Comment by taaaf11** [comment]
The `value` property of `Dropdown` gives the `key` property of `Option` class. It is okay, you ARE getting the object itself. What is the problem? Maybe you want  `dd.value.name` in the t1?

**Comment by cmas1** [comment]
Thank you for the reply.  What you are saying about how the `value` property works is what I expected, but it is not what I am experiencing. From what I can see, when I ask for the value of the dropdown option, either from the `dd` object itself or from the event `e`, it returns the string representation of the object, as you can see in my previous screen where I printed the type returned.

In fact, if I define the `__str__()` method for the test class, the value printed on screen it is exactly that string.
![image](https://github.com/flet-dev/flet/assets/19671250/21c04b3a-da3f-497f-aeeb-a422c7ff9644)
![image](https://github.com/flet-dev/flet/assets/19671250/95d90ee5-8f4a-4b9d-944b-fad34d03ced8)

My problem, is that if my class has some method that I need to invoke on the instance of the object (for example the method `hello()` in the following example), I cannot do it because the value I get from the dropdown is a string.
![image](https://github.com/flet-dev/flet/assets/19671250/20b1eb1e-3c76-4573-8f61-b20d2f72048a)
![Screenshot 2024-04-11 at 15 10 46](https://github.com/flet-dev/flet/assets/19671250/08474e16-4e33-4b41-b9bb-03650e7eda63)

Perhaps this example explains my problem more clearly.

**Comment by cmas1** [comment]
That  works, thank you for the tip. 

Still, I think that it would be neat (and much more streamlined) to be able to retrieve the object directly from the dropdown (which has a `key` property that currently is always `None`), without having an on_click event handler for each option.
Hence why I opened this thread as a feature request, and not a bug. 
I appreciate the work that is done here, so just take this as a feedback, not a complaint.

**Comment by taaaf11** [comment]
I agree

**Comment by ndonkoHenri** [comment]
You can store the object in `Option.data` and retrieve it though `e.control.data` returned by `Option.on_click`.
`Option.key` and `.text` are meant to store strings, not objects.

**Comment by CoutinhoElias** [comment]
For anyone struggling with not being able to reset/clear the dropdown:
[https://github.com/flet-dev/flet/issues/4719#issuecomment-2826639759](https://github.com/flet-dev/flet/issues/4719#issuecomment-2826639759)
