### ISSUE TITLE
Add flutter SelectableText widget

### ISSUE THREAD

**Issue by sgrefen** [flet-dev/flet#2982]
**Please Describe The Problem To Be Solved**

I need access to selected text in a Text or Markdown element from a flet app. Flutter provides the SelectableText widget for this and from my research it seems to be only option in Flutter.

**Comment by FeodorFitsner** [comment]
`Text` control in Flet already has [`selectable` property](https://flet.dev/docs/controls/text#selectable) which turns the control to SelectableText.

Are you looking for the way to work with selection (like [onSelectionChanged](https://api.flutter.dev/flutter/material/SelectableText/onSelectionChanged.html))?

**Comment by sgrefen** [comment]
Yes, I'm looking for onSelectionChanged (didn't know setting selectable has this effect, using it so cut&paste in the browser works). I'm on 0.21.2. Just found that SelectionArea got a on_change in https://github.com/flet-dev/flet/pull/2882 .

**Comment by ndonkoHenri** [comment]
You can do the following(with the latest Flet prerelease or the upcoming v0.22.0):
```py
import flet as ft

def main(page: ft.Page):
    page.add(
        ft.SelectionArea(
            ft.Text("This is some selectable text.!"),
            on_change=lambda e: print(e.data),
        )
    )

ft.app(target=main)
```
