### ISSUE TITLE
gradle error when trying to built flet app

### ISSUE THREAD

**Issue by coolninjaturtle** [flet-dev/flet#2987]
Below is the error I get when I try to build my flet app for android. I don't understand what's wrong can someone pls help.

C:\Users\ishaa\Python Programs\final_ia>flet build apk --no-android-splash --verbose
Flutter bootstrap directory: C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\dart.BAT', 'run',
'flutter_launcher_icons']
Resolving dependencies in C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih... (5.5s)
Got dependencies in C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih.
Building package executable... (4.1s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\dart.BAT', 'run',
'flutter_native_splash:create']
Building package executable... (3.7s)
Built flutter_native_splash:create.
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\dart.BAT', 'run',
'serious_python:main', 'package', 'C:\\Users\\ishaa\\Python Programs\\final_ia', '--mobile', '--platform', 'mobile',
'--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
Building package executable... (2.2s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih\app
Copying Python app from C:\Users\ishaa\Python Programs\final_ia to C:\Users\ishaa\AppData\Local\Temp\serious_python_tempc098dc1
Configured mobile platform with sitecustomize.py at C:\Users\ishaa\AppData\Local\Temp\serious_python_sitecustomizec232f01b\sitecustomize.py
Installing dependencies [flet-embed] with pip command to C:\Users\ishaa\AppData\Local\Temp\serious_python_tempc098dc1\__pypackages__
Extracting Python distributive from C:\Users\ishaa\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\ishaa\AppData\Local\Temp\hostpython3.11_ce261ec8
Compiling Python sources at C:\Users\ishaa\AppData\Local\Temp\serious_python_tempc098dc1
Delete unnecessary files with extensions: [.py, .c, .h, .typed, .exe, .so, .a, .pdb, .pyd, .dll]
Delete unnecessary files and directories: [__pycache__, bin]
Creating app archive at C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih\app/app.zip from C:\Users\ishaa\AppData\Local\Temp\serious_python_tempc098dc1
Deleting temp directory C:\Users\ishaa\AppData\Local\Temp\serious_python_tempc098dc1
Deleting sitecustomize directory C:\Users\ishaa\AppData\Local\Temp\serious_python_sitecustomizec232f01b
Deleting Python directory C:\Users\ishaa\AppData\Local\Temp\hostpython3.11_ce261ec8
OK
Building .apk for Android...
Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\flutter.BAT', 'build', 'apk']
Resolving dependencies...
  file_picker 6.2.1 (8.0.0+1 available)
  fl_chart 0.65.0 (0.67.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_native_splash 2.3.7 (2.4.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  package_info_plus 4.2.0 (6.0.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 4.0.2 (5.0.0 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  vm_service 13.0.0 (14.2.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih\android\settings.gradle' (C:\Users\ishaa\.gradle\caches\7.5\scripts\ceutkedvmknyol2k1s26p1ap).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleRelease'...                         2,033ms

┌─ Flutter Fix ───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project's Gradle version is incompatible with the Java version that Flutter is using for Gradle.           │
│                                                                                                                     │
│ If you recently upgraded Android Studio, consult the migration guide at                                             │
│ docs.flutter.dev/go/android-java-gradle-error.                                                                      │
│                                                                                                                     │
│ Otherwise, to fix this issue, first, check the Java version used by Flutter by running `flutter doctor --verbose`.  │
│                                                                                                                     │
│ Then, update the Gradle version specified in                                                                        │
│ C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih\android\gradle\wrapper\gradle-wrapper.properties to │
│ be compatible with that Java version. See the link below for more information on compatible Java/Gradle versions:   │
│ https://docs.gradle.org/current/userguide/compatibility.html#java                                                   │
│                                                                                                                     │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
Deleting Flutter bootstrap directory C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_WOequ5Z2Ih

Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\flutter.BAT', '--version']
Error building Flet app - see the log of failed command above.

**Comment by coolninjaturtle** [comment]
for reference, I am using the latest flet version 0.21.2 and the latest stable dart and flutter versions, which are versions 3.3.3 and 3.19.5 respectively. Requirements are the flet version 0.21.2 and supabase version 2.4.0

**Comment by baseplate-admin** [comment]
The issue is not with flet, but with flutter itself :)


Run this command `flutter doctor --verbose`

**Comment by coolninjaturtle** [comment]
this is the output with after running flutter doctor --verbose. The only thing it found a problem with was a lacking installation of android studio, but i don't think that really matters if I have the android SDK working.


C:\Users\ishaa>flutter doctor --verbose
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3296], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\Users\ishaa\flutter_windows_3.19.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (9 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ishaa\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 19.0.2+7-44)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34301.259
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Users\ishaa\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\223.8836.41
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.86.1)
    • VS Code at C:\Users\ishaa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3296]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by coolninjaturtle** [comment]
I thought it might have been a version issue with gradle and the Java runtime that flutter was using, but found that they were supposed to be compatible with each other. When I run gradle --version, this is the output I get:

C:\Users\ishaa\Python Programs\final_ia>gradle --version

------------------------------------------------------------
Gradle 7.6.4
------------------------------------------------------------

Build time:   2024-02-05 14:29:18 UTC
Revision:     e0bb3fc8cefad8432c9033cdfb12dc14facc9dd9

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          19.0.2 (Oracle Corporation 19.0.2+7-44)
OS:           Windows 11 10.0 amd64

C:\Users\ishaa\Python Programs\final_ia>java --version
java 19.0.2 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

It lists JVM 19.0.2, and following that is my java version, which is 19.0.2, so they should be compatible. I am so confused.

**Comment by coolninjaturtle** [comment]
downgraded jvm to version 17 and it worked
