### ISSUE TITLE
flet build get stuck due to supabase in requirements.txt

### ISSUE THREAD

**Issue by coolninjaturtle** [flet-dev/flet#2993]
When I built my project for the first time, I forgot to include a requirements.txt in the root of my project and thus failed to have supabase included in my app. However, it did build into a full apk without issues. However, now that I have a requirements.txt file which contains the following:

flet==0.21.2
supabase==2.4.0

the flet build apk ALWAYS gets stuck here:

Packaging Python app...
Run subprocess: ['C:\\Users\\ishaa\\flutter_windows_3.19.5-stable\\flutter\\bin\\dart.BAT', 'run',
'serious_python:main', 'package', 'C:\\Users\\ishaa\\Python Programs\\final_ia', '--mobile', '--platform', 'mobile',
'--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
Building package executable... (3.0s)
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\ishaa\AppData\Local\Temp\flet_flutter_build_SQXPOAb0lW\app
Copying Python app from C:\Users\ishaa\Python Programs\final_ia to C:\Users\ishaa\AppData\Local\Temp\serious_python_tempe6ddd7f5
Configured mobile platform with sitecustomize.py at C:\Users\ishaa\AppData\Local\Temp\serious_python_sitecustomize760fd645\sitecustomize.py
Installing dependencies [flet-embed==0.21.2, supabase==2.4.0] with pip command to C:\Users\ishaa\AppData\Local\Temp\serious_python_tempe6ddd7f5\__pypackages__
Extracting Python distributive from C:\Users\ishaa\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\ishaa\AppData\Local\Temp\hostpython3.11_6c6958bd

**Comment by Kacper-OS** [comment]
https://github.com/flet-dev/flet/issues/2416

**Comment by ndonkoHenri** [comment]
Closing this issue in favour of #3839
