### ISSUE TITLE
Assertion "lookup_hash_table" fails on ToDo App example

### ISSUE THREAD

**Issue by qertoip** [flet-dev/flet#30]
** (flet:31142): CRITICAL **: 10:04:19.347: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) == 0' failed

This happens on the console while playing with the ToDo App example w/o modifications. The GUI seems functional.

**Comment by FeodorFitsner** [comment]
Could you provide more info please? What OS are you running the example on? What command did you user to run it? Screenshot with an error would help too. Thanks!

**Comment by FeodorFitsner** [comment]
I'm testing it on Ubuntu 20.04 (though Python is 3.8, not the latest) and it looks "good":

![image](https://user-images.githubusercontent.com/5041459/174640209-f2ef9003-cd37-4c73-8af9-acac929cb12d.png)

What distro/version of Linux are you running it on? Could you catch the steps to reproduce?

**Comment by qertoip** [comment]
Please just **press and hold** any key in the top text field, entering something like `aaaaaaaaaaaaaaaaaaaaa`.

**Comment by FeodorFitsner** [comment]
Indeed, I can reproduce the issue in such a way:

![image](https://user-images.githubusercontent.com/5041459/175100322-ca1c6560-9d58-46f2-9c9d-c9ca337441ed.png)
