### ISSUE TITLE
Breaking change using OAuth provider from version 0.19 to 0.20/0.21

### ISSUE THREAD

**Issue by thinkORo** [flet-dev/flet#3007]
**Description**
Until today I used Flet 0.19.0 and was able to use the OAuth provider without any problems.

After switching to the current version 0.21, this no longer works, although I can't find any changes in the release notes.
When I install 0.19 it works again immediately.

**Code example to reproduce the issue:**
```python
import os

import flet
from flet import ElevatedButton, Page
from flet.auth import OAuthProvider
from init import read_dotenv

def main(page: Page):
    # code from documentation: https://flet.dev/docs/cookbook/authentication#configuring-a-custom-oauth-provider
    # provider = OAuthProvider(
    #     client_id=os.getenv("LINKEDIN_CLIENT_ID"),
    #     client_secret=os.getenv("LINKEDIN_CLIENT_SECRET"),
    #     authorization_endpoint="https://www.linkedin.com/oauth/v2/authorization",
    #     token_endpoint="https://www.linkedin.com/oauth/v2/accessToken",
    #     user_endpoint="https://api.linkedin.com/v2/me",
    #     user_scopes=["r_liteprofile", "r_emailaddress"],
    #     user_id_fn=lambda u: u["id"],
    #     redirect_url="http://localhost:8550/oauth_callback",
    # )

    # my code to read parameter from .env file via read_dotenv module
    provider = OAuthProvider(
        client_id=read_dotenv.keycloak_client_id,
        client_secret=read_dotenv.keycloak_client_secret_key,
        authorization_endpoint=read_dotenv.keycloak_auth_url,
        token_endpoint=read_dotenv.keycloak_token_url,
        user_scopes=read_dotenv.keycloak_scope,
        redirect_url=read_dotenv.redirect_url,
    )
    def login_click(e):
        page.login(provider)

    def on_login(e):
        if e.error:
            raise Exception(e.error)
        # print("User ID:", page.auth.user.id)
        print("Access token:", page.auth.token.access_token)

    page.on_login = on_login
    page.add(ElevatedButton("Keycloak Authentification", on_click=login_click))

flet.app(target=main, port=8550, view=flet.WEB_BROWSER)
```

**Describe the results you received:**
Nothing, because after logging in (to my OpenID provider = Keycloak) a new browser window simply opens without a recognizable login or the output of the AccessToken (`print("Access token:", page.auth.token.access_token)`)

**Describe the results you expected:**
After logging in, the OpenID browser window should close and the AccessToken should be displayed in the console.

**Flet version (`pip show flet`)**:
```
Name: flet
Version: 0.21.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/oro/Program/miniforge3/envs/expand/lib/python3.12/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: 
```

**Operating system**:
```
Linux with Python 3.12 in Conda virtual environment
```

**Comment by thinkORo** [comment]
I tried the new development version as well: flet==0.22.0.dev2609

Unfortunately with the same result. From my perspective `on_login` isn't called since version 0.20.x

Anyone with any idea?

**Comment by FeodorFitsner** [comment]
Default OAuth callback has been changed to `/oauth_callback`. Other than that - it should be the same.
What errors are you getting?

**Comment by thinkORo** [comment]
Unfortunately there isn't any error.

With version 0.19:
- After logging in, the open browser window closed and the Page.auth object was instantiated. And I use the provided access_token.

With version 0.20/0.21/0.22:
- After logging in, the window does not close, but returns (in my case) to the "/auth" route.
- I can see a reference to a route in the console: route /api/oauth/redirect?state=anyState&session_state=anySession&iss=http%3A%2F%2FmyServer%3A8180%2Frealms%2FmyRealm&code=anyCode

**Comment by FeodorFitsner** [comment]
`/api/oauth/redirect` does not exist anymore, it should be `/oauth_callback`.

**Comment by thinkORo** [comment]
Yes, but the problem was not only the configuration for Flet but also the configuration for the respective realm in Keycloak. My fault. Sorry.

For anyone who also encounters the problem: the "Valid redirect URIs" in Keycloak must be adjusted accordingly and be identical to the "redirect_url" of the OAuthProvider from "flet.auth".

Thank you, Feodor, for your quick reply.

No worries: I don't want to blame you (Flet is beautiful): Was there any hint in the release the I missed?

**Comment by FeodorFitsner** [comment]
No worries, thanks for the update! Funny enough - I also spent some time while testing OAuth with GitHub trying to figure out that "Redirect URL" must be changed on GitHub side as well 😂
