### ISSUE TITLE
Some older flet releases disappeared or were yanked from PyPI

### ISSUE THREAD

**Issue by eeintech** [flet-dev/flet#3014]
The releases between `0.1.65` and `0.9.0` have disappeared or were yanked from PyPI:

![image](https://github.com/flet-dev/flet/assets/4020546/56e164fc-5448-421a-9ad3-8ad194932dff)

This is a major problem as some older applications run on older versions of flet and newer version have breaking changes.

For instance, this is what Pip returns when trying to install an application using `0.7.4`:
``` shell
ERROR: Cannot install kintree==1.0.0, kintree==1.0.1, kintree==1.0.2, kintree==1.0.3, kintree==1.0.4, kintree==1.0.5, kintree==1.0.6 and kintree==1.0.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    kintree 1.0.7 depends on flet==0.7.4
    kintree 1.0.6 depends on flet==0.7.4
    kintree 1.0.5 depends on flet==0.7.4
    kintree 1.0.4 depends on flet==0.7.4
    kintree 1.0.3 depends on flet==0.5.2
    kintree 1.0.2 depends on flet==0.5.2
    kintree 1.0.2 depends on flet==0.5.2
    kintree 1.0.2 depends on flet==0.5.2
    kintree 1.0.1 depends on flet==0.5.2
    kintree 1.0.2 depends on flet==0.5.2
    kintree 1.0.0 depends on flet==0.5.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Please re-upload older versions and/or fix the missing packages.

Thank you.

**Comment by FeodorFitsner** [comment]
Sorry for breaking your workflow. I had no idea someone could be still using 0.7 which was released more than a year ago. PyPI is not unlimited and it gives 10 GB of storage per account. Flet has recently started hitting that limit a lot and we started cleanup from the end. Flet is production-ready, but still pre 1.0 which means its API could change many times and without backward compatibility. We do not plan to support old pre-1.0 versions of Flet. Flet 1.0 coming later this year, on the other hand, will be LTS and supported. So, before 1.0 we encourage Flet users to always adopt the latest, the freshest. Thanks for your understanding.

In the meantime, I'm going to write PyPI maintainers and ask for storage quota increase to reduce the pressure. Also, will improve CI process to copy wheels to GitHub releases.

**Comment by eeintech** [comment]
Hi @FeodorFitsner Thanks for your quick response. Understood we need to use the latest but I personally cannot keep up with your pace (this is a side project which I cannot dedicate much time to) and after `0.8` things got broken on my app so I decided on pinning the version and wait for a major release (`1.0`) to spend my spare time updating it, especially that it ran totally fine 😄 

If PyPI allows increase storage quota that'd be awesome, please let me know if that happens 👍 
The wheel could be another temporary option, would you have it for `0.7.4`?

**Comment by FeodorFitsner** [comment]
I'm afraid 0.7.4 has gone forever 😬. But [0.9.0](https://pypi.org/manage/project/flet/release/0.9.0/) should be compatible.

**Comment by second-string** [comment]
Could I get the wheel for 0.7.4 for apple silicon if it exists please? I'm running into the same issue from @eeintech 's repo but the wheel that he has provided for download is x86/64 linux
