### ISSUE TITLE
Flet 0.20 no longer available and app failing to load on upgrade

### ISSUE THREAD

**Issue by gitmatsika** [flet-dev/flet#3018]
flet version 0.20
Operating system Windows

Problem 1. Have upgraded from flet 0.20 to 0.22 and the application is failing to load however reverting to 0.20 does not work. It gives me invalid distribution 
![image](https://github.com/flet-dev/flet/assets/99650624/cac3b018-5aa0-4809-86fd-20fe4b533980)

Problem 2.

The same app that is running on 0.20 if upgraded is giving issues. FAiling to load a page on route change. I am getting a blank page

Code:

Route Change : function
![image](https://github.com/flet-dev/flet/assets/99650624/a0206e8f-f45f-48b9-986c-f2aba1adadd3)

The login module loads and when swicthing to the dashboard views , its not loading in 022 yet it worked in 0.20. Its also not working in 0.21

Here is part of the login
![image](https://github.com/flet-dev/flet/assets/99650624/380c898e-afc8-43d4-9702-05d4724e178d)

And also the dashboard view which i have simplified to avoid read a huge chunk of code

![image](https://github.com/flet-dev/flet/assets/99650624/95a42b89-59a4-4d0f-b6ca-2c9bdb9a6069)

I have tested many of the pages and they are loading by simply making them the home page or landing page as follows by commenting the login and the works

 
    #page.views.append(login)
    page.views.append(hom)
    page.update()

And then bringing back the login to be the home and try to change the route to point to the page representing the hom view ( page.views.append(hom)) as follows and its not working

![image](https://github.com/flet-dev/flet/assets/99650624/96be13ef-495f-477b-9787-7b07ba324d06)

**Comment by Humanbluray** [comment]
i got the same problem. when i launch an app with a single view it laucnhes correctly. for apps with multiples pages, i got a blank page

**Comment by eeintech** [comment]
Same issue here...

**Comment by FeodorFitsner** [comment]
Could you provide a code repro please?

**Comment by eeintech** [comment]
In my case I found the problem, the `_build` method of controls was replaced with `build` and after updating my views with the new naming it works fine.

**Comment by gitmatsika** [comment]
> Could you provide a code repro please?
Here is the repo
https://github.com/gitmatsika/flet-app

**Comment by gitmatsika** [comment]
> i got the same problem. when i launch an app with a single view it laucnhes correctly. for apps with multiples pages, i got a blank page

Did you get a solution

**Comment by gitmatsika** [comment]
> In my case I found the problem, the `_build` method of controls was replaced with `build` and after updating my views with the new naming it works fine.

Can i have a snippet of the code you changed for it to work

**Comment by gitmatsika** [comment]
> > > In my case I found the problem, the `_build` method of controls was replaced with `build` and after updating my views with the new naming it works fine.
> > 
> > 
> > Can i have a snippet of the code you changed for it to work
> 
> `0.19` and older:
> 
> ```python
> class CustomView(View):
> 
>   def _build(self):
>      <...>
> ```
> 
> `0.20` and newer:
> 
> ```python
> class CustomView(View):
> 
>   def build(self):
>      <...>
> ```

Have done this and its not working

**Comment by gitmatsika** [comment]
> Could you provide a code repro please?

This is another error that is poping up
File "D:\projects\py12\Lib\site-packages\flet_core\control.py", line 454, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'views.Dashboard' has no attribute '_build_add_commands'

**Comment by gitmatsika** [comment]
> > > > In my case I found the problem, the `_build` method of controls was replaced with `build` and after updating my views with the new naming it works fine.
> > > 
> > > 
> > > Can i have a snippet of the code you changed for it to work
> > 
> > 
> > `0.19` and older:
> > ```python
> > class CustomView(View):
> > 
> >   def _build(self):
> >      <...>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `0.20` and newer:
> > ```python
> > class CustomView(View):
> > 
> >   def build(self):
> >      <...>
> > ```
> 
> Have done this and its not working

**Comment by gitmatsika** [comment]
> > > In my case I found the problem, the `_build` method of controls was replaced with `build` and after updating my views with the new naming it works fine.
> > 
> > 
> > Can i have a snippet of the code you changed for it to work
> 
> `0.19` and older:
> 
> ```python
> class CustomView(View):
> 
>   def _build(self):
>      <...>
> ```
> 
> `0.20` and newer:
> 
> ```python
> class CustomView(View):
> 
>   def build(self):
>      <...>
> ```
This is what i am getting and points to the build command

AttributeError: module 'views.Dashboard' has no attribute '_build_add_commands'

**Comment by gitmatsika** [comment]
I Have managed to resolve the issue. As for the '_build_add_commands' error. I technically copied the same code into a new file with a new name and created my new routes and it worked fine. This was after realising that there is a module that is loading with almost the same code.
Other pages which were not loading was because i was clearing the views (page.views.clear() after changing a route

**Comment by eeintech** [comment]
@gitmatsika Glad to hear you found the solution!
