### ISSUE TITLE
blank screen since update to flet 0.22

### ISSUE THREAD

**Issue by Humanbluray** [flet-dev/flet#3031]
Hello
I was using flet 0.20 with python3.12.0 until yesterday and it worked very well.
I updated let to version 0.22.0 and now when I launch my application I get a blank page.
The code is far too long for me to post here, so I'll put the link below.
to try to fix the problem i tried to update python to 3.12.3. but the problem persists. 
i've noticed that for single page applications i don't have any problems.
i really need your help. the link f my project!!!

https://github.com/Humanbluray/fomiderc.git

**Comment by FeodorFitsner** [comment]
The repo is not accessible.

**Comment by Humanbluray** [comment]
sorry i have forgotten to put it public. now it's done

**Comment by sgrefen** [comment]
I had a similar issue with 0.21 where 0.20 applications produce a blank screen in Chrome when a (different) .21 application had been active in the same browser instance. Running it another browser or even an incognito worked just fine.

**Comment by Humanbluray** [comment]
i found the solution.
i had to add page.update()
