### ISSUE TITLE
Color not shown in "Testing Flet app on Android" Chip control

### ISSUE THREAD

**Issue by wschume** [flet-dev/flet#3037]
**Description**

When using a Chip control, the color is not displayed on Android.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Chip(label=ft.Text("foo"), color="red")))


ft.app(target=main)

```

**Describe the results you received:**

Running the app on Linux shows a red Chip control. Running the app on Android with
`flet run --android test.py` shows the Chip control without any color background.

**Describe the results you expected:**

The same red colored background as on the Linux application.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.22.0
```

**Operating system**:

Linux, Android

**Additional environment details:**

**Comment by wschume** [comment]
On a similar note, the flet mobile app is not able to correctly display [tabs](https://flet.dev/docs/controls/tabs). The tab bar itself is visible, but the content of the tabs is not.

**Comment by ndonkoHenri** [comment]
Will be fixed by https://github.com/flet-dev/flet/issues/3096.

**Comment by ndonkoHenri** [comment]
Closing in favor of https://github.com/flet-dev/flet/issues/3096
