### ISSUE TITLE
fluet build apk  (OS Error: The process cannot access the file because it is being used by another process. , errno = 32)

### ISSUE THREAD

**Issue by abdokhalil07** [flet-dev/flet#3039]
Unhandled exception:
PathAccessException: Deletion failed, path = 'C:\Users\ABDELR~1\AppData\Local\Temp\hostpython3.11_7264d0b' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:180:7)
<asynchronous suspension>
#2      PackageCommand.run (file:///C:/Users/abdelrahman/AppData/Local/Pub/Cache/hosted/pub.dev/serious_python-0.7.0/bin/package_command.dart:363:9)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      main (file:///C:/Users/abdelrahman/AppData/Local/Pub/Cache/hosted/pub.dev/serious_python-0.7.0/bin/main.dart:10:3)
<asynchronous suspension>

**Comment by abdokhalil07** [comment]
it sloved
i used python 3.11.4 and it work

**Comment by ndonkoHenri** [comment]
Please retry with the latest Flet version and at least Flutter version >3.22.2
If the issue persists open a new issue using the [bug issue-template](https://github.com/flet-dev/flet/issues/new?assignees=&labels=&projects=&template=01_bug_report.yml).
