### ISSUE TITLE
FPS show？

### ISSUE THREAD

**Issue by dragondjf** [flet-dev/flet#304]
can add FPS show on page to evaluate UI performance？

**Comment by FeodorFitsner** [comment]
Why would we need that?

**Comment by ndonkoHenri** [comment]
> to evaluate UI performance

**Comment by ndonkoHenri** [comment]
Some useful links:
[https://pub.dev/packages/fps_widget](https://pub.dev/packages/fps_widget)
[https://docs.flutter.dev/perf/ui-performance](https://docs.flutter.dev/perf/ui-performance)
[https://stackoverflow.com/questions/57754193/flutter-how-to-show-fps-frame-per-second-to-the-user](https://stackoverflow.com/questions/57754193/flutter-how-to-show-fps-frame-per-second-to-the-user)
