### ISSUE TITLE
Android APK size too big

### ISSUE THREAD

**Issue by omolayoabegunde** [flet-dev/flet#3056]
I appreciate all your effort in putting this framework together for Python. Please, can something be done on the apk size? The size is ridiculously large. Pls I shall be expecting your prompt response, thanks.

**Comment by baseplate-admin** [comment]
This is a known issue in `python-for-android`:

Discussion: 
* https://github.com/orgs/kivy/discussions/22#discussion-6032762

Issue : 
* https://github.com/kivy/kivy-github-discussions/issues/26

**Comment by FeodorFitsner** [comment]
Would love to work on that problem when packaging is improved.

**Comment by baseplate-admin** [comment]
Hi @FeodorFitsner, Do we have an ETA for this?

**Comment by omolayoabegunde** [comment]
> Would love to work on that problem when packaging is improved (currently working on).

Thanks for that. I have been trying to try Dioxus with Rust. We shall be expecting that.

**Comment by omolayoabegunde** [comment]
I have been introducing Flet to all my students at various levels, that it is a good choice to pick up

**Comment by ndonkoHenri** [comment]
> Please, can something be done on the apk size?

https://flet.dev/docs/publish/android#building-platform-specific-apk
