### ISSUE TITLE
the problems of testing Flet app on iOS and Android in Chinese

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3061]
OS: windows 10
python: 3.12
flet version: 0.22.0, 
ios flet: 1.5.1, mainland China

Following the operations in this document 'https://flet.dev/docs/getting-started/testing-on-ios', I found that when testing on an iOS phone, the path with Chinese characters could not be recognized.

In addition, users in mainland China cannot access Google Play and cannot install the Android version of flet. It is recommended to publish the Android version of flet to Tencent's App Store platform, which is called “应用宝” in Chinese.

**Comment by BrentHuang** [comment]
> use vpn, or email to [espholychan@outlook.com](mailto:espholychan@outlook.com) contact me使用 VPN，或发送电子邮件至 espholychan@outlook.com 联系我

thank you very much!

**Comment by mzdk100** [comment]
Can you upload an APK of Flet App to the releases page on GitHub? I am also unable to download.
