### ISSUE TITLE
SafeArea plays badly with Tabs

### ISSUE THREAD

**Issue by wschume** [flet-dev/flet#3063]
**Description**

Putting the Tabs example from the documentation in a SafeArea control, renders Tab 1 not readable.

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    t = ft.Tabs(
        tabs=[
            ft.Tab(
                text="Tab 1",
                content=ft.Container(
                    content=ft.Text("This is Tab 1"), alignment=ft.alignment.center
                ),
            ),
            ft.Tab(
                tab_content=ft.Icon(ft.icons.SEARCH),
                content=ft.Text("This is Tab 2"),
            ),
            ft.Tab(
                text="Tab 3",
                icon=ft.icons.SETTINGS,
                content=ft.Text("This is Tab 3"),
            ),
        ],
        expand=True,
    )

    page.add(ft.SafeArea(t))
    # page.add(t)


ft.app(target=main)

```

**Describe the results you received:**
Tab 2 renders correctly:
![image](https://github.com/flet-dev/flet/assets/65328438/b2431a4c-2ae2-45af-8d0e-29d020daee7d)

Tab 1 does not display its content:
![image](https://github.com/flet-dev/flet/assets/65328438/5e2c2215-2a01-4191-b4dd-f1b7883df64c)

While running the example without the SafeArea, the content of Tab 1 is shown:
![image](https://github.com/flet-dev/flet/assets/65328438/cbc6f13f-28b7-44b7-bf97-376e765669ab)

**Describe the results you expected:**

I'd expect, that the SafeArea has no influence on the rendering of the contents of Tab 1

**Flet version (`pip show flet`)**:
```
0.22.0
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
```

**Operating system**:

Linux

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Expand the `SafeArea` as follows: `page.add(ft.SafeArea(t, expand=True))`

**Comment by wschume** [comment]
Thank you for the reply. The `expand=True` completely fixed the issue. Thank you for your help.
