### ISSUE TITLE
Video lag and stream interruptions on Android TV devices

### ISSUE THREAD

**Issue by bl1nch** [flet-dev/flet#3072]
**Description**

High resolution videos play laggy on Android TV devices.
This problem is related to `media_kit` and can be found here: https://github.com/media-kit/media-kit/issues/614.
Possible solution: https://github.com/media-kit/media-kit/issues/614#issuecomment-2067968413.
If this solution actually works as I understand `flet_video` should be updated like this: https://github.com/flet-dev/flet/commit/240897e47b9d35bbee33f52fc9b3d297aef4d7e4

**Flet version (`pip show flet`)**:
```
0.22.0
```

**Operating system**:
```
Android TV
```

**Comment by ndonkoHenri** [comment]
Can you open a PR with the commit?
