### ISSUE TITLE
page.overlay.append - AttributeError: 'property' object has no attribute 'append'

### ISSUE THREAD

**Issue by gitmatsika** [flet-dev/flet#3073]
Flet 0.22
Windows 10

The code is from the documentation
Have the following code and and i am receiving  AttributeError: 'property' object has no attribute 'append' on the following line

 **page.overlay.append(pick_files_dialog)**

import flet as ft
def main(page: ft.Page):
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()

    pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
    selected_files = ft.Text()

    page.overlay.append(pick_files_dialog)

    page.add(
        ft.Row(
            [
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=lambda _: pick_files_dialog.pick_files(
                        allow_multiple=True
                    ),
                ),
                selected_files,
            ]
        )
    )

ft.app(target=main)

**Comment by ndonkoHenri** [comment]
It should certainly because the code is wrongly formatted(indentation?).
I reformated it as below and it works(Flet v0.22.0):
```py
import flet as ft


def main(page: ft.Page):
    def pick_files_result(e: ft.FilePickerResultEvent):
        selected_files.value = (
            ", ".join(map(lambda f: f.name, e.files)) if e.files else "Cancelled!"
        )
        selected_files.update()

    pick_files_dialog = ft.FilePicker(on_result=pick_files_result)
    selected_files = ft.Text()

    page.overlay.append(pick_files_dialog)

    page.add(
        ft.Row(
            [
                ft.ElevatedButton(
                    "Pick files",
                    icon=ft.icons.UPLOAD_FILE,
                    on_click=lambda _: pick_files_dialog.pick_files(
                        allow_multiple=True
                    ),
                ),
                selected_files,
            ]
        )
    )


ft.app(target=main)

```

If you still face issues, please report with your Flet version and virtual environment details.

**Comment by gitmatsika** [comment]
Thanks, I'll check it out.
