### ISSUE TITLE
An update is required for the Flet SDK

### ISSUE THREAD

**Issue by Klu1d** [flet-dev/flet#3075]
I only use the Flet SDK from the App Store to test my projects.
And here are the challenges I'm facing:

1. **Local images are not displaying in the Flet SDK**

Code to reproduce the issue:

```python
import flet as ft

def main(page: ft.Page):
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER

    page.add(
        ft.Text('The cowboy is riding a tiger'),
        ft.Image('./tiger.jpg', width=300, height=250),
        
        ft.Text('The cowboy is riding a tiger'),
        ft.Image('tiger.jpg', width=300, height=250),
    )

ft.app(target=main)
```
  **Expected result**
![image](https://github.com/flet-dev/flet/assets/105982046/860195a1-463f-44c4-9aa6-67b637b65003)
 
 **Result** 
![image](https://github.com/flet-dev/flet/assets/105982046/c4eaeb16-505f-43e0-ab3b-f6864409e652)

2. **Weird animation when swiping right on iOS.**
I've already opened a discussion about this in #2110, and the problem has remained the same since then. In that context, it's hard to notice if the app is small. But when the app gets bigger, it's much more noticeable—here's an additional video. I should also mention that when I press the back button, there's no issue. The problem only occurs when I swipe right to close the current page. This issue can be reproduced with the code in #2110.

https://github.com/flet-dev/flet/assets/105982046/52234a5d-ae5c-49fb-9612-b4535b682592

Besides that, I've noticed that this also happens in the Flet app from the App Store.

I haven't tested on other iPhones.
I have an iPhone SE 2016 with iOS 15.7.5
flet 0.22.0
Python 3.11.8

This text was translated with the help of ChatGPT.

**Comment by FeodorFitsner** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/3096
