### ISSUE TITLE
network proxy error

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3076]
on windows, I set network proxy: `$env:HTTP_PROXY="socks5://127.0.0.1:1080"; $env:HTTPS_PROXY="socks5://127.0.0.1:1080"`

execute 'flet build -vv windows', it report the following error:

Extracting Python distributive from C:\Users\hgc\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\hgc\AppData\Local\Temp\hostpython3.11_1737ae1f
VERBOSE: C:\Users\hgc\AppData\Local\Temp\hostpython3.11_1737ae1f\python\python.exe -m pip install --isolated --upgrade --target C:\Users\hgc\AppData\Local\Temp\serious_python_temp539f9f84\__pypackages__ flet-embed==0.22.*
**ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.**

I think the 'cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz' should have "pysocks" in it.

**Comment by FeodorFitsner** [comment]
Flet downloads complete Python distro from https://github.com/indygreg/python-build-standalone/releases
I don't think this issue is related to Flet.
