### ISSUE TITLE
Hi , please, I really need to use ft.Webview in my Flet / Android application, but it doesn't work currently I really think that a Widget for Webview will be a great advancement  THANKS

### ISSUE THREAD

**Issue by logololo** [flet-dev/flet#3085]
**Please Describe The Problem To Be Solved**

(Replace This Text: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

**(Optional): Suggest A Solution**

(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation, e.g. Flutter widget solving the problem.
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by ndonkoHenri** [comment]
Please provide some more details, if you need help.

**Comment by hanchenglong001** [comment]
可以用，但是http不行
