### ISSUE TITLE
Help on how to access HTTP web views instead of HTTPS   bug

### ISSUE THREAD

**Issue by hanchenglong001** [flet-dev/flet#3088]
Android
use webview
Error accessing HTTP service
How to support HTTP access and ignore SSL errors？

**Comment by hanchenglong001** [comment]
I started a Flask program in Fleet and used the Fleet UI to access it. But the Flask program is HTTP. I tried using the following method to start Flask and access HTTPS, but it still didn't work.

def run_flask_in_thread():
print("Starting Flask in thread...")
ssl_context = ('assets/aaa.pem', 'assets/aaa-key.pem')
app.run(host='0.0.0.0',port=5448,ssl_context=ssl_context)

**Comment by FeodorFitsner** [comment]
Please use correct template to submit the issue.
