### ISSUE TITLE
`BetterNavigationDrawer` and `BetterNavigationBar` controls

### ISSUE THREAD

**Issue by bleudev** [flet-dev/flet#3092]
**Please Describe The Problem To Be Solved**

I want to open PR where i'll make new classes: BetterNavigationDrawer, BetterNavigationBar where i'll realise my idea.

Concept:
```py
def hello(page): ...
def world(page): ...

drawer = BetterNavigationDrawer()
group = drawer.create_group('first group')

@group.destination
def hello(page): ...

@group.destination
def world(page): ...

@drawer.destination
def hi(page: Page): ...

page.drawer = drawer
```

After running there will is drawer with one group and one destination. Group - label + controls

-------
- first group
    - hello
    - world
- hi

Also i want to create `change` method for changing_pages

```py
page.drawer.change(1) # second page -> 'world' destination
```

BetterNavigationBar will be like, but without groups

**Comment by bleudev** [comment]
I want to open PR where i'll make new classes: BetterNavigationDrawer, BetterNavigationBar where i'll realise my idea.

Concept:
```py
page.drawer = BetterNavigationDrawer(
controls=[
NavigationDrawerControlsGroup(
    name='first group',
    controls=[
        NavigationDrawerDestination(label='hello'),
        NavigationDrawerDestination(label='world')
    ]
),
NavigationDrawerDestination(label='hi')
]
)
```

After running there will is drawer with one group and one destination. Group - label + controls

-------
- first group
    - hello
    - world
- hi

**Comment by ndonkoHenri** [comment]
I suggest you provide the community with the Better* controls as extension of Flet (in a separate repo or as part of Flet-contribs).
The goal is to keep the Flet API simple.

**Comment by bleudev** [comment]
> I suggest you provide the community with the Better* controls as extension of Flet (in a separate repo or as part of Flet-contribs). The goal is to keep the Flet API simple.

You suggest to create `better` folder in flet_core with all objects?

**Comment by ndonkoHenri** [comment]
Nope, I meant creating a new repo on your github account ([ex](https://github.com/ndonkoHenri/Flet-Custom-Controls)).

**Comment by bleudev** [comment]
> Nope, I meant creating a new repo on your github account ([ex](https://github.com/ndonkoHenri/Flet-Custom-Controls)).

But i want to create this package in flet. It's important for me.

**Comment by FeodorFitsner** [comment]
You are welcome to add your control to https://github.com/flet-dev/flet-contrib though!
