### ISSUE TITLE
安卓 http协议在ft.webview中无法正常运行。

### ISSUE THREAD

**Issue by hanchenglong001** [flet-dev/flet#3095]
import time

import flet as ft
import threading
from flask import Flask,send_file

app = Flask(__name__)
@app.route('/')
def hello_world():
    return send_file("assets/test.html")

def run_flask_in_thread():
    print("Starting Flask in thread...")
    ssl_context = ('assets/10.15.176.117.pem', 'assets/10.15.176.117-key.pem')
    app.run(host='0.0.0.0',port=5449,ssl_context=ssl_context)
    # app.run(host='0.0.0.0',port=5448)

def main(page: ft.Page):
    page.title = "test"
    flask_thread = threading.Thread(target=run_flask_in_thread)
    flask_thread.start()
    page.navigation_bar = ft.NavigationBar(
        destinations=[
            ft.NavigationDestination(icon=ft.icons.EXPLORE, label="test")
        ]
    )
    wv = ft.WebView(
        url=f"https://127.0.0.1:5448",
        expand=True,
        on_page_started=lambda _: print("Page start"),
        on_page_ended=lambda _: print("Page ended"),
        on_web_resource_error=lambda e: print("Page error:", e.data),
    )
    page.add(wv)

ft.app(target=main)

无法正常工作，没有打印Page start

**Comment by hanchenglong001** [comment]
import time

import flet as ft
import threading
from flask import Flask,send_file


app = Flask(__name__)
@app.route('/')
def hello_world():
    return send_file("assets/test.html")

def run_flask_in_thread():
    print("Starting Flask in thread...")
    app.run(host='0.0.0.0',port=5448)


def main(page: ft.Page):
    page.title = "测试工具"
    flask_thread = threading.Thread(target=run_flask_in_thread)
    flask_thread.start()
    page.navigation_bar = ft.NavigationBar(
        destinations=[
            ft.NavigationDestination(icon=ft.icons.EXPLORE, label="首页")
        ]
    )
    wv = ft.WebView(
        url=f"http://127.0.0.1:5448",
        expand=True,
        on_page_started=lambda _: print("Page start"),
        on_page_ended=lambda _: print("Page ended"),
        on_web_resource_error=lambda e: print("Page error:", e.data),
    )
    page.add(wv)


ft.app(target=main)

这样也不行



[图片]

**Comment by hanchenglong001** [comment]
![e9454ae7148ef6ace2f063fe7ac336b](https://github.com/flet-dev/flet/assets/56539098/0ffa982e-0e0a-4b58-8d92-bfeceb255df4)

**Comment by a83988029** [comment]
用 python 写安卓？

**Comment by FeodorFitsner** [comment]
Pleasе use English and correct template to submit the issue.

**Comment by hanchenglong001** [comment]
> 用python写安卓？
是的

**Comment by hanchenglong001** [comment]
> 请使用英文和正确的模板提交问题。

Link questions using English and correct templates
https://github.com/flet-dev/flet/issues/3128#issue-2268705349
