### ISSUE TITLE
Wrong QR code generated in flet run --android

### ISSUE THREAD

**Issue by vishnu-rvb** [flet-dev/flet#3108]
**Description**
When running `flet run --android` the QR code generated is indicating wrong .

**Describe the results you received:**
Correct text is supposed to be `http://192.168.0.102:8551/Quarentine-Manager/main.py` but upon scanning the QR code we receive the text `https://android.flet.dev/192.168.0.102%3A8551/Quarentine-Manager/main.py`
![Screenshot 2024-04-27 200838](https://github.com/flet-dev/flet/assets/118911871/4691b293-3b86-40bb-a51b-467058e688a7)

**Flet version (`pip show flet`)**:
```
Name: flet
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\program files\python310\lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```
**Operating system**:
Windows

**Comment by FeodorFitsner** [comment]
That's correct QR code for Android which includes https://android.flet.dev rendering the page simulating the click (you can try opening https://android.flet.dev and see its sources) - that's the only reliable way I found to open Flet app with deep linking.

**Comment by vishnu-rvb** [comment]
what about "192.168.0.102%3A85". port number seems to be messed up.

**Comment by FeodorFitsner** [comment]
It's URL-encoded value: 

<img width="251" alt="image" src="https://github.com/flet-dev/flet/assets/5041459/8c23dfec-6948-45c2-a71a-0c51abe5cb60">
