### ISSUE TITLE
AlertDialog control unable to scroll in flet run --android

### ISSUE THREAD

**Issue by vishnu-rvb** [flet-dev/flet#3111]
**Description**
Trying to build a Alert dialog control that is made of a column that contains long list of text control. Setting the scrollable=True in alert dialog control works when running in Desktop but  when running fr android it is no longer scrollable.
Although when building in android the alert dialog is scrollable.

**Code example to reproduce the issue:**

```python
import flet as ft
def main(page: ft.Page):
    dlg=ft.AlertDialog(scrollable=True)
    dlg.title=ft.Column([ft.Text(f"rows {i}") for i in range(0,50)])
    page.dialog=dlg
    dlg.open=True
    page.scroll='AUTO'
    page.update()

ft.app(main)

```

**Describe the results you received:**
This is when performing `flet run --android`.
Unable to scroll.
You can also note that the text controls are also overflowing from the alert dialog
![Screenshot_20240427_221556](https://github.com/flet-dev/flet/assets/118911871/836a9652-bc37-4311-a88b-8e9b5ca5ba99)

**Describe the results you expected:**
This is when performing `flet build apk`.
Able to scroll.
There is no overflowing from the alert dialog.
![Screenshot_20240427_224711](https://github.com/flet-dev/flet/assets/118911871/1568b77d-f51d-4076-a63f-16382b44d0a4)

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\program files\python310\lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**
```
flet==0.22.*
```

**Operating system**:
Windows

**Comment by ndonkoHenri** [comment]
Thanks for reporting. 

Let's wait for the Flet app to be updated - coming soon.

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/3096#issuecomment-2334248541
