### ISSUE TITLE
Add a PathPicker

### ISSUE THREAD

**Issue by MayorTom4815** [flet-dev/flet#3112]
**Please Describe The Problem To Be Solved**

Please, create a "PathPicker" because the "FilePicker" requires a file obligatory to take the path, or add an option to the "FilePicker" to not use a file to select a path.

**Comment by EmberLightVFX** [comment]
You can already do that by using

```
file_picker =  ft.FilePicker()
file_picker.get_directory_path()
```

**Comment by FeodorFitsner** [comment]
What Flutter package or library does solve that?
