### ISSUE TITLE
Feature: dark mode for error screen

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#312]
Please change what flet outputs for dark mode when it gets its 'blue screen' error (even blue would be better than all white !)

![Screen Shot 2022-09-11 at 7 23 50 PM](https://user-images.githubusercontent.com/11970940/189563070-f4b9deb7-ee95-4439-8296-e6859cd8ca74.png)

**Comment by ndonkoHenri** [comment]
🤣

**Comment by FeodorFitsner** [comment]
It's been implemented.
