### ISSUE TITLE
ERROR: No matching distribution found for flet==0.20.2 when install pip install flet-fastapi==0.20.2

### ISSUE THREAD

**Issue by freevid32** [flet-dev/flet#3122]
pip install flet-fastapi==0.20.2
Collecting flet-fastapi==0.20.2
  Using cached flet_fastapi-0.20.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: fastapi<0.102.0,>=0.101.0 in /opt/homebrew/lib/python3.11/site-packages (from flet-fastapi==0.20.2) (0.101.1)
INFO: pip is looking at multiple versions of flet-fastapi to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement flet==0.20.2 (from flet-fastapi) (from versions: 0.1.0, 0.1.56, 0.1.57, 0.1.58, 0.1.59, 0.1.60, 0.1.61, 0.1.62, 0.1.63, 0.1.64, 0.1.65, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.21.2, 0.22.0.dev2589, 0.22.0.dev2590, 0.22.0.dev2594, 0.22.0.dev2595, 0.22.0.dev2601, 0.22.0.dev2602, 0.22.0.dev2609, 0.22.0.dev2623, 0.22.0.dev2627, 0.22.0.dev2630, 0.22.0)
ERROR: No matching distribution found for flet==0.20.2

**Comment by ndonkoHenri** [comment]
Sorry for that, but some versions of Flet were deleted.
More detailed explanation: https://github.com/flet-dev/flet/issues/3014#issuecomment-2048120675

**Comment by freevid32** [comment]
Thank you so much.
