### ISSUE TITLE
ERROR: No matching distribution found for flet==0.20.2 (from flet-fastapi) on Mac M1 and Linux Ubuntu

### ISSUE THREAD

**Issue by freevid32** [flet-dev/flet#3124]
pip install flet-fastapi
Collecting flet-fastapi
  Downloading flet_fastapi-0.20.2-py3-none-any.whl (15 kB)
ERROR: Could not find a version that satisfies the requirement flet==0.20.2 (from flet-fastapi) (from versions: 0.1.0, 0.1.56, 0.1.57, 0.1.58, 0.1.59, 0.1.60, 0.1.61, 0.1.62, 0.1.63, 0.1.64, 0.1.65, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0)
ERROR: No matching distribution found for flet==0.20.2 (from flet-fastapi)

**Comment by FeodorFitsner** [comment]
0.20.0 has been removed while cleaning up PyPI because we didn't have enough space. Our storage has been increased since then, so it shouldn't happen anymore. Sorry about that!

Please upgrade to the latest Flet version.

**Comment by rutopio** [comment]
I got the same issue when I ran my Flet program which created last year.

```
Error: No matching distribution found for flet-embed==0.20.0
```

Here's my solution:

1. Update Flet

```shell
pip install flet -U 
```

2. Check Flet version

```
flet --version
# 0.22.1
```

3. Update `requirements.txt` before building

```
# turn these
flet==0.2.0
flet-core==0.20.0
flet-runtime==0.20.0
```

```
# to these
flet==0.22.1
flet-core==0.22.1
flet-runtime==0.22.1
```
