### ISSUE TITLE
Flet build `--exclude` command option

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3125]
flet build does not have the exclude option and cannot exclude some directories or files.

**Comment by ndonkoHenri** [comment]
Which directories do you wish to see excluded? Please provide more information.
Flet build packages only content of your project directory.

**Comment by BrentHuang** [comment]
For example, in my project, there is a logs directory, which contains log files, and a scripts directory, which contains my packaging scripts, which are not needed.

**Comment by FeodorFitsner** [comment]
`package` command in serious_python package already has `--exclude` option, but I see `flet build` passes hard-coded `assets,build` there. We need to expose this option in `flet build`.

Another option would be "automate" exclusion list by parsing `.gitignore`. Don't know if other tools do that, but sounds like a nice idea :)

**Comment by BrentHuang** [comment]
A semantically clear exclude is better.

**Comment by BrentHuang** [comment]
`flet build --build-number=1 --build-version="1.0.0" --exclude="scripts/ logs/ .gitignore babel.cfg i18n.bat README.md requirements.txt .pod.po" -vv windows`

flet 0.22.1 `--exclude` like this? but has no effect like this, no files and dirs excluded.

**Comment by MSchwesig** [comment]
> `flet build --build-number=1 --build-version="1.0.0" --exclude="scripts/ logs/ .gitignore babel.cfg i18n.bat README.md requirements.txt .pod.po" -vv windows`


It works, you just have to separate differently:

- no `/` at the end of a dir, just the name of the dir. 
- separate the files with a `,`
- pack all in `"`
so it would be something like that: 
`flet build --build-number=1 --build-version="1.0.0" --exclude="scripts, logs, .gitignore, babel.cfg, README.md" windows`

**Comment by syleishere** [comment]
This is useful, adding wildcard support like *.bat, *.sh would be great addition to this.
