### ISSUE TITLE
no on_press event?

### ISSUE THREAD

**Issue by scriptiot-dev** [flet-dev/flet#313]
**on_press event is very important！**

only container and  button have event ? 

why image/text not have event ?

**Comment by FeodorFitsner** [comment]
Sure, just put an image inside Container and add `on_click` to container. This way you can make any control clickable.

**Comment by scriptiot-dev** [comment]
yeah, I just do it as above, Thanks

**Comment by FeodorFitsner** [comment]
`on_press` is called `on_click` in Flet.

**Comment by scriptiot-dev** [comment]
I mean on_press  onrelease  onclick 

onpress: mouse down  not up

**Comment by FeodorFitsner** [comment]
Flet uses Flutter's [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html#instance-properties) - could you point me to the right event handlers you'd like to see implemented?

**Comment by scriptiot-dev** [comment]
just like html5 mouse event

+ onmousedown   
+ onmousemove
+ onmouseup

**Comment by FeodorFitsner** [comment]
OK, what would be your use case for that? What would you like to implement with those events?

**Comment by scriptiot-dev** [comment]
I want to change button background-color or change background-image when on_press/on_release

**Comment by FeodorFitsner** [comment]
Look at this example of a styled button: https://github.com/flet-dev/examples/blob/main/python/controls/elevated-buttons/styled-button.py

**Comment by scriptiot-dev** [comment]
yeah, but  if flet can have 

+ onmousedown
+ onmousemove
+ onmouseup

may be i can do more as i can

**Comment by FeodorFitsner** [comment]
Covered by https://flet.dev/docs/controls/gesturedetector
