### ISSUE TITLE
further using of flet-fastapi 0.19.0 and flet 0.19.0 as last available compatibility each other, some error occurred with this **AttributeError: module 'flet' has no attribute 'VideoMedia'**

### ISSUE THREAD

**Issue by freevid32** [flet-dev/flet#3130]
further using of flet-fastapi 0.19.0 and flet 0.19.0 as last available compatibility each other, some error occurred with this **AttributeError: module 'flet' has no attribute 'VideoMedia'**

**Comment by freevid32** [comment]
and also not available for ft.video ..

**Comment by InesaFitsner** [comment]
Please use the template to submit the issue and provide a complete runnable repro.
