### ISSUE TITLE
Using `CupertinoSegmentedButton.selected_index` raises `IndexError`

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3159]
**Description**

**Code example to reproduce the issue:**

```python
https://flet.dev/docs/controls/cupertinosegmentedbutton
```

**Describe the results you received:**

![image](https://github.com/flet-dev/flet/assets/2862064/a7b848fe-6d1b-4bd5-a794-81ff4bfcd5f2)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
PS D:\workspace\code\plan\flet_study> pip show flet
Name: flet
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: d:\workspace\code\plan\.venv\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

Windows, macOS

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
This issue should be fixed in the latest pre-release. Please try install the latest pre, retry, and let know.
```py
pip install flet --pre
```
