### ISSUE TITLE
Feature Request:ScreenShot

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#3189]
**Please Describe The Feature To Be Added**

Integration of ScreenShoting
**Suggest A Solution**

https://pub.dev/packages/screenshot

**Comment by FanaticExplorer** [comment]
I think you made a typo here ;)

**Comment by FeodorFitsner** [comment]
Yeah, what package is that?

**Comment by vv2006-mc** [comment]
let me check all the posts once again.... 😅

**Comment by NocoleNe** [comment]
I hope to have such a similar feature
How to get a control ui image?
I want to implement such a report for printing function, but I don't want to use MatplotlibChart and PlotlyChart,
Although MatplotlibChart and PlotlyChart can do this, flush control cannot be used inside them

**Comment by NocoleNe** [comment]
I hope to have such a similar feature
How to get a control ui image?
I want to implement such a report for printing function, but I don't want to use MatplotlibChart and PlotlyChart,
Although MatplotlibChart and PlotlyChart can do this, flush control cannot be used inside them

**Comment by ndonkoHenri** [comment]
Closing in favor of https://github.com/flet-dev/flet/issues/317
