### ISSUE TITLE
ERROR:websocket:[Errno 61] Connection refused 

### ISSUE THREAD

**Issue by Januswork** [flet-dev/flet#321]
macos+vscode,
app is running but got below ERROR message every time.

ERROR:websocket:[Errno 61] Connection refused - goodbye
WARNING:websocket:websocket connected

**Comment by FeodorFitsner** [comment]
I'm still trying to figure out where this error is coming from: Python, Flutter or some lib in between.

**Comment by FeodorFitsner** [comment]
Scratch that. Looks like it's coming from here: https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L380
https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L377

Will figure out how to properly disable/control the logging in websocket client: https://github.com/websocket-client/websocket-client/blob/master/websocket/_logging.py

**Comment by TahaAhvazi** [comment]
> macos+vscode, the app is running but got below ERROR message every time.
> 
> ERROR:websocket:[Errno 61] Connection refused - goodbye WARNING:websocket:websocket connected

I have the same error on Windows + VsCode

**Comment by FeodorFitsner** [comment]
It's been fixed. Updated Flet to the latest version.
