### ISSUE TITLE
long app loading time looks like app crashes on startup

### ISSUE THREAD

**Issue by clstaudt** [flet-dev/flet#322]
I am building a desktop app with flet, which depends on a couple of Python libraries. Pyinstaller works like a charm, however, the resulting app bundle on a Mac has 300 MB. 

When starting the app from the bundle, a startup icon appears:

![Screenshot 2022-09-14 at 14 23 32](https://user-images.githubusercontent.com/875194/190152838-67336233-f960-46d7-bf12-d1ce757152a5.png)

It then disappears for 10-20 seconds. The user might think that the app has failed to start. In fact it is still loading.

Finally the app appears in the dock with the flet default app icon:

![Screenshot 2022-09-14 at 14 26 45](https://user-images.githubusercontent.com/875194/190153000-ef8d28e5-2b33-4fb2-81f0-bd1ce29a1ff1.png)

This will be a source of confusion for users. Is there a way to:
- display a loading screen?
- have the app icon be there and bounce during the entire startup phase?

**Comment by FeodorFitsner** [comment]
I think you are fighting here with PyInstaller mostly, not Flet. When you package everything into a single executable it becomes bascially just a zip which is unpacked on the first run and I guess it takes time to unpack 300 MB. What times do you get when not packing to a single file?

There is a splash screen for pyinstaller https://pyinstaller.org/en/stable/usage.html#splash-screen-experimental, but it doesn't work on macOS.

Another thing is to change Flet client to start Python program as a sub-process (vs Python starting Flet client as currently implemented). This way we would have more control over loading process. However, packaging would be different - pyinstaller won't work. Need to think about that scenario.

**Comment by clstaudt** [comment]
> What times do you get when not packing to a single file?

If I omit the `--onefile` option, I get a 770 MB .app bundle that opens almost instantly... but with another Python&FloppyDisk app icon bouncing next to it for a minute. That's also likely to confuse and annoy, and does not feel like a native app.

So the choice is between a huge app file and slow loading? Is there anything else one could try?

**Comment by ningzichun** [comment]
The use of the "onefile" option also concerns me. As [pyinstaller/issues/4843](https://github.com/pyinstaller/pyinstaller/issues/4843), security checks are repeated every time the app is extracted to the temp directory. 

Additionally, if "windowed" and "onedir" are used, FloppyDisk and flet icons appear simultaneously and system report the app crash upon closure, which will confuse the user.

**Comment by cbenhagen** [comment]
@FeodorFitsner do you have any idea how to prevent the pyinstaller icon from bouncing when using `-windowed` option? The `-onefile` option is really unusable on newer macos systems due to the security features mentioned above. The app gets unpacked on each run and treated as new. So no notarizing or signing differently will fix this. 

I am sure we can find a solution to this bouncing icon issue and switch to windowed mode on macOS. Do you want me to open a new issue for that?

**Comment by cbenhagen** [comment]
@FeodorFitsner very intesting! Where can I learn more about this new approach?

**Comment by FeodorFitsner** [comment]
Sure, the solution is currently piloting for iOS. There is [`serious_python` Flutter package](https://pub.dev/packages/serious_python) that will be implemented for macOS (and other platforms) as well. Flutter app is just a bootstrap: https://github.com/flet-dev/serious-python/blob/main/example/flet_example/lib/main.dart

**Comment by cbenhagen** [comment]
Great project @FeodorFitsner! As much as I like Flet, serious-python is going to be much more useful to what I do as I am comfortable with Flutter but have some legacy Python apps I need to support as well as new project where I like to use some Python libraries while using Flutter for the GUI. Looking forward to the macOS version!

**Comment by ndonkoHenri** [comment]
> We are going to implement a generation of macOS Flutter app with embedded Python, so you get a completely white-labeled, clean Flutter app without any hacks.

https://flet.dev/docs/publish
