### ISSUE TITLE
ft.app(main,view=ft.AppView.FLET_APP_HIDDEN) does not work.

### ISSUE THREAD

**Issue by vitaluska123** [flet-dev/flet#3222]
Windows.
it happends in new project too.
![image](https://github.com/flet-dev/flet/assets/87501597/691ebf6c-35fb-43e6-8b1b-b66f4bbc7fa2)

**Comment by FeodorFitsner** [comment]
Could you please use the right template to submit the issue?

**Comment by FeodorFitsner** [comment]
Close in favour of #3223
