### ISSUE TITLE
After pressing back button on android, next time app is opened it instantly shuts down

### ISSUE THREAD

**Issue by J-PRS** [flet-dev/flet#3229]
Makes android builds pretty much unshippable.

**Comment by SIRGPrice** [comment]
Im trying to capture androids back button events, but I dont know how. If you tell me how you capture it efectively, I definetly will help you with the next part. Dont missundertand me, I would help you right now if I could test the button event capture. Thanks.

**Comment by FeodorFitsner** [comment]
Is https://github.com/flet-dev/flet/pull/4580 trying to solve the same problem for Android TV? It uses PopScope widget.

**Comment by SIRGPrice** [comment]
Ok, I actualy solved the back button issue and it does not close the app after open a second time. Could you share some code to see what the problem is?

The issue was basicaly that flet play store test app does not support the back action, but if you make the apk it works perfectly.

**Comment by SIRGPrice** [comment]
Solved and proved: https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586

**Comment by SIRGPrice** [comment]
> Is #4580 trying to solve the same problem for Android TV? It uses PopScope widget.

Android back button event capture and use in routing and exit solved and proved here: #4495 (reply in thread)
