### ISSUE TITLE
Text overflow options for dropdown options

### ISSUE THREAD

**Issue by torablien** [flet-dev/flet#3231]
**Please Describe The Problem To Be Solved**

The overflow of long text options in a `Dropdown` render outside the container.  I'd like to use ellipsis or clip it. In Flet (0.22), the [Option](https://flet.dev/docs/controls/dropdown/#option-properties) class only supports `str`-type key and text fields.

**(Optional): Suggest A Solution**

In Flutter, the [TextStyle class has an overflow option](https://api.flutter.dev/flutter/painting/TextStyle-class.html#:~:text=overflow%20%E2%86%92%20TextOverflow). This option would be useful wherever there is text - it would be great if it was included in Flet's `TextStyle`.

Flet does have the [overflow option on the `Text` control](https://flet.dev/docs/controls/text/#overflow) but `Dropdown`'s `Option` class expects just a string. Another option could be using the `Text` control in `Option`, though this could be a potential issue in other controls. `Dropdown` does have a `text_style` property so adding the support within `TextStyle` so that could just work.

**Comment by torablien** [comment]
@ndonkoHenri @FeodorFitsner, is there an option or configuration for the value text? It overflows past the boundary of the dropdown itself.

Example:

<img width="803" alt="image" src="https://github.com/flet-dev/flet/assets/11454665/78152212-7448-4ee2-9b3d-9c52831232c5">


```python
import flet as ft


def main(page: ft.Page):
    text_style = ft.TextStyle(
        overflow=ft.TextOverflow.ELLIPSIS,
    )
    str_options = [
        "A really large option string that can take up a lot of space so it will likely overflow but it shouldn't go outside the dropdown area itself",
        "Option 2",
        "Option 3",
    ]
    options = [
        ft.dropdown.Option(str_option, text_style=text_style)
        for str_option in str_options
    ]
    dropdown = ft.Dropdown(options=options, value=str_options[0], text_style=text_style)
    container_with_border = ft.Container(
        content=dropdown, border=ft.border.all(1, "RED")
    )
    page.add(container_with_border)


ft.app(main)
```

**Comment by ndonkoHenri** [comment]
@torablien you can open a new issue for that.

**Comment by bdoohan-goog** [comment]
any status on this?

**Comment by ndonkoHenri** [comment]
@bdoohan-goog `Option` has a [`text_style`](https://flet.dev/docs/controls/dropdown#text_style-1) property (of type `TextStyle`) through which you can set the `overflow`.
