### ISSUE TITLE
textfiled in listtile bug

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3252]
**Description**

**Code example to reproduce the issue:**

```python
# -*- coding: utf-8 -*-

import flet as ft


def main(page: ft.Page):
    page.add(
        ft.ListTile(
            title=ft.Text('Hotkeys'),
            trailing=ft.TextField(
                width=150,
                hint_text=''.join(['Search', '...']),
                prefix_icon=ft.icons.SEARCH,
                max_lines=1,
                autofocus=True)))


ft.app(target=main)
```

**Describe the results you received:**
When the length of the input exceeds the length of textfiled, only half of the text is displayed.
![image](https://github.com/flet-dev/flet/assets/2862064/dc6593ad-9b2d-4580-bd96-9a715c73a54d)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.22.0
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
no
```

**Operating system**:

Windows 10

**Additional environment details:**

**Comment by BrentHuang** [comment]
Adding `max_length=100` to the textfield is even weirder.
![image](https://github.com/flet-dev/flet/assets/2862064/e065da60-9b69-4df0-95d6-b18b8d6c7fd2)

**Comment by ndonkoHenri** [comment]
Read this: https://python.plainenglish.io/how-to-resize-flets-textfield-control-without-the-content-going-invisible-6d268a4d96e1

**Comment by BrentHuang** [comment]
why content_padding=ft.Padding(left=5, top=3, right=5, bottom=3) ?

This is not the ultimate solution and seems mysterious. There is something wrong with the default parameters. I seem to have never encountered such a problem in other libraries.

**Comment by BrentHuang** [comment]
> Adding `max_length=100` to the textfield is even weirder. ![image](https://private-user-images.githubusercontent.com/2862064/329093965-e065da60-9b69-4df0-95d6-b18b8d6c7fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDc0MTIsIm5iZiI6MTcxNTI0NzExMiwicGF0aCI6Ii8yODYyMDY0LzMyOTA5Mzk2NS1lMDY1ZGE2MC05YjY5LTRkZjAtOTVkNi1iMThiOGQ2YzdmZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDkzMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVhMTMyY2JjYWFmZmU4MjY3MzNiYmFlMTY0N2FhMDVhZWYxMzU4NTllM2I1NjJkNzkyMmIyYzg3OTlkOTA3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9VZxn8sLUJ2pAon6uDW6qiqe_z52_lvaoISplZRWfw0)

here why does the input box become flat? contet_padding has been added as you said.

**Comment by ndonkoHenri** [comment]
> here why does the input box become flat? 

The text field alone has at the beginning a default height, and the `counter_text` you added takes up some of this height/space inorder to be properly displayed. 
You can increase the height of field using the `height` property.

`content_padding` is the solution to the textfield's content/text going partly/completely invisible.
