### ISSUE TITLE
picke_files can't get path property in web mode

### ISSUE THREAD

**Issue by xiaotech** [flet-dev/flet#326]
import flet
    from flet import (
      Page,
      ElevatedButton,
      FilePicker,
      FilePickerResultEvent
    )
    def main(page: Page):
      def select_file(e: FilePickerResultEvent):
         print(e.files)
        
      pfd = FilePicker(on_result=select_file)    
      page.overlay.append( pfd)    
      page.add(
          ElevatedButton(text='pick file', on_click=lambda _: pfd.pick_files()),
      )

    flet.app(target=main,port=80)

In flet-app mode，it‘ running with no problem 

  ` [FilePickerFile(name='msedgedriver.exe', path='D:\\system\\flet\\msedgedriver.exe', size=15517120)]`

but in web-browser it can not get the path property

 ` [FilePickerFile(name='msedgedriver.exe', path=None, size=15517120)]`

**Comment by liudonghua123** [comment]
Maybe add `bytes` property to FilePickerFile is a good solution, Because the underearth lib used is [file_picker](https://[pub.dev](https://pub.dev/packages/file_picker)/packages/file_picker), see also https://github.com/miguelpruivo/flutter_file_picker#load-result-and-file-details.

Now I have some code as follows, the open text file on web is not support currently.

```python
  def read_file_content(file_picker_file: FilePickerFile):
    # https://flet.dev/docs/controls/filepicker#result
    # path - full path to a file. Works for desktop and mobile only. None on web.
    # TODO: support web, add bytes property to FilePickerFile
    # see also https://github.com/miguelpruivo/flutter_file_picker#load-result-and-file-details
    if file_picker_file.path is None:
      alert_dialog = AlertDialog(title=Text("Not supported on web currently, please paste the content manually"))
      page.dialog = alert_dialog
      alert_dialog.open = True
      page.update()
      return
    with open(file_picker_file.path, "r") as f:
      return f.read()

  def on_file_pick_result(e: FilePickerResultEvent):
    global current_file_mode
    choosed_file: FilePickerFile = e.files[0] if e.files else None
    txt_content = txt_content1 if current_file_mode == File_MODE.FILE1 else txt_content2
    if choosed_file:
      txt_content.value = read_file_content(choosed_file)
    page.update()
```

**Comment by liudonghua123** [comment]
I am reading the code, and I tried to add `bytes` to `FilePickerFile`. However, I have some problems with transferring bytes data from dart to python using JSON.

@FeodorFitsner Could you help me or give me some advices.

The current wip is on [here](https://github.com/flet-dev/flet/compare/main...liudonghua123:flet:file_picker_bytes).

**Comment by liudonghua123** [comment]
> I am reading the code, and I tried to add `bytes` to `FilePickerFile`. However, I have some problems with transferring bytes data from dart to python using JSON.
> 
> @FeodorFitsner Could you help me or give me some advices.
> 
> The current wip is on [here](https://github.com/flet-dev/flet/compare/main...liudonghua123:flet:file_picker_bytes).

I have tested my forked [file_picker_bytes](https://github.com/liudonghua123/flet/tree/file_picker_bytes) branch, it's worked as expected.
