### ISSUE TITLE
Page `window_always_on_top` doesn't work if set after adding to page

### ISSUE THREAD

**Issue by torablien** [flet-dev/flet#3272]
**Description**

Setting the value of `Page` [`window_always_on_top`](window_always_on_top) after adding to the page doesn't seem to do anything (at least on macOS). The window does not stay on top, and instead acts like a normal window. If you set it before adding to the page, it works as expected.

**Code example to reproduce the issue:**

Failing:
```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.Text("Hello World!"))
    page.window_always_on_top = True


ft.app(main)
```

Passing:
```python
import flet as ft


def main(page: ft.Page):
    page.window_always_on_top = True
    page.add(ft.Text("Hello World!"))


ft.app(main)
```

**Describe the results you received:**

Window doesn't stay on top (acts like normal).

**Describe the results you expected:**

Window stays on top.

**Additional information you deem important (e.g. issue happens only occasionally):**

Consistently reproducible

**Flet version (`pip show flet`)**:

```
% pip show flet
Name: flet
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/admin/Code/flet-testing2/venv/lib/python3.12/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: 
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
```

**Operating system**:

M1 Pro Mac - OS X Sonoma 14.1.2

**Additional environment details:**

Python 3.12.2

**Comment by ndonkoHenri** [comment]
The provided Flet code behaves as expected on my Mac(exactly thesame specifications as yours), but don't face this issue.
Can you please share a screen record of the issue?

**Comment by torablien** [comment]
Oh sorry, I realized the problem only occurs if you set `window_always_on_top` after adding controls to the page. I've updated the original report to more precisely reflect that. Let me know if that works for you and/or if you need any additional info.

**Comment by torablien** [comment]
I can also reproduce this issue with other page window properties like `page.window_prevent_close` - they don't work if put after a Control to the page.

```
import flet as ft


def main(page: ft.Page):
    page.add(ft.Text("Hello World!"))
    page.window_prevent_close = True


ft.app(main)
```

**Comment by ndonkoHenri** [comment]
Ah, I see the issue: You need to update the `page` after those changes by calling `page.update()`.

**Comment by torablien** [comment]
Doh, silly mistake, sorry for the noise!
