### ISSUE TITLE
This example breaks flet without throwing a Python exception

### ISSUE THREAD

**Issue by kristaller486** [flet-dev/flet#3287]
**Description**

In the code example below, flet breaks without any clear debugging messages. If the error is expected behavior, it would still be helpful to see what caused the error.

```python
import flet as ft


def main(page: ft.Page):
    app = ft.Column([
        ft.Column(expand=True), # without expand=True all right
        ft.Row([ft.TextField()])
    ])
    page.add(app)
    page.update()


ft.app(target=main)
```

**Describe the results you received:**

When running the code flutter gives errors and the UI doesn't work

```
flet run
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
```

**Describe the results you expected:**

Something like `Error: expand=True not allowed here`

**Flet version (`pip show flet`)**:

```
Version: 0.22.1
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet==0.22.1
```

**Operating system**:

Linux Mint 20.3 and Web (Chromium 121.0.6167.160)

**Additional environment details:**

Python 3.10

**Comment by ndonkoHenri** [comment]
You need to `expand` the topmost `Column` too.
