### ISSUE TITLE
`ft.SnackBar` sets `behavior=ft.SnackBarBehavior.FLOATING`, no floating effect

### ISSUE THREAD

**Issue by ixuuux** [flet-dev/flet#3311]
**Description**

Use `behavior=ft.SnackBarBehavior.FLOATING` in `ft.SnackBar`

In `0.22.1`, There is no floating effect, it seems to be glued to the right side. 
In `0.20.2`, works fine. 
They use the same code.

![image](https://github.com/flet-dev/flet/assets/31958128/7c052908-cd02-46d9-82c0-845b321f4291)

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.window_width = 500
    page.window_height = 500
    page.window_center()

    page.snack_bar = ft.SnackBar(
        content=ft.Text(f"Hello, world!"),
        behavior=ft.SnackBarBehavior.FLOATING,
        width=200,
    )

    def show_snack_bar(e):
        page.snack_bar.open = True
        page.snack_bar.duration = 30 * 1000
        page.update()

    page.add(
        ft.FilledTonalButton(f'Show SnackBar', on_click=show_snack_bar),
        ft.Text(value=f'{ft.__name__} {ft.version.version}', style=ft.TextStyle(size=30, color=ft.colors.RED))
    )
    page.update()


if __name__ == '__main__':
    ft.app(main)
```

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.22.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\...\lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Operating system**:
Windows10

**Additional environment details:**
python 3.8.10

**Comment by ixuuux** [comment]
This is what I want. (Pay attention to the position of the `SnackBar` message at the bottom)

![image](https://github.com/flet-dev/flet/assets/31958128/3abbd267-7cfb-41a3-94e4-8c45d3133456)

**Comment by ixuuux** [comment]
@ndonkoHenri I updated this issues, please take a look.

**Comment by ndonkoHenri** [comment]
Thanks! Working on the fix.
