### ISSUE TITLE
ListFile hover_color not working as expected

### ISSUE THREAD

**Issue by mvolar** [flet-dev/flet#3315]
**Description**

According to #2710 the hoverColor for ListTile has been added, however it is not clear how to properly use it.

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page):
    page.title = "ListTile Examples"
    page.add(
        ft.Card(
            content=ft.Container(
                width=500,
                content=ft.Column(
                    [
                        ft.ListTile(
                            title=ft.Text("One-line list tile"), hover_color=ft.colors.BLUE,
                        )
                    ],
                    spacing=0,
                ),
                padding=ft.padding.symmetric(vertical=10),
            )
        )
    )

ft.app(target=main)
```

**Describe the results you received:**

I expected to see hover to trigger once my mouse gets over the tile, I can see in Flutter that the ListTile requires some additional complexity but I am unable to understand how to translate this to flet. Additionally I get no errors in the console running this code and the method is exposed.

**Flet version (`pip show flet`)**:

```
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\python\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Operating system**:

Windows

**Comment by ndonkoHenri** [comment]
You need to specify one of this properties too for `hover_color` to be shown: `on_click`, `url`, `toggle_inputs`
