### ISSUE TITLE
Standalone mobile using Beeware

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#332]
I saw a #213 by lijinshanmx a few days back. after seeing that, I wondered if we could use `Briefcase`(Beeware's packaging software) or `buildozer`(Kivy's packaging software) to do the same. I know that `Briefcase` uses `Chaquopy`, but I don't know what the case is with `buildozer`.

I don't know how to make it work as it is outside my area of expertise.
if you could please check it out.

shout out to @lijinshanmx for giving me the idea.

**Comment by FeodorFitsner** [comment]
I don't think either `Breifcase` or `Chaquopy` can be used directly as they work with their own presentation layers.
I'm trying to collect the materials for a possible solution in this issue: https://github.com/flet-dev/flet/issues/284
Right now a "working" idea is calling Python from Flutter using Dart FFI. Python could be built for iOS/Android using BeeWare helpers: https://github.com/beeware/Python-Apple-support
You are welcome to continue discussion in that issue. I'm going to close this one as a duplicate.
