### ISSUE TITLE
flet build apk error

### ISSUE THREAD

**Issue by zubuntu101** [flet-dev/flet#3332]
Hi all
I wanted to try Flet application (Flutter package for Python) to test how to build apk app.

(env)   $ pip list
Package               Version
--------------------- --------------
annotated-types       0.7.0
anyio                 4.3.0
arrow                 1.3.0
bcrypt                4.1.3
binaryornot           0.4.4
certifi               2024.2.2
cffi                  1.16.0
chardet               5.2.0
charset-normalizer    3.3.2
click                 8.1.7
cookiecutter          2.6.0
cryptography          42.0.7
dnspython             2.6.1
email_validator       2.1.1
exceptiongroup        1.2.1
fastapi               0.111.0
fastapi-cli           0.0.4
flet                  0.22.1
flet-core             0.22.1
flet-runtime          0.22.1
future                1.0.0
h11                   0.14.0
httpcore              1.0.5
httptools             0.6.1
httpx                 0.27.0
idna                  3.7
Jinja2                3.1.4
markdown-it-py        3.0.0
MarkupSafe            2.1.5
mdurl                 0.1.2
netmiko               4.3.0
ntc_templates         5.0.0
oauthlib              3.2.2
orjson                3.10.3
packaging             23.2
paramiko              3.4.0
pip                   24.0
pycparser             2.22
pydantic              2.7.1
pydantic_core         2.18.2
Pygments              2.18.0
PyNaCl                1.5.0
pypng                 0.20220715.0
pyserial              3.5
python-dateutil       2.9.0.post0
python-dotenv         1.0.1
python-multipart      0.0.9
python-slugify        8.0.4
PyYAML                6.0.1
qrcode                7.4.2
repath                0.9.0
requests              2.32.2
rich                  13.7.1
scp                   0.14.5
setuptools            59.6.0
shellingham           1.5.4
six                   1.16.0
sniffio               1.3.1
starlette             0.37.2
text-unidecode        1.3
textfsm               1.1.3
typer                 0.12.3
types-python-dateutil 2.9.0.20240316
typing_extensions     4.11.0
ujson                 5.10.0
urllib3               2.2.1
uvicorn               0.29.0
uvloop                0.19.0
watchdog              4.0.0
watchfiles            0.21.0
websockets            12.0

 But i have encounter this error :

(env)   $ flet build apk 
Creating Flutter bootstrap project from 
gh:flet-dev/flet-build-template with ref 0.22.1...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Generating splash screens...OK
Packaging Python app...Running package command
Creating asset directory: 
/tmp/flet_flutter_build_8zrA008gVF/app
Copying Python app from /home/zte/Videos/1/main to 
/tmp/serious_python_tempEMYEPA
Configured mobile platform with sitecustomize.py at 
/tmp/serious_python_sitecustomizeZXLAWK/sitecustomize.py
Installing dependencies  with pip command to 
/tmp/serious_python_tempEMYEPA/__pypackages__
Downloading Python distributive from 
https://github.com/indygreg/python-build-standalone/releases/d
ownload/20231002/cpython-3.11.6+20231002-x86_64-unknown-linux-
gnu-install_only.tar.gz to 
/tmp/cpython-3.11.6+20231002-x86_64-unknown-linux-gnu-install_
only.tar.gz
Extracting Python distributive from 
/tmp/cpython-3.11.6+20231002-x86_64-unknown-linux-gnu-install_
only.tar.gz to /tmp/hostpython3.11_EUYQOO

/tmp/hostpython3.11_EUYQOO/python/lib/python3.11/site-packages
/_distutils_hack/__init__.py:33: UserWarning: Setuptools is 
replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run 
successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      Collecting setuptools>=61.0.0
        Obtaining dependency information for 
setuptools>=61.0.0 from 
https://files.pythonhosted.org/packages/de/88/70c5767a0e43eb44
51c2200f07d042a4bcd7639276003a9c54a68cfcc1f8/setuptools-70.0.0
-py3-none-any.whl.metadata
        Using cached 
setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
      Collecting wheel
        Obtaining dependency information for wheel from 
https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3
dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-
none-any.whl.metadata
        Using cached wheel-0.43.0-py3-none-any.whl.metadata 
(2.2 kB)
      Collecting cffi>=1.12
        Downloading cffi-1.16.0.tar.gz (512 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.9/512.9
kB 1.4 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 
'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with 
status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 
'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with 
status 'done'
      Collecting setuptools-rust>=1.7.0
        Obtaining dependency information for 
setuptools-rust>=1.7.0 from 
https://files.pythonhosted.org/packages/f7/7f/8b1c33598b03ad61
2b8ced223f9ca54076b789fabf5a66ce37cc096d9cf7/setuptools_rust-1
.9.0-py3-none-any.whl.metadata
        Using cached 
setuptools_rust-1.9.0-py3-none-any.whl.metadata (9.3 kB)
      Collecting pycparser (from cffi>=1.12)
        Obtaining dependency information for pycparser from 
https://files.pythonhosted.org/packages/13/a3/a812df4e2dd5696d
1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py
3-none-any.whl.metadata
        Downloading pycparser-2.22-py3-none-any.whl.metadata 
(943 bytes)
      Collecting semantic-version<3,>=2.8.2 (from 
setuptools-rust>=1.7.0)
        Obtaining dependency information for 
semantic-version<3,>=2.8.2 from 
https://files.pythonhosted.org/packages/6a/23/8146aad7d88f4fcb
3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-
2.10.0-py2.py3-none-any.whl.metadata
        Using cached 
semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
      Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
      Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Using cached setuptools_rust-1.9.0-py3-none-any.whl (26 
kB)
      Using cached 
semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Using cached pycparser-2.22-py3-none-any.whl (117 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished 
with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for cffi (pyproject.toml) did not run
successfully.
        │ exit code: 1
        ╰─> [48 lines of output]
      
                No working compiler found, or bogus compiler 
options passed to
                the compiler from Python's standard 
"distutils" module.  See
                the error messages above.  Likely, the problem
is not related
                to CFFI but generic to the setup.py of any 
Python package that
                tries to compile C code.  (Hints: on OS/X 
10.8, for errors about
                -mno-fused-madd see 
http://stackoverflow.com/questions/22313407/
                Otherwise, see 
https://wiki.python.org/moin/CompLangPython or
                the IRC channel #python on irc.libera.chat.)
      
                Trying to continue anyway.  If you are trying 
to install CFFI from
                a build done in a different context, you can 
ignore this warning.
      
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-311
            creating build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/backend_ctypes.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/__init__.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/lock.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/cparser.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/api.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/cffi_opcode.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/verifier.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/vengine_cpy.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/setuptools_ext.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/vengine_gen.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/model.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/recompiler.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/pkgconfig.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/error.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/commontypes.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/_shimmed_dist_utils.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/_imp_emulation.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/ffiplatform.py -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/_cffi_include.h -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/parse_c_type.h -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/_embedding.h -> 
build/lib.linux-x86_64-cpython-311/cffi
            copying src/cffi/_cffi_errors.h -> 
build/lib.linux-x86_64-cpython-311/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-x86_64-cpython-311
            creating build/temp.linux-x86_64-cpython-311/src
            creating build/temp.linux-x86_64-cpython-311/src/c
            Cannot_compile_native_modules -Wsign-compare 
-Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall 
-fdebug-default-version=4 -fPIC -I/tools/deps/include 
-I/tools/deps/include/ncursesw -I/tools/deps/libedit/include 
-fPIC -DFFI_BUILDING=1 
-I/tmp/hostpython3.11_EUYQOO/python/include/python3.11 -c 
src/c/_cffi_backend.c -o 
build/temp.linux-x86_64-cpython-311/src/c/_cffi_backend.o
            error: command 'Cannot_compile_native_modules' 
failed: No such file or directory
            
      
        note: This error originates from a subprocess, and is 
likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is 
required to install pyproject.toml-based projects
      
       A new release of pip is available: 23.2.1 -> 24.0
       To update, run: 
/tmp/hostpython3.11_EUYQOO/python/bin/python3 -m pip install 
--upgrade pip
      
  
  note: This error originates from a subprocess, and is likely
not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run 
successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely 
not a problem with pip.

 A new release of pip is available: 23.2.1 -> 24.0
 To update, run: /tmp/hostpython3.11_EUYQOO/python/bin/python3
-m pip install --upgrade pip

Error building Flet app - see the log of failed command above.

**Comment by FeodorFitsner** [comment]
Please do not use pip freeze: https://flet.dev/docs/publish#project-structure
