### ISSUE TITLE
how add netmiko to flet app

### ISSUE THREAD

**Issue by zubuntu101** [flet-dev/flet#3339]
Hi all
I want to add netmiko to flet project ..The steps are
mkdir first-flet-app
cd first-flet-app
python3 -m venv .venv
source .venv/bin/activate
pip install flet
flet create my_pro
cd my_pro     
flet build apk

After complete...I got error

Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/serious_python_tempQTFUCL/main.py", line 2, in <module>
ModuleNotFoundError: No module named 'netmiko'

How to add netmiko and what is suitable version ?

**Comment by ndonkoHenri** [comment]
You might want to read this: https://flet.dev/blog/flet-packaging-update

**Comment by zubuntu101** [comment]
requirements.txt file is only
flet==0.22.*

but when add any version of netmiko  to requirements.txt file ..I got error when flet build apk

**Comment by ndonkoHenri** [comment]
Closing this issue in favour of #3839
