### ISSUE TITLE
ModuleNotFound in apk build

### ISSUE THREAD

**Issue by marcodonatucci** [flet-dev/flet#3341]
Hi guys, I built an apk file of my python project that includes the cv2 module to scan a QR code, I built the p4a version with all the dependencies and I’m not including cv2 in the requirements file as specified in the Flet documentation. In the dist directory I can see cv2 in the specific directories like arm64 or x86_64… I added the dist to the path of serious python and I built the apk file. Everything went good but now when I open the file on my phone there’s a ModuleNotFound exception because he cannot find cv2. How can I solve this?

**Comment by ProPython007** [comment]
Same problem! any updates? @marcodonatucci

**Comment by marcodonatucci** [comment]
I didn't check If they solved the issue with the new update, I'm sure they will because it's a very common problem as I'm seeing from the community. For now I found another way to implement the functionality of reading QR codes by adding the FilePicker and sending the image to an online qr decoding service by API. Hope this was helpful.

**Comment by ndonkoHenri** [comment]
Closing in favour of #3839
