### ISSUE TITLE
Global update for type hinting: `IconStr` enum and `ColorStr` type alias

### ISSUE THREAD

**Issue by bleudev** [flet-dev/flet#3348]
**Please Describe The Problem To Be Solved**

I want to create new enum: `IconStr` in `types.py`. `IconStr` enum's variables is all icons from `icons.py`. `ColorStr = Union[HexStr, Literal['primary', 'on_primary', ...]`. Also i want to use this new variables in all controls
**(Optional): Suggest A Solution**

Create enum `IconStr` with all icons from `icons.py` and create variable `ColorStr = Union[HexStr, Literal['primary', 'on_primary', ...]`

It's for my future PR :)

**Comment by ndonkoHenri** [comment]
We moved away from literals in favor of enums.
Please use `Enums` instead.

**Comment by bleudev** [comment]
> We moved away from literals in favor of enums. Please use `Enums` for both instead.
> 
> You could create `Colors` and `Icons` enums (the singular form could have been better but `Icon` is a Control) which could be used as follows: `ft.Colors.BLUE`. The types will then be `Optional[Colors]` and `Optional[Icons]`.
> 
> While moving to enums we need to take care of backward compatibility for `ft.colors.BLUE`. For this, I suggest you dont remove the current variables in those modules now, but simply copy them into the new enum.
> 
> Let's discuss on [discord](https://discord.com/channels/981374556059086931/1243237230080688199) if you want.

Thanks, but about literals with ColorStr. I don't know how make and enum string and hex color in one type hinting. Only way - use type alias with `HexStr` (i'll want to make new type hinting - `HexStr` represents hex string) and with `Literal`.

I don't want use this:

```
class Colors(Enum): ...

def a(x: Union[HexStr, Colors] # It's hard!

def a(x: Colors) # i want to use new type hinting this way
```

How i can make this?

**Comment by ndonkoHenri** [comment]
I personally think we should leave colors and icons as-is. I mean, what is honestly the issue with `Optional[str]` ? it's short and normal - nothing fancy, no? 
However, if you dont think its the case, then I suggest you could create something like `OptionalString=Optional[str]`, then use it where necessary. I dont see the need of having `HexStr`, `ColorStr`, `IconStr`, etc, which are at the end of the day thesame (`= Optional[str]`)

**Comment by FeodorFitsner** [comment]
OK, let's leave it as is for now and settle other things. Lots of changes recently and there are even more changes towards 1.0 :)
