### ISSUE TITLE
Feature request: Unify all open_...() method into open()

### ISSUE THREAD

**Issue by bleudev** [flet-dev/flet#3367]
**Please Describe The Problem To Be Solved**

Feodor said in review of my pull (#3172) that it'll be great if will there is open() method. I'm requesting to add this in my future pull and requesting realisation. f. e.

```py
page.open('drawer')
# or
drawer = ...
page.open('drawer', drawer)
```

Also it'll great that will there is close() method

```py
page.close('drawer')
```

**Comment by ndonkoHenri** [comment]
> if drawer isn't in page it will be appended to this page

What do you mean?
