### ISSUE TITLE
Custom splash screen

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#337]
every time flet loads, we get a loading page of flet icon or a loading wheel spinning.
Is there a way to make a custom splash screen come up in place of the flet logo?

**Comment by ndonkoHenri** [comment]
This is exactly the issue i was about to raise!
I checked the docs, but nothing.

Please HELP on this.

**Comment by hololeo** [comment]
you can create an assets folder then replace the elements you want in there. 
https://flet.dev/docs/guides/python/packaging-desktop-app#packaging-assets

**Comment by ndonkoHenri** [comment]
That’s for desktop apps.
I mean for web apps. (For example, those made with fly.io or replit)

**Comment by ndonkoHenri** [comment]
[https://github.com/flet-dev/examples/tree/main/python/apps/custom-loading-image](https://github.com/flet-dev/examples/tree/main/python/apps/custom-loading-image)
I tried to follow this example. But when I implement this in my project, it doesn't work. I mean, the flet logo still shows up at the web app's launch.

**Comment by hololeo** [comment]
you created assets folder, and inside that icons folder, and in there the file to replace?
Only put in what you want changed

**Comment by ndonkoHenri** [comment]
Yes. Exactly.
I named the file just as in the example. (loading-animation.png)

I even tried with the icon image provided in the example's `assets/icon` folder.
But nothing.

**Comment by hololeo** [comment]
post your code and structure in a repo?

**Comment by FeodorFitsner** [comment]
Enable logging and see what's being loaded and from where:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by ndonkoHenri** [comment]
**It worked now.** 
`DEBU[2022-09-20T15:40:15+02:00] EmbedAssetsFS item: icons/loading-animation.png`
I just had to restart all from scratch(i was in hotreload mode). Just from noticing while closely looking at the logs that, any file added to my assets/icons directory(while still in HotReload) is never loaded/added. Is this a Bug or something normal @FeodorFitsner ?

So I can say briefly that, **Restarting my app from scratch kind of solved the problem.** Hope yours too @vv2006-mc !
Thanks y'all.

**Comment by ndonkoHenri** [comment]
By the way, **does the name of the icon(`loading-animation.png`) matters.**
Will any other image(icon) with a different name get loaded? (what if there are several image files in this `icons`directory? Any order of priority or something..?)

And also, **is it possible to change the Animation at launch screen?** By default, the image get bigger and fades away before our app's UI is shown...is it possible to change this Animation? If Yes, how please?

**Comment by ndonkoHenri** [comment]
> post your code and structure in a repo?

[https://github.com/ndonkoHenri/ToDo-App-with-Flet](https://github.com/ndonkoHenri/ToDo-App-with-Flet)
a personalised version of the example in the docs

**Comment by hololeo** [comment]
yeah hot reload works great but usually needs a reboot if you change something on init / startup. glad you got it fixed i know how those small overlooked things can drive you nuts 

nice repo btw!

**Comment by vv2006-mc** [comment]
is there a way to change this loading animation too? @FeodorFitsner
![image](https://user-images.githubusercontent.com/62519221/192153306-609bd19f-6ec6-44ca-985f-71170ccb19c7.png)

**Comment by FeodorFitsner** [comment]
Ah, well, that UI is built *before* user app's data is loaded. I think it would be possible to customize with a custom Flet app runner which is coming soon™.

**Comment by ndonkoHenri** [comment]
> custom Flet app runner

Still in your todo?
