### ISSUE TITLE
cocoapods error in macos and ios building process

### ISSUE THREAD

**Issue by Bbalduzz** [flet-dev/flet#3379]
I'm encountering an error in the `flet build macos` and `flet build ipa` stream.
It seems that the cocoapods are damaged no matter what I do. 
I've reinstalled them multiple times using `gem`, more precisely this has been my installation process:
```
sudo gem uninstall cocoapods
```
```
rm -rf ~/.cocoapods
sudo rm -rf /usr/local/bin/pod
sudo rm -rf /usr/local/CocoaPods
sudo rm -rf /Library/Ruby/Gems/*/gems/cocoapods-*
sudo rm -rf /Library/Ruby/Gems/*/specifications/cocoapods-*
```
```
gem install cocoapods --user-install
```
```
export PATH="$HOME/.gem/ruby/3.1.0/bin:$PATH"
```
```
source ~/.zshrc
```

but I cannot get them to work. build error below

## environment checks
```
┌(edoardomacbook-air)-[~/Projects/flet_flow_layout]
└─ $ ruby -v && gem --version && pod --version && python3.10 -m pip show flet
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin23]
3.5.10
1.15.2
Name: flet
Version: 0.22.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: fletmint
```
```
┌(edoardomacbook-air)-[~/Projects/flet_flow_layout]
└─ $ xcode-select --install
xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates                          
```
```
┌(edoardomacbook-air)-[~/Projects/flet_flow_layout]
└─ $ flutter doctor                                                                  1 ⨯
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-IT)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.71.0-insider)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Edoardo’s iPhone. Ensure the device
      is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 3 categories.
```
## addtional `pubspec.yaml`
```
name: flet_flow_layout
description: flow layout for flet
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flet_staggered_grid_view:
    path: /Users/edoardo/Projects/flet_staggered_grid_view

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

## build error
```
┌(edoardomacbook-air)-[~/Projects/flet_flow_layout]
└─ $ sudo flet build macos                                                         126 ⨯
Creating Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 
0.22.1...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...OK
Building macOS bundle...Resolving dependencies...
Downloading packages...
  fl_chart 0.65.0 (0.68.0 available)
  flutter_lints 2.0.3 (4.0.0 available)
  flutter_markdown 0.6.23 (0.7.1 available)
  flutter_native_splash 2.3.7 (2.4.0 available)
  flutter_staggered_grid_view 0.6.2 (0.7.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  lints 2.1.1 (4.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.12.0 (1.15.0 available)
  package_info_plus 4.2.0 (8.0.0 available)
  package_info_plus_platform_interface 2.0.1 (3.0.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 4.0.2 (5.0.1 available)
  test_api 0.7.0 (0.7.1 available)
  toml 0.14.0 (0.15.0 available)
  vm_service 14.2.1 (14.2.2 available)
  web_socket_channel 2.4.5 (3.0.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
20 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme

   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different 
from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation 
for instructions.

CocoaPods not installed or not in valid state.

Error building Flet app - see the log of failed command above.
```
> [!NOTE]  
> verbose
>  ```
> ┌(edoardomacbook-air)-[~/Projects/flet_flow_layout]
> └─ $ sudo flet build macos -v                                             
> Password:
> Flutter bootstrap directory: /tmp/flet_flutter_build_uOK4Gj4Cg3
> Additional Flutter dependencies:
> {
>     'flutter': {'sdk': 'flutter'},
>     'flet_staggered_grid_view': {
>         'path': '/Users/edoardo/Projects/flet_staggered_grid_view'
>     }
> }
> Creating Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 
> 0.22.1...OK
> Customizing app icons and splash images...OK
> Generating app icons...
> Run subprocess: ['/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/dart', 'run', 
> 'flutter_launcher_icons']
>    Woah! You appear to be trying to run flutter as root.
>    We strongly recommend running the flutter tool without superuser privileges.
>   /
> 📎
> Resolving dependencies in `/private/tmp/flet_flutter_build_uOK4Gj4Cg3`... (1.3s)
> Downloading packages... 
> Got dependencies in `/private/tmp/flet_flutter_build_uOK4Gj4Cg3`.
> Building package executable... (1.2s)
> Built flutter_launcher_icons:flutter_launcher_icons.
>  ════════════════════════════════════════════
>      FLUTTER LAUNCHER ICONS (v0.13.1)                               
>   ════════════════════════════════════════════
>   
> • Creating default icons Android
> • Overwriting the default Android launcher icon with a new icon
> • Overwriting default iOS launcher icon with new icon
> Creating Icons for Web...              done
> Creating Icons for Windows...          done
> Creating Icons for MacOS...            done
> 
> ✓ Successfully generated launcher icons
> OK
> Packaging Python app...
> Run subprocess: ['/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/dart', 'run', 
> 'serious_python:main', 'package', '/Users/edoardo/Projects/flet_flow_layout', 
> '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
>    Woah! You appear to be trying to run flutter as root.
>    We strongly recommend running the flutter tool without superuser privileges.
>   /
> 📎
> Building package executable... 
> Built serious_python:main.
> Running package command
> Creating asset directory: /private/tmp/flet_flutter_build_uOK4Gj4Cg3/app
> Copying Python app from /Users/edoardo/Projects/flet_flow_layout to /tmp/serious_python_temp07RhGi
> Installing dependencies [flet-embed] with pip command to /tmp/serious_python_temp07RhGi/__pypackages__
> Extracting Python distributive from /tmp/cpython-3.11.6+20231002-aarch64-apple-darwin-install_only.tar.gz to /tmp/hostpython3.11_fdLsU5
> Compiling Python sources at /tmp/serious_python_temp07RhGi
> Delete unnecessary files with extensions: [.py, .c, .h, .typed, .exe]
> Delete unnecessary files and directories: [__pycache__, bin]
> Creating app archive at /private/tmp/flet_flutter_build_uOK4Gj4Cg3/app/app.zip from /tmp/serious_python_temp07RhGi
> Deleting temp directory /tmp/serious_python_temp07RhGi
> Deleting Python directory /tmp/hostpython3.11_fdLsU5
> OK
> Building macOS bundle...
> Run subprocess: ['/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/flutter', 'build', 
> 'macos']
>    Woah! You appear to be trying to run flutter as root.
>    We strongly recommend running the flutter tool without superuser privileges.
>   /
> 📎
> Resolving dependencies... 
> Downloading packages... 
>   fl_chart 0.65.0 (0.68.0 available)
>   flutter_lints 2.0.3 (4.0.0 available)
>   flutter_markdown 0.6.23 (0.7.1 available)
>   flutter_native_splash 2.3.7 (2.4.0 available)
>   flutter_staggered_grid_view 0.6.2 (0.7.0 available)
>   js 0.6.7 (0.7.1 available)
>   leak_tracker 10.0.4 (10.0.5 available)
>   leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
>   lints 2.1.1 (4.0.0 available)
>   material_color_utilities 0.8.0 (0.11.1 available)
>   meta 1.12.0 (1.15.0 available)
>   package_info_plus 4.2.0 (8.0.0 available)
>   package_info_plus_platform_interface 2.0.1 (3.0.0 available)
>   petitparser 5.4.0 (6.0.2 available)
>   sensors_plus 4.0.2 (5.0.1 available)
>   test_api 0.7.0 (0.7.1 available)
>   toml 0.14.0 (0.15.0 available)
>   vm_service 14.2.1 (14.2.2 available)
>   web_socket_channel 2.4.5 (3.0.0 available)
>   xml 6.3.0 (6.5.0 available)
> Got dependencies!
> 20 packages have newer versions incompatible with dependency constraints.
> Try `flutter pub outdated` for more information.
> 
> Updating project for Xcode compatibility.
> Upgrading project.pbxproj
> Upgrading Runner.xcscheme
> Warning: CocoaPods is installed but broken. Skipping pod install.
>   You appear to have CocoaPods installed but it is not working.
>   This can happen if the version of Ruby that CocoaPods was installed with is different
>   from the one being used to invoke it.
>   This can usually be fixed by re-installing CocoaPods.
> To re-install see https://guides.cocoapods.org/using/getting-started.html#installation
> for instructions.
> 
> 
> 
> CocoaPods not installed or not in valid state.
> Deleting Flutter bootstrap directory /tmp/flet_flutter_build_uOK4Gj4Cg3
> 
> Run subprocess: ['/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/flutter', '--version']
> Error building Flet app - see the log of failed command above.
> ```

**Comment by ndonkoHenri** [comment]
Try installing cocoapads using brew: https://formulae.brew.sh/formula/cocoapods.

> Run subprocess: ['/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/flutter', '--version']

Btw, why does it seems like Flutter 3.7.3 is being used?

**Comment by john-c-kane** [comment]
I have the same issue.  I tried uninstalling cocoapods and reinstalling with homebrew but still same issue "CocoaPods in installed but broken."   is it possible flet build command is running wrong version of ruby (system ruby which is outdated versus homebrew/gem version?).  when i run flutter build macos directly on a new flutter project no cocoapods issue.  has anyone seen this or solved this? is there a way to run flutter build on a flet project?

**Comment by john-c-kane** [comment]
FYI I fixed my own problem.  The issue is i was running as SUDO flet build macos...  this was using the wrong GEM in the background i believe.  Fix was to chown any folders that issue permission errors when runnning flet build macos.  once get through all permission errors, run flet build macos will not have errors.
