### ISSUE TITLE
"MenuBar" GUI error in Linux (Gnome 46)

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#3380]
**Description**
I built an application (simple) for Windows and all is good, then I tried exactly the same in Linux and the control/widget "MenuBar" do an strange effect in the following case:
- If you click some "MenuBar" element and navigate just on the top of this element and hover/hold, then appears the "MenuBar" mega zoomed (I attach captures).

**Flet version (`pip show flet`)**:
v.0.22.1

**Operating system**:
Linux Ubuntu 24.04 , Gnome 46, Wayland , Kernel 6.8.0-31-generic)

**Additional environment details:**
x64

![Captura de pantalla de 2024-05-28 20-51-14](https://github.com/flet-dev/flet/assets/115594508/7b95193b-26b9-4fc6-8698-f56c0757baa0)
![Captura de pantalla de 2024-05-28 20-51-30](https://github.com/flet-dev/flet/assets/115594508/07cc8346-b78a-4de2-8aba-862de09f6d8f)

**Comment by nastiliano** [comment]
Here is.
Is when the mouse is over the top of the "MenuBar"

Thanks
[Enregistrament de pantalla del 2024-06-08 13-43-54.webm](https://github.com/flet-dev/flet/assets/115594508/7a8000f0-8489-41d6-b010-46e4a837718d)

**Comment by nastiliano** [comment]
Hello,

I tried just to code and "compile" with v.0.23.1 and the error remains.

Thank you.

**Comment by nastiliano** [comment]
Hello,

Today I tried the same with v.0.23.2.

Same error but it has enhanced.
Doesn't appear fullscreen (just a zoomed effect in the same MenuBar).

Thank you.
![Captura de pantalla de 2024-06-27 20-46-33](https://github.com/flet-dev/flet/assets/115594508/9b2bc499-c48c-49f1-927e-0e8dd056b925)

**Comment by nastiliano** [comment]
Hello,

Not only in "GNOME 46".
The same error in "Cinnamon 6.2" (Linux Mint 22)

Thanks.
Best regards.

**Comment by ndonkoHenri** [comment]
The error is a flutter issue. I will take some time to search their repo for any reported issue.

**Comment by nastiliano** [comment]
> The error is a flutter issue. I will take some time to search their repo for any reported issue.

Thanks!!! Best regards!

**Comment by nastiliano** [comment]
SOLVED IN  v.0.24    !!
