### ISSUE TITLE
No module named

### ISSUE THREAD

**Issue by claudioaguiarg** [flet-dev/flet#3382]
I had this problem with 2 libs that I tried to use in flet, and it gave the same problem, the first lib is cx_Oracle and the second is oracledb.

Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\claud\AppData\Roaming\Local\Temp\serious_python_tempb0bb1aed\main.py", line 2, in <module>
ModuleNotFoundError: No module named 'oracledb'

**Comment by tyu1996** [comment]
I think this issue is same as #2611  where flet did not package the Python libraries in virtual environment instead using global Python libraries.
This can be fixed by copying the whole 'site-packages' directory from .venv to the flet build's 'site-packages' directory.

**Comment by duyanh-y4n** [comment]
> I think this issue is same as #2611 where flet did not package the Python libraries in virtual environment instead using global Python libraries. This can be fixed by copying the whole 'site-packages' directory from .venv to the flet build's 'site-packages' directory.

I raised this issue https://github.com/flet-dev/flet/issues/3447 according to your comments with my own suggestion for packaging python project in general. Hopefully we can fix the build issue soon.

**Comment by ndonkoHenri** [comment]
Please give the latest Flet version a try.
