### ISSUE TITLE
TextField with on_change even

### ISSUE THREAD

**Issue by unitednews1111** [flet-dev/flet#3394]
**Description**
When we use TextField with on_change even every thing ok till use parameter key, when use key parameter  textField lost focuse when input data  

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    def textbox_changed(e):
        t.value = e.control.value
        page.update()

    t = ft.Text()
    tb = ft.TextField(
        label="Textbox with 'change' event:",
        on_change=textbox_changed,
        key=str(10)
    )

    page.add(tb, t)

ft.app(target=main)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:
Name: flet
Version: 0.22.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\Commander\PycharmProjects\Exchange\.venv\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of https://github.com/flet-dev/flet/issues/2210
