### ISSUE TITLE
Flet build apk stoping in (Extracting Python distributive) 

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#3408]
Some libraries in Python, such as firebase-admin, can cause the flet build apk command to freeze during the build process. The output stops at this line:

Extracting Python distributive from C:\Users\amgcy\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\amgcy\AppData\Local\Temp\hostpython3.11_f515b999

However, after removing firebase-admin from the requirements file, the build process works fine again.

OS:
flet==0.22.1
windows 10

**Comment by ndonkoHenri** [comment]
Please read this: https://flet.dev/blog/flet-packaging-update
