### ISSUE TITLE
flet build windows wrong

### ISSUE THREAD

**Issue by hionwi** [flet-dev/flet#3410]
**When using `flet build windows`, it gets stuck at "Packaging Python app...".**

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Text("Hello world!"))

ft.app(main)

```

**Describe the results you received:
PS C:\Users\hionwi\PycharmProjects\pythonProject\myApp> flet build windows
Creating Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.22.1...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...**

**Describe the results you expected:Correct build**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.22.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\Users\hionwi\PycharmProjects\pythonProject\.venv\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet==0.22.*
```

**Operating system**:
Windows

**Additional environment details:**

**Comment by ositoMalvado** [comment]
Try use pack. Example: 
`flet pack main.py --onedir --icon "some_icon.ico" --name "App Name" --add-data "assets:assets"`

**Comment by typedecker** [comment]
@ositoMalvado what about when pack isn't an option? like for when creating custom user extensions for flet? it doesn't let us build still, this doesn't fully solve the issue, it only provides an alternate version right?
