### ISSUE TITLE
How to load local pictures

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#342]
`https://flet.dev/docs/controls/image`

```
import flet
from flet import Page, Image

def main(page: Page):
    page.add(Image(src="F:/1.jpg"))

flet.app(
    target=main,
    assets_dir="assets"
)
```

![微信截图_20220917200029](https://user-images.githubusercontent.com/6490927/190855559-814e55f8-8289-4b00-9e11-8846c9dc7e1f.png)

**Comment by hololeo** [comment]
you need put 1.jpg in the assets folder that is relative to where you mainflet.py file is. Or you can load the file in with python and assign it to image

**Comment by FeodorFitsner** [comment]
Let's say your example could look like:

```python
import flet
from flet import Page, Image

def main(page: Page):
    page.add(Image(src="1.jpg"))

flet.app(
    target=main,
    assets_dir="F:\\"
)
```
