### ISSUE TITLE
camera demo ?

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#344]
Need a simple camera demo
Start Stop

**Comment by hololeo** [comment]
There is no camera support at the moment. Better to leave these kinds of questions in the discord.

**Comment by monkeycc** [comment]
Can I use cv2. VideoCapture (0) ?
Change Image

**Comment by FeodorFitsner** [comment]
I'm closing this issue as it's neither a bug, nor a feature request.

**Comment by goyalyashpal** [comment]
+ https://github.com/flet-dev/flet/issues/344
* https://github.com/flet-dev/flet/issues/648
* https://github.com/flet-dev/flet/discussions/1209
* https://github.com/flet-dev/flet/issues/1281
* https://github.com/flet-dev/flet/issues/1268
