### ISSUE TITLE
Building .apk for Android... took my 2 hours

### ISSUE THREAD

**Issue by zhang-yunqi** [flet-dev/flet#3440]
This is my first try to build android application with FLAT, but when I build apk(flat build apk) the step "Building .apk for Android..."took my 2 hours.Is this phenomenon common? In additionally, when I built it again, It takes 2 more hours again.

**Comment by ndonkoHenri** [comment]
Can you run the build command with [verbosity](https://flet.dev/docs/publish#verbose-logging), and share the full logs here? (Especially where it hangs..)

**Comment by NHLOCAL** [comment]
The likely hypothesis is that you have poor internet reception, and because the first time flet buid downloads a large amount of information, that's why it took so long

**Comment by baseplate-admin** [comment]
What is your system specs.

I think it could be one of these:

- Low internet bandwidth
- Low system RAM

**Comment by zhang-yunqi** [comment]
My system ram is enough. I think the reason maybe the network. But way it download these files everytime. Can I save them locally?

**Comment by NHLOCAL** [comment]
It doesn't download them every time, if I'm not mistaken after the first time it only downloads a smaller amount of files
