### ISSUE TITLE
Packaging Python app...Flet app package app/app.zip was not created.

### ISSUE THREAD

**Issue by MOHAMED-SEGHIR-Elhocine** [flet-dev/flet#3448]
I got this problem : Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Packaging Python app...Flet app package app/app.zip was not created.

I've used the command : flet build windows /Path/..

**Comment by Laztef** [comment]
u have problem whit dependencies. Try to upgrade flutter, dart, add the paths (use flutter doctor command in the terminal). Create your requirements.txt manually. If nothing work try to create a new env and install all the dependencies again.

**Comment by GidroN** [comment]
Have the same problem. Tried to recreate the env, but didn't work. Are there some other ways to solve it?

**Comment by MOHAMED-SEGHIR-Elhocine** [comment]
I managed to make it work by using PyCharm Community Edition, which has a built-in virtual environment. I was previously using VS Code. Thank you all.

**Comment by yucel685** [comment]
Sorunu çözebildiniz mi?

**Comment by ndonkoHenri** [comment]
@GidroN @yucel685 if you guys are facing this issue please share some more details (logs, repro code, captures etc).

**Comment by Laztef** [comment]
try to update python and flet! 
Delete the env folder and try to create this again.
Check your hdd capacity. If this is full you can't create the temp files to build your flet app

**Comment by TKZ700** [comment]
it's because of the requirements.txt . i think there's a problem with third party libraries

**Comment by diguijoaquim** [comment]
pessoal sera que o flet sempre leva as bibliotecas mesmo sem pyinatller?
ta meio dificil nao acho a diferenca de build recomendado e do pyintaller

**Comment by FeodorFitsner** [comment]
@diguijoaquim Try building with pre-release: https://flet.dev/blog/flet-new-packaging-pre-release

**Comment by mriscoc** [comment]
For reference, my requirements file was created using `pip freeze > requirements.txt` and it was saved using UTF-16 encoding which is incompatible with flutter, after open and save it in UTF-8 it works.
