### ISSUE TITLE
ENCHANTMENT: Add a `.fletignore` file

### ISSUE THREAD

**Issue by base-13** [flet-dev/flet#3450]
I think we should add a `.fletignore` file similar to `.gitignore`, it will ignore the files and directories during `flet build` so that you don't have to specify everytime and write big commands.

**Comment by ndonkoHenri** [comment]
Nice idea. But I think this could/will be covered by @FeodorFitsner in #3345.

**Comment by ndonkoHenri** [comment]
[Update](https://flet.dev/blog/pyproject-toml-support-for-flet-build-command/#:~:text=%3D%20%22src%22-,exclude,-%3D%20%5B%22assets)
