### ISSUE TITLE
FloatingActionButton Location

### ISSUE THREAD

**Issue by cudng** [flet-dev/flet#3461]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I place Floating button in center and it works fine if run it from my IDE on windows or if I use `flet run -- android` it' shows in the center. 
BUT after I created an APK file using `flet  build apk` and install the APP on android device somehow Floating button goes to the right. 
On the left side of screenshot provided APP running from IDE and on the right side same APP installed on android from APK file.

### To reproduce

![code](https://github.com/flet-dev/flet/assets/161624068/51aef63d-5fac-4828-8968-ae3dd5b32348)

### Screenshots

![photo_2024-06-13_10-45-42](https://github.com/flet-dev/flet/assets/161624068/980d726a-1938-4fb4-ac33-c9c419084458)

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.22.1

### Regression

I'm not sure / I don't know

**Comment by ndonkoHenri** [comment]
Please can you give a try to some other locations and report?

**Comment by SpellboundCoder** [comment]
> Please can you give a try to some other locations and report?



> Please can you give a try to some other locations and report?

I've tried CENTER_FLOATED and START_DOCKED, after compile app to APK file it always on the right

**Comment by ndonkoHenri** [comment]
Very strange issue. 
Marking as bug. Will investigate...

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of https://github.com/flet-dev/flet/issues/3867

Please mention any further details in there.
