### ISSUE TITLE
White screen when launching apk

### ISSUE THREAD

**Issue by ixenion** [flet-dev/flet#3465]
First of all I want to express my great gratitude for your titanic work.
This library is what we've all been waiting for. And finally it's here. 🥳

Unfortunatelly for some (unknown) reason I cant build working apk file.
Please, could you help to figure out what's going wrong?

I'm sorry that the issue turned out to be so big,
but I tried to provide as much information as possible.

**EXPECTATIONS**

Im trying to build apk from a simple flet template generated by:
```shell
# flet version
# flet==0.22.1
# flet-core==0.22.1
# flet-runtime==0.22.1
flet create simple-counter --description "A simple counter app." --template counter
```
Tree of the project:
```text
simple-counter
├── assets
│   └── icon.png
├── main.py
├── README.md
└── requirements.txt
```
**requirements.txt content:**
```text
flet
```
**main.py content**
```python
import flet as ft

def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(value="0", text_align=ft.TextAlign.RIGHT, width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,

        ),
    )
    page.update()

ft.app(main)
```

And on my ubuntu
```text
$ uname -a
Linux ubuntu 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC
Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
It works great

![image](https://github.com/flet-dev/flet/assets/48788888/07f2c06f-bbf5-4f1a-8be5-18f6bc23e86a)

**IN FACT**

Im using rooted android 10 **(!google servises are disabled with "titanium backup" app!)**
And getting blank white (if its white theme on my phone) screen:

![image](https://github.com/flet-dev/flet/assets/48788888/09b650f0-967b-47e3-bc29-f81c8879da9b)

**STEPS TO REPRODUCE**

Let me show you the way I followed - the full instruction

```shell
# Dependencies for Android studio
sudo apt install libncurses5 libstdc++6 libpango1.0-0 libcairo2
sudo apt install libc6 libncurses5 libstdc++6 lib32z1 libbz2-1.0


# Download and install android studio for linux
# https://developer.android.com/studio#downloads
tar xf android-studio-2023.3.1.19-linux.tar.gz
mv android-studio /opt/
sudo chown user:user -R /opt/androud-studio
studio.sh	# To install it.
# Now I have ~/Android/Sdk folder with its basic components

# Download and install android studio cmdline-tools
# https://developer.android.com/studio#downloads
unzip commandlinetools-linux-11076708_latest.zip
mv cmdline-tools ~/Android/Sdk

# Get flet
sudo apt update

cd ~/staff
mkdir android
cd android
python3.11 -m venv venv
source venv/bin/activate
pip install --upgrade cython flet numpy pyjnius


# Java
sudo apt install openjdk-17-jdk		# (~280mb)
# Select proper version if have several
sudo update-alternatives --config java

# flutter dependencies
sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
sudo apt-get install autoconf automake libtool lld	# (~121mb)
sudo apt-get install \
      clang cmake git \
      ninja-build pkg-config \
      libgtk-3-dev liblzma-dev \
      libstdc++-12-dev			# (~580mb)
sudo apt-get install \
    libc6:i386 libncurses5:i386 \
    libstdc++6:i386 lib32z1 \
    libbz2-1.0:i386			# (~30mb)


# Add env vars
vim ~/.zshrc
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export NDK_VERSION=25.2.9519653
export SDK_VERSION=android-24		# (33=Andr13; 24=Andr7) https://developer.android.com/tools/releases/platforms
# exit text editor
source ~/.zshrc


# Install android SDK, NDK
sudo apt install sdkmanager
echo "y" | sdkmanager --install "tools;26.1.1"
# If you dont do the next two lines
# flutter would argue on "sdkmanager" (some errors - dont remember)
rm ~/ANdroid/Sdk/tools/bin/sdkmanager
sudo cp /usr/bin/sdkmanager ~/Android/Sdk/tools/bin

# Add one more env variable for sdkmanager in ~/.zshrc
export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH

# Install rest android studio tools
echo "y" | sdkmanager --install "ndk;$NDK_VERSION" --channel=3	# (~1.7gb)
echo "y" | sdkmanager --install "platforms;$SDK_VERSION"	# (~140mb)
# Get (update) licenses
sdkmanager --licenses

# Install flutter (flet depends on flutter)
sudo snap install flutter --classic	# (~??)
# Init flutter
flutter				# (additional ~714mb)
# Disable data collection
flutter --disable-analytics
dart --disable-analytics
# Check that all is correct
flutter doctor


# Im not using native libraries, so skipping part with p4a

# Build apk
flet build apk --no-android-splash -vv
```

### Also Id like to share all my log files:
1. Flutter doctor output:
[flutter_doctor_log.txt](https://github.com/user-attachments/files/15836129/flutter_doctor_log.txt)
```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 22.04.4 LTS 6.5.0-35-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

2. flet build apk log
```shell
flet build apk -vv > log.txt 2>&1
```
[flet_build_apk_counter_log.txt](https://github.com/user-attachments/files/15836296/flet_build_apk_counter_log.txt)

The end of file (success):
```text
[        ] Gradle was unable to watch the file system for changes. Unable to watch same file twice via different paths: Already watching path: /home/arix/celestial/staff/android/flutter/packages/flutter_tools/gradle.
[ +518 ms] Running Gradle task 'assembleRelease'... (completed in 89.6s)
[   +1 ms] Calculate SHA1: LocalDirectory: '/tmp/flet_flutter_build_zNaJ81wqCf/build/app/outputs/flutter-apk'/app-release.apk
[ +781 ms] ✓ Built build/app/outputs/flutter-apk/app-release.apk (82.0MB)
[   +1 ms] "flutter apk" took 93,036ms.
[   +2 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
OK
Copying build to build/apk directory...Copying build output from: 
/tmp/flet_flutter_build_zNaJ81wqCf/build/app/outputs/flutter-apk/*
OK
Deleting Flutter bootstrap directory /tmp/flet_flutter_build_zNaJ81wqCf
Success!
```

3. For some (also unknown for me) reason I cant retreive app logs with adb logcat from my phone.
So Iv used Android studio emulator with android 12 onboard.
Iv filtered output by app process "com.flet.simple_counter"
[adb_logcat.txt](https://github.com/user-attachments/files/15836415/adb_logcat.txt)
And there is one suspicious line at the bottom:
```text
2024-06-14 12:52:41.927 8417-8442/com.flet.simple_counter E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Python bundle not found: /data/app/~~oBoaGFKoA5ReTiQP6tT_Og==/com.flet.simple_counter-7Y4KtOMlLA6NzuR-db1nLQ==/lib/arm64/libpythonbundle.so
    #0      SeriousPythonAndroid.run (package:serious_python_android/serious_python_android.dart:49)
    <asynchronous suspension>
```
Could this line cause the problem?
How can I fix that?
Or maybe I should use higher sdk version and not 24th for my android 10?
Also Iv seen that you suggest download flutter manually and not via snap,
Why so? Seems snap flutter works fine according to "flutter doctor".

Unfortunatelly I cant attach counter.apk because of github rules.

So here's all my evidence. 
Will be very grateful for any help 💪🔥

May be there is some ready for use linux VM or docker or something else?)

**Comment by ixenion** [comment]
May be there is some ready for use VM or docker or something else?)

**Comment by ixenion** [comment]
Ok, I found terrible solution:
Find libpythonbundle.so file in your system
```shell
sudo find / -name "libpythonbundle.so" | grep arm
```
In my case it was
```text
/home/arix/.pub-cache/hosted/pub.dev/serious_python_android-0.7.0/android/src/main/jniLibs/arm64-v8a/libpythonbundle.so
```
And copy this file into your phone at (as said adb logcat error message):
```text
/data/app/~~oBoaGFKoA5ReTiQP6tT_Og==/com.flet.simple_counter-7Y4KtOMlLA6NzuR-db1nLQ==/lib/arm64/libpythonbundle.so
```
Done.

Now investigating on why this file wasnt included by default...

**Comment by SpellboundCoder** [comment]
Where did you find that folder on your phone? Do I need root privilege to see it?

**Comment by ixenion** [comment]
> I have exact same issue, unfortunately I still have warranty on my device and I don't wanna root it. I wish there would be another way to fix this bug

Hehe, there is another way) see below

**Comment by ixenion** [comment]
So, after  some investigation I found that last version of Flet (for me it was 0.22.1 on 16th june 2024) doesnt compile .apk properly.
Look at the screenshot below: Iv installed .apk and in this folder should be at least "libpythonbundle.so", but there is nothing!..

![image](https://github.com/flet-dev/flet/assets/48788888/33520a1f-1989-478a-9525-34382db5c8bd)


Then I tryed several methods and solution for me is to downgrade flet from 0.22.1 to 0.21.2
And look at that) There is a bunch of files here right after usual installation) And of course there is "libpythonbundle.so"

![image](https://github.com/flet-dev/flet/assets/48788888/d167c905-23d7-4e5c-b15f-88cdb83e9a42)

I really don't like this solution method, I want to use the latest version of the library)
Developers comrades, please, pay attention to this bug.

**Comment by FeodorFitsner** [comment]
Hold tight, my friend, we are currently working on the next release of serious_python which does not depend on Kivy and has a new packaging mechanics.

**Comment by ixenion** [comment]
> Hold tight, my friend, we are currently working on the next release of serious_python which does not depend on Kivy and has a new packaging mechanics.

Thank you, I'm looking forward to it!

**Comment by NHLOCAL** [comment]
> Then I tryed several methods and the solution for me was to downgrade flet version from 0.22.1 to 0.21.2

From my testing, switching to version 0.22.0 should solve the problem. No need to downgrade to an older version
