### ISSUE TITLE
"SnackBar" doesn't work in MacOS Sonoma v.14.5 (Intel Processor)

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#3469]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Simply the control "SnackBar" doesn't work/appear

### Code

    page.snack_bar = ft.SnackBar(content = ft.Text("Hello world") , duration = 5000)
    page.snack_bar .open = True
    page.update()

### To reproduce

    page.snack_bar = ft.SnackBar(content = ft.Text("Hello world") , duration = 5000)
    page.snack_bar .open = True
    page.update()

### Operating System

macOS

### Operating system details

14.5 (Intel Processor)

### Flet version

0.22.1

### Regression

No, it isn't

**Comment by ndonkoHenri** [comment]
I have thesame mac version but with m1 chip and the snackbar works.
Can you please some full code i directly run to test?
If possible, could you share screenshots?

**Comment by nastiliano** [comment]
Thank you very much for your response.

This weekend I'll try just a simple page with some code and I'm going to try again and will inform you.

Thanks.

**Comment by nastiliano** [comment]
Hello again.

Imposssible to try anything.

With Flet v.0.23.1 I can't even compile, dark screen with Visual Studio.

Just this code:

    import flet as ft

    def main(page: ft.Page):
    
        page.expand = True
    
        page.add(
                ft.Card(expand = True ,
                        content = ft.Container(expand = True ,
                                               content = ft.Row(alignment = ft.MainAxisAlignment.CENTER ,
                                                                expand = True ,
                                                                vertical_alignment = "START" ,
                                                                #scroll = "ALWAYS" ,
                                                                controls = [ft.Container(ft.Column(expand = True ,
                                                                                                   horizontal_alignment = ft.CrossAxisAlignment.START,
                                                                                                   scroll = "ALWAYS" ,
                                                                                                   controls = [ft.Image(src=f"https://picsum.photos/500?random", 
    width=500, height=500, fit=ft.ImageFit.NONE) ,
                                                                                                               ft.TextField(label = "Hello World" , width = 400)
                                                                                                              ]
                                                                                                   )
                                                                                        ) ,
                                                                                                    
                                                                            ft.VerticalDivider() ,

                                                                            ft.Container(ft.Column(expand = True ,
                                                                                                   scroll = "ALWAYS" ,
                                                                                                   controls = [ft.Image(src=f"https://picsum.photos/500?random", 
    width=500, height=500, fit=ft.ImageFit.NONE) ,
                                                                                                               ft.TextField(label = "Hello World" , width = 400)
                                                                                                              ]
                                                                                                  )
                                                                                        )
                                                                            ]
                                                                )
                                                )
                         )
                )

    ft.app(target=main)

**Comment by ndonkoHenri** [comment]
Even this code works on my end. 
![image](https://github.com/flet-dev/flet/assets/98978078/793c80d1-62e7-4193-888d-f883b062403d)

Can you please try the code on web?
`ft.app(target=main, view=ft.AppView.WEB_BROWSER)`

**Comment by nastiliano** [comment]
Hello,

Sorry for my delay, but I only have access to MacOS weekends.

This weekend I'll inform to you.

Thanks.

**Comment by ndonkoHenri** [comment]
Reopen the issue once you try and still face issues.
