### ISSUE TITLE
flet doesn't load svg entirey 

### ISSUE THREAD

**Issue by yahiashamaa** [flet-dev/flet#3472]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

when import the svg, parts of loads but "<tspan>" doesnt load

### Code

import flet as ft

def main(page: ft.Page):
    pic= ft.Image(
        src="./s.svg",
        width="274",
        height="202"
    )
    page.add(pic)
    page.update()

ft.app(target=main)

### To reproduce

Run the given code using  ![s](https://github.com/flet-dev/flet/assets/111356355/ceeef9f6-5624-406a-b1a5-2085a29c3409) as the svg file

### Expected behavior

Correct output should look like the svg but the "text"  and "tspan" tags are completely missing

### Screenshots

![Screenshot 2024-06-16 013112](https://github.com/flet-dev/flet/assets/111356355/e3a7cb2f-b560-4098-b1cd-5e03c6f200a0)

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.22.1

### Regression

I'm not sure / I don't know

### Suggestions

I think that the "flutter_svg" package is at fault and can't correctly load the "text" or "tspan" tags. I am not sure whether the svg or flet is at fault.

**Comment by ndonkoHenri** [comment]
You svg might somehow be the issue. Click on your below svg and view what is shown:
![s](https://github.com/flet-dev/flet/assets/111356355/ceeef9f6-5624-406a-b1a5-2085a29c3409)
