### ISSUE TITLE
Add Mobile Ads Features (Rewarded Interstitial, Interstitial Video, App Open Ads)

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#3474]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

We need to integrate three types of mobile ads: Rewarded Interstitial, Interstitial Video, and App Open Ads. These ads will help monetize the app and enhance user engagement through rewarded content

**Comment by jeasoft** [comment]
Hmm, it seems like #286 to me, not 100% sure of course

**Comment by zox47** [comment]
> Hmm, it seems like #286 to me, not 100% sure of course

Yes, but this new type of ads hasn't been fully developed yet

**Comment by ndonkoHenri** [comment]
Closing as duplicate of https://github.com/flet-dev/flet/issues/286
Let's have all concerning ads at one spot. 
Feel free to mention any additional stuff in there.
