### ISSUE TITLE
Blank Screen After Build APk And Too Much Large Size of APK File

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3475]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

i created my project apk many times its working fine but yesterday and today when i build apk its build but when i run it in mobile its showing blank screen so i noticed its size is too high means double 78 MB of previous 41 MB then i test it on another project same issue there i think the bug come in previous 2 to 3 days

### To reproduce

i created my project apk many times its working fine but yesterday and today when i build apk its build but when i run it in mobile its showing blank screen so i noticed its size is too high means double 78 MB of previous 41 MB then i test it on another project same issue there i think the bug come in previous 2 to 3 days

### Operating System

Windows

### Operating system details

Android

### Flet version

0.22.1

### Regression

I'm not sure / I don't know

**Comment by fasilwdr** [comment]
Yes, I am experiencing the same issue. However, I am curious about why it occurred suddenly, without any recent updates or releases.

**Comment by Muddassirofficial** [comment]
> Yes, I am experiencing the same issue. However, I am curious about why it occurred suddenly, without any recent updates or releases.

May be this occurred due to flutter update but I also try this after upgrading flutter still same issue facing

**Comment by SpellboundCoder** [comment]
Here's the answer ...
[White screen when launching apk #3465](https://github.com/flet-dev/flet/issues/3465)

**Comment by FeodorFitsner** [comment]
It is fixed in Flet 0.23.1.

Please cleanup Cookiecutter cache before running `flet build` command.

On Windows:

```
rd /s /q %USERPROFILE%\.cookiecutters
```

On Mac/Linux:

```
rm -rf ~/.cookiecutters
```

**Comment by yst-one** [comment]
hello word apk  170M！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/publish/android#building-platform-specific-apk
