### ISSUE TITLE
Floating Action Button Location (FloatingActionButtonLocation) dont't work in v0.23

### ISSUE THREAD

**Issue by azhago** [flet-dev/flet#3485]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hi,
Just upgraded in v0.23:
floating_action_button_location param in page or view do not work anymore, floating ction button are always at bottom right of the page/view.

### Code

```py import flet as ft

def main(page: ft.Page) -> None:

    floating_button = ft.FloatingActionButton(
        icon=ft.icons.ADD,
        tooltip="Add",
        on_click=lambda _: print("Floating action button clicked"),
    )

    page.add(ft.Text("Floating action button location"))
    page.add(ft.Text("V23"))

    page.window_width = 500
    page.window_height = 500
    page.vertical_alignment = ft.MainAxisAlignment.START
    page.horizontal_alignment = ft.CrossAxisAlignment.START

    page.floating_action_button = floating_button
    page.floating_action_button_location = ft.FloatingActionButtonLocation.START_FLOAT
    page.update()

    print(page._get_attr("floatingActionButtonLocation"))

if __name__ == "__main__":
    ft.app(target=main)
```

### To reproduce

Run the previous code in v0.23.0

### Screenshots

v0.23.0
![image](https://github.com/flet-dev/flet/assets/66644024/27994640-034d-4e7f-bcbb-0abca3c1a9dc)
same code with v0.22.1
![image](https://github.com/flet-dev/flet/assets/66644024/62fa397f-936c-4120-999b-d640d6e95896)

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.23.0

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

**Comment by ndonkoHenri** [comment]
I get this:
![image](https://github.com/flet-dev/flet/assets/98978078/77164824-f127-4d8c-8957-f7f5ed4f4025)

**Comment by azhago** [comment]
I think it's platform dependant.
I recreate a brand new venv and install flet from scratch:

- I have this problem under windows 11 ( (floating action button on the default side)

- Making an exe with flet pack : same probleme

- It work fine in web_browser (floating action button on the left side)
I can't test under mac or linux

**Comment by azhago** [comment]
Wow, so fast!
Thanks for your great work 👍
