### ISSUE TITLE
`flet_permission_handler` breaks version solving

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3486]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

PS C:\Users\Muddassir Farooq\Desktop\Permission> & "C:/Users/Muddassir Farooq/AppData/Local/Programs/Python/Python312/python.exe" "c:/Users/Muddassir Farooq/Desktop/Permission/main.py"
PS C:\Users\Muddassir Farooq\Desktop\Permission> flet build apk --include-packages flet_permission_handler
[00:03:22] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.23.0 ✅                                                                                                              
           Customized app icons and splash images ✅                                                                                                                                                              
[00:03:25] Because every version of flet_permission_handler depends on flet ^0.23.0 and permission depends on flet ^0.22.1, flet_permission_handler is forbidden.
           So, because permission depends on flet_permission_handler any, version solving failed.

           You can try the following suggestion to make the pubspec resolve:
           * Try upgrading your constraint on flet: dart pub add flet:^0.23.0

[00:03:26] Error building Flet app - see the log of failed command above.
PS C:\Users\Muddassir Farooq\Desktop\Permission> 

### Code

import flet as ft

def main(page: ft.Page):
    page.scroll = ft.ScrollMode.ADAPTIVE
    page.appbar = ft.AppBar(title=ft.Text("PermissionHandler Tests"))
    ph = ft.PermissionHandler()
    page.overlay.append(ph)

    def check_permission(e):
        o = ph.check_permission(e.control.data)
        page.add(ft.Text(f"Checked {e.control.data.name}: {o}"))

    def request_permission(e):
        o = ph.request_permission(e.control.data)
        page.add(ft.Text(f"Requested {e.control.data.name}: {o}"))

    def open_app_settings(e):
        o = ph.open_app_settings()
        page.add(ft.Text(f"App Settings: {o}"))

    page.add(
        ft.OutlinedButton(
            "Check Microphone Permission",
            data=ft.PermissionType.MICROPHONE,
            on_click=check_permission,
        ),
        ft.OutlinedButton(
            "Request Microphone Permission",
            data=ft.PermissionType.MICROPHONE,
            on_click=request_permission,
        ),
        ft.OutlinedButton(
            "Open App Settings",
            on_click=open_app_settings,
        ),
    )

ft.app(main)

### To reproduce

PS C:\Users\Muddassir Farooq\Desktop\Permission> & "C:/Users/Muddassir Farooq/AppData/Local/Programs/Python/Python312/python.exe" "c:/Users/Muddassir Farooq/Desktop/Permission/main.py"
PS C:\Users\Muddassir Farooq\Desktop\Permission> flet build apk --include-packages flet_permission_handler
[00:03:22] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.23.0 ✅                                                                                                              
           Customized app icons and splash images ✅                                                                                                                                                              
[00:03:25] Because every version of flet_permission_handler depends on flet ^0.23.0 and permission depends on flet ^0.22.1, flet_permission_handler is forbidden.
           So, because permission depends on flet_permission_handler any, version solving failed.

           You can try the following suggestion to make the pubspec resolve:
           * Try upgrading your constraint on flet: dart pub add flet:^0.23.0

[00:03:26] Error building Flet app - see the log of failed command above.
PS C:\Users\Muddassir Farooq\Desktop\Permission> 

### Expected behavior

PS C:\Users\Muddassir Farooq\Desktop\Permission> & "C:/Users/Muddassir Farooq/AppData/Local/Programs/Python/Python312/python.exe" "c:/Users/Muddassir Farooq/Desktop/Permission/main.py"
PS C:\Users\Muddassir Farooq\Desktop\Permission> flet build apk --include-packages flet_permission_handler
[00:03:22] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.23.0 ✅                                                                                                              
           Customized app icons and splash images ✅                                                                                                                                                              
[00:03:25] Because every version of flet_permission_handler depends on flet ^0.23.0 and permission depends on flet ^0.22.1, flet_permission_handler is forbidden.
           So, because permission depends on flet_permission_handler any, version solving failed.

           You can try the following suggestion to make the pubspec resolve:
           * Try upgrading your constraint on flet: dart pub add flet:^0.23.0

[00:03:26] Error building Flet app - see the log of failed command above.
PS C:\Users\Muddassir Farooq\Desktop\Permission> 

### Operating System

Windows

### Operating system details

Windows

### Flet version

0.23.0

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

**Comment by ndonkoHenri** [comment]
Sorry for that! Will be fixed.

Thanks for reporting.

**Comment by Muddassirofficial** [comment]
Also recheck all those packages which we build using --include packages because they are creating issues and also this version also generate apk of double size with blank screen

**Comment by FeodorFitsner** [comment]
It's fixed now. Please rebuild your app.

**Comment by Muddassirofficial** [comment]
![Screenshot 2024-06-19 104853](https://github.com/flet-dev/flet/assets/135708579/41f036c6-29c3-4fbd-91c3-25bdfbeba20e)

Still Open App Setting Not Working

**Comment by FeodorFitsner** [comment]
what platform are you building for / running on?

**Comment by Muddassirofficial** [comment]
Android

> what platform are you building for / running on?

**Comment by Muddassirofficial** [comment]
also one more thing that now apk building is taking tooo long

**Comment by FeodorFitsner** [comment]
> also one more thing that now apk building is taking tooo long

Well, we need numbers :-/

Like it would be helpful if you could compare building with 0.22 and 0.23 with detailed logs.

**Comment by Muddassirofficial** [comment]
> what platform are you building for / running on?

kindly resolve one more issue that this latest  version build apk of double size and showing blank screen while launcing apk file as an android app

**Comment by Muddassirofficial** [comment]
> > also one more thing that now apk building is taking tooo long
> 
> Well, we need numbers :-/
> 
> Like it would be helpful if you could compare building with 0.22 and 0.23 with detailed logs.

i am building with 0.23.0

**Comment by FeodorFitsner** [comment]
blank screen fix is coming, sorry about that. Re: size - don't know - need to compare 0.22 and 0.23 as well. We can deal with that later.

**Comment by Muddassirofficial** [comment]
> 0.22

thanks but as u know permission handler depends on 0.23.0 and with this version i cant build apk because of blank screen and permission handler doesnt work on 0.22 and solution ???

**Comment by FeodorFitsner** [comment]
Ah, right. OK, 0.23.1 is coming today.

**Comment by Muddassirofficial** [comment]
> Ah, right. OK, 0.23.1 is coming today.

thanks for such a wonderful framework and thanks for fast help center

**Comment by Muddassirofficial** [comment]
in new release its still not solved
