### ISSUE TITLE
flet 0.23 critical erreur when runing application /  the application does not want to run ans stop

### ISSUE THREAD

**Issue by logololo** [flet-dev/flet#3490]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

 the application does not want to run with FLET v0.23  but work perfectly with flet 0.22 

### Code

import flet as ft

def main(page: ft.Page):
    

    page.add(
        ft.Text("Hello, World!", size=30),
    )

ft.app(target=main)

### To reproduce

** (flet:5945): CRITICAL **: 14:14:10.302: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

### Expected behavior

a simple  ' hello world  ' text

### Screenshots

** (flet:5615): CRITICAL **: 14:04:51.078: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlEventChannel *fl_event_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed
package:media_kit_libs_linux registered.

** (flet:5615): CRITICAL **: 14:04:51.078: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.078: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlTextureRegistrar *fl_plugin_registrar_get_texture_registrar(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_handler_find: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.079: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): GLib-GObject-WARNING **: 14:04:51.079: invalid (NULL) pointer instance

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.079: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(flet:5615): Gtk-CRITICAL **: 14:04:51.080: gtk_container_forall: assertion 'GTK_IS_CONTAINER (container)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(flet:5615): GLib-GObject-CRITICAL **: 14:04:51.080: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (flet:5615): CRITICAL **: 14:04:51.080: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
![save](https://github.com/flet-dev/flet/assets/123462001/beded4a4-aa9b-49e3-8481-3211ee3182f3)

### Operating System

Linux

### Operating system details

ubuntu 24  / flutter Flutter 3.22.2 

### Flet version

Name: flet Version: 0.23.0 Summary: Flet for Python - easily build interactive multi-platform apps in Python Home-page:  Author: Appveyor Systems Inc. Author-email: hello@flet.dev License: Apache-2.0 Location: /home/vox/.local/lib/python3.10/site-packages Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog Required-by: 

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Additional details

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (2 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by ndonkoHenri** [comment]
Related discussions: 
- https://github.com/ubuntu/yaru.dart/issues/903
- https://github.com/flet-dev/flet/discussions/3334

**Comment by logololo** [comment]
hi , 


in my opinion ,the problem is not related to Flutter, not directly.
here, it's FLET 0.23 and more precisely it's the change in flet Runtime from version 0.22.1 to version 0.23.
so , making corrections to Flutter will not solve the problem,

it's my opinion

**Comment by misterhackerman** [comment]
it's a bug or something with version 0.23. meanwhile u can pip install flet==0.22.1

**Comment by ndonkoHenri** [comment]
> in my opinion ,the problem is not related to Flutter, not directly.
here, it's FLET 0.23 and more precisely it's the change in flet Runtime from version 0.22.1 to version 0.23.
so , making corrections to Flutter will not solve the problem,

The things Flet 0.22.1 was built back then against Flutter 3.19.6 while this new 0.23.0 release is built against Flutter 3.22.2.

**Comment by FeodorFitsner** [comment]
But does the app work with those assertions or it crashes?

**Comment by logololo** [comment]
I am not an expert in FLET but I like it a lot and I use it more and more, I dont know if the transition to Flutter 3.22.2 was an absolute necessity to evolve FLET (and I think not) but in in the present case there is no solution to this Bug because even if I correct this bug in my machine and  in my package (FLET 0.23) the bug will reappear during the packaging of the application or during the execution of the application in an another machine.
to be more precise, the bug is related to Flutter 3.22 which is the basis of flet 0.23 so two solutions are possible:
- use an earlier version of flutter 3.19 or 3.20 i version for an update of FLET 0.23.1 (the most intelligent solution)

Or
- wait for the official correction in a future version of Flutter (it may take a long time) which will be very unpleasant for FLET.
- 
@FeodorFitsner: at my level of 'skill' I think it's not going to work, and even if I delve deeper into correcting the code of Flet 0.23 (or on my_application.cc), at best it will only work on my machine

It's just my opinion and my analysis

**Comment by FeodorFitsner** [comment]
Does the app start with the assertions shown or crash?

**Comment by FeodorFitsner** [comment]
I can reproduce the bug on my install of Ubuntu 22.04 (ARM) and looks like I'm going to have a fix for that...

**Comment by FeodorFitsner** [comment]
Flet 0.23.1 is out with the fix for Linux. Please give it another try and let me know.

**Comment by logololo** [comment]
It works like a charm :)

thank you for your work
