### ISSUE TITLE
Can no longer add package as detailed in the /integrating-existing-flutter-packages guide and the spinkit package

### ISSUE THREAD

**Issue by jameseflowers1000** [flet-dev/flet#3493]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Everything was working per the guide using the spinkit package as a prototype and based on ^0.22.1.  Worked for several days and then upon making a small change to the main.py for testing, got a broken app that displays:

> _Traceback (most recent call last):
>   File "<string>", line 43, in <module>
>   File "<frozen runpy>", line 229, in run_module
>   File "<frozen runpy>", line 88, in _run_code
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_tempxOmQuq/main.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_tempxOmQuq/__pypackages__/flet/__init__.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_tempxOmQuq/__pypackages__/flet_runtime/__init__.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_tempxOmQuq/__pypackages__/flet_core/__init__.py", line 204, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_tempxOmQuq/__pypackages__/flet_core/page.py", line 27, in <module>
> ModuleNotFoundError: No module named 'typing_extensions'_
> 

Tried going back to original main.py and rebuilding, but got the same error, so perhaps something changed in the template?

Decided to try 0.23.0 and now can no longer build:

  _

> _lib/main.dart:30:6: Error: A value of type 'Widget Function(Control?, String, bool, {Widget? nextChild, bool? parentAdaptive})' can't be assigned to a variable of type 'Widget? Function(CreateControlArgs)'.
>             - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/Users/jim/flutter/packages/flutter/lib/src/widgets/framework.dart').
>             - 'Control' is from 'package:flet/src/models/control.dart' ('/Users/jim/.pub-cache/hosted/pub.dev/flet-0.23.0/lib/src/models/control.dart').
>             - 'CreateControlArgs' is from 'package:flet/src/control_factory.dart' ('/Users/jim/.pub-cache/hosted/pub.dev/flet-0.23.0/lib/src/control_factory.dart').
>            flet.createControl,
>                 ^
>            lib/main.dart💯8: Error: Method not found: 'ensureInitialized'.
>              flet.ensureInitialized();
>                   ^^^^^^^^^^^^^^^^^
>            Target kernel_snapshot failed: Exception
> 
>            Command PhaseScriptExecution failed with a nonzero exit code
>            warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target
>            'Flutter Assemble' from project 'Runner')
>            ** BUILD FAILED **
> 
>            Build process failed_

_

### To reproduce

Try the spinkit example:   https://github.com/InesaFitsner/extend-flet-example

### Operating System

macOS

### Operating system details

14.4

### Flet version

0.22.1 and 0.23.0

### Regression

No, it isn't

**Comment by FeodorFitsner** [comment]
https://github.com/InesaFitsner/extend-flet-example has been updated to work with Flet 0.23. Please give it another try.

**Comment by jameseflowers1000** [comment]
Thanks Feodor,

Following your suggestion and cloning from your link, it now builds, but I still get:

> Traceback (most recent call last):
>   File "<string>", line 43, in <module>
>   File "<frozen runpy>", line 229, in run_module
>   File "<frozen runpy>", line 88, in _run_code
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_temp3KnbyR/main.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_temp3KnbyR/__pypackages__/flet/__init__.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_temp3KnbyR/__pypackages__/flet_runtime/__init__.py", line 1, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_temp3KnbyR/__pypackages__/flet_core/__init__.py", line 204, in <module>
>   File "/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/serious_python_temp3KnbyR/__pypackages__/flet_core/page.py", line 27, in <module>
> ModuleNotFoundError: No module named 'typing_extensions'

Note that I get a lot of warnings from the linker during the build, but the above errors seem to be in the python code:

> ld: warning: object file (/private/var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/flet_flutter_build_O7wNjx4lnt/build/macos/Build/Products/Release/XCFrameworkIntermediates/serious_python_darwin/libPython3.11.a[x86_64][147](frozen.o)) was built for newer 'macOS' version (11.0) than being linked (10.15)
> warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. (in target 'Runner' from project 'Runner')
> warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
> Building macOS application...
> ✓ Built build/macos/Build/Products/Release/flet_spinkit_app.app (119.7MB)
> [13:16:08] Built macOS bundle ✅
>            Copying build output from: /var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/flet_flutter_build_O7wNjx4lnt/build/macos/Build/Products/Release/flet_spinkit_app.app
> [13:16:09] Copied build to build/macos directory ✅
>            Deleting Flutter bootstrap directory /var/folders/wp/k19k64ln5hzcc8ygtlh3j9_m0000gn/T/flet_flutter_build_O7wNjx4lnt
>            Successfully built your macOS bundle! 🥳 Find it in build/macos directory. 📂

**Comment by FeodorFitsner** [comment]
`typing_extensions` fix is coming in 0.23.1 later today, sorry about that.

**Comment by jameseflowers1000** [comment]
Thank you so much!!!
