### ISSUE TITLE
Please update dependency libmpv.so.1 to libmpv.so.2

### ISSUE THREAD

**Issue by misterhackerman** [flet-dev/flet#3494]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

there is an error on runtime. that requires non-existant libmpv.so.1

### Code

`python -m venv venv && source venv/bin/activate && pip install flet && flet create demo && flet run demo`

### To reproduce

`python -m venv venv && source venv/bin/activate && pip install flet && flet create demo && flet run demo`

### Expected behavior

to work successfully using the new libmpv.so.2 library

### Operating System

Linux

### Operating system details

Arch Linux

### Flet version

flet 0.22.1 and 0.23.0

### Regression

I'm not sure / I don't know

### Additional details

I'm happy to help by opening a pull request but I don't think i have sufficient experience. can u point me to the file or files that fixes this. so that i can help?
i know that symlinking could solve the problem, but i want to help fix the issue from the core.

**Comment by FeodorFitsner** [comment]
I see both `libmpv.so.1` and `libmpv.so.2` are required by `media_kit_video` package that Flet uses for Video control: https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/core/native_library.dart#L53-L57

Maybe you can raise an issue in their repository to see what they think.

**Comment by FeodorFitsner** [comment]
Give a try to the solution in this comment: https://github.com/flet-dev/flet/issues/2637#issuecomment-2067801868 to see if that works.

**Comment by misterhackerman** [comment]
I got it working by symlinking. I'll see if anyone have a pull request to remove libmpv.so.1 from media-kit repo

**Comment by gab-luz** [comment]
Try the symlinking misterhackerman did. It worked for me, here's how you do it:
sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so.2 /usr/lib/x86_64-linux-gnu/libmpv.so.1

Don't forget to install libmpv2 first!
