### ISSUE TITLE
flet 0.23   bug in win7

### ISSUE THREAD

**Issue by ssz25** [flet-dev/flet#3501]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

use flet 0.22 on win7 is OK
use flet 0.23 on win7 is Err   ws2_32.dll can't find enter

### To reproduce

any flet proc

### Operating System

Windows

### Operating system details

win7

### Flet version

0.23.0

### Regression

No, it isn't

**Comment by ndonkoHenri** [comment]
Flet 0.22.0 was built using Flutter 3.19 which supported Win7/8.
Flet 0.23.0 is built with Flutter 3.22, version from which the support for Win7/8 has been officially dropped.

Ref: https://github.com/flutter/flutter/issues/140830#issuecomment-1936397549
