### ISSUE TITLE
Add enum support to `Slider` control

### ISSUE THREAD

**Issue by taaaf11** [flet-dev/flet#3508]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I think there should be a property (or a methodology or anything, you name it), so that, we can supply a subclass of `enum.Enum` to it. Then it should work like, `min` value would be the minimum value from the enum we supply, and the `max` value would be the maximum value from the enum values. And also, there should be option to choose the label as the `name` property of the `value` of the enum we give.

### Suggest a solution

There should be some property, which should accept the enum.

**Comment by ndonkoHenri** [comment]
I don't seem to understand your idea/suggestion.
Can you roughly share how the code for the enum will look like? and perhaps some code demonstrating a usage example.
