### ISSUE TITLE
After generating the apk and opening it on Android it appears on a white screen

### ISSUE THREAD

**Issue by Lucasapn2** [flet-dev/flet#3514]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I am facing an error when opening the apk it appears on a white screen, how can I resolve it? Is there any stable version? where it actually works? can anybody help me? it succeeds, it doesn't show an error.. only when opening it on android it doesn't work

### Code

import flet as ft

def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))

ft.app(main)

### To reproduce

(     ●) Building .apk for Andro  499,8s
(●     ) Building .apk for Android ⏳... √ Built build\app\outputs\flutter-apk\app-release.apk (78.0MB)
[10:52:35] Built .apk for Android ✅                                                                                                                                
           Copying build output from: C:\Users\Lucas\AppData\Local\Temp\flet_flutter_build_L2zJifnu1k\build\app\outputs\flutter-apk\*
           Copied build to build\apk directory ✅                                                                                                                   
           Deleting Flutter bootstrap directory C:\Users\Lucas\AppData\Local\Temp\flet_flutter_build_L2zJifnu1k
[10:52:57] Successfully built your .apk for Android! 🥳 Find it in  build\apk directory. 📂

### Operating System

Windows

### Operating system details

Windows 10 22H2

### Flet version

0.23.1

### Regression

I'm not sure / I don't know

**Comment by FeodorFitsner** [comment]
Dup of #3511

**Comment by sorincodes** [comment]
https://github.com/flet-dev/flet/issues/3511 does not exist anymore 👎
