### ISSUE TITLE
flet build aab - not work. white screen after start app

### ISSUE THREAD

**Issue by Aporial** [flet-dev/flet#3535]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

with `flet build apk` the app opens and runs successfully.
but with `flet build aab` starts up and shows a white screen.

each command completes successfully

### Code

```
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)

```

### To reproduce

`flet build aab`

### Screenshots

`flet build aab`
<img width="1018" alt="image" src="https://github.com/flet-dev/flet/assets/7197773/f9f5b374-7d3d-4447-b5b2-e5d450b04ba5">

### Operating System

macOS

### Operating system details

Monterey 12.7.5

### Flet version

Version: 0.22.1

### Regression

No, it isn't

**Comment by ndonkoHenri** [comment]
The below is from AI, give it a try:

> When you build an Android App Bundle (AAB), it cannot be directly tested on an Android emulator or device like an APK file. Instead, the AAB file is intended for distribution through the Google Play Store, where it will be dynamically optimized and split into smaller APKs that are specific to different device configurations.
> 
> However, you can still test the app locally by following these steps:
> 
> 1. **Download Bundletool**:
>    - Go to the [bundletool releases page](https://github.com/google/bundletool/releases).
>    - Download the latest `bundletool.jar`.
> 
> 2. **Generate APKs from the AAB**:
>    - Place the downloaded `bundletool.jar` in your project directory.
>    - Run the command:
>      ```bash
>      java -jar bundletool.jar build-apks --bundle=build/XXXX.aab --output=app.apks --mode=universal
>      ```
> 
> 3. **Extract and Install the Universal APK**:
>    - Extract the generated APKs:
>      ```bash
>      unzip app.apks -d output_folder
>      ```
>    - Install the universal APK using `adb`:
>      ```bash
>      adb install output_folder/universal.apk
>      ```
> 
> After these steps, your app will be installed on the emulator or device, and you can test it as you would with an APK file.

**Comment by Aporial** [comment]
> The below is from AI, give it a try:
> 
> > When you build an Android App Bundle (AAB), it cannot be directly tested on an Android emulator or device like an APK file. Instead, the AAB file is intended for distribution through the Google Play Store, where it will be dynamically optimized and split into smaller APKs that are specific to different device configurations.
> > However, you can still test the app locally by following these steps:
> > 
> > 1. **Download Bundletool**:
> >    
> >    * Go to the [bundletool releases page](https://github.com/google/bundletool/releases).
> >    * Download the latest `bundletool.jar`.
> > 2. **Generate APKs from the AAB**:
> >    
> >    * Place the downloaded `bundletool.jar` in your project directory.
> >    * Run the command:
> >      ```shell
> >      java -jar bundletool.jar build-apks --bundle=build/XXXX.aab --output=app.apks --mode=universal
> >      ```
> > 3. **Extract and Install the Universal APK**:
> >    
> >    * Extract the generated APKs:
> >      ```shell
> >      unzip app.apks -d output_folder
> >      ```
> >    * Install the universal APK using `adb`:
> >      ```shell
> >      adb install output_folder/universal.apk
> >      ```
> > 
> > After these steps, your app will be installed on the emulator or device, and you can test it as you would with an APK file.

I did everything that was written. But nothing has changed. When starting it shows just a black or white screen (depending on the theme in the phone)
![photo_2024-07-08_14-34-57](https://github.com/flet-dev/flet/assets/7197773/dddf9efe-6ef2-4868-8992-abca00248f41)

**Comment by ndonkoHenri** [comment]
Sorry, I think you will have to make some researches then.
Main point here is, AAB can't be run directly on Android.

- https://stackoverflow.com/questions/50419286/install-android-app-bundle-on-device

**Comment by jaychia0418** [comment]
I also have this issue, build APK can install and run properly, 
AAB convert to APK also can install and run properly, 
but if upload the AAB to play store and install from play store, it has white screen only when after start app

how to fix this?

**Comment by Muddassir-Farooq-official** [comment]
@ndonkoHenri help also facing this issue I have to publish client app made with flet on Google Play store but aab is showing blank screen
