### ISSUE TITLE
Content padding for TextField doesn't show on iOS

### ISSUE THREAD

**Issue by aurosevic** [flet-dev/flet#3541]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Property content_padding for the TextField doesn't work on iOS. I've set the property to "Servings" text field. Here's a screenshot on an app on Linux, where the property works as expected:

![Screenshot_20240625_211657](https://github.com/flet-dev/flet/assets/19304661/c860d821-76f3-48ab-9257-f6fbf4d9b3c3)

And here's a screenshot from iOS device, where the property did not take any effect:

![IMG_9246](https://github.com/flet-dev/flet/assets/19304661/56d7eca4-85f2-4e4b-a960-352534309896)

I am using iPhone 13 Pro Max with iOS 17.5.1.

Flet Application details:
* Client version: 1.5.1
* Flet SDK version: 0.21.1
* Python version 3.11.6

### To reproduce

Create a TextField with adaptive property set to True and run on iOS device.

### Operating System

Linux

### Operating system details

KDE Neon 6.0

### Flet version

0.23.1

### Regression

I'm not sure / I don't know

**Comment by ndonkoHenri** [comment]
The Flet mobile app needs to be updated to match the current Flet version.
Will be done in the coming days. 🤞🏾

**Comment by aurosevic** [comment]
Awesome, thanks!

**Comment by ndonkoHenri** [comment]
Closing in favor of https://github.com/flet-dev/flet/issues/3096
