### ISSUE TITLE
Blank Screen on Mac Intel

### ISSUE THREAD

**Issue by Schnurber** [flet-dev/flet#3557]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

`flet run` on the Mac (Intel I7 macOS Sonoma): An empty window appears, the program freezes. If I stop the process in the terminal, the Flet app still has to be closed separately via the task manager. This happened after I upgraded flutter (Flutter 3.22.2 with Dart 3.4.3) and installed the latest Flet version 0.23.2. `flet run --web` is working, but not the native app.

### Code

```
import flet as ft
def main_test(page):
    t = ft.Text(value="Hello, Mac!")
    page.controls.append(t)
    page.update()
ft.app(target=main_test)
```

### To reproduce

```
flutter upgrade
pip install flet
flet run
```

### Expected behavior

The app should not be an empty window that you can't close.

### Operating System

macOS

### Operating system details

Intel I7 macOS Sonoma

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

**Comment by Schnurber** [comment]
last version working is: 0.22.0

**Comment by beratcmn** [comment]
I am having the same error on my Intel Mac
