### ISSUE TITLE
Capitalization in TextField doesn't work

### ISSUE THREAD

**Issue by e-ferrara** [flet-dev/flet#3564]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When upgrading from version 0.22.* to 0.23.* I noticed that the TextField capitalization stopped working.

### Code

```
import flet as ft


def main(page: ft.Page):
    page.add(ft.TextField(capitalization=ft.TextCapitalization.CHARACTERS))


ft.app(main)
```

### To reproduce

Just type something and alternate between lowercase and uppercase.

### Expected behavior

In previous versions, when writing both lowercase and uppercase, the text entered was always seen in uppercase (Using ft.TextCapitalization.CHARACTERS or any other value).

### Screenshots

![image](https://github.com/flet-dev/flet/assets/79525934/3b95cec0-928f-4137-b700-139e08eeb6ed)

### Operating System

Windows

### Operating system details

Microsoft Windows 11 Pro

### Flet version

Version: 0.23.2

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Additional details

It worked correctly in version 0.22.*.

**Comment by ndonkoHenri** [comment]
Sorry for that! Will be fixed in a while...

**Comment by ndonkoHenri** [comment]
Issue has been fixed.
Give it a try by installing the latest Flet prerelease: `pip install flet --pre` (https://pypi.org/project/flet/#history)
Report if the issue persists.

**Comment by julianobramos** [comment]
Hello!
Still not working for me.
MacBook
macOS Sonoma 14.5
Flet 0.23.2

Code:

import flet as ft

def main(page: ft.Page):
    page.add(ft.TextField(capitalization=ft.TextCapitalization.CHARACTERS))

ft.app(main)

**Comment by ndonkoHenri** [comment]
My previous message explains how to grab the flet version with the fix.

**Comment by julianobramos** [comment]
With "pip install flet -U --pre", worked. Thank you!
