### ISSUE TITLE
ImportError: cannot import name 'is_coroutine' from 'flet_core.utils'

### ISSUE THREAD

**Issue by buton8744** [flet-dev/flet#3565]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I installed flet-fastapi using pip and installed flet.
The version of flet is 0.23.2. In this situation, when the code below is executed
ImportError: cannot import name 'is_coroutine' from 'flet_core.utils'
I got this error. If this is not how you should use it, I apologize for the bug report.

### Code

```
import asyncio
import flet as ft
import flet_fastapi

class Countdown(ft.Text):
    def __init__(self, seconds):
        super().__init__()
        self.seconds = seconds

    async def did_mount_async(self):
        self.running = True
        self.page.run_task(self.update_timer)

    async def will_unmount_async(self):
        self.running = False

    async def update_timer(self):
        while self.seconds and self.running:
            mins, secs = divmod(self.seconds, 60)
            self.value = "{:02d}:{:02d}".format(mins, secs)
            self.update()
            await asyncio.sleep(1)
            self.seconds -= 1

def main(page: ft.Page):
    await page.add_async(Countdown(120), Countdown(60))

app = flet_fastapi.app(main)
```

### To reproduce

1. pip install flet-fastapi
2. pip install flet
3. write code
4. run

### Operating System

macOS

### Operating system details

14.5(23F79)

### Flet version

Version: 0.23.2

### Regression

No, it isn't

**Comment by ndonkoHenri** [comment]
https://flet.dev/blog/flet-fastapi-and-async-api-improvements#:~:text=package%20has%20been-,deprecated,-and%20its%20contents
