### ISSUE TITLE
on_scroll in 0.23.2 doesnt work (ERROR Task exception was never retrieved. Key Error 'sd' etc)

### ISSUE THREAD

**Issue by Broys42** [flet-dev/flet#3566]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In new version flet on_scroll in any controls doesnt work

### Code

Code from doc - https://flet.dev/docs/controls/column/#scroll_tooffset-delta-key-duration-curve

```py

import threading
import flet as ft

class State:
    i = 0

s = State()
sem = threading.Semaphore()

def main(page: ft.Page):
    def on_scroll(e: ft.OnScrollEvent):
        if e.pixels >= e.max_scroll_extent - 100:
            if sem.acquire(blocking=False):
                try:
                    for i in range(0, 10):
                        cl.controls.append(ft.Text(f"Text line {s.i}", key=str(s.i)))
                        s.i += 1
                    cl.update()
                finally:
                    sem.release()

    cl = ft.Column(
        spacing=10,
        height=200,
        width=200,
        scroll=ft.ScrollMode.ALWAYS,
        on_scroll_interval=0,
        on_scroll=on_scroll,
    )
    for i in range(0, 50):
        cl.controls.append(ft.Text(f"Text line {s.i}", key=str(s.i)))
        s.i += 1

    page.add(ft.Container(cl, border=ft.border.all(1)))

ft.app(main)

```

### To reproduce

Try this code. I have exact problem in my projects

### Operating System

Windows

### Operating system details

11 23H2

### Flet version

0.23.2

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

**Comment by Broys42** [comment]
I changed all the on_scroll methods and ScrollableControl class from 0.19.0 to 0.23.2 and everything started working

**Comment by handouy** [comment]
Hey, hello. How'd you fix it?

Manually modify the class code?

**Comment by handouy** [comment]
I rolled back the flet version to 0.23.1 to work normally

**Comment by ndonkoHenri** [comment]
Issue has been fixed.
Give it a try by installing the latest Flet prerelease: `pip install flet --pre` (https://pypi.org/project/flet/#history)
Report if the issue persists.
