### ISSUE TITLE
Unable to update page using Threading

### ISSUE THREAD

**Issue by vishnu-rvb** [flet-dev/flet#3571]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

i am using threading to call page.update() periodically at a set time from a new thread. 
I also have a button called refresh that changes modifies page controls.
sometimes it is seen that page.update() is raising an error which i am not sure why and why its only sometimes and not all times.
i am sharing the relevant segments of the code.

### Code

```
from flet import app,Page
import time,threading
ThreadExit = threading.Event()

def newThread(func):
    def wrapped(*args,**kwargs):
        thread=threading.Thread(target=func,args=args,kwargs=kwargs)
        thread.start()
    return wrapped

def clockSchedule(func):
    @newThread
    def wrapped(*args,**kwargs):
        while not ThreadExit.is_set():
            func(*args,**kwargs)
            time.sleep(kwargs['dt'])
    return wrapped

class GUIApp:
    def Build(self,page: Page):
        #adds several flet controls including Refresh button
    def RefreshItems(self,page:Page):
        #modifies the added flet controls, triggered by press of Refresh button

    @clockSchedule    
    def updatePage(self,dt,page: Page):
        page.update()

    def run(self):
        target=lambda page:(self.Build(page),self.updatePage(dt=1/30,page=page))
        app(target=target)
        ThreadExit.set()
        quit()

if __name__=='__main__': GUIApp().run()
```

### To reproduce

1)Initial state:
![image](https://github.com/flet-dev/flet/assets/118911871/157398aa-079f-4ba2-bc55-74bff8cea30e)
2)Clicking Refresh button multiple times
3)When error is raised:
![image](https://github.com/flet-dev/flet/assets/118911871/e99a9a01-0386-4c04-91c5-462dae08e853)

### Expected behavior

Expected RefreshItems function call to be completed but is terminated due to the raised error

### Screenshots

Error seen
```
File "c:\Users\User\Documents\GitHub\Quarentine-Manager\main.py", line 27, in updatePage
    page.update()
  File "C:\Program Files\Python310\lib\site-packages\flet_core\page.py", line 718, in update
    r = self.__update(self)
  File "C:\Program Files\Python310\lib\site-packages\flet_core\page.py", line 832, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
  File "C:\Program Files\Python310\lib\site-packages\flet_core\page.py", line 848, in __prepare_update        
    control.build_update_commands(
  File "C:\Program Files\Python310\lib\site-packages\flet_core\control.py", line 464, in build_update_commands
    ctrl.build_update_commands(
  File "C:\Program Files\Python310\lib\site-packages\flet_core\control.py", line 464, in build_update_commands
    ctrl.build_update_commands(
  File "C:\Program Files\Python310\lib\site-packages\flet_core\control.py", line 464, in build_update_commands
    ctrl.build_update_commands(
  [Previous line repeated 1 more time]
  File "C:\Program Files\Python310\lib\site-packages\flet_core\control.py", line 480, in build_update_commands
    assert self.__uid is not None
AssertionError
```

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

Name: flet Version: 0.23.2 Summary: Flet for Python - easily build interactive multi-platform apps in Python Home-page: https://flet.dev Author: Appveyor Systems Inc. Author-email: hello@flet.dev License: Apache-2.0 Location: c:\program files\python310\lib\site-packages Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog Required-by:

### Regression

No, it isn't

### Suggestions

Seems like page update is hindered when refresh is in the process of modifying flet controls. would prefer if update checks and waits for end of refresh function call

**Comment by ndonkoHenri** [comment]
Please provide some runnable code which reproduces the issue.

**Comment by ethans333** [comment]
Im getting the same issue

**Comment by ndonkoHenri** [comment]
> Im getting the same issue

Saying it like this doesnt help at all.
Provide some runnable code to test the issue.

**Comment by burhansvural** [comment]
Please share the entire code so we can fully examine the issue.

**Comment by ethans333** [comment]
Fixed the issue. What I ended up doing is locking the threads right before creating/modifying the UI (this involves creating elements, updating the page, etc.) and then unlocking them right after. 

I believe the issue arose from a race condition involving the state of the page where certain threads were updating different versions of the same page.

I order to fix your specific issue go ahead and lock and unlock the threads before in after updating the page in the page function, like this:

```python
   import Threading
   
   lock = Threading.lock
   
   ...

    def updatePage(self,dt,page: Page):
        lock.aquire()
        page.update()
        lock.release()
```

If that doesn't work maybe try adding it to your RefreshItems function as well.

**Comment by vishnu-rvb** [comment]
@ethans333 yeah i too fixed my issue by disabling page update when controls are added but concern wise it should be page.updates responsibility to sort out its internal race conditions.

@ndonkoHenri  i will share a demo reproducing code for future references

**Comment by ethans333** [comment]
Agreed
