### ISSUE TITLE
the performance different  in local app and appview.web_browser

### ISSUE THREAD

**Issue by chenghunghsu** [flet-dev/flet#3591]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

i had create about 200 cards in one page, when i use local flet app it scroll as usual, but when i use browser when i scroll it might be  like lag.

**Comment by ndonkoHenri** [comment]
Wrong template choosen. 
Open a new issue, with the bug template and provide the demanded infos.
