### ISSUE TITLE
Unknown control: flashlight

### ISSUE THREAD

**Issue by Andrukva** [flet-dev/flet#3599]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When running on a physical device, it gives the error "unknown control: flashlight " and also swears at lambda. I use Windows11, Android Studio, Python 3.12.4 and Android 7. Please tell me how to fix it? Thank you in advance.

### Code

import flet as ft

def main(page: ft.Page):
    flashLight = ft.Flashlight()
    page.overlay.append(flashLight)
    page.add(
        ft.TextButton("toggle", on_click: lambda _: flashlight.toggle())
    )

ft.app(target=main)

### To reproduce

Unknown module flashlight 

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

**Comment by ndonkoHenri** [comment]
Using the official Flet app?
Or an `apk` you built?

**Comment by burhansvural** [comment]
![flet_flaslight](https://github.com/flet-dev/flet/assets/149883930/6c89a9cb-e02c-4720-a532-f5748f6882e6)

**Comment by burhansvural** [comment]
![flet_flaslight2](https://github.com/flet-dev/flet/assets/149883930/4ee98e09-0271-43fa-b223-ce8b67c39acf)

**Comment by ndonkoHenri** [comment]
I guess that's an apk you built.
It's really strange. Please make sure you are really using the latest Flet version: `flet --version`
Also, please share the logs of your app, with verbosity: https://flet.dev/docs/publish#verbose-logging

**Comment by burhansvural** [comment]
flet version : 0.24.0.dev3087

TheEthicalBoy ***@***.***>, 4 Tem 2024 Per, 23:32 tarihinde
şunu yazdı:

**Comment by Andrukva** [comment]
> ![flet_flaslight](https://private-user-images.githubusercontent.com/149883930/345936376-6c89a9cb-e02c-4720-a532-f5748f6882e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTg1MTMsIm5iZiI6MTcyMDE5ODIxMywicGF0aCI6Ii8xNDk4ODM5MzAvMzQ1OTM2Mzc2LTZjODlhOWNiLWUwMmMtNDcyMC1hNTMyLWY1NzQ4ZjY4ODJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTcyYjJiNDE0NDk3ZmFlZWM2MDc2YzY3NGY2MTM3NjUwYTEyZjc5OGEyODEwZjI1YjZkNWY2ODA1Yjg0NWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MkXO8uQGgguYkA7NU2t-Z3s4U_uYrWPoPvP2jZfd89E)

I got the same result.

**Comment by Andrukva** [comment]
I have version  Flet 0.23.2 and python version 3.12.4. I ran the code through the android studio and vs code. Windows 11.

**Comment by ndonkoHenri** [comment]
I tried it in my simulator and it works.
![image](https://github.com/flet-dev/flet/assets/98978078/613fcf02-f882-4b59-8d6a-b9b06e62e36b)

Please explain step-by-step how you run the code? 
Do you create an apk file? Or make use of the official Flet mobile app?

**Comment by Andrukva** [comment]
I am using the official mobile app Flet for Android.

**Comment by ndonkoHenri** [comment]
Yep, that was my guess.
Please subscribe to this: https://github.com/flet-dev/flet/issues/3096
