### ISSUE TITLE
Page Splash Bug

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3607]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

page.splash = None not works properly its a bug solve it as soon as possible and if possible also add a option to display splash ring or progressbar at cebnter of screen

### Code sample

<details open><summary>Logs</summary>

```python
from time import sleep
import flet as ft

def main(page: ft.Page):
    def button_click(e):
        page.splash = ft.ProgressBar()
        btn.disabled = True
        page.update()
        sleep(3)
        page.splash = None
        btn.disabled = False
        page.update()

    btn = ft.ElevatedButton("Do some lengthy task!", on_click=button_click)
    page.add(btn)

ft.app(target=main)
```

</details>

### To reproduce

To hide splash after completing operation

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows

### Flet version

0.23.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
`Page.splash` is deprecated as you might have noticed.
This is how you could do it: 
```py
from time import sleep
import flet as ft


def main(page: ft.Page):
    progress_bar = ft.ProgressBar(visible=False)
    page.overlay.append(progress_bar)

    def button_click(e):
        progress_bar.visible = True
        btn.disabled = True
        page.update()
        sleep(3)
        progress_bar.visible = False
        btn.disabled = False
        page.update()

    btn = ft.ElevatedButton("Do some lengthy task!", on_click=button_click)
    page.add(btn)


ft.app(target=main)

```
