### ISSUE TITLE
Flet APK exit gracefully 2

### ISSUE THREAD

**Issue by ixenion** [flet-dev/flet#3610]
I have to ask that again and again because on my previous attempts there was no final answer:
one: https://github.com/flet-dev/flet/discussions/3555
two: https://github.com/flet-dev/flet/issues/3587

I just want to know, wheither it possible at all. And if yes - show how. And if no - say no.

How do I make custom "cleanup" logic right before closing (destroying, removing from memory) the android app?

I have slightly modified simple counter code which doesnt work as expected
```python

import flet as ft


def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(value="0", text_align=ft.TextAlign.RIGHT, width=100)
    number = page.client_storage.get("number")
    txt_number.value = number if number else "0"


    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()


    row = ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,

        )

    page.add(
            row,
    )


    def handler(e:ft.AppLifecycleStateChangeEvent):
        if e.data == ft.AppLifecycleState.DETACH:
            page.client_storage.set("number", txt_number.value)
            page.window.destroy()

    page.on_app_lifecycle_state_change = handler
    page.window.prevent_close = True

ft.app(main)
```

Expectations: value was saved on app shutdown
Reality: counter value does not saved on app shutdown.

**Comment by ndonkoHenri** [comment]
Please avoid spamming issues.
Let's keep only one open: https://github.com/flet-dev/flet/issues/3566
Your question will be addressed when possible. Please be patient.
