### ISSUE TITLE
OnScrollEvent for Listview don't work for flet 0.23.2 

### ISSUE THREAD

**Issue by logololo** [flet-dev/flet#3612]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

hi ,  OnScrollEvent for Listview don't work in flet 0.23.2 , it give an error 

i use e: OnScrollEvent to print  (e.pixels )   to find  scrolling position ( delta )

it working fine in flet 0.22
on flet 0.23.1 it work fwhe i run  main.py (  for test code) but when not when i build APK (when code is compiled)
![Copie d'écran_20240706_211616](https://github.com/flet-dev/flet/assets/123462001/6dc5f390-edaf-48ff-a121-3350d54665c7)

### Code sample

<details open><summary>Logs</summary>

```python

import flet as ft

def main(page: ft.Page):
    page.title = "Scrolling ListView"
    
    def goo (e:ft.OnScrollEvent):
            
        print(f"{e.pixels}")
        print(f"{e.data}")
        global position
        position = e.pixels
        tx1.value= str(position)
        tx2.value= str(e.scroll_delta)
        tx1.update()
        tx2.update()
        return position  

    lv = ft.ListView(expand=1, spacing=10, padding=20, auto_scroll=False , 
            on_scroll = goo,    )         
       
    count = 1

    for i in range(0, 60):
        lv.controls.append(ft.Text(f"Line {count}" ))
        count += 1
    tx1 = ft.Text( size = 20 , color = "cyan")
    tx2 = ft.Text( size = 20 , color = "yellow")
    page.add(tx1 )
    page.add(tx2)    
    page.add(lv)


ft.app(target=main)
```

</details>

### To reproduce

Task exception was never retrieved
future: <Task finished name='Task-61' coro=<__run_socket_server.<locals>.on_event() done, defined at /home/vox/.local/lib/python3.10/site-packages/flet_runtime/app.py:217> exception=KeyError('sd')>
Traceback (most recent call last):
  File "/home/vox/.local/lib/python3.10/site-packages/flet_runtime/app.py", line 219, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/page.py", line 905, in on_event_async
    await handler(ce)
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/event_handler.py", line 18, in fn
    ce = self.__result_converter(e)
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/scrollable_control.py", line 22, in <lambda>
    self.__on_scroll = EventHandler(lambda e: OnScrollEvent(e))
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/scrollable_control.py", line 134, in __init__
    self.scroll_delta: Optional[float] = d["sd"]
KeyError: 'sd'

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

ubuntu 24  /  Flutter 3.22.2 

### Flet version

Name: flet Version: 0.23.2 Summary: Flet for Python - easily build interactive multi-platform apps in Python Home-page: https://flet.dev Author: Appveyor Systems Inc. Author-email: hello@flet.dev License: Apache-2.0 Location: /home/vox/.local/lib/python3.10/site-packages Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog Required-by:

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```
Task exception was never retrieved
future: <Task finished name='Task-61' coro=<__run_socket_server.<locals>.on_event() done, defined at /home/vox/.local/lib/python3.10/site-packages/flet_runtime/app.py:217> exception=KeyError('sd')>
Traceback (most recent call last):
  File "/home/vox/.local/lib/python3.10/site-packages/flet_runtime/app.py", line 219, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/page.py", line 905, in on_event_async
    await handler(ce)
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/event_handler.py", line 18, in fn
    ce = self.__result_converter(e)
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/scrollable_control.py", line 22, in <lambda>
    self.__on_scroll = EventHandler(lambda e: OnScrollEvent(e))
  File "/home/vox/.local/lib/python3.10/site-packages/flet_core/scrollable_control.py", line 134, in __init__
    self.scroll_delta: Optional[float] = d["sd"]
KeyError: 'sd'
</details>

**Comment by ndonkoHenri** [comment]
Sorry for the inconvenience.
Issue has been raised in https://github.com/flet-dev/flet/issues/3566 and a fix has been implemented in #3551

**Comment by ndonkoHenri** [comment]
Issue has been fixed.
Give it a try by installing the latest Flet prerelease: `pip install flet --pre` (https://pypi.org/project/flet/#history)
Report if the issue persists.

**Comment by logololo** [comment]
hello , 

sorry , it s not working     (i tried  with 0.24.0.dev3170, 0.24.0.dev3171 and flet 0.24.0.dev3108)

the  terminal  shown nothing   (*o*) 






perhaps  here / see  in  :   self.scroll_delta: Optional[float] = d.get("sd")          :    [get fonction is not define ]   

![1](https://github.com/user-attachments/assets/7789ebf2-516b-4c8d-aede-e8543624fe77)

**Comment by ndonkoHenri** [comment]
What errors do you get?

**Comment by logololo** [comment]
nothing displayed on terminal , and  it  s not working  :

i call this fonction when scroll on Listview :

def on_listview_scroll(e:ft.OnScrollEvent):
          
      position = f"{e.pixels}"
      print(f"{e.pixels}")

please see  in :    self.scroll_delta: Optional[float] = d.get("sd")    => =>   (   "get " fonction is not define  in scrollable_controle.py)


perhaps you forget to import somthing or defiine correctly the call of the "get" fonction

**Comment by ndonkoHenri** [comment]
> "get " fonction is not define in scrollable_controle.py

Thats by the type checker, but don't mind it, it not an issue.
Can you share the code you run and the result you have? Does the scrollable control scroll as expected?

**Comment by ndonkoHenri** [comment]
I also suggest you give another try to the latest prerelease. Maybe what I recently pushed will fix your issue.

**Comment by logololo** [comment]
hi  ,  

it work  :)  thank you for your work ...

simple test for delta scroll  :

def on_listview_scroll(e:ft.OnScrollEvent):

  position = f"{e.pixels}"
  print(f"{e.pixels}")

![save screen](https://github.com/user-attachments/assets/48fc505b-0a5e-44d8-87ba-b3ecced74fd5)

**Comment by logololo** [comment]
ps : i will try to build an APK  for test and give you a feedback

**Comment by logololo** [comment]
hi , 

bad news , it s not working when you build apk for android   :(     

it s ok for linux (desktop)  i tested it , but not working  for androis , and i don't know what s wrong ....

**Comment by ndonkoHenri** [comment]
Saying it like this doesn't help anyone. 😅
Provide appropriate details on how to repro.

**Comment by logololo** [comment]
hi , this is le code :


import flet as ft


def main(page: ft.Page):
    page.title = "Auto-scrolling ListView"
    


    
    tx1 = ft.Text(value= " start position e.pixels = 0 " , color = "red" , size = 23 )
    page.add(tx1)
    def on_listview_scroll(e:ft.OnScrollEvent):
               
        position = f"{e.pixels}"
        print(position)
        tx1.value = f"Listview delta position {position}"
        tx1.update()
        
    lv = ft.ListView( spacing=10, padding=20, expand = True ,  on_scroll= on_listview_scroll) 

    count = 1

    for i in range(0, 60):
        lv.controls.append(ft.Text(f"Line {count}"))
        count += 1

    page.add(lv)


ft.app(target=main)

**Comment by logololo** [comment]
Hi ,  it's note done , when build apk , it not working on Android

**Comment by ndonkoHenri** [comment]
Which version of Flet do you have in your `requirements.txt` file?
Make sure it is one of the latest prerelease: https://pypi.org/project/flet/#history

**Comment by logololo** [comment]
it s the last dev version 0.24.0.dev3274

**Comment by felipelobo16** [comment]
on_scroll dosent work on android.

`import flet as ft

def main(page: ft.Page):
    page.title = "Scroll Increment Example"
    
    
    counter_value = 0
    counter = ft.Text(f"Counter: {counter_value}")
    
    def on_scroll(e):
        nonlocal counter_value
        counter_value += 1
        counter.value = f"Counter: {counter_value}"
        counter.update()
    
    
    items = [ft.Text(f"Item {i}") for i in range(50)]
    
    list_view = ft.ListView(
        controls=items,
        on_scroll=on_scroll,  
        height=400,           
        expand=True
    )
    
    page.add(counter, list_view)

ft.app(target=main)
`

**Comment by felipelobo16** [comment]
on_scroll dosent work on mobile apk:


import flet as ft

def main(page: ft.Page):
    page.title = "Scroll Increment Example"
    
    
    counter_value = 0
    counter = ft.Text(f"Counter: {counter_value}")
    
    def on_scroll(e):
        nonlocal counter_value
        counter_value += 1
        counter.value = f"Counter: {counter_value}"
        counter.update()
    
    
    items = [ft.Text(f"Item {i}") for i in range(50)]
    
    list_view = ft.ListView(
        controls=items,
        on_scroll=on_scroll,  
        height=400,           
        expand=True
    )
    
    page.add(counter, list_view)

ft.app(target=main)

**Comment by ndonkoHenri** [comment]
Might be a new android "weirdos": https://github.com/flet-dev/flet/issues/3867

You can report it there so it can be considered when fixing the others.
