### ISSUE TITLE
flet 0.19.0 cannot run in python3.7 with dirs_exist_ok param in shutil.copytree function

### ISSUE THREAD

**Issue by hanyce** [flet-dev/flet#3621]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

in pypi, flet need >= 3.7, when i using 3.7 to pack, its raise a error:
```python
    hook_config.temp_bin_dir = copy_flet_bin()
  File "python3.7\lib\site-packages\flet\__pyinstaller\utils.py", line 23, in copy_flet_bin
    copy_tree(bin_path, str(temp_bin_dir))
  File "python3.7\lib\site-packages\flet_runtime\utils.py", line 277, in copy_tree
    return shutil.copytree(src, dst, ignore=ignore, symlinks=True, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'

```

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

```python
from flet.__pyinstaller.utils import copy_flet_bin

_dir = copy_flet_bin()
```

### Expected behavior

run success

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

11

### Flet version

0.19.0

### Regression

I'm not sure / I don't know

### Suggestions

Adapts to `flet_runtime.utils.copy_tree` in python3.7

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Flet now requires python version >=3.8
https://github.com/flet-dev/flet/blob/main/sdk/python/pyproject.toml#L8-L9
