### ISSUE TITLE
Permission Handler Bug

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3624]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Permission Handled Only Request Permission For Microphone but when we request for any other permission like Storage, Manage Storage, Notifications it always show denied 

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

I want to get storage permission from Android

### Expected behavior

Permission handler should be work will all types of permission it is better if you create a system like seperate file where we put all permissions we need in our whole application / project

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![Screenshot_20240709-222134](https://github.com/flet-dev/flet/assets/135708579/abfa7f1b-e8f6-4d75-be45-60c1843eb8d9)

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.23.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/3561#issuecomment-2200118594
