### ISSUE TITLE
ModuleNotFoundError: No module named 'flet.map' when i build apk

### ISSUE THREAD

**Issue by asil004** [flet-dev/flet#3633]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/serious_python_tempPCCXXV/main.py", line 4, in <module>
  File "/tmp/serious_python_tempPCCXXV/pages/about.py", line 3, in <module>
  File "/tmp/serious_python_tempPCCXXV/components/background/login_background.py", line 2, in <module>
ModuleNotFoundError: No module named 'flet.map'

### Code sample

<details open><summary>Logs</summary>

```python
import flet.map as map

map.Map(
                        height=315,
                        expand=True,
                        configuration=map.MapConfiguration(
                            initial_center=map.MapLatitudeLongitude(41.2995, 69.2401),
                            initial_zoom=16,
                            interaction_configuration=map.MapInteractionConfiguration(
                                flags=map.MapInteractiveFlag.ALL
                            ),

                        ),
                        layers=[
                            map.TileLayer(
                                url_template="https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                                on_image_error=lambda e: print("TileLayer Error"),
                            ),

                        ],
                    ),
```

</details>

### To reproduce

flet build apk --include-packages flet_map

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

Ubuntu 22.04

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
I reproduced the issue with the test code from the docs: https://flet.dev/docs/controls/map#example

**Comment by asil004** [comment]
> I reproduced the issue with the test code from the docs: https://flet.dev/docs/controls/map#example

![Screenshot 2024-07-19 115046](https://github.com/user-attachments/assets/cefa5bdb-012b-4644-bdd1-4303f7f7d03e)

i have already the same issue

**buil command**
`flet build windows --include-packages flet_map`

**the map code**
```
class AboutBackground(Container):
    def __init__(self, image_src):
        super().__init__(
            expand=True,
            bgcolor=BACK_OPACITY_DARK,
            opacity=0.3,
            padding=0,
            alignment=Alignment(0, 0),

            content=Column(
                expand=True,
                spacing=0,
                controls=[
                    Image(src=image_src, height=720, fit=ImageFit.COVER, width=1920),


                    map.Map(
                        height=315,
                        expand=True,
                        configuration=map.MapConfiguration(
                            initial_center=map.MapLatitudeLongitude(41.2995, 69.2401),
                            initial_zoom=16,
                            interaction_configuration=map.MapInteractionConfiguration(
                                flags=map.MapInteractiveFlag.ALL
                            ),

                        ),
                        layers=[
                            map.TileLayer(
                                url_template="https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                                on_image_error=lambda e: print("TileLayer Error"),
                            ),

                        ],
                    ),
                ]
            )
        )
```

**Comment by Kacper-OS** [comment]
`Flashlight` has the same issue

**Comment by felipelobo16** [comment]
Try:

import flet_core.map as map

**Comment by asil004** [comment]
> Try:
> 
> import flet_core.map as map

![image](https://github.com/user-attachments/assets/74ae2233-211c-4824-98e6-7915f187d3ea)

already error!

**Comment by ndonkoHenri** [comment]
try the latest pre-release using `pip install flet -U --pre`
