### ISSUE TITLE
MatplotlibChart messing up the layout

### ISSUE THREAD

**Issue by fccoelho** [flet-dev/flet#3642]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I am inserting a MatplotibChart into a Card and I am getting the error below:

```python
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
[ERROR:flutter/flow/layers/transform_layer.cc(23)] TransformLayer is constructed with an invalid matrix.
```

### Code sample

<details open><summary>Logs</summary>

In the code below, `fig` is a matplotlib figure object created as described in flet docs.

```python
page.plot_panel.content = MatplotlibChart(fig, isolated=True , expand=True)
page.update()
```

`page.plot_panel` is a flet.Card() control.
</details>

### To reproduce

1. add the chart
2. update the page

### Expected behavior

I expected the chart to simply be rendered without screwing the layout

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>
When the chart is added, it completely messes up the view layout: All widgets get moved into the top left corner, as can be seen in the screenshot below.

![image](https://github.com/user-attachments/assets/e5a289c7-cb10-408e-a8da-38a1904503d4)

</details>

### Operating System

Linux

### Operating system details

Ubuntu 24.04

### Flet version

0.22.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Can you build some simple reproducible code, so we can test the issue?

**Comment by fccoelho** [comment]
I have instead switched to showing charts on a Bottom Sheet, thus avoiding figuring out the layout bug.
