### ISSUE TITLE
Switch height/width properties are not working

### ISSUE THREAD

**Issue by Sifat-Ahmed** [flet-dev/flet#3651]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I am trying to resize the switch control. But it seems like width/height property isn't working.
https://flet.dev/docs/controls/switch . Even if I try to adjust the size of the parent element, switch stays to its default size. 

![image](https://github.com/user-attachments/assets/c7d55742-157e-491d-9f88-f93f0519811d)

### Code sample

<details open><summary>Logs</summary>

```python
import flet as ft

def main(page):
    def button_clicked(e):
        t.value = (
            f"Switch values are:  {c1.value}, {c2.value}, {c3.value}, {c4.value}."
        )
        page.update()

    t = ft.Text()
    c1 = ft.Switch(label="Unchecked switch", value=False, height=5, width=5)
    c2 = ft.Switch(label="Checked switch", value=True)
    c3 = ft.Switch(label="Disabled switch", disabled=True)
    c4 = ft.Switch(
        label="Switch with rendered label_position='left'", label_position=ft.LabelPosition.LEFT
    )
    b = ft.ElevatedButton(text="Submit", on_click=button_clicked)
    page.add(c1, c2, c3, c4, b, t)

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

</details>

### To reproduce

Run the code attached

### Expected behavior

Expected to see a smaller switch

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 (OS build: 22631.3880)

### Flet version

Version: 0.23.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Solution: https://stackoverflow.com/a/52572288

**Comment by ndonkoHenri** [comment]
Issue has been fixed.
Give it a try by installing the latest Flet prerelease: `pip install flet --pre` (https://pypi.org/project/flet/#history)
Report if the issue persists.
