### ISSUE TITLE
InputFilter in context of TextField. Problem with regex_string

### ISSUE THREAD

**Issue by ClearSafety** [flet-dev/flet#3657]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I'm trying to use a TextField accepting only digits separated by a dot, like "000.00".
Using the regex_string=r'^\d+\.\d{2}$' it makes the field not accept anything.

### Code sample

<details open><summary>Logs</summary>

```python
import flet as ft

def main(page: ft.Page):    
    
    fild = ft.TextField(input_filter=ft.InputFilter(allow=True, regex_string=r'^\d+\.\d{2}$', replacement_string=""))
    page.add(fild)

ft.app(target=main)
```

</details>

### To reproduce

1 Run the code inserted above as it is.

### Expected behavior

It was supposed to have a TextField allowing strings with the pattern 321532165132.00

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 Pro

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

### Suggestions

No suggestion.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Try the following regex string instead: `^\d*(\.\d{0,2})?$`
