### ISSUE TITLE
CircleAvatar enhancement

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3669]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

when click the CircleAvatar, display the original big img to user.

### Screenshots

when click the CircleAvatar, display the original big img to user.

**Comment by ndonkoHenri** [comment]
The [`CircleAvatar`](https://api.flutter.dev/flutter/material/CircleAvatar-class.html) widget we use from flutter doesnt have such capabilities. I fear you will have to somehow implement it yourself.
