### ISSUE TITLE
Tooltip class

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#367]
**Please Describe The Problem To Be Solved**

Some Controls have a tooltip property with already defined styles : color(black), bgcolor(white), font size, location relative to the Control and many more.... 

Personally, I will be glad to be able to customize these myself. 

**Suggest A Solution**

I propose the creation of a new class(a new control maybe) named `Tooltip`, that has all these properties.

Here is a link to Flutter's tooltip widget -> [https://api.flutter.dev/flutter/material/Tooltip-class.html](https://api.flutter.dev/flutter/material/Tooltip-class.html)

**Comment by ndonkoHenri** [comment]
Hey! Please Any updates here?

**Comment by FeodorFitsner** [comment]
Adding to the next sprint.
