### ISSUE TITLE
Incorrect typing of `OptionalEventCallable`

### ISSUE THREAD

**Issue by Birnendampf** [flet-dev/flet#3673]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

`OptionalEventCallable` is typed as only expecting functions without a return value. This is problematic when trying to pass a coroutine as they technically have the return type `Coroutine[Any, Any, None]`

### Code sample

<details open><summary>Sample</summary>

[From the official documentation](https://flet.dev/docs/getting-started/async-apps#sleeping)
```python

import asyncio
import flet as ft

def main(page: ft.Page):
    async def button_click(e):
        await asyncio.sleep(1)
        page.add(ft.Text("Hello!"))

    page.add(
        ft.ElevatedButton("Say hello with delay!", on_click=button_click)
    )

ft.app(main)
```
</details>

### To reproduce

1. Open the code  above with any IDE or run a Type Checker
2. see warning/error along the lines of `Expected type '(ControlEvent) -> None | None', got '(e: Any) -> Coroutine[Any, Any, None]' instead`

### Operating System

Linux

### Operating system details

Linux Mint 21.3 Cinnamon

### Flet version

0.23.2

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Suggestions

in flet-core.types, define `OptionalEventCallable` as `Optional[Callable[[ControlEvent], Any]]`, since flet probably does not care about the return value, and therefore should not place any restrictions on it.

### Additional details

It technically worked in previous versions since event handlers used to not be typed

**Comment by ndonkoHenri** [comment]
Coincidence, we are looking into that here: https://github.com/flet-dev/flet/pull/3659 :)
