### ISSUE TITLE
Documentation (doc-strings) for IDEs

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#368]
I noticed when using Flet on my IdE(pycharm) that there are no doc strings in functions or classes to inform us on the uses of the particular class, examples...etc

These docs are instead in the browser([the controls section](https://flet.dev/docs/controls/))...but we all know it's kind of difficult to move from IDE to browser all the time(especially when we are coding offline😐).

Is it please possible to add these?

**Comment by AdamMusa** [comment]
Thank you so much for reporting this , yeah it's possible to add.

**Comment by ndonkoHenri** [comment]
Thanks. It will be very awesome to have this.

**Comment by ndonkoHenri** [comment]
Any updates ?

**Comment by FeodorFitsner** [comment]
Nope. Would you like to help with that? ;)

**Comment by ndonkoHenri** [comment]
I will make researches on the possibilities and add them here.

But, to get started, have a look at [Sphinx](https://www.sphinx-doc.org/en/master/tutorial/describing-code.html#documenting-python-objects). You surely have heard of it. It's awesome. Changes made in the code(on parameters, doc-strings..etc) get synced with those on the webpage(generates static HTML which could hosted anywhere) directly. No need to make changes twice.

You guys will have to add Doc-Strings to all your functions and classes(btw this is also a programming good practice), so they could be rendered(take effect) on the webpage.
[Deploying a Sphinx project online 🙂](https://www.sphinx-doc.org/en/master/tutorial/deploying.html)

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/pull/681
