### ISSUE TITLE
page.open and page.close are not working on Replit, even using the version 0.23.2

### ISSUE THREAD

**Issue by jvalle63** [flet-dev/flet#3681]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I received the following message while running my flet script on vscode:
" Page.overlay.append(dialog) instead.
  page.dialog = dlg_modal"

So I have changed all page.dialog commands from page.dialog = dlg_modal / dlg_modal.open = True / dlg_modal.close  = True ,
 to page.open() / page.close()
It has worked 100% on my environment. 

But, when I put this code on a Replit environment, the following message appeared, even using the exactly same version 0.23.2:

pg.page.open(dlg_modal)
AttributeError: 'Page' object has no attribute 'open'

### Code sample

Deprecated version:
        page.dialog = dlg_modal
        dlg_modal.open = True

New Version:
page.open(dlg_modal)

### To reproduce

Just create a Replit on replit.com and put a code and use an alertdialog or datepicker control...

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

Poetry

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
> AttributeError: 'Page' object has no attribute 'open'

If it says this then it doesnt have Flet v0.23.2
Check the Flet version it installed again from its packages tab.
You can also run `flet --version` from the terminal

**Comment by jvalle63** [comment]
I did this and Replit is using 0.23.2.
But they are using Python 10. This could be the cause...

Em dom., 21 de jul. de 2024, 08:21, TheEthicalBoy ***@***.***>
escreveu:

**Comment by ndonkoHenri** [comment]
I gave it try and it worked without difficulty:
![image](https://github.com/user-attachments/assets/a1ed22c3-c8c5-4445-a96d-243a02e50f23)

I simply created a new repl, pasted the code from the docs and ran it...
