### ISSUE TITLE
icon.png bug

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3686]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When I replaced the icon.png file in the assets directory, the icon of the Windows desktop program started by `flet run` did not change.

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

This bug is inevitable

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows10

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
That icon is used only when packaging. To change the icon used when developing your app see this issue: https://github.com/flet-dev/flet/issues/3438
