### ISSUE TITLE
Solution to Enable WASM in Flet

### ISSUE THREAD

**Issue by jaluscg** [flet-dev/flet#3692]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### File Changes

1. **File:** **`flet/packages/flet/lib/src/flet_server_protocol_javascript_web.dart`**

```dart
@JS()
library script.js;

import 'dart:js_interop';

import 'package:flutter/foundation.dart';
import 'flet_server_protocol.dart';

@JS('jsConnect')
external JSPromise<JSAny?> jsConnect(JSFunction onMessage);

@JS('jsSend')
external void jsSend(JSString data);

class FletJavaScriptServerProtocol implements FletServerProtocol {
  final String address;
  final FletServerProtocolOnMessageCallback onMessage;
  final FletServerProtocolOnDisconnectCallback onDisconnect;

  FletJavaScriptServerProtocol({
    required this.address,
    required this.onDisconnect,
    required this.onMessage,
  });

  @override
  connect() async {
    debugPrint("Connecting to JavaScript server $address...");
    await jsConnect(onMessage.toJS).toDart;
  }

  @override
  bool get isLocalConnection => true;

  @override
  int get defaultReconnectIntervalMs => 10;

  @override
  void send(String message) {
    jsSend(message.toJS);
  }

  @override
  void disconnect() {}
}
```

2. **Change File:** `flet/packages/flet/lib/src/utils/platform_utils_web.dart`

```dart
// ignore: avoid_web_libraries_in_flutter
//import 'dart:html' as html;
import 'package:web/web.dart' as html;
```

3. **Update `sensors_plus` version in:** "flet/packages/flet/pubspec.yaml`

```yaml
dependencies:
  sensors_plus: ^5.0.1
```

4. **Change File:** `flet/packages/flet/lib/src/utils/session_store_web.dart`

```dart
import 'package:web/web.dart' as html;
```

5. **Update `flet/pubspec.yaml` to include `web` dependency**

```yaml
dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.0
```

### Notes

- WASM is not available for video and audio packages since they depend on `ffi`, which is not supported.

**Comment by ndonkoHenri** [comment]
We have an opened issue concerning this already: https://github.com/flet-dev/flet/issues/3069

A branch has also been created named `wasm`. You can have a look at what has already been done, and possibly make suggestions or open a PR based on that branch to have it completed.
