### ISSUE TITLE
flet build apk --product "Test App" is broken in latest flet versions

### ISSUE THREAD

**Issue by syleishere** [flet-dev/flet#3700]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Adding spaces in product resolves to following error:

```
(  ●   ) Generating app icons ... Resolving dependencies in C:\Users\dan\AppData\Local\Temp\flet_flutter_build_gQmf3SkuV6...
(    ● ) Generating app icons ... Error on line 67, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
```

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

`flet build apk --product="Test App"`

### Expected behavior

`flet build apk --product="Test App"`

Should be Valid. Without it you cannot hit "App Info" on your phone and see name of app with spaces.

### Operating System

Windows

### Operating system details

ALL BUILDS/ALL OS's

### Flet version

0.23.2

### Regression

No, it isn't

### Suggestions

`flet build apk --product="Test_App"`
is a temporary fix using an underscore, but should work without it.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by syleishere** [comment]
Seems to be --product is being confused with --project. When I look at the app, it should be com.blah.$project, seems product is being put there

**Comment by syleishere** [comment]
pip install flet==0.24.0.dev3171
seems to have fixed the issue when I tested with latest devel releases, so if already fixed in main branch, feel free to close ticket...

**Comment by ndonkoHenri** [comment]
Yep issue has been fixed and is available in the latest prerelease. Sorry for that.
