### ISSUE TITLE
Get /storage/emulated/0/... access

### ISSUE THREAD

**Issue by halexandrino** [flet-dev/flet#3704]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hi guys. I have this button to open a folder, and get a list of all csv files
```
EW_button = ft.ElevatedButton(text="Agua de Extração",
                              on_click=lambda _: get_directory_dialog_EW.get_directory_path(),
                              bgcolor=ft.colors.BLUE, 
                              color=ft.colors.WHITE)
    
    def get_directory_result_EW(event: ft.FilePickerResultEvent):
        directory_path = event.path if event.path else 'CANCELADO'
        arquivos = glob.glob(f"{directory_path}/*.csv")
        print("The directory is: ", directory_path)
        for i in arquivos:
            a = os.path.split(i)[-1]
            print("This is the file: ", a)
```

when i execute it in desktop mode, the print is:
```
PS C:\Users\ricardo.oliveira\Documents\Curso_Python\flet\storagetest> flet run main.py
The directory is:  C:\Users\ricardo.oliveira\Downloads\sap2024\sap2024\sap2024-05-13\2024-23-04 modelo artificial lote 240319\sensor 138
This is the file:  amostra 01_01.csv
This is the file:  amostra 01_02.csv
```

But when run it on android device by flet run --android, the printed mensage is:
```
The directory is:  /storage/emulated/0/Documents
[ ]
```

But there are the same files in my phone.
So, my problem is... how do i get the csv (or pdf) files access? it look like pictures access is allowed, but some other files need some magic trick 

### Code sample

<details open><summary>Logs</summary>

```python
EW_button = ft.ElevatedButton(text="Agua de Extração",
                              on_click=lambda _: get_directory_dialog_EW.get_directory_path(),
                              bgcolor=ft.colors.BLUE, 
                              color=ft.colors.WHITE)
    
    def get_directory_result_EW(event: ft.FilePickerResultEvent):
        directory_path = event.path if event.path else 'CANCELADO'
        arquivos = glob.glob(f"{directory_path}/*.csv")
        print("The directory is: ", directory_path)
        for i in arquivos:
            a = os.path.split(i)[-1]
            print("This is the file: ", a)
```

</details>

### To reproduce

`import flet as ft
import os
import glob

def main(page: ft.Page):

    page.title = "Salt Analysis"
    page.bgcolor = ft.colors.BLACK
    page.adaptive = True
    page.window.resizable = True

    EW_button = ft.ElevatedButton(text="Agua de Extração",
                              on_click=lambda _: get_directory_dialog_EW.get_directory_path(),
                              bgcolor=ft.colors.BLUE, 
                              color=ft.colors.WHITE)
    
    def get_directory_result_EW(event: ft.FilePickerResultEvent):
        directory_path = event.path if event.path else 'CANCELADO'
        arquivos = glob.glob(f"{directory_path}/*.csv")
        print(directory_path)
        #print(arquivos)
        for i in arquivos:
            a = os.path.split(i)[-1]
            print("This is the file: ", a)

    
    get_directory_dialog_EW = ft.FilePicker(on_result=get_directory_result_EW)

    page.overlay.extend([get_directory_dialog_EW])

    page.add(
        ft.Row(
               [EW_button],
               alignment=ft.MainAxisAlignment.CENTER)
    )
    page.update()

ft.app(target=main)`

### Expected behavior

```
The directory is:  C:\Users\ricardo.oliveira\Downloads\sap2024\sap2024\sap2024-05-13\2024-23-04 modelo artificial lote 240319\sensor 138
This is the file:  amostra 01_01.csv
This is the file:  amostra 01_02.csv
```

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

android 11

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
The directory is:  C:\Users\ricardo.oliveira\Downloads\sap2024\sap2024\sap2024-05-13\2024-23-04 modelo artificial lote 240319\sensor 138
This is the file:  amostra 01_01.csv
This is the file:  amostra 01_02.csv
```
when on android device
```
The directory is:  /storage/emulated/0/Documents
[ ]
```

</details>

**Comment by ndonkoHenri** [comment]
As mentioned in the discussion you previously opened, here is the issue concerned with storage: https://github.com/flet-dev/flet/issues/2357
