### ISSUE TITLE
Dissmissble don't work android

### ISSUE THREAD

**Issue by yucel685** [flet-dev/flet#3720]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

 i made the arrangements in flet core. the vs code is working dismissble. but when I created the apk, it doesn't work on the phone

### Code sample

import flet as ft

def main(page):
    def handle_dlg_action_clicked(e):
        page.close(dlg)
        dlg.data.confirm_dismiss(e.control.data)

    dlg = ft.AlertDialog(
        modal=True,
        title=ft.Text("Please confirm"),
        content=ft.Text("Do you really want to delete this item?"),
        actions=[
            ft.TextButton("Yes", data=True, on_click=handle_dlg_action_clicked),
            ft.TextButton("No", data=False, on_click=handle_dlg_action_clicked),
        ],
        actions_alignment=ft.MainAxisAlignment.CENTER,
    )

    def handle_confirm_dismiss(e: ft.DismissibleDismissEvent):
        if e.direction == ft.DismissDirection.END_TO_START:  # right-to-left slide
            # save current dismissible to dialog's data, for confirmation in handle_dlg_action_clicked
            dlg.data = e.control
            page.open(dlg)
        else:  # left-to-right slide
            e.control.confirm_dismiss(True)

    def handle_dismiss(e):
        e.control.parent.controls.remove(e.control)
        page.update()

    def handle_update(e: ft.DismissibleUpdateEvent):
        print(
            f"Update - direction: {e.direction}, progress: {e.progress}, reached: {e.reached}, previous_reached: {e.previous_reached}"
        )

    page.add(
        ft.ListView(
            expand=True,
            controls=[
                ft.Dismissible(
                    content=ft.ListTile(title=ft.Text(f"Item {i}")),
                    dismiss_direction=ft.DismissDirection.HORIZONTAL,
                    background=ft.Container(bgcolor=ft.colors.GREEN),
                    secondary_background=ft.Container(bgcolor=ft.colors.RED),
                    on_dismiss=handle_dismiss,
                    on_update=handle_update,
                    on_confirm_dismiss=handle_confirm_dismiss,
                    dismiss_thresholds={
                        ft.DismissDirection.END_TO_START: 0.2,
                        ft.DismissDirection.START_TO_END: 0.2,
                    },
                )
                for i in range(10)
            ],
        )
    )

ft.app(main)

### To reproduce

Nothing

### Operating System

Windows

### Operating system details

Intel core i5

### Flet version

0.23.2

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

it does not give an error in the installation. dissmissble just doesn't work on the phone

**Comment by ndonkoHenri** [comment]
> i made the arrangements in flet core.

What do you mean by this?

Your Flet version might be the issue. The fix for dismissible is available only in the latest prerelease.
Do `pip install flet -U --pre` and retry.

**Comment by yucel685** [comment]
yes, the problem was in the version. i have upgraded the version. it is working now. thank you for your help
