### ISSUE TITLE
"Black Screen" in MacOS Sonoma v.14.5 (Intel Processor) & Flet v0.23.2

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#3727]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I've updated to Flet v.023.2 and I removed the folder ("rm -rf ~/.cookiecutters") as @FeodorFitsner said in other post.

But I can't execute anything, all appears in "Black Screen" 

### Code sample

<details open><summary>Logs</summary>

```python
    import flet as ft


    def main(page):
        page.horizontal_alignment = ft.CrossAxisAlignment.CENTER

        def close_anchor(e):
            text = f"Color {e.control.data}"
            anchor.value = text
            anchor.update()
            # print(f"closing view from {text}")
            # anchor.close_view(text)

        anchor = ft.SearchBar(
            view_elevation=4,
            divider_color=ft.colors.AMBER,
            bar_hint_text="Search colors...",
            view_hint_text="Choose a color from the suggestions...",
            controls=[
                ft.ListTile(title=ft.Text(f"Color {i}"), on_click=close_anchor, data=i)
                for i in range(10)
            ],
        )

        page.add(
            ft.Row(
                alignment=ft.MainAxisAlignment.CENTER,
                controls=[
                    ft.OutlinedButton(
                        "Open Search View",
                        on_click=lambda _: anchor.open_view(),
                    ),
                ],
            ),
            anchor,
        )

    ft.app(target=main)
```

</details>

### To reproduce

Anything

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

14.5 (Intel Processor)

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
When running the packages macOS app? Or when running in normal mode.

Can you equally give a try to the latest prerelease: `pip install flet -U --pre`

**Comment by nastiliano** [comment]
Hello,

Ok! It works!

But with some "peculiarities".

For example, I have problems to show "Views". (my code works completly fine in Windows and Linux).

If we put "True" to our global variable "page.adaptive" , the GUI looks ugly (not similar to other O.S) and "Snackbar" doesn't work... If we put "False" looks like Windows or Linux and "Snsckbar" works again.

I'm going to check all this stuff and post another issue anyway.

Thank you very much.
Best regards.

**Comment by nastiliano** [comment]
Hello,

I realized that "the showing Views" issue" starts in 0.24 version in all platforms.

I opened an official issue.

Thanks!!
