### ISSUE TITLE
Alignment on DropDown not working

### ISSUE THREAD

**Issue by julianobramos** [flet-dev/flet#3734]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I'm trying to center text in dropdown component and it's not working.

### Code sample

import flet as ft

def main(page: ft.Page):
    dd = ft.Dropdown(
        label = 'Select an option',
        options = [
            ft.dropdown.Option(key=1, text='Option 1'),
            ft.dropdown.Option(key=2, text='Option 2'),
            ft.dropdown.Option(key=3, text='Option 3'),
            ft.dropdown.Option(key=4, text='Option 4'),
            ft.dropdown.Option(key=5, text='Option 5', disabled=True)
        ],

        alignment=ft.alignment.center,

    )

    page.add(dd)

### To reproduce

Run the code

### Expected behavior

Text "Choose your option"  on the center of the object.

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Sonoma 14.5

### Flet version

Version: 0.24.0.dev3196

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

It was working on 0.22 version

**Comment by ndonkoHenri** [comment]
Culprit: 
https://github.com/flet-dev/flet/blob/90436bbb89e8d712d4f3fb72e61d68c3ec8c4eb3/packages/flet/lib/src/controls/dropdown.dart#L175
