### ISSUE TITLE
`Page.window_resizable` doesn't work properly

### ISSUE THREAD

**Issue by KotonBads** [flet-dev/flet#375]
**Description**

Window expands to `1280x720` when I switch workspaces, window focus, or if I try to resize it when `Page.window_resizable` is set to `False`

**Code example to reproduce the issue:**

```python
import flet
from flet import Page, Text

def main(page: Page):
    page.window_height = 512
    page.window_width = 512
    page.window_resizable = False
    page.theme_mode = "dark"

    page.add(Text("Just a placeholder"))
    page.update()

flet.app(target=main)
```

**Describe the results you received:**

https://user-images.githubusercontent.com/66117568/191776490-f3e8bb92-78ea-478a-9dd1-52aaf10273a6.mp4

**Describe the results you expected:**

Window stays the size I set it to

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.1.59
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: 
Author-email: Appveyor Systems Inc. <hello@flet.dev>
License: MIT
Location: /home/koton-bads/.local/lib/python3.10/site-packages
Requires: beartype, repath, watchdog, websocket-client
Required-by: 
```

**Operating system**:

Fedora 36 Xfce

**Additional environment details:**
Kernel 5.19.9-200.fc36.x86_64
Xfce 4.16

**Comment by FeodorFitsner** [comment]
Watched the video? So, the issue is that a new window size is not restored after app restart?

**Comment by KotonBads** [comment]
The issue is that when I try to resize a supposedly unresizeable window, it jumps to 1280x720. 

It does restore the intended size on app restart though

**Comment by ndonkoHenri** [comment]
Can you try to resize from the window's edges ?

**Comment by ndonkoHenri** [comment]
If you want to prevent it from being maximized, add:
```python
page.window_maximizable = False
```
https://flet.dev/docs/controls/page#window_maximizable
