### ISSUE TITLE
Missing on_change and on_submit event on autocomplete

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3759]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Kindly add on_change and on_submit event on autocomplete

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

Need on_change and on_submit event on autocomplete

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Android

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Mention it in https://github.com/flet-dev/flet/issues/3524
Will see if it possible when on it.
