### ISSUE TITLE
Bug In Flet Video

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3760]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

i am facing an issue that video is not loading and not giving any error when i added video url 

### Code sample

<details open><summary>Logs</summary>

```python
import flet as ft
import yt_dlp

def main(page: ft.Page):
    
    def error():
        print("Error")
    
    video = ft.VideoMedia("https://app.miflexwave.com/wp-content/uploads/2024/08/y2mate.com-Action-Replayy-Hindi-Full-Movie-Akshay-Kumar-Aishwarya-Rai-Latest-Bollywood-Comedy-Movie_720pFH.mp4")

    box = ft.Video(
        expand=True,
        playlist=video,
        volume=100,
        autoplay=True,
        on_error= lambda _: error(),
        filter_quality=ft.FilterQuality.LOW,
        
    )

    page.add(box)

ft.app(main)
```

</details>

### To reproduce

i want to play video via URL

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
It loads on my end:
![image](https://github.com/user-attachments/assets/70ff286b-44f2-4000-8b8a-80a011ea5eca)

Issue might be your internet connection, I think. The video is very long, and probably it has to be fully downloaded/cached before being played.

**Comment by baseplate-admin** [comment]
> The video is very long, and probably it has to be fully downloaded/cached before being played.

This sounds like anti-pattern no?

Cant you load video by chunk? (same way youtube does)

**Comment by Muddassirofficial** [comment]
> > The video is very long, and probably it has to be fully downloaded/cached before being played.
> 
> This sounds like anti-pattern no?
> 
> Cant you load video by chunk? (same way youtube does)

Yes I also want this

**Comment by ndonkoHenri** [comment]
> Cant you load video by chunk? (same way youtube does)

What I said is just a speculation. I don't know why it doesnt load on his end. 
This is the package we use for video display if anyone wants to make research: https://pub.dev/packages/media_kit

@baseplate-admin feel free to try the code on your end and provide feedback if it works or not.
@Muddassirofficial can you try you code on the web platform?

**Comment by Muddassirofficial** [comment]
> > Cant you load video by chunk? (same way youtube does)
> 
> What I said is just a speculation. I don't know why it doesnt load on his end. 
> This is the package we use for video display if anyone wants to make research: https://pub.dev/packages/media_kit
> 
> @baseplate-admin feel free to try the code on your end and provide feedback if it works or not.
> @Muddassirofficial can you try you code on the web platform?

Thanks @ndonkoHenri I tried and it's working but little bit improvement needed in this functionality video should load in chunk it will improve speed and performance

**Comment by ndonkoHenri** [comment]
Sorry but I dont see how we can control that. On my end it loaded instantly.
If you find anything that can help us improve this control, simply provide a link, and we will have a look.

For now, let's close this issue.
