### ISSUE TITLE
Dropdown lists reset displayed value in web app on page reload

### ISSUE THREAD

**Issue by mghiggins** [flet-dev/flet#3761]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I've build a web app using flet that includes ft.Dropdown controls. I noticed that the app's web page force-reloads every so often (how do I stop that, btw?), and when it does, the values displayed in the dropdown lists reset to the first value in the list. How do I stop this from happening? 

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

Build a web app with a single dropdown, build it for the web, change the value in the dropdown, and reload the web page.

### Expected behavior

The selected value should be persisted across page reloads

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

MacOS 15.0

### Flet version

0.23

### Regression

No, it isn't

### Suggestions

I asked Google Gemini and it suggested inheriting a class from ft.UserControl, storing the dropdown value in page.session, and forcibly setting it on build(). That didn't work :( and also seems kind of clunky.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Please fill out the bug template with more info(code, captures etc)
