### ISSUE TITLE
Video Widget Not Working In Android

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3762]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I want to describe this serious issue that if we play any video via URL with ft.Video() it's working fine on desktop windows and web but when we convert application into apk then video is not rendering on Android and audio is playing fine but video is showing totally blur kindly solve this matter as soon as possible

### Code sample

<details open><summary>Logs</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

I want that video should be work fine in Android devices

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20240804-165454](https://github.com/user-attachments/assets/cfc781a8-7ea2-45f8-87d3-61bebcf7b429)

</details>

### Operating System

Windows

### Operating system details

Android

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by syleishere** [comment]
I think you'd need to post your code, works for me. Like how are you wrapping the video, a container? What are your ft.Video settings for android etc.

**Comment by syleishere** [comment]
Try these settings, what I use on android:

```
            self.video = ft.Video( 
                expand=True,
                playlist=sample_media,
                playlist_mode=ft.PlaylistMode.LOOP,
                fill_color=ft.colors.BLACK,
                aspect_ratio=16 / 9,
                fit=ft.ImageFit.FIT_WIDTH,
                volume=self.video_volume,
                title="testing",
                pause_upon_entering_background_mode=False,
                autoplay=False,
                filter_quality=ft.FilterQuality.MEDIUM,  # Android Phone can't take high quality or all garbled
                muted=False,
                on_loaded=lambda e: print("Video loaded successfully!"),
                visible=True,
                wakelock=True,
            )
```

**Comment by Muddassirofficial** [comment]
Thanks it working Great but kindly confirm me when will android support high Quality
