### ISSUE TITLE
Image does not load from Android or iOS to the application

### ISSUE THREAD

**Issue by Lucasapn2** [flet-dev/flet#3763]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Gentlemen, I would like to ask for help in selecting a file using the file selector. but selecting in a mobile application, I am building an application, but when I try to load the selected image from a mobile file it does not allow it. Is there any specific path or change I can make to solve this problem?
![a](https://github.com/user-attachments/assets/226f1643-52d5-4195-b60f-54c62f7df352)

### Code sample

def show_upload_photo_dialog(category_id):
    def upload_photo(e):
        try:
            # Check if the description is empty
            if not description_input.value.strip():
                error_message = ft.Text("A descrição não pode estar vazia!", color=ft.colors.RED)
                upload_dialog.content.controls.append(error_message)
                page.update()
                return

            # Check if a file has been selected
            if not selected_file_label.value.startswith("Arquivo Selecionado:"):
                error_message = ft.Text("Nenhum arquivo selecionado!", color=ft.colors.RED)
                upload_dialog.content.controls.append(error_message)
                page.update()
                return

            # Extract the file path
            file_path = selected_file_label.value.split(": ")[1]

            # Check if the file path is valid
            if not os.path.isfile(file_path):
                error_message = ft.Text("O arquivo selecionado não é válido ou não existe!", color=ft.colors.RED)
                upload_dialog.content.controls.append(error_message)
                page.update()
                return

            # Upload photo to the API
            with open(file_path, 'rb') as file:
                files = {'photo': file}
                data = {'description': description_input.value}
                response = requests.post(f'{API_URL}/categories/{category_id}/photos', files=files, data=data)
                response.raise_for_status()

            page.close(upload_dialog)  # Close the dialog after upload
            page.update()
        except requests.exceptions.RequestException as e:
            error_message = ft.Text(f"Erro ao fazer upload da foto: {e}", color=ft.colors.RED)
            upload_dialog.content.controls.append(error_message)
            print(f"Request Exception: {e}")
            page.update()
        except Exception as e:
            error_message = ft.Text(f"Erro ao processar a foto: {e}", color=ft.colors.RED)
            upload_dialog.content.controls.append(error_message)
            print(f"Exception: {e}")
            page.update()

    def open_file_picker(e):
        file_picker.pick_files(
            allow_multiple=False,
            allowed_extensions=['jpg', 'jpeg', 'png']
        )

    def on_file_selected(e: ft.FilePickerResultEvent):
        if e.files and e.files[0].path:
            file_path = e.files[0].path
            if file_path:  # Check if the file path is valid
                selected_file_label.value = f"Arquivo Selecionado: {file_path}"
            else:
                selected_file_label.value = "O arquivo selecionado não é válido."
        else:
            selected_file_label.value = "Nenhum arquivo selecionado."
        page.update()

    file_picker = ft.FilePicker(on_result=on_file_selected)
    page.overlay.append(file_picker)

    description_input = ft.TextField(label="Descrição", multiline=True)
    selected_file_label = ft.Text("Nenhum arquivo selecionado.")
    select_file_button = ft.ElevatedButton("Selecionar Arquivo", on_click=open_file_picker)
    upload_button = ft.ElevatedButton("Carregar", on_click=upload_photo)

    upload_dialog = ft.AlertDialog(
        title=ft.Text("Carregar Foto"),
        content=ft.Column(
            controls=[
                description_input,
                selected_file_label,
                select_file_button,
            ],
            tight=True,
            alignment=ft.MainAxisAlignment.CENTER,
            horizontal_alignment=ft.CrossAxisAlignment.CENTER,
            spacing=20
        ),
        actions=[
            upload_button,
            ft.TextButton("Cancelar", on_click=lambda e: page.close(upload_dialog))
        ],
        actions_alignment=ft.MainAxisAlignment.END,
        on_dismiss=lambda e: print("Diálogo de upload de foto fechado")
    )
    page.overlay.append(upload_dialog)
    page.update()
    page.open(upload_dialog)

### To reproduce

![a](https://github.com/user-attachments/assets/6766f564-73a6-407a-9bea-9d347f293827)

### Screenshots / Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

![a](https://github.com/user-attachments/assets/cabbb9a2-7cd2-4c56-95b7-e22429d67626)

**Comment by ndonkoHenri** [comment]
How do you run the app, please?

**Comment by Lucasapn2** [comment]
hello, like this ft.app(target=main )

**Comment by m77224844m** [comment]
ft.app(target=main )

**Comment by Lucasapn2** [comment]
use of the official flet app  
![Screenshot_2](https://github.com/user-attachments/assets/336db5f1-c62a-4423-8cc0-c89cc37d3a51)

**Comment by ndonkoHenri** [comment]
The needs to be updated. This will be done after the next Flet release.

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/3096#issuecomment-2334248541
