### ISSUE TITLE
Packaging with "Tauri"

### ISSUE THREAD

**Issue by ItsCubeTime** [flet-dev/flet#377]
For the purpose of letting a Flet app have its own desktop window & move out of the browser window (Tauri is a more lightweight Electron alternative - with package sizes as small as 1 mb or less. https://tauri.app/ and with support for all desktop platforms + soon to come mobile).

**Comment by FeodorFitsner** [comment]
How is Tauri supposed to work/integrate/package with Flet? Could you please elaborate on your idea?

**Comment by ItsCubeTime** [comment]
Hi @FeodorFitsner , stumbled upon this now again. Last when I posted here I actually hadn't noticed that it was already possible to package Flet with its own UI window, so when I was digging in this to try and give a more elaborate response I realized this was perhaps a bit over ambiguous.

But looking at this again now a couple of weeks later Im thinking this could perhaps still be interesting to allow for better app customizability, like allowing apps built with Flet to change app name, logo, copyright information (etc).

So to elaborate on the original idea, it was that something like Tauri could act as a "webbrowser" to display the UI rendered by Flet, so that when you ship an app created with Flet, instead of just shipping a single executable packaged with something like py2exe, you ship 2 programs, one being the Flet Flutter program embedded as a Python module that does the server side rendering and the other acting sort of like a specialized "webbrowser" created with (something like) Tauri - of which sole purpose is to displays/renders the actual UI and perhaps do some basic communication with the Flet Flutter program (like tell it to start when the user tries to start the "webbrowser" part of the app). 

This way, a developer creating an app using Flet would be able to rename/change icons of there apps (and change any other data that the OS may want) just by modifying the "webbrowser" part of the app, without having to recompile the Flet Flutter project itself (and offer a bit of convenience to the developer that way, assuming that Flet itself is a little heavier to compile) - which Im imagining would be done with some cmd line app that ships with Flet (that could for instance be invoked with something like: `flet-build myAwesomeAppName "c:/build/dest/dir" -icon="c:/path/to/icons" -author="Cool List of Names" -copyright="Company Name"` ).

Then at the end, the end user of a Flet created app would only be interacting directly with the specialized "webbrowser" and the flet flutter app would only be telling the "webbrowser" what to display exactly.



However I should mention, a downside with Tauri in particular is that intermediate files can goup to around 2.5 gb for an empty project atm (doing some quick hello world apps for testing with it), likewise clean builds takes a bit of time. So perhaps there are better tools for this kind of thing available. But like I said, the produced builds of Tauri are incredibly small (under a handful of mb for smaller projects built on Windows (not sure how file sizes are on other operative systems) ), so if this would allow for skinning off some parts of the Flutter project, perhaps this could even allow for reduction in file size of programs built with Flet?

**Comment by ndonkoHenri** [comment]
What is required to try this ?
Maybe you could try packaging it with this Tauri, and later sharing your experience here..

**Comment by ItsCubeTime** [comment]
> What is required to try this ? Maybe you could try packaging it with this Tauri, and later sharing your experience here.

Hi @ndonkoHenri & thanks for showing interest :)

Im not much of a Tauri expert, Ive only pulled down some demo project and played around with it for an hour or so.


But like  Ive mentioned, Tauri offers a [fully fledged html/js/css runtime environment](https://tauri.app/v1/guides/getting-started/setup/html-css-js/) (with the help of things like Microsoft webview & whatever the equalities are on other operative systems, it acts sort of like electron but with a smaller package size), so I believe you could just reuse all the code currently used to get Flet to open up a browser window > but instead of opening up the actual web browser, get Tauri to display the port chosen by Flet (for this you would have to somehow communicate from Flet to Tauris backend what port it needs to connect to (I would probably just write text to a file relative to the executable file paths for this, heh), then the Tauri backend can feed that info to the frontend (which could be some simple iframe html like `<iframe id="iframeDisplayingFletApp">` or `<iframe src="localFileToDisplay.html>` or use Tauris own "command" system ) ).


To give an example:
* The user starts the Tauri app
* In Tauris main() function it will look for an executable named "Flet.exe" (which would be your python program with the Flet module compiled to an exe) & then execute it
* The python program compiled to an exe (that includes flet) runs like normal, calling the `flet.app()` function, which starts the html renderer and makes itself available on a port just like when preparing to be displayed through a webbrowser. Instead of telling the OS to open up a webbrowser window however it somehow tells the Tauri app to display the local port it just opened up (for instance it could write a html document relative to the executables again where the Tauri app has some form of listener that looks for updates in this file and displays it on screen when possible).

Then you would also need flets functions for minimizing & expanding windows, displaying toasters (toasters in particular because you probably want the correct app name & logo to be displayed when sending out a toaster) and such to be forwarded to the Tauri app - and then be handled by Tauri instead of Flutter.

Another drawback of this is that the html renderer doesnt seem quite as responsible as Flutters canvas renderer when resizing windows (bothers me a bit, although Im not so sure whether this should be considered a deal breaker, this would happen with any web based tech however) 

Quick experiment using iframe (by connecting to an already launched Flet port): https://www.youtube.com/watch?v=7sA4F83RBg4

**Comment by ItsCubeTime** [comment]
I should say btw that this is only an idea for solution, maybe its better and more convenient to instead let users compile Flutter and modify things like app name/logo/copyright info that way - and instead focus on making this process as easy as possible so that anyone using Flet can do it conveniently

**Comment by FeodorFitsner** [comment]
Alright, thank you guys for your thoughts.

I've spent some time on weekend trying to find a solution for updating executable icon and metadata and found some good options. I was looking for Windows executables. When we're done with Windows we'll see how it could be done for macOS.

Using Tauri just for icon is a bit of overhead to my mind. Tauri is for web, so you have to enforce Flet app to run as a web app. Plus, Tauri relies on WebView available on user system.

I'm going to share my findings later this week.
