### ISSUE TITLE
Too large size of apk compare to other type of app

### ISSUE THREAD

**Issue by imadityacoder** [flet-dev/flet#3777]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Recently, I make a simple calculator in flet and I convert it into apk. The file size of it is 47 MB but the file size of buildin calculator of mobile is only 2 MB. 
Also it is working slow compare to buildin calculator.

Therefore , want to say that please decease it's size for speed, performance, easy to share and simplicity.

Thanks!

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/publish/android#building-platform-specific-apk

**Comment by imadityacoder** [comment]
> https://flet.dev/docs/publish/android#building-platform-specific-apk

Thanks!
