### ISSUE TITLE
Column can not scroll

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3781]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Column can not scroll

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    lv = ft.ListView(spacing=10)

    for i in range(1, 100):
        lv.controls.extend([
            ft.Text('aaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbb'),
            ft.Text('  aaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbb'),
            ft.Text('    aaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbb'),
            ft.Text('      aaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbb')
        ])

    page.add(
        ft.SafeArea(
            ft.ResponsiveRow(controls=[
                ft.Column(
                    col=2,
                    scroll=ft.ScrollMode.AUTO,
                    controls=[ft.Container(padding=ft.padding.only(right=20), content=lv)],
                ),
                ft.Column(
                    col=8,
                    scroll=ft.ScrollMode.AUTO,
                    controls=[ft.Container(content=lv)],
                ),
                ft.Column(
                    col=2,
                    scroll=ft.ScrollMode.AUTO,
                    controls=[ft.Container(padding=ft.padding.only(left=20), content=lv)],
                ),
            ], )))


ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

</details>

### To reproduce

look my code

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

wsl2 ubuntu 22.04

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by zox47** [comment]
Make expand=True for column

**Comment by BrentHuang** [comment]
@zox47 no effect.

**Comment by BrentHuang** [comment]
How do I set the Column to be as tall as its parent control(not the page's height, but the Column's parent's height), so that a scroll bar automatically appears when the content exceeds its height

**Comment by covixx** [comment]
Set expand = True for SafeArea, which is the outermost container for the flet page.

**Comment by BrentHuang** [comment]
@covixx thanks!
