### ISSUE TITLE
The Page container needs a property similar to on_keyboard_event for mouse movement 

### ISSUE THREAD

**Issue by covixx** [flet-dev/flet#3795]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I'm trying to program a screensaver with Flet, which should close on keyboard or mouse interaction. I can use keyboardevent to close the app just fine, but for mouse tracking I'm currently wrapping the entire page inside a GestureDetector to track mouse activity, which feels like a janky workaround. Are there any plans to introduce a process similar to on_keyboard_event for mouse tracking to page instances?

**Comment by ndonkoHenri** [comment]
Why do you think it is a "janky workaround".
Even if we have to make this possible, all we will do (from current research) will be to - internally - wrap the Flet application in a `GestureDetector` and "spam"/expose new properties in the `Page`.
I suggest we leave as-is, and you use the gesture detector. If you face an issue while using it, then let us know. :)
