### ISSUE TITLE
Google AdSense Support For Web

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3798]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Currently there is no support for AdSense to display ads on website or it is not even on road map. 

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

I want to display ads on website made with flet 

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
And why open a bug?
Subscribe here: https://github.com/flet-dev/flet/issues/286
I don't think Flutter makes it possible for google ads on web. Feel free to search and share a link in the issue mentioned above.
