### ISSUE TITLE
 No such file or directory: '/var/folders/z3/qx5fwddj6l71mkcr02kgsjsw0000gn/T/fletd-0.1.59/fletd'

### ISSUE THREAD

**Issue by DomineCore** [flet-dev/flet#380]
On my macos, startup appeared such a mistake.

**Comment by DomineCore** [comment]
MacBook Pro (13-inch, M1, 2020)

**Comment by hololeo** [comment]
this happens from time to time. you need to delete that directory

**Comment by DomineCore** [comment]
Sorry, I don't really understand

**Comment by FeodorFitsner** [comment]
Delete that folder `rm -rf /var/folders/z3/qx5fwddj6l71mkcr02kgsjsw0000gn/T/fletd-0.1.59` and start your Flet program again.
