### ISSUE TITLE
Need Feature For Displaying HTML CSS Directly In Flet 

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3800]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

We need a feature in flet web like ft. HTML() where we can directly put html code in web application and use services like Google AdSense, I-Frames etc... 

### Suggest a solution

Create a widget like ft.HTML() to display HTML and CSS directly

**Comment by ndonkoHenri** [comment]
Related to [`Webview`](https://github.com/flet-dev/flet/issues/432) issue.
