### ISSUE TITLE
NavigationBar error 

### ISSUE THREAD

**Issue by tinyabdu** [flet-dev/flet#3816]
![Screenshot_20240816-073123.png](https://github.com/user-attachments/assets/106c086a-8731-4a21-9833-0032540bb179)

Whenever I clik textfield keyboard is following navigation bar idk why I try but still no result

**Comment by ndonkoHenri** [comment]
Please next time, when opening an issue, avoid using the blank template and favour the "bug" template. Now I have to ask questions, which you would've normally provided through the template. 😅

How do you run the application on android, and which android device are you using?
