### ISSUE TITLE
page.query does not work properly.

### ISSUE THREAD

**Issue by 18909175158** [flet-dev/flet#3822]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

page.query does not work properly. No matter what page.route is, page.query.to_dict is an empty dictionary {},and does not get the  content What follows "?" in url.

some of tested urls:
192.168.1.32:8501/page1?name=jack&age=20
192.168.1.32:8501/page1/?name=jack&age=20
192.168.1.32:8501?name=jack&age=20

Flet v0.23.1

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    print(page.route)
    print(page.query.to_dict)
    page.add(ft.Text('ok'))

app=ft.app(main, export_asgi_app=True)

# url = 192.168.1.32:8501/page1?name=jack&age=20
"""
uvicorn main:app -host 0.0.0.0 -port 8501 --reload
>> /page1?name=jack&age=20
     {}
"""
```

</details>

### To reproduce

no bug report

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows10

### Flet version

v0.23.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by OwenMcDonnell** [comment]
Is this reproducible on latest Flet release?
