### ISSUE TITLE
funny flet building bug it shouldn't happen (apk build compiling error)

### ISSUE THREAD

**Issue by HamaBTW** [flet-dev/flet#3835]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hi so I've been using flet since 2020 and i this bug happened to me 3 times its actually funny and kinda stupid
okay so lets say u wanna export ur flet app to android (apk) ur gonna use flet build apk -vv for more details
and sometimes even if ur code is all good and all the libs and packages are pure-python u got an error on compiling

so we all familiar with the string formating (f"")

so i can say :
a = "alen"
b = f"hi {a}"
all good
but if u type :
b = f"{a}"
it will give u a compiling error 

NOTE : btw it only happens when the var a is a string

===========================================================================

please give it a try and fix it

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    a = "alen"
    # The following line causes a compiling error when building an APK
    b = f"{a}"
    page.add(ft.Text(b))

ft.app(target=main)
```

</details>

### To reproduce

1- Create a new Flet app with the following minimal code:

```python
import flet as ft

def main(page: ft.Page):
    a = "alen"
    # This line causes a compiling error when building an APK
    b = f"{a}"
    page.add(ft.Text(b))

ft.app(target=main)
```

2- Save the code as main.py.

3- Run the command flet build apk -vv to compile the app into an APK.

Observe that the compilation fails, even though the code is valid Python and should normally run without issues.

### Expected behavior

The app should compile successfully into an APK without errors.

### Operating System

Windows

### Operating system details

window 10 64bit last update

### Flet version

Version: 0.22.1

### Regression

No, it isn't

### Suggestions

i dont know but by removing the f"{}" it work

**Comment by ndonkoHenri** [comment]
Which version of python are you using?

**Comment by HamaBTW** [comment]
hi!!

I'm using Python 3.12.5

and it happened to me a year ago and when i found it after a day of debugging i thought it was funny 

and it happened to me like yesterday and after a lot of debugging when i knew it was the same prob i had to report it

and btw it happened in my laptop and desktop both with the same python version

soo look 

im gonna use the -vv cz it gives better details 

okay so my bad in the code i provided earlier the bug doesnt happen but imma give u the exact lines that made my code crash and what i changed them too and imma download the old version of the code and build it to show u 

![image_2024-08-22_014150964](https://github.com/user-attachments/assets/feb0c15f-f8b2-44ce-a8bb-bd0789eed8a8)

NOTE: relationship['device_id'] is a string //// relationship['device_status']  is a string and it can be ('true', 'false') 

![image_2024-08-22_014348098](https://github.com/user-attachments/assets/883b5b72-8fad-401d-a414-f969dfb417f2)

NOTE: here by simply removing the f and changing ' to " it worked 

now amma download the old version and build it for u :

![image_2024-08-22_015209632](https://github.com/user-attachments/assets/741bf084-d624-4475-bc92-dc4b9026c57d)

so as u can see here all the packages downloading and installing is going fine 

then comes the compiling 

![image_2024-08-22_015351820](https://github.com/user-attachments/assets/704c4206-2ddd-4329-a573-b9970fdebedc)


see its a compiling error and after changing what i showed u above just then it works fine so yeah

NOTE : its the same issue from a year ago too 


and here i tried to re-create the issue :

```Python
import flet as ft

def main(page: ft.Page):

    scene_devices_relationships = [
        {'device_id': '1', 'device_status': 'true'},
        {'device_id': '2', 'device_status': 'true'},
        {'device_id': '3', 'device_status': 'true'},
        {'device_id': '4', 'device_status': 'true'},
        {'device_id': '5', 'device_status': 'true'},
        {'device_id': '6', 'device_status': 'true'},
        {'device_id': '7', 'device_status': 'true'},
        {'device_id': '8', 'device_status': 'true'},
        {'device_id': '9', 'device_status': 'true'},
        {'device_id': '10', 'device_status': 'true'},
        {'device_id': '11', 'device_status': 'true'},
        {'device_id': '12', 'device_status': 'true'},
        {'device_id': '13', 'device_status': 'true'},
        {'device_id': '14', 'device_status': 'true'},
    ]
    
    
    scene_devices = []
    for relationship in scene_devices_relationships:
        device_data = {'id':f'{relationship['device_id']}', 'status':relationship['device_status'] == 'true'}
        status = relationship['device_status'] == 'true'
        device_data = {'id':relationship['device_id'], 'status': status}
        scene_devices.append(device_data)


    for device in scene_devices:
        page.add(ft.Text(device['id']))


ft.app(target=main)
```

and it works fine on vs code :
![image_2024-08-22_020600254](https://github.com/user-attachments/assets/465275fc-d9c0-461a-9580-d08a0fbbb6bb)


but not when building : i used ```flet build apk -vv```

![image_2024-08-22_020703168](https://github.com/user-attachments/assets/ea36adc8-2714-471d-ad2d-e10754aa8e19)


only this time it gave a more clear msg

if u need anything else just ask me
Thnx for ur time

**Comment by ndonkoHenri** [comment]
Can you give both Flet 0.24.1 and the latest [prerelease](https://pypi.org/project/flet/#history) a try and share the results?

**Comment by HamaBTW** [comment]
Ok I'll give it a try

**Comment by ndonkoHenri** [comment]
As mentioned in the [docs](https://flet.dev/blog/flet-new-packaging-pre-release#control-over-app-compilation-and-cleanup),
> flet build command is no longer compiling app .py files into .pyc by default

Install the latest Flet version and give it a try.
