### ISSUE TITLE
Mobile Packaging 2.0

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#3839]
Improve packaging for the mobile platforms as described in:
- https://flet.dev/blog/flet-packaging-update
- https://flet.dev/roadmap/#packaging

**Comment by YasseenAlhusammi** [comment]
متى سيم تحقيق هذه الطلبات، هل يوجد تقديرت؟؟ نحن في انتظار على الجمر خصوصا flet build apk with cv2

**Comment by YasseenAlhusammi** [comment]
When will these requests be fulfilled, are there any estimates?? We are waiting impatiently, especially flet build apk with cv2. Waiting is difficult for us. Please give us hope by giving an approximate possible date.

**Comment by zox47** [comment]
> When will these requests be fulfilled, are there any estimates?? We are waiting impatiently, especially flet build apk with cv2. Waiting is difficult for us. Please give us hope by giving an approximate possible date.

you can use this tool
https://github.com/zox47/build-lib-native?tab=readme-ov-file#flet-native-

**Comment by Balambonzo** [comment]
I have followed every instruction in your video (https://youtu.be/IcT_QrLWi10) but when I export my .apk file on my android phone the app instantly crash every time I try to open it, does anyone know why? pls help me

**Comment by Balambonzo** [comment]
> I have followed every instruction in your video (https://youtu.be/IcT_QrLWi10) but when I export my .apk file on my android phone the app instantly crash every time I try to open it, does anyone know why? pls help me

I am using libraries like faster-whisper, sounddevice, soundfile and ollama, maybe it is for this reason?
