### ISSUE TITLE
Flet for ruby developer 

### ISSUE THREAD

**Issue by AdamMusa** [flet-dev/flet#385]
Hello 👋 .  I see that flet will offer the Go, C# etc version in the future but we  the ruby ​​developer also want to have flet so we decided to create with osscameroon community (Developer passionate about open source ). Of course if you don't see the disadvantages We would like to continue or merge of course if you have dedicated people to create sdkRuby for flet .  
Advice or guidance needed that will allow us to have flet for ruby ​​developer are really appreciable.

**Comment by FeodorFitsner** [comment]
It would be great to have Ruby in the list of supported languages! At the moment we are focused on the best support for Python. We welcome community to help the project with adding other languages.

**Comment by AdamMusa** [comment]
> 
Thank you so much. And we need some help,
What are the main components to implement to be able to launch flet under ruby . For example Control, Ref and Page  ?

**Comment by FeodorFitsner** [comment]
Yep, as a starting point:

* `flet.py`
* `reconnecting_websocket`
* `connection.py`
* `page.py`
* `control.py`

**Comment by FeodorFitsner** [comment]
I'm going to close this issue and we are close to implementing other languages we could re-open it again.
