### ISSUE TITLE
Property `border_radius` Is Affecting Clipping Behaviour

### ISSUE THREAD

**Issue by Jarvis-Yu** [flet-dev/flet#3870]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Setting `border_radius` property for a `Container` clips offsprings that extend out of the `Container`.

### Code sample

<details open><summary>Code</summary>

```python
def main(page: ft.Page):
    def container(with_radius: bool) -> ft.Container:
        c = ft.Container(
            width=200,
            height=200,
            bgcolor="#FFFFFF",
            alignment=ft.Alignment(1.3, 0),
            content=ft.Container(
                width=100,
                height=100,
                bgcolor="#FF0000",
            ),
        )
        if with_radius:
            c.border_radius = 0  # Basically any value
        return c

    page.add(
        container(False),
        container(True),
    )
    page.update()

ft.app(target=main)
```

</details>

### To reproduce

1. Just run the code and you'll see the difference.

### Expected behavior

Both red children containers should be able to appear outside its parent.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

<img width="800" alt="image" src="https://github.com/user-attachments/assets/683915b7-23ca-42bd-8ac2-2df4d76283a7">

</details>

### Operating System

macOS

### Operating system details

Sonoma 14.6.1

### Flet version

0.22.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
python -m path.to.file
```

</details>

**Comment by Jarvis-Yu** [comment]
BTW, `flet>=0.23.0` cannot run properly on my mac with `python==3.10.11` somehow, so I cannot check if the issue is fixed in the latest version of `flet`.

**Comment by ndonkoHenri** [comment]
It happens because, when you set the border_radius (any value other than the default `None`), the [clip behavior](https://flet.dev/docs/reference/types/clipbehavior) of the container is internally changed to `ANTI_ALIAS`.
To achieve the expected result, you need to (force) set the `clip_behavior` to `NONE`: `clip_behavior=ft.ClipBehavior.NONE,`

**Comment by ndonkoHenri** [comment]
> BTW, flet>=0.23.0 cannot run properly on my mac with python==3.10.11 somehow, so I cannot check if the issue is fixed in the latest version of flet.

Try the latest pre-release: `pip install flet -U --pre`

**Comment by Jarvis-Yu** [comment]
Thanks, I should have saw that in the doc.

**Comment by Jarvis-Yu** [comment]
> > BTW, flet>=0.23.0 cannot run properly on my mac with python==3.10.11 somehow, so I cannot check if the issue is fixed in the latest version of flet.
> 
> Try the latest pre-release: `pip install flet -U --pre`

Hi, yes the pre-release version works on my Mac.

**Comment by ndonkoHenri** [comment]
Yh, the issue was fixed: https://github.com/flet-dev/flet/issues/3557
