### ISSUE TITLE
More online examples

### ISSUE THREAD

**Issue by FHU-yezi** [flet-dev/flet#388]
Just find this freaking awesome library, and looking forward native chart support too.

I quickly looked through the documentions and saw poor examples there.

for example, when I saw the banner, snackbar and alertdialog, without any example or screenshot there, I was unable to imagine how they look like.

It will be more friendly to new ones if we can add some examples, such as buttons that has 'banner' or something else, and when I press this button, it shows a banner.

**Comment by hololeo** [comment]
poor examples? there is a multitude of examples in the examples repo. The amount of time the author of this program has put into documentation + examples + support + new coding + quality testing is enormous. and all for free and open source!

see links on this repo cheatsheet
https://github.com/hololeo/flet-cheatsheet

**Comment by FHU-yezi** [comment]
> poor examples? there is a multitude of examples in the examples repo. The amount of time the author of this program has put into documentation + examples + support + new coding + quality testing is enormous. and all for free and open source!
> 
> 
> 
> 
> 
> 

I think we must clone the examples repo or copy codes and run it locally, and there are not direct link to one example file in doc. It's inpossible when you use a mobile phone etc. and ru? the example app.

**Comment by hololeo** [comment]
The docs and examples are numerous and of high quality. There is no repl for Flet atm.

**Comment by FeodorFitsner** [comment]
I agree we need more online examples. The work is in progress.
