### ISSUE TITLE
OnScrollEvent, self.scroll_delta: Optional[float] = d["sd"]

### ISSUE THREAD

**Issue by piidus** [flet-dev/flet#3884]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Error is self.scroll_delta: Optional[float] = d["sd"]

### Code sample

<details open><summary>Code</summary>

```python
def on_column_scroll(self,e: OnScrollEvent):
        print(
            f"Type: {e.event_type}, pixels: {e.pixels}, min_scroll_extent: {e.min_scroll_extent}, max_scroll_extent: {e.max_scroll_extent}"
        )
        if e.pixels == e.max_scroll_extent:
            self.demo()

    def content(self):
        self.text_holder = ft.Column(
            spacing=10,
            height=200,
            width=200,
            scroll="always",            
            on_scroll=self.on_column_scroll,
            # auto_scroll=True,
            
        )
```

</details>

### To reproduce

if I disable this 
self.scroll_delta: Optional[float] = d["sd"]
        self.direction: Optional[str] = d["dir"]
        self.overscroll: Optional[float] = d["os"]
        self.velocity: Optional[float] = d["v"]
then it print

### Expected behavior

print

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

ubuntu 24.04

### Flet version

0.23.2

### Regression

No, it isn't

### Suggestions

if I disable this 
self.scroll_delta: Optional[float] = d["sd"]
        self.direction: Optional[str] = d["dir"]
        self.overscroll: Optional[float] = d["os"]
        self.velocity: Optional[float] = d["v"]
then it print

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/3566#issuecomment-2246392779
