### ISSUE TITLE
InteractiveViewer Controle not found after build apk

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#3907]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

InteractiveViewer is not defined yet after build apk

### Code sample

import flet as ft

def main(page: ft.Page):
    page.add(
        ft.InteractiveViewer(
            expand=True,
            min_scale=0.1,
            max_scale=5,
            boundary_margin=ft.margin.all(20),
            on_interaction_start=lambda e: print(e),
            on_interaction_end=lambda e: print(e),
            on_interaction_update=lambda e: print(e),
            content=ft.Container(
                gradient=ft.LinearGradient(colors=[ft.colors.RED, ft.colors.BLUE]),
            ),
        )
    )

ft.app(target=main)

### To reproduce

run the code and build it apk

### Screenshots / Videos

![Screenshot_2024-08-31-20-18-25-792_com flet src](https://github.com/user-attachments/assets/2befcbc6-af0c-49ce-8a64-76974a6f6abd)

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.24.0

### Regression

I'm not sure / I don't know

### Suggestions

i think you shoud add it in package folder like a Lotties controle 

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
It should be fixed now. Please re-build the app.

**Comment by zox47** [comment]
@FeodorFitsner should i update the flet or what

**Comment by FeodorFitsner** [comment]
Yep
