### ISSUE TITLE
user-made control or template sharing

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#391]
Can we add a new part to the website to share user-made controls or templates?
I am creating a custom control that consists of a text field and button...

![image](https://user-images.githubusercontent.com/62519221/192152972-0b6bd858-7745-40e2-a2ba-b1fae2d5bce6.png)

and

![image](https://user-images.githubusercontent.com/62519221/192153037-58f4e967-dcbc-46b4-b1b1-3ce1f2beb9d2.png)

I want a way to share this to the community

**Comment by FeodorFitsner** [comment]
Yes, you can add your example here: https://github.com/flet-dev/examples/tree/main/python/community

PS: Please use https://github.com/flet-dev/flet/discussions to ask a question. Issues are for bug reports and feature requests.
