### ISSUE TITLE
Closing the program takes too long

### ISSUE THREAD

**Issue by pychans** [flet-dev/flet#3918]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In the official code, when I click 'yes' to close the program, it takes 3-5 seconds.

### Code sample

https://flet.dev/docs/controls/page/#window_destroy
```python
import flet as ft

def main(page: ft.Page):
    page.title = "MyApp"

    def handle_window_event(e):
        if e.data == "close":
            page.open(confirm_dialog)

    page.window.prevent_close = True
    page.window.on_event = handle_window_event

    def handle_yes(e):
        page.window.destroy()

    def handle_no(e):
        page.close(confirm_dialog)

    confirm_dialog = ft.AlertDialog(
        modal=True,
        title=ft.Text("Please confirm"),
        content=ft.Text("Do you really want to exit this app?"),
        actions=[
            ft.ElevatedButton("Yes", on_click=handle_yes),
            ft.OutlinedButton("No", on_click=handle_no),
        ],
        actions_alignment=ft.MainAxisAlignment.END,
    )

    page.add(ft.Text('Try exiting this app by clicking window\'s "Close" button!'))

ft.app(main)
```

### To reproduce

1. Run the repro code
2. Click on close, and yes

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.24.0

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Works normally on macOS. 
Can any Windows user test this and report?

Also, @icsos, does this issue happen occasionally or always.

**Comment by lixxu** [comment]
same on Windows 11 and 0.24

**Comment by lixxu** [comment]
> Works normally on macOS. Can any Windows user test this and report?
> 
> Also, @icsos, does this issue happen occasionally or always.

tested on Windows 11, it happens always (about 5~6 seconds to quit). I use below ugly way to prevent this:
```python
#page.window.destroy()
page.close(confirm_dialog)
page.window.prevent_close = False
page.window.close()
```

**Comment by nastiliano** [comment]
> > Works normally on macOS. Can any Windows user test this and report?
> > Also, @icsos, does this issue happen occasionally or always.
> 
> tested on Windows 11, it happens always (about 5~6 seconds to quit). I use below ugly way to prevent this:
> 
> ```python
> #page.window.destroy()
> page.close(confirm_dialog)
> page.window.prevent_close = False
> page.window.close()
> ```

Hello,

Just now, tested on Windows 11 x64 (completly updated) with last Flet version (v.0.24.1).

It has been enhanced. At least for me. It takes about 1.5 seconds to close (acceptable) without errors.

Thanks. Best regards.

**Comment by nastiliano** [comment]
> Works normally on macOS. Can any Windows user test this and report?
> 
> Also, @icsos, does this issue happen occasionally or always.

Hello,

Just now tested on MacOS updated (Sonoma 14.6.1 - Intel Processor).

The app closes perfectly and fast. (faster than Windows. 0 seconds :)

Thanks. Best regards

**Comment by ndonkoHenri** [comment]
> Just now, tested on Windows 11 x64 (completly updated) with last Flet version (v.0.24.1). It has been enhanced. At least for me. 

@icsos please upgrade your Flet version an retry.

**Comment by lixxu** [comment]
tried and takes longer time...
![explorer_gZOaDI76hB](https://github.com/user-attachments/assets/e9bb5cff-662f-4cde-a97c-00b1033458d5)
![image](https://github.com/user-attachments/assets/4a5ea583-9e09-4ffa-b5bd-0a72b620dac8)

**Comment by nastiliano** [comment]
Hello everyone,

I've updated to Windows 11 24H2 and the problem comes back.

The window stills 5-7 seconds to close itself.

Best regards!

**Comment by nastiliano** [comment]
> Hello everyone,
> 
> I've updated to Windows 11 24H2 and the problem comes back.
> 
> The window stills 5-7 seconds to close itself.
> 
> Best regards!


Fixed with:

Flet = 0.25.0.dev3519
Python = 3.13

Thanks

**Comment by syleishere** [comment]
Have you tried to code some test functions to see what works better?
Off top of my head I'd probably test with something like this to see what works on windows, android, web etc...

```
    async def terminate1(self, e):
        print("Trying to kill program")
        self.config.page.loop.stop()

    async def terminate2(self, e):
        sys.exit(0)

    async def terminate3(self, e):
        to_cancel = asyncio.all_tasks(self.config.page.loop)
        if not to_cancel:
            return
        for task in to_cancel:
            task.cancel()
        self.config.page.loop.run_until_complete(
            asyncio.gather(*to_cancel, return_exceptions=True)
```
