### ISSUE TITLE
unicode string in tooltip

### ISSUE THREAD

**Issue by lixxu** [flet-dev/flet#3924]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

tooltip on IconButton shows unicode strings not actual strings, [the example](https://flet.dev/docs/controls/iconbutton#icon-buttons) also not show the correct value if not English.
![8e7a705847282ef788f079029a3181b](https://github.com/user-attachments/assets/71d28714-0537-4c95-b052-449eb1c4ff9f)

# codes like below
```python

def get_button(icon: str, func: Any, tooltip: str = "") -> ft.IconButton:
    return ft.IconButton(
        icon=getattr(ft.icons, icon.upper()),
        style=ft.ButtonStyle(
            shape=ft.RoundedRectangleBorder(radius=0),
        ),
        on_click=func,
        tooltip=tooltip,
    )

get_button("remove", self.click_min, "最小化")
```

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

change the tooltip to non-English strings.
[https://flet.dev/docs/controls/iconbutton#icon-buttons](https://flet.dev/docs/controls/iconbutton#icon-buttons)

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.24

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
I think this should have been fixed in https://github.com/flet-dev/flet/issues/3920.

Can you try the latest prerelease: `pip install Flet -U --pre`

**Comment by lixxu** [comment]
yes, pre version fixed.
