### ISSUE TITLE
Adding custom icons when building APK?

### ISSUE THREAD

**Issue by jiho-m0521** [flet-dev/flet#3927]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Hello, Flet team!

I am developing a mobile app with flet. I usually build the mobile app using `flet build apk`, but the flet icon is bothersome. I want to add a custom icon myself when building APK file. Please consider this in the new version.

Best regards!

**Comment by ndonkoHenri** [comment]
Here: https://flet.dev/docs/publish#icons
