### ISSUE TITLE
 web server

### ISSUE THREAD

**Issue by soease** [flet-dev/flet#393]
I want to set up a web server myself. How can I use flet only as the foreground interface.

I think the back end has very rich solutions.

**Comment by FeodorFitsner** [comment]
Why would you need that? What is your use case?

**Comment by FHU-yezi** [comment]
> Why would you need that? What is your use case?

Maybe for higher performance? Or if you already has an API service write with Sanic, FastAPI etc. and you want to add flet App for one route.

**Comment by FeodorFitsner** [comment]
I don't know (yet) how Flet could be integrated into another web server. Flet comes with its own web server.

If you don't mind I'm going to close this issue and if you like we could continue in [discussions](https://github.com/flet-dev/flet/discussions).
