### ISSUE TITLE
Regression: IconButton "ToolTip" error

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#3935]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In new version 0.24 the "ToolTip" of "IconButton" doesn't remove the quotes and doesn't draw accents correctly

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

    import flet as ft

        def main(page: ft.Page):
            page.add(ft.IconButton(icon="insert_drive_file_outlined" , tooltip="Aló"))

    ft.app(main)

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>
![Captura de pantalla 2024-09-03 173945](https://github.com/user-attachments/assets/1188bb23-955b-4bf7-8447-b3fea29d0892)

### Operating System

Windows

### Operating system details

The samo on MacOS & Linux

### Flet version

0.24

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by HardMax71** [comment]
+1, works not as shown in https://flet.dev/docs/controls/iconbutton/

**Comment by FeodorFitsner** [comment]
It should be fixed in just-released Flet 0.24.1 - please upgrade and let us know if worked.

**Comment by nastiliano** [comment]
Yeah! It works again


Thanks!
