### ISSUE TITLE
Image cannot be displayed on win10

### ISSUE THREAD

**Issue by liziliang123** [flet-dev/flet#394]
when i run this example:

import flet
from flet import Image, Page, RadialGradient, Row, ShaderMask, alignment, colors

def main(page: Page):
    page.add(
        Row(
            [
                ShaderMask(
                    Image(
                        src="https://picsum.photos/200/200?1",
                        width=200,
                        height=200,
                        fit="fill",
                    ),
                    blend_mode="multiply",
                    shader=RadialGradient(
                        center=alignment.center,
                        radius=2.0,
                        colors=[colors.WHITE, colors.PINK],
                        tile_mode="clamp",
                    ),
                ),
            ]
        )
    )

flet.app(target=main)

Image cannot be displayed

**Comment by hololeo** [comment]
you need page.update() at the end

**Comment by FeodorFitsner** [comment]
My guess is https://picsum.photos blocked/throttled by Great China Firewall.

Try that example with a locally hosted image or an image (https://flet.dev/docs/controls/image/#src) hosted inside China.

**Comment by liziliang123** [comment]
@FeodorFitsner  That's right , thanks
