### ISSUE TITLE
Flet 0.24.1: Disabled background color for FilledTonalButton not applied

### ISSUE THREAD

**Issue by tobsome** [flet-dev/flet#3941]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When the FilledTonalButton is disabled the color stays like it's active. Before the last upgrade to 0.24.1, I was on 0.23.2 before, the disabled button got a background of Gray. I don't think it's intended? 

### Code sample

<details open><summary>Code</summary>

```python
        self.check_button = ft.FilledTonalButton(
            text="Get Users",
            on_click=self.on_check_click,
            icon=ft.icons.SEARCH,
            disabled=True,
        )
```

</details>

### To reproduce

Disabling an FilledTonalButton.

### Expected behavior

The button should get a Gray background.

### Operating System

macOS

### Operating system details

14.6.1

### Flet version

Name: flet Version: 0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)
-> 0.23.2

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

Happens for each single button in my tool.

**Comment by nastiliano** [comment]
Hello,

Exactly, this feature (disabled status) was suppressed (tested in Windows, MacOS and Linux)

Thank you. Best regards.

**Comment by tobsome** [comment]
Hi @nastiliano,

what does it mean? It will come back/fixed in future releases?

**Comment by nastiliano** [comment]
> Hi @nastiliano,
> 
> what does it mean? It will come back/fixed in future releases?

No, no... sorry for my explanation. I'm just a beginner.
I just say that in my program this feature works bad too.
I suppose that it would be resolved in future versions.

Thanks. Best regards.

**Comment by tobsome** [comment]
Got it! Cool, thanks for testing it! 🙏
