### ISSUE TITLE
Seems like TimePicker can't open on Android (Samsung) when using Page.open method in application built into APK

### ISSUE THREAD

**Issue by DanyaIzm** [flet-dev/flet#3951]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Android (Samsung): TimePicker can't be opened when using page.open(time_picker) method as recommended in documentation.
Everything is fine if deprecated time_picker.pick_time() is used.
When ```flet run --android``` is used everything is fine, but problem occurs when code is built into APK with ```flet build  apk```.
There are code examples of version, which uses Page.open and does not work properly, and version with page.overlay.append(time_picker) and deprecated TimePicker.pick_time which is working properly.

Flet version: 0.24.1
Android: 13
Smartphone manufacturer: Samsung
Samsung's One UI version: 5.1
Phone model: Galaxy Note 20 Ultra

### Code sample

<details open><summary>Code</summary>

Code which does not work properly:
```python
import datetime
import flet as ft


def main(page: ft.Page):
    page.title = "TimePicker"

    def handle_time_picker_change(e):
        time_button.text = str(time_picker.value)
        time_button.update()

    time_picker = ft.TimePicker(
        value=datetime.time(),
        confirm_text="Confirm",
        error_invalid_text="Time out of range",
        help_text="Pick your time slot",
        on_change=lambda e: handle_time_picker_change(e),
    )
    time_button = ft.ElevatedButton(
        text="00:00:00",
        on_click=lambda _: page.open(time_picker),
    )

    page.add(
        ft.Row(
            [
                ft.Column(
                    [
                        time_button,
                    ],
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                )
            ],
            expand=True,
            alignment=ft.MainAxisAlignment.CENTER,
            vertical_alignment=ft.CrossAxisAlignment.CENTER,
        )
    )


ft.app(main)
```

Alternative version of this code which works correctly:
```python
import datetime
import flet as ft


def main(page: ft.Page):
    page.title = "TimePicker"

    def open_time_picker(e, time_picker: ft.TimePicker):
        time_picker.pick_time()

    def handle_time_picker_change(e):
        time_button.text = str(time_picker.value)
        time_button.update()

    time_picker = ft.TimePicker(
        value=datetime.time(),
        confirm_text="Confirm",
        error_invalid_text="Time out of range",
        help_text="Pick your time slot",
        on_change=lambda e: handle_time_picker_change(e),
    )
    time_button = ft.ElevatedButton(
        text="00:00:00",
        on_click=lambda e: open_time_picker(e, time_picker=time_picker),
    )

    page.overlay.append(time_picker)

    page.add(
        ft.Row(
            [
                ft.Column(
                    [
                        time_button,
                    ],
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                )
            ],
            expand=True,
            alignment=ft.MainAxisAlignment.CENTER,
            vertical_alignment=ft.CrossAxisAlignment.CENTER,
        )
    )


ft.app(main)
```

</details>

### To reproduce

1. Build first version of code above with ```flet build apk```
2. Open application
3. Push the button - nothing will happen, no dialog will open

### Expected behavior

If you try to run second version of code above - TimePicker dialog will show up like should

### Screenshots / Videos

<details open>
<summary>Captures</summary>

https://github.com/user-attachments/assets/47f8ce75-50d5-4aeb-a41b-af7a3d1c7935

</details>

### Operating System

Windows

### Operating system details

APK build under Windows 10 for Android 13 with One UI 5.1

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Suggestions

I am a real newby in Flutter and Flet, but I suppose problem can be with page overlay, because in correctly working version of code above I added time_picker into overlay list manually.

Or maybe there is a problem in my code somewhere.

**Comment by DanyaIzm** [comment]
If I add time_picker to page.overlay with ```page.overlay.append(time_picker)``` and use ```page.open(time_picker)```, nothing changes - dialog still cannot open

**Comment by ndonkoHenri** [comment]
Related to #3867

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of https://github.com/flet-dev/flet/issues/3867

Please mention any further details in there.
