### ISSUE TITLE
 Issue: Packaging without using `app.zip` and keeping it decompressed

### ISSUE THREAD

**Issue by jaluscgr** [flet-dev/flet#3956]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I'm trying to package my web app using `flet build web`, and it successfully creates a build. However, when I deploy it, the application fails to run correctly because the `app.zip` is too large, and it gets stuck during the decompression process.

I'd like to know how to modify the build process so that the app is already decompressed when it is used on the web, without having to rely on the `app.zip`. In other words, how can I configure the build to have the app decompressed and ready to use directly after deployment?

### Steps to reproduce:
1. Run `flet build web` to package the app.
2. Deploy the app to the server.
3. Start the app and wait for the `app.zip` to decompress.

### Expected behavior:
The app should not require decompression of `app.zip` and should be ready to use immediately after deployment, with the folder structure already available.

### Actual behavior:
The app gets stuck during the decompression of `app.zip` due to its large size.

### Environment:
- Tool used: Flet
- Build command: `flet build web`

### Suggested solution:
Is there a way to configure the build or deployment process to avoid using a zip file and instead have the app's folder structure ready to use in its decompressed form?

Thank you in advance for your help!

**Comment by FeodorFitsner** [comment]
Pyodide works with a Python app located in its virtual file system. `app.zip` is unpacked into a browser's virtual file system with pre-served structure. Compared to a regular web app it's not a set of .js, .css, .html files and cannot be loaded file-by-file on demand.

Though why do you have such a huge zip? What are the dependencies, assets?
