### ISSUE TITLE
Container border-radius and border don't work if before_update method is used

### ISSUE THREAD

**Issue by azhago** [flet-dev/flet#3962]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

If the before_update method is used, border-radius and border  params for container don't work

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

# 0.19: OK
# 0.21.2 and > : KO
class Test(ft.Container):
    def __init__(self):
        super().__init__()
        self.border_radius = 15
        self.width=100
        self.height = 100
        self.bgcolor=ft.colors.BLUE_100
        self.border=ft.border.all(3,ft.colors.BLUE_ACCENT_700)
        self.content=ft.Icon(name=ft.icons.ADD)

    def before_update(self):
        print("doing something before update")

def main(page:ft.Page):
    page.theme_mode = ft.ThemeMode.LIGHT
    page.add(Test())

if __name__ == "__main__":
    ft.app(target=main)
```

</details>

### To reproduce

simply run the code and compare with flet 0.19 or less, or with before_update() commented

### Screenshots / Videos

<details open>
<summary>Captures</summary>
Wrong:

![Capture d'écran 2024-09-10 194524](https://github.com/user-attachments/assets/b1830d75-5842-4049-9478-ffe1507d17bd)
Good:
![Capture d'écran 2024-09-10 194618](https://github.com/user-attachments/assets/52820af4-f92d-482b-980e-089d35453851)
</details>

### Operating System

Windows

### Operating system details

W11

### Flet version

21.2 and >

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
You need to add a `super` call:
```py
    def before_update(self):
        super().before_update()
        print("doing something before update")
```
