### ISSUE TITLE
FAB on_click function triggering without click when code runs.

### ISSUE THREAD

**Issue by Dzheremi2** [flet-dev/flet#3964]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I created a FAB and set its `on_click` method to my function.
```python
    page.floating_action_button = ft.FloatingActionButton(
        icon=ft.icons.CHECK_CIRCLE_OUTLINE_OUTLINED,
        text="Start Sync",
        enable_feedback=True,
        on_click=change_to_sync(page)
    )
```
But every time I run my code, this function triggers without pressing the FAB

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    def test():
        for i in range(10):
            page.controls.append(ft.Text("Test Text", color=ft.colors.WHITE, size=100))

    page.floating_action_button = ft.FloatingActionButton(
        icon=ft.icons.CHECK_CIRCLE_OUTLINE_OUTLINED,
        text="Test",
        enable_feedback=True,
        on_click=test()
    )
    page.update()

ft.app(main)
```

</details>

### To reproduce

Just run this code with `flet run [name].py`

### Expected behavior

`test()` function executes only when FAB pressed.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

https://github.com/user-attachments/assets/3fc6c25c-74b1-4b35-af66-7393ac7525d3

</details>

### Operating System

Linux

### Operating system details

Linux fedora 6.10.7-200.fc40.x86_64

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

**Comment by lk-itween** [comment]
hey, bro. This is an incorrect usage. on_click may be set function name or using lambda instead of calling it
example:

```python
import flet as ft

def main(page: ft.Page):
    def test():
        for i in range(10):
            page.controls.append(ft.Text("Test Text", color=ft.colors.WHITE, size=100))

    page.floating_action_button = ft.FloatingActionButton(
        icon=ft.icons.CHECK_CIRCLE_OUTLINE_OUTLINED,
        text="Test",
        enable_feedback=True,
        on_click=test   # You shouldn't call it
    )
    page.update()

ft.app(main)
```

**Comment by Dzheremi2** [comment]
> hey, bro. This is an incorrect usage. on_click may be set function name or using lambda instead of calling it
> example:
> 
> ```python
> import flet as ft
> 
> def main(page: ft.Page):
>     def test(e):
>         for i in range(10):
>             page.controls.append(ft.Text("Test Text", color=ft.colors.WHITE, size=100))
>         page.update()
> 
>     page.floating_action_button = ft.FloatingActionButton(
>         icon=ft.icons.CHECK_CIRCLE_OUTLINE_OUTLINED,
>         text="Test",
>         enable_feedback=True,
>         on_click=test   # You shouldn't call it
>     )
>     page.update()
> 
> ft.app(main)
> ``` 

Oh god, thank you so much. I've almost gave up.
