### ISSUE TITLE
max_menu_height and height properties in Dropdown does not work

### ISSUE THREAD

**Issue by ClearSafety** [flet-dev/flet#3966]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I tried to set a maximum height for the list of the dropdown, but it seems to have no effect.

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):

    page.add(
        ft.Dropdown(
            options=[
                ft.dropdown.Option(text='Option 1'),
                ft.dropdown.Option(text='Option 2'),
                ft.dropdown.Option(text='Option 3'),
                ft.dropdown.Option(text='Option 4'),
                ft.dropdown.Option(text='Option 5'),
                ft.dropdown.Option(text='Option 6'),
                ft.dropdown.Option(text='Option 7'),
                ft.dropdown.Option(text='Option 8'),
            ],
            item_height=100, # Height of each option in the dropdown list
            max_menu_height=200, # It has no effect
        )
    )

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

</details>

### To reproduce

1. Run the repro code
2. Tap the Dropdown field

### Expected behavior

Display only two items of the list.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 Pro

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ClearSafety** [comment]
The other issue I forgot to mention is about the height property. It does not work properly.
It reduces the height properly, but does not increase. If you set a heigh number for this property, it increases only the shadow of the field, but not the field itself.

**Comment by ndonkoHenri** [comment]
I fixed the issue related to the max height in the attached PR.

Setting the height of the DD is also an issue. Found this comment https://github.com/flutter/flutter/issues/136407#issuecomment-1759096010 which points to issue https://github.com/flutter/flutter/issues/135903

**Comment by ClearSafety** [comment]
Thank you for solving this issue.
Could you tell me, please, how could I upgrade the Flet to capture this amendment?
Running 'pip install flet --pre -U' I got the version 0.25.0.dev3614.
But for some reason, when I try to run the app, it arises an error in Terminal.
When I come back to the version 0.24.1, the app run smothely.

  WARNING: Failed to write executable - trying to use .deleteme logic
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli.py", line 24, in main
    flet_cli.cli.main()
  File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_cli\cli.py", line 88, in main
    args.handler(args)
  File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_cli\commands\run.py", line 144, in handle
    from flet_desktop import close_flet_view
  File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\__init__.py", line 14, in <module>
    from flet_core.utils import (
ImportError: cannot import name 'get_arch' from 'flet_core.utils' (C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\utils\__init__.py)

**Comment by ndonkoHenri** [comment]
@ClearSafety please open a new issue.
