### ISSUE TITLE
Issue with code colors in dark mode in Markdown

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#3969]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In the Controls Gallery app (https://flet-controls-gallery.fly.dev/displays/markdown), Flet version 0.21.2,  code is displayed normally.

In 0.24.1, colors in the code displayed differently and some of them are not visible on the dark background.

### Code sample

<details open><summary>Code</summary>

import flet as ft

def main(page: ft.Page):

    table = """

### Create Python program

Create a new Python program using Flet which will be driving the content of `FletApp` widget.

Let's do a simple `counter.py` app similar to a Flutter new project template:

```python
import flet
from flet import IconButton, Page, Row, TextField, icons

def main(page: Page):
    page.title = "Flet counter example"
    page.vertical_alignment = "center"

    txt_number = TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = int(txt_number.value) - 1
        page.update()

    def plus_click(e):
        txt_number.value = int(txt_number.value) + 1
        page.update()

    page.add(
        Row(
            [
                IconButton(icons.REMOVE, on_click=minus_click),
                txt_number,
                IconButton(icons.ADD, on_click=plus_click),
            ],
            alignment="center",
        )
    )

flet.app(target=main, port=8550)
```
"""

    page.add(
        ft.Markdown(
            table,
            selectable=True,
            extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
            code_theme=ft.MarkdownCodeTheme.ATOM_ONE_DARK,
            code_style_sheet=ft.MarkdownStyleSheet(
                code_text_style=ft.TextStyle(font_family="Roboto Mono")
            ),
            # on_tap_link=lambda e: ft.page.launch_url(e.data),
        )
    )

ft.app(target=main)

</details>

### To reproduce

1. Run https://flet-controls-gallery.fly.dev/displays/markdown and see how code looks in 0.21.2:
<img width="1247" alt="Screenshot 2024-09-11 at 10 40 46 AM" src="https://github.com/user-attachments/assets/7d9dc948-197a-4596-be4d-bfe5d95484ec">

2. Run example code with 0.24.1 and result is this:
<img width="789" alt="Screenshot 2024-09-11 at 10 38 14 AM" src="https://github.com/user-attachments/assets/f0ad2c6b-dd4f-452b-be7d-1f4e44cf91e0">

### Expected behavior

Expected to look in 0.24.1 same as in 0.21.2.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

macOS

### Flet version

0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Seems like I am getting a different output.

### Data

```text
md = """
import flet
from flet import IconButton, Page, Row, TextField, icons

def main(page: Page):
    page.title = "Flet counter example"
    page.vertical_alignment = "center"

    txt_number = TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = int(txt_number.value) - 1
        page.update()

    def plus_click(e):
        txt_number.value = int(txt_number.value) + 1
        page.update()

    page.add(
        Row(
            [
                IconButton(icons.REMOVE, on_click=minus_click),
                txt_number,
                IconButton(icons.ADD, on_click=plus_click),
            ],
            alignment="center",
        )
    )

flet.app(target=main, port=8550)
"""
```

### Code
```python
def main(page):
    page.scroll = True
    page.window.always_on_top = True
    page.add(
        ft.Markdown(
            value=md,
            selectable=True,
            extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
            code_theme=ft.MarkdownCodeTheme.ATOM_ONE_DARK,
            code_style_sheet=ft.MarkdownStyleSheet(
                code_text_style=ft.TextStyle(font_family="Roboto Mono"),
            ),
        )
    )


ft.app(main)
```
### Output
![image](https://github.com/user-attachments/assets/bb66f7d8-0090-4885-a247-7ff1f4075c25)

**Comment by InesaFitsner** [comment]
Was issue with my environment
