### ISSUE TITLE
Tooltip is not displayed correctly in 0.24.1

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#3971]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Instead of tooltip, some text with tooltip properties is displayed.

### Code sample

<details open><summary>Code</summary>

```python
import math

import flet as ft


def main(page):

    text = ft.Text(
        value="Hover to see tooltip",
        tooltip=ft.Tooltip(
            message="This is tooltip",
            padding=20,
            border_radius=10,
            text_style=ft.TextStyle(size=20, color=ft.colors.WHITE),
            gradient=ft.LinearGradient(
                begin=ft.alignment.top_left,
                end=ft.alignment.Alignment(0.8, 1),
                colors=[
                    "0xff1f005c",
                    "0xff5b0060",
                    "0xff870160",
                    "0xffac255e",
                    "0xffca485c",
                    "0xffe16b5c",
                    "0xfff39060",
                    "0xffffb56b",
                ],
                tile_mode=ft.GradientTileMode.MIRROR,
                rotation=math.pi / 3,
            ),
        ),
    )

    page.add(text)


ft.app(target=main)
```

</details>

### To reproduce

1. Run repro code
2. Hover mouse over text
3. Instead of tooltip see this:
<img width="798" alt="Screenshot 2024-09-11 at 1 13 13 PM" src="https://github.com/user-attachments/assets/75a1c6d4-a8c0-447b-a391-25303d2fe7d3">

### Expected behavior

I expected to see tooltip with gradient.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

macOS

### Flet version

0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Suggestions

It used to work when Tooltip used to be a Control (0.21.2)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Here is the output on my end:
![image](https://github.com/user-attachments/assets/8d36440c-090b-46e5-932c-ca5bc6753019)

**Comment by InesaFitsner** [comment]
Was issue with my environment
