### ISSUE TITLE
image flicker on quick swap

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#398]
**Description**

Scenario: loading a sequence of image frames inside same Image.src creates a flicker.

![flet-image-bug](https://user-images.githubusercontent.com/11970940/192375141-17e540c1-e798-4b0a-bc5f-6ef96b1455ab.gif)

As discussed in discord, when replacing Image.scr in tight intervals, there is a flicker. 

As discussed possible solutions are
https://api.flutter.dev/flutter/widgets/Image/gaplessPlayback.html
https://api.flutter.dev/flutter/widgets/Image/frameBuilder.html

Source for horse frames player here:
[flet-frames-player.zip](https://github.com/flet-dev/flet/files/9649644/flet-frames-player.zip)

**Comment by FeodorFitsner** [comment]
Gapless playback worked! There is a new `Image.gapless_playback` property for that.
