### ISSUE TITLE
Tab doesn't display content

### ISSUE THREAD

**Issue by Dave-d-1st** [flet-dev/flet#3982]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When the scroll is enabled for a container that a tab is in or the entire page the tab does not display the content on android and scrolls infinitely and on windows it displays the content, but it scrolls infinitely 

### Code sample
<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    page.scroll=True
    t = ft.Tabs(
        selected_index=1,
        animation_duration=300,
        tabs=[
            ft.Tab(
                text="Tab 1",
                content=ft.Container(
                    content=ft.Text("This is Tab 1"), alignment=ft.alignment.center
                ),
            ),
            ft.Tab(
                tab_content=ft.Icon(ft.icons.SEARCH),
                content=ft.Text("This is Tab 2"),
            ),
            ft.Tab(
                text="Tab 3",
                icon=ft.icons.SETTINGS,
                content=ft.Text("This is Tab 3"),
            ),
        ],
        expand=1,
    )

    page.add(t)

ft.app(main)

```

</details>
### To reproduce

Just run the code and scroll

### Expected behavior

Meant to display the contents in the tab and not scroll infinitely 

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 and Flet app

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by OwenMcDonnell** [comment]
Scroll mode of page needs to be set to a value of `ScrollMode` enum defined [here](https://flet.dev/docs/reference/types/scrollmode). If you don't want any scrolling just remove that line from your code, thereby setting the value to `None` and you should get the result you're looking for.
