### ISSUE TITLE
why the container's expand is only for vertical , i want expand for both vertical and horizontal , how to do it?

### ISSUE THREAD

**Issue by liziliang123** [flet-dev/flet#399]
for example:

import flet
from flet import Container, Icon, Page, Tab, Tabs, Text, alignment, icons, Column, Row, colors, TextField

def main(page: Page):

    page.window_width = 800
    page.window_height = 600

    mainWindow = Container(
        expand=True,
        bgcolor = colors.YELLOW,
        content=Text('测试')
    )

    page.add(mainWindow)

flet.app(target=main)

 i want expand for both vertical and horizontal ,in flutter ,i can set width = double.infinity , but  how to do this in flet?

![QQ截图20220927113426](https://user-images.githubusercontent.com/22408584/192426677-e2cf80ef-d8e8-4b04-8340-3d2fe169e046.jpg)

**Comment by liziliang123** [comment]
![QQ截图20220927113426](https://user-images.githubusercontent.com/22408584/192426157-59da956a-cbb6-4d2c-b23d-7ec529c8a935.jpg)

**Comment by FeodorFitsner** [comment]
Add `page.horizontal_alignment = "stretch"`:

```python
import flet
from flet import Container, Text, colors

def main(page):
    mainWindow = Container(expand=True, bgcolor=colors.YELLOW, content=Text("测试"))
    page.horizontal_alignment = "stretch"
    page.add(mainWindow)

flet.app(target=main)
```

**Comment by liziliang123** [comment]
@FeodorFitsner ok , thanks!
