### ISSUE TITLE
KeyboardType is not working properly

### ISSUE THREAD

**Issue by thomaspt2016** [flet-dev/flet#3992]
def textboxcreator(Labl,color,width):
    buton = ft.TextField(
                label=Labl,
                width=width, 
                color=color,
                adaptive=True,
                border=ft.InputBorder.OUTLINE,
                border_color=ft.colors.WHITE70,
                border_radius=30,
                keyboard_type=ft.KeyboardType.NUMBER,
                 )
    return buton

Phone_Number = textboxcreator("Phone Number", ft.colors.WHITE70, 200,)

I was able to enter text in the field

**Comment by ndonkoHenri** [comment]
Please next time make use of the right template when creating an issue.

You need to set the [`input_filter`](https://flet.dev/docs/controls/textfield/#input_filter).
Also consider reading [this](https://python.plainenglish.io/textfield-input-filtering-validation-in-flet-python-177b737637dd) and [this](https://python.plainenglish.io/whats-new-in-flet-v0-24-0-83f758245f4d#:~:text=TextField-,InputFilter,-We%20modified%20how).

If you need assistance on this, [open a discussion](https://github.com/flet-dev/flet/discussions/new?category=q-a).
