### ISSUE TITLE
Unable to scroll smoothly on built executable

### ISSUE THREAD

**Issue by vishnu-rvb** [flet-dev/flet#4000]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I tried to build an simple app for windows that consists of long list of items.
when running code i am able to scroll smoothy by holding the mouse button and dragging on the scroll bar but on when running a built executable on windows i am unable to scroll by dragging and only mouse wheel works good.

### Code sample
```
import flet as ft
def main(page:ft.Page):
    page.scroll = "ALWAYS"
    layout=ft.Column()
    for i in range(0,100):
        item=ft.ExpansionTile(title=ft.Text(f'item {i}'),controls=[ft.Text(f'details {i}')])
        layout.controls.append(item)
    page.add(layout)
ft.app(main)
```

### To reproduce

1)Run in shell `flet run` or run the code as in any python debugger/interpreter.
2)check the scroll bar function
3)Run in shell `flet build windows` on the code
3)check the scroll bar function from the built app

### Expected behavior

Make screen scrolling smoother

### Screenshots / Videos
attached videos of scenario
1)Running on python IDLE

![list view scroll ok](https://github.com/user-attachments/assets/df8f8102-c671-4f51-9c20-5b054409533e)

2)Running on built executable
![list view scroll not ok](https://github.com/user-attachments/assets/ced695cb-60df-4655-b9ce-32aae2da1d83)

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

Name: flet Version: 0.22.0 Summary: Flet for Python - easily build interactive multi-platform apps in Python Home-page: https://flet.dev Author: Appveyor Systems Inc. Author-email: hello@flet.dev License: Apache-2.0 Location: c:\program files\python310\lib\site-packages Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog Required-by:

### Regression

I'm not sure / I don't know

</details>

### Additional details

On upgrading flet version to 0.24.1 the same issue is occurring when on python IDLE itself

**Comment by ndonkoHenri** [comment]
I think we can close this issue in favor of https://github.com/flet-dev/flet/issues/3963
