### ISSUE TITLE
Add src_base64 for VideoMedia

### ISSUE THREAD

**Issue by Grizou2018** [flet-dev/flet#4012]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I don't understand why this feature is available for images but not for videos.

**Comment by ndonkoHenri** [comment]
The Flutter package on which we depend for video doesn't seem to support this: https://pub.dev/packages/media_kit.
Feel free to search on how this can be done in Flutter and share here for possible implementation.

Closing this issue for now.
