### ISSUE TITLE
ButtonStyle alignment property not recognized

### ISSUE THREAD

**Issue by sfreemire** [flet-dev/flet#4016]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Using the "alignment" property of ButtonStyle generates this error:
`TypeError: ButtonStyle.__init__() got an unexpected keyword argument 'alignment'`

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page):
    button = ft.TextButton(
        "Click me",
        style=ft.ButtonStyle(
            alignment=ft.alignment.center_left  # Align the text to the left
        ),
        width=200  # Optional: Define the width for the button
    )
    
    page.add(button)

ft.app(target=main)
```

</details>

### To reproduce

Steps to reproduce:
1) Run the repro code
2) Error is generated

### Expected behavior

Expected to see button with left-aligned text label.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Sonoma 14.6.1

### Flet version

Version: 0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
Unhandled error processing page session : Traceback (most recent call last):
  File "/Users/scott.freemire/Code/fletapps/venv/lib/python3.12/site-packages/flet_runtime/app.py", line 244, in on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "/Users/scott.freemire/.pyenv/versions/3.12.4/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.freemire/Code/fletapps/ipmcapp/Calc_App_Base.py", line 6, in main
    style=ft.ButtonStyle(
          ^^^^^^^^^^^^^^^
TypeError: ButtonStyle.__init__() got an unexpected keyword argument 'alignment'

[Finished in 7.3s]
```

</details>

**Comment by ndonkoHenri** [comment]
Please upgrade to the latest Flet version (0.24.1)

**Comment by sfreemire** [comment]
Many thanks!
