### ISSUE TITLE
How can I update all the controls from data at once , just like flutter's setState()

### ISSUE THREAD

**Issue by liziliang123** [flet-dev/flet#403]
How can I update all the controls at once just like flutter's setState() , for example: 
`import flet
from flet import Container, Page, ElevatedButton, ListView

btList = []
def main(page: Page):
    
    btList.append('1')
    btList.append('2')
    
    def objectList():
        items = []
        for i in range(0, len(btList)):
            items.append(ElevatedButton(text=f"Elevated button {i}", width=30))
        return items

    mainWindow = Container(
        expand=True,
        content=ListView(
            controls=objectList(),
            expand=True
        ))

    page.add(mainWindow)

    btList.append('3')
    btList.append('4')

    page.update()  # it dosn't work

flet.app(target=main)
`

**Comment by FeodorFitsner** [comment]
Flet does not do "data binding" or "templating". Instead, you either building new `ElevatedButton` controls for 3 and 4 items and add them a ListView or rebuild the entire ListView after changing `btList`.

**Comment by FeodorFitsner** [comment]
Please post questions in https://github.com/flet-dev/flet/discussions or on Discord: https://discord.gg/dzWXP8SHG8

**Comment by ndonkoHenri** [comment]
Calling `page.update` like that can't eventually work(will have no visible effect).
The update function kind of makes visible(shows up) the changes you lately did on controls.

Concerning your question, I don't understand which control you wish to update. (I don't know Flutter's setState())
Do you want your program to later add two ElevatedButtons with the values you appended to the list(3 and 4) ?

**Comment by ndonkoHenri** [comment]
> Flet does not do "data binding" or "templating". Instead, you either building new `ElevatedButton` controls for 3 and 4 items and add them a ListView or rebuild the entire ListView after changing `btList`.

Exactly.
 I think doing this can work If you just add it before the `page.update()`:
`mainWindow.content.controls= objectList()`

But I don't see any reason for updating the Container contents this way. (Considering your code)
Just do the appends before calling the `page.add(mainWindow)` 🤷🏽‍♂️

See you in the discussions section for more discussion on this.
