### ISSUE TITLE
Columns and rows not working properly

### ISSUE THREAD

**Issue by H3m326** [flet-dev/flet#4030]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When assigning a function to the on_scroll method of a column or a row, it throws a 'KeyError', and, when trying to set a specific height and width to a column and a row respectively, without the on_scroll property, it doesn't work and the content overflows. I'm using Flet 0.23.2 with visual studio code and python 3.12..2,

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page:ft.Page):

    def on_scroll(e:ft.OnScrollEvent):
        print(e.data)

    column_on_scroll = ft.Column(
        height = 300,
        on_scroll = on_scroll, 
        scroll = ft.ScrollMode.ALWAYS,
        controls = [
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
        ] 
    )

    column_height = ft.Column(
        height = 200,
        controls = [
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
            ft.Container(width=100, height=100, bgcolor=ft.colors.RED),
        ] 
    )

    page.add(
        ft.Row([
            column_on_scroll,
            column_height
        ])
        
    )

if __name__ == '__main__':
    ft.app(target=main)
```

</details>

### To reproduce

Run the code as a desktop app  and scroll the column, it gaves an error

### Expected behavior

Executing the function that is assigned to the on_scrolled method, and when a height is set the content shuldnt overflow, or should it?

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Please upgrade your Flet version to the latest and retry.
