### ISSUE TITLE
can on_click pass param?

### ISSUE THREAD

**Issue by liziliang123** [flet-dev/flet#405]
from time import sleep
import flet
from flet import ListView, Page, Text ,ElevatedButton

def main(page: Page):
    page.title = "Auto-scrolling ListView"

    lv = ListView(expand=1, spacing=10, padding=20, auto_scroll=True)

    count = 1

    page.add(lv)

    for i in range(0, 60):
        sleep(1)
        lv.controls.append(ElevatedButton('按钮',on_click=test_click))
        count += 1
        page.update()

def test_click():
    print('测试')

flet.app(target=main)

if i pass param for test_click ,  it will go wrong

**Comment by modaye** [comment]
Yes, you can

1. Anonymous function
```python
def my_callback(event, x):
    print(event, x)
ElevatedButton('按钮',on_click=lambda event: my_callback(event, "click"))
```
2. Partial function
```python
def my_callback(event, x):
    print(event, x)
from functools import partial

test_click = partial(my_callback, x="click")
ElevatedButton('按钮',on_click=test_click)
```
3. Callable class instance
```python
class TestClick:
    def __init__(self, *args, **kwargs):
        self.args = args
        self.kwargs = kwargs

    def __call__(self, event):
        print(event, self.args, self.kwargs)
ElevatedButton('按钮',on_click=TestClick("click"))
```

**Comment by FeodorFitsner** [comment]
You can use `ElevatedButton.data` property to put arbitrary object and then read it in event handler:

```python
ElevatedButton('按钮',on_click=test_click, data=<something>)
```

and then:

```python
def test_click(e):
    something = e.control.data
```

**Comment by FeodorFitsner** [comment]
Use https://github.com/flet-dev/flet/discussions to post questions like this.

**Comment by liziliang123** [comment]
OK，thanks
