### ISSUE TITLE
Add Margin Into Badge Control

### ISSUE THREAD

**Issue by Siva-Rajan-R** [flet-dev/flet#4064]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Could you please add a margin parameter in Badge control , because if i need to change the position of the badge there is no margin property.

**Comment by ndonkoHenri** [comment]
It has no margin property. You can optionally wrap it in a `Container`, which has it.

**Comment by Siva-Rajan-R** [comment]
@ndonkoHenri ,
Ohh okk thank you for you response 😁
