### ISSUE TITLE
flet build apk --split-per-abi, Dose't Work, Becouse ndk default configure!

### ISSUE THREAD

**Issue by omamkaz** [flet-dev/flet#4076]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Conflicting configuration : 'armeabi-v7a,arm64-v8a,x86_64' in ndk abiFilters cannot be present when splits abi filters are set : armeabi-v7a,x86_64,arm64-v8a

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

not set

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

ubuntu-latest

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Suggestions

Edit in `build.gradle` file to clear the default **NDK** configured to let Flutter split APKs per abi into multiple APKs, when the developer sets `--split-per-abi`

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Please provide the exact command you are running.

**Comment by FeodorFitsner** [comment]
Close as dup of #4041
