### ISSUE TITLE
couldn't locate 'out.log'

### ISSUE THREAD

**Issue by jessic-cmd** [flet-dev/flet#4088]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hello, I can run the application normally using `flet run main.py`, but when I package the application using `flet build windows` and double-click main.exe, it crashes. 

Where can I check the error log? 

I tried to find the out.log file, but I couldn't locate it.

### Code sample

<details open><summary>Code</summary>

```python
flet build windows
```

</details>

### To reproduce

no

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.241

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

**Comment by tanmay-bhatgare** [comment]
Try `flet build windows -vv`, this will provide enough info for your build command.

**Comment by FeodorFitsner** [comment]
What do you have in `requirements.txt`?

**Comment by jessic-cmd** [comment]
> requirements

Thank you for your reply. I found the issue; it was a Windows system execution permissions problem. I wrote a txt file to the C drive, and the packaged exe file crashed due to lacking administrator execution permissions. However, when run as an administrator, the exe file opens normally without crashing.

**Comment by jessic-cmd** [comment]
> What do you have in `requirements.txt`?

Thank you for your reply. I found the issue; it was a Windows system execution permissions problem. I wrote a txt file to the C drive, and the packaged exe file crashed due to lacking administrator execution permissions. However, when run as an administrator, the exe file opens normally without crashing.
