### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'window' in Flet Python latest version

### ISSUE THREAD

**Issue by Bukmopbl4** [flet-dev/flet#4099]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

#### Description:
When using the latest version of Flet with Python, I encounter a blank window on Windows, macOS, and in the browser builds. The issue arises when following the new syntax for setting window properties, as suggested by the recent version update.

For example, the following new syntax:

```python
page.window.width = 320
page.window.height = 800
page.window.resizable = False
```

Results in the error:
```
AttributeError: 'Page' object has no attribute 'window'
```

This error occurs during builds on Windows, macOS, and the browser.

Interestingly, if I revert back to the deprecated syntax:

```python
page.window_width = 320
page.window_height = 800
page.window_resizable = False
```

The application builds and works correctly across all platforms.

#### Actual Behavior:
The build fails with the following error:
```
AttributeError: 'Page' object has no attribute 'window'
```

Reverting to the deprecated syntax resolves the issue.

#### Environment:
- Flet version: 0.24.1
- Platforms tested: Windows, macOS, Browsers

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

1. Use the latest version of Flet.
2. Replace old window property settings with the new `page.window` syntax as recommended.
3. Build the project for Windows, macOS, or browser.
4. Observe the blank window and check the console for the `AttributeError`.

### Expected behavior

The new `page.window` syntax should work correctly and apply the window properties as expected, without throwing an `AttributeError`.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Macos 15.0

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

The issue seems to affect builds on all platforms. It appears that the new syntax isn't recognized or properly implemented in the current version.

**Comment by ndonkoHenri** [comment]
If it shows this error, it simply means you are not using the latest version. 0.24.1 has been released a month ago, and no one has mentioned this issue before.

Create a new virtual environment and retry; I can't really tell where exactly the issue is...

Also, can you see any deprecation warning when using the old syntax when on your 0.24.1? If yes, please share it here; else it is a confirmation that you are not on 0.24.1.

**Comment by Bukmopbl4** [comment]
I am currently using the latest version of Flet:

```bash
python -m pip show flet
Name: flet
Version: 0.24.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: https://flet.dev
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: 
```

In this version, when using the old syntax, I see the following warnings in the console upon running the app:

```bash
main.py:13: DeprecationWarning: window_width is deprecated in version 0.23.0 and will be removed in version 0.26.0. Use Page.window.width instead.
  page.window_width = 320
main.py:14: DeprecationWarning: window_height is deprecated in version 0.23.0 and will be removed in version 0.26.0. Use Page.window.height instead.
  page.window_height = 800
main.py:15: DeprecationWarning: window_resizable is deprecated in version 0.23.0 and will be removed in version 0.26.0. Use Page.window.resizable instead.
  page.window_resizable = False
```

Despite using the old syntax, everything works fine on Windows, web, and Mac builds.

However, when switching to the new recommended syntax, the build completes without any errors, but upon launching the app on Windows, I only see a blank window. The web build also shows a blank screen. The debugger console indicates the issue — AttributeError: 'Page' object has no attribute 'window'. I believe this is the same reason why the Windows app crashes silently, leading to a blank window.

**Comment by ndonkoHenri** [comment]
Can you please share the content of your requirements file?

**Comment by Bukmopbl4** [comment]
I realized that when creating a project through `flet create`, the `requirements.txt` file automatically lists an older version (`flet==0.22.*`). After manually updating it to the latest version, the issue with the blank window goes away.

Thanks for your time, and I hope this helps others who might encounter the same problem!
