### ISSUE TITLE
How to create packages and plugins for flet?

### ISSUE THREAD

**Issue by lkrjangid1** [flet-dev/flet#41]

**Comment by FeodorFitsner** [comment]
Well, it's not like you are able to create packages/plugins for Flutter, but using Python. However, you can make reusable "controls" (or "components") in Python: https://flet.dev/docs/getting-started/python#user-controls

**Comment by FeodorFitsner** [comment]
I'm going to close this issue. If you feel it needs further discussion please start a new thread here: https://github.com/flet-dev/flet/discussions
