### ISSUE TITLE
TextField. Property height doesn't work properly

### ISSUE THREAD

**Issue by ClearSafety** [flet-dev/flet#4106]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

TextField has the properties height and width that do not figure in the documentation.
There's an issue with the property height, that works only to decrease the height of the field. 
The solution of the discussion 2345 is not very good, because it suggests you one uses the min_line to increase the field hight. It works, but it's not possible to have the control of the size in pixels, for instance.
Currently, as I could see, there's no way to have a single line field with its height customized in pixels by the developer. 

https://github.com/flet-dev/flet/discussions/2345

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    
    page.add(
        ft.TextField(
            height=100,
            width=100,
        )
    )

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

</details>

### To reproduce

1. Run the reprocode

### Expected behavior

It was expected the field increase its height size according to the value passed to the 'height' property.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 Pro

### Flet version

0.24.1

### Regression

No, it isn't

### Suggestions

Add the properties 'width' and 'height' to the documentation.
Enable the 'height' property to increase the size of the field, the same as it's possible with the CupertinoTextField.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ClearSafety** [comment]
@FeodorFitsner , even using now the Version: 0.25.0.dev3614, I'm afraid the 'height' property of the control TextField is still not working. It only increases the area occupied by the TextField in the page. The same behaviour of the margin applied in the botton. 

![textfield](https://github.com/user-attachments/assets/e8e706fa-e245-477b-872f-f40e32e940cd)

**Comment by ndonkoHenri** [comment]
@ClearSafety here s an example:
