### ISSUE TITLE
Database is cleared once you add the data for the very first time locally and close the APK

### ISSUE THREAD

**Issue by prajaktamogare** [flet-dev/flet#4114]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When you compile the apk using **flet build apk** command and you have database stored locally. For a very first time if you add something to the database or a log file and display it in the App it is visible once you close the app from the background task/ by comming back  the data gets vanished. From the second time it works similessly. This happens mostly on android version 11,12,14 but works without any issue sometimes on android version 13.

If we run same code on windows it will run without any issue but once it is converted to APK the data gets cleared for very first time

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

1. Generate an APK by using flet build apk command
2. Make sure that this APK has data stored locally in a log file or sqlite database and display it somewhere.
3. Now add your data into DB by entering data into textfield and saving it into DB and immediately displaying it on same page or create alog file and display it on another page.
4. It will be visible to you. Now go back and close the app
5. Now open it again... The data should not be visible.
6. It is a crucial on as the clients data is really important..

### Expected behavior

Data should not be cleared even if I close the APk

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

Flet 23.0.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by OwenMcDonnell** [comment]
Have you tried these steps on flet v0.24.1?

**Comment by prajaktamogare** [comment]
Yes, Still faced the same issue..

**Comment by FeodorFitsner** [comment]
Flet pre-release might solve data location issue: https://flet.dev/blog/flet-new-packaging-pre-release#data-and-temp-directories-for-the-app
