### ISSUE TITLE
unrequested apk/aab permissions android.permission.FOREGROUND_SERVICE_LOCATION

### ISSUE THREAD

**Issue by devcheny** [flet-dev/flet#4118]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

The apk/aab I create with flet=0.24.1 and flet=0.25.* include the following permissions without me requesting them, so I can't upload the app to Google Play because I can't prove the use of those permissions.

`    <uses-permission android:name="android.permission.INTERNET"/>` 
`     <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>` 
`     <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>` 
`     <uses-permission android:maxSdkVersion="32" android:name="android.permission.READ_EXTERNAL_STORAGE"/>` 
`     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` 
`     <uses-permission android:name="android.permission.RECORD_AUDIO"/>` 
`     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` 
`     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>` 
`     <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>` 
`     <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION"/>` 
`     <uses-permission android:name="android.permission.WAKE_LOCK"/>` 
`     <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

No error log.

### Expected behavior

The application should not request any special permissions.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![5766910897271456685](https://github.com/user-attachments/assets/0179acd6-b8c7-448e-a154-24deeb8b8d99)

</details>

### Operating System

Windows

### Operating system details

windows 10 and android 13

### Flet version

0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

This error appears since version 0.23.0 in 0.22.1 it only requests the microphone permission which it should not request either.

**Comment by FeodorFitsner** [comment]
Managing permissions is now available with the pre-release version of Flet: https://flet.dev/blog/flet-new-packaging-pre-release (and [here about permissions](https://flet.dev/blog/flet-new-packaging-pre-release#permissions))
