### ISSUE TITLE
How to set app name when build apk and aab

### ISSUE THREAD

**Issue by jaychia0418** [flet-dev/flet#4125]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

build apk with this command
flet build --project "ABC Def" --product abcdef --org abcd.feg --build-number 1 --build-version 1.0.0 --template-dir C:/Users/abcd/flet-build-template-main apk

install apk and the app name is abc_def
the name should be ABC Def

### Code sample

flet build --project "ABC Def" --product abcdef --org abcd.feg --build-number 1 --build-version 1.0.0 --template-dir C:/Users/abcd/flet-build-template-main apk

### To reproduce

1. Build apk
3. install apk
4. the app name wrong

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Why close?

**Comment by jaychia0418** [comment]
Has found solution
change the android: label can change the app name
![image](https://github.com/user-attachments/assets/7b4a87ae-c011-4c5b-8d1a-9713a92356f8)

**Comment by FeodorFitsner** [comment]
Right, but how did you do that with `flet build`, copied template?

**Comment by jaychia0418** [comment]
yes, I download this 
https://github.com/flet-dev/flet-build-template

**Comment by FeodorFitsner** [comment]
OK, it should be possible to fix via `flet build` though.

**Comment by FeodorFitsner** [comment]
Wait a second, I see it's already using `product-name` for filling `label` value: https://github.com/flet-dev/flet-build-template/blob/0.24.1/%7B%7Bcookiecutter.out_dir%7D%7D/android/app/src/main/AndroidManifest.xml#L24

which is correct. `--product-name` is "project display name that is shown in window titles and about app dialogs".

You command should be changed to:

```
flet build --project abcdef --product"ABC Def"
```

**Comment by jaychia0418** [comment]
maybe my template is old version
