### ISSUE TITLE
page.window.frameless = True After that, the window does not have rounded corners

### ISSUE THREAD

**Issue by yst-one** [flet-dev/flet#4130]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

![image](https://github.com/user-attachments/assets/c358f231-d869-40df-87be-e16c150dcefd)

### Code sample

import flet as ft

def main(page: ft.Page):
    page.window.frameless = True
    page.window.width = 320
    page.window.height = 480
    page.theme_mode= ft.ThemeMode.SYSTEM

    page.padding= 0
    page.add(
        ft.WindowDragArea(content= ft.Container(border_radius=20),expand=True),
        ft.IconButton(ft.icons.CLOSE, on_click=lambda _: page.window.close())
    )
    page.update()

ft.app(target=main, assets_dir="assets")

### To reproduce

aa

### Operating System

Windows

### Operating system details

win11

### Flet version

0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

**Comment by OwenMcDonnell** [comment]
Can you share with which version of flet this used to work and share a screenshot of the resulting window?

**Comment by JasonSettings** [comment]
Hello! May I chime in?
I opened an issue some time ago and it was closed, but the issue wasn’t fixed. It was 9 months ago. I didn’t reply because I missed the response somehow and forgot about it, terribly sorry. Issue number was #1110.
I think we’re dealing with the same thing here.


Here is the code to reproduce
```
import flet as ft


def main(page: ft.Page):
    page.window.width = 450
    page.window.height = 450
    page.window.bgcolor = ft.colors.TRANSPARENT
    page.bgcolor = ft.colors.TRANSPARENT
    page.window.frameless = True
    page.window.center()
    
    def open_dialog(e):
        page.dialog = ft.AlertDialog(
            modal=True,
            title=ft.Text('Alert Dialog'),
            content=ft.Text('This is an alert dialog'),
            actions=[
                ft.TextButton('OK', on_click=close_dialog),
                ],
            )
        page.dialog.open = True
        page.update()
    
    def close_dialog(e):
        page.dialog.open = False
        page.update()
    
    def close_app(e):
        page.window.close()
    
    page.add(
        ft.Container(
            content=ft.Column(
                controls=[
                    ft.ElevatedButton('Open dialog', on_click=open_dialog),
                    ft.ElevatedButton('Close app', on_click=close_app),
                    ],
                alignment=ft.MainAxisAlignment.CENTER,
                spacing=10,
                ),
            bgcolor=ft.colors.SURFACE_CONTAINER_HIGHEST,
            border_radius=30,
            alignment=ft.alignment.center,
            expand=True,
            ),
        )


ft.app(target=main)
```

How it looks on my end. Using python 3.12.6 and flet 0.24.1.

![frameless_alert_dialog](https://github.com/user-attachments/assets/5d5f5939-3707-4d4d-9abf-7860ba138b0f)
