### ISSUE TITLE
Where is flet-runtime 0.25.0.dev3514

### ISSUE THREAD

**Issue by pandayummy** [flet-dev/flet#4139]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

```
flet                                     0.25.0.dev3514
flet-cli                                 0.25.0.dev3514
flet-core                                0.25.0.dev3514
flet-desktop                             0.25.0.dev3514
flet-runtime                             0.25.0.dev3382
flet-web                                 0.25.0.dev3514
```

https://pypi.org/project/flet-runtime/#history
I think there should be a flet-runtime 0.25.0.dev3514 ?

![image](https://github.com/user-attachments/assets/0fa1a81f-4eb3-443a-95d6-7db289d2ee2a)

**Comment by kentbull** [comment]
I am hitting a related issue with `poetry lock && poetry install` showing the error message `Unimplemented comparison of constraints`

**Comment by kacper-the-programmer** [comment]
`flet-runtime` has been replaced by `flet-desktop`

**Comment by pandayummy** [comment]
Thank you.

**Comment by FeodorFitsner** [comment]
See here: https://flet.dev/blog/flet-new-packaging-pre-release#new-packages-structure

**Comment by pandayummy** [comment]
![image](https://github.com/user-attachments/assets/6b8bd730-2f6e-4ea6-80f3-46976e6a5078)

Sucessfully installed.
