### ISSUE TITLE
IPA build fails with `pod install error`

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#4168]
```
Running pod install...                                              3.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies
Error: The plugin "serious_python_darwin" requires a higher minimum iOS deployment version than your application is targeting.

To build, increase your application's deployment target to at least 13.0 as described at https://flutter.dev/to/ios-deploy
Error running pod install
``` 

Complete logs [here](https://github.com/ndonkoHenri/test-flet-github-actions/actions/runs/11345807151/job/31553507670#step:6:180 ).

To fix it, I had to modify the ios-platform constant in `ios/Podfile` (in a custom-build-template) from `'12.0'` to `'13.0'` as requested in the error message.

We need to update the default build template to this version. Also, will be nice to have a property for this in the `pyproject.toml` (https://github.com/flet-dev/flet/pull/4166)

**Comment by FeodorFitsner** [comment]
Template has been updated.
