### ISSUE TITLE
`AudioRecorder` control

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#419]
https://pub.dev/packages/record

**Comment by hololeo** [comment]
eveytime you add a feature here i get excited cause i know its gonna happen ;)

**Comment by Aakashagr** [comment]
Hi Feodor, I am eagerly waiting for this feature. Can you please let me know if there are plans to release it soon?

**Comment by AyberkAtalay0** [comment]
It's beyond amazing, is there an estimated release date?

**Comment by apiad** [comment]
Hi! Thanks for your incredible work. Flet has brought happiness back into application development for me.

I really need this feature and I'd love to give it a shot if no one is currently working on it. I have reasonable experience in web development with Python and some experience in Flutter. If you can point me to some reference implementation of a similar control, to understand how the back and forth between the Python and the Flutter side works, or any documentation.

Cheers!

**Comment by plugeit** [comment]
@apiad here you go https://www.youtube.com/watch?v=7ncWtV-8gis&feature=youtu.be

**Comment by apiad** [comment]
Awesome, thanks for the pointer. I'll check asap.
