### ISSUE TITLE
Not able to use P4A  jniLibs

### ISSUE THREAD

**Issue by gunaNeelamegam** [flet-dev/flet#4195]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Im using 0.25.0.dev3526 not able to use the P4A jniLibs, before its works fine

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

while running flet build apk

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

linux 

### Flet version

0.25.0.dev3526

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by kacper-the-programmer** [comment]
new `flet build` DOES NOT depend on Kivy's P4A anymore, so you can't use `PyJNIus`
since new `flet build` is based on Beeware's toolchain you can probably call Java/Kotlin functions directly from Python, see[here](https://chaquo.com/chaquopy/doc/current/python.html)

**Comment by FeodorFitsner** [comment]
Correct, it doesn't depend on p4a anymore, but it's not exactly using Beeware's toolchain as well. Python for mobile is now a part of Python 3.13 and backported to 3.12 and below. However, as Beeware and Flet are following the same packaging "standard" their pre-built binary packages should be interchangeable, theoretically.

Is there a separate lib for calling Java/Kotlin functions from Python?
