### ISSUE TITLE
Error to load an app: MissingPluginException

### ISSUE THREAD

**Issue by antoniofonseca** [flet-dev/flet#42]
After installing Flet support through the Ubuntu 22.04 LTS PIP, every attempt to load an application with `python3 app_name.py` just loads an empty window with the loading in progress icon and no content. The error message below is displayed.

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method isFocused on channel window_manager)

The webapp version always loads successfully in the browser. What am I missing?

PS: I also have Flutter installed. Could this be causing some bad behavior?

**Comment by FeodorFitsner** [comment]
Will fix that shortly!

**Comment by FeodorFitsner** [comment]
It's been fix. Upgrade Flet module to 0.1.38.
