### ISSUE TITLE
`item_height` not implemented causes Dropdown selected Option to render outside of control element if `height < item_height`

### ISSUE THREAD

**Issue by scipio-nl** [flet-dev/flet#420]

**Comment by scipio-nl** [comment]
https://user-images.githubusercontent.com/82219871/193192844-62dac2bc-ff4a-4ac2-afe7-bd5cccc96f15.mov

**Comment by FeodorFitsner** [comment]
what's the corresponding Flutter's widget property?

**Comment by scipio-nl** [comment]
itemHeight, (and maybe also iconSize)

**Comment by scipio-nl** [comment]
FYI: in the video I tried to demonstrate 2 issues:
-1- if the app window is "flat", the option list gets cut off,
and more urgent:
-2- how a selected option isn't shown due to itemHeight > Height

**Comment by FeodorFitsner** [comment]
1 - that's expected as the dropdown cannot be drawn outside the application window. Flutter dropdown is not a native OS dropdown which has its own "window" - it's just "painted" on a canvas.
2 - have you tried reducing Dropdown's `content_padding`?

**Comment by scipio-nl** [comment]
I'll check if I can work with `content_padding` on this matter; will report back.

**Comment by FeodorFitsner** [comment]
Thank you for the update!
