### ISSUE TITLE
flet==0.25.0.dev3526 apk "Android" error Pillow PIL "libjpeg.so" not found

### ISSUE THREAD

**Issue by jtoror** [flet-dev/flet#4200]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Apk "Android" error Pillow PIL ImportError: dlopen failed: library "libjpeg.so" not found

### Code sample

<details open><summary>Code</summary>

```python

pyproject.toml

[project]
name = "amy_app"
version = "1.0.0"
description = "My first Flet project"
authors = [
    {name = "John Smith", email = "john@email.com"}
]

dependencies = [
    "flet==0.25.0.dev3526",
    "numpy",
    "pandas",
    "imagekitio",
    "supabase",
    "Pillow",
    "libjpeg",
    "plotly"
]

# requires-python = ">=3.12"

icon = "assets/icon"

[tool.flet.android.permission] # --android-permissions
"android.permission.INTERNET" = true
"android.permission.CAMERA" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true
"android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = true

main.py

import os
import flet as ft
import numpy as np
# import pandas as pd
from imagekitio import ImageKit
from supabase import create_client, Client
from PIL import Image
import plotly.express as px


def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(
        value="0", text_align=ft.TextAlign.RIGHT, width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,
        )
    )


ft.app(main)


```

</details>

### To reproduce

Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/data/user/0/com.flet.amy_app/files/flet/app/main.py", line 7, in <module>
    from PIL import Image
  File "/data/user/0/com.flet.amy_app/files/flet/python_site_packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: dlopen failed: library "libjpeg.so" not found

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/95aef0ae-7f99-4b3f-a430-b6853d84c2b1)

</details>

### Operating System

Linux

### Operating system details

Kubuntu 24.04

### Flet version

0.25.0.dev3526

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by liuguanfei** [comment]
I'm having the same problem.

**Comment by jtoror** [comment]
Hi @FeodorFitsner , what happened with this? Has it been resolved?

**Comment by FeodorFitsner** [comment]
It's been fixed.
