### ISSUE TITLE
flet==0.25.0.dev3526 "Android" Apk does not show the application icon, it shows a black image

### ISSUE THREAD

**Issue by jtoror** [flet-dev/flet#4201]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

flet==0.25.0.dev3526 "Android" Apk does not show the application icon, it shows a black image, both on physical and virtual devices.

### Code sample

<details open><summary>Code</summary>

```python

[project]
name = "amy_app"
version = "1.0.0"
description = "My first Flet project"
authors = [
    {name = "John Smith", email = "john@email.com"}
]

dependencies = [
    "flet==0.25.0.dev3526"
]

# requires-python = ">=3.12"

icon = "assets/icon"

[tool.flet.android.permission] # --android-permissions
"android.permission.INTERNET" = true
"android.permission.CAMERA" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true
"android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = true

main.py

import os
import flet as ft

def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(
        value="0", text_align=ft.TextAlign.RIGHT, width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,
        )
    )


ft.app(main)



```

</details>

### To reproduce

flet build apk

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/8dd6f466-aa60-4113-b0d3-e6c0a6215154)

</details>

### Operating System

Linux

### Operating system details

Kubuntu 24.04

### Flet version

0.25.0.dev3526

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
What kind of image do you use for the icon and does it exist in assets folder?

**Comment by FeodorFitsner** [comment]
Solved.

Configure color for adaptive background on Android.

In `pyproject.toml`:

```toml
[tool.flet.android]
adaptive_icon_background = "#ffffff" # your color
```

or use `--android-adaptive-icon-background` CLI option.
