### ISSUE TITLE
I cant use builded Flet. 

### ISSUE THREAD

**Issue by Wanna-Pizza** [flet-dev/flet#4209]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I added new attribute to page.py. "bgblur"

but when i run script i see this message:

```
    print(page.window.bgblur)
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'bgblur'
```
![image](https://github.com/user-attachments/assets/1b598d95-1311-48e8-80e5-e972ac6b3b43)

### Code sample

<details open><summary>Code</summary>

```python
class Window:
    def __init__(self, page: "Page"):
        self.page = page
        self.__alignment = None
        self.__on_event = EventHandler(lambda e: WindowEvent(e))
        self.page._add_event_handler(
            "window_event",
            self.__on_event.get_handler(),
        )

    # bgcolor
    @property
    def bgcolor(self) -> Optional[str]:
        return self.page._get_attr("windowBgcolor")

    @bgcolor.setter
    def bgcolor(self, value: Optional[str]):
        self.page._set_attr("windowBgcolor", value)

    # bgblur
    @property
    def bgblur(self) -> Optional[str]:
        return self.page._get_attr("windowBgcolor")

    @bgblur.setter
    def bgblur(self, value: Optional[str]):
        self.page._set_attr("windowBgcolor", value)    

```
![image](https://github.com/user-attachments/assets/307a1852-b382-45da-8af0-00b77bbbbbd2)

</details>

Well I DONT UNDERSTAND why its not working. What I need to do? Why its not using builded flet. 

### To reproduce

Look to your instructions. I get same error every time. 

### Expected behavior

I need to work it 

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Windows 11

### Flet version

0.23.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by OwenMcDonnell** [comment]
Have you followed the steps [here](https://github.com/flet-dev/flet/blob/main/CONTRIBUTING.md) to build a local version of flet with your changes to the `Window` class?

**Comment by Wanna-Pizza** [comment]
> Have you followed the steps [here](https://github.com/flet-dev/flet/blob/main/CONTRIBUTING.md) to build a local version of flet with your changes to the `Window` class?

Uhm. I dont what exactly I did. But it works now :)
