### ISSUE TITLE
Implement useful magic methods in Controls (ex: `__contains__`)

### ISSUE THREAD

**Issue by theN1C1** [flet-dev/flet#4217]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I would like that in such elements as row, columns and so on it would be possible:
1. add an element as in `page.add()
2. use `__contains__ `method
```python
column = ft.Column()

column.add(
    text
)

print(text in column)
```

### Suggest a solution

```python
# add element in column
def add(self, control):
    self.controls.append(control)
    self.update()
```

### Additional details

This is a good way to bring the library to the same syntax, instead of using `page.add()` or `column.controls.append()`.

**Comment by ndonkoHenri** [comment]
The implementation of magic methods like `__contain__` can be done. 

Concerning `.add()` methods, I made a PR concerning it some months back (https://github.com/flet-dev/flet/pull/30539), but it implementation needs to be rediscussed.
