### ISSUE TITLE
flet not run ubuntu

### ISSUE THREAD

**Issue by MominIqbal-1234** [flet-dev/flet#4218]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

/home/momin/.flet/bin/flet-0.24.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)

```

</details>

### To reproduce

its simple code return the hello flet

### Expected behavior

i want run the app

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/9dfaf5fa-ebf5-487c-a697-db462292ac9a)

</details>

### Operating System

Linux

### Operating system details

Ubuntu 24.04.1 LTS

### Flet version

0.24.1

### Regression

No, it isn't

### Suggestions

i dont know

### Logs

<details open><summary>Logs</summary>

```console
/home/momin/.flet/bin/flet-0.24.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

</details>

**Comment by 31December99** [comment]
try this: 
https://stackoverflow.com/questions/78007193/error-while-loading-shared-libraries-libmpv-so-1-cannot-open-shared-object-fil

`
sudo apt update

sudo apt install libmpv-dev libmpv2

sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/libmpv.so.1

`

**Comment by FeodorFitsner** [comment]
or install pre-release version of Flet with `pip install flet --pre --upgrade`.
