### ISSUE TITLE
flet build apk not work 

### ISSUE THREAD

**Issue by MominIqbal-1234** [flet-dev/flet#4223]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

[03:23:09] `flutter` command is not available in PATH. Install Flutter SDK.                                                                        
Traceback (most recent call last):
  File "/home/momin/.local/bin/flet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/cli.py", line 88, in main
    args.handler(args)
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 489, in handle
    self.flutter_exe = self.find_flutter_batch("flutter")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1403, in find_flutter_batch
    self.cleanup(
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1484, in cleanup
    self.run_flutter_doctor(style=error_style)
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1489, in run_flutter_doctor
    self.status.update(
    ^^^^^^^^^^^
AttributeError: 'Command' object has no attribute 'status'

### ENV
already add flutter in env
/home/momin/.local/bin:~/development/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)

```

</details>

### To reproduce

----

### Expected behavior

return the apk for android

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/d67023c2-fba7-4686-a965-55f9619c954f)

</details>

### Operating System

Linux

### Operating system details

Ubuntu 24.04.1 LTS

### Flet version

0.25.0.dev3570

### Regression

No, it isn't

### Suggestions

i dont no

### Logs

<details open><summary>Logs</summary>

```console
momin@momin:~/code$ flet build apk
[03:23:09] `flutter` command is not available in PATH. Install Flutter SDK.                                                                        
Traceback (most recent call last):
  File "/home/momin/.local/bin/flet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/cli.py", line 88, in main
    args.handler(args)
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 489, in handle
    self.flutter_exe = self.find_flutter_batch("flutter")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1403, in find_flutter_batch
    self.cleanup(
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1484, in cleanup
    self.run_flutter_doctor(style=error_style)
  File "/home/momin/.local/lib/python3.12/site-packages/flet_cli/commands/build.py", line 1489, in run_flutter_doctor
    self.status.update(
    ^^^^^^^^^^^
AttributeError: 'Command' object has no attribute 'status'

```

</details>

**Comment by MominIqbal-1234** [comment]
i flow all the step install flutter and add env in ubuntu but then agin return this error 

[03:23:09] `flutter` command is not available in PATH. Install Flutter SDK.

**Comment by jtoror** [comment]
> i flow all the step install flutter and add env in ubuntu but then agin return this error
> 
> [03:23:09] `flutter` command is not available in PATH. Install Flutter SDK.

Use VS Code to install Flutter
[#](https://docs.flutter.dev/get-started/install/linux/android#use-vs-code-to-install-flutter)
To install Flutter using these instructions, verify that you have installed [Visual Studio Code](https://code.visualstudio.com/docs/setup/mac) 1.77 or later and the [Flutter extension for VS Code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter).

Prompt VS Code to install Flutter
[#](https://docs.flutter.dev/get-started/install/linux/android#prompt-vs-code-to-install-flutter)
Launch VS Code.

To open the Command Palette, press Control + Shift + P.

In the Command Palette, type flutter.

Select Flutter: New Project.

VS Code prompts you to locate the Flutter SDK on your computer.

If you have the Flutter SDK installed, click Locate SDK.

If you do not have the Flutter SDK installed, click Download SDK.

This option sends you the Flutter install page if you have not installed Git as directed in the [development tools prerequisites](https://docs.flutter.dev/get-started/install/linux/android#development-tools).

When prompted Which Flutter template?, ignore it. Press Esc. You can create a test project after checking your development setup.

Download the Flutter SDK
[#](https://docs.flutter.dev/get-started/install/linux/android#download-the-flutter-sdk)
When the Select Folder for Flutter SDK dialog displays, choose where you want to install Flutter.

VS Code places you in your user profile to start. Choose a different location.

Consider ~/development/

Click Clone Flutter.

While downloading Flutter, VS Code displays this pop-up notification:

Downloading the Flutter SDK. This may take a few minutes.
content_copy
This download takes a few minutes. If you suspect that the download has hung, click Cancel then start the installation again.

Once it finishes downloading Flutter, the Output panel displays.

Checking Dart SDK version...
Downloading Dart SDK from the Flutter engine ...
Expanding downloaded archive...
content_copy
When successful, VS Code displays this pop-up notification:

Initializing the Flutter SDK. This may take a few minutes.
content_copy
While initializing, the Output panel displays the following:

Building flutter tool...
Running pub upgrade...
Resolving dependencies...
Got dependencies.
Downloading Material fonts...
Downloading Gradle Wrapper...
Downloading package sky_engine...
Downloading flutter_patched_sdk tools...
Downloading flutter_patched_sdk_product tools...
Downloading windows-x64 tools...
Downloading windows-x64/font-subset tools...
content_copy
This process also runs flutter doctor -v. At this point in the procedure, ignore this output. Flutter Doctor might show errors that don't apply to this quick start.

When the Flutter install succeeds, VS Code displays this pop-up notification:

Do you want to add the Flutter SDK to PATH so it's accessible
in external terminals?
content_copy
VS Code may display a Google Analytics notice.

If you agree, click OK.

To enable flutter in all Terminal windows:

Close, then reopen all Terminal windows.
Restart VS Code.

**Comment by MominIqbal-1234** [comment]
i try this solution but not work
please you can create a google cloab link set all the dependencies in this colab and then any buddy upload the flet code and generate apk 
i think this is best solution
