### ISSUE TITLE
flet==0.25.0.dev3526 apk "Android" error cffi: Unable to build parse

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#4226]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

After building apk with cffi package and running it on Android device simulator, import cffi works but after there is "Unable to build parse" error.

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.title = "Flet libs test"

    def cffi_tests(e):
        def test_basic():
            try:
                from cffi import FFI

                page.add(ft.Text("from cffi import FFI - OK"))

                ffi = FFI()
                ffi.cdef("size_t strlen(char *str);")
                page.add(ft.Text('ffi.cdef("size_t strlen(char *str);") - OK'))
                lib = ffi.dlopen(None)
                page.add(ft.Text("ffi.dlopen(None) - OK"))
                assert lib.strlen(ffi.new("char[]", b"hello world")) == 11

                page.add(ft.Text("cffi: test_basic - OK"))
            except Exception as e:
                page.add(ft.Text(f"cffi: test_basic - error: {e}", selectable=True))

        test_basic()

    page.add(
        ft.SafeArea(
            ft.Column(
                [
                    ft.ElevatedButton("Run cffi tests", on_click=cffi_tests),
                ]
            )
        )
    )


ft.app(main)
```
pyproject.toml
```
[project]

name = "cffi_app"
version = "1.0.0"
description = ""
authors = [{name = "Flet Developer", email = "your@email.com"}]
dependencies = ["flet==0.25.0.dev3526", "cffi"]

[tool.flet]
android.adaptive_icon_background = "#ffffff"
```
</details>

### To reproduce

flet build apk
install apk on android device
click on "Run cffi tests" button

### Expected behavior

expected to see "Test OK" messages

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

15

### Flet version

0.25.0.dev3526

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
It's been fixed.
