### ISSUE TITLE
textfield for log view

### ISSUE THREAD

**Issue by yincheng8** [flet-dev/flet#4249]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I want to use textfield to create a log window for recording logs, but after recording a lot of logs, I cannot control the scrollbar of textfield. I want to know how to control it. I think there should be methods such as scoll_to-end

```python
import time

import flet as ft
from datetime import datetime


def get_now_time():
    current_time = datetime.now()
    formatted_time = current_time.strftime('%Y-%m-%d %H:%M:%S')
    return formatted_time


def main(page: ft.Page):
    page.window.center()
    page.window.width = 480
    page.window.height = 320
    page.window.resizable = False

    def btn_click(e):
        print(e)
        for i in range(20):
            log_field.value += f"{get_now_time()}......{i + 1}\n"
            time.sleep(0.3)
            log_field.focus()
            page.update()

    log_field = ft.TextField(label='write log example', min_lines=8, max_lines=8, read_only=False,
                             value='-------------------Log-------------------\n')
    page.add(log_field)
    button = ft.ElevatedButton(text='start', color='#499c54', on_click=btn_click)
    row = ft.Row(
        controls=[
            ft.Text(),
            button],
        alignment=ft.MainAxisAlignment.END
    )
    page.add(row)
    page.update()


if __name__ == '__main__':
    ft.app(target=main)
```

### Suggest a solution

maybe add a func scoll_to_end

**Comment by yincheng-a** [comment]
Thank you for your reply，I use textfield to record logs, and during the process of recording logs, I want the scrollbar of textfield to always be at the bottom, that is, after clicking the button and waiting for all logs to be added, as the logs increase, my scrollbar should also move together instead of being in its original position。
The current effect:![now](https://github.com/user-attachments/assets/40c7b5d9-14b7-4c62-97a9-c26d03ecb188)
The effect I want:
![i_want](https://github.com/user-attachments/assets/987d697e-557e-46e5-b88b-32c6a0e91f72)

**Comment by ndonkoHenri** [comment]
Set [`Column.auto_scroll`](https://flet.dev/docs/controls/column#auto_scroll) to True.

**Comment by yincheng8** [comment]
aha， How can I modify my code based on it？I think textField should also need a similar attribute，such as auto_scroll or scroll_to_end

**Comment by ndonkoHenri** [comment]
Seems like this issue doesn't have a proper fix in flutter yet. I found [some](https://stackoverflow.com/questions/43348254/automatically-scroll-multiline-textformfield-when-it-extends-the-maxlines-attrib) SO threads, but nothing concrete honestly.

Let us know if you find a solution which could be implemented.

**Comment by yincheng-a** [comment]
Look forward to your good news
