### ISSUE TITLE
Subprocess duplicates the GUI

### ISSUE THREAD

**Issue by ap4499** [flet-dev/flet#4252]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When using subprocess, the GUI is duplicated - and I cannot find a way to fix it. The issue below is on a MacOS 15 M1 Max, but I have also observed the same on Windows. 

This issue also occurs when using Multiprocessing (and ofcourse process pool executor), I have used subprocess as an example as its the simplest to create a minimal example from - but I suspect the underlying cause is the same for both given the mechanism that multiprocessing uses. 

Note, this issue is only present when the application is built when using Flet Build (when using Flet Run/ development, it does not occur).

To illustrate this, I have created two scripts, one being the main.py, the other being the subprocess which simply prints a string to the terminal, this is then picked off the pipe by main. I have included the requirements.txt but it only contains Flet (0.25.0.dev3598).

I believe that it is generally recommended to use this line when packing/building an app using other frameworks (PyInstaller if I recall), but it has no effect: 
    multiprocessing.freeze_support()

### Code sample

<details open><summary>Code</summary>

#main.py
```
import subprocess
import flet as ft
import sys
import multiprocessing


def main(page):
    text = ft.Text(value = "init")
    def click(e):
        process = subprocess.Popen([sys.executable, 'subprocess_mod.py'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        for line in process.stdout:
            output = line.decode('utf-8').strip()
            print(output)
            text.value = output
            text.update()



    button = ft.ElevatedButton("Click", on_click = click)
    page.add(text)
    page.add(button)


if __name__ == '__main__':
    multiprocessing.freeze_support()
    ft.app(target = main)
```

#subprocess_mod.py
```
print("Test!")
```

</details>

### To reproduce

Build the app using Flet Build

export PATH=$HOME/development/flutter/bin:$PATH

flet build macos --project "Demo" --product "Demo" --org "com.ABC" --company "Demo" --build-version "1.0.0"

### Expected behavior

The expected behaviour is the same that is observed when using Flet run. The GUI element text.value should update to "Test!".

However, instead, another new GUI window is launched.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/eaa6a823-42fe-41b0-9420-ce27aa935f1e)
</details>

### Operating System

macOS

### Operating system details

MacOS 15.0.1

### Flet version

flet==0.25.0.dev3598

### Regression

No, it isn't

### Suggestions

The issue is present in all 3 recent Flet's. 

Tested:
Flet==0.23.2
Flet==0.24.1
Flet==0.25.0.dev3598

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ap4499** [comment]
Not sure if you need this - but running Python 3.12.5

**Comment by ap4499** [comment]
Thank you for the reply and code - that is helpful. However, even after using your example, I still end up with a second instance of the GUI when I click the button (after using Flet Build).

The intended behaviour, is that the subprocess does something in isolation, and shouldn't affect the GUI or create a new instance. It should have its own interpreter. The only interaction should be indirect, where we read that print statement off of the pipe and place it in our GUI.

In your code above, I am still getting a second instance of the application launch, but I think it should just update the text to say "Test!" (as it does when running the application from terminal/Flet Run), rather than create a new instance. 

The context to this example, is that in my main development, I am performing many image operations that consume a lot of CPU time, and a sizeable amount of memory. The subprocess is passed only a tuple of images, these are then processed in isolation using a process pool. It runs via subprocess to avoid mixing the GUI and the multiprocessing environment (I have found this significantly reduces the memory footprint). There is a Pipe that has two integers that return to the main thread from the subprocess (with the Flet GUI), those two are just: [images competed] / [total images]. But again, this should be thread safe. 

In that scenario, I don't want Flet to create another instance of the GUI when it is built, I want the Flet Run behaviour where it effectively runs in the background. (this is the behaviour observed in Flet Pack and Flet Run).

When trying this with Multiprocessing directly, I found that the GUI was duplicated for x = number of virtual cores (max_workers default).

Apologies if I have I just missed something obvious here.

**Comment by FeodorFitsner** [comment]
OK, see here:

```py
process = subprocess.Popen(
            [sys.executable, os.path.join(script_dir, "subprocess_mod.py")],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
        )
```

`sys.executable` is **not** a python interpreter, but a compiled executable:

<img width="785" alt="image" src="https://github.com/user-attachments/assets/bab8bbb8-60d6-4841-9d33-85e918c3ffb9">

You *expect* it should be `/some/path/to/python`, but in reality you are starting another copy the app itself.

**Comment by FeodorFitsner** [comment]
Other words, Flet is not creating another instance of a program, *you* are creating it :)

**Comment by FeodorFitsner** [comment]
Do you have a more practical example of using `multiprocessing`? It could be required to tweak something to make it work in compiled form.

**Comment by ap4499** [comment]
> Other words, Flet is not creating another instance of a program - _you_ are creating it :)

Ahh, I have got you. Is it possible to launch the Python interpreter directly for that subprocess when using Flet? I can't seem to find it in the app cache, although I think I can see it in the .app.


and yes, I was halfway through building an example on Multiprocessing - I'll dig it out tomorrow.

**Comment by ap4499** [comment]
@FeodorFitsner 

Here is an example of the issue that I am finding with multiprocessing.

Application:
- Basic sort of the same list of numbers, but across multiple workers (processes).
- Using a multiprocessing.Queue() to pass information.
- Running the long running task using page.run_thread()
- Updating the GUI only from the main thread.


Behaviour:
- When running from terminal/ Flet Run the application behaves as expected.
- When running the .app created with Flet Build (using your latest dev build from yday, dev3598), there are two behaviours:
+ As soon as the application is launched, another GUI window appears. I believe this is when we create the Multiprocessing.queue()
+ When the actual processing starts, a window is created for each worker that is used by multiprocessing.  



#main.py
```
import flet as ft
from flet import Page, Text, ElevatedButton
from multiprocessing import Queue
import numpy as np
from concurrent.futures import ProcessPoolExecutor, as_completed


def sort_sublist(sublist):
    """Sorts a sublist of numbers."""
    return sorted(sublist)


def parallel_sort(queue_var):
    num_elements = 10_000_000  
    data = np.random.rand(num_elements).tolist()
    number_of_sorts = 20
    """Sorts a list of numbers in parallel."""

    with ProcessPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(sort_sublist, data) for _ in range(number_of_sorts)]  # Sort the same list x times
        for future in as_completed(futures):
            queue_var.put(1) 


def main(page: Page):
    page.title = "Flet Background Task Example"
    queue_var = Queue()
    text = ft.Text("Init")
    

    def update_text():
        completed = 0
        while True:
            completed += queue_var.get()
            text.value = completed
            text.update()

    def on_click(e):
        page.run_thread(parallel_sort,queue_var)
        update_text()


    page.add(
        ElevatedButton("Start Loop", on_click=on_click),
    )
    page.add(
        text
    )

if __name__ == "__main__":
    multiprocessing.freeze_support()
    ft.app(target=main)
```

#requirements.txt
```
flet==0.25.0.dev3598
numpy
```

**Comment by ap4499** [comment]
I think the reason that Multiprocessing is exhibiting the same issue as subprocess, is the one that you have identified already - the usage of sys.executable, and what that actually is for a Flet application.

> multiprocessing.set_executable(executable)
> Set the path of the Python interpreter to use when starting a child process. (By default [sys.executable](https://docs.python.org/3/library/sys.html#sys.executable) is used). 
> 

> Embedders will probably need to do some thing like:


`set_executable(os.path.join(sys.exec_prefix, 'pythonw.exe'))
`

https://docs.python.org/3/library/multiprocessing.html

**Comment by ap4499** [comment]
@FeodorFitsner - is this something that you can replicate?

**Comment by FeodorFitsner** [comment]
if you can set executable used by multiprocessing module then I think you can use the same program to run an arbitrary python script passed as an argument, instead of starting Flet app with `ft.app()`.

Have you tried seeing what's being passed in `argv` when the app is called by multiprocessing?

**Comment by FeodorFitsner** [comment]
also, just to make sure, you are aware that multiprocessing is not going to work on iOS and Android as it's impossible to spawn a new process there?

**Comment by ap4499** [comment]
> also, just to make sure, you are aware that multiprocessing is not going to work on iOS and Android as it's impossible to spawn a new process there?

Confirmed. The issue is occurring on MacOS and Windows (I'm not attempting iOS or Android)

On Windows (and as it does no harm on Mac), I use the multiprocessing.freeze_support().

**Comment by FeodorFitsner** [comment]
> But I couldn't get any args from new process even when running with a basic subprocess command.

This sounds like a real issue we could look into! Let me see if that could be easily hacked. You are on pre-release version of Flet, right?

**Comment by ap4499** [comment]
> > But I couldn't get any args from new process even when running with a basic subprocess command.
> 
> This sounds like a real issue we could look into! Let me see if that could be easily hacked. You are on pre-release version of Flet, right?

Yep, I've been using the daily builds. I just ran the above on flet==0.25.0.dev3636.

**Comment by FeodorFitsner** [comment]
OK, I've just updated a temp build template.

Run `flet build` with `--template-ref 0.25.0-dev` option and you'll be able to get `sys.argv` in your compiled Flet app.

**Comment by ap4499** [comment]
I can confirm this is working on my side - I'm getting the sys.argv through!

Thank you
