### ISSUE TITLE
flet==0.25.0.dev3526 apk "Android" error kiwisolver: dlopen failed

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#4254]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

After building apk with kiwisolver package and running it on Android device simulator, import kiwisolver fails with the following error:
dlopen failed: library "libc++_shared.so" not found: needed by /data/data/com.flet.kiwisolver_app/files/flet/python_site_packages/kiwisolver/_cext.cpython-312.so in namespace classloader-namespace

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.title = "Flet libs test"

    def kiwisolver_tests(e):
        def test_basic():
            try:

                from kiwisolver import Solver, Variable

                page.add(ft.Text("kiwisolver: import - OK"))
                x1 = Variable("x1")
                x2 = Variable("x2")
                xm = Variable("xm")

                constraints = [x1 >= 0, x2 <= 100, x2 >= x1 + 10, xm == (x1 + x2) / 2]
                solver = Solver()
                for cn in constraints:
                    solver.addConstraint(cn)

                solver.addConstraint((x1 == 40) | "weak")
                solver.addEditVariable(xm, "strong")
                solver.suggestValue(xm, 60)
                solver.updateVariables()

                assert xm.value() == 60
                assert x1.value() == 40
                assert x2.value() == 80

                page.add(ft.Text("kiwisolver: test_basic - OK"))
            except Exception as e:
                page.add(
                    ft.Text(f"kiwisolver: test_basic - error: {e}", selectable=True)
                )

        test_basic()

    page.add(
        ft.SafeArea(
            ft.Column(
                [
                    ft.ElevatedButton(
                        "Run kiwisolver tests", on_click=kiwisolver_tests
                    ),
                ]
            )
        )
    )


ft.app(main)
```
pyproject.toml:
```
[project]

name = "kiwisolver_app"
version = "1.0.0"
description = ""
authors = [{name = "Flet Developer", email = "your@email.com"}]
dependencies = ["flet==0.25.0.dev3526", "kiwisolver"]

[tool.flet]
android.adaptive_icon_background = "#ffffff"
```
</details>

### To reproduce

flet build apk
install apk on android device
click on "Run kiwisolver tests" button

### Expected behavior

Expected to see import - ok and Basic test - ok Texts

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

15

### Flet version

0.25.0.dev3526

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by MominIqbal-1234** [comment]
i try solution but not work
please you can create a google cloab link set all the dependencies in this colab and then any buddy upload the flet code and generate apk
i think this is best solution
