### ISSUE TITLE
How to implement two tabs, where one can scroll and the other cannot.

### ISSUE THREAD

**Issue by hionwi** [flet-dev/flet#4262]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

How to implement two tabs, where one can scroll and the other cannot.Now, I can only make them both scroll or stop at the same time by using page.scroll.

### Code sample

<details open><summary>Code</summary>

```python



import flet as ft


def main(page: ft.Page):
    page.scroll = ft.ScrollMode.ALWAYS
    col1 = ft.Column(
        scroll=ft.ScrollMode.ALWAYS
    )
    col2 = ft.Column()

    for i in range(30):
        col1.controls.append(ft.Text(f"item {i}"))
        col2.controls.append(ft.Text(f"item {i}"))
    page.add(
        ft.Tabs(
            tabs=[
                ft.Tab(
                    "tab 1",
                    col1

                ),
                ft.Tab(
                    "tab 2",
                    col2
                ), ]
        )
    )


ft.app(main)


```

</details>

### To reproduce

run the code

### Expected behavior

Make one tab scrollable while the other stops scrolling

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

https://github.com/user-attachments/assets/bd20ad0b-026e-445a-b1fe-426600cb09b7

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by lasifea** [comment]
It's not a problem, just add the **expand** attribute in the tabs component.
```python
import flet as ft


def main(page: ft.Page):
    # page.scroll = ft.ScrollMode.ALWAYS
    col1 = ft.Column(
        scroll=ft.ScrollMode.AUTO
    )
    col2 = ft.Column()

    for i in range(30):
        col1.controls.append(ft.Text(f"item {i}"))
        col2.controls.append(ft.Text(f"item {i}"))
    page.add(
        ft.Tabs(
            tabs=[
                ft.Tab(
                    "tab 1",
                    col1

                ),
                ft.Tab(
                    "tab 2",
                    col2
                ), ],
            expand=1,
        )
    )


ft.app(main)
```
