### ISSUE TITLE
Flet Version 0.25.0.dev3614: WARNING: Failed to write executable - trying to use .deleteme logic

### ISSUE THREAD

**Issue by ClearSafety** [flet-dev/flet#4263]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Some issues (#4095 and #3966) have been closed as solved.
To obtain the latest version of Flet, I run pip install Flet --pre -U, taking the version 0.25.0.dev3614.
However, when I try to run the app, I got the below error. This error doesn't happen when I swich back to the version 0.24.1.

ndonkoHenri suggested I open a new issue.

WARNING: Failed to write executable - trying to use .deleteme logic
Traceback (most recent call last):
File "", line 198, in run_module_as_main
File "", line 88, in run_code
File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Scripts\flet.exe_main.py", line 7, in
File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli.py", line 24, in main
flet_cli.cli.main()
File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_cli\cli.py", line 88, in main
args.handler(args)
File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_cli\commands\run.py", line 144, in handle
from flet_desktop import close_flet_view
File "C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop_init.py", line 14, in
from flet_core.utils import (
ImportError: cannot import name 'get_arch' from 'flet_core.utils' (C:\Users\RafaelOliveira\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\utils_init_.py)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
  
    page.add(
        ft.Dropdown(
            options=[
                ft.dropdown.Option(text='Option 1'),
                ft.dropdown.Option(text='Option 2'),
                ft.dropdown.Option(text='Option 3'),
                ft.dropdown.Option(text='Option 4'),
                ft.dropdown.Option(text='Option 5'),
                ft.dropdown.Option(text='Option 6'),
                ft.dropdown.Option(text='Option 7'),
                ft.dropdown.Option(text='Option 8'),
                ft.dropdown.Option(text='Option 9'),
            ],
            item_height=50, # Height of each option in the dropdown list
            max_menu_height=200, # It has no effect
        )
    )

ft.app(target=main)#, view=ft.AppView.WEB_BROWSER)
```

</details>

### To reproduce

1. Run the repro code.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11 Pro

### Flet version

0.25.0.dev3614

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Was that pre-release of flet installed before? Can you give me the output of 'pip list'?

**Comment by ClearSafety** [comment]
@FeodorFitsner 
Here you are:

Package                   Version
------------------------- ---------------
altgraph                  0.17.4
annotated-types           0.6.0
anyio                     4.3.0
arrow                     1.3.0
asttokens                 2.4.1
attrs                     23.2.0
azure-core                1.30.2
azure-storage-blob        12.22.0
beautifulsoup4            4.12.3
binaryornot               0.4.4
blinker                   1.7.0
blis                      0.7.11
bs4                       0.0.2
cachetools                5.4.0
catalogue                 2.0.10
certifi                   2023.11.17
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
colorama                  0.4.6
comm                      0.2.1
confection                0.1.4
contourpy                 1.2.0
cookiecutter              2.6.0
cryptography              43.0.0
cycler                    0.12.1
cymem                     2.0.8
debugpy                   1.8.0
decorator                 5.1.1
distlib                   0.3.8
dnspython                 2.4.2
email-validator           2.1.0.post1
en-core-web-sm            3.7.1
et-xmlfile                1.1.0
executing                 2.0.1
fastapi                   0.101.1
filelock                  3.13.1
Flask                     3.0.0
Flask-WTF                 1.2.1
flet                      0.25.0.dev3614
flet-cli                  0.25.0.dev3611
flet-core                 0.25.0.dev3611
flet-desktop              0.25.0.dev3611
flet-runtime              0.24.1
flet-web                  0.25.0.dev3611
fonttools                 4.49.0
google-api-core           2.19.1
google-auth               2.32.0
google-cloud-core         2.4.1
google-cloud-storage      2.18.0
google-crc32c             1.5.0
google-resumable-media    2.7.1
googleapis-common-protos  1.63.2
h11                       0.14.0
httpcore                  0.17.3
httptools                 0.6.1
httpx                     0.24.1
idna                      3.6
ipykernel                 6.29.0
ipython                   8.21.0
isodate                   0.6.1
itsdangerous              2.1.2
jedi                      0.19.1
Jinja2                    3.1.2
jupyter_client            8.6.0
jupyter_core              5.7.1
kiwisolver                1.4.5
langcodes                 3.3.0
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.3
matplotlib-inline         0.1.6
mdurl                     0.1.2
murmurhash                1.0.10
nest-asyncio              1.6.0
network                   0.1
numpy                     1.26.2
oauthlib                  3.2.2
openpyxl                  3.1.2
outcome                   1.3.0.post0
packaging                 23.2
pandas                    2.2.3
parso                     0.8.3
pefile                    2023.2.7
pillow                    10.2.0
pip                       24.3.1
platformdirs              4.2.0
preshed                   3.0.9
prompt-toolkit            3.0.43
proto-plus                1.24.0
protobuf                  5.27.2
psutil                    5.9.8
pure-eval                 0.2.2
pyasn1                    0.5.1
pyasn1_modules            0.4.0
pycparser                 2.21
pydantic                  2.6.2
pydantic_core             2.16.3
Pygments                  2.17.2
pyinstaller               6.9.0
pyinstaller-hooks-contrib 2024.7
pyparsing                 3.1.1
pypng                     0.20220715.0
PyQt5                     5.15.10
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.13.0
PySimpleGUI               5.0.3
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-slugify            8.0.4
pytz                      2023.3.post1
pywin32                   306
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
pyzmq                     25.1.2
qrcode                    7.4.2
repath                    0.9.0
requests                  2.31.0
rich                      13.7.1
rsa                       4.9
scapy                     2.5.0
selenium                  4.18.1
setuptools                69.1.1
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.5
spacy                     3.7.4
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
stack-data                0.6.3
starlette                 0.27.0
text-unidecode            1.3
thinc                     8.2.3
toml                      0.10.2
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.1
trio                      0.24.0
trio-websocket            0.11.1
typer                     0.9.0
types-python-dateutil     2.8.19.20240106
typing_extensions         4.9.0
tzdata                    2023.3
Unidecode                 1.3.8
urllib3                   2.1.0
uvicorn                   0.27.1
validate_email            1.3
virtualenv                20.25.1
wasabi                    1.1.2
watchdog                  4.0.1
watchfiles                0.21.0
wcwidth                   0.2.13
weasel                    0.3.4
websocket-client          1.8.0
websockets                11.0.3
Werkzeug                  3.0.1
wsproto                   1.2.0
WTForms                   3.1.1

**Comment by FeodorFitsner** [comment]
OK, try upgrading with:

```
pip install 'flet[all]' --pre --upgrade
```

**Comment by ClearSafety** [comment]
It's working now, thanks.

**Comment by trantu0210** [comment]
> OK, hãy thử nâng cấp với:
> 
> ```
> pip install 'flet[all]' --pre --upgrade
> ```

when i upgrade the package i get error, ERROR: Invalid requirement: "'flet[all]'": Expected package name at the start of dependency specifier 'flet[all]', can you help me? thanks

**Comment by ndonkoHenri** [comment]
try: `pip install 'flet[all]' -U `
