### ISSUE TITLE
Image not reload by clear control and add as new control refered to same path, but difrent image

### ISSUE THREAD

**Issue by Rzezimioszek** [flet-dev/flet#4275]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

If i have control with image and change image, clear control and make new one with same name and same path, but with new picture i still get old picture. Only way to escape it is to add image as src_base64, but it add aditional work to someting that's supost to work out of box. If i have image from example url  `https://picsum.photos/200/200?1` what i need to do to get new image without saving image , converting to base64 etc.?

```
img = ft.Image(
        src=f"/icons/icon-512.png",
        width=100,
        height=100,
        fit=ft.ImageFit.CONTAIN,
    )
```

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

img = ft.Image(
        src=f"/icons/icon-512.png",
        width=100,
        height=100,
        fit=ft.ImageFit.CONTAIN,
    )

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

v24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Please share runnable to code to reproduce the issue. Preferably use urls as source so we can run it easily.
