### ISSUE TITLE
Серый Экран(gray screen)

### ISSUE THREAD

**Issue by zodak123** [flet-dev/flet#4282]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Я даже не писал код на флет, написал основную конструкцию для запуска, до этого всё работало, но через секунду перестало и начал появляться серый экран. Не знаю что делать.  **### IN ENGLISH** (I didn't even write code on the fllet, I wrote a basic design to run it, before that everything worked, but after a second it stopped and a gray screen started appearing. I don't know what to do.) 
![image](https://github.com/user-attachments/assets/9f06f138-cccb-4f6e-8e54-ab3223bd3396)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    page.theme_mode = 'dark'
    page.title = 'Оки Оки'



ft.app(main)
```

</details>

### To reproduce

1.  Скопируйте код (Copy code)
2. Запустить код (Run code)

### Expected behavior

Должен был быть запущен черный экран и у приложения должно быть название "Оки Оки" ### **IN ENGLISH** (There should have been a black screen running and the app should have the name “Oki Oki Oki”)

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10 pro

### Flet version

Name: flet Version: 0.24.1 Summary: Flet for Python - easily build interactive multi-platform apps in Python Home-page: https://flet.dev Author: Appveyor Systems Inc. Author-email: hello@flet.dev License: Apache-2.0 Location: C:\Users\pavel\PycharmProjects\pythonProject\.venv\Lib\site-packages Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog Required-by:

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Try adding at least some control to the page:

```py
import flet as ft

def main(page: ft.Page):
    page.theme_mode = 'dark'
    page.title = 'Оки Оки'
    page.add(ft.Text("Hi!"))


ft.app(main)
```

**Comment by zodak123** [comment]
> ```python
> page.add(ft.Text("Hi!"))
> ```

Да, всё работает, спасибо большое! (Yes, everything works, thank you very much!)
