### ISSUE TITLE
Want to lock orientation of android apps

### ISSUE THREAD

**Issue by imadityacoder** [flet-dev/flet#4286]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Recently I create a todo app in flet and convert into apk. After installing apk in my android phone and when my phone rotate, **the GUI also rotate** to look **very bad** for using.

Therefore, I want a property for page to lock orientation in code.
Thanks!

**Comment by yunguangli** [comment]
good one. I need this feature too.

**Comment by ndonkoHenri** [comment]
Closing this issue as duplicate of #2694
