### ISSUE TITLE
Elevation of AppBar

### ISSUE THREAD

**Issue by fabio56** [flet-dev/flet#43]
There is no elevation propritie in AppBar

**Comment by FeodorFitsner** [comment]
Will add that shortly. Are you missing anything else in AppBar control?

**Comment by FeodorFitsner** [comment]
Update Flet to 0.1.38. There is a new `elevation` property in `AppBar` control.
To make it work though you have to switch app theme to Material 2 (default is Material 3).

The example of AppBar with a shadow:

```python
import flet
from flet import AppBar, Icon, Page, Text, colors, icons, theme

def main(page: Page):
    page.theme = theme.Theme(color_scheme_seed=colors.BLUE, use_material3=False)
    page.appbar = AppBar(
        leading=Icon(icons.PALETTE),
        leading_width=40,
        title=Text("AppBar Example"),
        elevation=10,
    )
    page.add(Text("Body!"))

flet.app(target=main)
```

**Comment by fabio56** [comment]
Good Job

**Comment by ndonkoHenri** [comment]
> To make it work though you have to switch app theme to Material 2 (default is Material 3).

If I may ask, why is it not possible with M3 please?

**Comment by FeodorFitsner** [comment]
It's like AppBar is made in M3 - `elevation` property doesn't have any effect.
