### ISSUE TITLE
Plotly_chart can't deploy

### ISSUE THREAD

**Issue by liguanlian** [flet-dev/flet#4302]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

# there is my code
import threading

import numpy as np
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import flet as ft
from flet.matplotlib_chart import MatplotlibChart
from flet.plotly_chart import PlotlyChart
matplotlib.use("svg")

def main(page: ft.Page):

    #plotly
    df = px.data.gapminder().query("continent=='Oceania'")
    fig1 = px.line(df, x="year", y="lifeExp", color="country")
    plotly_fig = PlotlyChart(fig1,visible=False, expand=True)

    #matplotlib
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [4, 5, 6])
    ply_fig = MatplotlibChart(fig,visible=True, expand=False)

    contents = ft.Container(
        width=400,height=800,content=
        ft.Column(
            scroll=ft.ScrollMode.ALWAYS,
            controls=[
                ft.Text('this is a MatplotlibChart'),
                ft.Container(ply_fig),
                ft.Text('this is a PlotlyChart'),
                ft.Container(plotly_fig),

            ]
        )

    )

    page.add(contents)

ft.app(main)

when I use ply_fig,the page  is OK, but the plotly_fig will let all disappear

![20241104102614](https://github.com/user-attachments/assets/a51c789b-5d11-4f30-8296-40a3679d1898)

![20241104102658](https://github.com/user-attachments/assets/ce2a7029-a25f-4514-987e-a464e1861c44)

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>
import threading

import numpy as np
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import flet as ft
from flet.matplotlib_chart import MatplotlibChart
from flet.plotly_chart import PlotlyChart
matplotlib.use("svg")

def main(page: ft.Page):

    # 绘制plotly图像
    df = px.data.gapminder().query("continent=='Oceania'")
    fig1 = px.line(df, x="year", y="lifeExp", color="country")
    plotly_fig = PlotlyChart(fig1,visible=False, expand=True)

    # 绘制matplotlib图像
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [4, 5, 6])
    ply_fig = MatplotlibChart(fig,visible=True, expand=False)

    contents = ft.Container(
        width=400,height=800,content=
        ft.Column(
            scroll=ft.ScrollMode.ALWAYS,
            controls=[
                ft.Text('this is a MatplotlibChart'),
                ft.Container(ply_fig),
                ft.Text('this is a PlotlyChart'),
                ft.Container(plotly_fig),
            ]
        )
    )

    page.add(contents)

ft.app(main)

### To reproduce

  # Nothing

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

window 11

### Flet version

V0.24

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by afraniofilho** [comment]
I'm not sure if I have had the same problem but the plotly graph is not shown after I build the app for windows. It works well in runtime.

**Comment by OwenMcDonnell** [comment]
So, to be clear the second image is what you get when you take the above code (which should really be re-formatted by the way) and simply change the `PlotlyChart` visible property to `True`? 
If that is the issue then it is *not* reporducible on macOS.
