### ISSUE TITLE
`Segment.tooltip` must be of type string

### ISSUE THREAD

**Issue by lasifea** [flet-dev/flet#4324]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I found that when I set the tooltip in the **Segment** component, the text displayed incorrectly, and the same issue also exists in other components, such as the **BarChartRod** component. In version **0.23.2**, this issue will not occur. (From machine translation, please understand if the expression is inaccurate.)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.window.width = 500
    page.window.height = 300

    segments = [ft.Segment('0', icon=ft.Icon(ft.icons.LOOKS_ONE), label=ft.Text('Dog', size=16), tooltip='a dog'),
                ft.Segment('1', icon=ft.Icon(ft.icons.LOOKS_TWO), label=ft.Text('Cat', size=16), tooltip='一只猫'),
                ft.Segment('2', icon=ft.Icon(ft.icons.LOOKS_3), label=ft.Text('Bird', size=16), tooltip=ft.Tooltip('一只鸟', padding=20, border_radius=10))]
    segment_btn = ft.SegmentedButton(segments=segments, selected={'0'}, selected_icon=ft.Icon(ft.icons.CHECK))
    page.add(segment_btn)


if __name__ == '__main__':
    ft.app(main)

```

</details>

### To reproduce

After running, please notice the tooltip of the button.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]
![image](https://github.com/user-attachments/assets/c2e7440e-33eb-44db-9d0f-99a75d18a86f)

</details>

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

There may still be some components that have the same issue, but I haven't encountered them yet.

**Comment by ndonkoHenri** [comment]
Two ways to display a tooltip in the `Segment`:
- set it's `tooltip` property to a `string`
- set the `tooltip` property of its `label` to a `string` or `Tooltip` object

Example:
```python
import flet as ft


def main(page: ft.Page):
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    page.add(
        ft.SegmentedButton(
            selected={"0"},
            selected_icon=ft.Icon(ft.icons.CHECK),
            segments=[
                ft.Segment(
                    value="0",
                    icon=ft.Icon(ft.icons.LOOKS_ONE),
                    label=ft.Text("I am Text", size=16),
                    tooltip="tooltip from text",
                ),
                ft.Segment(
                    value="2",
                    icon=ft.Icon(ft.icons.LOOKS_3),
                    label=ft.Text(
                        "I am Class",
                        size=16,
                        tooltip=ft.Tooltip(
                            message="tooltip from class",
                            padding=3,
                            border_radius=10,
                            gradient=ft.LinearGradient(
                                colors=[ft.colors.RED, ft.colors.BLUE]
                            ),
                        ),
                    ),
                ),
            ],
        )
    )


ft.app(main)
```

**Comment by lasifea** [comment]
OK, I'm watting for the next version of Flet. Thanks!
