### ISSUE TITLE
Flutter: Clean up warnings

### ISSUE THREAD

**Issue by sh1l0n** [flet-dev/flet#433]
**Description**

Some Flutter warnings appear when load the project in VSCode using the default linter

**Describe the results you received:**

![Screenshot 2022-10-03 at 22 03 22](https://user-images.githubusercontent.com/11474367/193668859-c89b4e90-127f-4c8a-8776-384febfebee6.png)

**Describe the results you expected:**
0 warnings 

**Flet version (`pip show flet`)**:

```
0.1.60
```

**Operating system**:
```
macOS
12.3.1
```

**Additional environment details:**
```bash
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.3.1 21E258 darwin-arm, locale
    en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by FeodorFitsner** [comment]
It should be fixed now.
