### ISSUE TITLE
ERROR WHEN: pip install flet==0.25.0.dev3704

### ISSUE THREAD

**Issue by YasseenAlhusammi** [flet-dev/flet#4338]
(venv) PS E:\pythonProject54> pip install flet==0.25.0.dev3704
Collecting flet==0.25.0.dev3704
  Using cached flet-0.25.0.dev3704-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: httpx in e:\pythonproject54\venv\lib\site-packages (from flet==0.25.0.dev3704) (0.27.2)
Requirement already satisfied: oauthlib<4.0.0,>=3.2.2 in e:\pythonproject54\venv\lib\site-packages (from flet==0.25.0.dev3704) (3.2.2)
Requirement already satisfied: repath<0.10.0,>=0.9.0 in e:\pythonproject54\venv\lib\site-packages (from flet==0.25.0.dev3704) (0.9.0)
Requirement already satisfied: six>=1.9.0 in e:\pythonproject54\venv\lib\site-packages (from repath<0.10.0,>=0.9.0->flet==0.25.0.dev3704) (1.16.0)
Requirement already satisfied: anyio in e:\pythonproject54\venv\lib\site-packages (from httpx->flet==0.25.0.dev3704) (4.6.2.post1)
Requirement already satisfied: certifi in e:\pythonproject54\venv\lib\site-packages (from httpx->flet==0.25.0.dev3704) (2024.8.30)
Requirement already satisfied: httpcore==1.* in e:\pythonproject54\venv\lib\site-packages (from httpx->flet==0.25.0.dev3704) (1.0.6)
Requirement already satisfied: idna in e:\pythonproject54\venv\lib\site-packages (from httpx->flet==0.25.0.dev3704) (3.10)
Requirement already satisfied: sniffio in e:\pythonproject54\venv\lib\site-packages (from httpx->flet==0.25.0.dev3704) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in e:\pythonproject54\venv\lib\site-packages (from httpcore==1.*->httpx->flet==0.25.0.dev3704) (0.14.0)    
Using cached flet-0.25.0.dev3704-py3-none-any.whl (530 kB)
Installing collected packages: flet
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following d
ependency conflicts.
flet-cli 0.25.0.dev3673 requires flet==0.25.0.dev3673, but you have flet 0.25.0.dev3704 which is incompatible.
Successfully installed flet-0.25.0.dev3704

**Comment by FeodorFitsner** [comment]
can you give me `pip list`?

**Comment by YasseenAlhusammi** [comment]
(venv) PS E:\pythonProject54> pip list
Package               Version
--------------------- --------------
anyio                 4.6.2.post1   
arrow                 1.3.0         
binaryornot           0.4.4         
certifi               2024.8.30     
chardet               5.2.0         
charset-normalizer    3.4.0         
click                 8.1.7         
colorama              0.4.6         
cookiecutter          2.6.0         
flet                  0.25.0.dev3704
flet-cli              0.25.0.dev3673
h11                   0.14.0        
httpcore              1.0.6         
httpx                 0.27.2        
idna                  3.10          
Jinja2                3.1.4
markdown-it-py        3.0.0
MarkupSafe            3.0.2
mdurl                 0.1.2
oauthlib              3.2.2
packaging             24.2
pip                   24.3.1
Pygments              2.18.0
pypng                 0.20220715.0
python-dateutil       2.9.0.post0
python-slugify        8.0.4
PyYAML                6.0.2
pyzbar                0.1.9
qrcode                7.4.2
repath                0.9.0
requests              2.32.3
rich                  13.9.4
six                   1.16.0
sniffio               1.3.1
text-unidecode        1.3
toml                  0.10.2
types-python-dateutil 2.9.0.20241003
typing_extensions     4.12.2
urllib3               2.2.3
watchdog              4.0.2

**Comment by FeodorFitsner** [comment]
OK, upgrade to the latest:

```
pip install flet==0.25.0.dev3708
```
