### ISSUE TITLE
Icon rotation doesn't work with flet-0.25.0.dev3711

### ISSUE THREAD

**Issue by azhago** [flet-dev/flet#4349]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Icon rotation doesn't work anymore with flet 0.25
IconButton and other controls are OK

### Code sample

<details open><summary>Code</summary>

flet 0.24.1 : 
```python
import flet as ft
import math


def main(page: ft.Page):
    page.add(
        ft.Icon(
            name=ft.icons.FAVORITE,
        ),
        ft.Icon(
            name=ft.icons.FAVORITE,
            size=60,
            rotate=ft.Rotate(0.5*math.pi)
        ),
    )
    


ft.app(target=main)
```

flet-0.25.0.dev3711 : 
```python
import flet as ft
import math


def main(page: ft.Page):
    page.add(
        ft.Icon(
            name=ft.Icons.FAVORITE,
        ),
        ft.Icon(
            name=ft.Icons.FAVORITE,
            size=60,
            rotate=ft.Rotate(0.5*math.pi)
        ),
    )

ft.app(target=main)
```
</details>

### To reproduce

Nothing particular : 
With the same code, icon is rotated with flet 0.24.1 and lower, not rotated with 0.25

### Expected behavior

Icon rotate..

### Screenshots / Videos

<details open>
<summary>Captures</summary>

0.24.1 : 
![image](https://github.com/user-attachments/assets/620d5cd8-c867-4cd7-8ecf-73837665cb68)

flet-0.25.0.dev3711
![image](https://github.com/user-attachments/assets/25a13b91-3de3-4831-86cf-06b201c28312)

</details>

### Operating System

Windows

### Operating system details

windows 11 24H2

### Flet version

flet-0.25.0.dev3711

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Muddassir-Farooq-official** [comment]
There is a lot of issues we are facing after 0.24.1
