### ISSUE TITLE
content property not in Badge Control

### ISSUE THREAD

**Issue by Siva-Rajan-R** [flet-dev/flet#4350]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Where is the content property in Badge control i used it in previous version flet==0.24.1 but i upgraded to flet==0.25.0.dev3717 the content property is gone.How to add Icon on it 

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

1.contetn propery was not in Badge control 
2.provide a content property or similar property to add a Icon

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

10

### Flet version

flet==0.25.0.dev3717

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

It worked on previous version flet 0.24.1

**Comment by InesaFitsner** [comment]
In Flet 0.25 we re-worked Badge so that it is no more a Flet control and is from now on a simple Python dataclass. The `badge` property (available in almost all controls) now supports both strings and Badge objects.

Example of usage:
```
import flet as ft


def main(page: ft.Page):

    txtfield1 = ft.TextField(
        width=400, value="Default value", badge=ft.Badge(text="New")
    )

    page.bottom_appbar = ft.BottomAppBar(
        bgcolor=ft.colors.BLUE,
        shape=ft.NotchShape.CIRCULAR,
        content=ft.Row(
            controls=[
                ft.IconButton(
                    icon=ft.icons.MENU, icon_color=ft.colors.WHITE, badge=ft.Badge("1")
                ),
                ft.Container(expand=True, badge=ft.Badge("2")),
                ft.IconButton(
                    icon=ft.icons.SEARCH, icon_color=ft.colors.WHITE, badge="3"
                ),
                ft.IconButton(
                    icon=ft.icons.FAVORITE, icon_color=ft.colors.WHITE, badge="4"
                ),
            ]
        ),
    )

    page.add(ft.Row([txtfield1]))


ft.app(target=main)
```

**Comment by Siva-Rajan-R** [comment]
Thanks for your response bro😄
