### ISSUE TITLE
Flutter: Use built value serializer instead of manual serialization

### ISSUE THREAD

**Issue by sh1l0n** [flet-dev/flet#436]
**Please Describe The Problem To Be Solved**
In Flutter side
Refactor fromJson() and toJson() implementation to a standart serializer

**(Optional): Suggest A Solution**

Use https://pub.dev/packages/built_value pattern

**Comment by FeodorFitsner** [comment]
Are you going to submit PR for this issue and https://github.com/flet-dev/flet/issues/437?

**Comment by sh1l0n** [comment]
> Are you going to submit PR for this issue and #437?

for this case maybe takes sense because both will introduce built_value pattern

**Comment by FeodorFitsner** [comment]
I'm closing this issue and #437 unless you are willing to implement that.
