### ISSUE TITLE
pyrebase4 or pyrebase

### ISSUE THREAD

**Issue by Youssef3082004** [flet-dev/flet#4377]
### Discussed in https://github.com/flet-dev/flet/discussions/4375

<div type='discussions-op-text'>

<sup>Originally posted by **youssef969** November 14, 2024</sup>

hello everybody, at first I had flet project with Firebase, so I used Pyrebase lib to connect with Firebase 

so when I transformed the main file with this library it didn't transform to APK and at the same time didn't generate an error just loading without progress
so what is the solution to this problem? 
and I will upload the log file and requirements file 

python version is 3.13
flet version is 0.24.1
pyrebase4 is 4.8.0
requests is 2.32.3

</div>

**Comment by ndonkoHenri** [comment]
https://flet.dev/blog/flet-packaging-update
