### ISSUE TITLE
MASKs input Text_Field with bug

### ISSUE THREAD

**Issue by VictorDeon** [flet-dev/flet#4408]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

I've developed a CNPJ normalization within the on_change of the TextField, but it keeps selecting the value and when I type it again it goes out because it's selected, I've tried autofocus, focus and etc and nothing works, can anyone help me?

I don't know if there is another way to do this, or if this is a bug, but it would be interesting to have this functionality to create masks for inputs.

```py
ft.TextField(
  label="CNPJ",
  hint_text="33.933.606/001-39",
  filled=True,
  on_change=normalize_cnpj
)
 
def normalize_cnpj(e: ft.ControlEvent): 
        field: ft.TextField = e.control
        cnpj: str = field.value
 
        digits = "".join(filter(str.isdigit, cnpj))
 
        if len(digits) <= 2:
            field.value = digits
        elif len(digits) <= 5:
            field.value = f"{digits[:2]}.{digits[2:5]}"
        elif len(digits) <= 8:
            field.value = f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}"
        elif len(digits) <= 12:
            field.value = f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}"
        elif len(digits) <= 14:
            field.value = f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}-{digits[12:14]}"
        else:
            field.value = f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}-{digits[12:14]}"
 
        field.update()
```

### Screenshots

![Capturar](https://github.com/user-attachments/assets/6e8fa975-ba15-4fc1-84d0-4b5d5b9dc355)

**Comment by VictorDeon** [comment]
I know there's a duplicate ![here](https://github.com/flet-dev/flet/issues/3467), but mine is more specific

**Comment by ndonkoHenri** [comment]
Please can you share a screen recording of the issue ?
