### ISSUE TITLE
Implement `on_click()` and `on_hover()` for `Text` and `Image`

### ISSUE THREAD

**Issue by scipio-nl** [flet-dev/flet#442]
Having to wrap Text, Image and SVG as a child inside a Container only to access its `on_click()` and `on_hover()` event handlers becomes overly bloated and resource intensive.

**Comment by FeodorFitsner** [comment]
That makes sense.

**Comment by FeodorFitsner** [comment]
This is going to be covered by https://github.com/flet-dev/flet/issues/450
