### ISSUE TITLE
Unhandled exception at 0x00007FFB13FBD9F0 (flutter_windows.dll) in flet.exe

### ISSUE THREAD

**Issue by 3mora2** [flet-dev/flet#4420]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

after update to flet=0.24.1
when use `page.window.destroy()` show error Unhandled exception at 0x00007FFB13FBD9F0 (flutter_windows.dll) in flet.exe
it work fine with flet==0.23.2

![image](https://github.com/user-attachments/assets/bc17e4b7-41c1-4355-9853-9f5c0810ca81)
![image](https://github.com/user-attachments/assets/4d749b5f-ba69-4f2b-9c7e-e0d1c1fc51c0)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    def window_event(e):
        if e.data == "close":
            page.window.destroy()

    page.window.prevent_close = True
    page.window.on_event = window_event

    page.add(ft.Text("Hello, World!"))


ft.app(main)
```

</details>

### To reproduce

.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

win64

### Flet version

flet==0.24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

it work fine with flet==0.23.2

**Comment by ndonkoHenri** [comment]
Which Version of windows do you have? 
Your code works as expected on my windows 10.

**Comment by 3mora2** [comment]
win 10
any suggest to solve error
