### ISSUE TITLE
New Flet 0.25v LINUX error: "flutter/runtime/dart_vm_initializer.cc "

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#4443]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

A message in console when we start our program (only in Linux)

### Code sample

<details open><summary>Code</summary>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      AdInstanceManager.initialize (package:google_mobile_ads/src/ad_instance_manager.dart:440)
<asynchronous suspension>

</details>

### To reproduce

Only happens in Linux, not in Windows nor MacOS

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

Ubuntu 24.10 (linux 6.12)

### Flet version

0.25

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Looking into that.

**Comment by FeodorFitsner** [comment]
Upstream issue: https://github.com/googleads/googleads-mobile-flutter/issues/746
