### ISSUE TITLE
app crached every time opened

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#4458]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

the app keep crash when try to open it 

### Code sample

import flet as ft

def main(page: ft.Page):
    def check_item_clicked(e):
        e.control.checked = not e.control.checked
        page.update()

    page.appbar = ft.AppBar(
        leading=ft.Icon(ft.Icons.PALETTE),
        leading_width=40,
        title=ft.Text("AppBar Example"),
        center_title=False,
        bgcolor=ft.Colors.SURFACE_VARIANT,
        actions=[
            ft.IconButton(ft.Icons.WB_SUNNY_OUTLINED),
            ft.IconButton(ft.Icons.FILTER_3),
            ft.PopupMenuButton(
                items=[
                    ft.PopupMenuItem(text="Item 1"),
                    ft.PopupMenuItem(),  # divider
                    ft.PopupMenuItem(
                        text="Checked item", checked=False, on_click=check_item_clicked
                    ),
                ]
            ),
        ],
    )
    page.add(ft.Text("Body!"))

ft.app(main)

### To reproduce

run app

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.25.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Please provide details on the type of app. (apk, windows exe, ..)

**Comment by zox47** [comment]
yes its an apk

**Comment by zox47** [comment]
> A packaged app? If yes, for which platform did you package? Can you share a video capture?


https://github.com/user-attachments/assets/d3032a8a-943c-429c-9733-019e7738c8ee

**Comment by zox47** [comment]
the logs 
![Screenshot_2024-11-30-19-07-19-212_com miui bugreport](https://github.com/user-attachments/assets/5123734a-c51b-492b-a43e-5128f43b93a0)

**Comment by zox47** [comment]
the error fixed by add meta data gms.ads.application id but after that app block in spalch screen

**Comment by FeodorFitsner** [comment]
What command do you use to build the apk and what requirements do you have in pyproject.toml?

**Comment by zox47** [comment]
command : flet build apk -v
requirements pyproject.toml : 
[project]
name = "tastyfit"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "flet==0.25.1",
  "bs4",
  "requests"
]

#[tool.flet.android.meta_data]
#"com.google.android.gms.ads.APPLICATION_ID" = "ca-app-#pub-3202390806346245~4632644573"

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.tastyfit"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "tastyfit"

# company name to display in about app dialogs
company = "tastyFitCompany"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2024 by Tastyfit"


[tool.flet.flutter.dependencies]
flet_lottie  = "0.25.1"
flet_audio = "0.25.1"
flet_permission_handler = "0.25.1"
#flet_ads = "0.25.1"

[tool.flet.android.permission] # --android-permissions
"android.permission.INTERNET" = true
"android.permission.ACCESS_NETWORK_STATE" = true


[tool.flet.app]
path = "src"

> What command do you use to build the apk and what requirements do you have in pyproject.toml?

**Comment by zox47** [comment]
the app work fin when i remove flet ads and when add it its block yhe app in spalsh screen
