### ISSUE TITLE
Text control is not displayed if TextStyle weight is provided

### ISSUE THREAD

**Issue by InesaFitsner** [flet-dev/flet#4482]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I add `Text` control to a page with `weight` provided for `style` and see grey rectangle instead of Text control.

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.title = "TextStyle weight example"

    text = ft.Text(value="Test Text", style=ft.TextStyle(size=10, height=10, weight=10))
    page.add(text)

ft.app(main)
```

</details>

### To reproduce

1. Run repro code
2. See grey rectangle instead of Text

### Expected behavior

Expected to see styled Text

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

macOS

### Flet version

0.25.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
![image](https://github.com/user-attachments/assets/3835d1cb-23be-44db-bcb4-3e0133ca55df)
[`TextStyle.weight`](https://flet.dev/docs/reference/types/textstyle/#weight) is of type [`FontWeight`](https://flet.dev/docs/reference/types/fontweight) and should not be a number.

Pydantic might be integrated in the future for more validation checking.
