### ISSUE TITLE
`GestureDetector` control

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#450]
https://api.flutter.dev/flutter/widgets/GestureDetector-class.html

"v1" scope:
* [onTap](https://api.flutter.dev/flutter/widgets/GestureDetector/onTap.html)
* [onTapDown](https://api.flutter.dev/flutter/widgets/GestureDetector/onTapDown.html)
* [onTapUp](https://api.flutter.dev/flutter/widgets/GestureDetector/onTapUp.html)
* [onSecondaryTap](https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryTap.html)
* [onSecondaryTapDown](https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryTapDown.html)
* [onSecondaryTapUp](https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryTapUp.html)
* [onLongPressStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onLongPressStart.html)
* [onLongPressEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onLongPressEnd.html)
* [onSecondaryLongPressStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryLongPressStart.html)
* [onSecondaryLongPressEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryLongPressEnd.html)
* [onDoubleTap](https://api.flutter.dev/flutter/widgets/GestureDetector/onDoubleTap.html)
* [onDoubleTapDown](https://api.flutter.dev/flutter/widgets/GestureDetector/onDoubleTapDown.html)
* [onHorizontalDragStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onHorizontalDragStart.html)
* [onHorizontalDragUpdate](https://api.flutter.dev/flutter/widgets/GestureDetector/onHorizontalDragUpdate.html)
* [onHorizontalDragEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onHorizontalDragEnd.html)
* [onVerticalDragStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onVerticalDragStart.html)
* [onVerticalDragUpdate](https://api.flutter.dev/flutter/widgets/GestureDetector/onVerticalDragUpdate.html)
* [onVerticalDragEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onVerticalDragEnd.html)
* [onPanStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onPanStart.html)
* [onPanUpdate](https://api.flutter.dev/flutter/widgets/GestureDetector/onPanUpdate.html)
* [onPanEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onPanEnd.html)
* [onScaleStart](https://api.flutter.dev/flutter/widgets/GestureDetector/onScaleStart.html)
* [onScaleUpdate](https://api.flutter.dev/flutter/widgets/GestureDetector/onScaleUpdate.html)
* [onScaleEnd](https://api.flutter.dev/flutter/widgets/GestureDetector/onScaleEnd.html)
* onHover
* onEnter
* onExit

**Comment by YouJiacheng** [comment]
Also add `MouseRegion` for `onEnter`, `onExit` and `onHover`?
https://api.flutter.dev/flutter/widgets/MouseRegion-class.html

**Comment by FeodorFitsner** [comment]
Absolutely!
