### ISSUE TITLE
[Need Help] Alignment and Scroll not work, flet-0.25.*

### ISSUE THREAD

**Issue by liuzhuoling2011** [flet-dev/flet#4504]
Previous Flet Version < flet-0.25.0 works normally:
![image](https://github.com/user-attachments/assets/4b5d602b-c5b1-4019-9890-321255ed94e1)

Lastest Version cant alignment and scroll:
![image](https://github.com/user-attachments/assets/17a0df5d-d268-4ade-bea4-6013886b3424)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft
from flet_core import MainAxisAlignment, CrossAxisAlignment, ScrollMode


class MainView(ft.View):
    def __init__(self, page: ft.Page, endpoint):
        super().__init__()
        self.page = page
        self.route = f'/{endpoint}'
        self.scroll = ScrollMode.ADAPTIVE
        self.horizontal_alignment = CrossAxisAlignment.CENTER
        self.appbar = ft.AppBar(title=ft.Text(f"Alignment and Scroll not work"))

    def did_mount(self):
        self.page.run_task(self.view_mount)

    def will_unmount(self):
        pass

    async def view_mount(self):
        test_alignment = ft.Row(alignment=MainAxisAlignment.END, controls=[
            ft.Text(f"Alignment not work"),
        ])

        self.controls = [
            test_alignment, *[ft.Text('Scroll not work') for i in range(100)]
        ]

        self.update()


def main(page: ft.Page):
    page.scroll = ScrollMode.ADAPTIVE
    page.horizontal_alignment = CrossAxisAlignment.CENTER
    page.views.append(MainView(page, '/'))
    page.update()


if __name__ == '__main__':
    ft.app(main)


```

</details>

### To reproduce

Run the code

### Operating System

macOS

### Operating system details

MacOS Sequoia 15.1.1

### Flet version

flet-0.25.1

### Regression

No, it isn't

**Comment by liuzhuoling2011** [comment]
**Solved**

Change import from:
`from flet_core import MainAxisAlignment, CrossAxisAlignment, ScrollMode`
to:
`from flet.core.types import ScrollMode, CrossAxisAlignment, MainAxisAlignment`

**Comment by ndonkoHenri** [comment]
You can also use `ft.ScrollMode`.
