### ISSUE TITLE
Hint is only displayed if dropdown is focused

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4511]
### Discussed in https://github.com/flet-dev/flet/discussions/4509

<div type='discussions-op-text'>

<sup>Originally posted by **ingdesarr1** December  6, 2024</sup>
### Question

Good afternoon. Today, I update my versión of flet, to 0.23 to 0.25.1, and now, the hint text of the dropdown not appear correctly. I dont move anything, but how can I fix this? Thanks

With version 0.21
![image](https://github.com/user-attachments/assets/ef7e48ec-901f-4ed6-be08-578b2e85179b)

With version 0.25.1
![image](https://github.com/user-attachments/assets/a214192e-cb9a-4be1-b360-e938d7c79e39)

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

**Comment by Muddassir-Farooq-official** [comment]
@FeodorFitsner there is a bug that tabs methods are not working on Android devices specially on_change in 25.1

**Comment by jlb2-abc** [comment]
the hint text is not being displayed until focused

**Comment by ndonkoHenri** [comment]
This issue has been fixed. Give the the [latest pre-release](https://pypi.org/project/flet/#history) a try: `pip install 'flet[all]' --pre`

**Comment by jlb2-abc** [comment]
it works now thanks
