### ISSUE TITLE
MacOS build with SSL problems

### ISSUE THREAD

**Issue by syleishere** [flet-dev/flet#4514]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

  File "./ssl.py", line 100, in <module>
ImportError: dlopen(/Users/dan/flet/crystaltunes/build/macos/Crystal Tunes.app/Contents/Frameworks/serious_python_darwin.framework/Resources/python-stdlib/lib-dynload/_ssl.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/Python.framework/Versions/3.12/lib/libssl.3.dylib
  Referenced from: <025BF2AA-54E7-333A-B7FA-BD852F11C4CE> /Users/dan/flet/crystaltunes/build/macos/Crystal Tunes.app/Contents/Frameworks/serious_python_darwin.framework/Versions/A/Resources/python-stdlib/lib-dynload/_ssl.cpython-312-darwin.so
  Reason: tried: '/usr/lib/swift/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file), '/Users/dan/flet/crystaltunes/build/macos/Crystal Tunes.app/Contents/Frameworks/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file), '/Users/dan/flet/crystaltunes/build/macos/Crystal Tunes.app/Contents/MacOS/Frameworks/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/Python.framework/Versions/3.12/lib/libssl.3.dylib' (no such file), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)

### Code sample

<details open><summary>Code</summary>

A simple hello world that does an  "import ssl" is sufficient to reproduce along with a "flet build macos" and try to run app. 
Should keep in mind here I am talking about the final build macos app, and not just running flet in pycharm or vscode, as that of course would work....

</details>

### To reproduce

A simple hello world with "import ssl" or import aiohttp or httpx which will call import ssl for you under the hood.
flet build macos
and run the app in build/macos folder.

### Expected behavior

The app should run fine, end users should not be expected to install python or openssl in order to run app. On windows builds the .dll files are included in same directory as the app itself, on macos the .dylib could be included. At this point I am thinking VMs should be created that are fresh for MacOS/windows with no python or anything development related installed and see if a simple flet program with 'hello world" and import ssl are working.

### Operating System

macOS

### Operating system details

Mac Mini M4

### Flet version

Latest devel

### Regression

No, it isn't

### Suggestions

After app is built you could do something like 
```
mkdir build/macos/<appname>/Contents/Frameworks/Python.framework/Versions/3.12/lib
cp -f /path/to/libssl.3.dylib build/macos/<appname>/Contents/Frameworks/Python.framework/Versions/3.12/lib/
cp -f /path/to/libcrypto.3.dylib build/macos/<appname>/Contents/Frameworks/Python.framework/Versions/3.12/lib/
```

or maybe _ssl.cpython-312-darwin.so could be built statically to include those 2 .dylib files somehow...

### Additional details

There are more dylib files that may be needed for other things as well:

```
# ls /Library/Frameworks/Python.framework/Versions/3.12/lib/
Tk.icns                 libformw.5.dylib        libncursesw.dylib       libssl.dylib            pkgconfig               tclConfig.sh            tdbcpostgres1.1.7
Tk.tiff                 libformw.dylib          libpanelw.5.dylib       libtcl8.6.dylib         python3.12              tclooConfig.sh          thread2.8.9
itcl4.2.4               libmenuw.5.dylib        libpanelw.dylib         libtclstub8.6.a         sqlite3.44.2            tdbc1.1.7               tk8.6
libcrypto.3.dylib       libmenuw.dylib          libpython3.12.dylib     libtk8.6.dylib          tcl8                    tdbcmysql1.1.7          tkConfig.sh
libcrypto.dylib         libncursesw.5.dylib     libssl.3.dylib          libtkstub8.6.a          tcl8.6                  tdbcodbc1.1.7

```

**Comment by dsx1986** [comment]
same here. I am on intel mac

**Comment by dsx1986** [comment]
I got this error when I release it to test flight and test on my mac M4:


  File "/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: dlopen(/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so, 0x0002): tried: '/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so' (code signature in <17D6EF5C-4D71-3E06-912D-5464BC98FC00> '/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so' (no such file), '/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so' (code signature in <17D6EF5C-4D71-3E06-912D-5464BC98FC00> '/Users/simon/Library/Containers/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/Data/Library/Application Support/com.diogenes.ai.chatbot.flet.diogenesaibutlerflet/flet/app/__pypackages__/pydantic_core/_pydantic_core.cpython-312-darwin.so' not valid for use in process: library load disallowed by system policy)

**Comment by FeodorFitsner** [comment]
Have you signed and notarized the bundle?

**Comment by FeodorFitsner** [comment]
I'm going to perform a full test of macOS packaging. Two things I suspect: 1) the app needs some entitlements: https://forums.developer.apple.com/forums/thread/716918 (also, `flet build` creates [non-sandboxed app](https://github.com/flet-dev/flet-build-template/blob/main/%7B%7Bcookiecutter.out_dir%7D%7D/macos/Runner/Release.entitlements)) and 2) it could be a problem with signing 3rd-party python packages (like pydantic) unpacked during the first run.

**Comment by dsx1986** [comment]
> Have you signed and notarized the bundle?

Yes, I signed through xcode build/archive using mac distribution certificate and profile, and it passed app store connect upload. The error happened when I test in through TestFlight

**Comment by FeodorFitsner** [comment]
Good, will be investigating the issue. Packaging has #1 priority for us.

**Comment by FeodorFitsner** [comment]
@syleishere SSL issue has been fixed. macOS package now includes `libcrypto.dylib` and `libssl.dylib`. `import ssl` in Python worked for me. Re-build the app. I'm closing this issue as fixed.

@dsx1986 For "library load disallowed by system policy" error I've opened another issue: #4543

**Comment by dsx1986** [comment]
> @syleishere SSL issue has been fixed. macOS package now includes `libcrypto.dylib` and `libssl.dylib`. `import ssl` in Python worked for me. Re-build the app. I'm closing this issue as fixed.
> 
> @dsx1986 For "library load disallowed by system policy" error I've opened another issue: #4543

How do we get latest fix? Did you release new version?

**Comment by FeodorFitsner** [comment]
> How do we get latest fix? Did you release new version?

I've updated iOS distro here: https://github.com/flet-dev/python-build/releases/tag/v3.12
It gets downloaded every time you `flet build`. Delete `build` directory in your project and re-build the app.

**Comment by syleishere** [comment]
All good.

```
macos:~/flet/crystaltunes/build/macos/Crystal Tunes.app $ find .|grep dylib |xargs ls -al
-rwxr-xr-x@ 1 dan  staff  7860080 Dec 10 15:20 ./Contents/Frameworks/Python.framework/Versions/3.12/lib/libcrypto.3.dylib
lrwxr-xr-x@ 1 dan  staff       17 Sep 30 22:35 ./Contents/Frameworks/Python.framework/Versions/3.12/lib/libcrypto.dylib -> libcrypto.3.dylib
-rwxr-xr-x@ 1 dan  staff  1321936 Dec 10 15:20 ./Contents/Frameworks/Python.framework/Versions/3.12/lib/libssl.3.dylib
lrwxr-xr-x@ 1 dan  staff       14 Sep 30 22:35 ./Contents/Frameworks/Python.framework/Versions/3.12/lib/libssl.dylib -> libssl.3.dylib
-rw-r--r--@ 1 dan  staff     1261 Dec 10 23:11 ./Contents/Frameworks/serious_python_darwin.framework/Versions/A/Resources/python-stdlib/ctypes/macholib/dylib.pyc
macos:~/flet/crystaltunes/build/macos/Crystal Tunes.app $ 
```
