### ISSUE TITLE
feature - javascript support to control client (flutter web)

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#452]
**Please Describe The Problem To Be Solved**

Presently changing any control property or the widget tree requires a websocket connection. Change prop, add, remove control etc. This is by design. 

This makes a continual dependency on a websocket connection to control even the simplest update (a text control for example). This is something that should be offloaded to client side javascript

**(Optional): Suggest A Solution**

Instead a hybrid approach is proposed in the same spirit as PWA. The server could deliver a shell , but the javascript could control and update the flet flutter widget by send the same commands the server does.

In fact a flet app could in theory be entirely serialized as json, then javascript could inject that into the flet fluter web client and start the app. Updates are then done by javascript.

I do not know if this is a big or medium size feature. I just know that having a completely serverless flet client would have many use cases.

**Comment by hololeo** [comment]
looks like this feature may come true based on this blog post

https://flet.dev/blog/flet-mobile-update/

```
Even more exciting, async Flet will be able to run entirely in the browser within [Pyodide](https://pyodide.org/) - Python distribution based on WebAssembly (WASM). WebAssembly doesn't have multi-threading support yet, so running in a single thread is a must. Just imagine, Flet web app with a trully offline Flet PWA that does not require a web server to run a Python code!
```

What would be needed after that is a javascript api to talk to the flet/flutter dom .. so you could update properties and call methods from JS to python/wasm

**Comment by FeodorFitsner** [comment]
Well, yeah, re-implementing Flet API in JavaScript would allow that. Flet Pyodide will be using JS to talk to Flutter anyway:

```
Flet Pyodide (WASM)  <->  JavaScript  <->  Flutter (WASM)
```

**Comment by hololeo** [comment]
you are a rock star!
