### ISSUE TITLE
Flet 0.25.1 not working offline (web html)

### ISSUE THREAD

**Issue by Idanaviv66** [flet-dev/flet#4524]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

On previous version of flet, I was able to create an app that can run offline. Using the solution from this [question](https://stackoverflow.com/questions/78313772/issues-with-offline-operation-in-flet-web-application).

Since version 2.4.1 This solution doesn't work. Have any idea how to fix it ?

### Code sample

<details open><summary>Code</summary>

```python
flet.app(main, view=flet.AppView.FLET_APP_WEB, web_renderer=flet.WebRenderer.HTML)
```

</details>

### To reproduce

1. Run the flet app as website with html render.
2. Turn off the internet and see that the website is not loading.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.25.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Unfortunately, HTML renderer was removed in the recent releases of Flutter. There are now **canvaskit** and **skwasm** (not yet supported in Flet): https://docs.flutter.dev/platform-integration/web/renderers
See this Flutter issue: https://github.com/flutter/flutter/issues/145954

We need a proper offline support which is tracked in https://github.com/flet-dev/flet/issues/2096
