### ISSUE TITLE
Flet requires build using pyinstaller requires downloading flet runtime on start

### ISSUE THREAD

**Issue by Idanaviv66** [flet-dev/flet#4549]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

After I build my flet app using pyinstaller and try to transfer it to other computers, on startup the app tries to download from the flet website some libraires. Without them it won't run.  On previous releases it didn't work like that, I could just do pyinstaller and it will work without downloading any additional libraires. 

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

1. create any simple flet desktop app 
2. use pyinstaller to build 
3. run on a different computer when the wifi is off

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.25.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by FeodorFitsner** [comment]
Fixed in 0.25.2
