### ISSUE TITLE
Image not loading using URL as src

### ISSUE THREAD

**Issue by harshnagar** [flet-dev/flet#4563]
Hello, I am trying to add Image in my Image Control but its not loading when provided URL to the Image although the image is accessible when opening in browser.

```
ft.Image(
                src=f"https://i.ytimg.com/vi_webp/fWVtPYZxRXE/maxresdefault.webp",
                height=200,
                fit=ft.ImageFit.NONE,
                repeat=ft.ImageRepeat.NO_REPEAT,
                border_radius=ft.border_radius.all(10)
)
```

**Comment by ndonkoHenri** [comment]
I get this when i run you code:
![image](https://github.com/user-attachments/assets/79d351e8-d633-472f-9e7e-5be358b33770)

**Comment by ndonkoHenri** [comment]
Just from trying it on web, and i get CORS error, which prevents the image from being displayed:
![image](https://github.com/user-attachments/assets/1a5ed9d8-b07b-4abe-8661-88cc9395dec6)

**Comment by harshnagar** [comment]
> Just from trying it on web, and i get CORS error, which prevents the image from being displayed:
> 
> ![image](https://github.com/user-attachments/assets/1a5ed9d8-b07b-4abe-8661-88cc9395dec6)
> 
> 
> 
> Is that what you get? (Open the console tab of the browser)
> 
> 

Yes getting the same error on web, is there any way to get ride out of this in order to display this image on web.

**Comment by ndonkoHenri** [comment]
CORS happens independent of Flet.

You can read online on how you could go about that:
- https://docs.flutter.dev/platform-integration/web/web-images#cross-origin-resource-sharing-cors
- https://enable-cors.org/
