### ISSUE TITLE
How to draw a circle

### ISSUE THREAD

**Issue by artillerymans** [flet-dev/flet#458]
I want to draw a simple geometric figure

**Comment by FeodorFitsner** [comment]
That's a good one!

You can take a `Container` and set its `border_radius` to a half of size, for example:

```python
import flet
from flet import Container, Page

def main(page: Page):
    page.add(Container(bgcolor="blue", width=100, height=100, border_radius=50))

flet.app(target=main)
```

![image](https://user-images.githubusercontent.com/5041459/194738496-9e47a00a-bf9e-4b7f-91ac-4dbff6c11f29.png)

**Comment by artillerymans** [comment]
So what if the hollow circle? By way of superposition?

**Comment by artillerymans** [comment]
![image](https://user-images.githubusercontent.com/16060581/194740630-618de1de-dfdd-46d2-a904-e0e678dbfac9.png)
Something like this

**Comment by ndonkoHenri** [comment]
> You can take a `Container` and set its `border_radius` to a half of size,

What if the `width != height`..
How can we make a circle from that? That will obviously not be the half again. 🤔

And btw, what is the max border radius of a container(i.e the value at which any further increase in border Radius will have no effect)?
And eventually, how can it be calculated..? 🤔

**Comment by FeodorFitsner** [comment]
A new [`Container.shape`](https://flet.dev/docs/controls/container#shape) property was added in the recent release.
