### ISSUE TITLE
When will Golang be supported

### ISSUE THREAD

**Issue by yvanu** [flet-dev/flet#4589]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

When will Golang be supported

**Comment by FeodorFitsner** [comment]
I'm afraid we are going to focus on Python support for a while. It's a huge area and takes a lot of time to make it right. At the moment we just don't have enough resources to support another language.
