### ISSUE TITLE
When build, I met some error (VERBOSE: Preparing metadata (pyproject.toml): finished with status 'error'(

### ISSUE THREAD

**Issue by edwardcho** [flet-dev/flet#4602]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When build, I met some error.
...
VERBOSE: Obtaining dependency information for yfinance==0.2.50 from https://files.pythonhosted.org/packages/c5/98/6f
d94db428a9670d638d4469cedfea51671de0126b8f50de1b06e2245c97/yfinance-0.2.50-py2.py3-none-any.whl.metadata
VERBOSE: Using cached yfinance-0.2.50-py2.py3-none-any.whl.metadata (5.5 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting matplotlib==3.10.0
(  ●   ) Packaging Python app ⏳...VERBOSE: Using cached matplotlib-3.10.0.tar.gz (36.7 MB)
(    ● ) Packaging Python app ⏳...VERBOSE: Installing build dependencies: started
(   ●  ) Packaging Python app ⏳...VERBOSE: Installing build dependencies: finished with status 'done'
VERBOSE: Getting requirements to build wheel: started
(   ●  ) Packaging Python app ⏳...VERBOSE: Getting requirements to build wheel: finished with status 'done'
VERBOSE: Installing backend dependencies: started
(    ● ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
( ●    ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
(   ●  ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
( ●    ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
(  ●   ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
(     ●) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
( ●    ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: still running...
(  ●   ) Packaging Python app ⏳...VERBOSE: Installing backend dependencies: finished with status 'done'
VERBOSE: Preparing metadata (pyproject.toml): started
(    ● ) Packaging Python app ⏳...VERBOSE: Preparing metadata (pyproject.toml): finished with status 'error'

...

### Code sample

<details open><summary>Code</summary>

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

import flet as ft
from flet.matplotlib_chart import MatplotlibChart

matplotlib.use("svg")

def main(page: ft.Page):

    # Fixing random state for reproducibility
    np.random.seed(19680801)

    dt = 0.01
    t = np.arange(0, 30, dt)
    nse1 = np.random.randn(len(t))  # white noise 1
    nse2 = np.random.randn(len(t))  # white noise 2

    # Two signals with a coherent part at 10Hz and a random part
    s1 = np.sin(2 * np.pi * 10 * t) + nse1
    s2 = np.sin(2 * np.pi * 10 * t) + nse2

    fig, axs = plt.subplots(2, 1)
    axs[0].plot(t, s1, t, s2)
    axs[0].set_xlim(0, 2)
    axs[0].set_xlabel("time")
    axs[0].set_ylabel("s1 and s2")
    axs[0].grid(True)

    cxy, f = axs[1].cohere(s1, s2, 256, 1.0 / dt)
    axs[1].set_ylabel("coherence")

    fig.tight_layout()

    chart = MatplotlibChart(fig, expand=True)

    #page.add(chart)

    def on_button_click(e):

        plt.cla()
        #plt.clf()

        # Fixing random state for reproducibility
        np.random.seed(23412)

        dt = 0.01
        t = np.arange(0, 30, dt)
        nse1 = np.random.randn(len(t))  # white noise 1
        nse2 = np.random.randn(len(t))  # white noise 2

        # Two signals with a coherent part at 10Hz and a random part
        s1 = np.sin(2 * np.pi * 10 * t) + nse1
        s2 = np.sin(2 * np.pi * 10 * t) + nse2

        fig, axs = plt.subplots(1, 1)
        #axs[0].plot(t, s1, t, s2)
        #axs[0].set_xlim(0, 2)
        #axs[0].set_xlabel("timesssss")
        #axs[0].set_ylabel("s2 and s1")
        #axs[0].grid(True)

        #cxy, f = axs[0].cohere(s1, s2, 256, 1.0 / dt)
        #axs[0].set_ylabel("coherence")

        cxy, f = axs.cohere(s1, s2, 256, 1.0 / dt)
        axs.set_ylabel("coherence")

        fig.tight_layout()

        #chart.update()

        page.update()

    page.add(
        ft.ElevatedButton("Update Stock Chart", on_click=on_button_click),
        chart
    )

ft.app(main)

```

</details>

### To reproduce

1. Flet build apk -vv
2. Then, after some minutes, can display error.

### Expected behavior

I want to get apk bulit-file.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/eca6bbec-9151-4d10-94d9-a3d81fb6d03d)

</details>

### Operating System

Windows

### Operating system details

Windows 10

### Flet version

0.24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Upgrade to the latest Flet version available with `pip install 'flet[all]' -U`

**Comment by edwardcho** [comment]
Hello Sir,

After flet, I tried build again.
But I met other problem.

![image](https://github.com/user-attachments/assets/ee0a7ace-82dc-4a0a-9eef-a70b5941de13)

The peewee does not have whl file... (maybe tar.gz).
How to solve it??

![image](https://github.com/user-attachments/assets/4fa7966f-94d7-402a-ad71-c4d2b96eb9c3)


Thanks.

**Comment by FeodorFitsner** [comment]
OK, to allow installing source packages run the following command before `flet build`:

```
set SERIOUS_PYTHON_ALLOW_SOURCE_DISTRIBUTIONS=1
```

**Comment by edwardcho** [comment]
Hello FeodorFitsner.

Thank you for your reply.
But still, I can't build my app.

![image](https://github.com/user-attachments/assets/7b388b8c-4bfa-4aa1-b7c2-f7c01300fa44)

![image](https://github.com/user-attachments/assets/701e6581-6459-4e02-9018-af13e1aa80dc)

What should I do for my problem??

Thanks.

**Comment by edwardcho** [comment]
Hello Sir,

I think my problem that is problem with linking Python external libraries in source code form.
(As you know, peewee : peewee_3.17.8.tar.gz)

What should I do to solve this?

Thanks.

**Comment by edwardcho** [comment]
Hello Sir,

I didn't know poetry.dependancy of pyproject.toml.
Anyway I solved my problem.

Thanks.
