### ISSUE TITLE
Error building with flutter 0.27.0

### ISSUE THREAD

**Issue by zox47** [flet-dev/flet#4609]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
../../../../.pub-cache/hosted/pub.dev/flet-0.25.2/lib/src/utils/theme.dart:356:28: Error: A value of type 'TabBarThemeData' can't be returned from a function with return type 'TabBarTheme?'.
 - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
 - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
  return theme.tabBarTheme.copyWith(

### Code sample

import flet
from flet import IconButton, Page, Row, TextField, icons

def main(page: Page):
    page.title = "Flet counter example"
    page.vertical_alignment = "center"

    txt_number = TextField(value="0", text_align="right", width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        Row(
            [
                IconButton(icons.REMOVE, on_click=minus_click),
                txt_number,
                IconButton(icons.ADD, on_click=plus_click),
            ],
            alignment="center",
        )
    )

flet.app(target=main)

### To reproduce

run

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

ubuntu budgie

### Flet version

0.25.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by wikm360** [comment]
I have the same problem.

**Comment by zox47** [comment]
> I have the same problem.

the error come from flutter version try flutter 0.24.5

**Comment by betopolione** [comment]
https://github.com/flet-dev/flet/issues/4607

**Comment by youssef969** [comment]
+1 i have the same problem

**Comment by ndonkoHenri** [comment]
If you want to use Flutter 3.27, follow this: https://github.com/flet-dev/flet/issues/4548#issuecomment-2558093530
