### ISSUE TITLE
build apk fail in flutter 3.27.*

### ISSUE THREAD

**Issue by Laztef** [flet-dev/flet#4629]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

(  ●   ) Building .apk for Android ⏳... 
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.2/lib/src/utils/theme.dart:356:28: Error: A value of type 'TabBarThemeData' can't be returned from a function with return type 
'TabBarTheme?'.
 - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
 - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
  return theme.tabBarTheme.copyWith(
                           ^
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.2/lib/src/utils/theme.dart:438:28: Error: A value of type 'DialogThemeData' can't be returned from a function with return type 
'DialogTheme?'.
 - 'DialogThemeData' is from 'package:flutter/src/material/dialog_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
 - 'DialogTheme' is from 'package:flutter/src/material/dialog_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
  return theme.dialogTheme.copyWith(
                           ^
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.2/lib/src/utils/theme.dart:482:26: Error: A value of type 'CardThemeData' can't be returned from a function with return type 'CardTheme?'.
 - 'CardThemeData' is from 'package:flutter/src/material/card_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/card_theme.dart').
 - 'CardTheme' is from 'package:flutter/src/material/card_theme.dart' ('/D:/flutter/flutter/packages/flutter/lib/src/material/card_theme.dart').
  return theme.cardTheme.copyWith(
                         ^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 37s
(    ● ) Building .apk for Andro   38,3s 
Gradle task assembleRelease failed with exit code 1
[04:29:39] Error building Flet app - see the log of failed command above.
           Run subprocess: ['D:\\flutter\\flutter\\bin\\flutter.BAT', '--version']
[04:29:40] Run subprocess: ['D:\\flutter\\flutter\\bin\\flutter.BAT', 'doctor']
[04:29:47] Doctor summary (to see all details, run flutter doctor -v):
           [√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Versi¢n 10.0.19045.5247], locale es-AR)
           [√] Windows Version (Installed version of Windows is version 10 or higher)
           [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
           [X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
               ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
           [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.2)
           [√] Android Studio (version 2024.2)
           [√] Connected device (1 available)
           [√] Network resources

           ! Doctor found issues in 1 category.

### Additional details

In flutter 3.24 work build apk, but if i upgrade flutter to 3.27.1 break.
it isn't the filepicker problem.
Android SDK version 35.0.0
flutter 3.27.1
java : openjdk version "1.8.0_432"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_432-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.432-b06, mixed mode)

**Comment by ndonkoHenri** [comment]
Read this: https://github.com/flet-dev/flet/issues/4548#issuecomment-2558093530
