### ISSUE TITLE
Proposal: Ability to navigate between items

### ISSUE THREAD

**Issue by Pablo2m** [flet-dev/flet#469]
Both in a column, a list or some more complex element it would be interesting to have the possibility of moving the scroll to go forward or backward between what each item contains, I am making a blog reader and in the expanded view it is very useful to scroll with j and k between the different items.

The solution could be from the ability to move the scroll and being able to inspect each item to know the height (or width) of each one of them to something higher level

**Comment by FeodorFitsner** [comment]
That's absolutely doable in Flutter, thanks for the suggestion!

Implementation details:
https://stackoverflow.com/a/49154882/1435891
https://diamantidis.github.io/2021/10/10/exploring-flutter-scrollable-ensurevisible

**Comment by FeodorFitsner** [comment]
https://flet.dev/blog/scrolling-controls-and-theming#controlling-scroll-position
