### ISSUE TITLE
How to change the  title icon ?

### ISSUE THREAD

**Issue by noob-infinity** [flet-dev/flet#471]
![image](https://user-images.githubusercontent.com/86180049/195305761-e46fec87-9999-4d22-908d-4eb41602840e.png)

Is there anyway to change the default flet icon in the title bar. I have read the flet official website but nowhere found the any suggestion.

I am developing an application and almost completed. Struggling in changing title icon.

Any suggestion will be appreciated.

Thanks in advance.

**Comment by FeodorFitsner** [comment]
It's currently not supported. In the future versions that will be done by rebuilding Flet viewer executable with custom media and metadata.

**Comment by wenjiro** [comment]
> It's currently not supported. In the future versions that will be done by rebuilding Flet viewer executable with custom media and metadata.

hello. Is it supported now?
