### ISSUE TITLE
Optimize Flutter web

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#474]
https://medium.com/@GSYTech/how-to-optimize-flutter-web-and-how-flutter-web-work-in-html-renderer-b399ffd66718

**Comment by ItsCubeTime** [comment]
Im guessing this might have been related to my comment in the Discord server 1-2 days ago
![image](https://user-images.githubusercontent.com/20190653/195731149-e7a13eb1-0189-4502-bbf3-083df8c18d2d.png)

Thank you for opening an issue for it 😘
