### ISSUE TITLE
Whether custom colors can use hexadecimal strings？

### ISSUE THREAD

**Issue by artillerymans** [flet-dev/flet#475]
For example: Can the color of a Text control be passed directly as a hexadecimal color like "#658790"?
Tried all kinds of ways but no。
I just want to customize the color

`
Text(
       value="xxxxxxxxx",
       color="#666666"
 )
`

**Comment by artillerymans** [comment]
I see, I can't use ”#666666”, I should use '#666666'

**Comment by ndonkoHenri** [comment]
What's the difference ? The quotes?
