### ISSUE TITLE
How to use Divider to draw dashed lines

### ISSUE THREAD

**Issue by artillerymans** [flet-dev/flet#476]

**Comment by FeodorFitsner** [comment]
Flutter's Divider widget cannot be displayed as a dashed line.

**Comment by artillerymans** [comment]
Is there any way to draw dashed lines

**Comment by ndonkoHenri** [comment]
https://coflutter.com/flutter-how-to-draw-dashed-line-on-canvas/

This seems possible with the `CustomPaint`.
