### ISSUE TITLE
How to build button to download file

### ISSUE THREAD

**Issue by italanchan** [flet-dev/flet#477]
Just see flet support upload file, is it also support download file feature? How to write?

**Comment by FeodorFitsner** [comment]
Sure, you can use [`page.launch_url(url)`](https://flet.dev/docs/controls/page#launch_urlurl) method and provide URL to a file to download.

URL can be an [asset](https://flet.dev/docs/controls/image#src) (so, copy a file that needs to be downloaded to that folder) or a [pre-signed GET URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) for a cloud storage.
