### ISSUE TITLE
Flet Studio

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#478]
* Adding an app to Flet Studio
  * [ ] Deep linking in Flutter ([1](https://docs.flutter.dev/development/ui/navigation/deep-linking))
    * [x] iOS
    * [ ] Android
  * [x] QR Code generator for Python with output to terminal ([1](https://github.com/lincolnloop/python-qrcode/issues/61), [2](https://gist.github.com/FeodorFitsner/e74940743df4b6f8ceff284bbb720f09))
  * [x] Get IP address from NIC ([1](https://gist.github.com/EONRaider/3b7a8ca433538dc52b09099c0ea92745))
* Exit user app
  * [x] Multi-touch gestures in Flutter ([1](https://fleetingpixels.com/articles/2019/multitouch-tap-gestures-in-flutter/))
  * [x] Shake detector ([1](https://pub.dev/packages/shake))
* [x] Programmatic update of manifest, icons
* [x] FletApp and FletAppStatus controls
* [x] `flet run` CLI
* [x] `flet create <template>`

**Comment by scipio-nl** [comment]
What exactly are you having in mind with "Flet Studio" ?

**Comment by FeodorFitsner** [comment]
https://flet.dev/docs/guides/python/mobile-support#flet-studio-for-ios-and-android

**Comment by 5icoding** [comment]
When to release flet-studio-for-ios-and-android？

**Comment by FeodorFitsner** [comment]
In a few weeks, hopefully, but it all depends on App Store approval.

**Comment by ndonkoHenri** [comment]
> Few weeks 

😁
I think the `flet run` is done right?

**Comment by FeodorFitsner** [comment]
Well, that's for desktop/web only, not for mobile.

**Comment by FeodorFitsner** [comment]
https://flet.dev/blog/flet-for-ios
https://flet.dev/blog/flet-for-android
