### ISSUE TITLE
[Feature request] Support for html/css

### ISSUE THREAD

**Issue by ItsCubeTime** [flet-dev/flet#480]
Hi 👋 Would like to see a control/widget that can take custom html/css (maybe in js?) passed from a file or string

Interesting resources: 
https://medium.com/nerd-for-tech/how-to-add-inline-html-in-webview-flutter-fcc7e0f6a3a2
https://pub.dev/packages/flutter_html  - Somewhat disappointing that it doesn't support the full html/css syntax

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/432
