### ISSUE TITLE
[Feature request] Anti aliasing for svg images (or if possible, as a filter applicable to any control)

### ISSUE THREAD

**Issue by ItsCubeTime** [flet-dev/flet#481]
Anti aliasing is a post-rasterization process that blends neighboring pixels to hide pixels on the screen, being especially important for monitors with less pixels per inch

To demonstrate its importance, here are some images that compares 3 versions of the same set of icons rendered differently:

| desc                                                                                 | fig                                                                                                             |
|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| *a. Png with "fake" anti-aliasing with the help of blurring via image manipulation:* | ![image](https://user-images.githubusercontent.com/20190653/195734308-4e19e049-a3e2-4be6-9cae-d15be7eae3d7.png) |
| *b. Png, no anti-aliasing, same resolution as figure a:*                             | ![image](https://user-images.githubusercontent.com/20190653/195734409-ad8c256b-4642-41d5-aa6c-96bc64138114.png) |
| *c. Svg, no anti-aliasing*                                                           | ![image](https://user-images.githubusercontent.com/20190653/195734938-ec92211e-55c5-4c1b-ae3a-cadad7b9662e.png) |                                                                                                 | 

*All figures were rendered with a height and width of 26px*

Interesting resources: https://pub.dev/packages/blur     https://api.flutter.dev/flutter/widgets/Image/isAntiAlias.html

**Comment by ItsCubeTime** [comment]
![image](https://user-images.githubusercontent.com/20190653/195744905-10fd63d5-4da4-43af-92f6-3071ba3a1aed.png)
An interesting find I just had is that the lack of anti aliasing only seem to be prevalent with the canvaskit renderer

**Comment by FeodorFitsner** [comment]
Is that screenshot an SVG?

**Comment by ItsCubeTime** [comment]
> Is that screenshot an SVG?

Screenshots of images (png & svg) displayed in the canvasKit renderer using flet.Image
