### ISSUE TITLE
'headless' flet web mode

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#492]
**Please Describe The Problem To Be Solved**

Presently launching flet for web/html, launches the url in a browser tab. This is great for development but not necessary in production.

**(Optional): Suggest A Solution**

Add commandline switch and / or api option to only serve webpage/websocket without launching browser

perhaps something like

```
flet.app(target=main, view=flet.WEB_BROWSER mode=headless)

or 

flet.app(target=main, view=flet.WEB_BROWSER mode=serveronly)
```

**Comment by FeodorFitsner** [comment]
It's already possible with:

```python
flet.app(target=main, view=None)
```
