### ISSUE TITLE
support for image zoom in and zoom out

### ISSUE THREAD

**Issue by SimmerChan** [flet-dev/flet#493]
Hi. How about the feature that when clicking on an image, there will be a popup control displaying on the window with zooming in the image?

I have checked the AlertDialog control, and it seems not supporting for holding an Image as its content.

awesome project by the way!

**Comment by SimmerChan** [comment]
Which flet version did you use? Mine is 0.1.62 over windows, and the image doesn't show. I also tried local image in case network problem

![image](https://user-images.githubusercontent.com/7333516/196592334-9ea42dcb-c427-4a3c-9cf9-107f393dc006.png)

**Comment by FeodorFitsner** [comment]
Where are you located? Looks like https://picsum.photos is blocked in China.

**Comment by SimmerChan** [comment]
> Where are you located? Looks like https://picsum.photos is blocked in China.

Sorry, I forgot to add assets_dir to flet.app(). It works now. THX!!
