### ISSUE TITLE
Add `page.window_maximizable`

### ISSUE THREAD

**Issue by noob-infinity** [flet-dev/flet#494]
Hi, 

I can  prevent window from getting minimized but not maximize.

Is there any way to achieve this ?

**Comment by nasoma** [comment]
Set a `window_max_width` and `window_max_height` property on the page control.

**Comment by noob-infinity** [comment]
Earlier I had checked with max_width only but after reading I have set the max_height too and it worked. Thanks for the help.

There is one issue with this though. Maximize button reset the position of the window to origin and give the impression that maximize button is not working properly.

**Comment by FeodorFitsner** [comment]
[window_manager](https://pub.dev/packages/window_manager) library has "setMaximizable" method, but it works on Windows only. I don't know if it makes sense implementing it in Flet as it's for Windows only?

**Comment by ndonkoHenri** [comment]
There are some other window properties in Page that work only for Mac. (Forgot the names actually) 

So, I think it's worth it.
Let's add everything possible to flet and give the devs the full choice on how to build their UIs. 🙂

**Comment by FeodorFitsner** [comment]
You bet!
