### ISSUE TITLE
'Reconnecting' Screen shown after coming back to app

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#498]
A reconnection screen is shown after leaving a running flet app(ex: https://flutils.fly.dev/) for a while in the background, and coming back to it.
- Happened on both Android and iPhones
- very brief (2 to 4 secs)

**Comment by john-rager** [comment]
I just got one of these while running as a Windows app.  Left it running and came back, and had this message with a spinning progress indicator.  Left it for a minute and then just killed it and restarted.

What is trying to "connect", and why would this be necessary for a Windows app?

**Comment by ndonkoHenri** [comment]
A question please, what do you mean by `windows app`?

**Comment by FeodorFitsner** [comment]
Well, currently it's the [same architecture](https://flet.dev/docs/guides/python/mobile-support#flet-approach) even for a desktop, i.e. Flet client in Flutter and Python program both connecting via WebSockets to Flet server written in Go.

I'm working on a [mobile support](https://github.com/flet-dev/flet/issues/478) at the moment and when we are there and see how it performs we'll get back to desktop story. We will try to make it ultra-optimized and ultra-fast: Fletd server will be removed and its functionality replaced with a Python. Flutter client will be hosting Python engine in its process and communicate via [FFI](https://dart.dev/guides/libraries/c-interop).

**Comment by JWDT** [comment]
I've had a similar issue on Linux, seems to be especially if I close my laptop and re-open it later. Doesn't always happen though. Looking forward to the new architecture if it makes everything faster and removes odd things like this. :D

**Comment by FeodorFitsner** [comment]
This behaviour will be changed for desktop apps with a new architecture: https://flet.dev/blog/flet-mobile-update#flet-new-desktop-architecture. Web UX will be reviewed as well, e.g. silent re-connecting on background.
