### ISSUE TITLE
`google_fonts` dart package 

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#502]
**Please Describe The Problem To Be Solved**

I heard that the [google_font ](https://pub.dev/packages/google_fonts) dart package is very efficient and useful when working with fonts. Is it possible to have this here?

Let me know what you think..

**Comment by FeodorFitsner** [comment]
It's already possible to use Google fonts in Flet!

Browse fonts here: https://fonts.google.com/
Let's say you liked "Dancing script": https://fonts.google.com/specimen/Dancing+Script
Find selected font in this repository: https://github.com/google/fonts/tree/main/ofl/dancingscript
Use it in a Flet app - download or reference raw URL: https://flet.dev/docs/controls/page#fonts

If you see a font with the name like [DancingScript[wght].ttf](https://github.com/google/fonts/blob/main/ofl/dancingscript/DancingScript%5Bwght%5D.ttf) that means it is a variable weight font, i.e. it contains multiple fonts.

You can split fonts like that into multiple `.ttf` files for every weight using [**fonttools**](https://pypi.org/project/fonttools/):

    fonttools varLib.mutator ./YourVariableFont-VF.ttf wght=140 wdth=85

To explore available font features (e.g. possible options for `wght`) use [**Wakamai Fondue**](https://wakamaifondue.com/beta/) online tool:

![image](https://user-images.githubusercontent.com/5041459/196851748-23307c3b-7918-4e0e-9553-e011bcf35f5e.png)

**Comment by ndonkoHenri** [comment]
I got that.
But I suggested that Google-fonts package because it will permit us the devs test multiple fonts in a very small time lapse, compared to downloading individual fonts before testing.
Have a look at this @FeodorFitsner

https://user-images.githubusercontent.com/6655696/161121395-bbda7d3e-0842-4fe2-b428-9b2f29da8a8f.gif

That will be great in hot reload mode.
