### ISSUE TITLE
windows 7 support is block by audio plugin.

### ISSUE THREAD

**Issue by liudonghua123** [flet-dev/flet#520]
**Description**

I tried to build a hello flet app, it is ok on my windows 11, however when I copied to another windows 7 x64 computer, it could not startup. I got `GetPointerType` error initially, after update flet, I got another similar error `MFPutWorkItem2`, I found it is because the audio plugin (https://pub.dev/packages/audioplayers, https://github.com/flet-dev/flet/commit/d1bfe1a69713bb5ba9bb1538e1984e0a995621f2#diff-0324ad8599b1c1f40e4ef9102d2c0683581379d966c9bc90aefe5192394330de) dll does not work on windows 7. See also https://github.com/flet-dev/flet/issues/171#issuecomment-1290724229, https://github.com/flutter/flutter/issues/114017.

**Code example to reproduce the issue:**

```python
n.a.
```

**Describe the results you received:**

`MFPutWorkItem2 could not be located in dynamic link library Mfplat.dll.`

**Describe the results you expected:**

No errors when running on windows.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.1.63
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author:
Author-email: Appveyor Systems Inc. <hello@flet.dev>
License: MIT
Location: c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages
Requires: beartype, oauthlib, repath, requests, watchdog, websocket-client
Required-by:
```

**Operating system**:

Windows 11, Microsoft Windows [Version 10.0.22621.675]

**Additional environment details:**

n.a.

**Comment by ndonkoHenri** [comment]
Seems like Flet doesn't support win7 ..
