### ISSUE TITLE
Feature: Theming Switch and Checkbox component

### ISSUE THREAD

**Issue by Skquark** [flet-dev/flet#523]
So all the components that I'm using are being color themed automatically, except for Switch and Checkbox.. At least Checkbox I can manually give it the check_color and fill_color to the color theme, however it doesn't look like Switch has any color setting options exposed.  I expected it to have active_color, active_track_color, inactive_thumb_color, and inactive_track_color, but it doesn't look like that's been implemented yet.  Ideally they would default to the accent color of the theme like all the other components, but if not I'd like to manually set it.  Thanks...

**Comment by Skquark** [comment]
Another thing I've noticed using the Switch & Checkbox is that the tooltip text parameter doesn't work on the Switch but it does on Checkbox.  However the tooltip on the Checkbox pops up in the center, offset from the checkbox that's aligned on the left, so it looks strange detached in the middle.  Tried to hack it to align right, like it does correctly on the button tooltips, but couldn't find a workaround without getting into the Flet code.

**Comment by ndonkoHenri** [comment]
It will be great to have a Tooltip class.

https://github.com/flet-dev/flet/issues/367

**Comment by FeodorFitsner** [comment]
Working on #367!

**Comment by FeodorFitsner** [comment]
@Skquark Regarding tooltip location: it's shown in the middle because checkbox with a label consists of `Checkbox` widget and `Text` put in a `Row` widget together and the resulting group has a tooltip over it. If you need to show tooltip when hovering Checkbox then do not use built-in "label".

**Comment by Skquark** [comment]
Looking forward to seeing the change merged, I tried installing the git controls-s3 branch in my project but it didn't install right for some reason.  Would also love to see the Tooltip class, almost all of my Switches with labels could also use a tooltip to provide more information about what the switch does that I can't fit in the label.
Thanks a bunch, been having a lot of fun coding with this framework...

**Comment by FeodorFitsner** [comment]
It's been released.
