### ISSUE TITLE
Server-Driven UI - How to access mobile features?

### ISSUE THREAD

**Issue by marcelomanzo** [flet-dev/flet#524]
This is a fantastic framework; I have done some tests today and it has so much potential. It's also amazing what have been implemented in short span of time.

Thumbs up for everyone involved, I have been using the Python Remi framework, and Flet takes abstraction to a whole new level, everything is extremely easy and build-in.

I have red and understood the Server-Driven UI approach, one of my requirements is to have the ability to open a serial connection to Bluetooth device and exchange data from a mobile device like ios or android.

Can you please advise if this will be feasible, or it will be situation where I would need to use a combination of Flutter with embedded Flet?

Thanks, and keep up the outstanding work

**Comment by FeodorFitsner** [comment]
Thank you for your interest and kind words!

Yes, to support Bluetooth in Flet it should be implemented in Flutter.
I did a quick look and found [flutter_bluetooth_serial](https://pub.dev/packages/flutter_bluetooth_serial) package which works for Android only. For iOS support I found [this SO discussion](https://stackoverflow.com/a/72953015/1435891) - looks like it is different on iOS. Even [plyer](https://github.com/kivy/plyer#supported-apis) API for Kivy which could have been a good inspiration has Android support only.

But if you know how to implement Bluetooth support in Swift/Objective-C then obviously that could be added to Flutter: https://docs.flutter.dev/development/platform-integration/platform-channels

**Comment by FeodorFitsner** [comment]
...and, yes, Flutter with embedded Flet could be a right solution provided you find/do the right Flutter widget to work with Bluetooth. It will be even possible to extend "Flet" widget with your own widgets.

**Comment by marcelomanzo** [comment]
Sounds great, I can use flet to everything server driven + ui. If I want to access ios/android features, I have to combine with flutter. Fair enough, looking forward for the flutter flet widget.

**Comment by marcelomanzo** [comment]
@FeodorFitsner I would like to discuss something in private, can you please send me a hello via email? marcelomanzo at gmail.com

**Comment by FeodorFitsner** [comment]
Sure, it's already available: https://pub.dev/packages/flet
