### ISSUE TITLE
add color picker  widget supoort?

### ISSUE THREAD

**Issue by scriptiot-dev** [flet-dev/flet#528]
![1666869621718](https://user-images.githubusercontent.com/60819459/198271199-13260c5d-20ad-472a-8e28-5b1f155b785f.png)

**Comment by ndonkoHenri** [comment]
Useful Links for the devs :
https://pub.dev/packages/flex_color_picker

https://pub.dev/packages/flutter_colorpicker

**Comment by FeodorFitsner** [comment]
[flex_color_picker](https://pub.dev/packages/flex_color_picker) is a color picker on steroids :)

**Comment by ndonkoHenri** [comment]
A lot of work in a package. 

Is it doable (flet-speaking)? 🙂

**Comment by FeodorFitsner** [comment]
Doable, sure.

**Comment by hemangjoshi37a** [comment]
hello, Is there any development in this direction yet? If yes please let me know how to  use color picker.

**Comment by FeodorFitsner** [comment]
https://github.com/flet-dev/flet-contrib/tree/main/flet_contrib/color_picker
