### ISSUE TITLE
Add `page.can_launch_url()`

### ISSUE THREAD

**Issue by liudonghua123** [flet-dev/flet#533]
**Please Describe The Problem To Be Solved**

I want to use `url_launcher` library to open the system file explorer in [`file://`](https://pub.dev/packages/url_launcher#supported-url-schemes) protocol. I see the `flet` flutter package has involved this dependence already.

It will be convenient if it supports `url_launcher.canLaunchUrl` and `url_launcher.launchUrl` features.

I will try to make a pr about this.

**Comment by FeodorFitsner** [comment]
`url_launcher` is already implemented: https://flet.dev/docs/controls/page#launch_urlurl

**Comment by FeodorFitsner** [comment]
Could you please elaborate how do you plan to use that method?
