### ISSUE TITLE
Change shape of AlertDialog

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#537]
https://api.flutter.dev/flutter/material/AlertDialog/shape.html

**Comment by dragondjf** [comment]
https://flet.dev/docs/controls/alertdialog

The default shape is a RoundedRectangleBorder with a radius of **4.0.**

defalut RoundedRectangleBorder radius: 
maye  is   40  not 4.0 

@FeodorFitsner

**Comment by dragondjf** [comment]
how to add background-color to alertdialog, more  theme property of alertdialog
