### ISSUE TITLE
Saving and retreiving a string value from client storage adds quotation marks

### ISSUE THREAD

**Issue by langfingaz** [flet-dev/flet#545]
**Description**

Saving and retreiving a string value from the client storage adds quotation marks around it.

**Code example to reproduce the issue:**

```python
import flet
from flet import Page, TextField


class MyApp:
    @staticmethod
    def static_run(page: Page) -> None:
        MyApp(page)

    def __init__(self, page: Page):
        self.page: Page = page
        self.text_field = TextField(label="Value Store", value=self.get_text(), on_submit=self.save_text)
        self.page.add(self.text_field)
        self.text_field.focus()

    def get_text(self) -> str:
        key = "text"
        if self.page.client_storage.contains_key(key):
            return self.page.client_storage.get(key)
        else:
            return "Enter some text here."

    def save_text(self, e):
        key = "text"
        self.page.client_storage.set(key, self.text_field.value)


if __name__ == '__main__':
    flet.app(target=MyApp.static_run, assets_dir="assets")
    # flet.app(target=MyApp.static_run, assets_dir="assets", view=flet.WEB_BROWSER, port=8080)
```

**Describe the results you received:**

1. Start the application
2. Enter some text and press enter to save it to client storage

![image](https://user-images.githubusercontent.com/10504672/199579317-16e7cc57-c2ba-4983-a6e4-bf6dface7cfc.png)
3. Stop and reopen the app. There are now quotations around the text

![image](https://user-images.githubusercontent.com/10504672/199579395-db42e5a5-58c7-4794-b137-2d3c20aa97db.png)

**Flet version (`pip show flet`)**:

```
Version: 0.1.63
```

**Operating system**:

Arch Linux x86

**Additional environment details:**
I am using a `venv` with these requirements installed:
* `flet`
* `py-staticmaps[cairo]`

**Comment by ndonkoHenri** [comment]
I tried adding a print to see the issue better.
![image](https://user-images.githubusercontent.com/98978078/199597961-1967c8de-7bee-47b3-a949-704f4be716e5.png)

And had this..
![image](https://user-images.githubusercontent.com/98978078/199598055-d2bb0440-2098-450c-a55c-a1f552afdd25.png)

This is quite «bizard»/strange.

**Comment by FeodorFitsner** [comment]
Can confirm - it's a bug. Thanks for reporting!

**Comment by FeodorFitsner** [comment]
Fixed in the next release coming later this week.

For workaround unwrap the value with `json.loads()`, for example:

```
v = json.loads(page.client_storage.get("AAA"))
```

**Comment by langfingaz** [comment]
> Thanks for reporting!

You're welcome. Many thanks for your quick replies. Should I close this issue then or leave it open until the next release?

**Comment by FeodorFitsner** [comment]
It will be closed automatically when PR is merged.
