### ISSUE TITLE
run app in canvaskit  background render failed!

### ISSUE THREAD

**Issue by scriptiot-dev** [flet-dev/flet#551]
```
import flet
from flet import Container, Page


def main(page: Page):
    page.title = "Containers bug of canvaskit"

    element = Container(
        bgcolor="#282828",
        width=500,
        height=500,
        border=None
    )

    page.add(element)

flet.app(target=main)
```

+ window mode  [ OK ]

![1667800438044](https://user-images.githubusercontent.com/60819459/200236034-1b102d66-78bf-412d-9e62-de576373f961.png)

+ html  mode   [ OK ]

```
import flet
from flet import Container, Page


def main(page: Page):
    page.title = "Containers bug of canvaskit"

    element = Container(
        bgcolor="#282828",
        width=500,
        height=500,
        border=None
    )

    page.add(element)



flet.app(target=main, view=flet.WEB_BROWSER, web_renderer="html")
```

![image](https://user-images.githubusercontent.com/60819459/200236168-8d4eacd5-9937-4e5a-9e70-325ef4dd416f.png)

+ canvaskit mode **[ failed]**

```
import flet
from flet import Container, Page


def main(page: Page):
    page.title = "Containers bug of canvaskit"

    element = Container(
        bgcolor="#282828",
        width=500,
        height=500,
        border=None
    )

    page.add(element)

flet.app(target=main, view=flet.WEB_BROWSER, web_renderer="canvaskit")
```

![image](https://user-images.githubusercontent.com/60819459/200236216-9054de97-61ac-4a2c-b2bb-d1848b78f326.png)

**Comment by FeodorFitsner** [comment]
I'm sorry, I cannot reproduce the issue using `canvaskit` renderer on macOS in both Edge and Safari browsers:

![image](https://user-images.githubusercontent.com/5041459/201564416-d7d18947-90b6-4ac2-ae91-9104010be510.png)

What browser are you testing that in?
