### ISSUE TITLE
Add support for installing the Flet repository directly with pip.

### ISSUE THREAD

**Issue by ZeroCool940711** [flet-dev/flet#558]
**Please Describe The Problem To Be Solved**
Allow the Flet repository to be installable using pip, this will allow users or developers to have the latest unstable version from the repository with latest features or bug fixes before a proper stable release version is made and uploaded to `pypi`.

**(Optional): Suggest A Solution**
1- In order to make it so the repository can be installed with pip it needs to have a `setup.py` file either on the root of the repo, on the subdirectory which will be used when installing with the `#egg=` option or both places. This file will cover the dependencies and other things needed for building the wheel used by pip.
2- Another solution would be to make it so we can get a wheel from the CI or any other tool used after each commit or PR is approved and merged, then we would just use a fixed URL to get the latest built wheel but this might have issues if the latest build failed for any reason and we could end up with not the latest wheel but a previous built one.

Note: Documentation for devs running from the repository directly should also be created.

**Comment by FeodorFitsner** [comment]
Solution #1 - every single build of Flet is published to https://test.pypi.org: https://test.pypi.org/project/flet/
You can install a fully functional bleeding-edge copy from there. We recommend installing into a new Python virtual environment.

Solution #2 - not exactly a solution, but a direction. We are going to switch Flet development to smaller PRs or so-called WIPs (work in progress), so `main` branch is updated more often and there is always an ability to cut release if we need to do that.

**Comment by ndonkoHenri** [comment]
Solution 1: Great and happy to hear that. Let me/us know from now on when there is a feature you wish should be tested by the community.. 😉

**Comment by ZeroCool940711** [comment]
Mmm, while having it build and publish it to test.pypi.org is a valid solution I think having it be released normally but with the name `flet-nightly` on pypi would be better, it's easier to remember and easier to type than `pip install -i https://test.pypi.org/simple/ flet`, that way we can just do `pip install flet-nightly`.

**Comment by FeodorFitsner** [comment]
`flet-nightly` sounds good and I see other projects use that approach on pypi.org. I'm only not sure about publishing it nightly. I would rather think publishing a new "nightly" release when a PR is merged into `main`. But what would be a better suffix for that? :)

**Comment by ZeroCool940711** [comment]
> `flet-nightly` sounds good and I see other projects use that approach on pypi.org. I'm only not sure about publishing it nightly. I would rather think publishing a new "nightly" release when a PR is merged into `main`. But what would be a better suffix for that? :)

mmm, what about a pre-release, something that can be installed with just `pip install --pre flet`?, not sure how to do that tho but it would be the middle ground between `release` and `nightly`.
