### ISSUE TITLE
Failing to Implement my own ICONS

### ISSUE THREAD

**Issue by applicatlat** [flet-dev/flet#560]
Hi again,

I tried to implement my own icon but could not figure out.
tried to use this code t
`engl_flag_ic = Icon(name="/assets/uk_round_flag.ico")`
`icon_lang = icon_button_creator(ic_color=None,ic_size=text_size*1.5,ic_tip="language",  ic=engl_flag_ic, ref=icon_lang_ref)`
Error message:
Icon button does not have an icon neither content specified.

- I also tried to use it with Image but could not manage it as well.
- Also I looked into the icons. py tried to implement my icon address from there. However I could  not manage it  again. 

Can you please add a guildeline for it?
I wanted to the ask these questions from stackoverflow but my popularity score was below the required level.

**Comment by FeodorFitsner** [comment]
I don't think .ico format is supported by Flutter at the moment and there is an open issue to add that support: https://github.com/flutter/flutter/issues/105848

Convert .ico to PNG, so you can use it with Flet.

**Comment by applicatlat** [comment]
I am trying to use it on a button. But I will try. Thank you very much feodor. I had another question. I hope you may find the time to look into it. Thank you very much for your wonderful work and effort. When I finish my app I will mention your name in credits.
