### ISSUE TITLE
Restarting the app from within the app.

### ISSUE THREAD

**Issue by applicatlat** [flet-dev/flet#561]
As you know there is on_start on_destroy on_restart methodsin Android Java. I could manage write something close to on destroy and on start.But I am unable to restart the app without completely closing it. When it closes it does not open. Is there a method for this? Or a roundabout way that you can think of.

**Comment by ndonkoHenri** [comment]
Do you mean while developing the app? Or in production?

**Comment by applicatlat** [comment]
Both and I did not know if there is much difference.

**Comment by applicatlat** [comment]
Ah yes. After your first message I checked on hot reload but as you said ther eis no reference I hope feodor might sho us da weii.

**Comment by ndonkoHenri** [comment]
Flet has not yet gone "mobile"(in the stores).
But my question now is, how/why do you expect your app's user to restart the app? I mean, he could simply close and open it back right? 🤔
