### ISSUE TITLE
feature: control scroll position of scrollable lists (column,row, etc)

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#566]
**Please Describe The Problem To Be Solved**

Presently there is no way to set the  x/y scroll position of controls in scrolling list controls (column,row,listview,etc). The only mechanism available is autoscroll which only scrolls position to last item in list (and it does with a slow tween)

The use case is a UI that displays captions. As text is added to the Column, the user should see the latest by scrolling to the bottom most position. In addition, if the user wants to jump to parts in the column this should be possible with a set x/y of the column/row... much like hash links allow jumping within a single html page

**(Optional): Suggest A Solution**

IDEAL SOLUTION:

Scrollable list control should allow setting the x,y offset from top/left. The api should be something like column.setscroll (40) and that would update the column so its items come into 40 pixels from top to view. Or column.setscroll (-1) would update column to the last most position. something like this.

ALTERNATIVE 2:

Scrolling to an item index and letting flutter figure it out would work really nicely as well
see 

https://pub.dev/documentation/scrollable_positioned_list/latest/scrollable_positioned_list/ScrollablePositionedList-class.html

ALTERNATIVE 3:

If this is too involved, simply allowing for setting  the tween behavior of autoscroll would achieve it. A duration of 0 should immediately scroll the item bottom most.

some links

https://stackoverflow.com/questions/49153087/flutter-scrolling-to-a-widget-in-listview
https://pub.dev/documentation/scrollable_positioned_list/latest/scrollable_positioned_list/ScrollablePositionedList-class.html
(more links in that stackflow discussion)

**Comment by magnuswenzer** [comment]
Hi! 
I'm currently working on a calender view where I would like to scroll in a list of days. As of now I can not goto a specific day in the listview. Implementing a functionality to GOTO or FOCUS on a specific control that the listview controls would be a much appriciated improvement. 
Keep up the nice work!

**Comment by FeodorFitsner** [comment]
https://flet.dev/blog/scrolling-controls-and-theming#controlling-scroll-position
