### ISSUE TITLE
Theming Slider component like swicth or checkbox support

### ISSUE THREAD

**Issue by dragondjf** [flet-dev/flet#570]
now slider theme can't change by user !

@FeodorFitsner

**Comment by FeodorFitsner** [comment]
With the latest Flet release you can change colours of all switch elements and checkbox. Could you please elaborate what's missing?

**Comment by dragondjf** [comment]
Yeah, all switch elements and checkbox can, but  slider widget can't change theme

**Comment by FeodorFitsner** [comment]
Oh, right, Slider! :) Sorry, I must be slow on Sunday!

Will implement that tomorrow.
