### ISSUE TITLE
how to change NavigationBar position?

### ISSUE THREAD

**Issue by dragondjf** [flet-dev/flet#571]
![image](https://user-images.githubusercontent.com/4066126/201567136-25ffc71e-dcd8-48a8-991a-6fc5712c4ba2.png)

now NavigationBar can only  show on bottom,  how to show on left/top/right?

@FeodorFitsner

**Comment by FeodorFitsner** [comment]
`NavigationBar` is always at the bottom. If you need a navigation control on left or right use [NavigationRail](https://flet.dev/docs/controls/navigationrail).

**Comment by ndonkoHenri** [comment]
> now NavigationBar can only show on bottom, how to show on left/top/right?

Remember it is also called: **Bottom** Navigation Bar. 😉

**Comment by FeodorFitsner** [comment]
Yeah, it's its former Material 2 name.
