### ISSUE TITLE
Will a canvas widget be implemented? 

### ISSUE THREAD

**Issue by SimmerChan** [flet-dev/flet#575]
prefer a control like canvas in HTML or Flutter canvas Class https://api.flutter.dev/flutter/dart-ui/Canvas-class.html
Will it be under consideration?
THX

**Comment by FeodorFitsner** [comment]
Not sure about Canvas, but [CustomPaint](https://github.com/flet-dev/flet/issues/205) will be implemented for sure.

**Comment by SimmerChan** [comment]
我已收到您的邮件，祝您生活愉快！

**Comment by FeodorFitsner** [comment]
Let's close this issue for now. If there is a greater demand for a canvas control we could re-open it.
