### ISSUE TITLE
IMAGE DISPLAYING BUG!

### ISSUE THREAD

**Issue by applicatlat** [flet-dev/flet#576]
I experienced this in PYCHARM community edition: If you write the .py file inside a folder that you created and want to view images within that .py file you wont be able to observe the image and there will be no error messages. If you move the .py file under the project than it turns out ok.

**Comment by FeodorFitsner** [comment]
Could you please provide more details as described in the [issue template](https://github.com/flet-dev/flet/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by applicatlat** [comment]
Sure I need to spare some time on it. I will do it on the following days.

**Comment by FeodorFitsner** [comment]
Great, feel free to re-open this issue when you collect more details.
