### ISSUE TITLE
Is there a way to disable tooltips being visible on hover on widgets?

### ISSUE THREAD

**Issue by applicatlat** [flet-dev/flet#586]
Hi, I use tooltips to call functions with e.control property. I do this due to having automatically created widgets. However, I do not want them to be visible on hover on the objects like buttons and containers. Is there a solution for this?

**Comment by ndonkoHenri** [comment]
Instead of using a Tooltip you could make use of the Control's `data` property. And in your function use `e.control.data`

**Comment by applicatlat** [comment]
Wow thank you very much it was a huge help.
