### ISSUE TITLE
Tree View Support

### ISSUE THREAD

**Issue by Pablo2m** [flet-dev/flet#590]
Would it be possible to add a tree view? I saw several libraries but I don't have the knowledge to be able to evaluate them, for example
https://github.com/xrr2016/flutter-tree
Many thanks in advance

**Comment by Pablo2m** [comment]
With that example I think it's enough for me, thanks

**Comment by iron3oxide** [comment]
I think the Collapsible is basic enough to be useful in many projects. Could we add it to the standard widgets?

**Comment by eeintech** [comment]
> I think the Collapsible is basic enough to be useful in many projects. Could we add it to the standard widgets?

:+1:

**Comment by CoutinhoElias** [comment]
> With that example I think it's enough for me, thanks

Interestingly, when running here, only a blank form appeared.
Is there anything else to do?

**Comment by Casyvina** [comment]
same here, just blank

**Comment by meistermaxb04** [comment]
> same here, just blank

Had the same issue

In the collapsible.py you got to call the _build function at the end of __init__

Same goes for menu_button.py

**Comment by Wanna-Pizza** [comment]
> > same here, just blank
> 
> Had the same issue
> 
> In the collapsible.py you got to call the _build function at the end of **init**
> 
> Same goes for menu_button.py

Hello! I edited some files. It works now!

Just need to add "did_mount". Normally flet widgets using "did_mount". _build or Build was working with ft.UserControl. 

[TreeMenu.zip](https://github.com/user-attachments/files/18551834/TreeMenu.zip)

**Comment by CoutinhoElias** [comment]
Very good.
Can you believe I had already implemented it this way?
Thank you very much for your answer.

> > > same here, just blank
> > 
> > 
> > Had the same issue
> > In the collapsible.py you got to call the _build function at the end of **init**
> > Same goes for menu_button.py
> 
> Hello! I edited some files. It works now!
> 
> Just need to add "did_mount". Normally flet widgets using "did_mount". _build or Build was working with ft.UserControl.
> 
> [TreeMenu.zip](https://github.com/user-attachments/files/18551834/TreeMenu.zip)
