### ISSUE TITLE
Slider support on_pressed and on_released event

### ISSUE THREAD

**Issue by cuifengcn** [flet-dev/flet#596]
I want to use Slider to implement a audio slide control component,but there's no on_pressed and on_release event, it bothers me >_<

**Comment by ndonkoHenri** [comment]
Why not use the `on_change` event? 
https://flet.dev/docs/controls/slider#on_change

**Comment by cuifengcn** [comment]
> Why not use the `on_change` event? https://flet.dev/docs/controls/slider#on_change

`Slider` goes with `Audio` playing，but when i pressed `Slider`, `Audio` must no more push the `Slider` untill i release the `Slider`, so i need to know the Slider `press` and `release` event. (forgive my poor english)

**Comment by FeodorFitsner** [comment]
I guess [Slider.onChangeStart](https://api.flutter.dev/flutter/material/Slider/onChangeStart.html) and [Slider.onChangeEnd](https://api.flutter.dev/flutter/material/Slider/onChangeStart.html) should work then?

**Comment by cuifengcn** [comment]
> I guess [Slider.onChangeStart](https://api.flutter.dev/flutter/material/Slider/onChangeStart.html) and [Slider.onChangeEnd](https://api.flutter.dev/flutter/material/Slider/onChangeStart.html) should work then?

Yeah, that's exactly what i  need! Could you please fix it? that'll be a big help.[smile face]

**Comment by FeodorFitsner** [comment]
Sure, will make a PR tomorrow.

**Comment by FeodorFitsner** [comment]
Sample code:

```python
import flet as ft

def main(page: ft.Page):
    page.add(
        ft.Slider(
            width=200,
            on_change=lambda e: print("ON CHANGE:", e.data),
            on_change_start=lambda e: print("ON CHANGE START:", e.data),
            on_change_end=lambda e: print("ON CHANGE END:", e.data),
        ),
    )

ft.app(target=main)
```

**Comment by FeodorFitsner** [comment]
The feature has been published as a pre-release and can be installed with the following command:

```
pip install flet --pre
```

Usage example:

```python
import flet as ft

def main(page: ft.Page):
    page.add(
        ft.Slider(
            width=200,
            on_change=lambda e: print("ON CHANGE:", e.data),
            on_change_start=lambda e: print("ON CHANGE START:", e.data),
            on_change_end=lambda e: print("ON CHANGE END:", e.data),
        ),
    )

ft.app(target=main)
```
