### ISSUE TITLE
Border Radius FloatingActionButton

### ISSUE THREAD

**Issue by nascin** [flet-dev/flet#602]
Insert `border_radius` in the FloantingActionButton control as it is in the Container.

Currently it is not possible to change, to have a button with a customized border radius, I use the `Container` as a button, I think that would not be ideal.

**Comment by FeodorFitsner** [comment]
So, we are looking into implementing `Fab.shape` property: https://api.flutter.dev/flutter/material/FloatingActionButton/shape.html

Is there anything else missing in FAB control that you'd like to be added?

**Comment by FeodorFitsner** [comment]
> At the moment I missed being able to insert an icon and a content at the same time.

It's how FAB is made in Flutter. Just put icon and text into Row and use it as a content.

**Comment by nascin** [comment]
Ah, I see.. perfect!

**Comment by FeodorFitsner** [comment]
The feature has been published as a pre-release and can be installed with the following command:

```
pip install flet --pre
```

Usage example:

```python
import flet as ft

def main(page: ft.Page):

    page.floating_action_button = ft.FloatingActionButton(
        content=ft.Row(
            [ft.Icon(ft.icons.ADD), ft.Text("Add")], alignment="center", spacing=5
        ),
        bgcolor=ft.colors.AMBER_300,
        shape=ft.RoundedRectangleBorder(radius=5),
        width=100,
        mini=True,
    )

    page.add(ft.Text("Just a text!"))

ft.app(target=main)
```
