### ISSUE TITLE
Replace Literals with Enums

### ISSUE THREAD

**Issue by EGAMAGZ** [flet-dev/flet#607]
**Please Describe The Problem To Be Solved**

When it's needed to set an attribute such as theme, alignment, type of scroll, etc , we have to type "magic" literals after consulting them in the documentation or in the IDE, leading to misstyping errors.

```python
def main(page: flet.Page):
    page.theme_mode = "light"
    page.add(
        Row(
            controls=[
                Text(
                    "Hello World!"
                )
            ],
            alignment="center"
        )
    )
```

**(Optional): Suggest A Solution**
My suggestion is to replace the use of literals with Enums, to make it easier to set attributes to an usercontrol, and reusable the values related with same features. This is something that other UI frameworks such as Flutter and Jetpack Compose do.

Jetpack Compose:
```kotlin
@Composable
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }

    MaterialTheme {
        Column(
            modifier = Modifier.fillMaxSize(),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
           Button(onClick = {
            text = "Hello, Desktop!"
           }) {
               Text(text)
            }
        }
    }
}
```

Flutter:
```dart
Column(
  crossAxisAlignment: CrossAxisAlignment.start,
  mainAxisSize: MainAxisSize.min,
  children: <Widget>[
    const Text('We move under cover and we move as one'),
    const Text('Through the night, we have one shot to live another day'),
    const Text('We cannot let a stray gunshot give us away'),
    const Text('We will fight up close, seize the moment and stay in it'),
    const Text('It’s either that or meet the business end of a bayonet'),
    const Text('The code word is ‘Rochambeau,’ dig me?'),
    Text('Rochambeau!', style: DefaultTextStyle.of(context).style.apply(fontSizeFactor: 2.0)),
  ],
)
```

In the case of Flet, the implementation coulbe like this:
```python
class ThemeMode(enum.Enum):
    NONE = None
    SYSTEM = "system"
    LIGHT = "light"
    DARK = "dark"


class MainAxisAlignment(enum.Enum):
    NONE = None
    START = "start"
    END = "end"
    CENTER = "center"
    SPACE_BETWEEN = "spaceBetween"
    SPACE_AROUND = "spaceAround"
    SPACE_EVENLY = "spaceEvenly"


def main(page: flet.Page):
    page.theme_mode = ThemeMode.DARK
    page.add(
        Row(
            controls=[
                Text(
                    "Hello World!"
                )
            ],
            alignment=MainAxisAlignment.CENTER
        )
    )
```

**Comment by FeodorFitsner** [comment]
That sounds great and right! I'm going to do a PR with that. Or you probably want to help? ;)

**Comment by EGAMAGZ** [comment]
I'll be glad to help, but i'll take me while because i have some issues with pdm when i try to configure the env for sdk/python

**Comment by ItsCubeTime** [comment]
Im also in favor of this :)

Otherwise I suppose you could also start using classes with string literals inside - that way perhaps it would be easier to translate the existing codebase

Like:

```py
class ThemeModes():
    lightTheme = "light"
    darkTheme = "dark"
```
and then expose ThemeModes under flet, maybe like `flet.types.ThemeModes.lightTheme` (perhaps with capital letters to make it obvious that its supposed to be used as an ENUM)

**Comment by FeodorFitsner** [comment]
Enums look nicer :) I'm working on that.

**Comment by FeodorFitsner** [comment]
Closing https://github.com/flet-dev/flet/issues/316 in favor of this issue.

**Comment by FeodorFitsner** [comment]
It's been published to Flet pre-releases:

```
pip install flet --pre
```
