### ISSUE TITLE
Customizing Flet error screen

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#619]
### Discussed in https://github.com/flet-dev/flet/discussions/614

<div type='discussions-op-text'>

<sup>Originally posted by **Fatpandac** November 21, 2022</sup>
I want to catch exceptions and then show exceptions on display or let the user send me feedback.</div>

**Comment by ndonkoHenri** [comment]
At the moment, the below can be done:
```py
import flet as ft


def main(page: ft.Page):
    page.add(
        ft.ElevatedButton(
            "Don't click on this.",
            on_click=lambda _: page.error("You shouldn't have clicked!!")
        )
    )


ft.app(target=main)
```

Or one could create a `View` to which the app routes can route when an error is caught by the `try-except` or `page.error`. 
This view could contain a form to send feedback...
