### ISSUE TITLE
Dockerize web-based Flet Application

### ISSUE THREAD

**Issue by pangoro24** [flet-dev/flet#625]
I am not a really expert on docker but following the https://flet.dev/docs/guides/python/deploying-web-app/fly-io, I wanted to try my demo in my own computer. When I run the app from my local virtual env, the web app is displayed without problem. However, when I try to run it from a docker container, even when the container is running without issues, it give me error: (failed)net::ERR_EMPTY_RESPONSE

Docker commands used to create the image and run the container
docker build --tag flet-app:latest .
docker run -it -p 62590:62590 -p 8080:8080 flet-app

Source Code
```
import flet as ft

def main(page: ft.Page):
    page.add(ft.Text(value="Hello world from containerized Flet app!"))

ft.app(target=main, view=ft.WEB_BROWSER)
```

dockerfile
```
# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . . 

EXPOSE 8080 62590

CMD ["python", "./app/main.py"] 
```

**Comment by FeodorFitsner** [comment]
Try [this Dockerfile](https://github.com/flet-dev/examples/blob/main/python/apps/icons-browser/Dockerfile) which works great for Fly.io environment. Let me know if that worked.

**Comment by arminus** [comment]
I think the key here is that you start your app with
```
ft.app(target=main, port=8080, view=ft.WEB_BROWSER)
```
Then you don't need to expose 62590 - which is pointless anyway, because unless you specify the port for ft.app(...) explicitly, fletd starts on a random port which your Docker will never know about.

At any rate, this way, my brief test worked.

**Comment by pangoro24** [comment]
Thanks for your comments. It helped to fix my dockerfile.
```
FROM python:3-alpine

# Set the working directory to /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

EXPOSE 8080

CMD ["python", "./app/main.py"]
```

and compose file is:
```

version: '3.8'
services:
  webapp: 
    build: .
    ports:
      - '8080:8080'
    restart: always
    container_name: fletappcontainer
    image: webapp/fletapp:latest
```

Just as a reference for the community, I leave the demo in a public github repo. https://github.com/pangoro24/pyflet

**Comment by FeodorFitsner** [comment]
It's great you got it working and thanks for sharing the resulting files! We will include that into the guide.

Btw, it's also possible to define Flet port in `Dockerfile` via `FLET_SERVER_PORT` environment variable.

**Comment by pangoro24** [comment]
thank you @FeodorFitsner  for your feedback. I updated the repo and plus, added an env file to set the PORT

**Comment by Shahin-rmz** [comment]
> Try [this Dockerfile](https://github.com/flet-dev/examples/blob/main/python/apps/icons-browser/Dockerfile) which works great for Fly.io environment.

It's very nice.
thanks.
Can we have an official docker compose file for Flet?

**Comment by shinriyo** [comment]
```
git clone https://github.com/flet-dev/exampleshttps://github.com/flet-dev/examples
cd examples/examples/python/apps/icons-browser
docker build --tag flet-app:latest .
docker run -it -p 62590:62590 -p 8080:8080 flet-app
```

but I can't access both of them.

http://localhost:8080/
http://localhost:62590/

**Comment by Spritaro** [comment]
It appears that Flet switches to the browser when running inside a container. But it fails to call ```open_in_browser()``` function if ```view``` option is not set to ```WEB_BROWSER```.

https://github.com/flet-dev/flet/blob/2150cc506798dd92481c25e3432cc929f3bd6c23/sdk/python/packages/flet/src/flet/flet.py#L147-L167

It would be nice if it could raise an error or a warning though.

**Comment by FeodorFitsner** [comment]
@Spritaro so, we should add another check for running inside Docker container before opening web browser, right?

**Comment by Spritaro** [comment]
Thank you @FeodorFitsner for your response. Yes, adding another check before opening or an else block afterwards will be helpful.

**Comment by FeodorFitsner** [comment]
Sorry, I just realized you need to pass `view=None` when running in container:

```python
ft.app(main, port=8080, view=None)
```
