### ISSUE TITLE
Is it possible to set the font size of the text of a button

### ISSUE THREAD

**Issue by TingTingin** [flet-dev/flet#635]
**Please Describe The Problem To Be Solved**

As of right now I want to change the font and font size of the text in a button but it doesn't seem you can independently do this you can only change the size of the button itself and not the padding also you cant change the font family of a button either

**(Optional): Suggest A Solution**

Adding the ability to set the size and font of the text in a button independently

**Comment by ndonkoHenri** [comment]
It is possible. See this example: https://flet.dev/docs/controls/elevatedbutton#elevated-button-with-custom-content

Buttons have a `content` property. Set that to your custom `Text` control with modified fonts..

**Comment by khairm** [comment]
This should be closed now
