### ISSUE TITLE
Make the flet app accessible in the LAN

### ISSUE THREAD

**Issue by huanmengmie** [flet-dev/flet#645]
hello， I'm using flet to develop a website and I think it's very cool.
**Please Describe The Problem To Be Solved**
After I package the app, because it contains some web resources, such as [canvas. js], I cannot access the website I developed on the LAN
![image](https://user-images.githubusercontent.com/26222630/204689210-cff85639-d648-40a3-a5fa-044bf0ffae43.png)

**(Optional): Suggest A Solution**

Package the web resources together when packaging

Look forward to your reply. Thank you

**Comment by FeodorFitsner** [comment]
There is a related issue for that and a solution for hosting canvaskit.wasm: https://github.com/flet-dev/flet/issues/269#issuecomment-1236492198

I'll look into that more closely.
