### ISSUE TITLE
Is there a demonstration of camera reading and video reading

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#648]
**Please Describe The Problem To Be Solved**

Read the camera and display the interface

Read the video file and display the interface

**Comment by ipritom** [comment]
Currently Flet has no built-in video support. This feature is requested by many. #257 

However, we can read video frames with OpenCV. We can view frames in flet `Image` control. 
https://flet.dev/docs/controls/image/

To update frames in the `Image` control we have to run the OpenCV video source `read()` function in a separate thread.
You'll find both example for camera and video source reading in the following repo.
https://github.com/ipritom/flet-demo/tree/main/media

**Comment by monkeycc** [comment]
Problem solved

Thanks for your help
