### ISSUE TITLE
`Image` control must support loading images from local files

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#651]

**Comment by ipritom** [comment]
So there is no way to load and show images from the local storage currently in Flet? I was try with the following code.

```python
import flet as ft

def main(page : ft.Page):
    page.title = "image viewer"
    image = ft.Image(src='butterfy.jpg', height=500, width=500)

    page.add(image)
    page.update()

ft.app(target=main)
```
The image is in the same directory. But it shows nothing in the output. Then I found out this post in Issues. 
OS: Ubuntu 20.04

**Comment by ipritom** [comment]
Got a solution for this: 

```python
import flet as ft
import cv2
import base64

def get_base64(image_path):
    img = cv2.imread(image_path)
    jpg_img = cv2.imencode('.jpg', img)
    b64_string = base64.b64encode(jpg_img[1]).decode('utf-8')
    return b64_string



def main(page : ft.Page):
    page.title = "image viewer"

    image = ft.Image(src_base64=get_base64('butterfly.jpg'), height=500, width=500)

    page.add(image)
    page.update()

ft.app(target=main)

```

**Comment by FeodorFitsner** [comment]
Or just use `assets` dir approach: https://flet.dev/docs/controls/image#src

**Comment by FeodorFitsner** [comment]
`Image` now supports local file paths in `src` property though it works in desktop app only.
You can give it a try by installer pre-release Flet package with `pip install flet --pre`.
