### ISSUE TITLE
Android and IOS support

### ISSUE THREAD

**Issue by MominIqbal-1234** [flet-dev/flet#660]
**Please add Android and ISO Support**

**Comment by FeodorFitsner** [comment]
What is "ISO" in this context, could you please elaborate? I'm quite new to Android development.

**Comment by kmranrg** [comment]
Hello @MominIqbal-1234 ,

Do you mean iOS support, if that's the case, Flet is already very to close to achieve that. Please refer to the below article.

Link: https://flet.dev/docs/guides/python/mobile-support

Regards,
Kumar Anurag

**Comment by MominIqbal-1234** [comment]
hi @FeodorFitsner  
sorry bro my spelling mistake
i mean IOS 

Thansk for @kmranrg 
i am waiting for android and IOS Support 
i hope android and IOS support soon as soon
thanks so much

**Comment by FeodorFitsner** [comment]
https://flet.dev/blog/flet-for-ios
https://flet.dev/blog/flet-for-android
