### ISSUE TITLE
Interaction with the app through multiple devices gets reflected on all of them

### ISSUE THREAD

**Issue by mnobeidat13** [flet-dev/flet#663]
Sorry for not following the required format for bug reports but I don't know where the bug exactly happens and its not an error.
I deployed my app to replit.com. I open the app through two devices, my phone and my laptop. What happens is any interaction I do on either device gets reflected on the app opened in the other one. 
I cant explain more and screenshots wont help any further I guess. 
I dont know, but it seems that the app runs in one session.
I dont use any authintication nor I save user session (I font know if that is even possible).

This is a link to the app deployed on replit:
https://portfolio.mnobeidat.repl.co/#/item_recommendation

**Comment by FeodorFitsner** [comment]
I'm closing this issue as a dup of https://github.com/flet-dev/flet/discussions/665
