### ISSUE TITLE
App name not showing after deploying to Replit

### ISSUE THREAD

**Issue by kmranrg** [flet-dev/flet#668]
**App Name not showing what I'm setting using `page.title` property**

I followed up all the steps mentioned in the Flet official documentation for deploying the web app in Replit. The one thing that I am noticing is when I'm the trying to install the PWA, whether in Desktop or Mobile device, after installation, it's just showing the App name as Flet but not the name that I'm setting through `page.title` property.

**Small section of Source Code**

```python
import flet as ft

def main(page: ft.Page):
    page.title = "Wicktionary"

ft.app(target=main)
```

**Screenshot**

<img width="395" alt="Screenshot 2022-12-04 at 6 52 00 PM" src="https://user-images.githubusercontent.com/31153544/205493028-9c0f9b42-beeb-4e10-8ecf-aec3b43f7355.png">

**Comment by kmranrg** [comment]
Hello @FeodorFitsner,

Is there any function/method in Flet by which we can set the App logo and name of our application.

Regards,
Anurag

**Comment by FeodorFitsner** [comment]
There is a working item for that, but right now it's only by providing customized `manifest.json` and images in "assets" directory, like in example @ndonkoHenri shared.

**Comment by kmranrg** [comment]
Okay, thanks for the update!

**Comment by kmranrg** [comment]
Hello Feodor,

Thanks for your swift response!

Hello @ndonkoHenri,

Even after executing your program using `flet main.py` I still can't see your app logo. It's still showing the default Flet logo.

.......................................................................
Thanks & Regards,
Kumar Anurag
________________________________

**Comment by ndonkoHenri** [comment]
I mentioned [here](https://github.com/flet-dev/flet/issues/479#issuecomment-1278251575) that in hot reload mode, the custom manifest.json is not loaded.

Run the program normally. (Without hot reload)

**Comment by kmranrg** [comment]
Hello @ndonkoHenri ,

Thanks a lot! It's working perfectly fine.

Special thanks to @FeodorFitsner who created this amazing and powerful framework. We're good to close this case now.

Regards,
Anurag
