### ISSUE TITLE
libgstapp shared libraries not available on WSL2

### ISSUE THREAD

**Issue by frankhuurman** [flet-dev/flet#670]
**Description**

When trying to run the Basic app structure Flet docs example on WSL2(Ubuntu 20.04) I get an error that libgstapp is not a file or directory.
Perhaps this is because of the way WSL works that some shared files aren't available that are normally available in a full Ubuntu install? I can't seem to find this lib on apt.

Flet was installed in a venv with Python 3.8.10.
**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    # add/update controls on Page
    pass

ft.app(target=main)
```

**Describe the results you received:**

```python
/home/myuser/.flet/bin/flet-0.3.0.dev892/flet/flet: error while loading shared libraries: libgstapp-1.0.so.0: cannot open shared object file: No such file or directory
```

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/19980966/205512280-e563dd2e-7cca-4b54-8db5-a086d266f5ca.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.3.0.dev892
```

This is a pre-release but I've had the same results with Version: 0.2.2

**Operating system**:

Ubuntu 20.04 on Windows 10 (WSL2).

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Thank you for creating the issue and sorry for not following up on Discord earlier.

So, the issue is missing GStreamer libraries that can be installed in WSL with the following commands:

```
sudo apt-get update
```

and then:

```
sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
```

I've just tested on my WSL Ubuntu 20.04 installation and it worked like a charm.

**Comment by frankhuurman** [comment]
Ah no problem, appreciate it a lot that you responded to this so quickly!

I installed all the libraries you recommended and got to the point I'm running into a GTK error:
```bash
Unable to init server: Could not connect: Connection refused

(flet:20159): Gtk-WARNING **: 21:37:15.320: cannot open display:
```

Tried with both the pre-release version and the 0.2.2 one.

**Comment by FeodorFitsner** [comment]
https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by frankhuurman** [comment]
Seems that I don't have an x11 Socket, thanks for the link!
I'll just run flet on PopOS! for now until I get WSL sorted out.

Maybe you could add the Gstreamer libs to a FAQ for people running WSL?

Closing ticket :)

**Comment by eeintech** [comment]
Hello @FeodorFitsner I have a question related to this.

I have switched to Windows 11 and cannot get Flet app to run the basic example (from OP), I'm only getting a phantom window:

![image](https://github.com/flet-dev/flet/assets/4020546/c664071a-16d2-49e1-9b2a-bb103f8b79bd)

However, if I set the app to launch on browser, and with firefox install on WSL, it works fine:

![image](https://github.com/flet-dev/flet/assets/4020546/2c7fc227-044a-4dbd-ae96-67015bdc2a6c)

I have tested with different versions of Flet (0.5.2 and 0.7.4) and always have the same results...

Do you have it working on your side?
I have tested my old Tkinter app to verify my X11 server setup and it works fine:

![image](https://github.com/flet-dev/flet/assets/4020546/df53ad4f-3104-420c-a018-ce63ed21cdc0)

So at this point I starting thinking it is a problem on Flet side? Or Windows 11?

**Comment by FeodorFitsner** [comment]
A minimal program would be this - you should add at least something:

```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Text("Hello"))

ft.app(target=main)
```

**Comment by FeodorFitsner** [comment]
How do you run Flet app? It looks like you are running it from WSL?...

**Comment by eeintech** [comment]
@FeodorFitsner Yes WSL (Ubuntu 22.04) on Windows 11, that's why I added my question here 😃 
I can open a new issue if you'd like

**Comment by FeodorFitsner** [comment]
Have you checked this: https://flet.dev/docs/guides/python/getting-started/#wsl ?

**Comment by FeodorFitsner** [comment]
Are you able to run Flet apps as Windows apps, without WSL?

**Comment by eeintech** [comment]
Yes on a Linux machine it's completely fine.

**Comment by eeintech** [comment]
And sorry yes Windows with Git bash is fine too.

**Comment by eeintech** [comment]
@FeodorFitsner Should I open a new issue?

**Comment by FeodorFitsner** [comment]
So, it's WSL-only issue?

**Comment by FeodorFitsner** [comment]
OK, then this issue is fine I think.

**Comment by eeintech** [comment]
Ok great, please let me know if you need any other information, I'd really like to get this working 😃

**Comment by eeintech** [comment]
@FeodorFitsner Have you had to chance to take a closer look?
