### ISSUE TITLE
Whether to consider Drag Nodes

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#672]
**Please Describe The Problem To Be Solved**

Whether to consider Drag Nodes

![imnodes](https://user-images.githubusercontent.com/6490927/205535093-f83d9a7b-0a19-4267-b65b-010ec08fdb70.gif)
![drawflow](https://user-images.githubusercontent.com/6490927/205535254-513c378d-7c2a-4cab-bb76-a22847df2215.gif)

**(Optional): Suggest A Solution**

`https://github.com/jerosoler/Drawflow`
`https://github.com/Nelarius/imnodes`

**Comment by FeodorFitsner** [comment]
Is there an analog for Flutter?

**Comment by ZeroCool940711** [comment]
@FeodorFitsner I found [this repo](https://github.com/saurabhguptarock/TisScript) which could be useful, it is a visual programming editor for dart.

**Comment by monkeycc** [comment]
I think the effect is hard to achieve,

So I suggest giving up
