### ISSUE TITLE
How to quit the app from inside the app?

### ISSUE THREAD

**Issue by DaedlyKitten** [flet-dev/flet#673]
for desktop apps.

quit() or sys,exit() doesnt seem to work

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/page#window_close

https://flet.dev/docs/controls/page#window_destroy

Don't really know the difference between the two, but they both seem to be able to solve your problem.
Let me know if it works.

**Comment by DaedlyKitten** [comment]
Thank you!!
