### ISSUE TITLE
Is their any in-built method for creating `TextField` with suggesions?

### ISSUE THREAD

**Issue by ipritom** [flet-dev/flet#683]
For many application if input text can generate suggestions (not `hint_text`) it will be very helpful for users. Is there any method in Flet for this?

![image](https://user-images.githubusercontent.com/16554898/206349287-6e097b79-4fad-473b-b251-55c50df28992.png)

**Comment by mswastik** [comment]
Yes really need this either in `TextField` or in `Dropdown`

**Comment by FeodorFitsner** [comment]
Dup of #791
