### ISSUE TITLE
Flet ```MaterialState``` in ```ButtonStyle``` throws a TypeError

### ISSUE THREAD

**Issue by rohitsathish** [flet-dev/flet#685]
When setting the style properties for a ```TextButton```,```MaterialState``` throws a type error. I was able to replicate the same with example provided in the docs.

app.py
```
style = ft.ButtonStyle(
    color = {
        ft.MaterialState.DEFAULT: ft.colors.WHITE,
        ft.MaterialState.HOVERED: ft.colors.LIGHT_BLUE,
    },
    bgcolor = {
        ft.MaterialState.FOCUSED: ft.colors.LIGHT_BLUE
    }
)
```

error
```
TypeError: keys must be str, int, float, bool or None, not MaterialState
````

Flet 0.2.4
Windows 11

**Comment by ndonkoHenri** [comment]
Hum, Just had thesame issue.
instead of `ft.MaterialState.DEFAULT` for example, you need to use `ft.MaterialState.DEFAULT.value`

After this change it should work now..

**Comment by ndonkoHenri** [comment]
@FeodorFitsner , seems like there are alot of changes to do on website with these Enums addition..

**Comment by FeodorFitsner** [comment]
Yep 😟. I've changed most of the examples here and there but there are more.

**Comment by FeodorFitsner** [comment]
I'm looking into this issue with MaterialState.
