### ISSUE TITLE
Persist ```PopupMenu``` when clicking on checkbox items.

### ISSUE THREAD

**Issue by rohitsathish** [flet-dev/flet#686]
Currently, even when a checkbox item is selected from ```PopupMenu```, it closes after the selection is made. This is not the expected behaviour for menus (for example, if you're toggling between dark/light mode, you would want to see the changes before exiting the menu. You might also want to make changes to other checkbox items before exiting the menu). When a checkbox is selected, there should be an option to allow the menu to persist.

A possible solution is to introduce a property for checkbox items with ```persist = True``` to keep the menu open in case that checkbox item is selected.

**Comment by ndonkoHenri** [comment]
I haven't found how this is done in Flutter.
Also, I don't think this is a behaviour accepted by M3.

**Comment by ndonkoHenri** [comment]
Closing this for now as I haven't found a solution for this in Flutter.

If you find a way, please let know.
