### ISSUE TITLE
Rendering flet app into html, css and javascript

### ISSUE THREAD

**Issue by MosTafa2K** [flet-dev/flet#688]
Hello, today I was writing a student project using **flet** and I needed to have an output in the form of **HTML, CSS and JavaScript** files from my project, but I saw that this feature is not available in **flet**. Will this feature be added in the future?

**Comment by dragondjf** [comment]
https://github.com/scriptiot/evue
@MosTafa2K

**Comment by MosTafa2K** [comment]
> https://github.com/scriptiot/evue @dragondjf 

Cool, it looks like an interesting project, but I think it needs a little improvement😀
