### ISSUE TITLE
Add `dense` property to `TextField` and `Dropdown` controls

### ISSUE THREAD

**Issue by miguelagve** [flet-dev/flet#690]
Hello, I'm trying to develop a simple desktop application with multiple `TextField` objects. The default dimensions are much taller that what I'm looking for, and as far as I can tell from Flutter documentation, the best way to modify this is changing the `decoration` property of the `TextField`, that takes an `InputDecoration`. 

Could this class implemented in flet, as well as the corresponding property to use it?

I wonder if there's any workaround to achieve this effect at the moment.

Thank you

**Comment by FeodorFitsner** [comment]
Thanks for trying Flet!

InputDecoration is flattened into multiple properties in Dropdown and TextField. Which properties are you missing?

**Comment by miguelagve** [comment]
As far as I can tell, a combination of `isDense` and `contentPadding` would do the job.
 
I've just realized that `TextField` in Flet contains the property `content_padding` but, while it allows me to increase the height, it doesn't manage to decrease it any further than default no matter the value I use.

**Comment by FeodorFitsner** [comment]
Yep, `content_padding` corresponds to that property.

So, I'm going to add `isDense` property then.

**Comment by miguelagve** [comment]
Thank you very much!
I've submitted a pull reques to update the documentation about this property (flet-dev/website#81)

**Comment by FeodorFitsner** [comment]
The change is here: https://pypi.org/project/flet/0.3.0.dev923/

**Comment by miguelagve** [comment]
I've had the chance to give it a try and it does exactly what I wanted. Many thanks!!
