### ISSUE TITLE
How component interact with background thread or process?

### ISSUE THREAD

**Issue by leeleilei** [flet-dev/flet#70]
Hi there, I look through the doc and did not find a case of demonstration the concept id signal or slot which is used for interaction between components or thread/process.

Could anyone give some idea of how to do that manually?

Thanks

**Comment by FeodorFitsner** [comment]
Could you please elaborate what you are trying to do?

**Comment by FeodorFitsner** [comment]
I'm closing this issue. If you have a question please [start a new discussion](https://github.com/flet-dev/flet/discussions).
