### ISSUE TITLE
Run a flet app in the background. 

### ISSUE THREAD

**Issue by carefreeGod** [flet-dev/flet#719]
Flet is doing a great job now! I wrote my own chat program in 72 lines of code after reading the documentation for less than a day (some of the code is borrowed from the official example, of course). On my local machine, I can either run a Python program I 've written or build a service using the Flet CLI, but on my server, I prefer it to run in the background. Although I can use the ‘nohup python main.py &’ statement to get my way, it 's too much trouble to do it all the time. Hopefully you will consider adding this functionality to a future version of the CLI. Thanks. 

现在的Flet做得很好！我只是看了不到一天的文档就用72行代码自己写了一个聊天程序（当然，有一些代码还是借鉴了一下官方给的示例）。在本地电脑上，我可以直接运行编写好的Python程序或者使用Flet CLI搭建服务，但是在我的服务器上，我更希望它能在后台运行。虽然我可以使用nohup python main.py &语句达成我的目的，但是一直这样未免过于麻烦。希望你们能够考虑将这个功能加入未来某个版本的CLI中。谢谢。

**Comment by apumapho** [comment]
@carefreeGod you can try running flet using a systemd service as per [Self Hosting: Automatically Start Flet Server](https://flet.dev/docs/guides/python/deploying-web-app/self-hosting#automatically-start-flet-server)
