### ISSUE TITLE
Is there any way you can make BottomSheet transparent or invisible without it affecting the content?

### ISSUE THREAD

**Issue by ayamEdwin** [flet-dev/flet#744]
I used border radius on a Container inside a BottomSheet. The border radius only affects the container and by so doing the bottom sheet still shows. Is there any way to correct this?
I tried opacity but it affects everything.
When I put visible to false it doesn't show the content.
Thank you
![sheet](https://user-images.githubusercontent.com/110039131/208887394-7496e888-ff95-43e7-b7af-3a7948b9252f.jpg)

**Comment by FeodorFitsner** [comment]
Would you share a code sample please?

**Comment by ayamEdwin** [comment]
Sure

**Comment by ayamEdwin** [comment]
Sample code here....the bottom sheet still shows after creating a border
radius with the container. Thanks Foeder , more grease to your elbow ❤️
