### ISSUE TITLE
PlotlyChart module keeps loading and cannot display the chart properly

### ISSUE THREAD

**Issue by anine09** [flet-dev/flet#758]
When I try to use the [example](https://github.com/flet-dev/examples/blob/main/python/controls/charts/plotly-linechart.py) on the official website, the program keeps loading and won't display the chart properly for a long time.

my `flet` version is `0.3.0.dev954`.

![image](https://user-images.githubusercontent.com/30095629/206831847-2bbd3177-7bf9-41ce-9280-d6995296c253.png)

**Comment by anine09** [comment]
update issue

**Comment by anine09** [comment]
On Ubuntu 22.04 is **OK**, But on Windows 10 is not.

**Comment by ndonkoHenri** [comment]
I am using Windows 10 too, and when I try the code the same issue appears (endless loading).
I copied the [code](https://flet.dev/docs/controls/plotlychart#line-chart) from the official doc (not that different actually), and had this:
![image](https://user-images.githubusercontent.com/98978078/209581326-e7181c32-8c59-418e-b312-3a646a1fac14.png)

**Comment by anine09** [comment]
well, I have installed it. It does not pop up any error message.

**Comment by ndonkoHenri** [comment]
Is it working now?

**Comment by anine09** [comment]
I think I have solved the problem. [kaleido is not working on some machines for some reason](https://github.com/plotly/Kaleido/issues/126), I installed kaleido with `v0.1.0post1` and flet shows the charts properly.

**Comment by ndonkoHenri** [comment]
Thanks for your feedback on this.
