### ISSUE TITLE
NavigationRailDestination without hover

### ISSUE THREAD

**Issue by foozzi** [flet-dev/flet#769]
![Screenshot from 2022-12-26 21-59-37](https://user-images.githubusercontent.com/1178208/209580072-ccbc88f8-848d-400a-8437-6d3f7b9f9100.png)

Is it possible to remove NavigationRailDestination holder like in the screenshot?

**Comment by ndonkoHenri** [comment]
I want to help, but don't really seem to understand.
Can you please show us 'what happens' VerSus 'what you expect/want to achieve'?
Thanks..

**Comment by foozzi** [comment]
> I want to help, but don't really seem to understand. Can you please show us 'what happens' VerSus 'what you expect/want to achieve'? Thanks..

I mean remove it:
![Screenshot from 2022-12-26 21-59-37](https://user-images.githubusercontent.com/1178208/209581865-1731931d-5db1-49b4-9efc-b66f0cd45350.png)

**Comment by FeodorFitsner** [comment]
I don't think it's possible, but you can implement your own navigation rail using other Flet primitives like container, text, buttons.
