### ISSUE TITLE
How can I get real width and heigth of containers?

### ISSUE THREAD

**Issue by Sangwon91** [flet-dev/flet#773]
First of all, thank you for the good library. I really enjoy this these days.

I'm working on creating an interactive chart using matplotlib. In order to implement this, the display coordinates (the pixel position of the container) must be converted into data coordinates.

However, width and height are not explicitly provided. The original size of svg image is not helpful because the actual size of the container is resizable.

Is there a way to save these properties?

Thank you again for your tremendous effort!

**Comment by FeodorFitsner** [comment]
Ah, that's a good ask. What I'm thinking to do is to implement `on_resize` event handler for container which will provide dimensions in the event object.

**Comment by FeodorFitsner** [comment]
Possible solution: https://stackoverflow.com/a/60868972/1435891

**Comment by Sangwon91** [comment]
That sounds great. I hope the `on_resize` is implemented soon. Then I think I can provide an example of an interactive chart implementation using matplotlib and flet.

Thank you!

**Comment by mikaelho** [comment]
Would the resize event be called also when the control is first shown on-screen? This would be valuable when wanting to fill the control with e.g. the right amount of map tiles.

Related issue is getting/setting the current scroll position of a scrollable.

**Comment by FeodorFitsner** [comment]
Flet 0.6.0 is introducing `Canvas` control which can be used to get the size of its contents:

```python
import flet as ft
import flet.canvas as cv

class SizeAwareContainer(cv.Canvas):
    def __init__(self, color, expand):
        super().__init__(expand=expand)
        self.size = ft.Text()
        self.content = ft.Container(
            self.size,
            alignment=ft.alignment.center,
            bgcolor=color,
        )
        self.resize_interval = 100
        self.on_resize = self.canvas_resize

    def canvas_resize(self, e):
        self.size.value = f"{int(e.width)} x {int(e.height)}"
        self.update()


def main(page: ft.Page):
    page.add(
        ft.Row(
            [
                SizeAwareContainer(ft.colors.RED, expand=2),
                SizeAwareContainer(ft.colors.GREEN, expand=4),
            ],
            expand=2,
        ),
        ft.Row(
            [
                SizeAwareContainer(ft.colors.YELLOW, expand=2),
                SizeAwareContainer(ft.colors.BLUE, expand=4),
            ],
            expand=3,
        ),
    )

ft.app(main)
```

![image](https://user-images.githubusercontent.com/5041459/234669419-1de2cf2d-718b-4088-b115-322e786741b5.png)

Canvas can contain a child control as well as be a child of another control.

**Comment by ndonkoHenri** [comment]
I think this should be documented somewhere please.

**Comment by mikaelho** [comment]
Thanks! Looks like this can be used for many useful things.

As the size capture is an event on Python side, do we have a performance concern if I see myself applying this to a lot of controls on one page?

**Comment by FeodorFitsner** [comment]
It could be a concern, yes. There is `resize_interval` property to reduce the frequency of event "sampling".
