### ISSUE TITLE
fletd issue ‘dyld: Symbol not found: _utimensat’ on macOS 10.12.6

### ISSUE THREAD

**Issue by ybz-zh** [flet-dev/flet#779]
**Description**

**Code example to reproduce the issue:**

```
import flet as ft
def main(page: ft.Page):
    # add/update controls on Page
    pass
ft.app(target=main)
```

Error message

Flet version:
flet-0.2.4

Python version:
Python-3.7.5

macOS version:
10.12.6

**Comment by ndonkoHenri** [comment]
Can you try this instead please?

```python
import flet as ft

def main(page: ft.Page):
    t = ft.Text(value="Hello, world!", color="green")
    page.controls.append(t)
    page.update()

ft.app(target=main)
```
You should be able to see a "Hello World".
Let me have your feedback if your said issue persists.

**Comment by FeodorFitsner** [comment]
I don't think Flutter 3.x is compatible with macOS Sierra.

Despite the official docs are [saying "macOS 10.11 and later"](https://docs.flutter.dev/deployment/macos#review-xcode-project-settings) I think that was for Flutter 2.x or docs are just not updated. Look, there is an [issue](https://github.com/flutter/flutter/pull/107689) to increase macOS requirements from 10.11 to 10.13 which is merged on July and there is even [another issue](https://github.com/flutter/flutter/issues/114445) (still open) to bump it even further from 10.13 to 10.14 (Mojave which is [EOT a year ago](https://endoflife.date/macos)).

**Comment by ybz-zh** [comment]
Thanks :) @ndonkoHenri @FeodorFitsner 

Looks like a incompatibility issue.

$ ./fletd -v
0.2.4
$ ./fletd
INFO[2022-12-29T20:47:01+08:00] Using in-memory cache                        
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
 ...
$ sw_vers
ProductName: Mac OS X
ProductVersion: 10.14.6


$ ./fletd -v
dyld: Symbol not found: _utimensat
  Referenced from: /Users/xxx/.flet/bin/fletd-0.2.4/./fletd
  Expected in: flat namespace

Abort trap: 6
$ ./fletd 
dyld: Symbol not found: _utimensat
  Referenced from: /Users/xxx/.flet/bin/fletd-0.2.4/./fletd
  Expected in: flat namespace

Abort trap: 6
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6

**Comment by FeodorFitsner** [comment]
Go is in the same situation: https://github.com/golang/go/issues/50855 - recent versions of Go are not compatible with macOS 10.12.
