### ISSUE TITLE
Build for Android and using other flutter plugins 

### ISSUE THREAD

**Issue by hardesh** [flet-dev/flet#78]
Hi,

Thanks for this awesome package! Absolutely love this!

I have some questions:
1. Is it possible to compile the app as an android app? If yes, I'd appreciate any leads on this 
2. How can use other flutter plugins with flet? 

Thanks,
Harshal

**Comment by FeodorFitsner** [comment]
Hi Harshal,

Thanks for trying out Flet!

We are working on mobile support and we should have something pretty soon. Of course, delivering to Androind is on the map.

**Comment by FeodorFitsner** [comment]
I'm afraid not. To use any 3rd-party plugins with Flet they must be "implemented" in Flet. What widgets are you missing?

**Comment by hardesh** [comment]
Hi, 
I just went through the src code. If i've understood correctly, you have a separate flutter app that has all the supported plugins. When we run the python script, you're downloading the flutter app and starting the websocket connection with the python app. The attributes of the widgets are then sent to the app using websocket.

If this is correct, I have some thoughts:
1. Can we specify the download location of the flet app through the API of `flet.app()`? - since the app is getting downloaded in the `/tmp` directory delete automatically on most systems. 
2. Would love to know about your approach towards android and iOS.

**Comment by FeodorFitsner** [comment]
Answers to your questions:

1. It's being unpacked to a temp directory for now, but please feel free to submit a new issue to implement that in `flet.app()` call.
2. Please see [Flet Mobile Strategy](https://flet.dev/blog/flet-mobile-strategy).

**Comment by hardesh** [comment]
Thanks for the reply. 
1 -> 

> please feel free to submit a new issue to implement that

Okay. I can submit a PR as well :smiley: 

2 -> Thanks. Will go through it

**Comment by FeodorFitsner** [comment]
Sounds great! In the meantime I'm going to close this issue. Feel free to start a [new discussion](https://github.com/flet-dev/flet/discussions) if you have any questions.
