### ISSUE TITLE
Change App Icon Without Packaging

### ISSUE THREAD

**Issue by TingTingin** [flet-dev/flet#783]
Is it possible to change the app icon and name without packaging the app?

**Comment by FeodorFitsner** [comment]
https://github.com/flet-dev/flet/pull/770 will add `flet pack` command, when merged, which allows changing app bundle icon and metadata. It's just docs needs to be finished. I'm going to complete it early next week. 

Closing as a dup of https://github.com/flet-dev/flet/issues/113
