### ISSUE TITLE
How to change name and icon in android ???

### ISSUE THREAD

**Issue by alexyucra** [flet-dev/flet#785]
I installed 2 flet app in android, after installing the 2 icons are the same, how can i change this icon and app name?
I have searched in several places how to be able to change to distinguish.

![image](https://user-images.githubusercontent.com/114123162/210179141-83c5b93f-b644-4c38-8fa0-e1c6e8b3c8e7.png)

into web browser, too, how to change icon.ico?

![image](https://user-images.githubusercontent.com/114123162/210179336-5e47d042-c274-4bde-9c39-dc53bb0bb970.png)

**Comment by FeodorFitsner** [comment]
Here is an example: https://github.com/flet-dev/examples/tree/main/python/apps/custom-loading-image

**Comment by ndonkoHenri** [comment]
@FeodorFitsner this is a real concern.
Changing all the icons (as I always do) has no effect on the image rendered on the browser tab. (I could provide deployed examples if you wish)

If you were not aware of this behavior, please consider it.
