### ISSUE TITLE
3rd Party Flutter Plugins Support?

### ISSUE THREAD

**Issue by swarajpeppermint** [flet-dev/flet#79]
Hi Team Flet,

Very excited to see this project! This has a lot of potential for quickly building applications and seamlessly porting existing Python Apps to Modern Technologies and Flutter.

My questions:
- How can we use 3rd party Flutter Plugins with this? Is it planned in the roadmap?
- In case we want to use more advanced Flutter Functionality, does Flet support them somehow? (such as platform specific components, custom animations, Flutter Painter etc.)

**Comment by FeodorFitsner** [comment]
At the moment 3rd-party Flutter Plugins must be explicitly supported in Flet, i.e. there is no ability to load them dynamically.

If you like to see some specific Flutter widget/plugin required by your use case please submit a separate issue per widget. In the meantime, I'm closing this issue.
