### ISSUE TITLE
How to capture a mouse click on a page with an image and draw a dot based on that captured location?

### ISSUE THREAD

**Issue by swarajpeppermint** [flet-dev/flet#80]
What should be the thought process or code to capture the position of a mouse with respect to an image loaded on the window and then paint/draw a dot at that location?

**Comment by FeodorFitsner** [comment]
So, I would put `Image` control into `Container` and added [`on_click` handler](https://flet.dev/blog#clickable-container) to container. In event's `data` you will receive a string with both local (relative to container position) and global (relative to app window) mouse pointer coordinates in the format `local_x:local_y global_x:global_y`. Then, `Container` could be put into `Stack` and finally dots could be containers with round corners [positioned absolutely inside Stack](https://flet.dev/blog#absolute-positioning-inside-stack). Let me know if you need a code example :)

**Comment by swarajpeppermint** [comment]
Thanks! Will try this approach when we get the time and get back to you if we need more help. Closing this issue for now.

**Comment by YouJiacheng** [comment]
I'd like to leave a note: if `ink` is enabled, event `data` will be empty.(version: 0.1.59) This is feature, not bug.
I spent 30 minutes on this, hope this note can help others!
