### ISSUE TITLE
Page transition without animation

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#808]
### Discussed in https://github.com/flet-dev/flet/discussions/806

<div type='discussions-op-text'>

<sup>Originally posted by **Allen-Taylor** January  5, 2023</sup>
First, thank you for Flet. I am thinking about making it my "go to" for making GUIs. 

I have a quick question about Themes and Page Transitions. I understand the Flet supports 4 transition types: 
FADE_UPWARDS, OPEN_UPWARDS, ZOOM, and CUPERTINO.

My question is: is there a way to have page transitions without the animations? I want no animation between the transition between views. 

I tried: 

**theme = Theme()
theme.page_transitions.android = None
theme.page_transitions.ios = None
theme.page_transitions.macos = None
theme.page_transitions.linux = None
theme.page_transitions.windows = None
page.theme = theme
page.update()**

Any help would be greatly appreciated!

-Al</div>

**Comment by FeodorFitsner** [comment]
Solution: https://stackoverflow.com/a/71636856

**Comment by eeintech** [comment]
@FeodorFitsner Can those 5 lines:
``` python
theme.page_transitions.android = None
theme.page_transitions.ios = None
theme.page_transitions.macos = None
theme.page_transitions.linux = None
theme.page_transitions.windows = None
```

be combined into one?

``` python
theme.page_transitions.all = None
```

Thanks!
