### ISSUE TITLE
Is there a possibilty of using flet for Artificial Intelligence?

### ISSUE THREAD

**Issue by drexhacker** [flet-dev/flet#81]

**Comment by drexhacker** [comment]
Would like to know if there is any plans of implementing support for programs like opencv, numpy, pandas, tensorflow, pytorch and other similar programs as these will really  benefit Machine Learning Engineers and more. Thank you!

**Comment by FeodorFitsner** [comment]
You mean visualising that data with Flet?

**Comment by Yuribtr** [comment]
> Would like to know if there is any plans of implementing support for programs like opencv, numpy, pandas, tensorflow, pytorch and other similar programs as these will really benefit Machine Learning Engineers and more. Thank you!

Flet is pretty but too young for such hard work. I would like to consider [DearPyGUI](https://github.com/hoffstadt/DearPyGui) which has a lot of visualization options.

**Comment by FeodorFitsner** [comment]
Flet app is just a regular Python app + Flet UI. You are talking about visualization support for those libraries, right?

**Comment by drexhacker** [comment]
YES

**Comment by FeodorFitsner** [comment]
OK, thanks. Let's post separate issues to implement specific controls, one control per issue. In the meantime, I'm going to close this issue.

**Comment by drexhacker** [comment]
Yes and even more
