### ISSUE TITLE
Load local image, some ok but some fail

### ISSUE THREAD

**Issue by makao007** [flet-dev/flet#810]
Hi, I try to load and show local image, but some images are ok, but some fail.
I found the images larger than 3MB will fail.
Could somebody help to fixed it ?

```python
import flet as ft
import base64

def get_base64(image_path):
    with open(image_path, "rb") as img_file:
        my_string = base64.b64encode(img_file.read()).decode('utf-8')
        return my_string


def main(page : ft.Page):
    page.title = "image viewer"

    image = ft.Image(src_base64=get_base64('butterfly.jpg'), height=500, width=500)

    page.add(image)
    page.update()

ft.app(target=main)

```

_Originally posted by @ipritom in https://github.com/flet-dev/flet/issues/651#issuecomment-1336208307_

**Comment by FeodorFitsner** [comment]
You don't need to convert the image into base64 and squeeze it through the wire (there is a default limit on WebSockets message size). Instead, utilize "assets" folder: https://flet.dev/docs/controls/image#src - put image to "assets" folder and then load it by URL.

**Comment by makao007** [comment]
in my case, I use a FilePicker to chose the file on my computer which return a absolute file path.
I can't just copy the file into assets and show it.

**Comment by FeodorFitsner** [comment]
I see. What we need is an ability to load an image from a local path.

I'm going to implement that shortly. Closing in favour of https://github.com/flet-dev/flet/issues/651

**Comment by FeodorFitsner** [comment]
#651 was merged into `main`. `Image` now supports local file paths in `src` property though it works in desktop app only.
You can give it a try by installer pre-release Flet package with `pip install flet --pre`.
