### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by comdav** [flet-dev/flet#820]
In page: https://flet.dev/docs/guides/python/getting-started
1) Section: Basic app structure

Info box:
in the code: 
`flet.app(port=8550, target=main)`
is missing the view option:
`flet.app(port=8550, target=main, view=ft.WEB_BROWSER)`

2) Section: Controls

in the code:
```
for i in range(10):
   t.value = f"Step {i}"
   page.update()
   sleep(1)
```

in sleep(1) statement is missing 
`ft. `

**Comment by FeodorFitsner** [comment]
1. That was the idea - to show that you open a desktop version of app, but at the same time you can open it in the browser.
2. Could you paste the exact URL?

**Comment by comdav** [comment]
Hi,
URL: https://flet.dev/docs/guides/python/getting-started#controls

![image](https://user-images.githubusercontent.com/64091690/211162388-cf6018d1-534e-4fc7-83d4-c794fee657d8.png)

**Comment by FeodorFitsner** [comment]
oh, that sleep is `threading.sleep`.
