### ISSUE TITLE
No stdout/sterr printouts when run with Docker

### ISSUE THREAD

**Issue by langfingaz** [flet-dev/flet#823]
**Description**

When a Flet application is started inside a Docker container, one does not see the output of `print()` calls (to `stdout`/`stderr`).

**Code example to reproduce the issue:**

In #625 a full docker/docker-compose example is given: https://github.com/pangoro24/pyflet

It can be built and started by running `sudo docker-compose up`.

The only python file, `app/main.py`, contains a print statement:

```python
import flet as ft
print("Webserver is starting...")
def main(page: ft.Page):
    page.add(ft.Text(value="Hello world from containerized Flet app!"))

ft.app(target=main, view=None)
```

**Describe the results you received:**

```
linuxUser ~/Downloads/git/pyflet (git)-[master] % sudo docker-compose up
[+] Running 1/0
 ⠿ Container fletappcontainer  Created                                     0.0s
Attaching to fletappcontainer
```

**Describe the results you expected:**

When `ft.app(target=main, view=None)` is commented out, one does see the `print()` output:

```
linuxUser ~/Downloads/git/pyflet (git)-[master] % sudo docker-compose up   
[+] Running 1/1
 ⠿ Container fletappcontainer  Recreated                                   0.1s
Attaching to fletappcontainer
fletappcontainer  | Webserver is starting...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

In the mentioned example, `requirements.txt` contains `flet==0.1.65`.

I have tried different Flet versions until `flet==0.4.0.dev1011` but all behave the same.

**Operating system**:

uname -r: 6.1.3-arch1-1
docker: 1:20.10.22-1
docker-compose: 2.14.2-1

**Comment by langfingaz** [comment]
Well, adding `ENV PYTHONUNBUFFERED=1` to the Dockerfile resolves this problem.

However, it still looks very strange to me. Why is there no output with `ft.app(target=main, view=None)` at the end?

**Comment by FeodorFitsner** [comment]
Right, Flet does not interfere with print() in anyway and those calls are before `ft.app()`. What output do you expect with `ft.app(target=main, view=None)`?

**Comment by langfingaz** [comment]
Thanks for the quick response!

I would expect to see `Webserver is starting...` in the output of the running Docker container.

Maybe it's clearer with the print statement right before the `ft.app()` line:

```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Text(value="Hello world from containerized Flet app!"))

print("Webserver is starting...")
ft.app(target=main, view=None)
```

However, the output I get is only:

```
linuxUser ~/Downloads/git/pyflet (git)-[master] % sudo docker-compose up   
[+] Running 1/1
 ⠿ Container fletappcontainer  Recreated                                   0.1s
Attaching to fletappcontainer
```

**Comment by FeodorFitsner** [comment]
But you are saying `ENV PYTHONUNBUFFERED=1` helps?

**Comment by langfingaz** [comment]
Yes, with `PYTHONUNBUFFERED` I get one more line of output:

```
fletappcontainer  | Webserver is starting...
```

**Comment by langfingaz** [comment]
> Flet does not interfere with print() in anyway

Maybe it is some bug of Docker or the Python Docker image? The use of `PYTHONUNBUFFERED` does not bother me further, so we can close the issue as solved. Not sure if you have further ideas and time to look into this.

**Comment by FeodorFitsner** [comment]
I'm sure it's Python's buffering. `flet run` CLI also uses unbuffering while running python executable.
