### ISSUE TITLE
UnicodeDecodeError, Use flet run .\main.py, Cannot print chinse

### ISSUE THREAD

**Issue by achieve-dream1221** [flet-dev/flet#828]
**Description**

When I use `python main.py`,  this is correct, but when i use `flet run .\main.py`, this program **cannot print chinese**
**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.title = "One"
    page.theme_mode = ft.ThemeMode.LIGHT

    def nav_on_change(e: ft.control_event.ControlEvent):
        print("中文")
        match e.data:
            case "0":
                print("one")
            case "1":
                print("two")
            case "2":
                print("three")
            case _:
                print("other")

    page.navigation_bar = ft.NavigationBar(destinations=[
        ft.NavigationDestination(icon=ft.icons.EXPLORE, label="Explore"),
        ft.NavigationDestination(icon=ft.icons.COMMUTE, label="Commute"),
        ft.NavigationDestination(
            icon=ft.icons.BOOKMARK_BORDER,
            selected_icon=ft.icons.BOOKMARK,
            label="Explore",
        ),
    ], bgcolor=ft.colors.GREEN_50, elevation=1, label_behavior=ft.NavigationBarLabelBehavior.ALWAYS_HIDE,
        on_change=nav_on_change)
    page.add(
        ft.Text("Body"),
        ft.ElevatedButton(text="打印中文", on_click=lambda _: print("中文"))
    )


if __name__ == '__main__':
    ft.app(target=main)

```

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/57209087/211179300-ad3f05ab-0087-4c01-8056-75595d34a7c8.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/57209087/211179281-0c0b905f-e3f0-4665-b011-a53ec385a4a9.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Version: 0.4.0.dev988

```

**Operating system**:

WIndows
**Additional environment details:**

**Comment by FeodorFitsner** [comment]
As a workaround run with `python` directly, without `flet run`:

    python main.py

**Comment by achieve-dream1221** [comment]
> 
I know this way, but I want to use the **[hot reload](https://flet.dev/docs/guides/python/hot-reload)**

**Comment by ndonkoHenri** [comment]
Should be solved with this proposal: https://github.com/flet-dev/flet/issues/863

**Comment by FeodorFitsner** [comment]
Could you please try encoding fix with pre-release version of Flet module:

```
pip install flet --upgrade --pre
```

and let me know if that worked. Thanks!

**Comment by yuanaki9090** [comment]
Thank you, the same error in Japanese has been solved.

**Comment by achieve-dream1221** [comment]
> 

It's worked! Thank you very much!
