### ISSUE TITLE
Customizing macOS app bundle with flet pack not working

### ISSUE THREAD

**Issue by clstaudt** [flet-dev/flet#832]
As described here: https://flet.dev/docs/guides/python/packaging-desktop-app/#customizing-macos-bundle

**Code example to reproduce the issue:**

```shell
flet pack app/app.py --name Tuttle --icon app/assets/images/icon.png --product-name Tuttle --product-version 1.0  
```

**Describe the results you received:**

The resulting .app file gets the name and the icon. However, when starting the app with double click:
1. the app appears in the Dock with the custom name and icon and a startup animation
2. the app disappears from the Dock
3. after some loading time, the app reappears in the Dock:
- with the flet default icon
- with the name "Flet"
- apparently unaffected by the `--product-name` and `--product-version` arguments

![Screenshot 2023-01-08 at 18 25 53](https://user-images.githubusercontent.com/875194/211210464-b60f585c-4adc-4c32-aa16-7a1625200a92.png)
![Screenshot 2023-01-08 at 18 26 26](https://user-images.githubusercontent.com/875194/211210467-1de71661-57a5-4caa-b842-251b06543f64.png)
![Screenshot 2023-01-08 at 18 26 43](https://user-images.githubusercontent.com/875194/211210476-33da8df6-c817-492f-88d3-c5e8695777d7.png)

**Flet version (`pip show flet`)**:

```
Version: 0.3.2
```

**Operating system**:

macOS 13.1

**Comment by FeodorFitsner** [comment]
Try running it on a different computer. While developing/testing the feature I noticed macOS does a really hard caching of app bundles. You can also inspect Flet app bundle to see if its `AppIcon.icns` and `.plist` contains modified data. It's being unpacked into `$HOME/.flet/bin/{version}/{product-name}.app` folder.

Also, [this gist](https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224) to clear icon cache helped me a lot.

**Comment by clstaudt** [comment]
I don't know why, but what worked for me is deleting the content of `~/.flet/bin`.

Clearing the cache did not work, possibly because of permissions.

**Comment by FeodorFitsner** [comment]
Good. What do you have there when running your bundled app?

**Comment by clstaudt** [comment]
A folder `flet-0.3.2` with the customized .app bundle.

ps.

- How to set icon, product name etc. when running the app before packaging (`flet app/app.py`) 
- Can the icon be set from an `.icns` file instead of a `.png` file?

**Comment by ndonkoHenri** [comment]
Try [`flet build`](https://flet.dev/docs/guides/python/packaging-app-for-distribution).
