### ISSUE TITLE
Flet web mode at windows have problem

### ISSUE THREAD

**Issue by cyrus0880** [flet-dev/flet#833]
my project on linux is can use host=0.0.0.0
but now i try on windows run is not work
```
app(target=main,host="0.0.0.0",assets_dir="WebUI/assets")
```

show this error log
```
    app(target=main,host="0.0.0.0",assets_dir="assets")
  File "C:\Program Files\Python311\Lib\site-packages\flet\flet.py", line 94, in app
    conn = _connect_internal(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flet\flet.py", line 256, in _connect_internal    
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.
```

can you fix it?

**Comment by FeodorFitsner** [comment]
When `host` is not specified it binds to all NIC IPs. You don't need `0.0.0.0`.

**Comment by cyrus0880** [comment]
> When `host` is not specified it binds to all NIC IPs. You don't need `0.0.0.0`.
def host is export to all ip access?

**Comment by FeodorFitsner** [comment]
Yes.

**Comment by cyrus0880** [comment]
> Yes.

thx ~~ 
now is work , other pc access can access windows flet web project

i use fastapi if not set host default 127.0.0.1 is only localhost can access

**Comment by FeodorFitsner** [comment]
Fair point! Fortunately, the next release of Flet will have default `127.0.0.1` binding for desktop apps!
