### ISSUE TITLE
Snackbar error in Flet 0.3.x

### ISSUE THREAD

**Issue by certainlyWrong** [flet-dev/flet#836]
I detected that the consecutive use of the Snackbar generates an error when navigating between pages from version 3 of Flet.

**Comment by FeodorFitsner** [comment]
Would you please provide a code sample reproducing the issue?

**Comment by certainlyWrong** [comment]
Apparently the error happens when I call the Snackbar for the second time and try to navigate to another page. I recorded a video reproducing the error that is in the following link. I'm also making available the part of the code where the problem happens.

![code](https://user-images.githubusercontent.com/66525990/211300250-26ad4bd4-d7e6-4646-88ca-cccf8d8fa943.png)

[Reproducing the Issue](https://youtu.be/yf9N6qfKsCk)

**Comment by FeodorFitsner** [comment]
Thanks for the video!

But it's still unclear to me how to reproduce the error. Could you please provide a code sample, in a separate GitHub repo, so I can do a simple clone and reproduce the issue? You can use this app as a template for navigation/routing: https://github.com/flet-dev/examples/blob/main/python/apps/routing-navigation/home-store.py

Thanks!

**Comment by certainlyWrong** [comment]
Hi, I just made the repository available. To work perfectly you will need to create a Mysql Docker container. Here is an example of how I create this container:
docker run -p 3306:3306 --name evilBank -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest

And here is the repository link:
[Evil Bank](https://github.com/certainlyWrong/EvilBank-Desktop/blob/main/src/front/views/deposit/deposit_view.py)

Please don't laugh too much at my code. I'm learning this a little while ago. Also understand that it is in another language, but it is still possible to reproduce the error smoothly. One detail I forgot to mention is that you'll need to update your Flet version, for now I'm using 0.2.4.

**Comment by certainlyWrong** [comment]
I tested it one more time just to confirm. The result is that this problem persists in versions 0.3.x. In fact, the version that still doesn't have this problem is 0.2.4.

**Comment by FeodorFitsner** [comment]
Here's an example I use to test SnackBar with routing and it works for me. Could you try running it and let me know what error are you getting or modify it to simulate your issue?

```python
import logging
from time import sleep

import flet
from flet import (
    AppBar,
    ElevatedButton,
    Page,
    PageTransitionsTheme,
    PageTransitionTheme,
    SnackBar,
    Text,
    Theme,
    ThemeVisualDensity,
    View,
    colors,
)

# logging.basicConfig(level=logging.DEBUG)


def main(page: Page):
    page.title = "Routes Example"

    print("Initial route:", page.route)

    def route_change(route):
        print("Route change:", route)
        page.views.clear()
        page.views.append(
            View(
                "/",
                [
                    AppBar(title=Text("AppBar Example")),
                    ElevatedButton("Go to settings", on_click=open_settings),
                ],
            )
        )
        if page.route == "/settings" or page.route == "/settings/mail":
            page.views.append(
                View(
                    "/settings",
                    [
                        AppBar(title=Text("Settings"), bgcolor=colors.SURFACE_VARIANT),
                        Text("Settings!", style="bodyMedium"),
                        ElevatedButton(
                            "Go to mail settings", on_click=open_mail_settings
                        ),
                    ],
                )
            )
        if page.route == "/settings/mail":
            page.views.append(
                View(
                    "/settings/mail",
                    [
                        AppBar(
                            title=Text("Mail Settings"), bgcolor=colors.SURFACE_VARIANT
                        ),
                        Text("Mail settings!"),
                    ],
                )
            )
        page.update()

    def view_pop(view):
        print("View pop:", view)
        page.views.pop()
        top_view = page.views[-1]
        page.go(top_view.route)

    page.on_route_change = route_change
    page.on_view_pop = view_pop

    def open_mail_settings(e):
        page.snack_bar = SnackBar(Text(f"Opened mail settings"), open=True)
        page.go("/settings/mail")

    def open_settings(e):
        page.snack_bar = SnackBar(Text(f"Opened settings"), open=True)
        page.go("/settings")

    page.theme = Theme(
        visual_density=ThemeVisualDensity.COMFORTABLE,
        page_transitions=PageTransitionsTheme(macos=PageTransitionTheme.CUPERTINO),
    )

    page.go(page.route)


flet.app(target=main, port=8550, view=flet.WEB_BROWSER)
```

**Comment by certainlyWrong** [comment]
Hello @FeodorFitsner and hello everybody. I made some changes following the sample code you provided. I also tested the project in the browser, which I hadn't done so far. The end result is that problem persists in the same way I showed in the video.

**Comment by certainlyWrong** [comment]
Hello everyone, I recently changed the way that the Front-end made in flet communicates with the Back-end. After I finished the changes the Snackbar issue did not recur. I still find the fact that this happened before to be very strange, I can't find logical errors to justify this, but the point is that this was probably a problem particular to my project. Thank you for your patience!
