### ISSUE TITLE
[Feature Request] Generic Keyboard/mouse/touch input that works without the need of a certain widget being in focus

### ISSUE THREAD

**Issue by ItsCubeTime** [flet-dev/flet#840]
## Desired functionality:
* Call a function when a key or mousebutton is pressed
* Check if a key or button is held down
* Get mouse position relative to Window
* Get mouse position relative to the entire desktop screen

If possible it would also be nice if you could:
* Check if the mouse is currently hovering the Flet app
* For multi-monitor computers, check which monitor the cursor is currently on (maybe excessive)
* Check if the caps-lock key is on or off
* Would preferably work on all platforms

## Suggested syntax (psuedo-code):
*(to demonstrate sort of how I would like to be able to use it)*
```py
import flet as ft
import asyncio
def main(page: ft.Page):
    t = ft.Text(value="", color="green")
    page.controls.append(t)
    page.update()
    def my_callback(data):
        q_press_text = "Q was pressed"
        if ft.input.is_key_pressed('ctrl'):
            q_press_text += ". You're also holding ctrl!"
        q_Press_text += f"\n\nYour mouse position in pixels relative to the top left corner of your computer screen is: {ft.input.mouse_pos}"
        if ft.input.caps_lock:
            q_Press_text += "\n\nYour caps-lock key is also active!"
        if ft.input.is_hovering_control(data.page): # @note Would be cool if this could take a reference to any control?
            q_Press_text += "\n\nAnd you're hovering the Flet window!"
        print(q_press_text)
        t.value = q_press_text 
        data.page.update()
        asyncio.sleep(5)
        t.value = ""
        data.page.update()
    def remove_callback(data):
        ft.input.remove_on_key_press(my_callback, 'q') # @note Makes the my_callback function invalid
    ft.input.on_key_press(my_callback, 'q')
    ft.input.on_key_press(remove_callback, 'esc')

ft.app(target=main)
```
## Contributing

Im not very familiar with Dart nor Flutter, but as it doesnt look too difficult to work with I would gladly have a go at contributing with some of this, especially if someone could link me to the parts of the Flutter API that I should be looking at.

After doing some quick google searches I found my way to:
https://api.flutter.dev/flutter/services/RawKeyboard-class.html
But Im not sure what one would use to get mouse loc and lmb/rmb/mmb states? Likewise it says that the RawKeyboard class doesnt support on-screen-keyboards, which I would assume also includes mobile device on-screen-keyboards?

#### Thanks for reading 💝

**Comment by FeodorFitsner** [comment]
https://flet.dev/docs/controls/page#on_keyboard_event
