### ISSUE TITLE
[DataTable] on_selection_change called but checkbox is not updated neither selected attribute of DataRow

### ISSUE THREAD

**Issue by mnesarco** [flet-dev/flet#841]
**Description**
I have created a DataTable with `show_checkbox_column=True` and all rows has on_select_changed set to a simple callback. When the user clicks the checkbox or the row, the callback is called, but the checkbox is not updated, also DataRow.selected value is not updated.

**Code example to reproduce the issue:**

```python
        self.data = ft.DataTable(
            show_checkbox_column=True,
            columns=[col.build_header() for col in self.columns],
            rows=create_rows(),            
        )
```

Rows are created like this:

```python
    def build_row(self, row):
        row_control = ft.DataRow(cells=[col.build_cell(row) for col in self.columns])
        def toggle(x):
            print(x.control.data, x.control.selected)
        row_control.on_select_changed=toggle
        row_control.data = row
        return row_control
```

**Describe the results you received:**

toggle (on_select_changed) callback is called whenever the user clicks the row or the checkbox, but the DataRow.selected value never changes and the row does not reflect the state (obviously because no change)

**Describe the results you expected:**

the toggle callback should be called (as it is) but also the DataRow.selected must reflect selected state and the UI must reflect the state.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.3.2
```

**Operating system**:

Linux Mint 21

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
You have to set the state yourself. 
Implement this in your callback:
```python
def select_changed(e):
    e.control.selected = not e.control.selected
    e.page.update()  # or page.update() directly
```

**Comment by ndonkoHenri** [comment]
Close?
