### ISSUE TITLE
`AutofillGroup` control

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#848]
when creating an authentication page, my browser never asks me if it can save the password for me.

There is an HTML property for `TextField`: `autocomplete="username" and autocomplete="current-password"` that appears to turn this feature on in browsers.  Can we add a property in Textfield to add this to the final HTML? (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).  and here is a stackoverflow answer for flutter: https://stackoverflow.com/questions/67448771/flutter-autofill-login

**Comment by FeodorFitsner** [comment]
Good suggestion!

It requires implementing of [AutofillGroup](https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html) widget.

**Comment by gbrandt** [comment]
Any chance of getting this looked at for 0.9.0?

**Comment by FeodorFitsner** [comment]
Sure!
