### ISSUE TITLE
custom-loading-image , How to modify a title

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#854]
`examples-main\apps\custom-loading-image\main.py`

![微信截图_20230111223349](https://user-images.githubusercontent.com/6490927/211832992-9cb28d54-5acf-462f-a62e-cefa5bb3e618.png)

Load Animation
The title is Flet
How to modify this title

`page.title`
Yes, modify the title after loading successfully
But how to modify this title during loading

**Comment by ndonkoHenri** [comment]
Do you have issues with modifying the loading image?

**Comment by regstuff** [comment]
I'm looking for a solution for this too. Anyway to get this done?

**Comment by ndonkoHenri** [comment]
@regstuff can you outline you issue please?

**Comment by ndonkoHenri** [comment]
I don't this is possible.
Because the script(hence the custom `page.title`) is not yet loaded.

**Comment by FeodorFitsner** [comment]
https://flet.dev/docs/guides/python/deploying-web-app/customizing-web-app
