### ISSUE TITLE
Please wait while the application is being started , How to modify

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#855]
`Please wait while the application is being started..`
Because I want to change it to Chinese

I need to modify this
But it is not clear where to modify it

`/anaconda3/lib/python3.8/site-packages/flet`
Could not find

**Comment by ndonkoHenri** [comment]
Here it is: https://github.com/flet-dev/flet/blob/b87fb5d55bb29fe873ef6192e9f5a7ef4502b30a/server/page/client.go#L28
But I don't know how it could be changed.
