### ISSUE TITLE
Deploy flet app on Kubernetes cluster - deploy to my_k8scluster.com/{myflet_app}/

### ISSUE THREAD

**Issue by R-fred** [flet-dev/flet#858]
**Description**
Internally, we run our applications on a Kubernetes Cluster. I tried to run a flet app on the cluster and have the following problem (as reported by my browser's dev tools):

`GET https://my_k8scluster.com/flutter.js net::ERR_ABORTED 404`
`GET https://my_k8scluster.com/icons/loading-animation.png`
`[SHEP] Site not supported: https://my_k8scluster.com/flettrial`
`Uncaught ReferenceError: _flutter is not defined`

Similarly, it cannot load the images required for the loading page.

This issue is similar to that described here: [https://github.com/pglet/pglet-python/issues/35](https://github.com/pglet/pglet-python/issues/35)

**Code example to reproduce the issue:**

I used the counter example with the `view=flet.WEB_BROWSER` and `port=8501` parameters set in the flet.app() function.

**Describe the results you received:**

The flet app is stuck on the loading page with only the alternate text 'Loading Image' being shown.

**Describe the results you expected:**

i would have expected the app to load without an issue

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Version: 0.3.2
```

**Operating system**:

Linux

**Additional environment details:**
docker file
Kubernetes cluster

**Comment by FeodorFitsner** [comment]
So, Flet web app is installed (mapped) to `/flettrial`, not root?

**Comment by R-fred** [comment]
> So, Flet web app is installed (mapped) to `/flettrial`, not root?

yes.

**Comment by FeodorFitsner** [comment]
So, you would need to update `<base href="$FLUTTER_BASE_HREF">` inside Flet's `index.html` to `<base href="/flettrial">`.

You need to do "assets" folder approach as shown in [this example](https://github.com/flet-dev/examples/tree/main/python/apps/custom-loading-image). You can take an original `index.html` from [here](https://github.com/flet-dev/flet/blob/main/client/web/index.html), update its `<base>` and put updated `index.html` to the root of `assets`.

Let me know if that worked.

**Comment by R-fred** [comment]
I tried it, and at least in my first try, it did not work.

**Here is the output when running the same code on my laptop - running on windows - :**

![FletTrial_Desktop_Console](https://user-images.githubusercontent.com/8479604/212421357-2d728c49-883b-4150-adbd-4c33b9f50c80.JPG)
![FletTrial_Desktop_Network](https://user-images.githubusercontent.com/8479604/212421361-f7dd96d4-e30c-43fb-8f96-4bf65d264ff6.JPG)

**Here is the result on K8S - running on linux - (without assets dir):**

![FletTrial_K8S_Console](https://user-images.githubusercontent.com/8479604/212421418-3f3075ee-bb80-4fff-8ba3-6dfed0f2a430.JPG)
![FletTrial_K8S_Network](https://user-images.githubusercontent.com/8479604/212421420-b522b913-af32-4531-9436-87524326f1aa.JPG)

One of the issues with the K8S environment, is that the app can't seem to load flutter.js to start with.

**Note:** I tried to do the assets fix on my desktop and it worked, the app starts directly where it should. The only caveat is that  the address returned is this: `http://127.0.0.1:8501/flettrial#/`. Note the added `#`.

**Comment by FeodorFitsner** [comment]
This is the solution: https://flet.dev/blog/flet-for-fastapi
