### ISSUE TITLE
 TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by hro-ict** [flet-dev/flet#862]
When I run the code below, I get the following error:
    all_params = set(params)
TypeError: unhashable type: 'list'

CODE:
import flet as ft

def main(page: ft.Page):
    # add/update controls on Page
    pass

ft.app(target=main)
****

**Comment by ndonkoHenri** [comment]
Try looking at the Hello world example in this section : https://flet.dev/docs/guides/python/getting-started#controls
Let me know if the error persists.

**Comment by iron3oxide** [comment]
You can't add lists to a set in python, so if `params` contains a list, your code will fail with the error you mentioned. Try using a tuple instead. This is definitely not a flet issue, so please close it or convert it into a discussion if you need further help fixing it.

**Comment by ndonkoHenri** [comment]
I didn't even take good attention at what was up there. I was just looking at the code, and noticed nothing was being added to the page, hence recommended a Hello world example.

**Comment by ilisien** [comment]
I am having a similar error using Python 3.9, even with the Hello world example; when I update to 3.11, the error appears to disappear. Perhaps "Flet requires Python 3.7 or above" on the website is outdated?

**Comment by ndonkoHenri** [comment]
Strange though.

**Comment by ndonkoHenri** [comment]
Issue still occurs with latest release?
