### ISSUE TITLE
line152 in flet.cli.commands.run.py

### ISSUE THREAD

**Issue by Lee7goal** [flet-dev/flet#863]
hello  
there have something wrong with flet/cli/commands/run.py
if my path have chinese str,there will get a UnicodeDecodeError,
you can fix this bug in next version
i just change this code like:
            try:
                line = line.decode("utf-8").rstrip("\r\n")
            except UnicodeDecodeError:
                line = line.decode("gbk").rstrip("\r\n")

**Comment by FeodorFitsner** [comment]
Thanks for pointing that out!

I understand "gbk" works for Chinese only, no?

**Comment by Lee7goal** [comment]
yes use gbk can parse chinese

**Comment by ndonkoHenri** [comment]
...
@FeodorFitsner I think you forgot to try this.

**Comment by FeodorFitsner** [comment]
Could you please try encoding fix with pre-release version of Flet module:

```
pip install flet --upgrade --pre
```

and let me know if that worked. Thanks!

**Comment by Lee7goal** [comment]
It's work!!
Thank You
