### ISSUE TITLE
The web loads too slowly due to requests for resources such as Google

### ISSUE THREAD

**Issue by Inotart** [flet-dev/flet#874]
**Please Describe The Problem To Be Solved**

Google and other websites are too slow to access fonts or can't download fonts causing garbled web interface issues, I tried to change the download address from the source level but couldn't find it. Want to add a proxy feature, such as GitHub.
Google is not accessible in some areas, which can cause problems with pages not displaying fonts correctly

**(Optional): Suggest A Solution**

Add a function or function that sets the proxy URL globally.

**Comment by huangshishangjiang** [comment]
I think this suggestion is great. I encountered the problem that the offline environment js could not be loaded. If flex can support local sources, it will help solve similar problems.

**Comment by Inotart** [comment]
你好,我目前不在，如果你只是看到论坛邮件就不用回复了

**Comment by FeodorFitsner** [comment]
Let's keep this issue only and close https://github.com/flet-dev/flet/issues/873

**Comment by FeodorFitsner** [comment]
We need a solution from Flutter. Once there is one we will implement it in Flet.
