### ISSUE TITLE
ENTER key does not fire on_submit on TextField

### ISSUE THREAD

**Issue by mnesarco** [flet-dev/flet#876]
**Description**

When the user presses `RETURN`, on_submit is fired, but when the user presses `INTRO` (ENTER), it is not fired.

**Describe the results you expected:**

`ENTER` should fire `TextField.on_submit`

**Flet version**:

```
Version: 0.3.2
```

**Operating system**:

Linux

**Comment by FeodorFitsner** [comment]
What is `INTRO` key?

**Comment by mnesarco** [comment]
The ENTER key in the numeric pad (marked in green) known as INTRO (in spanish :D)
![image](https://user-images.githubusercontent.com/1087317/212554432-42251d84-3e33-4883-ac2c-e7173abee57b.png)

When I pres the big one (marked in red) on_submit is fired, but when I press the one maked in green it is not.

**Comment by ndonkoHenri** [comment]
I am just from trying it works as expected.

Try this code:
```python
import flet as ft


def main(page: ft.Page):
    def textbox_submit(e):
        page.add(ft.Text("I work!"))
        page.update()

    tb = ft.TextField(
        label="Textbox with 'submit' event:",
        on_submit=textbox_submit
    )

    page.add(tb)


ft.app(
    target=main,
    # view=ft.WEB_BROWSER
)
```
Maybe your keyboard key is bad. To be sure, try the above code using another PC.

**Comment by mnesarco** [comment]
Actually it is a conflict with the `ft.DataTable` selection:

```python
import flet as ft

def main(page: ft.Page):
    page.title = "ENTER vs RETURN"
    page.theme_mode = ft.ThemeMode.DARK
    page.padding = 50

    table = ft.DataTable(columns=[ft.DataColumn(ft.Text("Column1"))],
        rows=[
            ft.DataRow([
                ft.DataCell(ft.TextField(on_submit=lambda e: print("on_submit fired"))),
            ],
            on_select_changed=lambda e: 0)
        ]
    )

    page.add(table)
    page.update()

ft.app(target=main)


```

Try this code to reproduce the problem.

**Comment by ndonkoHenri** [comment]
Oops, I missed your last message.
I just tried your code, and the both key work. Try on a different computer.

**Comment by mnesarco** [comment]
You insist in a hardware failure, but it is not. 
Don't worry about this Issue, I will close it as it is not critical for me right now and nobody else have a similar problem.
