### ISSUE TITLE
is there something like Responsive column?

### ISSUE THREAD

**Issue by B-2U** [flet-dev/flet#877]
hello sir, i was working on my app that create a container that fill the whole window, 
and i found `ResponsiveRow` to deal with the width changing, but after few days of searching in doc I still can't find a way to react the window height change
![image](https://user-images.githubusercontent.com/82710122/212489027-4eb451c8-c76c-45d1-8cda-602b2bbbc81e.png)
![image](https://user-images.githubusercontent.com/82710122/212489029-f5b4ec0a-3be1-4a4b-b50f-13bd4ef4e57e.png)

**Comment by JorgeAlvarez21** [comment]
I don't think there is a responsive Column component. But you could probably put together something similar with a few simple lines of code, my approach would be to use a container to act as a html div and set different breakpoints for the height, as you scale down or up your **main window**, use the EventHandler ```page.on_resize```  to call your function that will adjust the container's new height.

**Comment by B-2U** [comment]
> I don't think there is a responsive Column component. But you could probably put together something similar with a few simple lines of code, my approach would be to use a container to act as a html div and set different breakpoints for the height, as you scale down or up your **main window**, use the EventHandler `page.on_resize` to call your function that will adjust the container's new height.

thx for your advice, i made it with `page.on_resize`, but the event only trigger when i finished window resizing(left my LMB), unlike the instant width change with `ResponsiveRow`
Is there any way better? or its the limit, thx for your help still

**Comment by ndonkoHenri** [comment]
There isn't.
@FeodorFitsner do you think it could be added?
