### ISSUE TITLE
Feature Request: IndexedStack

### ISSUE THREAD

**Issue by roniemartinez** [flet-dev/flet#878]
**Please Describe The Problem To Be Solved**

https://api.flutter.dev/flutter/widgets/IndexedStack-class.html

**Comment by FeodorFitsner** [comment]
Thanks for the suggestion!

In the meantime you could implement that with a regular stack, right?

**Comment by roniemartinez** [comment]
I have no luck implementing this with Stack because children cannot expand.  I was able to temporarily use a Column by hiding other children and showing one at time but this does not preserve the scroll position.

**Comment by roniemartinez** [comment]
@FeodorFitsner Thanks for marking this issue as complete.

But I am not really sure where is this completed or documented?
