### ISSUE TITLE
If we use Flutter and run Flet as a widget, how to pass data to Flet ?

### ISSUE THREAD

**Issue by Francois-Belanger** [flet-dev/flet#881]
Please can you suggest a way to pass data between Flutter and Flet ?  I need BLE for iOS and Android, so I need to communicate with Flutter.

using: https://pub.dev/packages/flet

Thanks
Francois

**Comment by FeodorFitsner** [comment]
What is BLE?

**Comment by Francois-Belanger** [comment]
Bluetooth :-)

**Comment by Francois-Belanger** [comment]
Would it be possible to create a web socket server in Flutter and connect to it from Flet ?

Thanks for the help
