### ISSUE TITLE
FilePicker not obeying initial_directory

### ISSUE THREAD

**Issue by riebecj** [flet-dev/flet#884]
**Description**

When utilizing multiple `FilePicker`'s, each with a different `initial_directory`, the provided directory arguments at function call time are not obeyed. This prevents the ability from using different initial directories depending on the `FilePicker` being called. 

**Code example to reproduce the issue:**

```python
import os.path

import flet as ft

dir1 = "C:\\Users"
dir2 = "C:\\Windows"


def main(page: ft.Page):
    def update_dir(event: ft.FilePickerResultEvent):
        global dir1, dir2
        if event.path:
            dir1 = event.path
        elif event.files:
            for file in event.files:
                dir2 = os.path.dirname(file.path)

    dir_picker = ft.FilePicker(on_result=update_dir)
    file_picker = ft.FilePicker(on_result=update_dir)

    page.add(
        ft.ElevatedButton(
            "Pick Directory",
            on_click=lambda _: dir_picker.get_directory_path(
                dialog_title="File Selector",
                initial_directory=dir1
            )
        ),
        ft.ElevatedButton(
            "Pick Files",
            on_click=lambda _: file_picker.pick_files(
                dialog_title="File Selector",
                allow_multiple=True,
                initial_directory=dir2
            )
        )
    )
    page.overlay.extend([dir_picker, file_picker])
    page.update()


ft.app(target=main)
```

**Describe the results you received:**

Using the above code example, if you click the `Pick Files` button and select a music file or two from `C:\Users\<USERNAME>\Music`, when you click the `Pick Directory` button it opens a dialog in  `C:\Users\<USERNAME>\Music`, not in the provided `initial_directory` argument of `C:\Users`.

**Describe the results you expected:**

I expect the `FilePicker` dialogs to start in the `initial_directory` provided to the function call.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.3.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author:
Author-email: Appveyor Systems Inc. <hello@flet.dev>
License: MIT
Location: c:\users\casey\appdata\local\programs\python\python310\lib\site-packages
Requires: beartype, oauthlib, packaging, repath, requests, watchdog, websocket-client
Required-by:
```

**Operating system**:

Windows 10 Home 22H2 19045.2486

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Apparently, `initial_directory` is not supported in `get_directory_path` on Windows:
https://pub.dev/documentation/file_picker/latest/file_picker/FilePicker/getDirectoryPath.html
https://github.com/miguelpruivo/flutter_file_picker/pull/953

We need to update docs.

**Comment by FeodorFitsner** [comment]
Looks like there was an attempt to implement initial directory on Windows: https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/src/windows/file_picker_windows.dart#L128-L140

I'd help with that, but I'm not a C++ expert - there is some real COM wizardry.

**Comment by riebecj** [comment]
That's unfortunate. I can live with it for now. It's more of a UX thing than primary functionality for me. I save a user-selected directory in an INI config, which pre-populates the `TextField` at program launch. It would just be nice to start from that directory if the user wants to change it.

**Comment by FeodorFitsner** [comment]
OK, let's close this issue for now and when there is a solution in FilePicker Flutter component we'll revisit it again.
