### ISSUE TITLE
Running on the M1 chip will prompt error

### ISSUE THREAD

**Issue by Skyllqq** [flet-dev/flet#890]
**this simple program running on the M1 chip, Will show all_params = set(params)
TypeError: unhashable type: 'list', this program fails to run**

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.title = "My first App"
    page.add(ft.ElevatedButton(text="click"))


ft.app(target=main)

```

**
all_params = set(params)
TypeError: unhashable type: 'list'
**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Operating system**:

**Additional environment details:**

**Comment by kkinder** [comment]
FWIW, I'm not able to reproduce this on my M1 Max MacBook Pro running Ventura.
