### ISSUE TITLE
how to achieve a header bar draggable in parent node but undraggable in child node

### ISSUE THREAD

**Issue by zrr1999** [flet-dev/flet#896]
**Please Describe The Problem To Be Solved**
now
![iShot_2023-01-17_19 31 22](https://user-images.githubusercontent.com/46243324/212888345-62fbde57-1f58-4c56-b997-402acd34b1df.gif)

expected
![iShot_2023-01-17_19 03 06](https://user-images.githubusercontent.com/46243324/212882860-bf9b0a59-e3b2-4368-9d1a-2611665ec7bf.gif)
**(Optional): Suggest A Solution**

**Comment by FeodorFitsner** [comment]
https://flet.dev/docs/controls/windowdragarea
