### ISSUE TITLE
Platform channels alternative ?

### ISSUE THREAD

**Issue by pacifio** [flet-dev/flet#90]
flet is good but how do we call native functions with it
ig we should look into `plyer` library
https://github.com/kivy/plyer
is there any plans to make an API layer library for flet specifically ?

**Comment by FeodorFitsner** [comment]
Yes, we are going to have a common layer to make mobile APIs available in a Flet program. They will be implemented in Flutter though using respective packages.

I'm closing this issue which looks more like a discussion. If you'd like to continue on that topic feel free to [start a new discussion](https://github.com/flet-dev/flet/discussions).
