### ISSUE TITLE
*How to integrate Google Ads in the Flet App*

### ISSUE THREAD

**Issue by kmranrg** [flet-dev/flet#902]
**How to integrate Google Ads in the Flet App**

Hello Flet Team,

I am getting many concerns from the users regarding the integration of Google Ads in the Flet App, so on their behalf I am raising this case, please provide your assistance on this.

Thanks,
Anurag

**Comment by ndonkoHenri** [comment]
Duplicate of https://github.com/flet-dev/flet/issues/286

**Comment by kmranrg** [comment]
Hello @ndonkoHenri -

Thanks for your quick response!

I am good to close this case.

Regards,
Anurag
