### ISSUE TITLE
Is it pure python?

### ISSUE THREAD

**Issue by mn9142001** [flet-dev/flet#91]
I'm trying to understand flet, is it just python code, if I wanted to send request should I use normal python request lib or something else

Same for cameras, file upload and converting to apk.
The docs is missing alot

**Comment by KranzKrone** [comment]
I am also missing the Same information. What will BE happen with a SQLite Database on PWA?

**Comment by FeodorFitsner** [comment]
Yes, it's pure Python.

File uploads, camera, accelerometer would be part of Flet client written in Flutter with Python interface.

**Comment by goyalyashpal** [comment]
> camera
\- @FeodorFitsner at https://github.com/flet-dev/flet/issues/91#issuecomment-1193200781

does flet have any widget to connect to camera live feed?
