### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by mn9142001** [flet-dev/flet#92]
is there any way to implement hot reload? the development is really slow this way

Implementation notes:
https://pdm.fming.dev/latest/pyproject/pep621/#console-scripts
https://api.flutter.dev/flutter/dart-io/FileSystemEntity/watch.html
https://github.com/dart-lang/sdk/issues/30918
https://api.dart.dev/stable/2.17.6/dart-io/Process-class.html

**Comment by DanielRios549** [comment]
There is a package for this called `jurigged`, but unfortunately, it does not seems to work, it prints in the terminal that the file was changed but did not update the UI

**Comment by FeodorFitsner** [comment]
Can you try this solution: https://flet.dev/docs/guides/python/hot-reload/

**Comment by DanielRios549** [comment]
@FeodorFitsner This `watchexec` works for me, it closes and reopens the application, not the perfect world but it is ok for now. I'm entering the desktop and mobile development right now (just studying), isn't there something more "perfect" for desktop hot reaload like `ViteJS`?

**Comment by FeodorFitsner** [comment]
Hot reload has been just released and documented here: https://flet.dev/docs/guides/python/hot-reload

**Comment by ResetPress** [comment]
This is very helpful. Thank you for implementing.
