### ISSUE TITLE
Cleaning up tooltips

### ISSUE THREAD

**Issue by Deathdadev** [flet-dev/flet#920]
The tooltip class is already pretty customizable (flet.Tooltip on its own), but the inbuilt tooltips for containers, text, etc are lacking customization. Simple fix: instead of having a string for the inbuilt tooltip, parse the actual ft.Tooltip().

I'm not sure if this ones possible, but maybe allowing more options of content for tooltip such as images, buttons and icons, and to change the width of tool tip.

**Comment by ndonkoHenri** [comment]
> Simple fix: instead of having a string for the inbuilt tooltip, parse the actual ft.Tooltip().

Simple fix: set the `content` prop of your tooltip control to your control. See this example for help: https://flet.dev/docs/controls/tooltip#tooltip-with-a-custom-decoration

By the way, the [`tooltip` property is of type string](https://api.flutter.dev/flutter/material/IconButton/tooltip.html).
I also noticed Flutter's `Tooltip` widget had no `width` property.

A suggestion I am just from having, which I will like @FeodorFitsner to implement is a way to [programmatically show the tooltip](https://api.flutter.dev/flutter/material/Tooltip-class.html#material.Tooltip.4).

**Comment by Deathdadev** [comment]
Thanks for the reply. Is there any way to embed images or buttons in tooltips or possibly a way to make a custom tooltip to do that (e.g. onhover of a container, somehow reveal a hidden container)?

**Comment by ndonkoHenri** [comment]
> Is there any way to embed images or buttons in tooltips 

I think, Tooltips are not meant for that.


> a way to make a custom tooltip to do that (e.g. onhover of a container, somehow reveal a hidden container)?

I think, Tooltips are not meant for that too. Use a [`GestureDetector`](https://flet.dev/docs/controls/gesturedetector) instead. It has an [`on_hover`](https://flet.dev/docs/controls/gesturedetector#on_hover) which you can use to reveal your 'hidden container'.
If you need it to show a custom Tooltip, you could then insert your GestureDetector in the [`content`](https://flet.dev/docs/controls/tooltip#content) property of the Tooltip object.
