### ISSUE TITLE
How to change the value of a TextField in the on_change event

### ISSUE THREAD

**Issue by Code4SAFrankie** [flet-dev/flet#94]
In kivy I can subclass the `TextInput` widget to change the behaviour to always make the value uppercase and one letter long by doing the following:

```
class MyTextInput(TextInput):
    def __init__(self, **kwargs):
        super(MyTextInput, self).__init__(**kwargs)

    def keyboard_on_textinput(self, window, text):
        """Upper case and always one letter only."""
        self.text = text.upper()

```
Can something similar be done in flet? I tried the following which did not work:

```
def main(page: Page):
    def cw_textbox_changed(e):
        e.control.value = e.control.value[-1:]
        page.update()

    c1 = Container(
                content=TextField(
                    value="W",
                    label=None,
                    hint_text=None,
                    text_align="center",
                    border="none",
                    content_padding=None,
                    data=d,
                    on_change=cw_textbox_changed,
                ),
    )
```

Not sure if `c1.value = e.control.value[-1:]` would do the trick, since I have many `TextField` controls and only the one event handler function.

**Comment by FeodorFitsner** [comment]
Yep, it won't work like that and even if it would the experience won't be OK-ish because of latency.

What if we just add built-in `capitalize` property to TextField?

**Comment by Code4SAFrankie** [comment]
Built-in `capitalize`, `min_value_length` and `max_value_length` would be nice. Thanks.

**Comment by FeodorFitsner** [comment]
Closing this issue in favour of:
https://github.com/flet-dev/flet/issues/100
https://github.com/flet-dev/flet/issues/101
