### ISSUE TITLE
Be able to copy text across Markdown Formats

### ISSUE THREAD

**Issue by regstuff** [flet-dev/flet#942]
I have a fulltext search application, so when a word in a document matches the search term, it will be bolded. I'm using Markdown for this (because Text doesn't support formatting). The issue is I am unable to copy paste the whole paragraph if it is in markdown. The copy paste seems to break due to formatting, and I can only copy chunks that are in the same Markdown format. 

Any way around this? I know I could create a copy button, but that will only allow them to copy the whole document. It won't help when they only want to copy a small chunk or sentence.

**Comment by ndonkoHenri** [comment]
You can use a `SelectionArea`:
```
def main(page: ft.Page):
    page.scroll = "auto"
    page.add(
        ft.SelectionArea(
            content=ft.Markdown(
                "Your selectable markdown here",
                extension_set=ft.MarkdownExtensionSet.GITHUB_WEB,
                on_tap_link=lambda e: page.launch_url(e.data),
                on_tap_text=lambda e: print("Text was tapped"),
                on_selection_change=print,
                img_error_content=ft.ProgressRing(),
            )
        )
    )


ft.app(target=main)
```
