### ISSUE TITLE
emoji/emoticons support for Static website when deployed with `flet publish`

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#957]
**Code:**
```python
import flet as ft

def main(page: ft.Page):
    page.add(ft.Text("Emoji: 📸 | 😂 | 📝 | 😉"))

ft.app(target=main)
```

**ACTUAL BUG:**

![image](https://user-images.githubusercontent.com/98978078/215520209-609b82f2-7ea7-478f-8793-4b4146813004.png)
![image](https://user-images.githubusercontent.com/98978078/215520241-99ada8ec-918c-411e-9850-22779e17c09d.png)

**Comment by FeodorFitsner** [comment]
Closing as dup of https://github.com/flet-dev/flet/issues/1265
