### ISSUE TITLE
how to use multi pages ??

### ISSUE THREAD

**Issue by abdallah-baraka** [flet-dev/flet#97]
i know you have completed  Navigation and Routing #95 
so how can i use it ??

**Comment by FeodorFitsner** [comment]
This is the guide: https://flet.dev/blog/navigation-and-routing

**Comment by abdallah-baraka** [comment]
thanks

**Comment by abulka** [comment]
Any way to change the transition effect for multi-page apps  - the current big sideways slide is a bit dramatic for more conservative apps!

**Comment by FeodorFitsner** [comment]
@abulka are you testing on macOS?

**Comment by abulka** [comment]
Yes - how did you know!?

**Comment by FeodorFitsner** [comment]
Noticed while testing on macOS. On Windows it's from bottom to up animation, but on macOS it's the same as iOS - sliding from the right to the left.

**Comment by saurabhwadekar** [comment]
@abdallah-baraka 
you can try this i think it will be easy for you.
[flet_route](https://github.com/saurabhwadekar/flet_route)
