### ISSUE TITLE
Changing app host/IP binding

### ISSUE THREAD

**Issue by iforvard** [flet-dev/flet#98]
How to change host address other than 127.0.0.1?

example
`flet.app(target=main, host="192.168.1.1")`

**Comment by FeodorFitsner** [comment]
Flet server is listening on all NIC IP addresses by default. You can just change opened URL into 192.168.0.1 and it should work.

**Comment by FeodorFitsner** [comment]
But I agree adding `host` parameter would be natural. Let's keep this item opened, so I can fix it.

**Comment by Hrishikesh46779** [comment]
I changed 127.0.0.1 to 192.168.1.109.
But it shows Exception: Could not connected to Flet server in 30 seconds.
I want to run it on other Ip address than 127.0.0.1 so I can access the page with other devices.
I have done this
ft.app(target=main,  host="192.168.1.109", view=ft.WEB_BROWSER)
