### ISSUE TITLE
Add expand property to datatable layout

### ISSUE THREAD

**Issue by Khanhlinhdang** [flet-dev/flet#988]
I want to create a app using datatable layout, but it can apply properties expand.

**Comment by Khanhlinhdang** [comment]
How to replace Flet app Icon by a custom?

**Comment by Khanhlinhdang** [comment]
is it possible to embed pyside6 or pyqt6 in a flet app?

**Comment by FeodorFitsner** [comment]
but Flet *is* replacement for PySide6 🤔

**Comment by Khanhlinhdang** [comment]
Ofcouse yes, sorry I forgot it. FLET is awesome standalone framwork to
create GUI in python. It is just need more tutorial and guidance on how to
arrange code in folders, for example  using multi page, layout, input,
display controls in a project.

Vào 3:19, Th 3, 7 thg 2, 2023 Feodor Fitsner ***@***.***> đã
viết:

**Comment by ndonkoHenri** [comment]
@Khanhlinhdang, can you detail on this issue?
