### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Jinder2050** [flet-dev/flet#989]
I am using flet library, but i get this error. The example in the image, I took it directly from flet documentation

![imagen_2023-02-06_181739891](https://user-images.githubusercontent.com/76700460/217109036-06ec94ad-af8d-45bd-9129-e4a548434fce.png)

**Comment by FeodorFitsner** [comment]
Please install the latest 0.4.0 version of Flet package and give another try:

```
pip install flet --upgrade
```
