### ISSUE TITLE
Cannot override built-in flet icon in title bar when running application (Windows) -- no packaging

### ISSUE THREAD

**Issue by flamesjames** [flet-dev/flet#991]
**Description**

I haven't been able to find documentation or examples on how to override the built-in flet icon in the window title bar when running my python application. I've tried multiple methods from threads found online [(1)](https://github.com/flet-dev/flet/discussions/741) and [(2)](https://github.com/flet-dev/flet/discussions/99), including one where a maintainer described a method that seemed to work for them but no luck with either. I went thru the `flet` discussion boards as well and couldn't find any answers to this issue.

To be clear, creating an `assets/icons` directory and adding my own `favicon.png` did not work. I was still left with the default flet icon. Is there any easy way to override this for any time you run the application (without packaging)?

**Describe the results you received:**

<img width="174" alt="image" src="https://user-images.githubusercontent.com/40143723/217246773-4395db87-1f0d-4399-ac3b-94d1c08b555b.png">

**Describe the results you expected:**

My own defined app icon located within my `assets` directory.

**Additional information you deem important (e.g. issue happens only occasionally):**
Should work running app via command line or IDE.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.3.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: 
Author-email: Appveyor Systems Inc. <hello@flet.dev>
License: MIT
Requires: beartype, oauthlib, packaging, repath, requests, watchdog, websocket-client
```

**Operating system**: 

Windows 11 Home

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Desktop app icon can be customized on packaging phase only: https://flet.dev/docs/guides/python/packaging-desktop-app#customizing-package-icon

**Comment by clstaudt** [comment]
@FeodorFitsner  Can we turn this into a feature request?

**Comment by flamesjames** [comment]
> @FeodorFitsner Can we turn this into a feature request?

I also think that this would be valuable

**Comment by eeintech** [comment]
Hello there, I support this request as distributing through PyPI as wheel package isn't compatible with packaging using `PyInstaller`/`flet pack` option.

I need to look for workarounds for my apps: https://github.com/sparkmicro/Ki-nTree/issues/124
But I'd rather get this icon to be showing at runtime if possible, so much easier to distribute!

**Comment by eeintech** [comment]
Moreover, the icon support appears to be only for Windows and MacOS?

I get this in the PyInstaller output when running `flet pack app.py --icon logo.png` command:
``` shell
WARNING: Ignoring icon; supported only on Windows and macOS!
```

**Comment by ndonkoHenri** [comment]
To change the icon of your app without having to package, use [`page.window.icon`](https://flet.dev/docs/reference/types/window#icon), and specify a full path to the `.ico` icon file.
It works on Windows only for now.

**Comment by eeintech** [comment]
@ndonkoHenri Awesome thanks for the update!
