### ISSUE TITLE
Linux/macOS: "Address already in use" error on app hot reload

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#997]
### Discussed in https://github.com/flet-dev/flet/discussions/995

<div type='discussions-op-text'>

<sup>Originally posted by **bobwatcherx** February  7, 2023</sup>
I got an error when I want to save and reload the application.  even though yesterday was normal.  is there anything that needs to be fixed

info 
flet               0.4.0
</div>

**Comment by FeodorFitsner** [comment]
I don't have a proper Linux installation and I'm trying to reproduce on WSL for Windows 11, but no avail.

Could you please enable logging in your program and give me a log with what's going on when hot reload occurs:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by ChristianKranemann** [comment]
I can confirm this problem also occurs since version 0.40 on macOS 13.1

```
INFO:root:Starting up TCP server on ('localhost', 60994)
Traceback (most recent call last):
  File "/Path/To/Project/widgets/line/__init__.py", line 292, in <module>
    ft.app(target=main, view=ft.FLET_APP)
  File "/Path/To/Project/widgets/.venv/lib/python3.11/site-packages/flet/flet.py", line 82, in app
    __app_sync(
  File "/Path/To/Project/widgets/.venv/lib/python3.11/site-packages/flet/flet.py", line 111, in __app_sync
    conn = __connect_internal_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Path/To/Project/widgets/.venv/lib/python3.11/site-packages/flet/flet.py", line 323, in __connect_internal_sync
    conn.connect()
  File "/Path/To/Project/widgets/.venv/lib/python3.11/site-packages/flet/sync_local_socket_connection.py", line 46, in connect
    self.__sock.bind(server_address)
OSError: [Errno 48] Address already in use
```

**Comment by ChristianKranemann** [comment]
Some additional information: If i try to force UDS with the `-p 0` flag a new url is used but no connection is established

```
INFO:root:Starting up UDS server on /var/folders/s_/v7nwnyf90yx7ybmy651wrw0r0000gn/T/tZNMqiSaXb
DEBUG:root:Waiting for a client connection
INFO:root:Connected to Flet app and handling user sessions...
```

hangs afterwards. 

The original server creation message is 
```
INFO:root:Starting up UDS server on /var/folders/s_/v7nwnyf90yx7ybmy651wrw0r0000gn/T/pFkpNmsnSZ
DEBUG:root:Waiting for a client connection
INFO:root:Connected to Flet app and handling user sessions...
DEBUG:root:Connection from 
```

**Comment by FeodorFitsner** [comment]
Yep, I've been able to reproduce it on macOS. Will try to figure out a UDS thing too.

**Comment by ndonkoHenri** [comment]
strange..
that `FLET_APP` is the default

**Comment by FeodorFitsner** [comment]
The issue has been fixed. You can try it with Flet pre-release: `pip install flet --upgrade --pre`.

Let me know how that worked.

**Comment by ChristianKranemann** [comment]
Hey @FeodorFitsner 

works as expected. Thanks! Really enjoy using flet.
